class AquaBottleRunner {
	public static void main(String[] args) {

		AquaBottle a1 = new AquaBottle();
		a1.productId = 101;
		a1.brandName = "Sample1";
		a1.material = "Sample1";
		a1.color = "Sample1";
		a1.capacity = 11.0;
		a1.price = 11.0;
		a1.isInsulated = false;
		a1.isAvailable = false;
		a1.manufacturingDate = "Sample1";
		a1.expiryDate = "Sample1";
		a1.bottleType = "Sample1";
		a1.lidType = "Sample1";
		a1.height = 11.0;
		a1.isEcoFriendly = false;
		a1.countryOfOrigin = "Sample1";
		a1.warrantyMonths = 101;
		a1.packagingType = "Sample1";
		a1.weight = 11.0;
		a1.isLeakProof = false;
		a1.feature1 = "Sample1";
		a1.feature2 = "Sample1";
		a1.feature3 = "Sample1";
		a1.isPortable = false;
		a1.isReusable = false;
		a1.rating = 101;

		System.out.println("----- AquaBottle 1 -----");
		System.out.println("productId: " + a1.productId);
		System.out.println("brandName: " + a1.brandName);
		System.out.println("material: " + a1.material);
		System.out.println("color: " + a1.color);
		System.out.println("capacity: " + a1.capacity);
		System.out.println("price: " + a1.price);
		System.out.println("isInsulated: " + a1.isInsulated);
		System.out.println("isAvailable: " + a1.isAvailable);
		System.out.println("manufacturingDate: " + a1.manufacturingDate);
		System.out.println("expiryDate: " + a1.expiryDate);
		System.out.println("bottleType: " + a1.bottleType);
		System.out.println("lidType: " + a1.lidType);
		System.out.println("height: " + a1.height);
		System.out.println("isEcoFriendly: " + a1.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a1.countryOfOrigin);
		System.out.println("warrantyMonths: " + a1.warrantyMonths);
		System.out.println("packagingType: " + a1.packagingType);
		System.out.println("weight: " + a1.weight);
		System.out.println("isLeakProof: " + a1.isLeakProof);
		System.out.println("feature1: " + a1.feature1);
		System.out.println("feature2: " + a1.feature2);
		System.out.println("feature3: " + a1.feature3);
		System.out.println("isPortable: " + a1.isPortable);
		System.out.println("isReusable: " + a1.isReusable);
		System.out.println("rating: " + a1.rating);


		AquaBottle a2 = new AquaBottle();
		a2.productId = 102;
		a2.brandName = "Sample2";
		a2.material = "Sample2";
		a2.color = "Sample2";
		a2.capacity = 12.0;
		a2.price = 12.0;
		a2.isInsulated = true;
		a2.isAvailable = true;
		a2.manufacturingDate = "Sample2";
		a2.expiryDate = "Sample2";
		a2.bottleType = "Sample2";
		a2.lidType = "Sample2";
		a2.height = 12.0;
		a2.isEcoFriendly = true;
		a2.countryOfOrigin = "Sample2";
		a2.warrantyMonths = 102;
		a2.packagingType = "Sample2";
		a2.weight = 12.0;
		a2.isLeakProof = true;
		a2.feature1 = "Sample2";
		a2.feature2 = "Sample2";
		a2.feature3 = "Sample2";
		a2.isPortable = true;
		a2.isReusable = true;
		a2.rating = 102;

		System.out.println("----- AquaBottle 2 -----");
		System.out.println("productId: " + a2.productId);
		System.out.println("brandName: " + a2.brandName);
		System.out.println("material: " + a2.material);
		System.out.println("color: " + a2.color);
		System.out.println("capacity: " + a2.capacity);
		System.out.println("price: " + a2.price);
		System.out.println("isInsulated: " + a2.isInsulated);
		System.out.println("isAvailable: " + a2.isAvailable);
		System.out.println("manufacturingDate: " + a2.manufacturingDate);
		System.out.println("expiryDate: " + a2.expiryDate);
		System.out.println("bottleType: " + a2.bottleType);
		System.out.println("lidType: " + a2.lidType);
		System.out.println("height: " + a2.height);
		System.out.println("isEcoFriendly: " + a2.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a2.countryOfOrigin);
		System.out.println("warrantyMonths: " + a2.warrantyMonths);
		System.out.println("packagingType: " + a2.packagingType);
		System.out.println("weight: " + a2.weight);
		System.out.println("isLeakProof: " + a2.isLeakProof);
		System.out.println("feature1: " + a2.feature1);
		System.out.println("feature2: " + a2.feature2);
		System.out.println("feature3: " + a2.feature3);
		System.out.println("isPortable: " + a2.isPortable);
		System.out.println("isReusable: " + a2.isReusable);
		System.out.println("rating: " + a2.rating);


		AquaBottle a3 = new AquaBottle();
		a3.productId = 103;
		a3.brandName = "Sample3";
		a3.material = "Sample3";
		a3.color = "Sample3";
		a3.capacity = 13.0;
		a3.price = 13.0;
		a3.isInsulated = false;
		a3.isAvailable = false;
		a3.manufacturingDate = "Sample3";
		a3.expiryDate = "Sample3";
		a3.bottleType = "Sample3";
		a3.lidType = "Sample3";
		a3.height = 13.0;
		a3.isEcoFriendly = false;
		a3.countryOfOrigin = "Sample3";
		a3.warrantyMonths = 103;
		a3.packagingType = "Sample3";
		a3.weight = 13.0;
		a3.isLeakProof = false;
		a3.feature1 = "Sample3";
		a3.feature2 = "Sample3";
		a3.feature3 = "Sample3";
		a3.isPortable = false;
		a3.isReusable = false;
		a3.rating = 103;

		System.out.println("----- AquaBottle 3 -----");
		System.out.println("productId: " + a3.productId);
		System.out.println("brandName: " + a3.brandName);
		System.out.println("material: " + a3.material);
		System.out.println("color: " + a3.color);
		System.out.println("capacity: " + a3.capacity);
		System.out.println("price: " + a3.price);
		System.out.println("isInsulated: " + a3.isInsulated);
		System.out.println("isAvailable: " + a3.isAvailable);
		System.out.println("manufacturingDate: " + a3.manufacturingDate);
		System.out.println("expiryDate: " + a3.expiryDate);
		System.out.println("bottleType: " + a3.bottleType);
		System.out.println("lidType: " + a3.lidType);
		System.out.println("height: " + a3.height);
		System.out.println("isEcoFriendly: " + a3.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a3.countryOfOrigin);
		System.out.println("warrantyMonths: " + a3.warrantyMonths);
		System.out.println("packagingType: " + a3.packagingType);
		System.out.println("weight: " + a3.weight);
		System.out.println("isLeakProof: " + a3.isLeakProof);
		System.out.println("feature1: " + a3.feature1);
		System.out.println("feature2: " + a3.feature2);
		System.out.println("feature3: " + a3.feature3);
		System.out.println("isPortable: " + a3.isPortable);
		System.out.println("isReusable: " + a3.isReusable);
		System.out.println("rating: " + a3.rating);


		AquaBottle a4 = new AquaBottle();
		a4.productId = 104;
		a4.brandName = "Sample4";
		a4.material = "Sample4";
		a4.color = "Sample4";
		a4.capacity = 14.0;
		a4.price = 14.0;
		a4.isInsulated = true;
		a4.isAvailable = true;
		a4.manufacturingDate = "Sample4";
		a4.expiryDate = "Sample4";
		a4.bottleType = "Sample4";
		a4.lidType = "Sample4";
		a4.height = 14.0;
		a4.isEcoFriendly = true;
		a4.countryOfOrigin = "Sample4";
		a4.warrantyMonths = 104;
		a4.packagingType = "Sample4";
		a4.weight = 14.0;
		a4.isLeakProof = true;
		a4.feature1 = "Sample4";
		a4.feature2 = "Sample4";
		a4.feature3 = "Sample4";
		a4.isPortable = true;
		a4.isReusable = true;
		a4.rating = 104;

		System.out.println("----- AquaBottle 4 -----");
		System.out.println("productId: " + a4.productId);
		System.out.println("brandName: " + a4.brandName);
		System.out.println("material: " + a4.material);
		System.out.println("color: " + a4.color);
		System.out.println("capacity: " + a4.capacity);
		System.out.println("price: " + a4.price);
		System.out.println("isInsulated: " + a4.isInsulated);
		System.out.println("isAvailable: " + a4.isAvailable);
		System.out.println("manufacturingDate: " + a4.manufacturingDate);
		System.out.println("expiryDate: " + a4.expiryDate);
		System.out.println("bottleType: " + a4.bottleType);
		System.out.println("lidType: " + a4.lidType);
		System.out.println("height: " + a4.height);
		System.out.println("isEcoFriendly: " + a4.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a4.countryOfOrigin);
		System.out.println("warrantyMonths: " + a4.warrantyMonths);
		System.out.println("packagingType: " + a4.packagingType);
		System.out.println("weight: " + a4.weight);
		System.out.println("isLeakProof: " + a4.isLeakProof);
		System.out.println("feature1: " + a4.feature1);
		System.out.println("feature2: " + a4.feature2);
		System.out.println("feature3: " + a4.feature3);
		System.out.println("isPortable: " + a4.isPortable);
		System.out.println("isReusable: " + a4.isReusable);
		System.out.println("rating: " + a4.rating);


		AquaBottle a5 = new AquaBottle();
		a5.productId = 105;
		a5.brandName = "Sample5";
		a5.material = "Sample5";
		a5.color = "Sample5";
		a5.capacity = 15.0;
		a5.price = 15.0;
		a5.isInsulated = false;
		a5.isAvailable = false;
		a5.manufacturingDate = "Sample5";
		a5.expiryDate = "Sample5";
		a5.bottleType = "Sample5";
		a5.lidType = "Sample5";
		a5.height = 15.0;
		a5.isEcoFriendly = false;
		a5.countryOfOrigin = "Sample5";
		a5.warrantyMonths = 105;
		a5.packagingType = "Sample5";
		a5.weight = 15.0;
		a5.isLeakProof = false;
		a5.feature1 = "Sample5";
		a5.feature2 = "Sample5";
		a5.feature3 = "Sample5";
		a5.isPortable = false;
		a5.isReusable = false;
		a5.rating = 105;

		System.out.println("----- AquaBottle 5 -----");
		System.out.println("productId: " + a5.productId);
		System.out.println("brandName: " + a5.brandName);
		System.out.println("material: " + a5.material);
		System.out.println("color: " + a5.color);
		System.out.println("capacity: " + a5.capacity);
		System.out.println("price: " + a5.price);
		System.out.println("isInsulated: " + a5.isInsulated);
		System.out.println("isAvailable: " + a5.isAvailable);
		System.out.println("manufacturingDate: " + a5.manufacturingDate);
		System.out.println("expiryDate: " + a5.expiryDate);
		System.out.println("bottleType: " + a5.bottleType);
		System.out.println("lidType: " + a5.lidType);
		System.out.println("height: " + a5.height);
		System.out.println("isEcoFriendly: " + a5.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a5.countryOfOrigin);
		System.out.println("warrantyMonths: " + a5.warrantyMonths);
		System.out.println("packagingType: " + a5.packagingType);
		System.out.println("weight: " + a5.weight);
		System.out.println("isLeakProof: " + a5.isLeakProof);
		System.out.println("feature1: " + a5.feature1);
		System.out.println("feature2: " + a5.feature2);
		System.out.println("feature3: " + a5.feature3);
		System.out.println("isPortable: " + a5.isPortable);
		System.out.println("isReusable: " + a5.isReusable);
		System.out.println("rating: " + a5.rating);


		AquaBottle a6 = new AquaBottle();
		a6.productId = 106;
		a6.brandName = "Sample6";
		a6.material = "Sample6";
		a6.color = "Sample6";
		a6.capacity = 16.0;
		a6.price = 16.0;
		a6.isInsulated = true;
		a6.isAvailable = true;
		a6.manufacturingDate = "Sample6";
		a6.expiryDate = "Sample6";
		a6.bottleType = "Sample6";
		a6.lidType = "Sample6";
		a6.height = 16.0;
		a6.isEcoFriendly = true;
		a6.countryOfOrigin = "Sample6";
		a6.warrantyMonths = 106;
		a6.packagingType = "Sample6";
		a6.weight = 16.0;
		a6.isLeakProof = true;
		a6.feature1 = "Sample6";
		a6.feature2 = "Sample6";
		a6.feature3 = "Sample6";
		a6.isPortable = true;
		a6.isReusable = true;
		a6.rating = 106;

		System.out.println("----- AquaBottle 6 -----");
		System.out.println("productId: " + a6.productId);
		System.out.println("brandName: " + a6.brandName);
		System.out.println("material: " + a6.material);
		System.out.println("color: " + a6.color);
		System.out.println("capacity: " + a6.capacity);
		System.out.println("price: " + a6.price);
		System.out.println("isInsulated: " + a6.isInsulated);
		System.out.println("isAvailable: " + a6.isAvailable);
		System.out.println("manufacturingDate: " + a6.manufacturingDate);
		System.out.println("expiryDate: " + a6.expiryDate);
		System.out.println("bottleType: " + a6.bottleType);
		System.out.println("lidType: " + a6.lidType);
		System.out.println("height: " + a6.height);
		System.out.println("isEcoFriendly: " + a6.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a6.countryOfOrigin);
		System.out.println("warrantyMonths: " + a6.warrantyMonths);
		System.out.println("packagingType: " + a6.packagingType);
		System.out.println("weight: " + a6.weight);
		System.out.println("isLeakProof: " + a6.isLeakProof);
		System.out.println("feature1: " + a6.feature1);
		System.out.println("feature2: " + a6.feature2);
		System.out.println("feature3: " + a6.feature3);
		System.out.println("isPortable: " + a6.isPortable);
		System.out.println("isReusable: " + a6.isReusable);
		System.out.println("rating: " + a6.rating);


		AquaBottle a7 = new AquaBottle();
		a7.productId = 107;
		a7.brandName = "Sample7";
		a7.material = "Sample7";
		a7.color = "Sample7";
		a7.capacity = 17.0;
		a7.price = 17.0;
		a7.isInsulated = false;
		a7.isAvailable = false;
		a7.manufacturingDate = "Sample7";
		a7.expiryDate = "Sample7";
		a7.bottleType = "Sample7";
		a7.lidType = "Sample7";
		a7.height = 17.0;
		a7.isEcoFriendly = false;
		a7.countryOfOrigin = "Sample7";
		a7.warrantyMonths = 107;
		a7.packagingType = "Sample7";
		a7.weight = 17.0;
		a7.isLeakProof = false;
		a7.feature1 = "Sample7";
		a7.feature2 = "Sample7";
		a7.feature3 = "Sample7";
		a7.isPortable = false;
		a7.isReusable = false;
		a7.rating = 107;

		System.out.println("----- AquaBottle 7 -----");
		System.out.println("productId: " + a7.productId);
		System.out.println("brandName: " + a7.brandName);
		System.out.println("material: " + a7.material);
		System.out.println("color: " + a7.color);
		System.out.println("capacity: " + a7.capacity);
		System.out.println("price: " + a7.price);
		System.out.println("isInsulated: " + a7.isInsulated);
		System.out.println("isAvailable: " + a7.isAvailable);
		System.out.println("manufacturingDate: " + a7.manufacturingDate);
		System.out.println("expiryDate: " + a7.expiryDate);
		System.out.println("bottleType: " + a7.bottleType);
		System.out.println("lidType: " + a7.lidType);
		System.out.println("height: " + a7.height);
		System.out.println("isEcoFriendly: " + a7.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a7.countryOfOrigin);
		System.out.println("warrantyMonths: " + a7.warrantyMonths);
		System.out.println("packagingType: " + a7.packagingType);
		System.out.println("weight: " + a7.weight);
		System.out.println("isLeakProof: " + a7.isLeakProof);
		System.out.println("feature1: " + a7.feature1);
		System.out.println("feature2: " + a7.feature2);
		System.out.println("feature3: " + a7.feature3);
		System.out.println("isPortable: " + a7.isPortable);
		System.out.println("isReusable: " + a7.isReusable);
		System.out.println("rating: " + a7.rating);


		AquaBottle a8 = new AquaBottle();
		a8.productId = 108;
		a8.brandName = "Sample8";
		a8.material = "Sample8";
		a8.color = "Sample8";
		a8.capacity = 18.0;
		a8.price = 18.0;
		a8.isInsulated = true;
		a8.isAvailable = true;
		a8.manufacturingDate = "Sample8";
		a8.expiryDate = "Sample8";
		a8.bottleType = "Sample8";
		a8.lidType = "Sample8";
		a8.height = 18.0;
		a8.isEcoFriendly = true;
		a8.countryOfOrigin = "Sample8";
		a8.warrantyMonths = 108;
		a8.packagingType = "Sample8";
		a8.weight = 18.0;
		a8.isLeakProof = true;
		a8.feature1 = "Sample8";
		a8.feature2 = "Sample8";
		a8.feature3 = "Sample8";
		a8.isPortable = true;
		a8.isReusable = true;
		a8.rating = 108;

		System.out.println("----- AquaBottle 8 -----");
		System.out.println("productId: " + a8.productId);
		System.out.println("brandName: " + a8.brandName);
		System.out.println("material: " + a8.material);
		System.out.println("color: " + a8.color);
		System.out.println("capacity: " + a8.capacity);
		System.out.println("price: " + a8.price);
		System.out.println("isInsulated: " + a8.isInsulated);
		System.out.println("isAvailable: " + a8.isAvailable);
		System.out.println("manufacturingDate: " + a8.manufacturingDate);
		System.out.println("expiryDate: " + a8.expiryDate);
		System.out.println("bottleType: " + a8.bottleType);
		System.out.println("lidType: " + a8.lidType);
		System.out.println("height: " + a8.height);
		System.out.println("isEcoFriendly: " + a8.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a8.countryOfOrigin);
		System.out.println("warrantyMonths: " + a8.warrantyMonths);
		System.out.println("packagingType: " + a8.packagingType);
		System.out.println("weight: " + a8.weight);
		System.out.println("isLeakProof: " + a8.isLeakProof);
		System.out.println("feature1: " + a8.feature1);
		System.out.println("feature2: " + a8.feature2);
		System.out.println("feature3: " + a8.feature3);
		System.out.println("isPortable: " + a8.isPortable);
		System.out.println("isReusable: " + a8.isReusable);
		System.out.println("rating: " + a8.rating);


		AquaBottle a9 = new AquaBottle();
		a9.productId = 109;
		a9.brandName = "Sample9";
		a9.material = "Sample9";
		a9.color = "Sample9";
		a9.capacity = 19.0;
		a9.price = 19.0;
		a9.isInsulated = false;
		a9.isAvailable = false;
		a9.manufacturingDate = "Sample9";
		a9.expiryDate = "Sample9";
		a9.bottleType = "Sample9";
		a9.lidType = "Sample9";
		a9.height = 19.0;
		a9.isEcoFriendly = false;
		a9.countryOfOrigin = "Sample9";
		a9.warrantyMonths = 109;
		a9.packagingType = "Sample9";
		a9.weight = 19.0;
		a9.isLeakProof = false;
		a9.feature1 = "Sample9";
		a9.feature2 = "Sample9";
		a9.feature3 = "Sample9";
		a9.isPortable = false;
		a9.isReusable = false;
		a9.rating = 109;

		System.out.println("----- AquaBottle 9 -----");
		System.out.println("productId: " + a9.productId);
		System.out.println("brandName: " + a9.brandName);
		System.out.println("material: " + a9.material);
		System.out.println("color: " + a9.color);
		System.out.println("capacity: " + a9.capacity);
		System.out.println("price: " + a9.price);
		System.out.println("isInsulated: " + a9.isInsulated);
		System.out.println("isAvailable: " + a9.isAvailable);
		System.out.println("manufacturingDate: " + a9.manufacturingDate);
		System.out.println("expiryDate: " + a9.expiryDate);
		System.out.println("bottleType: " + a9.bottleType);
		System.out.println("lidType: " + a9.lidType);
		System.out.println("height: " + a9.height);
		System.out.println("isEcoFriendly: " + a9.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a9.countryOfOrigin);
		System.out.println("warrantyMonths: " + a9.warrantyMonths);
		System.out.println("packagingType: " + a9.packagingType);
		System.out.println("weight: " + a9.weight);
		System.out.println("isLeakProof: " + a9.isLeakProof);
		System.out.println("feature1: " + a9.feature1);
		System.out.println("feature2: " + a9.feature2);
		System.out.println("feature3: " + a9.feature3);
		System.out.println("isPortable: " + a9.isPortable);
		System.out.println("isReusable: " + a9.isReusable);
		System.out.println("rating: " + a9.rating);


		AquaBottle a10 = new AquaBottle();
		a10.productId = 110;
		a10.brandName = "Sample10";
		a10.material = "Sample10";
		a10.color = "Sample10";
		a10.capacity = 20.0;
		a10.price = 20.0;
		a10.isInsulated = true;
		a10.isAvailable = true;
		a10.manufacturingDate = "Sample10";
		a10.expiryDate = "Sample10";
		a10.bottleType = "Sample10";
		a10.lidType = "Sample10";
		a10.height = 20.0;
		a10.isEcoFriendly = true;
		a10.countryOfOrigin = "Sample10";
		a10.warrantyMonths = 110;
		a10.packagingType = "Sample10";
		a10.weight = 20.0;
		a10.isLeakProof = true;
		a10.feature1 = "Sample10";
		a10.feature2 = "Sample10";
		a10.feature3 = "Sample10";
		a10.isPortable = true;
		a10.isReusable = true;
		a10.rating = 110;

		System.out.println("----- AquaBottle 10 -----");
		System.out.println("productId: " + a10.productId);
		System.out.println("brandName: " + a10.brandName);
		System.out.println("material: " + a10.material);
		System.out.println("color: " + a10.color);
		System.out.println("capacity: " + a10.capacity);
		System.out.println("price: " + a10.price);
		System.out.println("isInsulated: " + a10.isInsulated);
		System.out.println("isAvailable: " + a10.isAvailable);
		System.out.println("manufacturingDate: " + a10.manufacturingDate);
		System.out.println("expiryDate: " + a10.expiryDate);
		System.out.println("bottleType: " + a10.bottleType);
		System.out.println("lidType: " + a10.lidType);
		System.out.println("height: " + a10.height);
		System.out.println("isEcoFriendly: " + a10.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a10.countryOfOrigin);
		System.out.println("warrantyMonths: " + a10.warrantyMonths);
		System.out.println("packagingType: " + a10.packagingType);
		System.out.println("weight: " + a10.weight);
		System.out.println("isLeakProof: " + a10.isLeakProof);
		System.out.println("feature1: " + a10.feature1);
		System.out.println("feature2: " + a10.feature2);
		System.out.println("feature3: " + a10.feature3);
		System.out.println("isPortable: " + a10.isPortable);
		System.out.println("isReusable: " + a10.isReusable);
		System.out.println("rating: " + a10.rating);


		AquaBottle a11 = new AquaBottle();
		a11.productId = 111;
		a11.brandName = "Sample11";
		a11.material = "Sample11";
		a11.color = "Sample11";
		a11.capacity = 21.0;
		a11.price = 21.0;
		a11.isInsulated = false;
		a11.isAvailable = false;
		a11.manufacturingDate = "Sample11";
		a11.expiryDate = "Sample11";
		a11.bottleType = "Sample11";
		a11.lidType = "Sample11";
		a11.height = 21.0;
		a11.isEcoFriendly = false;
		a11.countryOfOrigin = "Sample11";
		a11.warrantyMonths = 111;
		a11.packagingType = "Sample11";
		a11.weight = 21.0;
		a11.isLeakProof = false;
		a11.feature1 = "Sample11";
		a11.feature2 = "Sample11";
		a11.feature3 = "Sample11";
		a11.isPortable = false;
		a11.isReusable = false;
		a11.rating = 111;

		System.out.println("----- AquaBottle 11 -----");
		System.out.println("productId: " + a11.productId);
		System.out.println("brandName: " + a11.brandName);
		System.out.println("material: " + a11.material);
		System.out.println("color: " + a11.color);
		System.out.println("capacity: " + a11.capacity);
		System.out.println("price: " + a11.price);
		System.out.println("isInsulated: " + a11.isInsulated);
		System.out.println("isAvailable: " + a11.isAvailable);
		System.out.println("manufacturingDate: " + a11.manufacturingDate);
		System.out.println("expiryDate: " + a11.expiryDate);
		System.out.println("bottleType: " + a11.bottleType);
		System.out.println("lidType: " + a11.lidType);
		System.out.println("height: " + a11.height);
		System.out.println("isEcoFriendly: " + a11.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a11.countryOfOrigin);
		System.out.println("warrantyMonths: " + a11.warrantyMonths);
		System.out.println("packagingType: " + a11.packagingType);
		System.out.println("weight: " + a11.weight);
		System.out.println("isLeakProof: " + a11.isLeakProof);
		System.out.println("feature1: " + a11.feature1);
		System.out.println("feature2: " + a11.feature2);
		System.out.println("feature3: " + a11.feature3);
		System.out.println("isPortable: " + a11.isPortable);
		System.out.println("isReusable: " + a11.isReusable);
		System.out.println("rating: " + a11.rating);


		AquaBottle a12 = new AquaBottle();
		a12.productId = 112;
		a12.brandName = "Sample12";
		a12.material = "Sample12";
		a12.color = "Sample12";
		a12.capacity = 22.0;
		a12.price = 22.0;
		a12.isInsulated = true;
		a12.isAvailable = true;
		a12.manufacturingDate = "Sample12";
		a12.expiryDate = "Sample12";
		a12.bottleType = "Sample12";
		a12.lidType = "Sample12";
		a12.height = 22.0;
		a12.isEcoFriendly = true;
		a12.countryOfOrigin = "Sample12";
		a12.warrantyMonths = 112;
		a12.packagingType = "Sample12";
		a12.weight = 22.0;
		a12.isLeakProof = true;
		a12.feature1 = "Sample12";
		a12.feature2 = "Sample12";
		a12.feature3 = "Sample12";
		a12.isPortable = true;
		a12.isReusable = true;
		a12.rating = 112;

		System.out.println("----- AquaBottle 12 -----");
		System.out.println("productId: " + a12.productId);
		System.out.println("brandName: " + a12.brandName);
		System.out.println("material: " + a12.material);
		System.out.println("color: " + a12.color);
		System.out.println("capacity: " + a12.capacity);
		System.out.println("price: " + a12.price);
		System.out.println("isInsulated: " + a12.isInsulated);
		System.out.println("isAvailable: " + a12.isAvailable);
		System.out.println("manufacturingDate: " + a12.manufacturingDate);
		System.out.println("expiryDate: " + a12.expiryDate);
		System.out.println("bottleType: " + a12.bottleType);
		System.out.println("lidType: " + a12.lidType);
		System.out.println("height: " + a12.height);
		System.out.println("isEcoFriendly: " + a12.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a12.countryOfOrigin);
		System.out.println("warrantyMonths: " + a12.warrantyMonths);
		System.out.println("packagingType: " + a12.packagingType);
		System.out.println("weight: " + a12.weight);
		System.out.println("isLeakProof: " + a12.isLeakProof);
		System.out.println("feature1: " + a12.feature1);
		System.out.println("feature2: " + a12.feature2);
		System.out.println("feature3: " + a12.feature3);
		System.out.println("isPortable: " + a12.isPortable);
		System.out.println("isReusable: " + a12.isReusable);
		System.out.println("rating: " + a12.rating);


		AquaBottle a13 = new AquaBottle();
		a13.productId = 113;
		a13.brandName = "Sample13";
		a13.material = "Sample13";
		a13.color = "Sample13";
		a13.capacity = 23.0;
		a13.price = 23.0;
		a13.isInsulated = false;
		a13.isAvailable = false;
		a13.manufacturingDate = "Sample13";
		a13.expiryDate = "Sample13";
		a13.bottleType = "Sample13";
		a13.lidType = "Sample13";
		a13.height = 23.0;
		a13.isEcoFriendly = false;
		a13.countryOfOrigin = "Sample13";
		a13.warrantyMonths = 113;
		a13.packagingType = "Sample13";
		a13.weight = 23.0;
		a13.isLeakProof = false;
		a13.feature1 = "Sample13";
		a13.feature2 = "Sample13";
		a13.feature3 = "Sample13";
		a13.isPortable = false;
		a13.isReusable = false;
		a13.rating = 113;

		System.out.println("----- AquaBottle 13 -----");
		System.out.println("productId: " + a13.productId);
		System.out.println("brandName: " + a13.brandName);
		System.out.println("material: " + a13.material);
		System.out.println("color: " + a13.color);
		System.out.println("capacity: " + a13.capacity);
		System.out.println("price: " + a13.price);
		System.out.println("isInsulated: " + a13.isInsulated);
		System.out.println("isAvailable: " + a13.isAvailable);
		System.out.println("manufacturingDate: " + a13.manufacturingDate);
		System.out.println("expiryDate: " + a13.expiryDate);
		System.out.println("bottleType: " + a13.bottleType);
		System.out.println("lidType: " + a13.lidType);
		System.out.println("height: " + a13.height);
		System.out.println("isEcoFriendly: " + a13.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a13.countryOfOrigin);
		System.out.println("warrantyMonths: " + a13.warrantyMonths);
		System.out.println("packagingType: " + a13.packagingType);
		System.out.println("weight: " + a13.weight);
		System.out.println("isLeakProof: " + a13.isLeakProof);
		System.out.println("feature1: " + a13.feature1);
		System.out.println("feature2: " + a13.feature2);
		System.out.println("feature3: " + a13.feature3);
		System.out.println("isPortable: " + a13.isPortable);
		System.out.println("isReusable: " + a13.isReusable);
		System.out.println("rating: " + a13.rating);


		AquaBottle a14 = new AquaBottle();
		a14.productId = 114;
		a14.brandName = "Sample14";
		a14.material = "Sample14";
		a14.color = "Sample14";
		a14.capacity = 24.0;
		a14.price = 24.0;
		a14.isInsulated = true;
		a14.isAvailable = true;
		a14.manufacturingDate = "Sample14";
		a14.expiryDate = "Sample14";
		a14.bottleType = "Sample14";
		a14.lidType = "Sample14";
		a14.height = 24.0;
		a14.isEcoFriendly = true;
		a14.countryOfOrigin = "Sample14";
		a14.warrantyMonths = 114;
		a14.packagingType = "Sample14";
		a14.weight = 24.0;
		a14.isLeakProof = true;
		a14.feature1 = "Sample14";
		a14.feature2 = "Sample14";
		a14.feature3 = "Sample14";
		a14.isPortable = true;
		a14.isReusable = true;
		a14.rating = 114;

		System.out.println("----- AquaBottle 14 -----");
		System.out.println("productId: " + a14.productId);
		System.out.println("brandName: " + a14.brandName);
		System.out.println("material: " + a14.material);
		System.out.println("color: " + a14.color);
		System.out.println("capacity: " + a14.capacity);
		System.out.println("price: " + a14.price);
		System.out.println("isInsulated: " + a14.isInsulated);
		System.out.println("isAvailable: " + a14.isAvailable);
		System.out.println("manufacturingDate: " + a14.manufacturingDate);
		System.out.println("expiryDate: " + a14.expiryDate);
		System.out.println("bottleType: " + a14.bottleType);
		System.out.println("lidType: " + a14.lidType);
		System.out.println("height: " + a14.height);
		System.out.println("isEcoFriendly: " + a14.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a14.countryOfOrigin);
		System.out.println("warrantyMonths: " + a14.warrantyMonths);
		System.out.println("packagingType: " + a14.packagingType);
		System.out.println("weight: " + a14.weight);
		System.out.println("isLeakProof: " + a14.isLeakProof);
		System.out.println("feature1: " + a14.feature1);
		System.out.println("feature2: " + a14.feature2);
		System.out.println("feature3: " + a14.feature3);
		System.out.println("isPortable: " + a14.isPortable);
		System.out.println("isReusable: " + a14.isReusable);
		System.out.println("rating: " + a14.rating);


		AquaBottle a15 = new AquaBottle();
		a15.productId = 115;
		a15.brandName = "Sample15";
		a15.material = "Sample15";
		a15.color = "Sample15";
		a15.capacity = 25.0;
		a15.price = 25.0;
		a15.isInsulated = false;
		a15.isAvailable = false;
		a15.manufacturingDate = "Sample15";
		a15.expiryDate = "Sample15";
		a15.bottleType = "Sample15";
		a15.lidType = "Sample15";
		a15.height = 25.0;
		a15.isEcoFriendly = false;
		a15.countryOfOrigin = "Sample15";
		a15.warrantyMonths = 115;
		a15.packagingType = "Sample15";
		a15.weight = 25.0;
		a15.isLeakProof = false;
		a15.feature1 = "Sample15";
		a15.feature2 = "Sample15";
		a15.feature3 = "Sample15";
		a15.isPortable = false;
		a15.isReusable = false;
		a15.rating = 115;

		System.out.println("----- AquaBottle 15 -----");
		System.out.println("productId: " + a15.productId);
		System.out.println("brandName: " + a15.brandName);
		System.out.println("material: " + a15.material);
		System.out.println("color: " + a15.color);
		System.out.println("capacity: " + a15.capacity);
		System.out.println("price: " + a15.price);
		System.out.println("isInsulated: " + a15.isInsulated);
		System.out.println("isAvailable: " + a15.isAvailable);
		System.out.println("manufacturingDate: " + a15.manufacturingDate);
		System.out.println("expiryDate: " + a15.expiryDate);
		System.out.println("bottleType: " + a15.bottleType);
		System.out.println("lidType: " + a15.lidType);
		System.out.println("height: " + a15.height);
		System.out.println("isEcoFriendly: " + a15.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a15.countryOfOrigin);
		System.out.println("warrantyMonths: " + a15.warrantyMonths);
		System.out.println("packagingType: " + a15.packagingType);
		System.out.println("weight: " + a15.weight);
		System.out.println("isLeakProof: " + a15.isLeakProof);
		System.out.println("feature1: " + a15.feature1);
		System.out.println("feature2: " + a15.feature2);
		System.out.println("feature3: " + a15.feature3);
		System.out.println("isPortable: " + a15.isPortable);
		System.out.println("isReusable: " + a15.isReusable);
		System.out.println("rating: " + a15.rating);


		AquaBottle a16 = new AquaBottle();
		a16.productId = 116;
		a16.brandName = "Sample16";
		a16.material = "Sample16";
		a16.color = "Sample16";
		a16.capacity = 26.0;
		a16.price = 26.0;
		a16.isInsulated = true;
		a16.isAvailable = true;
		a16.manufacturingDate = "Sample16";
		a16.expiryDate = "Sample16";
		a16.bottleType = "Sample16";
		a16.lidType = "Sample16";
		a16.height = 26.0;
		a16.isEcoFriendly = true;
		a16.countryOfOrigin = "Sample16";
		a16.warrantyMonths = 116;
		a16.packagingType = "Sample16";
		a16.weight = 26.0;
		a16.isLeakProof = true;
		a16.feature1 = "Sample16";
		a16.feature2 = "Sample16";
		a16.feature3 = "Sample16";
		a16.isPortable = true;
		a16.isReusable = true;
		a16.rating = 116;

		System.out.println("----- AquaBottle 16 -----");
		System.out.println("productId: " + a16.productId);
		System.out.println("brandName: " + a16.brandName);
		System.out.println("material: " + a16.material);
		System.out.println("color: " + a16.color);
		System.out.println("capacity: " + a16.capacity);
		System.out.println("price: " + a16.price);
		System.out.println("isInsulated: " + a16.isInsulated);
		System.out.println("isAvailable: " + a16.isAvailable);
		System.out.println("manufacturingDate: " + a16.manufacturingDate);
		System.out.println("expiryDate: " + a16.expiryDate);
		System.out.println("bottleType: " + a16.bottleType);
		System.out.println("lidType: " + a16.lidType);
		System.out.println("height: " + a16.height);
		System.out.println("isEcoFriendly: " + a16.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a16.countryOfOrigin);
		System.out.println("warrantyMonths: " + a16.warrantyMonths);
		System.out.println("packagingType: " + a16.packagingType);
		System.out.println("weight: " + a16.weight);
		System.out.println("isLeakProof: " + a16.isLeakProof);
		System.out.println("feature1: " + a16.feature1);
		System.out.println("feature2: " + a16.feature2);
		System.out.println("feature3: " + a16.feature3);
		System.out.println("isPortable: " + a16.isPortable);
		System.out.println("isReusable: " + a16.isReusable);
		System.out.println("rating: " + a16.rating);


		AquaBottle a17 = new AquaBottle();
		a17.productId = 117;
		a17.brandName = "Sample17";
		a17.material = "Sample17";
		a17.color = "Sample17";
		a17.capacity = 27.0;
		a17.price = 27.0;
		a17.isInsulated = false;
		a17.isAvailable = false;
		a17.manufacturingDate = "Sample17";
		a17.expiryDate = "Sample17";
		a17.bottleType = "Sample17";
		a17.lidType = "Sample17";
		a17.height = 27.0;
		a17.isEcoFriendly = false;
		a17.countryOfOrigin = "Sample17";
		a17.warrantyMonths = 117;
		a17.packagingType = "Sample17";
		a17.weight = 27.0;
		a17.isLeakProof = false;
		a17.feature1 = "Sample17";
		a17.feature2 = "Sample17";
		a17.feature3 = "Sample17";
		a17.isPortable = false;
		a17.isReusable = false;
		a17.rating = 117;

		System.out.println("----- AquaBottle 17 -----");
		System.out.println("productId: " + a17.productId);
		System.out.println("brandName: " + a17.brandName);
		System.out.println("material: " + a17.material);
		System.out.println("color: " + a17.color);
		System.out.println("capacity: " + a17.capacity);
		System.out.println("price: " + a17.price);
		System.out.println("isInsulated: " + a17.isInsulated);
		System.out.println("isAvailable: " + a17.isAvailable);
		System.out.println("manufacturingDate: " + a17.manufacturingDate);
		System.out.println("expiryDate: " + a17.expiryDate);
		System.out.println("bottleType: " + a17.bottleType);
		System.out.println("lidType: " + a17.lidType);
		System.out.println("height: " + a17.height);
		System.out.println("isEcoFriendly: " + a17.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a17.countryOfOrigin);
		System.out.println("warrantyMonths: " + a17.warrantyMonths);
		System.out.println("packagingType: " + a17.packagingType);
		System.out.println("weight: " + a17.weight);
		System.out.println("isLeakProof: " + a17.isLeakProof);
		System.out.println("feature1: " + a17.feature1);
		System.out.println("feature2: " + a17.feature2);
		System.out.println("feature3: " + a17.feature3);
		System.out.println("isPortable: " + a17.isPortable);
		System.out.println("isReusable: " + a17.isReusable);
		System.out.println("rating: " + a17.rating);


		AquaBottle a18 = new AquaBottle();
		a18.productId = 118;
		a18.brandName = "Sample18";
		a18.material = "Sample18";
		a18.color = "Sample18";
		a18.capacity = 28.0;
		a18.price = 28.0;
		a18.isInsulated = true;
		a18.isAvailable = true;
		a18.manufacturingDate = "Sample18";
		a18.expiryDate = "Sample18";
		a18.bottleType = "Sample18";
		a18.lidType = "Sample18";
		a18.height = 28.0;
		a18.isEcoFriendly = true;
		a18.countryOfOrigin = "Sample18";
		a18.warrantyMonths = 118;
		a18.packagingType = "Sample18";
		a18.weight = 28.0;
		a18.isLeakProof = true;
		a18.feature1 = "Sample18";
		a18.feature2 = "Sample18";
		a18.feature3 = "Sample18";
		a18.isPortable = true;
		a18.isReusable = true;
		a18.rating = 118;

		System.out.println("----- AquaBottle 18 -----");
		System.out.println("productId: " + a18.productId);
		System.out.println("brandName: " + a18.brandName);
		System.out.println("material: " + a18.material);
		System.out.println("color: " + a18.color);
		System.out.println("capacity: " + a18.capacity);
		System.out.println("price: " + a18.price);
		System.out.println("isInsulated: " + a18.isInsulated);
		System.out.println("isAvailable: " + a18.isAvailable);
		System.out.println("manufacturingDate: " + a18.manufacturingDate);
		System.out.println("expiryDate: " + a18.expiryDate);
		System.out.println("bottleType: " + a18.bottleType);
		System.out.println("lidType: " + a18.lidType);
		System.out.println("height: " + a18.height);
		System.out.println("isEcoFriendly: " + a18.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a18.countryOfOrigin);
		System.out.println("warrantyMonths: " + a18.warrantyMonths);
		System.out.println("packagingType: " + a18.packagingType);
		System.out.println("weight: " + a18.weight);
		System.out.println("isLeakProof: " + a18.isLeakProof);
		System.out.println("feature1: " + a18.feature1);
		System.out.println("feature2: " + a18.feature2);
		System.out.println("feature3: " + a18.feature3);
		System.out.println("isPortable: " + a18.isPortable);
		System.out.println("isReusable: " + a18.isReusable);
		System.out.println("rating: " + a18.rating);


		AquaBottle a19 = new AquaBottle();
		a19.productId = 119;
		a19.brandName = "Sample19";
		a19.material = "Sample19";
		a19.color = "Sample19";
		a19.capacity = 29.0;
		a19.price = 29.0;
		a19.isInsulated = false;
		a19.isAvailable = false;
		a19.manufacturingDate = "Sample19";
		a19.expiryDate = "Sample19";
		a19.bottleType = "Sample19";
		a19.lidType = "Sample19";
		a19.height = 29.0;
		a19.isEcoFriendly = false;
		a19.countryOfOrigin = "Sample19";
		a19.warrantyMonths = 119;
		a19.packagingType = "Sample19";
		a19.weight = 29.0;
		a19.isLeakProof = false;
		a19.feature1 = "Sample19";
		a19.feature2 = "Sample19";
		a19.feature3 = "Sample19";
		a19.isPortable = false;
		a19.isReusable = false;
		a19.rating = 119;

		System.out.println("----- AquaBottle 19 -----");
		System.out.println("productId: " + a19.productId);
		System.out.println("brandName: " + a19.brandName);
		System.out.println("material: " + a19.material);
		System.out.println("color: " + a19.color);
		System.out.println("capacity: " + a19.capacity);
		System.out.println("price: " + a19.price);
		System.out.println("isInsulated: " + a19.isInsulated);
		System.out.println("isAvailable: " + a19.isAvailable);
		System.out.println("manufacturingDate: " + a19.manufacturingDate);
		System.out.println("expiryDate: " + a19.expiryDate);
		System.out.println("bottleType: " + a19.bottleType);
		System.out.println("lidType: " + a19.lidType);
		System.out.println("height: " + a19.height);
		System.out.println("isEcoFriendly: " + a19.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a19.countryOfOrigin);
		System.out.println("warrantyMonths: " + a19.warrantyMonths);
		System.out.println("packagingType: " + a19.packagingType);
		System.out.println("weight: " + a19.weight);
		System.out.println("isLeakProof: " + a19.isLeakProof);
		System.out.println("feature1: " + a19.feature1);
		System.out.println("feature2: " + a19.feature2);
		System.out.println("feature3: " + a19.feature3);
		System.out.println("isPortable: " + a19.isPortable);
		System.out.println("isReusable: " + a19.isReusable);
		System.out.println("rating: " + a19.rating);


		AquaBottle a20 = new AquaBottle();
		a20.productId = 120;
		a20.brandName = "Sample20";
		a20.material = "Sample20";
		a20.color = "Sample20";
		a20.capacity = 30.0;
		a20.price = 30.0;
		a20.isInsulated = true;
		a20.isAvailable = true;
		a20.manufacturingDate = "Sample20";
		a20.expiryDate = "Sample20";
		a20.bottleType = "Sample20";
		a20.lidType = "Sample20";
		a20.height = 30.0;
		a20.isEcoFriendly = true;
		a20.countryOfOrigin = "Sample20";
		a20.warrantyMonths = 120;
		a20.packagingType = "Sample20";
		a20.weight = 30.0;
		a20.isLeakProof = true;
		a20.feature1 = "Sample20";
		a20.feature2 = "Sample20";
		a20.feature3 = "Sample20";
		a20.isPortable = true;
		a20.isReusable = true;
		a20.rating = 120;

		System.out.println("----- AquaBottle 20 -----");
		System.out.println("productId: " + a20.productId);
		System.out.println("brandName: " + a20.brandName);
		System.out.println("material: " + a20.material);
		System.out.println("color: " + a20.color);
		System.out.println("capacity: " + a20.capacity);
		System.out.println("price: " + a20.price);
		System.out.println("isInsulated: " + a20.isInsulated);
		System.out.println("isAvailable: " + a20.isAvailable);
		System.out.println("manufacturingDate: " + a20.manufacturingDate);
		System.out.println("expiryDate: " + a20.expiryDate);
		System.out.println("bottleType: " + a20.bottleType);
		System.out.println("lidType: " + a20.lidType);
		System.out.println("height: " + a20.height);
		System.out.println("isEcoFriendly: " + a20.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a20.countryOfOrigin);
		System.out.println("warrantyMonths: " + a20.warrantyMonths);
		System.out.println("packagingType: " + a20.packagingType);
		System.out.println("weight: " + a20.weight);
		System.out.println("isLeakProof: " + a20.isLeakProof);
		System.out.println("feature1: " + a20.feature1);
		System.out.println("feature2: " + a20.feature2);
		System.out.println("feature3: " + a20.feature3);
		System.out.println("isPortable: " + a20.isPortable);
		System.out.println("isReusable: " + a20.isReusable);
		System.out.println("rating: " + a20.rating);


		AquaBottle a21 = new AquaBottle();
		a21.productId = 121;
		a21.brandName = "Sample21";
		a21.material = "Sample21";
		a21.color = "Sample21";
		a21.capacity = 31.0;
		a21.price = 31.0;
		a21.isInsulated = false;
		a21.isAvailable = false;
		a21.manufacturingDate = "Sample21";
		a21.expiryDate = "Sample21";
		a21.bottleType = "Sample21";
		a21.lidType = "Sample21";
		a21.height = 31.0;
		a21.isEcoFriendly = false;
		a21.countryOfOrigin = "Sample21";
		a21.warrantyMonths = 121;
		a21.packagingType = "Sample21";
		a21.weight = 31.0;
		a21.isLeakProof = false;
		a21.feature1 = "Sample21";
		a21.feature2 = "Sample21";
		a21.feature3 = "Sample21";
		a21.isPortable = false;
		a21.isReusable = false;
		a21.rating = 121;

		System.out.println("----- AquaBottle 21 -----");
		System.out.println("productId: " + a21.productId);
		System.out.println("brandName: " + a21.brandName);
		System.out.println("material: " + a21.material);
		System.out.println("color: " + a21.color);
		System.out.println("capacity: " + a21.capacity);
		System.out.println("price: " + a21.price);
		System.out.println("isInsulated: " + a21.isInsulated);
		System.out.println("isAvailable: " + a21.isAvailable);
		System.out.println("manufacturingDate: " + a21.manufacturingDate);
		System.out.println("expiryDate: " + a21.expiryDate);
		System.out.println("bottleType: " + a21.bottleType);
		System.out.println("lidType: " + a21.lidType);
		System.out.println("height: " + a21.height);
		System.out.println("isEcoFriendly: " + a21.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a21.countryOfOrigin);
		System.out.println("warrantyMonths: " + a21.warrantyMonths);
		System.out.println("packagingType: " + a21.packagingType);
		System.out.println("weight: " + a21.weight);
		System.out.println("isLeakProof: " + a21.isLeakProof);
		System.out.println("feature1: " + a21.feature1);
		System.out.println("feature2: " + a21.feature2);
		System.out.println("feature3: " + a21.feature3);
		System.out.println("isPortable: " + a21.isPortable);
		System.out.println("isReusable: " + a21.isReusable);
		System.out.println("rating: " + a21.rating);


		AquaBottle a22 = new AquaBottle();
		a22.productId = 122;
		a22.brandName = "Sample22";
		a22.material = "Sample22";
		a22.color = "Sample22";
		a22.capacity = 32.0;
		a22.price = 32.0;
		a22.isInsulated = true;
		a22.isAvailable = true;
		a22.manufacturingDate = "Sample22";
		a22.expiryDate = "Sample22";
		a22.bottleType = "Sample22";
		a22.lidType = "Sample22";
		a22.height = 32.0;
		a22.isEcoFriendly = true;
		a22.countryOfOrigin = "Sample22";
		a22.warrantyMonths = 122;
		a22.packagingType = "Sample22";
		a22.weight = 32.0;
		a22.isLeakProof = true;
		a22.feature1 = "Sample22";
		a22.feature2 = "Sample22";
		a22.feature3 = "Sample22";
		a22.isPortable = true;
		a22.isReusable = true;
		a22.rating = 122;

		System.out.println("----- AquaBottle 22 -----");
		System.out.println("productId: " + a22.productId);
		System.out.println("brandName: " + a22.brandName);
		System.out.println("material: " + a22.material);
		System.out.println("color: " + a22.color);
		System.out.println("capacity: " + a22.capacity);
		System.out.println("price: " + a22.price);
		System.out.println("isInsulated: " + a22.isInsulated);
		System.out.println("isAvailable: " + a22.isAvailable);
		System.out.println("manufacturingDate: " + a22.manufacturingDate);
		System.out.println("expiryDate: " + a22.expiryDate);
		System.out.println("bottleType: " + a22.bottleType);
		System.out.println("lidType: " + a22.lidType);
		System.out.println("height: " + a22.height);
		System.out.println("isEcoFriendly: " + a22.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a22.countryOfOrigin);
		System.out.println("warrantyMonths: " + a22.warrantyMonths);
		System.out.println("packagingType: " + a22.packagingType);
		System.out.println("weight: " + a22.weight);
		System.out.println("isLeakProof: " + a22.isLeakProof);
		System.out.println("feature1: " + a22.feature1);
		System.out.println("feature2: " + a22.feature2);
		System.out.println("feature3: " + a22.feature3);
		System.out.println("isPortable: " + a22.isPortable);
		System.out.println("isReusable: " + a22.isReusable);
		System.out.println("rating: " + a22.rating);


		AquaBottle a23 = new AquaBottle();
		a23.productId = 123;
		a23.brandName = "Sample23";
		a23.material = "Sample23";
		a23.color = "Sample23";
		a23.capacity = 33.0;
		a23.price = 33.0;
		a23.isInsulated = false;
		a23.isAvailable = false;
		a23.manufacturingDate = "Sample23";
		a23.expiryDate = "Sample23";
		a23.bottleType = "Sample23";
		a23.lidType = "Sample23";
		a23.height = 33.0;
		a23.isEcoFriendly = false;
		a23.countryOfOrigin = "Sample23";
		a23.warrantyMonths = 123;
		a23.packagingType = "Sample23";
		a23.weight = 33.0;
		a23.isLeakProof = false;
		a23.feature1 = "Sample23";
		a23.feature2 = "Sample23";
		a23.feature3 = "Sample23";
		a23.isPortable = false;
		a23.isReusable = false;
		a23.rating = 123;

		System.out.println("----- AquaBottle 23 -----");
		System.out.println("productId: " + a23.productId);
		System.out.println("brandName: " + a23.brandName);
		System.out.println("material: " + a23.material);
		System.out.println("color: " + a23.color);
		System.out.println("capacity: " + a23.capacity);
		System.out.println("price: " + a23.price);
		System.out.println("isInsulated: " + a23.isInsulated);
		System.out.println("isAvailable: " + a23.isAvailable);
		System.out.println("manufacturingDate: " + a23.manufacturingDate);
		System.out.println("expiryDate: " + a23.expiryDate);
		System.out.println("bottleType: " + a23.bottleType);
		System.out.println("lidType: " + a23.lidType);
		System.out.println("height: " + a23.height);
		System.out.println("isEcoFriendly: " + a23.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a23.countryOfOrigin);
		System.out.println("warrantyMonths: " + a23.warrantyMonths);
		System.out.println("packagingType: " + a23.packagingType);
		System.out.println("weight: " + a23.weight);
		System.out.println("isLeakProof: " + a23.isLeakProof);
		System.out.println("feature1: " + a23.feature1);
		System.out.println("feature2: " + a23.feature2);
		System.out.println("feature3: " + a23.feature3);
		System.out.println("isPortable: " + a23.isPortable);
		System.out.println("isReusable: " + a23.isReusable);
		System.out.println("rating: " + a23.rating);


		AquaBottle a24 = new AquaBottle();
		a24.productId = 124;
		a24.brandName = "Sample24";
		a24.material = "Sample24";
		a24.color = "Sample24";
		a24.capacity = 34.0;
		a24.price = 34.0;
		a24.isInsulated = true;
		a24.isAvailable = true;
		a24.manufacturingDate = "Sample24";
		a24.expiryDate = "Sample24";
		a24.bottleType = "Sample24";
		a24.lidType = "Sample24";
		a24.height = 34.0;
		a24.isEcoFriendly = true;
		a24.countryOfOrigin = "Sample24";
		a24.warrantyMonths = 124;
		a24.packagingType = "Sample24";
		a24.weight = 34.0;
		a24.isLeakProof = true;
		a24.feature1 = "Sample24";
		a24.feature2 = "Sample24";
		a24.feature3 = "Sample24";
		a24.isPortable = true;
		a24.isReusable = true;
		a24.rating = 124;

		System.out.println("----- AquaBottle 24 -----");
		System.out.println("productId: " + a24.productId);
		System.out.println("brandName: " + a24.brandName);
		System.out.println("material: " + a24.material);
		System.out.println("color: " + a24.color);
		System.out.println("capacity: " + a24.capacity);
		System.out.println("price: " + a24.price);
		System.out.println("isInsulated: " + a24.isInsulated);
		System.out.println("isAvailable: " + a24.isAvailable);
		System.out.println("manufacturingDate: " + a24.manufacturingDate);
		System.out.println("expiryDate: " + a24.expiryDate);
		System.out.println("bottleType: " + a24.bottleType);
		System.out.println("lidType: " + a24.lidType);
		System.out.println("height: " + a24.height);
		System.out.println("isEcoFriendly: " + a24.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a24.countryOfOrigin);
		System.out.println("warrantyMonths: " + a24.warrantyMonths);
		System.out.println("packagingType: " + a24.packagingType);
		System.out.println("weight: " + a24.weight);
		System.out.println("isLeakProof: " + a24.isLeakProof);
		System.out.println("feature1: " + a24.feature1);
		System.out.println("feature2: " + a24.feature2);
		System.out.println("feature3: " + a24.feature3);
		System.out.println("isPortable: " + a24.isPortable);
		System.out.println("isReusable: " + a24.isReusable);
		System.out.println("rating: " + a24.rating);


		AquaBottle a25 = new AquaBottle();
		a25.productId = 125;
		a25.brandName = "Sample25";
		a25.material = "Sample25";
		a25.color = "Sample25";
		a25.capacity = 35.0;
		a25.price = 35.0;
		a25.isInsulated = false;
		a25.isAvailable = false;
		a25.manufacturingDate = "Sample25";
		a25.expiryDate = "Sample25";
		a25.bottleType = "Sample25";
		a25.lidType = "Sample25";
		a25.height = 35.0;
		a25.isEcoFriendly = false;
		a25.countryOfOrigin = "Sample25";
		a25.warrantyMonths = 125;
		a25.packagingType = "Sample25";
		a25.weight = 35.0;
		a25.isLeakProof = false;
		a25.feature1 = "Sample25";
		a25.feature2 = "Sample25";
		a25.feature3 = "Sample25";
		a25.isPortable = false;
		a25.isReusable = false;
		a25.rating = 125;

		System.out.println("----- AquaBottle 25 -----");
		System.out.println("productId: " + a25.productId);
		System.out.println("brandName: " + a25.brandName);
		System.out.println("material: " + a25.material);
		System.out.println("color: " + a25.color);
		System.out.println("capacity: " + a25.capacity);
		System.out.println("price: " + a25.price);
		System.out.println("isInsulated: " + a25.isInsulated);
		System.out.println("isAvailable: " + a25.isAvailable);
		System.out.println("manufacturingDate: " + a25.manufacturingDate);
		System.out.println("expiryDate: " + a25.expiryDate);
		System.out.println("bottleType: " + a25.bottleType);
		System.out.println("lidType: " + a25.lidType);
		System.out.println("height: " + a25.height);
		System.out.println("isEcoFriendly: " + a25.isEcoFriendly);
		System.out.println("countryOfOrigin: " + a25.countryOfOrigin);
		System.out.println("warrantyMonths: " + a25.warrantyMonths);
		System.out.println("packagingType: " + a25.packagingType);
		System.out.println("weight: " + a25.weight);
		System.out.println("isLeakProof: " + a25.isLeakProof);
		System.out.println("feature1: " + a25.feature1);
		System.out.println("feature2: " + a25.feature2);
		System.out.println("feature3: " + a25.feature3);
		System.out.println("isPortable: " + a25.isPortable);
		System.out.println("isReusable: " + a25.isReusable);
		System.out.println("rating: " + a25.rating);


	}
}

	