class AuroraSpeakerRunner {
	public static void main(String[] args) {

		AuroraSpeaker a1 = new AuroraSpeaker();
		a1.productId = 101;
		a1.brandName = "Sample1";
		a1.connectivityType = "Sample1";
		a1.color = "Sample1";
		a1.batteryCapacity = 11.0;
		a1.price = 11.0;
		a1.isWireless = false;
		a1.isAvailable = false;
		a1.manufacturingDate = "Sample1";
		a1.expiryDate = "Sample1";
		a1.soundType = "Sample1";
		a1.material = "Sample1";
		a1.powerOutput = 11.0;
		a1.isWaterproof = false;
		a1.countryOfOrigin = "Sample1";
		a1.warrantyMonths = 101;
		a1.packagingType = "Sample1";
		a1.weight = 11.0;
		a1.isPortable = false;
		a1.feature1 = "Sample1";
		a1.feature2 = "Sample1";
		a1.feature3 = "Sample1";
		a1.hasBluetooth = false;
		a1.hasMic = false;
		a1.rating = 101;

		System.out.println("----- AuroraSpeaker 1 -----");
		System.out.println("productId: " + a1.productId);
		System.out.println("brandName: " + a1.brandName);
		System.out.println("connectivityType: " + a1.connectivityType);
		System.out.println("color: " + a1.color);
		System.out.println("batteryCapacity: " + a1.batteryCapacity);
		System.out.println("price: " + a1.price);
		System.out.println("isWireless: " + a1.isWireless);
		System.out.println("isAvailable: " + a1.isAvailable);
		System.out.println("manufacturingDate: " + a1.manufacturingDate);
		System.out.println("expiryDate: " + a1.expiryDate);
		System.out.println("soundType: " + a1.soundType);
		System.out.println("material: " + a1.material);
		System.out.println("powerOutput: " + a1.powerOutput);
		System.out.println("isWaterproof: " + a1.isWaterproof);
		System.out.println("countryOfOrigin: " + a1.countryOfOrigin);
		System.out.println("warrantyMonths: " + a1.warrantyMonths);
		System.out.println("packagingType: " + a1.packagingType);
		System.out.println("weight: " + a1.weight);
		System.out.println("isPortable: " + a1.isPortable);
		System.out.println("feature1: " + a1.feature1);
		System.out.println("feature2: " + a1.feature2);
		System.out.println("feature3: " + a1.feature3);
		System.out.println("hasBluetooth: " + a1.hasBluetooth);
		System.out.println("hasMic: " + a1.hasMic);
		System.out.println("rating: " + a1.rating);


		AuroraSpeaker a2 = new AuroraSpeaker();
		a2.productId = 102;
		a2.brandName = "Sample2";
		a2.connectivityType = "Sample2";
		a2.color = "Sample2";
		a2.batteryCapacity = 12.0;
		a2.price = 12.0;
		a2.isWireless = true;
		a2.isAvailable = true;
		a2.manufacturingDate = "Sample2";
		a2.expiryDate = "Sample2";
		a2.soundType = "Sample2";
		a2.material = "Sample2";
		a2.powerOutput = 12.0;
		a2.isWaterproof = true;
		a2.countryOfOrigin = "Sample2";
		a2.warrantyMonths = 102;
		a2.packagingType = "Sample2";
		a2.weight = 12.0;
		a2.isPortable = true;
		a2.feature1 = "Sample2";
		a2.feature2 = "Sample2";
		a2.feature3 = "Sample2";
		a2.hasBluetooth = true;
		a2.hasMic = true;
		a2.rating = 102;

		System.out.println("----- AuroraSpeaker 2 -----");
		System.out.println("productId: " + a2.productId);
		System.out.println("brandName: " + a2.brandName);
		System.out.println("connectivityType: " + a2.connectivityType);
		System.out.println("color: " + a2.color);
		System.out.println("batteryCapacity: " + a2.batteryCapacity);
		System.out.println("price: " + a2.price);
		System.out.println("isWireless: " + a2.isWireless);
		System.out.println("isAvailable: " + a2.isAvailable);
		System.out.println("manufacturingDate: " + a2.manufacturingDate);
		System.out.println("expiryDate: " + a2.expiryDate);
		System.out.println("soundType: " + a2.soundType);
		System.out.println("material: " + a2.material);
		System.out.println("powerOutput: " + a2.powerOutput);
		System.out.println("isWaterproof: " + a2.isWaterproof);
		System.out.println("countryOfOrigin: " + a2.countryOfOrigin);
		System.out.println("warrantyMonths: " + a2.warrantyMonths);
		System.out.println("packagingType: " + a2.packagingType);
		System.out.println("weight: " + a2.weight);
		System.out.println("isPortable: " + a2.isPortable);
		System.out.println("feature1: " + a2.feature1);
		System.out.println("feature2: " + a2.feature2);
		System.out.println("feature3: " + a2.feature3);
		System.out.println("hasBluetooth: " + a2.hasBluetooth);
		System.out.println("hasMic: " + a2.hasMic);
		System.out.println("rating: " + a2.rating);


		AuroraSpeaker a3 = new AuroraSpeaker();
		a3.productId = 103;
		a3.brandName = "Sample3";
		a3.connectivityType = "Sample3";
		a3.color = "Sample3";
		a3.batteryCapacity = 13.0;
		a3.price = 13.0;
		a3.isWireless = false;
		a3.isAvailable = false;
		a3.manufacturingDate = "Sample3";
		a3.expiryDate = "Sample3";
		a3.soundType = "Sample3";
		a3.material = "Sample3";
		a3.powerOutput = 13.0;
		a3.isWaterproof = false;
		a3.countryOfOrigin = "Sample3";
		a3.warrantyMonths = 103;
		a3.packagingType = "Sample3";
		a3.weight = 13.0;
		a3.isPortable = false;
		a3.feature1 = "Sample3";
		a3.feature2 = "Sample3";
		a3.feature3 = "Sample3";
		a3.hasBluetooth = false;
		a3.hasMic = false;
		a3.rating = 103;

		System.out.println("----- AuroraSpeaker 3 -----");
		System.out.println("productId: " + a3.productId);
		System.out.println("brandName: " + a3.brandName);
		System.out.println("connectivityType: " + a3.connectivityType);
		System.out.println("color: " + a3.color);
		System.out.println("batteryCapacity: " + a3.batteryCapacity);
		System.out.println("price: " + a3.price);
		System.out.println("isWireless: " + a3.isWireless);
		System.out.println("isAvailable: " + a3.isAvailable);
		System.out.println("manufacturingDate: " + a3.manufacturingDate);
		System.out.println("expiryDate: " + a3.expiryDate);
		System.out.println("soundType: " + a3.soundType);
		System.out.println("material: " + a3.material);
		System.out.println("powerOutput: " + a3.powerOutput);
		System.out.println("isWaterproof: " + a3.isWaterproof);
		System.out.println("countryOfOrigin: " + a3.countryOfOrigin);
		System.out.println("warrantyMonths: " + a3.warrantyMonths);
		System.out.println("packagingType: " + a3.packagingType);
		System.out.println("weight: " + a3.weight);
		System.out.println("isPortable: " + a3.isPortable);
		System.out.println("feature1: " + a3.feature1);
		System.out.println("feature2: " + a3.feature2);
		System.out.println("feature3: " + a3.feature3);
		System.out.println("hasBluetooth: " + a3.hasBluetooth);
		System.out.println("hasMic: " + a3.hasMic);
		System.out.println("rating: " + a3.rating);


		AuroraSpeaker a4 = new AuroraSpeaker();
		a4.productId = 104;
		a4.brandName = "Sample4";
		a4.connectivityType = "Sample4";
		a4.color = "Sample4";
		a4.batteryCapacity = 14.0;
		a4.price = 14.0;
		a4.isWireless = true;
		a4.isAvailable = true;
		a4.manufacturingDate = "Sample4";
		a4.expiryDate = "Sample4";
		a4.soundType = "Sample4";
		a4.material = "Sample4";
		a4.powerOutput = 14.0;
		a4.isWaterproof = true;
		a4.countryOfOrigin = "Sample4";
		a4.warrantyMonths = 104;
		a4.packagingType = "Sample4";
		a4.weight = 14.0;
		a4.isPortable = true;
		a4.feature1 = "Sample4";
		a4.feature2 = "Sample4";
		a4.feature3 = "Sample4";
		a4.hasBluetooth = true;
		a4.hasMic = true;
		a4.rating = 104;

		System.out.println("----- AuroraSpeaker 4 -----");
		System.out.println("productId: " + a4.productId);
		System.out.println("brandName: " + a4.brandName);
		System.out.println("connectivityType: " + a4.connectivityType);
		System.out.println("color: " + a4.color);
		System.out.println("batteryCapacity: " + a4.batteryCapacity);
		System.out.println("price: " + a4.price);
		System.out.println("isWireless: " + a4.isWireless);
		System.out.println("isAvailable: " + a4.isAvailable);
		System.out.println("manufacturingDate: " + a4.manufacturingDate);
		System.out.println("expiryDate: " + a4.expiryDate);
		System.out.println("soundType: " + a4.soundType);
		System.out.println("material: " + a4.material);
		System.out.println("powerOutput: " + a4.powerOutput);
		System.out.println("isWaterproof: " + a4.isWaterproof);
		System.out.println("countryOfOrigin: " + a4.countryOfOrigin);
		System.out.println("warrantyMonths: " + a4.warrantyMonths);
		System.out.println("packagingType: " + a4.packagingType);
		System.out.println("weight: " + a4.weight);
		System.out.println("isPortable: " + a4.isPortable);
		System.out.println("feature1: " + a4.feature1);
		System.out.println("feature2: " + a4.feature2);
		System.out.println("feature3: " + a4.feature3);
		System.out.println("hasBluetooth: " + a4.hasBluetooth);
		System.out.println("hasMic: " + a4.hasMic);
		System.out.println("rating: " + a4.rating);


		AuroraSpeaker a5 = new AuroraSpeaker();
		a5.productId = 105;
		a5.brandName = "Sample5";
		a5.connectivityType = "Sample5";
		a5.color = "Sample5";
		a5.batteryCapacity = 15.0;
		a5.price = 15.0;
		a5.isWireless = false;
		a5.isAvailable = false;
		a5.manufacturingDate = "Sample5";
		a5.expiryDate = "Sample5";
		a5.soundType = "Sample5";
		a5.material = "Sample5";
		a5.powerOutput = 15.0;
		a5.isWaterproof = false;
		a5.countryOfOrigin = "Sample5";
		a5.warrantyMonths = 105;
		a5.packagingType = "Sample5";
		a5.weight = 15.0;
		a5.isPortable = false;
		a5.feature1 = "Sample5";
		a5.feature2 = "Sample5";
		a5.feature3 = "Sample5";
		a5.hasBluetooth = false;
		a5.hasMic = false;
		a5.rating = 105;

		System.out.println("----- AuroraSpeaker 5 -----");
		System.out.println("productId: " + a5.productId);
		System.out.println("brandName: " + a5.brandName);
		System.out.println("connectivityType: " + a5.connectivityType);
		System.out.println("color: " + a5.color);
		System.out.println("batteryCapacity: " + a5.batteryCapacity);
		System.out.println("price: " + a5.price);
		System.out.println("isWireless: " + a5.isWireless);
		System.out.println("isAvailable: " + a5.isAvailable);
		System.out.println("manufacturingDate: " + a5.manufacturingDate);
		System.out.println("expiryDate: " + a5.expiryDate);
		System.out.println("soundType: " + a5.soundType);
		System.out.println("material: " + a5.material);
		System.out.println("powerOutput: " + a5.powerOutput);
		System.out.println("isWaterproof: " + a5.isWaterproof);
		System.out.println("countryOfOrigin: " + a5.countryOfOrigin);
		System.out.println("warrantyMonths: " + a5.warrantyMonths);
		System.out.println("packagingType: " + a5.packagingType);
		System.out.println("weight: " + a5.weight);
		System.out.println("isPortable: " + a5.isPortable);
		System.out.println("feature1: " + a5.feature1);
		System.out.println("feature2: " + a5.feature2);
		System.out.println("feature3: " + a5.feature3);
		System.out.println("hasBluetooth: " + a5.hasBluetooth);
		System.out.println("hasMic: " + a5.hasMic);
		System.out.println("rating: " + a5.rating);


		AuroraSpeaker a6 = new AuroraSpeaker();
		a6.productId = 106;
		a6.brandName = "Sample6";
		a6.connectivityType = "Sample6";
		a6.color = "Sample6";
		a6.batteryCapacity = 16.0;
		a6.price = 16.0;
		a6.isWireless = true;
		a6.isAvailable = true;
		a6.manufacturingDate = "Sample6";
		a6.expiryDate = "Sample6";
		a6.soundType = "Sample6";
		a6.material = "Sample6";
		a6.powerOutput = 16.0;
		a6.isWaterproof = true;
		a6.countryOfOrigin = "Sample6";
		a6.warrantyMonths = 106;
		a6.packagingType = "Sample6";
		a6.weight = 16.0;
		a6.isPortable = true;
		a6.feature1 = "Sample6";
		a6.feature2 = "Sample6";
		a6.feature3 = "Sample6";
		a6.hasBluetooth = true;
		a6.hasMic = true;
		a6.rating = 106;

		System.out.println("----- AuroraSpeaker 6 -----");
		System.out.println("productId: " + a6.productId);
		System.out.println("brandName: " + a6.brandName);
		System.out.println("connectivityType: " + a6.connectivityType);
		System.out.println("color: " + a6.color);
		System.out.println("batteryCapacity: " + a6.batteryCapacity);
		System.out.println("price: " + a6.price);
		System.out.println("isWireless: " + a6.isWireless);
		System.out.println("isAvailable: " + a6.isAvailable);
		System.out.println("manufacturingDate: " + a6.manufacturingDate);
		System.out.println("expiryDate: " + a6.expiryDate);
		System.out.println("soundType: " + a6.soundType);
		System.out.println("material: " + a6.material);
		System.out.println("powerOutput: " + a6.powerOutput);
		System.out.println("isWaterproof: " + a6.isWaterproof);
		System.out.println("countryOfOrigin: " + a6.countryOfOrigin);
		System.out.println("warrantyMonths: " + a6.warrantyMonths);
		System.out.println("packagingType: " + a6.packagingType);
		System.out.println("weight: " + a6.weight);
		System.out.println("isPortable: " + a6.isPortable);
		System.out.println("feature1: " + a6.feature1);
		System.out.println("feature2: " + a6.feature2);
		System.out.println("feature3: " + a6.feature3);
		System.out.println("hasBluetooth: " + a6.hasBluetooth);
		System.out.println("hasMic: " + a6.hasMic);
		System.out.println("rating: " + a6.rating);


		AuroraSpeaker a7 = new AuroraSpeaker();
		a7.productId = 107;
		a7.brandName = "Sample7";
		a7.connectivityType = "Sample7";
		a7.color = "Sample7";
		a7.batteryCapacity = 17.0;
		a7.price = 17.0;
		a7.isWireless = false;
		a7.isAvailable = false;
		a7.manufacturingDate = "Sample7";
		a7.expiryDate = "Sample7";
		a7.soundType = "Sample7";
		a7.material = "Sample7";
		a7.powerOutput = 17.0;
		a7.isWaterproof = false;
		a7.countryOfOrigin = "Sample7";
		a7.warrantyMonths = 107;
		a7.packagingType = "Sample7";
		a7.weight = 17.0;
		a7.isPortable = false;
		a7.feature1 = "Sample7";
		a7.feature2 = "Sample7";
		a7.feature3 = "Sample7";
		a7.hasBluetooth = false;
		a7.hasMic = false;
		a7.rating = 107;

		System.out.println("----- AuroraSpeaker 7 -----");
		System.out.println("productId: " + a7.productId);
		System.out.println("brandName: " + a7.brandName);
		System.out.println("connectivityType: " + a7.connectivityType);
		System.out.println("color: " + a7.color);
		System.out.println("batteryCapacity: " + a7.batteryCapacity);
		System.out.println("price: " + a7.price);
		System.out.println("isWireless: " + a7.isWireless);
		System.out.println("isAvailable: " + a7.isAvailable);
		System.out.println("manufacturingDate: " + a7.manufacturingDate);
		System.out.println("expiryDate: " + a7.expiryDate);
		System.out.println("soundType: " + a7.soundType);
		System.out.println("material: " + a7.material);
		System.out.println("powerOutput: " + a7.powerOutput);
		System.out.println("isWaterproof: " + a7.isWaterproof);
		System.out.println("countryOfOrigin: " + a7.countryOfOrigin);
		System.out.println("warrantyMonths: " + a7.warrantyMonths);
		System.out.println("packagingType: " + a7.packagingType);
		System.out.println("weight: " + a7.weight);
		System.out.println("isPortable: " + a7.isPortable);
		System.out.println("feature1: " + a7.feature1);
		System.out.println("feature2: " + a7.feature2);
		System.out.println("feature3: " + a7.feature3);
		System.out.println("hasBluetooth: " + a7.hasBluetooth);
		System.out.println("hasMic: " + a7.hasMic);
		System.out.println("rating: " + a7.rating);


		AuroraSpeaker a8 = new AuroraSpeaker();
		a8.productId = 108;
		a8.brandName = "Sample8";
		a8.connectivityType = "Sample8";
		a8.color = "Sample8";
		a8.batteryCapacity = 18.0;
		a8.price = 18.0;
		a8.isWireless = true;
		a8.isAvailable = true;
		a8.manufacturingDate = "Sample8";
		a8.expiryDate = "Sample8";
		a8.soundType = "Sample8";
		a8.material = "Sample8";
		a8.powerOutput = 18.0;
		a8.isWaterproof = true;
		a8.countryOfOrigin = "Sample8";
		a8.warrantyMonths = 108;
		a8.packagingType = "Sample8";
		a8.weight = 18.0;
		a8.isPortable = true;
		a8.feature1 = "Sample8";
		a8.feature2 = "Sample8";
		a8.feature3 = "Sample8";
		a8.hasBluetooth = true;
		a8.hasMic = true;
		a8.rating = 108;

		System.out.println("----- AuroraSpeaker 8 -----");
		System.out.println("productId: " + a8.productId);
		System.out.println("brandName: " + a8.brandName);
		System.out.println("connectivityType: " + a8.connectivityType);
		System.out.println("color: " + a8.color);
		System.out.println("batteryCapacity: " + a8.batteryCapacity);
		System.out.println("price: " + a8.price);
		System.out.println("isWireless: " + a8.isWireless);
		System.out.println("isAvailable: " + a8.isAvailable);
		System.out.println("manufacturingDate: " + a8.manufacturingDate);
		System.out.println("expiryDate: " + a8.expiryDate);
		System.out.println("soundType: " + a8.soundType);
		System.out.println("material: " + a8.material);
		System.out.println("powerOutput: " + a8.powerOutput);
		System.out.println("isWaterproof: " + a8.isWaterproof);
		System.out.println("countryOfOrigin: " + a8.countryOfOrigin);
		System.out.println("warrantyMonths: " + a8.warrantyMonths);
		System.out.println("packagingType: " + a8.packagingType);
		System.out.println("weight: " + a8.weight);
		System.out.println("isPortable: " + a8.isPortable);
		System.out.println("feature1: " + a8.feature1);
		System.out.println("feature2: " + a8.feature2);
		System.out.println("feature3: " + a8.feature3);
		System.out.println("hasBluetooth: " + a8.hasBluetooth);
		System.out.println("hasMic: " + a8.hasMic);
		System.out.println("rating: " + a8.rating);


		AuroraSpeaker a9 = new AuroraSpeaker();
		a9.productId = 109;
		a9.brandName = "Sample9";
		a9.connectivityType = "Sample9";
		a9.color = "Sample9";
		a9.batteryCapacity = 19.0;
		a9.price = 19.0;
		a9.isWireless = false;
		a9.isAvailable = false;
		a9.manufacturingDate = "Sample9";
		a9.expiryDate = "Sample9";
		a9.soundType = "Sample9";
		a9.material = "Sample9";
		a9.powerOutput = 19.0;
		a9.isWaterproof = false;
		a9.countryOfOrigin = "Sample9";
		a9.warrantyMonths = 109;
		a9.packagingType = "Sample9";
		a9.weight = 19.0;
		a9.isPortable = false;
		a9.feature1 = "Sample9";
		a9.feature2 = "Sample9";
		a9.feature3 = "Sample9";
		a9.hasBluetooth = false;
		a9.hasMic = false;
		a9.rating = 109;

		System.out.println("----- AuroraSpeaker 9 -----");
		System.out.println("productId: " + a9.productId);
		System.out.println("brandName: " + a9.brandName);
		System.out.println("connectivityType: " + a9.connectivityType);
		System.out.println("color: " + a9.color);
		System.out.println("batteryCapacity: " + a9.batteryCapacity);
		System.out.println("price: " + a9.price);
		System.out.println("isWireless: " + a9.isWireless);
		System.out.println("isAvailable: " + a9.isAvailable);
		System.out.println("manufacturingDate: " + a9.manufacturingDate);
		System.out.println("expiryDate: " + a9.expiryDate);
		System.out.println("soundType: " + a9.soundType);
		System.out.println("material: " + a9.material);
		System.out.println("powerOutput: " + a9.powerOutput);
		System.out.println("isWaterproof: " + a9.isWaterproof);
		System.out.println("countryOfOrigin: " + a9.countryOfOrigin);
		System.out.println("warrantyMonths: " + a9.warrantyMonths);
		System.out.println("packagingType: " + a9.packagingType);
		System.out.println("weight: " + a9.weight);
		System.out.println("isPortable: " + a9.isPortable);
		System.out.println("feature1: " + a9.feature1);
		System.out.println("feature2: " + a9.feature2);
		System.out.println("feature3: " + a9.feature3);
		System.out.println("hasBluetooth: " + a9.hasBluetooth);
		System.out.println("hasMic: " + a9.hasMic);
		System.out.println("rating: " + a9.rating);


		AuroraSpeaker a10 = new AuroraSpeaker();
		a10.productId = 110;
		a10.brandName = "Sample10";
		a10.connectivityType = "Sample10";
		a10.color = "Sample10";
		a10.batteryCapacity = 20.0;
		a10.price = 20.0;
		a10.isWireless = true;
		a10.isAvailable = true;
		a10.manufacturingDate = "Sample10";
		a10.expiryDate = "Sample10";
		a10.soundType = "Sample10";
		a10.material = "Sample10";
		a10.powerOutput = 20.0;
		a10.isWaterproof = true;
		a10.countryOfOrigin = "Sample10";
		a10.warrantyMonths = 110;
		a10.packagingType = "Sample10";
		a10.weight = 20.0;
		a10.isPortable = true;
		a10.feature1 = "Sample10";
		a10.feature2 = "Sample10";
		a10.feature3 = "Sample10";
		a10.hasBluetooth = true;
		a10.hasMic = true;
		a10.rating = 110;

		System.out.println("----- AuroraSpeaker 10 -----");
		System.out.println("productId: " + a10.productId);
		System.out.println("brandName: " + a10.brandName);
		System.out.println("connectivityType: " + a10.connectivityType);
		System.out.println("color: " + a10.color);
		System.out.println("batteryCapacity: " + a10.batteryCapacity);
		System.out.println("price: " + a10.price);
		System.out.println("isWireless: " + a10.isWireless);
		System.out.println("isAvailable: " + a10.isAvailable);
		System.out.println("manufacturingDate: " + a10.manufacturingDate);
		System.out.println("expiryDate: " + a10.expiryDate);
		System.out.println("soundType: " + a10.soundType);
		System.out.println("material: " + a10.material);
		System.out.println("powerOutput: " + a10.powerOutput);
		System.out.println("isWaterproof: " + a10.isWaterproof);
		System.out.println("countryOfOrigin: " + a10.countryOfOrigin);
		System.out.println("warrantyMonths: " + a10.warrantyMonths);
		System.out.println("packagingType: " + a10.packagingType);
		System.out.println("weight: " + a10.weight);
		System.out.println("isPortable: " + a10.isPortable);
		System.out.println("feature1: " + a10.feature1);
		System.out.println("feature2: " + a10.feature2);
		System.out.println("feature3: " + a10.feature3);
		System.out.println("hasBluetooth: " + a10.hasBluetooth);
		System.out.println("hasMic: " + a10.hasMic);
		System.out.println("rating: " + a10.rating);


		AuroraSpeaker a11 = new AuroraSpeaker();
		a11.productId = 111;
		a11.brandName = "Sample11";
		a11.connectivityType = "Sample11";
		a11.color = "Sample11";
		a11.batteryCapacity = 21.0;
		a11.price = 21.0;
		a11.isWireless = false;
		a11.isAvailable = false;
		a11.manufacturingDate = "Sample11";
		a11.expiryDate = "Sample11";
		a11.soundType = "Sample11";
		a11.material = "Sample11";
		a11.powerOutput = 21.0;
		a11.isWaterproof = false;
		a11.countryOfOrigin = "Sample11";
		a11.warrantyMonths = 111;
		a11.packagingType = "Sample11";
		a11.weight = 21.0;
		a11.isPortable = false;
		a11.feature1 = "Sample11";
		a11.feature2 = "Sample11";
		a11.feature3 = "Sample11";
		a11.hasBluetooth = false;
		a11.hasMic = false;
		a11.rating = 111;

		System.out.println("----- AuroraSpeaker 11 -----");
		System.out.println("productId: " + a11.productId);
		System.out.println("brandName: " + a11.brandName);
		System.out.println("connectivityType: " + a11.connectivityType);
		System.out.println("color: " + a11.color);
		System.out.println("batteryCapacity: " + a11.batteryCapacity);
		System.out.println("price: " + a11.price);
		System.out.println("isWireless: " + a11.isWireless);
		System.out.println("isAvailable: " + a11.isAvailable);
		System.out.println("manufacturingDate: " + a11.manufacturingDate);
		System.out.println("expiryDate: " + a11.expiryDate);
		System.out.println("soundType: " + a11.soundType);
		System.out.println("material: " + a11.material);
		System.out.println("powerOutput: " + a11.powerOutput);
		System.out.println("isWaterproof: " + a11.isWaterproof);
		System.out.println("countryOfOrigin: " + a11.countryOfOrigin);
		System.out.println("warrantyMonths: " + a11.warrantyMonths);
		System.out.println("packagingType: " + a11.packagingType);
		System.out.println("weight: " + a11.weight);
		System.out.println("isPortable: " + a11.isPortable);
		System.out.println("feature1: " + a11.feature1);
		System.out.println("feature2: " + a11.feature2);
		System.out.println("feature3: " + a11.feature3);
		System.out.println("hasBluetooth: " + a11.hasBluetooth);
		System.out.println("hasMic: " + a11.hasMic);
		System.out.println("rating: " + a11.rating);


		AuroraSpeaker a12 = new AuroraSpeaker();
		a12.productId = 112;
		a12.brandName = "Sample12";
		a12.connectivityType = "Sample12";
		a12.color = "Sample12";
		a12.batteryCapacity = 22.0;
		a12.price = 22.0;
		a12.isWireless = true;
		a12.isAvailable = true;
		a12.manufacturingDate = "Sample12";
		a12.expiryDate = "Sample12";
		a12.soundType = "Sample12";
		a12.material = "Sample12";
		a12.powerOutput = 22.0;
		a12.isWaterproof = true;
		a12.countryOfOrigin = "Sample12";
		a12.warrantyMonths = 112;
		a12.packagingType = "Sample12";
		a12.weight = 22.0;
		a12.isPortable = true;
		a12.feature1 = "Sample12";
		a12.feature2 = "Sample12";
		a12.feature3 = "Sample12";
		a12.hasBluetooth = true;
		a12.hasMic = true;
		a12.rating = 112;

		System.out.println("----- AuroraSpeaker 12 -----");
		System.out.println("productId: " + a12.productId);
		System.out.println("brandName: " + a12.brandName);
		System.out.println("connectivityType: " + a12.connectivityType);
		System.out.println("color: " + a12.color);
		System.out.println("batteryCapacity: " + a12.batteryCapacity);
		System.out.println("price: " + a12.price);
		System.out.println("isWireless: " + a12.isWireless);
		System.out.println("isAvailable: " + a12.isAvailable);
		System.out.println("manufacturingDate: " + a12.manufacturingDate);
		System.out.println("expiryDate: " + a12.expiryDate);
		System.out.println("soundType: " + a12.soundType);
		System.out.println("material: " + a12.material);
		System.out.println("powerOutput: " + a12.powerOutput);
		System.out.println("isWaterproof: " + a12.isWaterproof);
		System.out.println("countryOfOrigin: " + a12.countryOfOrigin);
		System.out.println("warrantyMonths: " + a12.warrantyMonths);
		System.out.println("packagingType: " + a12.packagingType);
		System.out.println("weight: " + a12.weight);
		System.out.println("isPortable: " + a12.isPortable);
		System.out.println("feature1: " + a12.feature1);
		System.out.println("feature2: " + a12.feature2);
		System.out.println("feature3: " + a12.feature3);
		System.out.println("hasBluetooth: " + a12.hasBluetooth);
		System.out.println("hasMic: " + a12.hasMic);
		System.out.println("rating: " + a12.rating);


		AuroraSpeaker a13 = new AuroraSpeaker();
		a13.productId = 113;
		a13.brandName = "Sample13";
		a13.connectivityType = "Sample13";
		a13.color = "Sample13";
		a13.batteryCapacity = 23.0;
		a13.price = 23.0;
		a13.isWireless = false;
		a13.isAvailable = false;
		a13.manufacturingDate = "Sample13";
		a13.expiryDate = "Sample13";
		a13.soundType = "Sample13";
		a13.material = "Sample13";
		a13.powerOutput = 23.0;
		a13.isWaterproof = false;
		a13.countryOfOrigin = "Sample13";
		a13.warrantyMonths = 113;
		a13.packagingType = "Sample13";
		a13.weight = 23.0;
		a13.isPortable = false;
		a13.feature1 = "Sample13";
		a13.feature2 = "Sample13";
		a13.feature3 = "Sample13";
		a13.hasBluetooth = false;
		a13.hasMic = false;
		a13.rating = 113;

		System.out.println("----- AuroraSpeaker 13 -----");
		System.out.println("productId: " + a13.productId);
		System.out.println("brandName: " + a13.brandName);
		System.out.println("connectivityType: " + a13.connectivityType);
		System.out.println("color: " + a13.color);
		System.out.println("batteryCapacity: " + a13.batteryCapacity);
		System.out.println("price: " + a13.price);
		System.out.println("isWireless: " + a13.isWireless);
		System.out.println("isAvailable: " + a13.isAvailable);
		System.out.println("manufacturingDate: " + a13.manufacturingDate);
		System.out.println("expiryDate: " + a13.expiryDate);
		System.out.println("soundType: " + a13.soundType);
		System.out.println("material: " + a13.material);
		System.out.println("powerOutput: " + a13.powerOutput);
		System.out.println("isWaterproof: " + a13.isWaterproof);
		System.out.println("countryOfOrigin: " + a13.countryOfOrigin);
		System.out.println("warrantyMonths: " + a13.warrantyMonths);
		System.out.println("packagingType: " + a13.packagingType);
		System.out.println("weight: " + a13.weight);
		System.out.println("isPortable: " + a13.isPortable);
		System.out.println("feature1: " + a13.feature1);
		System.out.println("feature2: " + a13.feature2);
		System.out.println("feature3: " + a13.feature3);
		System.out.println("hasBluetooth: " + a13.hasBluetooth);
		System.out.println("hasMic: " + a13.hasMic);
		System.out.println("rating: " + a13.rating);


		AuroraSpeaker a14 = new AuroraSpeaker();
		a14.productId = 114;
		a14.brandName = "Sample14";
		a14.connectivityType = "Sample14";
		a14.color = "Sample14";
		a14.batteryCapacity = 24.0;
		a14.price = 24.0;
		a14.isWireless = true;
		a14.isAvailable = true;
		a14.manufacturingDate = "Sample14";
		a14.expiryDate = "Sample14";
		a14.soundType = "Sample14";
		a14.material = "Sample14";
		a14.powerOutput = 24.0;
		a14.isWaterproof = true;
		a14.countryOfOrigin = "Sample14";
		a14.warrantyMonths = 114;
		a14.packagingType = "Sample14";
		a14.weight = 24.0;
		a14.isPortable = true;
		a14.feature1 = "Sample14";
		a14.feature2 = "Sample14";
		a14.feature3 = "Sample14";
		a14.hasBluetooth = true;
		a14.hasMic = true;
		a14.rating = 114;

		System.out.println("----- AuroraSpeaker 14 -----");
		System.out.println("productId: " + a14.productId);
		System.out.println("brandName: " + a14.brandName);
		System.out.println("connectivityType: " + a14.connectivityType);
		System.out.println("color: " + a14.color);
		System.out.println("batteryCapacity: " + a14.batteryCapacity);
		System.out.println("price: " + a14.price);
		System.out.println("isWireless: " + a14.isWireless);
		System.out.println("isAvailable: " + a14.isAvailable);
		System.out.println("manufacturingDate: " + a14.manufacturingDate);
		System.out.println("expiryDate: " + a14.expiryDate);
		System.out.println("soundType: " + a14.soundType);
		System.out.println("material: " + a14.material);
		System.out.println("powerOutput: " + a14.powerOutput);
		System.out.println("isWaterproof: " + a14.isWaterproof);
		System.out.println("countryOfOrigin: " + a14.countryOfOrigin);
		System.out.println("warrantyMonths: " + a14.warrantyMonths);
		System.out.println("packagingType: " + a14.packagingType);
		System.out.println("weight: " + a14.weight);
		System.out.println("isPortable: " + a14.isPortable);
		System.out.println("feature1: " + a14.feature1);
		System.out.println("feature2: " + a14.feature2);
		System.out.println("feature3: " + a14.feature3);
		System.out.println("hasBluetooth: " + a14.hasBluetooth);
		System.out.println("hasMic: " + a14.hasMic);
		System.out.println("rating: " + a14.rating);


		AuroraSpeaker a15 = new AuroraSpeaker();
		a15.productId = 115;
		a15.brandName = "Sample15";
		a15.connectivityType = "Sample15";
		a15.color = "Sample15";
		a15.batteryCapacity = 25.0;
		a15.price = 25.0;
		a15.isWireless = false;
		a15.isAvailable = false;
		a15.manufacturingDate = "Sample15";
		a15.expiryDate = "Sample15";
		a15.soundType = "Sample15";
		a15.material = "Sample15";
		a15.powerOutput = 25.0;
		a15.isWaterproof = false;
		a15.countryOfOrigin = "Sample15";
		a15.warrantyMonths = 115;
		a15.packagingType = "Sample15";
		a15.weight = 25.0;
		a15.isPortable = false;
		a15.feature1 = "Sample15";
		a15.feature2 = "Sample15";
		a15.feature3 = "Sample15";
		a15.hasBluetooth = false;
		a15.hasMic = false;
		a15.rating = 115;

		System.out.println("----- AuroraSpeaker 15 -----");
		System.out.println("productId: " + a15.productId);
		System.out.println("brandName: " + a15.brandName);
		System.out.println("connectivityType: " + a15.connectivityType);
		System.out.println("color: " + a15.color);
		System.out.println("batteryCapacity: " + a15.batteryCapacity);
		System.out.println("price: " + a15.price);
		System.out.println("isWireless: " + a15.isWireless);
		System.out.println("isAvailable: " + a15.isAvailable);
		System.out.println("manufacturingDate: " + a15.manufacturingDate);
		System.out.println("expiryDate: " + a15.expiryDate);
		System.out.println("soundType: " + a15.soundType);
		System.out.println("material: " + a15.material);
		System.out.println("powerOutput: " + a15.powerOutput);
		System.out.println("isWaterproof: " + a15.isWaterproof);
		System.out.println("countryOfOrigin: " + a15.countryOfOrigin);
		System.out.println("warrantyMonths: " + a15.warrantyMonths);
		System.out.println("packagingType: " + a15.packagingType);
		System.out.println("weight: " + a15.weight);
		System.out.println("isPortable: " + a15.isPortable);
		System.out.println("feature1: " + a15.feature1);
		System.out.println("feature2: " + a15.feature2);
		System.out.println("feature3: " + a15.feature3);
		System.out.println("hasBluetooth: " + a15.hasBluetooth);
		System.out.println("hasMic: " + a15.hasMic);
		System.out.println("rating: " + a15.rating);


		AuroraSpeaker a16 = new AuroraSpeaker();
		a16.productId = 116;
		a16.brandName = "Sample16";
		a16.connectivityType = "Sample16";
		a16.color = "Sample16";
		a16.batteryCapacity = 26.0;
		a16.price = 26.0;
		a16.isWireless = true;
		a16.isAvailable = true;
		a16.manufacturingDate = "Sample16";
		a16.expiryDate = "Sample16";
		a16.soundType = "Sample16";
		a16.material = "Sample16";
		a16.powerOutput = 26.0;
		a16.isWaterproof = true;
		a16.countryOfOrigin = "Sample16";
		a16.warrantyMonths = 116;
		a16.packagingType = "Sample16";
		a16.weight = 26.0;
		a16.isPortable = true;
		a16.feature1 = "Sample16";
		a16.feature2 = "Sample16";
		a16.feature3 = "Sample16";
		a16.hasBluetooth = true;
		a16.hasMic = true;
		a16.rating = 116;

		System.out.println("----- AuroraSpeaker 16 -----");
		System.out.println("productId: " + a16.productId);
		System.out.println("brandName: " + a16.brandName);
		System.out.println("connectivityType: " + a16.connectivityType);
		System.out.println("color: " + a16.color);
		System.out.println("batteryCapacity: " + a16.batteryCapacity);
		System.out.println("price: " + a16.price);
		System.out.println("isWireless: " + a16.isWireless);
		System.out.println("isAvailable: " + a16.isAvailable);
		System.out.println("manufacturingDate: " + a16.manufacturingDate);
		System.out.println("expiryDate: " + a16.expiryDate);
		System.out.println("soundType: " + a16.soundType);
		System.out.println("material: " + a16.material);
		System.out.println("powerOutput: " + a16.powerOutput);
		System.out.println("isWaterproof: " + a16.isWaterproof);
		System.out.println("countryOfOrigin: " + a16.countryOfOrigin);
		System.out.println("warrantyMonths: " + a16.warrantyMonths);
		System.out.println("packagingType: " + a16.packagingType);
		System.out.println("weight: " + a16.weight);
		System.out.println("isPortable: " + a16.isPortable);
		System.out.println("feature1: " + a16.feature1);
		System.out.println("feature2: " + a16.feature2);
		System.out.println("feature3: " + a16.feature3);
		System.out.println("hasBluetooth: " + a16.hasBluetooth);
		System.out.println("hasMic: " + a16.hasMic);
		System.out.println("rating: " + a16.rating);


		AuroraSpeaker a17 = new AuroraSpeaker();
		a17.productId = 117;
		a17.brandName = "Sample17";
		a17.connectivityType = "Sample17";
		a17.color = "Sample17";
		a17.batteryCapacity = 27.0;
		a17.price = 27.0;
		a17.isWireless = false;
		a17.isAvailable = false;
		a17.manufacturingDate = "Sample17";
		a17.expiryDate = "Sample17";
		a17.soundType = "Sample17";
		a17.material = "Sample17";
		a17.powerOutput = 27.0;
		a17.isWaterproof = false;
		a17.countryOfOrigin = "Sample17";
		a17.warrantyMonths = 117;
		a17.packagingType = "Sample17";
		a17.weight = 27.0;
		a17.isPortable = false;
		a17.feature1 = "Sample17";
		a17.feature2 = "Sample17";
		a17.feature3 = "Sample17";
		a17.hasBluetooth = false;
		a17.hasMic = false;
		a17.rating = 117;

		System.out.println("----- AuroraSpeaker 17 -----");
		System.out.println("productId: " + a17.productId);
		System.out.println("brandName: " + a17.brandName);
		System.out.println("connectivityType: " + a17.connectivityType);
		System.out.println("color: " + a17.color);
		System.out.println("batteryCapacity: " + a17.batteryCapacity);
		System.out.println("price: " + a17.price);
		System.out.println("isWireless: " + a17.isWireless);
		System.out.println("isAvailable: " + a17.isAvailable);
		System.out.println("manufacturingDate: " + a17.manufacturingDate);
		System.out.println("expiryDate: " + a17.expiryDate);
		System.out.println("soundType: " + a17.soundType);
		System.out.println("material: " + a17.material);
		System.out.println("powerOutput: " + a17.powerOutput);
		System.out.println("isWaterproof: " + a17.isWaterproof);
		System.out.println("countryOfOrigin: " + a17.countryOfOrigin);
		System.out.println("warrantyMonths: " + a17.warrantyMonths);
		System.out.println("packagingType: " + a17.packagingType);
		System.out.println("weight: " + a17.weight);
		System.out.println("isPortable: " + a17.isPortable);
		System.out.println("feature1: " + a17.feature1);
		System.out.println("feature2: " + a17.feature2);
		System.out.println("feature3: " + a17.feature3);
		System.out.println("hasBluetooth: " + a17.hasBluetooth);
		System.out.println("hasMic: " + a17.hasMic);
		System.out.println("rating: " + a17.rating);


		AuroraSpeaker a18 = new AuroraSpeaker();
		a18.productId = 118;
		a18.brandName = "Sample18";
		a18.connectivityType = "Sample18";
		a18.color = "Sample18";
		a18.batteryCapacity = 28.0;
		a18.price = 28.0;
		a18.isWireless = true;
		a18.isAvailable = true;
		a18.manufacturingDate = "Sample18";
		a18.expiryDate = "Sample18";
		a18.soundType = "Sample18";
		a18.material = "Sample18";
		a18.powerOutput = 28.0;
		a18.isWaterproof = true;
		a18.countryOfOrigin = "Sample18";
		a18.warrantyMonths = 118;
		a18.packagingType = "Sample18";
		a18.weight = 28.0;
		a18.isPortable = true;
		a18.feature1 = "Sample18";
		a18.feature2 = "Sample18";
		a18.feature3 = "Sample18";
		a18.hasBluetooth = true;
		a18.hasMic = true;
		a18.rating = 118;

		System.out.println("----- AuroraSpeaker 18 -----");
		System.out.println("productId: " + a18.productId);
		System.out.println("brandName: " + a18.brandName);
		System.out.println("connectivityType: " + a18.connectivityType);
		System.out.println("color: " + a18.color);
		System.out.println("batteryCapacity: " + a18.batteryCapacity);
		System.out.println("price: " + a18.price);
		System.out.println("isWireless: " + a18.isWireless);
		System.out.println("isAvailable: " + a18.isAvailable);
		System.out.println("manufacturingDate: " + a18.manufacturingDate);
		System.out.println("expiryDate: " + a18.expiryDate);
		System.out.println("soundType: " + a18.soundType);
		System.out.println("material: " + a18.material);
		System.out.println("powerOutput: " + a18.powerOutput);
		System.out.println("isWaterproof: " + a18.isWaterproof);
		System.out.println("countryOfOrigin: " + a18.countryOfOrigin);
		System.out.println("warrantyMonths: " + a18.warrantyMonths);
		System.out.println("packagingType: " + a18.packagingType);
		System.out.println("weight: " + a18.weight);
		System.out.println("isPortable: " + a18.isPortable);
		System.out.println("feature1: " + a18.feature1);
		System.out.println("feature2: " + a18.feature2);
		System.out.println("feature3: " + a18.feature3);
		System.out.println("hasBluetooth: " + a18.hasBluetooth);
		System.out.println("hasMic: " + a18.hasMic);
		System.out.println("rating: " + a18.rating);


		AuroraSpeaker a19 = new AuroraSpeaker();
		a19.productId = 119;
		a19.brandName = "Sample19";
		a19.connectivityType = "Sample19";
		a19.color = "Sample19";
		a19.batteryCapacity = 29.0;
		a19.price = 29.0;
		a19.isWireless = false;
		a19.isAvailable = false;
		a19.manufacturingDate = "Sample19";
		a19.expiryDate = "Sample19";
		a19.soundType = "Sample19";
		a19.material = "Sample19";
		a19.powerOutput = 29.0;
		a19.isWaterproof = false;
		a19.countryOfOrigin = "Sample19";
		a19.warrantyMonths = 119;
		a19.packagingType = "Sample19";
		a19.weight = 29.0;
		a19.isPortable = false;
		a19.feature1 = "Sample19";
		a19.feature2 = "Sample19";
		a19.feature3 = "Sample19";
		a19.hasBluetooth = false;
		a19.hasMic = false;
		a19.rating = 119;

		System.out.println("----- AuroraSpeaker 19 -----");
		System.out.println("productId: " + a19.productId);
		System.out.println("brandName: " + a19.brandName);
		System.out.println("connectivityType: " + a19.connectivityType);
		System.out.println("color: " + a19.color);
		System.out.println("batteryCapacity: " + a19.batteryCapacity);
		System.out.println("price: " + a19.price);
		System.out.println("isWireless: " + a19.isWireless);
		System.out.println("isAvailable: " + a19.isAvailable);
		System.out.println("manufacturingDate: " + a19.manufacturingDate);
		System.out.println("expiryDate: " + a19.expiryDate);
		System.out.println("soundType: " + a19.soundType);
		System.out.println("material: " + a19.material);
		System.out.println("powerOutput: " + a19.powerOutput);
		System.out.println("isWaterproof: " + a19.isWaterproof);
		System.out.println("countryOfOrigin: " + a19.countryOfOrigin);
		System.out.println("warrantyMonths: " + a19.warrantyMonths);
		System.out.println("packagingType: " + a19.packagingType);
		System.out.println("weight: " + a19.weight);
		System.out.println("isPortable: " + a19.isPortable);
		System.out.println("feature1: " + a19.feature1);
		System.out.println("feature2: " + a19.feature2);
		System.out.println("feature3: " + a19.feature3);
		System.out.println("hasBluetooth: " + a19.hasBluetooth);
		System.out.println("hasMic: " + a19.hasMic);
		System.out.println("rating: " + a19.rating);


		AuroraSpeaker a20 = new AuroraSpeaker();
		a20.productId = 120;
		a20.brandName = "Sample20";
		a20.connectivityType = "Sample20";
		a20.color = "Sample20";
		a20.batteryCapacity = 30.0;
		a20.price = 30.0;
		a20.isWireless = true;
		a20.isAvailable = true;
		a20.manufacturingDate = "Sample20";
		a20.expiryDate = "Sample20";
		a20.soundType = "Sample20";
		a20.material = "Sample20";
		a20.powerOutput = 30.0;
		a20.isWaterproof = true;
		a20.countryOfOrigin = "Sample20";
		a20.warrantyMonths = 120;
		a20.packagingType = "Sample20";
		a20.weight = 30.0;
		a20.isPortable = true;
		a20.feature1 = "Sample20";
		a20.feature2 = "Sample20";
		a20.feature3 = "Sample20";
		a20.hasBluetooth = true;
		a20.hasMic = true;
		a20.rating = 120;

		System.out.println("----- AuroraSpeaker 20 -----");
		System.out.println("productId: " + a20.productId);
		System.out.println("brandName: " + a20.brandName);
		System.out.println("connectivityType: " + a20.connectivityType);
		System.out.println("color: " + a20.color);
		System.out.println("batteryCapacity: " + a20.batteryCapacity);
		System.out.println("price: " + a20.price);
		System.out.println("isWireless: " + a20.isWireless);
		System.out.println("isAvailable: " + a20.isAvailable);
		System.out.println("manufacturingDate: " + a20.manufacturingDate);
		System.out.println("expiryDate: " + a20.expiryDate);
		System.out.println("soundType: " + a20.soundType);
		System.out.println("material: " + a20.material);
		System.out.println("powerOutput: " + a20.powerOutput);
		System.out.println("isWaterproof: " + a20.isWaterproof);
		System.out.println("countryOfOrigin: " + a20.countryOfOrigin);
		System.out.println("warrantyMonths: " + a20.warrantyMonths);
		System.out.println("packagingType: " + a20.packagingType);
		System.out.println("weight: " + a20.weight);
		System.out.println("isPortable: " + a20.isPortable);
		System.out.println("feature1: " + a20.feature1);
		System.out.println("feature2: " + a20.feature2);
		System.out.println("feature3: " + a20.feature3);
		System.out.println("hasBluetooth: " + a20.hasBluetooth);
		System.out.println("hasMic: " + a20.hasMic);
		System.out.println("rating: " + a20.rating);


		AuroraSpeaker a21 = new AuroraSpeaker();
		a21.productId = 121;
		a21.brandName = "Sample21";
		a21.connectivityType = "Sample21";
		a21.color = "Sample21";
		a21.batteryCapacity = 31.0;
		a21.price = 31.0;
		a21.isWireless = false;
		a21.isAvailable = false;
		a21.manufacturingDate = "Sample21";
		a21.expiryDate = "Sample21";
		a21.soundType = "Sample21";
		a21.material = "Sample21";
		a21.powerOutput = 31.0;
		a21.isWaterproof = false;
		a21.countryOfOrigin = "Sample21";
		a21.warrantyMonths = 121;
		a21.packagingType = "Sample21";
		a21.weight = 31.0;
		a21.isPortable = false;
		a21.feature1 = "Sample21";
		a21.feature2 = "Sample21";
		a21.feature3 = "Sample21";
		a21.hasBluetooth = false;
		a21.hasMic = false;
		a21.rating = 121;

		System.out.println("----- AuroraSpeaker 21 -----");
		System.out.println("productId: " + a21.productId);
		System.out.println("brandName: " + a21.brandName);
		System.out.println("connectivityType: " + a21.connectivityType);
		System.out.println("color: " + a21.color);
		System.out.println("batteryCapacity: " + a21.batteryCapacity);
		System.out.println("price: " + a21.price);
		System.out.println("isWireless: " + a21.isWireless);
		System.out.println("isAvailable: " + a21.isAvailable);
		System.out.println("manufacturingDate: " + a21.manufacturingDate);
		System.out.println("expiryDate: " + a21.expiryDate);
		System.out.println("soundType: " + a21.soundType);
		System.out.println("material: " + a21.material);
		System.out.println("powerOutput: " + a21.powerOutput);
		System.out.println("isWaterproof: " + a21.isWaterproof);
		System.out.println("countryOfOrigin: " + a21.countryOfOrigin);
		System.out.println("warrantyMonths: " + a21.warrantyMonths);
		System.out.println("packagingType: " + a21.packagingType);
		System.out.println("weight: " + a21.weight);
		System.out.println("isPortable: " + a21.isPortable);
		System.out.println("feature1: " + a21.feature1);
		System.out.println("feature2: " + a21.feature2);
		System.out.println("feature3: " + a21.feature3);
		System.out.println("hasBluetooth: " + a21.hasBluetooth);
		System.out.println("hasMic: " + a21.hasMic);
		System.out.println("rating: " + a21.rating);


		AuroraSpeaker a22 = new AuroraSpeaker();
		a22.productId = 122;
		a22.brandName = "Sample22";
		a22.connectivityType = "Sample22";
		a22.color = "Sample22";
		a22.batteryCapacity = 32.0;
		a22.price = 32.0;
		a22.isWireless = true;
		a22.isAvailable = true;
		a22.manufacturingDate = "Sample22";
		a22.expiryDate = "Sample22";
		a22.soundType = "Sample22";
		a22.material = "Sample22";
		a22.powerOutput = 32.0;
		a22.isWaterproof = true;
		a22.countryOfOrigin = "Sample22";
		a22.warrantyMonths = 122;
		a22.packagingType = "Sample22";
		a22.weight = 32.0;
		a22.isPortable = true;
		a22.feature1 = "Sample22";
		a22.feature2 = "Sample22";
		a22.feature3 = "Sample22";
		a22.hasBluetooth = true;
		a22.hasMic = true;
		a22.rating = 122;

		System.out.println("----- AuroraSpeaker 22 -----");
		System.out.println("productId: " + a22.productId);
		System.out.println("brandName: " + a22.brandName);
		System.out.println("connectivityType: " + a22.connectivityType);
		System.out.println("color: " + a22.color);
		System.out.println("batteryCapacity: " + a22.batteryCapacity);
		System.out.println("price: " + a22.price);
		System.out.println("isWireless: " + a22.isWireless);
		System.out.println("isAvailable: " + a22.isAvailable);
		System.out.println("manufacturingDate: " + a22.manufacturingDate);
		System.out.println("expiryDate: " + a22.expiryDate);
		System.out.println("soundType: " + a22.soundType);
		System.out.println("material: " + a22.material);
		System.out.println("powerOutput: " + a22.powerOutput);
		System.out.println("isWaterproof: " + a22.isWaterproof);
		System.out.println("countryOfOrigin: " + a22.countryOfOrigin);
		System.out.println("warrantyMonths: " + a22.warrantyMonths);
		System.out.println("packagingType: " + a22.packagingType);
		System.out.println("weight: " + a22.weight);
		System.out.println("isPortable: " + a22.isPortable);
		System.out.println("feature1: " + a22.feature1);
		System.out.println("feature2: " + a22.feature2);
		System.out.println("feature3: " + a22.feature3);
		System.out.println("hasBluetooth: " + a22.hasBluetooth);
		System.out.println("hasMic: " + a22.hasMic);
		System.out.println("rating: " + a22.rating);


		AuroraSpeaker a23 = new AuroraSpeaker();
		a23.productId = 123;
		a23.brandName = "Sample23";
		a23.connectivityType = "Sample23";
		a23.color = "Sample23";
		a23.batteryCapacity = 33.0;
		a23.price = 33.0;
		a23.isWireless = false;
		a23.isAvailable = false;
		a23.manufacturingDate = "Sample23";
		a23.expiryDate = "Sample23";
		a23.soundType = "Sample23";
		a23.material = "Sample23";
		a23.powerOutput = 33.0;
		a23.isWaterproof = false;
		a23.countryOfOrigin = "Sample23";
		a23.warrantyMonths = 123;
		a23.packagingType = "Sample23";
		a23.weight = 33.0;
		a23.isPortable = false;
		a23.feature1 = "Sample23";
		a23.feature2 = "Sample23";
		a23.feature3 = "Sample23";
		a23.hasBluetooth = false;
		a23.hasMic = false;
		a23.rating = 123;

		System.out.println("----- AuroraSpeaker 23 -----");
		System.out.println("productId: " + a23.productId);
		System.out.println("brandName: " + a23.brandName);
		System.out.println("connectivityType: " + a23.connectivityType);
		System.out.println("color: " + a23.color);
		System.out.println("batteryCapacity: " + a23.batteryCapacity);
		System.out.println("price: " + a23.price);
		System.out.println("isWireless: " + a23.isWireless);
		System.out.println("isAvailable: " + a23.isAvailable);
		System.out.println("manufacturingDate: " + a23.manufacturingDate);
		System.out.println("expiryDate: " + a23.expiryDate);
		System.out.println("soundType: " + a23.soundType);
		System.out.println("material: " + a23.material);
		System.out.println("powerOutput: " + a23.powerOutput);
		System.out.println("isWaterproof: " + a23.isWaterproof);
		System.out.println("countryOfOrigin: " + a23.countryOfOrigin);
		System.out.println("warrantyMonths: " + a23.warrantyMonths);
		System.out.println("packagingType: " + a23.packagingType);
		System.out.println("weight: " + a23.weight);
		System.out.println("isPortable: " + a23.isPortable);
		System.out.println("feature1: " + a23.feature1);
		System.out.println("feature2: " + a23.feature2);
		System.out.println("feature3: " + a23.feature3);
		System.out.println("hasBluetooth: " + a23.hasBluetooth);
		System.out.println("hasMic: " + a23.hasMic);
		System.out.println("rating: " + a23.rating);


		AuroraSpeaker a24 = new AuroraSpeaker();
		a24.productId = 124;
		a24.brandName = "Sample24";
		a24.connectivityType = "Sample24";
		a24.color = "Sample24";
		a24.batteryCapacity = 34.0;
		a24.price = 34.0;
		a24.isWireless = true;
		a24.isAvailable = true;
		a24.manufacturingDate = "Sample24";
		a24.expiryDate = "Sample24";
		a24.soundType = "Sample24";
		a24.material = "Sample24";
		a24.powerOutput = 34.0;
		a24.isWaterproof = true;
		a24.countryOfOrigin = "Sample24";
		a24.warrantyMonths = 124;
		a24.packagingType = "Sample24";
		a24.weight = 34.0;
		a24.isPortable = true;
		a24.feature1 = "Sample24";
		a24.feature2 = "Sample24";
		a24.feature3 = "Sample24";
		a24.hasBluetooth = true;
		a24.hasMic = true;
		a24.rating = 124;

		System.out.println("----- AuroraSpeaker 24 -----");
		System.out.println("productId: " + a24.productId);
		System.out.println("brandName: " + a24.brandName);
		System.out.println("connectivityType: " + a24.connectivityType);
		System.out.println("color: " + a24.color);
		System.out.println("batteryCapacity: " + a24.batteryCapacity);
		System.out.println("price: " + a24.price);
		System.out.println("isWireless: " + a24.isWireless);
		System.out.println("isAvailable: " + a24.isAvailable);
		System.out.println("manufacturingDate: " + a24.manufacturingDate);
		System.out.println("expiryDate: " + a24.expiryDate);
		System.out.println("soundType: " + a24.soundType);
		System.out.println("material: " + a24.material);
		System.out.println("powerOutput: " + a24.powerOutput);
		System.out.println("isWaterproof: " + a24.isWaterproof);
		System.out.println("countryOfOrigin: " + a24.countryOfOrigin);
		System.out.println("warrantyMonths: " + a24.warrantyMonths);
		System.out.println("packagingType: " + a24.packagingType);
		System.out.println("weight: " + a24.weight);
		System.out.println("isPortable: " + a24.isPortable);
		System.out.println("feature1: " + a24.feature1);
		System.out.println("feature2: " + a24.feature2);
		System.out.println("feature3: " + a24.feature3);
		System.out.println("hasBluetooth: " + a24.hasBluetooth);
		System.out.println("hasMic: " + a24.hasMic);
		System.out.println("rating: " + a24.rating);


		AuroraSpeaker a25 = new AuroraSpeaker();
		a25.productId = 125;
		a25.brandName = "Sample25";
		a25.connectivityType = "Sample25";
		a25.color = "Sample25";
		a25.batteryCapacity = 35.0;
		a25.price = 35.0;
		a25.isWireless = false;
		a25.isAvailable = false;
		a25.manufacturingDate = "Sample25";
		a25.expiryDate = "Sample25";
		a25.soundType = "Sample25";
		a25.material = "Sample25";
		a25.powerOutput = 35.0;
		a25.isWaterproof = false;
		a25.countryOfOrigin = "Sample25";
		a25.warrantyMonths = 125;
		a25.packagingType = "Sample25";
		a25.weight = 35.0;
		a25.isPortable = false;
		a25.feature1 = "Sample25";
		a25.feature2 = "Sample25";
		a25.feature3 = "Sample25";
		a25.hasBluetooth = false;
		a25.hasMic = false;
		a25.rating = 125;

		System.out.println("----- AuroraSpeaker 25 -----");
		System.out.println("productId: " + a25.productId);
		System.out.println("brandName: " + a25.brandName);
		System.out.println("connectivityType: " + a25.connectivityType);
		System.out.println("color: " + a25.color);
		System.out.println("batteryCapacity: " + a25.batteryCapacity);
		System.out.println("price: " + a25.price);
		System.out.println("isWireless: " + a25.isWireless);
		System.out.println("isAvailable: " + a25.isAvailable);
		System.out.println("manufacturingDate: " + a25.manufacturingDate);
		System.out.println("expiryDate: " + a25.expiryDate);
		System.out.println("soundType: " + a25.soundType);
		System.out.println("material: " + a25.material);
		System.out.println("powerOutput: " + a25.powerOutput);
		System.out.println("isWaterproof: " + a25.isWaterproof);
		System.out.println("countryOfOrigin: " + a25.countryOfOrigin);
		System.out.println("warrantyMonths: " + a25.warrantyMonths);
		System.out.println("packagingType: " + a25.packagingType);
		System.out.println("weight: " + a25.weight);
		System.out.println("isPortable: " + a25.isPortable);
		System.out.println("feature1: " + a25.feature1);
		System.out.println("feature2: " + a25.feature2);
		System.out.println("feature3: " + a25.feature3);
		System.out.println("hasBluetooth: " + a25.hasBluetooth);
		System.out.println("hasMic: " + a25.hasMic);
		System.out.println("rating: " + a25.rating);


	}
}
