class Bracelet { int feature1;
 int feature2;
 int feature3;
 int feature4;
 int feature5;
 int feature6;
 int feature7;
 int feature8;
 int feature9;
 int feature10;
 int feature11;
 int feature12;
 int feature13;
 int feature14;
 int feature15;
 int feature16;
 int feature17;
 int feature18;
 int feature19;
 int feature20;

    Bracelet() {
        feature1 = 1;
        feature2 = 1;
        feature3 = 1;
        feature4 = 1;
        feature5 = 1;
        feature6 = 1;
        feature7 = 1;
        feature8 = 1;
        feature9 = 1;
        feature10 = 1;
        feature11 = 1;
        feature12 = 1;
        feature13 = 1;
        feature14 = 1;
        feature15 = 1;
        feature16 = 1;
        feature17 = 1;
        feature18 = 1;
        feature19 = 1;
        feature20 = 1;
        System.out.println("feature1: " + feature1);
        System.out.println("feature2: " + feature2);
        System.out.println("feature3: " + feature3);
        System.out.println("feature4: " + feature4);
        System.out.println("feature5: " + feature5);
        System.out.println("feature6: " + feature6);
        System.out.println("feature7: " + feature7);
        System.out.println("feature8: " + feature8);
        System.out.println("feature9: " + feature9);
        System.out.println("feature10: " + feature10);
        System.out.println("feature11: " + feature11);
        System.out.println("feature12: " + feature12);
        System.out.println("feature13: " + feature13);
        System.out.println("feature14: " + feature14);
        System.out.println("feature15: " + feature15);
        System.out.println("feature16: " + feature16);
        System.out.println("feature17: " + feature17);
        System.out.println("feature18: " + feature18);
        System.out.println("feature19: " + feature19);
        System.out.println("feature20: " + feature20);
    }

    Bracelet(int feature1, int feature2, int feature3, int feature4, int feature5, int feature6, int feature7, int feature8, int feature9, int feature10, int feature11, int feature12, int feature13, int feature14, int feature15, int feature16, int feature17, int feature18, int feature19, int feature20) {
        this.feature1 = feature1;
        this.feature2 = feature2;
        this.feature3 = feature3;
        this.feature4 = feature4;
        this.feature5 = feature5;
        this.feature6 = feature6;
        this.feature7 = feature7;
        this.feature8 = feature8;
        this.feature9 = feature9;
        this.feature10 = feature10;
        this.feature11 = feature11;
        this.feature12 = feature12;
        this.feature13 = feature13;
        this.feature14 = feature14;
        this.feature15 = feature15;
        this.feature16 = feature16;
        this.feature17 = feature17;
        this.feature18 = feature18;
        this.feature19 = feature19;
        this.feature20 = feature20;
        System.out.println("feature1: " + this.feature1);
        System.out.println("feature2: " + this.feature2);
        System.out.println("feature3: " + this.feature3);
        System.out.println("feature4: " + this.feature4);
        System.out.println("feature5: " + this.feature5);
        System.out.println("feature6: " + this.feature6);
        System.out.println("feature7: " + this.feature7);
        System.out.println("feature8: " + this.feature8);
        System.out.println("feature9: " + this.feature9);
        System.out.println("feature10: " + this.feature10);
        System.out.println("feature11: " + this.feature11);
        System.out.println("feature12: " + this.feature12);
        System.out.println("feature13: " + this.feature13);
        System.out.println("feature14: " + this.feature14);
        System.out.println("feature15: " + this.feature15);
        System.out.println("feature16: " + this.feature16);
        System.out.println("feature17: " + this.feature17);
        System.out.println("feature18: " + this.feature18);
        System.out.println("feature19: " + this.feature19);
        System.out.println("feature20: " + this.feature20);
    }

}
