class CellPhoneExecutor{
	public static void main(String[] args){
	
	String contactName="Baba";
	long number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Virat Kohli";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Keerthana";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Navii";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Vaishnavi";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Ankitha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Dev";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Chaithra";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Madhu";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Deeksha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Chaman";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Hruthik";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Spoorthi";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Amma";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Pappa";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Sneha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Anusha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Kesari";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Chandana";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Kshama";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Deepika";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Sanjana";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Pratham";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Sahana";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Sinchana";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Anju";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Srushti";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Avani";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Disha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Shreya";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Varshi";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Inchara";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Raj";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Nisha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Sanju";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Hani";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Kushi";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Karan";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Anitha";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Rashmi";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
	contactName="Lokdeep";
	number=CellPhone.getContactNumber(contactName);
	System.out.println("The Contact no of" + contactName +" is "+number);
}
}