class Cricket { 
int stat1 ;
int stat2;
 int stat3;
 int stat4;
 int stat5;
 int stat6;
 int stat7;
 int stat8;
 int stat9;
 int stat10;
 int stat11;
 int stat12;
 int stat13;
 int stat14;
 int stat15;
 int stat16;
 int stat17;
 int stat18;
 int stat19;
int stat20;

    Cricket() {
        stat1 = 1;
        stat2 = 1;
        stat3 = 1;
        stat4 = 1;
        stat5 = 1;
        stat6 = 1;
        stat7 = 1;
        stat8 = 1;
        stat9 = 1;
        stat10 = 1;
        stat11 = 1;
        stat12 = 1;
        stat13 = 1;
        stat14 = 1;
        stat15 = 1;
        stat16 = 1;
        stat17 = 1;
        stat18 = 1;
        stat19 = 1;
        stat20 = 1;
        System.out.println("stat1: " + stat1);
        System.out.println("stat2: " + stat2);
        System.out.println("stat3: " + stat3);
        System.out.println("stat4: " + stat4);
        System.out.println("stat5: " + stat5);
        System.out.println("stat6: " + stat6);
        System.out.println("stat7: " + stat7);
        System.out.println("stat8: " + stat8);
        System.out.println("stat9: " + stat9);
        System.out.println("stat10: " + stat10);
        System.out.println("stat11: " + stat11);
        System.out.println("stat12: " + stat12);
        System.out.println("stat13: " + stat13);
        System.out.println("stat14: " + stat14);
        System.out.println("stat15: " + stat15);
        System.out.println("stat16: " + stat16);
        System.out.println("stat17: " + stat17);
        System.out.println("stat18: " + stat18);
        System.out.println("stat19: " + stat19);
        System.out.println("stat20: " + stat20);
    }

    Cricket(int stat1, int stat2, int stat3, int stat4, int stat5, int stat6, int stat7, int stat8, int stat9, int stat10, int stat11, int stat12, int stat13, int stat14, int stat15, int stat16, int stat17, int stat18, int stat19, int stat20) {
        this.stat1 = stat1;
        this.stat2 = stat2;
        this.stat3 = stat3;
        this.stat4 = stat4;
        this.stat5 = stat5;
        this.stat6 = stat6;
        this.stat7 = stat7;
        this.stat8 = stat8;
        this.stat9 = stat9;
        this.stat10 = stat10;
        this.stat11 = stat11;
        this.stat12 = stat12;
        this.stat13 = stat13;
        this.stat14 = stat14;
        this.stat15 = stat15;
        this.stat16 = stat16;
        this.stat17 = stat17;
        this.stat18 = stat18;
        this.stat19 = stat19;
        this.stat20 = stat20;
        System.out.println("stat1: " + this.stat1);
        System.out.println("stat2: " + this.stat2);
        System.out.println("stat3: " + this.stat3);
        System.out.println("stat4: " + this.stat4);
        System.out.println("stat5: " + this.stat5);
        System.out.println("stat6: " + this.stat6);
        System.out.println("stat7: " + this.stat7);
        System.out.println("stat8: " + this.stat8);
        System.out.println("stat9: " + this.stat9);
        System.out.println("stat10: " + this.stat10);
        System.out.println("stat11: " + this.stat11);
        System.out.println("stat12: " + this.stat12);
        System.out.println("stat13: " + this.stat13);
        System.out.println("stat14: " + this.stat14);
        System.out.println("stat15: " + this.stat15);
        System.out.println("stat16: " + this.stat16);
        System.out.println("stat17: " + this.stat17);
        System.out.println("stat18: " + this.stat18);
        System.out.println("stat19: " + this.stat19);
        System.out.println("stat20: " + this.stat20);
    }

}
