class CrystalLampRunner {
	public static void main(String[] args) {

		CrystalLamp c1 = new CrystalLamp();
		c1.productId = 101;
		c1.brandName = "Sample1";
		c1.lampType = "Sample1";
		c1.color = "Sample1";
		c1.voltage = 11.0;
		c1.price = 11.0;
		c1.isLED = false;
		c1.isAvailable = false;
		c1.manufacturingDate = "Sample1";
		c1.expiryDate = "Sample1";
		c1.usageType = "Sample1";
		c1.material = "Sample1";
		c1.brightnessLevel = 11.0;
		c1.isEnergyEfficient = false;
		c1.countryOfOrigin = "Sample1";
		c1.warrantyMonths = 101;
		c1.packagingType = "Sample1";
		c1.weight = 11.0;
		c1.isShockResistant = false;
		c1.feature1 = "Sample1";
		c1.feature2 = "Sample1";
		c1.feature3 = "Sample1";
		c1.isDecorative = false;
		c1.isPortable = false;
		c1.rating = 101;

		System.out.println("----- CrystalLamp 1 -----");
		System.out.println("productId: " + c1.productId);
		System.out.println("brandName: " + c1.brandName);
		System.out.println("lampType: " + c1.lampType);
		System.out.println("color: " + c1.color);
		System.out.println("voltage: " + c1.voltage);
		System.out.println("price: " + c1.price);
		System.out.println("isLED: " + c1.isLED);
		System.out.println("isAvailable: " + c1.isAvailable);
		System.out.println("manufacturingDate: " + c1.manufacturingDate);
		System.out.println("expiryDate: " + c1.expiryDate);
		System.out.println("usageType: " + c1.usageType);
		System.out.println("material: " + c1.material);
		System.out.println("brightnessLevel: " + c1.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c1.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c1.countryOfOrigin);
		System.out.println("warrantyMonths: " + c1.warrantyMonths);
		System.out.println("packagingType: " + c1.packagingType);
		System.out.println("weight: " + c1.weight);
		System.out.println("isShockResistant: " + c1.isShockResistant);
		System.out.println("feature1: " + c1.feature1);
		System.out.println("feature2: " + c1.feature2);
		System.out.println("feature3: " + c1.feature3);
		System.out.println("isDecorative: " + c1.isDecorative);
		System.out.println("isPortable: " + c1.isPortable);
		System.out.println("rating: " + c1.rating);


		CrystalLamp c2 = new CrystalLamp();
		c2.productId = 102;
		c2.brandName = "Sample2";
		c2.lampType = "Sample2";
		c2.color = "Sample2";
		c2.voltage = 12.0;
		c2.price = 12.0;
		c2.isLED = true;
		c2.isAvailable = true;
		c2.manufacturingDate = "Sample2";
		c2.expiryDate = "Sample2";
		c2.usageType = "Sample2";
		c2.material = "Sample2";
		c2.brightnessLevel = 12.0;
		c2.isEnergyEfficient = true;
		c2.countryOfOrigin = "Sample2";
		c2.warrantyMonths = 102;
		c2.packagingType = "Sample2";
		c2.weight = 12.0;
		c2.isShockResistant = true;
		c2.feature1 = "Sample2";
		c2.feature2 = "Sample2";
		c2.feature3 = "Sample2";
		c2.isDecorative = true;
		c2.isPortable = true;
		c2.rating = 102;

		System.out.println("----- CrystalLamp 2 -----");
		System.out.println("productId: " + c2.productId);
		System.out.println("brandName: " + c2.brandName);
		System.out.println("lampType: " + c2.lampType);
		System.out.println("color: " + c2.color);
		System.out.println("voltage: " + c2.voltage);
		System.out.println("price: " + c2.price);
		System.out.println("isLED: " + c2.isLED);
		System.out.println("isAvailable: " + c2.isAvailable);
		System.out.println("manufacturingDate: " + c2.manufacturingDate);
		System.out.println("expiryDate: " + c2.expiryDate);
		System.out.println("usageType: " + c2.usageType);
		System.out.println("material: " + c2.material);
		System.out.println("brightnessLevel: " + c2.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c2.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c2.countryOfOrigin);
		System.out.println("warrantyMonths: " + c2.warrantyMonths);
		System.out.println("packagingType: " + c2.packagingType);
		System.out.println("weight: " + c2.weight);
		System.out.println("isShockResistant: " + c2.isShockResistant);
		System.out.println("feature1: " + c2.feature1);
		System.out.println("feature2: " + c2.feature2);
		System.out.println("feature3: " + c2.feature3);
		System.out.println("isDecorative: " + c2.isDecorative);
		System.out.println("isPortable: " + c2.isPortable);
		System.out.println("rating: " + c2.rating);


		CrystalLamp c3 = new CrystalLamp();
		c3.productId = 103;
		c3.brandName = "Sample3";
		c3.lampType = "Sample3";
		c3.color = "Sample3";
		c3.voltage = 13.0;
		c3.price = 13.0;
		c3.isLED = false;
		c3.isAvailable = false;
		c3.manufacturingDate = "Sample3";
		c3.expiryDate = "Sample3";
		c3.usageType = "Sample3";
		c3.material = "Sample3";
		c3.brightnessLevel = 13.0;
		c3.isEnergyEfficient = false;
		c3.countryOfOrigin = "Sample3";
		c3.warrantyMonths = 103;
		c3.packagingType = "Sample3";
		c3.weight = 13.0;
		c3.isShockResistant = false;
		c3.feature1 = "Sample3";
		c3.feature2 = "Sample3";
		c3.feature3 = "Sample3";
		c3.isDecorative = false;
		c3.isPortable = false;
		c3.rating = 103;

		System.out.println("----- CrystalLamp 3 -----");
		System.out.println("productId: " + c3.productId);
		System.out.println("brandName: " + c3.brandName);
		System.out.println("lampType: " + c3.lampType);
		System.out.println("color: " + c3.color);
		System.out.println("voltage: " + c3.voltage);
		System.out.println("price: " + c3.price);
		System.out.println("isLED: " + c3.isLED);
		System.out.println("isAvailable: " + c3.isAvailable);
		System.out.println("manufacturingDate: " + c3.manufacturingDate);
		System.out.println("expiryDate: " + c3.expiryDate);
		System.out.println("usageType: " + c3.usageType);
		System.out.println("material: " + c3.material);
		System.out.println("brightnessLevel: " + c3.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c3.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c3.countryOfOrigin);
		System.out.println("warrantyMonths: " + c3.warrantyMonths);
		System.out.println("packagingType: " + c3.packagingType);
		System.out.println("weight: " + c3.weight);
		System.out.println("isShockResistant: " + c3.isShockResistant);
		System.out.println("feature1: " + c3.feature1);
		System.out.println("feature2: " + c3.feature2);
		System.out.println("feature3: " + c3.feature3);
		System.out.println("isDecorative: " + c3.isDecorative);
		System.out.println("isPortable: " + c3.isPortable);
		System.out.println("rating: " + c3.rating);


		CrystalLamp c4 = new CrystalLamp();
		c4.productId = 104;
		c4.brandName = "Sample4";
		c4.lampType = "Sample4";
		c4.color = "Sample4";
		c4.voltage = 14.0;
		c4.price = 14.0;
		c4.isLED = true;
		c4.isAvailable = true;
		c4.manufacturingDate = "Sample4";
		c4.expiryDate = "Sample4";
		c4.usageType = "Sample4";
		c4.material = "Sample4";
		c4.brightnessLevel = 14.0;
		c4.isEnergyEfficient = true;
		c4.countryOfOrigin = "Sample4";
		c4.warrantyMonths = 104;
		c4.packagingType = "Sample4";
		c4.weight = 14.0;
		c4.isShockResistant = true;
		c4.feature1 = "Sample4";
		c4.feature2 = "Sample4";
		c4.feature3 = "Sample4";
		c4.isDecorative = true;
		c4.isPortable = true;
		c4.rating = 104;

		System.out.println("----- CrystalLamp 4 -----");
		System.out.println("productId: " + c4.productId);
		System.out.println("brandName: " + c4.brandName);
		System.out.println("lampType: " + c4.lampType);
		System.out.println("color: " + c4.color);
		System.out.println("voltage: " + c4.voltage);
		System.out.println("price: " + c4.price);
		System.out.println("isLED: " + c4.isLED);
		System.out.println("isAvailable: " + c4.isAvailable);
		System.out.println("manufacturingDate: " + c4.manufacturingDate);
		System.out.println("expiryDate: " + c4.expiryDate);
		System.out.println("usageType: " + c4.usageType);
		System.out.println("material: " + c4.material);
		System.out.println("brightnessLevel: " + c4.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c4.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c4.countryOfOrigin);
		System.out.println("warrantyMonths: " + c4.warrantyMonths);
		System.out.println("packagingType: " + c4.packagingType);
		System.out.println("weight: " + c4.weight);
		System.out.println("isShockResistant: " + c4.isShockResistant);
		System.out.println("feature1: " + c4.feature1);
		System.out.println("feature2: " + c4.feature2);
		System.out.println("feature3: " + c4.feature3);
		System.out.println("isDecorative: " + c4.isDecorative);
		System.out.println("isPortable: " + c4.isPortable);
		System.out.println("rating: " + c4.rating);


		CrystalLamp c5 = new CrystalLamp();
		c5.productId = 105;
		c5.brandName = "Sample5";
		c5.lampType = "Sample5";
		c5.color = "Sample5";
		c5.voltage = 15.0;
		c5.price = 15.0;
		c5.isLED = false;
		c5.isAvailable = false;
		c5.manufacturingDate = "Sample5";
		c5.expiryDate = "Sample5";
		c5.usageType = "Sample5";
		c5.material = "Sample5";
		c5.brightnessLevel = 15.0;
		c5.isEnergyEfficient = false;
		c5.countryOfOrigin = "Sample5";
		c5.warrantyMonths = 105;
		c5.packagingType = "Sample5";
		c5.weight = 15.0;
		c5.isShockResistant = false;
		c5.feature1 = "Sample5";
		c5.feature2 = "Sample5";
		c5.feature3 = "Sample5";
		c5.isDecorative = false;
		c5.isPortable = false;
		c5.rating = 105;

		System.out.println("----- CrystalLamp 5 -----");
		System.out.println("productId: " + c5.productId);
		System.out.println("brandName: " + c5.brandName);
		System.out.println("lampType: " + c5.lampType);
		System.out.println("color: " + c5.color);
		System.out.println("voltage: " + c5.voltage);
		System.out.println("price: " + c5.price);
		System.out.println("isLED: " + c5.isLED);
		System.out.println("isAvailable: " + c5.isAvailable);
		System.out.println("manufacturingDate: " + c5.manufacturingDate);
		System.out.println("expiryDate: " + c5.expiryDate);
		System.out.println("usageType: " + c5.usageType);
		System.out.println("material: " + c5.material);
		System.out.println("brightnessLevel: " + c5.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c5.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c5.countryOfOrigin);
		System.out.println("warrantyMonths: " + c5.warrantyMonths);
		System.out.println("packagingType: " + c5.packagingType);
		System.out.println("weight: " + c5.weight);
		System.out.println("isShockResistant: " + c5.isShockResistant);
		System.out.println("feature1: " + c5.feature1);
		System.out.println("feature2: " + c5.feature2);
		System.out.println("feature3: " + c5.feature3);
		System.out.println("isDecorative: " + c5.isDecorative);
		System.out.println("isPortable: " + c5.isPortable);
		System.out.println("rating: " + c5.rating);


		CrystalLamp c6 = new CrystalLamp();
		c6.productId = 106;
		c6.brandName = "Sample6";
		c6.lampType = "Sample6";
		c6.color = "Sample6";
		c6.voltage = 16.0;
		c6.price = 16.0;
		c6.isLED = true;
		c6.isAvailable = true;
		c6.manufacturingDate = "Sample6";
		c6.expiryDate = "Sample6";
		c6.usageType = "Sample6";
		c6.material = "Sample6";
		c6.brightnessLevel = 16.0;
		c6.isEnergyEfficient = true;
		c6.countryOfOrigin = "Sample6";
		c6.warrantyMonths = 106;
		c6.packagingType = "Sample6";
		c6.weight = 16.0;
		c6.isShockResistant = true;
		c6.feature1 = "Sample6";
		c6.feature2 = "Sample6";
		c6.feature3 = "Sample6";
		c6.isDecorative = true;
		c6.isPortable = true;
		c6.rating = 106;

		System.out.println("----- CrystalLamp 6 -----");
		System.out.println("productId: " + c6.productId);
		System.out.println("brandName: " + c6.brandName);
		System.out.println("lampType: " + c6.lampType);
		System.out.println("color: " + c6.color);
		System.out.println("voltage: " + c6.voltage);
		System.out.println("price: " + c6.price);
		System.out.println("isLED: " + c6.isLED);
		System.out.println("isAvailable: " + c6.isAvailable);
		System.out.println("manufacturingDate: " + c6.manufacturingDate);
		System.out.println("expiryDate: " + c6.expiryDate);
		System.out.println("usageType: " + c6.usageType);
		System.out.println("material: " + c6.material);
		System.out.println("brightnessLevel: " + c6.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c6.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c6.countryOfOrigin);
		System.out.println("warrantyMonths: " + c6.warrantyMonths);
		System.out.println("packagingType: " + c6.packagingType);
		System.out.println("weight: " + c6.weight);
		System.out.println("isShockResistant: " + c6.isShockResistant);
		System.out.println("feature1: " + c6.feature1);
		System.out.println("feature2: " + c6.feature2);
		System.out.println("feature3: " + c6.feature3);
		System.out.println("isDecorative: " + c6.isDecorative);
		System.out.println("isPortable: " + c6.isPortable);
		System.out.println("rating: " + c6.rating);


		CrystalLamp c7 = new CrystalLamp();
		c7.productId = 107;
		c7.brandName = "Sample7";
		c7.lampType = "Sample7";
		c7.color = "Sample7";
		c7.voltage = 17.0;
		c7.price = 17.0;
		c7.isLED = false;
		c7.isAvailable = false;
		c7.manufacturingDate = "Sample7";
		c7.expiryDate = "Sample7";
		c7.usageType = "Sample7";
		c7.material = "Sample7";
		c7.brightnessLevel = 17.0;
		c7.isEnergyEfficient = false;
		c7.countryOfOrigin = "Sample7";
		c7.warrantyMonths = 107;
		c7.packagingType = "Sample7";
		c7.weight = 17.0;
		c7.isShockResistant = false;
		c7.feature1 = "Sample7";
		c7.feature2 = "Sample7";
		c7.feature3 = "Sample7";
		c7.isDecorative = false;
		c7.isPortable = false;
		c7.rating = 107;

		System.out.println("----- CrystalLamp 7 -----");
		System.out.println("productId: " + c7.productId);
		System.out.println("brandName: " + c7.brandName);
		System.out.println("lampType: " + c7.lampType);
		System.out.println("color: " + c7.color);
		System.out.println("voltage: " + c7.voltage);
		System.out.println("price: " + c7.price);
		System.out.println("isLED: " + c7.isLED);
		System.out.println("isAvailable: " + c7.isAvailable);
		System.out.println("manufacturingDate: " + c7.manufacturingDate);
		System.out.println("expiryDate: " + c7.expiryDate);
		System.out.println("usageType: " + c7.usageType);
		System.out.println("material: " + c7.material);
		System.out.println("brightnessLevel: " + c7.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c7.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c7.countryOfOrigin);
		System.out.println("warrantyMonths: " + c7.warrantyMonths);
		System.out.println("packagingType: " + c7.packagingType);
		System.out.println("weight: " + c7.weight);
		System.out.println("isShockResistant: " + c7.isShockResistant);
		System.out.println("feature1: " + c7.feature1);
		System.out.println("feature2: " + c7.feature2);
		System.out.println("feature3: " + c7.feature3);
		System.out.println("isDecorative: " + c7.isDecorative);
		System.out.println("isPortable: " + c7.isPortable);
		System.out.println("rating: " + c7.rating);


		CrystalLamp c8 = new CrystalLamp();
		c8.productId = 108;
		c8.brandName = "Sample8";
		c8.lampType = "Sample8";
		c8.color = "Sample8";
		c8.voltage = 18.0;
		c8.price = 18.0;
		c8.isLED = true;
		c8.isAvailable = true;
		c8.manufacturingDate = "Sample8";
		c8.expiryDate = "Sample8";
		c8.usageType = "Sample8";
		c8.material = "Sample8";
		c8.brightnessLevel = 18.0;
		c8.isEnergyEfficient = true;
		c8.countryOfOrigin = "Sample8";
		c8.warrantyMonths = 108;
		c8.packagingType = "Sample8";
		c8.weight = 18.0;
		c8.isShockResistant = true;
		c8.feature1 = "Sample8";
		c8.feature2 = "Sample8";
		c8.feature3 = "Sample8";
		c8.isDecorative = true;
		c8.isPortable = true;
		c8.rating = 108;

		System.out.println("----- CrystalLamp 8 -----");
		System.out.println("productId: " + c8.productId);
		System.out.println("brandName: " + c8.brandName);
		System.out.println("lampType: " + c8.lampType);
		System.out.println("color: " + c8.color);
		System.out.println("voltage: " + c8.voltage);
		System.out.println("price: " + c8.price);
		System.out.println("isLED: " + c8.isLED);
		System.out.println("isAvailable: " + c8.isAvailable);
		System.out.println("manufacturingDate: " + c8.manufacturingDate);
		System.out.println("expiryDate: " + c8.expiryDate);
		System.out.println("usageType: " + c8.usageType);
		System.out.println("material: " + c8.material);
		System.out.println("brightnessLevel: " + c8.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c8.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c8.countryOfOrigin);
		System.out.println("warrantyMonths: " + c8.warrantyMonths);
		System.out.println("packagingType: " + c8.packagingType);
		System.out.println("weight: " + c8.weight);
		System.out.println("isShockResistant: " + c8.isShockResistant);
		System.out.println("feature1: " + c8.feature1);
		System.out.println("feature2: " + c8.feature2);
		System.out.println("feature3: " + c8.feature3);
		System.out.println("isDecorative: " + c8.isDecorative);
		System.out.println("isPortable: " + c8.isPortable);
		System.out.println("rating: " + c8.rating);


		CrystalLamp c9 = new CrystalLamp();
		c9.productId = 109;
		c9.brandName = "Sample9";
		c9.lampType = "Sample9";
		c9.color = "Sample9";
		c9.voltage = 19.0;
		c9.price = 19.0;
		c9.isLED = false;
		c9.isAvailable = false;
		c9.manufacturingDate = "Sample9";
		c9.expiryDate = "Sample9";
		c9.usageType = "Sample9";
		c9.material = "Sample9";
		c9.brightnessLevel = 19.0;
		c9.isEnergyEfficient = false;
		c9.countryOfOrigin = "Sample9";
		c9.warrantyMonths = 109;
		c9.packagingType = "Sample9";
		c9.weight = 19.0;
		c9.isShockResistant = false;
		c9.feature1 = "Sample9";
		c9.feature2 = "Sample9";
		c9.feature3 = "Sample9";
		c9.isDecorative = false;
		c9.isPortable = false;
		c9.rating = 109;

		System.out.println("----- CrystalLamp 9 -----");
		System.out.println("productId: " + c9.productId);
		System.out.println("brandName: " + c9.brandName);
		System.out.println("lampType: " + c9.lampType);
		System.out.println("color: " + c9.color);
		System.out.println("voltage: " + c9.voltage);
		System.out.println("price: " + c9.price);
		System.out.println("isLED: " + c9.isLED);
		System.out.println("isAvailable: " + c9.isAvailable);
		System.out.println("manufacturingDate: " + c9.manufacturingDate);
		System.out.println("expiryDate: " + c9.expiryDate);
		System.out.println("usageType: " + c9.usageType);
		System.out.println("material: " + c9.material);
		System.out.println("brightnessLevel: " + c9.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c9.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c9.countryOfOrigin);
		System.out.println("warrantyMonths: " + c9.warrantyMonths);
		System.out.println("packagingType: " + c9.packagingType);
		System.out.println("weight: " + c9.weight);
		System.out.println("isShockResistant: " + c9.isShockResistant);
		System.out.println("feature1: " + c9.feature1);
		System.out.println("feature2: " + c9.feature2);
		System.out.println("feature3: " + c9.feature3);
		System.out.println("isDecorative: " + c9.isDecorative);
		System.out.println("isPortable: " + c9.isPortable);
		System.out.println("rating: " + c9.rating);


		CrystalLamp c10 = new CrystalLamp();
		c10.productId = 110;
		c10.brandName = "Sample10";
		c10.lampType = "Sample10";
		c10.color = "Sample10";
		c10.voltage = 20.0;
		c10.price = 20.0;
		c10.isLED = true;
		c10.isAvailable = true;
		c10.manufacturingDate = "Sample10";
		c10.expiryDate = "Sample10";
		c10.usageType = "Sample10";
		c10.material = "Sample10";
		c10.brightnessLevel = 20.0;
		c10.isEnergyEfficient = true;
		c10.countryOfOrigin = "Sample10";
		c10.warrantyMonths = 110;
		c10.packagingType = "Sample10";
		c10.weight = 20.0;
		c10.isShockResistant = true;
		c10.feature1 = "Sample10";
		c10.feature2 = "Sample10";
		c10.feature3 = "Sample10";
		c10.isDecorative = true;
		c10.isPortable = true;
		c10.rating = 110;

		System.out.println("----- CrystalLamp 10 -----");
		System.out.println("productId: " + c10.productId);
		System.out.println("brandName: " + c10.brandName);
		System.out.println("lampType: " + c10.lampType);
		System.out.println("color: " + c10.color);
		System.out.println("voltage: " + c10.voltage);
		System.out.println("price: " + c10.price);
		System.out.println("isLED: " + c10.isLED);
		System.out.println("isAvailable: " + c10.isAvailable);
		System.out.println("manufacturingDate: " + c10.manufacturingDate);
		System.out.println("expiryDate: " + c10.expiryDate);
		System.out.println("usageType: " + c10.usageType);
		System.out.println("material: " + c10.material);
		System.out.println("brightnessLevel: " + c10.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c10.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c10.countryOfOrigin);
		System.out.println("warrantyMonths: " + c10.warrantyMonths);
		System.out.println("packagingType: " + c10.packagingType);
		System.out.println("weight: " + c10.weight);
		System.out.println("isShockResistant: " + c10.isShockResistant);
		System.out.println("feature1: " + c10.feature1);
		System.out.println("feature2: " + c10.feature2);
		System.out.println("feature3: " + c10.feature3);
		System.out.println("isDecorative: " + c10.isDecorative);
		System.out.println("isPortable: " + c10.isPortable);
		System.out.println("rating: " + c10.rating);


		CrystalLamp c11 = new CrystalLamp();
		c11.productId = 111;
		c11.brandName = "Sample11";
		c11.lampType = "Sample11";
		c11.color = "Sample11";
		c11.voltage = 21.0;
		c11.price = 21.0;
		c11.isLED = false;
		c11.isAvailable = false;
		c11.manufacturingDate = "Sample11";
		c11.expiryDate = "Sample11";
		c11.usageType = "Sample11";
		c11.material = "Sample11";
		c11.brightnessLevel = 21.0;
		c11.isEnergyEfficient = false;
		c11.countryOfOrigin = "Sample11";
		c11.warrantyMonths = 111;
		c11.packagingType = "Sample11";
		c11.weight = 21.0;
		c11.isShockResistant = false;
		c11.feature1 = "Sample11";
		c11.feature2 = "Sample11";
		c11.feature3 = "Sample11";
		c11.isDecorative = false;
		c11.isPortable = false;
		c11.rating = 111;

		System.out.println("----- CrystalLamp 11 -----");
		System.out.println("productId: " + c11.productId);
		System.out.println("brandName: " + c11.brandName);
		System.out.println("lampType: " + c11.lampType);
		System.out.println("color: " + c11.color);
		System.out.println("voltage: " + c11.voltage);
		System.out.println("price: " + c11.price);
		System.out.println("isLED: " + c11.isLED);
		System.out.println("isAvailable: " + c11.isAvailable);
		System.out.println("manufacturingDate: " + c11.manufacturingDate);
		System.out.println("expiryDate: " + c11.expiryDate);
		System.out.println("usageType: " + c11.usageType);
		System.out.println("material: " + c11.material);
		System.out.println("brightnessLevel: " + c11.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c11.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c11.countryOfOrigin);
		System.out.println("warrantyMonths: " + c11.warrantyMonths);
		System.out.println("packagingType: " + c11.packagingType);
		System.out.println("weight: " + c11.weight);
		System.out.println("isShockResistant: " + c11.isShockResistant);
		System.out.println("feature1: " + c11.feature1);
		System.out.println("feature2: " + c11.feature2);
		System.out.println("feature3: " + c11.feature3);
		System.out.println("isDecorative: " + c11.isDecorative);
		System.out.println("isPortable: " + c11.isPortable);
		System.out.println("rating: " + c11.rating);


		CrystalLamp c12 = new CrystalLamp();
		c12.productId = 112;
		c12.brandName = "Sample12";
		c12.lampType = "Sample12";
		c12.color = "Sample12";
		c12.voltage = 22.0;
		c12.price = 22.0;
		c12.isLED = true;
		c12.isAvailable = true;
		c12.manufacturingDate = "Sample12";
		c12.expiryDate = "Sample12";
		c12.usageType = "Sample12";
		c12.material = "Sample12";
		c12.brightnessLevel = 22.0;
		c12.isEnergyEfficient = true;
		c12.countryOfOrigin = "Sample12";
		c12.warrantyMonths = 112;
		c12.packagingType = "Sample12";
		c12.weight = 22.0;
		c12.isShockResistant = true;
		c12.feature1 = "Sample12";
		c12.feature2 = "Sample12";
		c12.feature3 = "Sample12";
		c12.isDecorative = true;
		c12.isPortable = true;
		c12.rating = 112;

		System.out.println("----- CrystalLamp 12 -----");
		System.out.println("productId: " + c12.productId);
		System.out.println("brandName: " + c12.brandName);
		System.out.println("lampType: " + c12.lampType);
		System.out.println("color: " + c12.color);
		System.out.println("voltage: " + c12.voltage);
		System.out.println("price: " + c12.price);
		System.out.println("isLED: " + c12.isLED);
		System.out.println("isAvailable: " + c12.isAvailable);
		System.out.println("manufacturingDate: " + c12.manufacturingDate);
		System.out.println("expiryDate: " + c12.expiryDate);
		System.out.println("usageType: " + c12.usageType);
		System.out.println("material: " + c12.material);
		System.out.println("brightnessLevel: " + c12.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c12.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c12.countryOfOrigin);
		System.out.println("warrantyMonths: " + c12.warrantyMonths);
		System.out.println("packagingType: " + c12.packagingType);
		System.out.println("weight: " + c12.weight);
		System.out.println("isShockResistant: " + c12.isShockResistant);
		System.out.println("feature1: " + c12.feature1);
		System.out.println("feature2: " + c12.feature2);
		System.out.println("feature3: " + c12.feature3);
		System.out.println("isDecorative: " + c12.isDecorative);
		System.out.println("isPortable: " + c12.isPortable);
		System.out.println("rating: " + c12.rating);


		CrystalLamp c13 = new CrystalLamp();
		c13.productId = 113;
		c13.brandName = "Sample13";
		c13.lampType = "Sample13";
		c13.color = "Sample13";
		c13.voltage = 23.0;
		c13.price = 23.0;
		c13.isLED = false;
		c13.isAvailable = false;
		c13.manufacturingDate = "Sample13";
		c13.expiryDate = "Sample13";
		c13.usageType = "Sample13";
		c13.material = "Sample13";
		c13.brightnessLevel = 23.0;
		c13.isEnergyEfficient = false;
		c13.countryOfOrigin = "Sample13";
		c13.warrantyMonths = 113;
		c13.packagingType = "Sample13";
		c13.weight = 23.0;
		c13.isShockResistant = false;
		c13.feature1 = "Sample13";
		c13.feature2 = "Sample13";
		c13.feature3 = "Sample13";
		c13.isDecorative = false;
		c13.isPortable = false;
		c13.rating = 113;

		System.out.println("----- CrystalLamp 13 -----");
		System.out.println("productId: " + c13.productId);
		System.out.println("brandName: " + c13.brandName);
		System.out.println("lampType: " + c13.lampType);
		System.out.println("color: " + c13.color);
		System.out.println("voltage: " + c13.voltage);
		System.out.println("price: " + c13.price);
		System.out.println("isLED: " + c13.isLED);
		System.out.println("isAvailable: " + c13.isAvailable);
		System.out.println("manufacturingDate: " + c13.manufacturingDate);
		System.out.println("expiryDate: " + c13.expiryDate);
		System.out.println("usageType: " + c13.usageType);
		System.out.println("material: " + c13.material);
		System.out.println("brightnessLevel: " + c13.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c13.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c13.countryOfOrigin);
		System.out.println("warrantyMonths: " + c13.warrantyMonths);
		System.out.println("packagingType: " + c13.packagingType);
		System.out.println("weight: " + c13.weight);
		System.out.println("isShockResistant: " + c13.isShockResistant);
		System.out.println("feature1: " + c13.feature1);
		System.out.println("feature2: " + c13.feature2);
		System.out.println("feature3: " + c13.feature3);
		System.out.println("isDecorative: " + c13.isDecorative);
		System.out.println("isPortable: " + c13.isPortable);
		System.out.println("rating: " + c13.rating);


		CrystalLamp c14 = new CrystalLamp();
		c14.productId = 114;
		c14.brandName = "Sample14";
		c14.lampType = "Sample14";
		c14.color = "Sample14";
		c14.voltage = 24.0;
		c14.price = 24.0;
		c14.isLED = true;
		c14.isAvailable = true;
		c14.manufacturingDate = "Sample14";
		c14.expiryDate = "Sample14";
		c14.usageType = "Sample14";
		c14.material = "Sample14";
		c14.brightnessLevel = 24.0;
		c14.isEnergyEfficient = true;
		c14.countryOfOrigin = "Sample14";
		c14.warrantyMonths = 114;
		c14.packagingType = "Sample14";
		c14.weight = 24.0;
		c14.isShockResistant = true;
		c14.feature1 = "Sample14";
		c14.feature2 = "Sample14";
		c14.feature3 = "Sample14";
		c14.isDecorative = true;
		c14.isPortable = true;
		c14.rating = 114;

		System.out.println("----- CrystalLamp 14 -----");
		System.out.println("productId: " + c14.productId);
		System.out.println("brandName: " + c14.brandName);
		System.out.println("lampType: " + c14.lampType);
		System.out.println("color: " + c14.color);
		System.out.println("voltage: " + c14.voltage);
		System.out.println("price: " + c14.price);
		System.out.println("isLED: " + c14.isLED);
		System.out.println("isAvailable: " + c14.isAvailable);
		System.out.println("manufacturingDate: " + c14.manufacturingDate);
		System.out.println("expiryDate: " + c14.expiryDate);
		System.out.println("usageType: " + c14.usageType);
		System.out.println("material: " + c14.material);
		System.out.println("brightnessLevel: " + c14.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c14.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c14.countryOfOrigin);
		System.out.println("warrantyMonths: " + c14.warrantyMonths);
		System.out.println("packagingType: " + c14.packagingType);
		System.out.println("weight: " + c14.weight);
		System.out.println("isShockResistant: " + c14.isShockResistant);
		System.out.println("feature1: " + c14.feature1);
		System.out.println("feature2: " + c14.feature2);
		System.out.println("feature3: " + c14.feature3);
		System.out.println("isDecorative: " + c14.isDecorative);
		System.out.println("isPortable: " + c14.isPortable);
		System.out.println("rating: " + c14.rating);


		CrystalLamp c15 = new CrystalLamp();
		c15.productId = 115;
		c15.brandName = "Sample15";
		c15.lampType = "Sample15";
		c15.color = "Sample15";
		c15.voltage = 25.0;
		c15.price = 25.0;
		c15.isLED = false;
		c15.isAvailable = false;
		c15.manufacturingDate = "Sample15";
		c15.expiryDate = "Sample15";
		c15.usageType = "Sample15";
		c15.material = "Sample15";
		c15.brightnessLevel = 25.0;
		c15.isEnergyEfficient = false;
		c15.countryOfOrigin = "Sample15";
		c15.warrantyMonths = 115;
		c15.packagingType = "Sample15";
		c15.weight = 25.0;
		c15.isShockResistant = false;
		c15.feature1 = "Sample15";
		c15.feature2 = "Sample15";
		c15.feature3 = "Sample15";
		c15.isDecorative = false;
		c15.isPortable = false;
		c15.rating = 115;

		System.out.println("----- CrystalLamp 15 -----");
		System.out.println("productId: " + c15.productId);
		System.out.println("brandName: " + c15.brandName);
		System.out.println("lampType: " + c15.lampType);
		System.out.println("color: " + c15.color);
		System.out.println("voltage: " + c15.voltage);
		System.out.println("price: " + c15.price);
		System.out.println("isLED: " + c15.isLED);
		System.out.println("isAvailable: " + c15.isAvailable);
		System.out.println("manufacturingDate: " + c15.manufacturingDate);
		System.out.println("expiryDate: " + c15.expiryDate);
		System.out.println("usageType: " + c15.usageType);
		System.out.println("material: " + c15.material);
		System.out.println("brightnessLevel: " + c15.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c15.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c15.countryOfOrigin);
		System.out.println("warrantyMonths: " + c15.warrantyMonths);
		System.out.println("packagingType: " + c15.packagingType);
		System.out.println("weight: " + c15.weight);
		System.out.println("isShockResistant: " + c15.isShockResistant);
		System.out.println("feature1: " + c15.feature1);
		System.out.println("feature2: " + c15.feature2);
		System.out.println("feature3: " + c15.feature3);
		System.out.println("isDecorative: " + c15.isDecorative);
		System.out.println("isPortable: " + c15.isPortable);
		System.out.println("rating: " + c15.rating);


		CrystalLamp c16 = new CrystalLamp();
		c16.productId = 116;
		c16.brandName = "Sample16";
		c16.lampType = "Sample16";
		c16.color = "Sample16";
		c16.voltage = 26.0;
		c16.price = 26.0;
		c16.isLED = true;
		c16.isAvailable = true;
		c16.manufacturingDate = "Sample16";
		c16.expiryDate = "Sample16";
		c16.usageType = "Sample16";
		c16.material = "Sample16";
		c16.brightnessLevel = 26.0;
		c16.isEnergyEfficient = true;
		c16.countryOfOrigin = "Sample16";
		c16.warrantyMonths = 116;
		c16.packagingType = "Sample16";
		c16.weight = 26.0;
		c16.isShockResistant = true;
		c16.feature1 = "Sample16";
		c16.feature2 = "Sample16";
		c16.feature3 = "Sample16";
		c16.isDecorative = true;
		c16.isPortable = true;
		c16.rating = 116;

		System.out.println("----- CrystalLamp 16 -----");
		System.out.println("productId: " + c16.productId);
		System.out.println("brandName: " + c16.brandName);
		System.out.println("lampType: " + c16.lampType);
		System.out.println("color: " + c16.color);
		System.out.println("voltage: " + c16.voltage);
		System.out.println("price: " + c16.price);
		System.out.println("isLED: " + c16.isLED);
		System.out.println("isAvailable: " + c16.isAvailable);
		System.out.println("manufacturingDate: " + c16.manufacturingDate);
		System.out.println("expiryDate: " + c16.expiryDate);
		System.out.println("usageType: " + c16.usageType);
		System.out.println("material: " + c16.material);
		System.out.println("brightnessLevel: " + c16.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c16.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c16.countryOfOrigin);
		System.out.println("warrantyMonths: " + c16.warrantyMonths);
		System.out.println("packagingType: " + c16.packagingType);
		System.out.println("weight: " + c16.weight);
		System.out.println("isShockResistant: " + c16.isShockResistant);
		System.out.println("feature1: " + c16.feature1);
		System.out.println("feature2: " + c16.feature2);
		System.out.println("feature3: " + c16.feature3);
		System.out.println("isDecorative: " + c16.isDecorative);
		System.out.println("isPortable: " + c16.isPortable);
		System.out.println("rating: " + c16.rating);


		CrystalLamp c17 = new CrystalLamp();
		c17.productId = 117;
		c17.brandName = "Sample17";
		c17.lampType = "Sample17";
		c17.color = "Sample17";
		c17.voltage = 27.0;
		c17.price = 27.0;
		c17.isLED = false;
		c17.isAvailable = false;
		c17.manufacturingDate = "Sample17";
		c17.expiryDate = "Sample17";
		c17.usageType = "Sample17";
		c17.material = "Sample17";
		c17.brightnessLevel = 27.0;
		c17.isEnergyEfficient = false;
		c17.countryOfOrigin = "Sample17";
		c17.warrantyMonths = 117;
		c17.packagingType = "Sample17";
		c17.weight = 27.0;
		c17.isShockResistant = false;
		c17.feature1 = "Sample17";
		c17.feature2 = "Sample17";
		c17.feature3 = "Sample17";
		c17.isDecorative = false;
		c17.isPortable = false;
		c17.rating = 117;

		System.out.println("----- CrystalLamp 17 -----");
		System.out.println("productId: " + c17.productId);
		System.out.println("brandName: " + c17.brandName);
		System.out.println("lampType: " + c17.lampType);
		System.out.println("color: " + c17.color);
		System.out.println("voltage: " + c17.voltage);
		System.out.println("price: " + c17.price);
		System.out.println("isLED: " + c17.isLED);
		System.out.println("isAvailable: " + c17.isAvailable);
		System.out.println("manufacturingDate: " + c17.manufacturingDate);
		System.out.println("expiryDate: " + c17.expiryDate);
		System.out.println("usageType: " + c17.usageType);
		System.out.println("material: " + c17.material);
		System.out.println("brightnessLevel: " + c17.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c17.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c17.countryOfOrigin);
		System.out.println("warrantyMonths: " + c17.warrantyMonths);
		System.out.println("packagingType: " + c17.packagingType);
		System.out.println("weight: " + c17.weight);
		System.out.println("isShockResistant: " + c17.isShockResistant);
		System.out.println("feature1: " + c17.feature1);
		System.out.println("feature2: " + c17.feature2);
		System.out.println("feature3: " + c17.feature3);
		System.out.println("isDecorative: " + c17.isDecorative);
		System.out.println("isPortable: " + c17.isPortable);
		System.out.println("rating: " + c17.rating);


		CrystalLamp c18 = new CrystalLamp();
		c18.productId = 118;
		c18.brandName = "Sample18";
		c18.lampType = "Sample18";
		c18.color = "Sample18";
		c18.voltage = 28.0;
		c18.price = 28.0;
		c18.isLED = true;
		c18.isAvailable = true;
		c18.manufacturingDate = "Sample18";
		c18.expiryDate = "Sample18";
		c18.usageType = "Sample18";
		c18.material = "Sample18";
		c18.brightnessLevel = 28.0;
		c18.isEnergyEfficient = true;
		c18.countryOfOrigin = "Sample18";
		c18.warrantyMonths = 118;
		c18.packagingType = "Sample18";
		c18.weight = 28.0;
		c18.isShockResistant = true;
		c18.feature1 = "Sample18";
		c18.feature2 = "Sample18";
		c18.feature3 = "Sample18";
		c18.isDecorative = true;
		c18.isPortable = true;
		c18.rating = 118;

		System.out.println("----- CrystalLamp 18 -----");
		System.out.println("productId: " + c18.productId);
		System.out.println("brandName: " + c18.brandName);
		System.out.println("lampType: " + c18.lampType);
		System.out.println("color: " + c18.color);
		System.out.println("voltage: " + c18.voltage);
		System.out.println("price: " + c18.price);
		System.out.println("isLED: " + c18.isLED);
		System.out.println("isAvailable: " + c18.isAvailable);
		System.out.println("manufacturingDate: " + c18.manufacturingDate);
		System.out.println("expiryDate: " + c18.expiryDate);
		System.out.println("usageType: " + c18.usageType);
		System.out.println("material: " + c18.material);
		System.out.println("brightnessLevel: " + c18.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c18.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c18.countryOfOrigin);
		System.out.println("warrantyMonths: " + c18.warrantyMonths);
		System.out.println("packagingType: " + c18.packagingType);
		System.out.println("weight: " + c18.weight);
		System.out.println("isShockResistant: " + c18.isShockResistant);
		System.out.println("feature1: " + c18.feature1);
		System.out.println("feature2: " + c18.feature2);
		System.out.println("feature3: " + c18.feature3);
		System.out.println("isDecorative: " + c18.isDecorative);
		System.out.println("isPortable: " + c18.isPortable);
		System.out.println("rating: " + c18.rating);


		CrystalLamp c19 = new CrystalLamp();
		c19.productId = 119;
		c19.brandName = "Sample19";
		c19.lampType = "Sample19";
		c19.color = "Sample19";
		c19.voltage = 29.0;
		c19.price = 29.0;
		c19.isLED = false;
		c19.isAvailable = false;
		c19.manufacturingDate = "Sample19";
		c19.expiryDate = "Sample19";
		c19.usageType = "Sample19";
		c19.material = "Sample19";
		c19.brightnessLevel = 29.0;
		c19.isEnergyEfficient = false;
		c19.countryOfOrigin = "Sample19";
		c19.warrantyMonths = 119;
		c19.packagingType = "Sample19";
		c19.weight = 29.0;
		c19.isShockResistant = false;
		c19.feature1 = "Sample19";
		c19.feature2 = "Sample19";
		c19.feature3 = "Sample19";
		c19.isDecorative = false;
		c19.isPortable = false;
		c19.rating = 119;

		System.out.println("----- CrystalLamp 19 -----");
		System.out.println("productId: " + c19.productId);
		System.out.println("brandName: " + c19.brandName);
		System.out.println("lampType: " + c19.lampType);
		System.out.println("color: " + c19.color);
		System.out.println("voltage: " + c19.voltage);
		System.out.println("price: " + c19.price);
		System.out.println("isLED: " + c19.isLED);
		System.out.println("isAvailable: " + c19.isAvailable);
		System.out.println("manufacturingDate: " + c19.manufacturingDate);
		System.out.println("expiryDate: " + c19.expiryDate);
		System.out.println("usageType: " + c19.usageType);
		System.out.println("material: " + c19.material);
		System.out.println("brightnessLevel: " + c19.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c19.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c19.countryOfOrigin);
		System.out.println("warrantyMonths: " + c19.warrantyMonths);
		System.out.println("packagingType: " + c19.packagingType);
		System.out.println("weight: " + c19.weight);
		System.out.println("isShockResistant: " + c19.isShockResistant);
		System.out.println("feature1: " + c19.feature1);
		System.out.println("feature2: " + c19.feature2);
		System.out.println("feature3: " + c19.feature3);
		System.out.println("isDecorative: " + c19.isDecorative);
		System.out.println("isPortable: " + c19.isPortable);
		System.out.println("rating: " + c19.rating);


		CrystalLamp c20 = new CrystalLamp();
		c20.productId = 120;
		c20.brandName = "Sample20";
		c20.lampType = "Sample20";
		c20.color = "Sample20";
		c20.voltage = 30.0;
		c20.price = 30.0;
		c20.isLED = true;
		c20.isAvailable = true;
		c20.manufacturingDate = "Sample20";
		c20.expiryDate = "Sample20";
		c20.usageType = "Sample20";
		c20.material = "Sample20";
		c20.brightnessLevel = 30.0;
		c20.isEnergyEfficient = true;
		c20.countryOfOrigin = "Sample20";
		c20.warrantyMonths = 120;
		c20.packagingType = "Sample20";
		c20.weight = 30.0;
		c20.isShockResistant = true;
		c20.feature1 = "Sample20";
		c20.feature2 = "Sample20";
		c20.feature3 = "Sample20";
		c20.isDecorative = true;
		c20.isPortable = true;
		c20.rating = 120;

		System.out.println("----- CrystalLamp 20 -----");
		System.out.println("productId: " + c20.productId);
		System.out.println("brandName: " + c20.brandName);
		System.out.println("lampType: " + c20.lampType);
		System.out.println("color: " + c20.color);
		System.out.println("voltage: " + c20.voltage);
		System.out.println("price: " + c20.price);
		System.out.println("isLED: " + c20.isLED);
		System.out.println("isAvailable: " + c20.isAvailable);
		System.out.println("manufacturingDate: " + c20.manufacturingDate);
		System.out.println("expiryDate: " + c20.expiryDate);
		System.out.println("usageType: " + c20.usageType);
		System.out.println("material: " + c20.material);
		System.out.println("brightnessLevel: " + c20.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c20.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c20.countryOfOrigin);
		System.out.println("warrantyMonths: " + c20.warrantyMonths);
		System.out.println("packagingType: " + c20.packagingType);
		System.out.println("weight: " + c20.weight);
		System.out.println("isShockResistant: " + c20.isShockResistant);
		System.out.println("feature1: " + c20.feature1);
		System.out.println("feature2: " + c20.feature2);
		System.out.println("feature3: " + c20.feature3);
		System.out.println("isDecorative: " + c20.isDecorative);
		System.out.println("isPortable: " + c20.isPortable);
		System.out.println("rating: " + c20.rating);


		CrystalLamp c21 = new CrystalLamp();
		c21.productId = 121;
		c21.brandName = "Sample21";
		c21.lampType = "Sample21";
		c21.color = "Sample21";
		c21.voltage = 31.0;
		c21.price = 31.0;
		c21.isLED = false;
		c21.isAvailable = false;
		c21.manufacturingDate = "Sample21";
		c21.expiryDate = "Sample21";
		c21.usageType = "Sample21";
		c21.material = "Sample21";
		c21.brightnessLevel = 31.0;
		c21.isEnergyEfficient = false;
		c21.countryOfOrigin = "Sample21";
		c21.warrantyMonths = 121;
		c21.packagingType = "Sample21";
		c21.weight = 31.0;
		c21.isShockResistant = false;
		c21.feature1 = "Sample21";
		c21.feature2 = "Sample21";
		c21.feature3 = "Sample21";
		c21.isDecorative = false;
		c21.isPortable = false;
		c21.rating = 121;

		System.out.println("----- CrystalLamp 21 -----");
		System.out.println("productId: " + c21.productId);
		System.out.println("brandName: " + c21.brandName);
		System.out.println("lampType: " + c21.lampType);
		System.out.println("color: " + c21.color);
		System.out.println("voltage: " + c21.voltage);
		System.out.println("price: " + c21.price);
		System.out.println("isLED: " + c21.isLED);
		System.out.println("isAvailable: " + c21.isAvailable);
		System.out.println("manufacturingDate: " + c21.manufacturingDate);
		System.out.println("expiryDate: " + c21.expiryDate);
		System.out.println("usageType: " + c21.usageType);
		System.out.println("material: " + c21.material);
		System.out.println("brightnessLevel: " + c21.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c21.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c21.countryOfOrigin);
		System.out.println("warrantyMonths: " + c21.warrantyMonths);
		System.out.println("packagingType: " + c21.packagingType);
		System.out.println("weight: " + c21.weight);
		System.out.println("isShockResistant: " + c21.isShockResistant);
		System.out.println("feature1: " + c21.feature1);
		System.out.println("feature2: " + c21.feature2);
		System.out.println("feature3: " + c21.feature3);
		System.out.println("isDecorative: " + c21.isDecorative);
		System.out.println("isPortable: " + c21.isPortable);
		System.out.println("rating: " + c21.rating);


		CrystalLamp c22 = new CrystalLamp();
		c22.productId = 122;
		c22.brandName = "Sample22";
		c22.lampType = "Sample22";
		c22.color = "Sample22";
		c22.voltage = 32.0;
		c22.price = 32.0;
		c22.isLED = true;
		c22.isAvailable = true;
		c22.manufacturingDate = "Sample22";
		c22.expiryDate = "Sample22";
		c22.usageType = "Sample22";
		c22.material = "Sample22";
		c22.brightnessLevel = 32.0;
		c22.isEnergyEfficient = true;
		c22.countryOfOrigin = "Sample22";
		c22.warrantyMonths = 122;
		c22.packagingType = "Sample22";
		c22.weight = 32.0;
		c22.isShockResistant = true;
		c22.feature1 = "Sample22";
		c22.feature2 = "Sample22";
		c22.feature3 = "Sample22";
		c22.isDecorative = true;
		c22.isPortable = true;
		c22.rating = 122;

		System.out.println("----- CrystalLamp 22 -----");
		System.out.println("productId: " + c22.productId);
		System.out.println("brandName: " + c22.brandName);
		System.out.println("lampType: " + c22.lampType);
		System.out.println("color: " + c22.color);
		System.out.println("voltage: " + c22.voltage);
		System.out.println("price: " + c22.price);
		System.out.println("isLED: " + c22.isLED);
		System.out.println("isAvailable: " + c22.isAvailable);
		System.out.println("manufacturingDate: " + c22.manufacturingDate);
		System.out.println("expiryDate: " + c22.expiryDate);
		System.out.println("usageType: " + c22.usageType);
		System.out.println("material: " + c22.material);
		System.out.println("brightnessLevel: " + c22.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c22.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c22.countryOfOrigin);
		System.out.println("warrantyMonths: " + c22.warrantyMonths);
		System.out.println("packagingType: " + c22.packagingType);
		System.out.println("weight: " + c22.weight);
		System.out.println("isShockResistant: " + c22.isShockResistant);
		System.out.println("feature1: " + c22.feature1);
		System.out.println("feature2: " + c22.feature2);
		System.out.println("feature3: " + c22.feature3);
		System.out.println("isDecorative: " + c22.isDecorative);
		System.out.println("isPortable: " + c22.isPortable);
		System.out.println("rating: " + c22.rating);


		CrystalLamp c23 = new CrystalLamp();
		c23.productId = 123;
		c23.brandName = "Sample23";
		c23.lampType = "Sample23";
		c23.color = "Sample23";
		c23.voltage = 33.0;
		c23.price = 33.0;
		c23.isLED = false;
		c23.isAvailable = false;
		c23.manufacturingDate = "Sample23";
		c23.expiryDate = "Sample23";
		c23.usageType = "Sample23";
		c23.material = "Sample23";
		c23.brightnessLevel = 33.0;
		c23.isEnergyEfficient = false;
		c23.countryOfOrigin = "Sample23";
		c23.warrantyMonths = 123;
		c23.packagingType = "Sample23";
		c23.weight = 33.0;
		c23.isShockResistant = false;
		c23.feature1 = "Sample23";
		c23.feature2 = "Sample23";
		c23.feature3 = "Sample23";
		c23.isDecorative = false;
		c23.isPortable = false;
		c23.rating = 123;

		System.out.println("----- CrystalLamp 23 -----");
		System.out.println("productId: " + c23.productId);
		System.out.println("brandName: " + c23.brandName);
		System.out.println("lampType: " + c23.lampType);
		System.out.println("color: " + c23.color);
		System.out.println("voltage: " + c23.voltage);
		System.out.println("price: " + c23.price);
		System.out.println("isLED: " + c23.isLED);
		System.out.println("isAvailable: " + c23.isAvailable);
		System.out.println("manufacturingDate: " + c23.manufacturingDate);
		System.out.println("expiryDate: " + c23.expiryDate);
		System.out.println("usageType: " + c23.usageType);
		System.out.println("material: " + c23.material);
		System.out.println("brightnessLevel: " + c23.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c23.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c23.countryOfOrigin);
		System.out.println("warrantyMonths: " + c23.warrantyMonths);
		System.out.println("packagingType: " + c23.packagingType);
		System.out.println("weight: " + c23.weight);
		System.out.println("isShockResistant: " + c23.isShockResistant);
		System.out.println("feature1: " + c23.feature1);
		System.out.println("feature2: " + c23.feature2);
		System.out.println("feature3: " + c23.feature3);
		System.out.println("isDecorative: " + c23.isDecorative);
		System.out.println("isPortable: " + c23.isPortable);
		System.out.println("rating: " + c23.rating);


		CrystalLamp c24 = new CrystalLamp();
		c24.productId = 124;
		c24.brandName = "Sample24";
		c24.lampType = "Sample24";
		c24.color = "Sample24";
		c24.voltage = 34.0;
		c24.price = 34.0;
		c24.isLED = true;
		c24.isAvailable = true;
		c24.manufacturingDate = "Sample24";
		c24.expiryDate = "Sample24";
		c24.usageType = "Sample24";
		c24.material = "Sample24";
		c24.brightnessLevel = 34.0;
		c24.isEnergyEfficient = true;
		c24.countryOfOrigin = "Sample24";
		c24.warrantyMonths = 124;
		c24.packagingType = "Sample24";
		c24.weight = 34.0;
		c24.isShockResistant = true;
		c24.feature1 = "Sample24";
		c24.feature2 = "Sample24";
		c24.feature3 = "Sample24";
		c24.isDecorative = true;
		c24.isPortable = true;
		c24.rating = 124;

		System.out.println("----- CrystalLamp 24 -----");
		System.out.println("productId: " + c24.productId);
		System.out.println("brandName: " + c24.brandName);
		System.out.println("lampType: " + c24.lampType);
		System.out.println("color: " + c24.color);
		System.out.println("voltage: " + c24.voltage);
		System.out.println("price: " + c24.price);
		System.out.println("isLED: " + c24.isLED);
		System.out.println("isAvailable: " + c24.isAvailable);
		System.out.println("manufacturingDate: " + c24.manufacturingDate);
		System.out.println("expiryDate: " + c24.expiryDate);
		System.out.println("usageType: " + c24.usageType);
		System.out.println("material: " + c24.material);
		System.out.println("brightnessLevel: " + c24.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c24.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c24.countryOfOrigin);
		System.out.println("warrantyMonths: " + c24.warrantyMonths);
		System.out.println("packagingType: " + c24.packagingType);
		System.out.println("weight: " + c24.weight);
		System.out.println("isShockResistant: " + c24.isShockResistant);
		System.out.println("feature1: " + c24.feature1);
		System.out.println("feature2: " + c24.feature2);
		System.out.println("feature3: " + c24.feature3);
		System.out.println("isDecorative: " + c24.isDecorative);
		System.out.println("isPortable: " + c24.isPortable);
		System.out.println("rating: " + c24.rating);


		CrystalLamp c25 = new CrystalLamp();
		c25.productId = 125;
		c25.brandName = "Sample25";
		c25.lampType = "Sample25";
		c25.color = "Sample25";
		c25.voltage = 35.0;
		c25.price = 35.0;
		c25.isLED = false;
		c25.isAvailable = false;
		c25.manufacturingDate = "Sample25";
		c25.expiryDate = "Sample25";
		c25.usageType = "Sample25";
		c25.material = "Sample25";
		c25.brightnessLevel = 35.0;
		c25.isEnergyEfficient = false;
		c25.countryOfOrigin = "Sample25";
		c25.warrantyMonths = 125;
		c25.packagingType = "Sample25";
		c25.weight = 35.0;
		c25.isShockResistant = false;
		c25.feature1 = "Sample25";
		c25.feature2 = "Sample25";
		c25.feature3 = "Sample25";
		c25.isDecorative = false;
		c25.isPortable = false;
		c25.rating = 125;

		System.out.println("----- CrystalLamp 25 -----");
		System.out.println("productId: " + c25.productId);
		System.out.println("brandName: " + c25.brandName);
		System.out.println("lampType: " + c25.lampType);
		System.out.println("color: " + c25.color);
		System.out.println("voltage: " + c25.voltage);
		System.out.println("price: " + c25.price);
		System.out.println("isLED: " + c25.isLED);
		System.out.println("isAvailable: " + c25.isAvailable);
		System.out.println("manufacturingDate: " + c25.manufacturingDate);
		System.out.println("expiryDate: " + c25.expiryDate);
		System.out.println("usageType: " + c25.usageType);
		System.out.println("material: " + c25.material);
		System.out.println("brightnessLevel: " + c25.brightnessLevel);
		System.out.println("isEnergyEfficient: " + c25.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + c25.countryOfOrigin);
		System.out.println("warrantyMonths: " + c25.warrantyMonths);
		System.out.println("packagingType: " + c25.packagingType);
		System.out.println("weight: " + c25.weight);
		System.out.println("isShockResistant: " + c25.isShockResistant);
		System.out.println("feature1: " + c25.feature1);
		System.out.println("feature2: " + c25.feature2);
		System.out.println("feature3: " + c25.feature3);
		System.out.println("isDecorative: " + c25.isDecorative);
		System.out.println("isPortable: " + c25.isPortable);
		System.out.println("rating: " + c25.rating);


	}
}

	