class EchoHeadphonesRunner {
	public static void main(String[] args) {

		EchoHeadphones e1 = new EchoHeadphones();
		e1.productId = 101;
		e1.brandName = "Sample1";
		e1.connectivityType = "Sample1";
		e1.color = "Sample1";
		e1.batteryCapacity = 11.0;
		e1.price = 11.0;
		e1.isWireless = false;
		e1.isAvailable = false;
		e1.manufacturingDate = "Sample1";
		e1.expiryDate = "Sample1";
		e1.driverType = "Sample1";
		e1.material = "Sample1";
		e1.frequencyRange = 11.0;
		e1.isNoiseCancelling = false;
		e1.countryOfOrigin = "Sample1";
		e1.warrantyMonths = 101;
		e1.packagingType = "Sample1";
		e1.weight = 11.0;
		e1.isFoldable = false;
		e1.feature1 = "Sample1";
		e1.feature2 = "Sample1";
		e1.feature3 = "Sample1";
		e1.hasMic = false;
		e1.hasBluetooth = false;
		e1.rating = 101;

		System.out.println("----- EchoHeadphones 1 -----");
		System.out.println("productId: " + e1.productId);
		System.out.println("brandName: " + e1.brandName);
		System.out.println("connectivityType: " + e1.connectivityType);
		System.out.println("color: " + e1.color);
		System.out.println("batteryCapacity: " + e1.batteryCapacity);
		System.out.println("price: " + e1.price);
		System.out.println("isWireless: " + e1.isWireless);
		System.out.println("isAvailable: " + e1.isAvailable);
		System.out.println("manufacturingDate: " + e1.manufacturingDate);
		System.out.println("expiryDate: " + e1.expiryDate);
		System.out.println("driverType: " + e1.driverType);
		System.out.println("material: " + e1.material);
		System.out.println("frequencyRange: " + e1.frequencyRange);
		System.out.println("isNoiseCancelling: " + e1.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e1.countryOfOrigin);
		System.out.println("warrantyMonths: " + e1.warrantyMonths);
		System.out.println("packagingType: " + e1.packagingType);
		System.out.println("weight: " + e1.weight);
		System.out.println("isFoldable: " + e1.isFoldable);
		System.out.println("feature1: " + e1.feature1);
		System.out.println("feature2: " + e1.feature2);
		System.out.println("feature3: " + e1.feature3);
		System.out.println("hasMic: " + e1.hasMic);
		System.out.println("hasBluetooth: " + e1.hasBluetooth);
		System.out.println("rating: " + e1.rating);


		EchoHeadphones e2 = new EchoHeadphones();
		e2.productId = 102;
		e2.brandName = "Sample2";
		e2.connectivityType = "Sample2";
		e2.color = "Sample2";
		e2.batteryCapacity = 12.0;
		e2.price = 12.0;
		e2.isWireless = true;
		e2.isAvailable = true;
		e2.manufacturingDate = "Sample2";
		e2.expiryDate = "Sample2";
		e2.driverType = "Sample2";
		e2.material = "Sample2";
		e2.frequencyRange = 12.0;
		e2.isNoiseCancelling = true;
		e2.countryOfOrigin = "Sample2";
		e2.warrantyMonths = 102;
		e2.packagingType = "Sample2";
		e2.weight = 12.0;
		e2.isFoldable = true;
		e2.feature1 = "Sample2";
		e2.feature2 = "Sample2";
		e2.feature3 = "Sample2";
		e2.hasMic = true;
		e2.hasBluetooth = true;
		e2.rating = 102;

		System.out.println("----- EchoHeadphones 2 -----");
		System.out.println("productId: " + e2.productId);
		System.out.println("brandName: " + e2.brandName);
		System.out.println("connectivityType: " + e2.connectivityType);
		System.out.println("color: " + e2.color);
		System.out.println("batteryCapacity: " + e2.batteryCapacity);
		System.out.println("price: " + e2.price);
		System.out.println("isWireless: " + e2.isWireless);
		System.out.println("isAvailable: " + e2.isAvailable);
		System.out.println("manufacturingDate: " + e2.manufacturingDate);
		System.out.println("expiryDate: " + e2.expiryDate);
		System.out.println("driverType: " + e2.driverType);
		System.out.println("material: " + e2.material);
		System.out.println("frequencyRange: " + e2.frequencyRange);
		System.out.println("isNoiseCancelling: " + e2.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e2.countryOfOrigin);
		System.out.println("warrantyMonths: " + e2.warrantyMonths);
		System.out.println("packagingType: " + e2.packagingType);
		System.out.println("weight: " + e2.weight);
		System.out.println("isFoldable: " + e2.isFoldable);
		System.out.println("feature1: " + e2.feature1);
		System.out.println("feature2: " + e2.feature2);
		System.out.println("feature3: " + e2.feature3);
		System.out.println("hasMic: " + e2.hasMic);
		System.out.println("hasBluetooth: " + e2.hasBluetooth);
		System.out.println("rating: " + e2.rating);


		EchoHeadphones e3 = new EchoHeadphones();
		e3.productId = 103;
		e3.brandName = "Sample3";
		e3.connectivityType = "Sample3";
		e3.color = "Sample3";
		e3.batteryCapacity = 13.0;
		e3.price = 13.0;
		e3.isWireless = false;
		e3.isAvailable = false;
		e3.manufacturingDate = "Sample3";
		e3.expiryDate = "Sample3";
		e3.driverType = "Sample3";
		e3.material = "Sample3";
		e3.frequencyRange = 13.0;
		e3.isNoiseCancelling = false;
		e3.countryOfOrigin = "Sample3";
		e3.warrantyMonths = 103;
		e3.packagingType = "Sample3";
		e3.weight = 13.0;
		e3.isFoldable = false;
		e3.feature1 = "Sample3";
		e3.feature2 = "Sample3";
		e3.feature3 = "Sample3";
		e3.hasMic = false;
		e3.hasBluetooth = false;
		e3.rating = 103;

		System.out.println("----- EchoHeadphones 3 -----");
		System.out.println("productId: " + e3.productId);
		System.out.println("brandName: " + e3.brandName);
		System.out.println("connectivityType: " + e3.connectivityType);
		System.out.println("color: " + e3.color);
		System.out.println("batteryCapacity: " + e3.batteryCapacity);
		System.out.println("price: " + e3.price);
		System.out.println("isWireless: " + e3.isWireless);
		System.out.println("isAvailable: " + e3.isAvailable);
		System.out.println("manufacturingDate: " + e3.manufacturingDate);
		System.out.println("expiryDate: " + e3.expiryDate);
		System.out.println("driverType: " + e3.driverType);
		System.out.println("material: " + e3.material);
		System.out.println("frequencyRange: " + e3.frequencyRange);
		System.out.println("isNoiseCancelling: " + e3.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e3.countryOfOrigin);
		System.out.println("warrantyMonths: " + e3.warrantyMonths);
		System.out.println("packagingType: " + e3.packagingType);
		System.out.println("weight: " + e3.weight);
		System.out.println("isFoldable: " + e3.isFoldable);
		System.out.println("feature1: " + e3.feature1);
		System.out.println("feature2: " + e3.feature2);
		System.out.println("feature3: " + e3.feature3);
		System.out.println("hasMic: " + e3.hasMic);
		System.out.println("hasBluetooth: " + e3.hasBluetooth);
		System.out.println("rating: " + e3.rating);


		EchoHeadphones e4 = new EchoHeadphones();
		e4.productId = 104;
		e4.brandName = "Sample4";
		e4.connectivityType = "Sample4";
		e4.color = "Sample4";
		e4.batteryCapacity = 14.0;
		e4.price = 14.0;
		e4.isWireless = true;
		e4.isAvailable = true;
		e4.manufacturingDate = "Sample4";
		e4.expiryDate = "Sample4";
		e4.driverType = "Sample4";
		e4.material = "Sample4";
		e4.frequencyRange = 14.0;
		e4.isNoiseCancelling = true;
		e4.countryOfOrigin = "Sample4";
		e4.warrantyMonths = 104;
		e4.packagingType = "Sample4";
		e4.weight = 14.0;
		e4.isFoldable = true;
		e4.feature1 = "Sample4";
		e4.feature2 = "Sample4";
		e4.feature3 = "Sample4";
		e4.hasMic = true;
		e4.hasBluetooth = true;
		e4.rating = 104;

		System.out.println("----- EchoHeadphones 4 -----");
		System.out.println("productId: " + e4.productId);
		System.out.println("brandName: " + e4.brandName);
		System.out.println("connectivityType: " + e4.connectivityType);
		System.out.println("color: " + e4.color);
		System.out.println("batteryCapacity: " + e4.batteryCapacity);
		System.out.println("price: " + e4.price);
		System.out.println("isWireless: " + e4.isWireless);
		System.out.println("isAvailable: " + e4.isAvailable);
		System.out.println("manufacturingDate: " + e4.manufacturingDate);
		System.out.println("expiryDate: " + e4.expiryDate);
		System.out.println("driverType: " + e4.driverType);
		System.out.println("material: " + e4.material);
		System.out.println("frequencyRange: " + e4.frequencyRange);
		System.out.println("isNoiseCancelling: " + e4.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e4.countryOfOrigin);
		System.out.println("warrantyMonths: " + e4.warrantyMonths);
		System.out.println("packagingType: " + e4.packagingType);
		System.out.println("weight: " + e4.weight);
		System.out.println("isFoldable: " + e4.isFoldable);
		System.out.println("feature1: " + e4.feature1);
		System.out.println("feature2: " + e4.feature2);
		System.out.println("feature3: " + e4.feature3);
		System.out.println("hasMic: " + e4.hasMic);
		System.out.println("hasBluetooth: " + e4.hasBluetooth);
		System.out.println("rating: " + e4.rating);


		EchoHeadphones e5 = new EchoHeadphones();
		e5.productId = 105;
		e5.brandName = "Sample5";
		e5.connectivityType = "Sample5";
		e5.color = "Sample5";
		e5.batteryCapacity = 15.0;
		e5.price = 15.0;
		e5.isWireless = false;
		e5.isAvailable = false;
		e5.manufacturingDate = "Sample5";
		e5.expiryDate = "Sample5";
		e5.driverType = "Sample5";
		e5.material = "Sample5";
		e5.frequencyRange = 15.0;
		e5.isNoiseCancelling = false;
		e5.countryOfOrigin = "Sample5";
		e5.warrantyMonths = 105;
		e5.packagingType = "Sample5";
		e5.weight = 15.0;
		e5.isFoldable = false;
		e5.feature1 = "Sample5";
		e5.feature2 = "Sample5";
		e5.feature3 = "Sample5";
		e5.hasMic = false;
		e5.hasBluetooth = false;
		e5.rating = 105;

		System.out.println("----- EchoHeadphones 5 -----");
		System.out.println("productId: " + e5.productId);
		System.out.println("brandName: " + e5.brandName);
		System.out.println("connectivityType: " + e5.connectivityType);
		System.out.println("color: " + e5.color);
		System.out.println("batteryCapacity: " + e5.batteryCapacity);
		System.out.println("price: " + e5.price);
		System.out.println("isWireless: " + e5.isWireless);
		System.out.println("isAvailable: " + e5.isAvailable);
		System.out.println("manufacturingDate: " + e5.manufacturingDate);
		System.out.println("expiryDate: " + e5.expiryDate);
		System.out.println("driverType: " + e5.driverType);
		System.out.println("material: " + e5.material);
		System.out.println("frequencyRange: " + e5.frequencyRange);
		System.out.println("isNoiseCancelling: " + e5.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e5.countryOfOrigin);
		System.out.println("warrantyMonths: " + e5.warrantyMonths);
		System.out.println("packagingType: " + e5.packagingType);
		System.out.println("weight: " + e5.weight);
		System.out.println("isFoldable: " + e5.isFoldable);
		System.out.println("feature1: " + e5.feature1);
		System.out.println("feature2: " + e5.feature2);
		System.out.println("feature3: " + e5.feature3);
		System.out.println("hasMic: " + e5.hasMic);
		System.out.println("hasBluetooth: " + e5.hasBluetooth);
		System.out.println("rating: " + e5.rating);


		EchoHeadphones e6 = new EchoHeadphones();
		e6.productId = 106;
		e6.brandName = "Sample6";
		e6.connectivityType = "Sample6";
		e6.color = "Sample6";
		e6.batteryCapacity = 16.0;
		e6.price = 16.0;
		e6.isWireless = true;
		e6.isAvailable = true;
		e6.manufacturingDate = "Sample6";
		e6.expiryDate = "Sample6";
		e6.driverType = "Sample6";
		e6.material = "Sample6";
		e6.frequencyRange = 16.0;
		e6.isNoiseCancelling = true;
		e6.countryOfOrigin = "Sample6";
		e6.warrantyMonths = 106;
		e6.packagingType = "Sample6";
		e6.weight = 16.0;
		e6.isFoldable = true;
		e6.feature1 = "Sample6";
		e6.feature2 = "Sample6";
		e6.feature3 = "Sample6";
		e6.hasMic = true;
		e6.hasBluetooth = true;
		e6.rating = 106;

		System.out.println("----- EchoHeadphones 6 -----");
		System.out.println("productId: " + e6.productId);
		System.out.println("brandName: " + e6.brandName);
		System.out.println("connectivityType: " + e6.connectivityType);
		System.out.println("color: " + e6.color);
		System.out.println("batteryCapacity: " + e6.batteryCapacity);
		System.out.println("price: " + e6.price);
		System.out.println("isWireless: " + e6.isWireless);
		System.out.println("isAvailable: " + e6.isAvailable);
		System.out.println("manufacturingDate: " + e6.manufacturingDate);
		System.out.println("expiryDate: " + e6.expiryDate);
		System.out.println("driverType: " + e6.driverType);
		System.out.println("material: " + e6.material);
		System.out.println("frequencyRange: " + e6.frequencyRange);
		System.out.println("isNoiseCancelling: " + e6.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e6.countryOfOrigin);
		System.out.println("warrantyMonths: " + e6.warrantyMonths);
		System.out.println("packagingType: " + e6.packagingType);
		System.out.println("weight: " + e6.weight);
		System.out.println("isFoldable: " + e6.isFoldable);
		System.out.println("feature1: " + e6.feature1);
		System.out.println("feature2: " + e6.feature2);
		System.out.println("feature3: " + e6.feature3);
		System.out.println("hasMic: " + e6.hasMic);
		System.out.println("hasBluetooth: " + e6.hasBluetooth);
		System.out.println("rating: " + e6.rating);


		EchoHeadphones e7 = new EchoHeadphones();
		e7.productId = 107;
		e7.brandName = "Sample7";
		e7.connectivityType = "Sample7";
		e7.color = "Sample7";
		e7.batteryCapacity = 17.0;
		e7.price = 17.0;
		e7.isWireless = false;
		e7.isAvailable = false;
		e7.manufacturingDate = "Sample7";
		e7.expiryDate = "Sample7";
		e7.driverType = "Sample7";
		e7.material = "Sample7";
		e7.frequencyRange = 17.0;
		e7.isNoiseCancelling = false;
		e7.countryOfOrigin = "Sample7";
		e7.warrantyMonths = 107;
		e7.packagingType = "Sample7";
		e7.weight = 17.0;
		e7.isFoldable = false;
		e7.feature1 = "Sample7";
		e7.feature2 = "Sample7";
		e7.feature3 = "Sample7";
		e7.hasMic = false;
		e7.hasBluetooth = false;
		e7.rating = 107;

		System.out.println("----- EchoHeadphones 7 -----");
		System.out.println("productId: " + e7.productId);
		System.out.println("brandName: " + e7.brandName);
		System.out.println("connectivityType: " + e7.connectivityType);
		System.out.println("color: " + e7.color);
		System.out.println("batteryCapacity: " + e7.batteryCapacity);
		System.out.println("price: " + e7.price);
		System.out.println("isWireless: " + e7.isWireless);
		System.out.println("isAvailable: " + e7.isAvailable);
		System.out.println("manufacturingDate: " + e7.manufacturingDate);
		System.out.println("expiryDate: " + e7.expiryDate);
		System.out.println("driverType: " + e7.driverType);
		System.out.println("material: " + e7.material);
		System.out.println("frequencyRange: " + e7.frequencyRange);
		System.out.println("isNoiseCancelling: " + e7.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e7.countryOfOrigin);
		System.out.println("warrantyMonths: " + e7.warrantyMonths);
		System.out.println("packagingType: " + e7.packagingType);
		System.out.println("weight: " + e7.weight);
		System.out.println("isFoldable: " + e7.isFoldable);
		System.out.println("feature1: " + e7.feature1);
		System.out.println("feature2: " + e7.feature2);
		System.out.println("feature3: " + e7.feature3);
		System.out.println("hasMic: " + e7.hasMic);
		System.out.println("hasBluetooth: " + e7.hasBluetooth);
		System.out.println("rating: " + e7.rating);


		EchoHeadphones e8 = new EchoHeadphones();
		e8.productId = 108;
		e8.brandName = "Sample8";
		e8.connectivityType = "Sample8";
		e8.color = "Sample8";
		e8.batteryCapacity = 18.0;
		e8.price = 18.0;
		e8.isWireless = true;
		e8.isAvailable = true;
		e8.manufacturingDate = "Sample8";
		e8.expiryDate = "Sample8";
		e8.driverType = "Sample8";
		e8.material = "Sample8";
		e8.frequencyRange = 18.0;
		e8.isNoiseCancelling = true;
		e8.countryOfOrigin = "Sample8";
		e8.warrantyMonths = 108;
		e8.packagingType = "Sample8";
		e8.weight = 18.0;
		e8.isFoldable = true;
		e8.feature1 = "Sample8";
		e8.feature2 = "Sample8";
		e8.feature3 = "Sample8";
		e8.hasMic = true;
		e8.hasBluetooth = true;
		e8.rating = 108;

		System.out.println("----- EchoHeadphones 8 -----");
		System.out.println("productId: " + e8.productId);
		System.out.println("brandName: " + e8.brandName);
		System.out.println("connectivityType: " + e8.connectivityType);
		System.out.println("color: " + e8.color);
		System.out.println("batteryCapacity: " + e8.batteryCapacity);
		System.out.println("price: " + e8.price);
		System.out.println("isWireless: " + e8.isWireless);
		System.out.println("isAvailable: " + e8.isAvailable);
		System.out.println("manufacturingDate: " + e8.manufacturingDate);
		System.out.println("expiryDate: " + e8.expiryDate);
		System.out.println("driverType: " + e8.driverType);
		System.out.println("material: " + e8.material);
		System.out.println("frequencyRange: " + e8.frequencyRange);
		System.out.println("isNoiseCancelling: " + e8.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e8.countryOfOrigin);
		System.out.println("warrantyMonths: " + e8.warrantyMonths);
		System.out.println("packagingType: " + e8.packagingType);
		System.out.println("weight: " + e8.weight);
		System.out.println("isFoldable: " + e8.isFoldable);
		System.out.println("feature1: " + e8.feature1);
		System.out.println("feature2: " + e8.feature2);
		System.out.println("feature3: " + e8.feature3);
		System.out.println("hasMic: " + e8.hasMic);
		System.out.println("hasBluetooth: " + e8.hasBluetooth);
		System.out.println("rating: " + e8.rating);


		EchoHeadphones e9 = new EchoHeadphones();
		e9.productId = 109;
		e9.brandName = "Sample9";
		e9.connectivityType = "Sample9";
		e9.color = "Sample9";
		e9.batteryCapacity = 19.0;
		e9.price = 19.0;
		e9.isWireless = false;
		e9.isAvailable = false;
		e9.manufacturingDate = "Sample9";
		e9.expiryDate = "Sample9";
		e9.driverType = "Sample9";
		e9.material = "Sample9";
		e9.frequencyRange = 19.0;
		e9.isNoiseCancelling = false;
		e9.countryOfOrigin = "Sample9";
		e9.warrantyMonths = 109;
		e9.packagingType = "Sample9";
		e9.weight = 19.0;
		e9.isFoldable = false;
		e9.feature1 = "Sample9";
		e9.feature2 = "Sample9";
		e9.feature3 = "Sample9";
		e9.hasMic = false;
		e9.hasBluetooth = false;
		e9.rating = 109;

		System.out.println("----- EchoHeadphones 9 -----");
		System.out.println("productId: " + e9.productId);
		System.out.println("brandName: " + e9.brandName);
		System.out.println("connectivityType: " + e9.connectivityType);
		System.out.println("color: " + e9.color);
		System.out.println("batteryCapacity: " + e9.batteryCapacity);
		System.out.println("price: " + e9.price);
		System.out.println("isWireless: " + e9.isWireless);
		System.out.println("isAvailable: " + e9.isAvailable);
		System.out.println("manufacturingDate: " + e9.manufacturingDate);
		System.out.println("expiryDate: " + e9.expiryDate);
		System.out.println("driverType: " + e9.driverType);
		System.out.println("material: " + e9.material);
		System.out.println("frequencyRange: " + e9.frequencyRange);
		System.out.println("isNoiseCancelling: " + e9.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e9.countryOfOrigin);
		System.out.println("warrantyMonths: " + e9.warrantyMonths);
		System.out.println("packagingType: " + e9.packagingType);
		System.out.println("weight: " + e9.weight);
		System.out.println("isFoldable: " + e9.isFoldable);
		System.out.println("feature1: " + e9.feature1);
		System.out.println("feature2: " + e9.feature2);
		System.out.println("feature3: " + e9.feature3);
		System.out.println("hasMic: " + e9.hasMic);
		System.out.println("hasBluetooth: " + e9.hasBluetooth);
		System.out.println("rating: " + e9.rating);


		EchoHeadphones e10 = new EchoHeadphones();
		e10.productId = 110;
		e10.brandName = "Sample10";
		e10.connectivityType = "Sample10";
		e10.color = "Sample10";
		e10.batteryCapacity = 20.0;
		e10.price = 20.0;
		e10.isWireless = true;
		e10.isAvailable = true;
		e10.manufacturingDate = "Sample10";
		e10.expiryDate = "Sample10";
		e10.driverType = "Sample10";
		e10.material = "Sample10";
		e10.frequencyRange = 20.0;
		e10.isNoiseCancelling = true;
		e10.countryOfOrigin = "Sample10";
		e10.warrantyMonths = 110;
		e10.packagingType = "Sample10";
		e10.weight = 20.0;
		e10.isFoldable = true;
		e10.feature1 = "Sample10";
		e10.feature2 = "Sample10";
		e10.feature3 = "Sample10";
		e10.hasMic = true;
		e10.hasBluetooth = true;
		e10.rating = 110;

		System.out.println("----- EchoHeadphones 10 -----");
		System.out.println("productId: " + e10.productId);
		System.out.println("brandName: " + e10.brandName);
		System.out.println("connectivityType: " + e10.connectivityType);
		System.out.println("color: " + e10.color);
		System.out.println("batteryCapacity: " + e10.batteryCapacity);
		System.out.println("price: " + e10.price);
		System.out.println("isWireless: " + e10.isWireless);
		System.out.println("isAvailable: " + e10.isAvailable);
		System.out.println("manufacturingDate: " + e10.manufacturingDate);
		System.out.println("expiryDate: " + e10.expiryDate);
		System.out.println("driverType: " + e10.driverType);
		System.out.println("material: " + e10.material);
		System.out.println("frequencyRange: " + e10.frequencyRange);
		System.out.println("isNoiseCancelling: " + e10.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e10.countryOfOrigin);
		System.out.println("warrantyMonths: " + e10.warrantyMonths);
		System.out.println("packagingType: " + e10.packagingType);
		System.out.println("weight: " + e10.weight);
		System.out.println("isFoldable: " + e10.isFoldable);
		System.out.println("feature1: " + e10.feature1);
		System.out.println("feature2: " + e10.feature2);
		System.out.println("feature3: " + e10.feature3);
		System.out.println("hasMic: " + e10.hasMic);
		System.out.println("hasBluetooth: " + e10.hasBluetooth);
		System.out.println("rating: " + e10.rating);


		EchoHeadphones e11 = new EchoHeadphones();
		e11.productId = 111;
		e11.brandName = "Sample11";
		e11.connectivityType = "Sample11";
		e11.color = "Sample11";
		e11.batteryCapacity = 21.0;
		e11.price = 21.0;
		e11.isWireless = false;
		e11.isAvailable = false;
		e11.manufacturingDate = "Sample11";
		e11.expiryDate = "Sample11";
		e11.driverType = "Sample11";
		e11.material = "Sample11";
		e11.frequencyRange = 21.0;
		e11.isNoiseCancelling = false;
		e11.countryOfOrigin = "Sample11";
		e11.warrantyMonths = 111;
		e11.packagingType = "Sample11";
		e11.weight = 21.0;
		e11.isFoldable = false;
		e11.feature1 = "Sample11";
		e11.feature2 = "Sample11";
		e11.feature3 = "Sample11";
		e11.hasMic = false;
		e11.hasBluetooth = false;
		e11.rating = 111;

		System.out.println("----- EchoHeadphones 11 -----");
		System.out.println("productId: " + e11.productId);
		System.out.println("brandName: " + e11.brandName);
		System.out.println("connectivityType: " + e11.connectivityType);
		System.out.println("color: " + e11.color);
		System.out.println("batteryCapacity: " + e11.batteryCapacity);
		System.out.println("price: " + e11.price);
		System.out.println("isWireless: " + e11.isWireless);
		System.out.println("isAvailable: " + e11.isAvailable);
		System.out.println("manufacturingDate: " + e11.manufacturingDate);
		System.out.println("expiryDate: " + e11.expiryDate);
		System.out.println("driverType: " + e11.driverType);
		System.out.println("material: " + e11.material);
		System.out.println("frequencyRange: " + e11.frequencyRange);
		System.out.println("isNoiseCancelling: " + e11.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e11.countryOfOrigin);
		System.out.println("warrantyMonths: " + e11.warrantyMonths);
		System.out.println("packagingType: " + e11.packagingType);
		System.out.println("weight: " + e11.weight);
		System.out.println("isFoldable: " + e11.isFoldable);
		System.out.println("feature1: " + e11.feature1);
		System.out.println("feature2: " + e11.feature2);
		System.out.println("feature3: " + e11.feature3);
		System.out.println("hasMic: " + e11.hasMic);
		System.out.println("hasBluetooth: " + e11.hasBluetooth);
		System.out.println("rating: " + e11.rating);


		EchoHeadphones e12 = new EchoHeadphones();
		e12.productId = 112;
		e12.brandName = "Sample12";
		e12.connectivityType = "Sample12";
		e12.color = "Sample12";
		e12.batteryCapacity = 22.0;
		e12.price = 22.0;
		e12.isWireless = true;
		e12.isAvailable = true;
		e12.manufacturingDate = "Sample12";
		e12.expiryDate = "Sample12";
		e12.driverType = "Sample12";
		e12.material = "Sample12";
		e12.frequencyRange = 22.0;
		e12.isNoiseCancelling = true;
		e12.countryOfOrigin = "Sample12";
		e12.warrantyMonths = 112;
		e12.packagingType = "Sample12";
		e12.weight = 22.0;
		e12.isFoldable = true;
		e12.feature1 = "Sample12";
		e12.feature2 = "Sample12";
		e12.feature3 = "Sample12";
		e12.hasMic = true;
		e12.hasBluetooth = true;
		e12.rating = 112;

		System.out.println("----- EchoHeadphones 12 -----");
		System.out.println("productId: " + e12.productId);
		System.out.println("brandName: " + e12.brandName);
		System.out.println("connectivityType: " + e12.connectivityType);
		System.out.println("color: " + e12.color);
		System.out.println("batteryCapacity: " + e12.batteryCapacity);
		System.out.println("price: " + e12.price);
		System.out.println("isWireless: " + e12.isWireless);
		System.out.println("isAvailable: " + e12.isAvailable);
		System.out.println("manufacturingDate: " + e12.manufacturingDate);
		System.out.println("expiryDate: " + e12.expiryDate);
		System.out.println("driverType: " + e12.driverType);
		System.out.println("material: " + e12.material);
		System.out.println("frequencyRange: " + e12.frequencyRange);
		System.out.println("isNoiseCancelling: " + e12.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e12.countryOfOrigin);
		System.out.println("warrantyMonths: " + e12.warrantyMonths);
		System.out.println("packagingType: " + e12.packagingType);
		System.out.println("weight: " + e12.weight);
		System.out.println("isFoldable: " + e12.isFoldable);
		System.out.println("feature1: " + e12.feature1);
		System.out.println("feature2: " + e12.feature2);
		System.out.println("feature3: " + e12.feature3);
		System.out.println("hasMic: " + e12.hasMic);
		System.out.println("hasBluetooth: " + e12.hasBluetooth);
		System.out.println("rating: " + e12.rating);


		EchoHeadphones e13 = new EchoHeadphones();
		e13.productId = 113;
		e13.brandName = "Sample13";
		e13.connectivityType = "Sample13";
		e13.color = "Sample13";
		e13.batteryCapacity = 23.0;
		e13.price = 23.0;
		e13.isWireless = false;
		e13.isAvailable = false;
		e13.manufacturingDate = "Sample13";
		e13.expiryDate = "Sample13";
		e13.driverType = "Sample13";
		e13.material = "Sample13";
		e13.frequencyRange = 23.0;
		e13.isNoiseCancelling = false;
		e13.countryOfOrigin = "Sample13";
		e13.warrantyMonths = 113;
		e13.packagingType = "Sample13";
		e13.weight = 23.0;
		e13.isFoldable = false;
		e13.feature1 = "Sample13";
		e13.feature2 = "Sample13";
		e13.feature3 = "Sample13";
		e13.hasMic = false;
		e13.hasBluetooth = false;
		e13.rating = 113;

		System.out.println("----- EchoHeadphones 13 -----");
		System.out.println("productId: " + e13.productId);
		System.out.println("brandName: " + e13.brandName);
		System.out.println("connectivityType: " + e13.connectivityType);
		System.out.println("color: " + e13.color);
		System.out.println("batteryCapacity: " + e13.batteryCapacity);
		System.out.println("price: " + e13.price);
		System.out.println("isWireless: " + e13.isWireless);
		System.out.println("isAvailable: " + e13.isAvailable);
		System.out.println("manufacturingDate: " + e13.manufacturingDate);
		System.out.println("expiryDate: " + e13.expiryDate);
		System.out.println("driverType: " + e13.driverType);
		System.out.println("material: " + e13.material);
		System.out.println("frequencyRange: " + e13.frequencyRange);
		System.out.println("isNoiseCancelling: " + e13.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e13.countryOfOrigin);
		System.out.println("warrantyMonths: " + e13.warrantyMonths);
		System.out.println("packagingType: " + e13.packagingType);
		System.out.println("weight: " + e13.weight);
		System.out.println("isFoldable: " + e13.isFoldable);
		System.out.println("feature1: " + e13.feature1);
		System.out.println("feature2: " + e13.feature2);
		System.out.println("feature3: " + e13.feature3);
		System.out.println("hasMic: " + e13.hasMic);
		System.out.println("hasBluetooth: " + e13.hasBluetooth);
		System.out.println("rating: " + e13.rating);


		EchoHeadphones e14 = new EchoHeadphones();
		e14.productId = 114;
		e14.brandName = "Sample14";
		e14.connectivityType = "Sample14";
		e14.color = "Sample14";
		e14.batteryCapacity = 24.0;
		e14.price = 24.0;
		e14.isWireless = true;
		e14.isAvailable = true;
		e14.manufacturingDate = "Sample14";
		e14.expiryDate = "Sample14";
		e14.driverType = "Sample14";
		e14.material = "Sample14";
		e14.frequencyRange = 24.0;
		e14.isNoiseCancelling = true;
		e14.countryOfOrigin = "Sample14";
		e14.warrantyMonths = 114;
		e14.packagingType = "Sample14";
		e14.weight = 24.0;
		e14.isFoldable = true;
		e14.feature1 = "Sample14";
		e14.feature2 = "Sample14";
		e14.feature3 = "Sample14";
		e14.hasMic = true;
		e14.hasBluetooth = true;
		e14.rating = 114;

		System.out.println("----- EchoHeadphones 14 -----");
		System.out.println("productId: " + e14.productId);
		System.out.println("brandName: " + e14.brandName);
		System.out.println("connectivityType: " + e14.connectivityType);
		System.out.println("color: " + e14.color);
		System.out.println("batteryCapacity: " + e14.batteryCapacity);
		System.out.println("price: " + e14.price);
		System.out.println("isWireless: " + e14.isWireless);
		System.out.println("isAvailable: " + e14.isAvailable);
		System.out.println("manufacturingDate: " + e14.manufacturingDate);
		System.out.println("expiryDate: " + e14.expiryDate);
		System.out.println("driverType: " + e14.driverType);
		System.out.println("material: " + e14.material);
		System.out.println("frequencyRange: " + e14.frequencyRange);
		System.out.println("isNoiseCancelling: " + e14.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e14.countryOfOrigin);
		System.out.println("warrantyMonths: " + e14.warrantyMonths);
		System.out.println("packagingType: " + e14.packagingType);
		System.out.println("weight: " + e14.weight);
		System.out.println("isFoldable: " + e14.isFoldable);
		System.out.println("feature1: " + e14.feature1);
		System.out.println("feature2: " + e14.feature2);
		System.out.println("feature3: " + e14.feature3);
		System.out.println("hasMic: " + e14.hasMic);
		System.out.println("hasBluetooth: " + e14.hasBluetooth);
		System.out.println("rating: " + e14.rating);


		EchoHeadphones e15 = new EchoHeadphones();
		e15.productId = 115;
		e15.brandName = "Sample15";
		e15.connectivityType = "Sample15";
		e15.color = "Sample15";
		e15.batteryCapacity = 25.0;
		e15.price = 25.0;
		e15.isWireless = false;
		e15.isAvailable = false;
		e15.manufacturingDate = "Sample15";
		e15.expiryDate = "Sample15";
		e15.driverType = "Sample15";
		e15.material = "Sample15";
		e15.frequencyRange = 25.0;
		e15.isNoiseCancelling = false;
		e15.countryOfOrigin = "Sample15";
		e15.warrantyMonths = 115;
		e15.packagingType = "Sample15";
		e15.weight = 25.0;
		e15.isFoldable = false;
		e15.feature1 = "Sample15";
		e15.feature2 = "Sample15";
		e15.feature3 = "Sample15";
		e15.hasMic = false;
		e15.hasBluetooth = false;
		e15.rating = 115;

		System.out.println("----- EchoHeadphones 15 -----");
		System.out.println("productId: " + e15.productId);
		System.out.println("brandName: " + e15.brandName);
		System.out.println("connectivityType: " + e15.connectivityType);
		System.out.println("color: " + e15.color);
		System.out.println("batteryCapacity: " + e15.batteryCapacity);
		System.out.println("price: " + e15.price);
		System.out.println("isWireless: " + e15.isWireless);
		System.out.println("isAvailable: " + e15.isAvailable);
		System.out.println("manufacturingDate: " + e15.manufacturingDate);
		System.out.println("expiryDate: " + e15.expiryDate);
		System.out.println("driverType: " + e15.driverType);
		System.out.println("material: " + e15.material);
		System.out.println("frequencyRange: " + e15.frequencyRange);
		System.out.println("isNoiseCancelling: " + e15.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e15.countryOfOrigin);
		System.out.println("warrantyMonths: " + e15.warrantyMonths);
		System.out.println("packagingType: " + e15.packagingType);
		System.out.println("weight: " + e15.weight);
		System.out.println("isFoldable: " + e15.isFoldable);
		System.out.println("feature1: " + e15.feature1);
		System.out.println("feature2: " + e15.feature2);
		System.out.println("feature3: " + e15.feature3);
		System.out.println("hasMic: " + e15.hasMic);
		System.out.println("hasBluetooth: " + e15.hasBluetooth);
		System.out.println("rating: " + e15.rating);


		EchoHeadphones e16 = new EchoHeadphones();
		e16.productId = 116;
		e16.brandName = "Sample16";
		e16.connectivityType = "Sample16";
		e16.color = "Sample16";
		e16.batteryCapacity = 26.0;
		e16.price = 26.0;
		e16.isWireless = true;
		e16.isAvailable = true;
		e16.manufacturingDate = "Sample16";
		e16.expiryDate = "Sample16";
		e16.driverType = "Sample16";
		e16.material = "Sample16";
		e16.frequencyRange = 26.0;
		e16.isNoiseCancelling = true;
		e16.countryOfOrigin = "Sample16";
		e16.warrantyMonths = 116;
		e16.packagingType = "Sample16";
		e16.weight = 26.0;
		e16.isFoldable = true;
		e16.feature1 = "Sample16";
		e16.feature2 = "Sample16";
		e16.feature3 = "Sample16";
		e16.hasMic = true;
		e16.hasBluetooth = true;
		e16.rating = 116;

		System.out.println("----- EchoHeadphones 16 -----");
		System.out.println("productId: " + e16.productId);
		System.out.println("brandName: " + e16.brandName);
		System.out.println("connectivityType: " + e16.connectivityType);
		System.out.println("color: " + e16.color);
		System.out.println("batteryCapacity: " + e16.batteryCapacity);
		System.out.println("price: " + e16.price);
		System.out.println("isWireless: " + e16.isWireless);
		System.out.println("isAvailable: " + e16.isAvailable);
		System.out.println("manufacturingDate: " + e16.manufacturingDate);
		System.out.println("expiryDate: " + e16.expiryDate);
		System.out.println("driverType: " + e16.driverType);
		System.out.println("material: " + e16.material);
		System.out.println("frequencyRange: " + e16.frequencyRange);
		System.out.println("isNoiseCancelling: " + e16.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e16.countryOfOrigin);
		System.out.println("warrantyMonths: " + e16.warrantyMonths);
		System.out.println("packagingType: " + e16.packagingType);
		System.out.println("weight: " + e16.weight);
		System.out.println("isFoldable: " + e16.isFoldable);
		System.out.println("feature1: " + e16.feature1);
		System.out.println("feature2: " + e16.feature2);
		System.out.println("feature3: " + e16.feature3);
		System.out.println("hasMic: " + e16.hasMic);
		System.out.println("hasBluetooth: " + e16.hasBluetooth);
		System.out.println("rating: " + e16.rating);


		EchoHeadphones e17 = new EchoHeadphones();
		e17.productId = 117;
		e17.brandName = "Sample17";
		e17.connectivityType = "Sample17";
		e17.color = "Sample17";
		e17.batteryCapacity = 27.0;
		e17.price = 27.0;
		e17.isWireless = false;
		e17.isAvailable = false;
		e17.manufacturingDate = "Sample17";
		e17.expiryDate = "Sample17";
		e17.driverType = "Sample17";
		e17.material = "Sample17";
		e17.frequencyRange = 27.0;
		e17.isNoiseCancelling = false;
		e17.countryOfOrigin = "Sample17";
		e17.warrantyMonths = 117;
		e17.packagingType = "Sample17";
		e17.weight = 27.0;
		e17.isFoldable = false;
		e17.feature1 = "Sample17";
		e17.feature2 = "Sample17";
		e17.feature3 = "Sample17";
		e17.hasMic = false;
		e17.hasBluetooth = false;
		e17.rating = 117;

		System.out.println("----- EchoHeadphones 17 -----");
		System.out.println("productId: " + e17.productId);
		System.out.println("brandName: " + e17.brandName);
		System.out.println("connectivityType: " + e17.connectivityType);
		System.out.println("color: " + e17.color);
		System.out.println("batteryCapacity: " + e17.batteryCapacity);
		System.out.println("price: " + e17.price);
		System.out.println("isWireless: " + e17.isWireless);
		System.out.println("isAvailable: " + e17.isAvailable);
		System.out.println("manufacturingDate: " + e17.manufacturingDate);
		System.out.println("expiryDate: " + e17.expiryDate);
		System.out.println("driverType: " + e17.driverType);
		System.out.println("material: " + e17.material);
		System.out.println("frequencyRange: " + e17.frequencyRange);
		System.out.println("isNoiseCancelling: " + e17.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e17.countryOfOrigin);
		System.out.println("warrantyMonths: " + e17.warrantyMonths);
		System.out.println("packagingType: " + e17.packagingType);
		System.out.println("weight: " + e17.weight);
		System.out.println("isFoldable: " + e17.isFoldable);
		System.out.println("feature1: " + e17.feature1);
		System.out.println("feature2: " + e17.feature2);
		System.out.println("feature3: " + e17.feature3);
		System.out.println("hasMic: " + e17.hasMic);
		System.out.println("hasBluetooth: " + e17.hasBluetooth);
		System.out.println("rating: " + e17.rating);


		EchoHeadphones e18 = new EchoHeadphones();
		e18.productId = 118;
		e18.brandName = "Sample18";
		e18.connectivityType = "Sample18";
		e18.color = "Sample18";
		e18.batteryCapacity = 28.0;
		e18.price = 28.0;
		e18.isWireless = true;
		e18.isAvailable = true;
		e18.manufacturingDate = "Sample18";
		e18.expiryDate = "Sample18";
		e18.driverType = "Sample18";
		e18.material = "Sample18";
		e18.frequencyRange = 28.0;
		e18.isNoiseCancelling = true;
		e18.countryOfOrigin = "Sample18";
		e18.warrantyMonths = 118;
		e18.packagingType = "Sample18";
		e18.weight = 28.0;
		e18.isFoldable = true;
		e18.feature1 = "Sample18";
		e18.feature2 = "Sample18";
		e18.feature3 = "Sample18";
		e18.hasMic = true;
		e18.hasBluetooth = true;
		e18.rating = 118;

		System.out.println("----- EchoHeadphones 18 -----");
		System.out.println("productId: " + e18.productId);
		System.out.println("brandName: " + e18.brandName);
		System.out.println("connectivityType: " + e18.connectivityType);
		System.out.println("color: " + e18.color);
		System.out.println("batteryCapacity: " + e18.batteryCapacity);
		System.out.println("price: " + e18.price);
		System.out.println("isWireless: " + e18.isWireless);
		System.out.println("isAvailable: " + e18.isAvailable);
		System.out.println("manufacturingDate: " + e18.manufacturingDate);
		System.out.println("expiryDate: " + e18.expiryDate);
		System.out.println("driverType: " + e18.driverType);
		System.out.println("material: " + e18.material);
		System.out.println("frequencyRange: " + e18.frequencyRange);
		System.out.println("isNoiseCancelling: " + e18.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e18.countryOfOrigin);
		System.out.println("warrantyMonths: " + e18.warrantyMonths);
		System.out.println("packagingType: " + e18.packagingType);
		System.out.println("weight: " + e18.weight);
		System.out.println("isFoldable: " + e18.isFoldable);
		System.out.println("feature1: " + e18.feature1);
		System.out.println("feature2: " + e18.feature2);
		System.out.println("feature3: " + e18.feature3);
		System.out.println("hasMic: " + e18.hasMic);
		System.out.println("hasBluetooth: " + e18.hasBluetooth);
		System.out.println("rating: " + e18.rating);


		EchoHeadphones e19 = new EchoHeadphones();
		e19.productId = 119;
		e19.brandName = "Sample19";
		e19.connectivityType = "Sample19";
		e19.color = "Sample19";
		e19.batteryCapacity = 29.0;
		e19.price = 29.0;
		e19.isWireless = false;
		e19.isAvailable = false;
		e19.manufacturingDate = "Sample19";
		e19.expiryDate = "Sample19";
		e19.driverType = "Sample19";
		e19.material = "Sample19";
		e19.frequencyRange = 29.0;
		e19.isNoiseCancelling = false;
		e19.countryOfOrigin = "Sample19";
		e19.warrantyMonths = 119;
		e19.packagingType = "Sample19";
		e19.weight = 29.0;
		e19.isFoldable = false;
		e19.feature1 = "Sample19";
		e19.feature2 = "Sample19";
		e19.feature3 = "Sample19";
		e19.hasMic = false;
		e19.hasBluetooth = false;
		e19.rating = 119;

		System.out.println("----- EchoHeadphones 19 -----");
		System.out.println("productId: " + e19.productId);
		System.out.println("brandName: " + e19.brandName);
		System.out.println("connectivityType: " + e19.connectivityType);
		System.out.println("color: " + e19.color);
		System.out.println("batteryCapacity: " + e19.batteryCapacity);
		System.out.println("price: " + e19.price);
		System.out.println("isWireless: " + e19.isWireless);
		System.out.println("isAvailable: " + e19.isAvailable);
		System.out.println("manufacturingDate: " + e19.manufacturingDate);
		System.out.println("expiryDate: " + e19.expiryDate);
		System.out.println("driverType: " + e19.driverType);
		System.out.println("material: " + e19.material);
		System.out.println("frequencyRange: " + e19.frequencyRange);
		System.out.println("isNoiseCancelling: " + e19.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e19.countryOfOrigin);
		System.out.println("warrantyMonths: " + e19.warrantyMonths);
		System.out.println("packagingType: " + e19.packagingType);
		System.out.println("weight: " + e19.weight);
		System.out.println("isFoldable: " + e19.isFoldable);
		System.out.println("feature1: " + e19.feature1);
		System.out.println("feature2: " + e19.feature2);
		System.out.println("feature3: " + e19.feature3);
		System.out.println("hasMic: " + e19.hasMic);
		System.out.println("hasBluetooth: " + e19.hasBluetooth);
		System.out.println("rating: " + e19.rating);


		EchoHeadphones e20 = new EchoHeadphones();
		e20.productId = 120;
		e20.brandName = "Sample20";
		e20.connectivityType = "Sample20";
		e20.color = "Sample20";
		e20.batteryCapacity = 30.0;
		e20.price = 30.0;
		e20.isWireless = true;
		e20.isAvailable = true;
		e20.manufacturingDate = "Sample20";
		e20.expiryDate = "Sample20";
		e20.driverType = "Sample20";
		e20.material = "Sample20";
		e20.frequencyRange = 30.0;
		e20.isNoiseCancelling = true;
		e20.countryOfOrigin = "Sample20";
		e20.warrantyMonths = 120;
		e20.packagingType = "Sample20";
		e20.weight = 30.0;
		e20.isFoldable = true;
		e20.feature1 = "Sample20";
		e20.feature2 = "Sample20";
		e20.feature3 = "Sample20";
		e20.hasMic = true;
		e20.hasBluetooth = true;
		e20.rating = 120;

		System.out.println("----- EchoHeadphones 20 -----");
		System.out.println("productId: " + e20.productId);
		System.out.println("brandName: " + e20.brandName);
		System.out.println("connectivityType: " + e20.connectivityType);
		System.out.println("color: " + e20.color);
		System.out.println("batteryCapacity: " + e20.batteryCapacity);
		System.out.println("price: " + e20.price);
		System.out.println("isWireless: " + e20.isWireless);
		System.out.println("isAvailable: " + e20.isAvailable);
		System.out.println("manufacturingDate: " + e20.manufacturingDate);
		System.out.println("expiryDate: " + e20.expiryDate);
		System.out.println("driverType: " + e20.driverType);
		System.out.println("material: " + e20.material);
		System.out.println("frequencyRange: " + e20.frequencyRange);
		System.out.println("isNoiseCancelling: " + e20.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e20.countryOfOrigin);
		System.out.println("warrantyMonths: " + e20.warrantyMonths);
		System.out.println("packagingType: " + e20.packagingType);
		System.out.println("weight: " + e20.weight);
		System.out.println("isFoldable: " + e20.isFoldable);
		System.out.println("feature1: " + e20.feature1);
		System.out.println("feature2: " + e20.feature2);
		System.out.println("feature3: " + e20.feature3);
		System.out.println("hasMic: " + e20.hasMic);
		System.out.println("hasBluetooth: " + e20.hasBluetooth);
		System.out.println("rating: " + e20.rating);


		EchoHeadphones e21 = new EchoHeadphones();
		e21.productId = 121;
		e21.brandName = "Sample21";
		e21.connectivityType = "Sample21";
		e21.color = "Sample21";
		e21.batteryCapacity = 31.0;
		e21.price = 31.0;
		e21.isWireless = false;
		e21.isAvailable = false;
		e21.manufacturingDate = "Sample21";
		e21.expiryDate = "Sample21";
		e21.driverType = "Sample21";
		e21.material = "Sample21";
		e21.frequencyRange = 31.0;
		e21.isNoiseCancelling = false;
		e21.countryOfOrigin = "Sample21";
		e21.warrantyMonths = 121;
		e21.packagingType = "Sample21";
		e21.weight = 31.0;
		e21.isFoldable = false;
		e21.feature1 = "Sample21";
		e21.feature2 = "Sample21";
		e21.feature3 = "Sample21";
		e21.hasMic = false;
		e21.hasBluetooth = false;
		e21.rating = 121;

		System.out.println("----- EchoHeadphones 21 -----");
		System.out.println("productId: " + e21.productId);
		System.out.println("brandName: " + e21.brandName);
		System.out.println("connectivityType: " + e21.connectivityType);
		System.out.println("color: " + e21.color);
		System.out.println("batteryCapacity: " + e21.batteryCapacity);
		System.out.println("price: " + e21.price);
		System.out.println("isWireless: " + e21.isWireless);
		System.out.println("isAvailable: " + e21.isAvailable);
		System.out.println("manufacturingDate: " + e21.manufacturingDate);
		System.out.println("expiryDate: " + e21.expiryDate);
		System.out.println("driverType: " + e21.driverType);
		System.out.println("material: " + e21.material);
		System.out.println("frequencyRange: " + e21.frequencyRange);
		System.out.println("isNoiseCancelling: " + e21.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e21.countryOfOrigin);
		System.out.println("warrantyMonths: " + e21.warrantyMonths);
		System.out.println("packagingType: " + e21.packagingType);
		System.out.println("weight: " + e21.weight);
		System.out.println("isFoldable: " + e21.isFoldable);
		System.out.println("feature1: " + e21.feature1);
		System.out.println("feature2: " + e21.feature2);
		System.out.println("feature3: " + e21.feature3);
		System.out.println("hasMic: " + e21.hasMic);
		System.out.println("hasBluetooth: " + e21.hasBluetooth);
		System.out.println("rating: " + e21.rating);


		EchoHeadphones e22 = new EchoHeadphones();
		e22.productId = 122;
		e22.brandName = "Sample22";
		e22.connectivityType = "Sample22";
		e22.color = "Sample22";
		e22.batteryCapacity = 32.0;
		e22.price = 32.0;
		e22.isWireless = true;
		e22.isAvailable = true;
		e22.manufacturingDate = "Sample22";
		e22.expiryDate = "Sample22";
		e22.driverType = "Sample22";
		e22.material = "Sample22";
		e22.frequencyRange = 32.0;
		e22.isNoiseCancelling = true;
		e22.countryOfOrigin = "Sample22";
		e22.warrantyMonths = 122;
		e22.packagingType = "Sample22";
		e22.weight = 32.0;
		e22.isFoldable = true;
		e22.feature1 = "Sample22";
		e22.feature2 = "Sample22";
		e22.feature3 = "Sample22";
		e22.hasMic = true;
		e22.hasBluetooth = true;
		e22.rating = 122;

		System.out.println("----- EchoHeadphones 22 -----");
		System.out.println("productId: " + e22.productId);
		System.out.println("brandName: " + e22.brandName);
		System.out.println("connectivityType: " + e22.connectivityType);
		System.out.println("color: " + e22.color);
		System.out.println("batteryCapacity: " + e22.batteryCapacity);
		System.out.println("price: " + e22.price);
		System.out.println("isWireless: " + e22.isWireless);
		System.out.println("isAvailable: " + e22.isAvailable);
		System.out.println("manufacturingDate: " + e22.manufacturingDate);
		System.out.println("expiryDate: " + e22.expiryDate);
		System.out.println("driverType: " + e22.driverType);
		System.out.println("material: " + e22.material);
		System.out.println("frequencyRange: " + e22.frequencyRange);
		System.out.println("isNoiseCancelling: " + e22.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e22.countryOfOrigin);
		System.out.println("warrantyMonths: " + e22.warrantyMonths);
		System.out.println("packagingType: " + e22.packagingType);
		System.out.println("weight: " + e22.weight);
		System.out.println("isFoldable: " + e22.isFoldable);
		System.out.println("feature1: " + e22.feature1);
		System.out.println("feature2: " + e22.feature2);
		System.out.println("feature3: " + e22.feature3);
		System.out.println("hasMic: " + e22.hasMic);
		System.out.println("hasBluetooth: " + e22.hasBluetooth);
		System.out.println("rating: " + e22.rating);


		EchoHeadphones e23 = new EchoHeadphones();
		e23.productId = 123;
		e23.brandName = "Sample23";
		e23.connectivityType = "Sample23";
		e23.color = "Sample23";
		e23.batteryCapacity = 33.0;
		e23.price = 33.0;
		e23.isWireless = false;
		e23.isAvailable = false;
		e23.manufacturingDate = "Sample23";
		e23.expiryDate = "Sample23";
		e23.driverType = "Sample23";
		e23.material = "Sample23";
		e23.frequencyRange = 33.0;
		e23.isNoiseCancelling = false;
		e23.countryOfOrigin = "Sample23";
		e23.warrantyMonths = 123;
		e23.packagingType = "Sample23";
		e23.weight = 33.0;
		e23.isFoldable = false;
		e23.feature1 = "Sample23";
		e23.feature2 = "Sample23";
		e23.feature3 = "Sample23";
		e23.hasMic = false;
		e23.hasBluetooth = false;
		e23.rating = 123;

		System.out.println("----- EchoHeadphones 23 -----");
		System.out.println("productId: " + e23.productId);
		System.out.println("brandName: " + e23.brandName);
		System.out.println("connectivityType: " + e23.connectivityType);
		System.out.println("color: " + e23.color);
		System.out.println("batteryCapacity: " + e23.batteryCapacity);
		System.out.println("price: " + e23.price);
		System.out.println("isWireless: " + e23.isWireless);
		System.out.println("isAvailable: " + e23.isAvailable);
		System.out.println("manufacturingDate: " + e23.manufacturingDate);
		System.out.println("expiryDate: " + e23.expiryDate);
		System.out.println("driverType: " + e23.driverType);
		System.out.println("material: " + e23.material);
		System.out.println("frequencyRange: " + e23.frequencyRange);
		System.out.println("isNoiseCancelling: " + e23.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e23.countryOfOrigin);
		System.out.println("warrantyMonths: " + e23.warrantyMonths);
		System.out.println("packagingType: " + e23.packagingType);
		System.out.println("weight: " + e23.weight);
		System.out.println("isFoldable: " + e23.isFoldable);
		System.out.println("feature1: " + e23.feature1);
		System.out.println("feature2: " + e23.feature2);
		System.out.println("feature3: " + e23.feature3);
		System.out.println("hasMic: " + e23.hasMic);
		System.out.println("hasBluetooth: " + e23.hasBluetooth);
		System.out.println("rating: " + e23.rating);


		EchoHeadphones e24 = new EchoHeadphones();
		e24.productId = 124;
		e24.brandName = "Sample24";
		e24.connectivityType = "Sample24";
		e24.color = "Sample24";
		e24.batteryCapacity = 34.0;
		e24.price = 34.0;
		e24.isWireless = true;
		e24.isAvailable = true;
		e24.manufacturingDate = "Sample24";
		e24.expiryDate = "Sample24";
		e24.driverType = "Sample24";
		e24.material = "Sample24";
		e24.frequencyRange = 34.0;
		e24.isNoiseCancelling = true;
		e24.countryOfOrigin = "Sample24";
		e24.warrantyMonths = 124;
		e24.packagingType = "Sample24";
		e24.weight = 34.0;
		e24.isFoldable = true;
		e24.feature1 = "Sample24";
		e24.feature2 = "Sample24";
		e24.feature3 = "Sample24";
		e24.hasMic = true;
		e24.hasBluetooth = true;
		e24.rating = 124;

		System.out.println("----- EchoHeadphones 24 -----");
		System.out.println("productId: " + e24.productId);
		System.out.println("brandName: " + e24.brandName);
		System.out.println("connectivityType: " + e24.connectivityType);
		System.out.println("color: " + e24.color);
		System.out.println("batteryCapacity: " + e24.batteryCapacity);
		System.out.println("price: " + e24.price);
		System.out.println("isWireless: " + e24.isWireless);
		System.out.println("isAvailable: " + e24.isAvailable);
		System.out.println("manufacturingDate: " + e24.manufacturingDate);
		System.out.println("expiryDate: " + e24.expiryDate);
		System.out.println("driverType: " + e24.driverType);
		System.out.println("material: " + e24.material);
		System.out.println("frequencyRange: " + e24.frequencyRange);
		System.out.println("isNoiseCancelling: " + e24.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e24.countryOfOrigin);
		System.out.println("warrantyMonths: " + e24.warrantyMonths);
		System.out.println("packagingType: " + e24.packagingType);
		System.out.println("weight: " + e24.weight);
		System.out.println("isFoldable: " + e24.isFoldable);
		System.out.println("feature1: " + e24.feature1);
		System.out.println("feature2: " + e24.feature2);
		System.out.println("feature3: " + e24.feature3);
		System.out.println("hasMic: " + e24.hasMic);
		System.out.println("hasBluetooth: " + e24.hasBluetooth);
		System.out.println("rating: " + e24.rating);


		EchoHeadphones e25 = new EchoHeadphones();
		e25.productId = 125;
		e25.brandName = "Sample25";
		e25.connectivityType = "Sample25";
		e25.color = "Sample25";
		e25.batteryCapacity = 35.0;
		e25.price = 35.0;
		e25.isWireless = false;
		e25.isAvailable = false;
		e25.manufacturingDate = "Sample25";
		e25.expiryDate = "Sample25";
		e25.driverType = "Sample25";
		e25.material = "Sample25";
		e25.frequencyRange = 35.0;
		e25.isNoiseCancelling = false;
		e25.countryOfOrigin = "Sample25";
		e25.warrantyMonths = 125;
		e25.packagingType = "Sample25";
		e25.weight = 35.0;
		e25.isFoldable = false;
		e25.feature1 = "Sample25";
		e25.feature2 = "Sample25";
		e25.feature3 = "Sample25";
		e25.hasMic = false;
		e25.hasBluetooth = false;
		e25.rating = 125;

		System.out.println("----- EchoHeadphones 25 -----");
		System.out.println("productId: " + e25.productId);
		System.out.println("brandName: " + e25.brandName);
		System.out.println("connectivityType: " + e25.connectivityType);
		System.out.println("color: " + e25.color);
		System.out.println("batteryCapacity: " + e25.batteryCapacity);
		System.out.println("price: " + e25.price);
		System.out.println("isWireless: " + e25.isWireless);
		System.out.println("isAvailable: " + e25.isAvailable);
		System.out.println("manufacturingDate: " + e25.manufacturingDate);
		System.out.println("expiryDate: " + e25.expiryDate);
		System.out.println("driverType: " + e25.driverType);
		System.out.println("material: " + e25.material);
		System.out.println("frequencyRange: " + e25.frequencyRange);
		System.out.println("isNoiseCancelling: " + e25.isNoiseCancelling);
		System.out.println("countryOfOrigin: " + e25.countryOfOrigin);
		System.out.println("warrantyMonths: " + e25.warrantyMonths);
		System.out.println("packagingType: " + e25.packagingType);
		System.out.println("weight: " + e25.weight);
		System.out.println("isFoldable: " + e25.isFoldable);
		System.out.println("feature1: " + e25.feature1);
		System.out.println("feature2: " + e25.feature2);
		System.out.println("feature3: " + e25.feature3);
		System.out.println("hasMic: " + e25.hasMic);
		System.out.println("hasBluetooth: " + e25.hasBluetooth);
		System.out.println("rating: " + e25.rating);


	}
}
