class ElevatorExecutor {
    public static void main(String[] args) {
        boolean isValidate;

        isValidate = Elevator.createElevator("Otis", 8, "Passenger", 15, 680.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Schindler", 15, "Freight", 40, 1500.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Kone", 6, "Residential", 10, 450.0, true, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Thyssenkrupp", 20, "Hospital", 25, 2000.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Mitsubishi", 10, "Observation", 50, 800.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Fujitec", 12, "Office", 30, 1000.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Hitachi", 25, "Industrial", 5, 3000.0, false, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Toshiba", 8, "Capsule", 20, 600.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Hyundai", 13, "Passenger", 18, 900.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Johnson", 4, "Home Lift", 3, 300.0, true, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Omega", 10, "Stretcher", 12, 1200.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator(null, 10, "Passenger", 10, 700.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("",0, "Freight", 20, 1500.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Otis", 0, "Passenger", 15, 600.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Schindler", -5, "Freight", 10, 1000.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Kone", 8, null, 12, 600.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Kone", 8, "", 12, 600.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Mitsubishi", 10, "Passenger", 0, 800.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Mitsubishi", 10, "Passenger", -1, 800.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Fujitec", 12, "Office", 20, 0.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Fujitec", 12, "Office", 20, -100.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator(null, 0, null, 0, 0.0, false, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Express", 10, "MRL", 14, 750.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Kleemann", 21, "Vehicle", 4, 5000.0, true, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Orona", 8, "Eco-Lift", 8, 630.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Stannah", 2, "Stair Lift", 2, 150.0, false, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Canny", 16, "Passenger", 22, 1150.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Sanyo", 10, "Glass Lift", 15, 800.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Espero", 11, "Passenger", 12, 825.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Xizi", 9, "Passenger", 10, 675.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Glarie", 8, "Residential", 6, 600.0, true, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Aritco", 5, "Platform", 4, 400.0, false, false);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Eito", 10, "Service", 25, 1000.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Dover", 15, "Hydraulic", 5, 1200.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Montgomery", 12, "Traction", 30, 900.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Haughton", 10, "Passenger", 15, 750.0, true, true);
        Elevator.getElevatorDetails();
        isValidate = Elevator.createElevator("Armor", 8, "Freight", 10, 2000.0, false, true);
        Elevator.getElevatorDetails();
    }
}