class FoodExecutor {
    public static void main(String[] args) {
        boolean isValidate;

        isValidate = Food.createFood("Paneer Tikka", "Starter", 250.0, 320, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Chicken Burger", "Fast Food", 180.0, 550, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Masala Dosa", "Breakfast", 80.0, 400, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Pepperoni Pizza", "Italian", 599.0, 1200, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Greek Salad", "Salad", 350.0, 150, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Sushi Roll", "Japanese", 850.0, 250, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Pasta Alfredo", "Italian", 450.0, 700, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Fish and Chips", "Seafood", 550.0, 850, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Veg Biryani", "Main Course", 220.0, 600, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Mutton Rogan Josh", "Main Course", 480.0, 900, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Chocolate Brownie", "Dessert", 120.0, 450, true);
        Food.getFoodDetails();
        isValidate = Food.createFood(null, "Starter", 100.0, 200, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("", "Main Course", 250.0, 500, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Tacos", null, 300.0, 400, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Nachos", "", 200.0, 600, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("French Fries", "Sides", 0.0, 300, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Spring Rolls", "Starter", -50.0, 250, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Ice Cream", "Dessert", 90.0, 0, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Apple Pie", "Dessert", 150.0, -100, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Steak", "Main Course", 950.0, 1100, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Garlic Bread", "Sides", 110.0, 350, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Chicken Wings", "Starter", 320.0, 800, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Momos", "Street Food", 100.0, 280, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Ramen", "Japanese", 600.0, 500, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Idli Sambar", "Breakfast", 60.0, 200, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Butter Chicken", "Main Course", 400.0, 850, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Club Sandwich", "Snack", 220.0, 450, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Falafel wrap", "Snack", 180.0, 350, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Hot Dog", "Fast Food", 120.0, 300, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Egg Curry", "Main Course", 150.0, 400, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Pancakes", "Breakfast", 250.0, 600, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Pad Thai", "Thai", 450.0, 550, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Waffles", "Breakfast", 280.0, 700, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Pav Bhaji", "Street Food", 120.0, 500, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Shrimp Scampi", "Italian", 750.0, 400, false);
        Food.getFoodDetails();
        isValidate = Food.createFood("Gulab Jamun", "Dessert", 60.0, 300, true);
        Food.getFoodDetails();
        isValidate = Food.createFood("Fruit Salad", "Salad", 150.0, 120, true);
        Food.getFoodDetails();
    }
}