class Forever24Executor {
    public static void main(String[] args) {
        boolean isValidate;

        isValidate = Forever24.createInventoryItem("Crop Top", "Tops", "S", 999.0, "Pink", "Cotton", 50, true, 10.0, "Summer24", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("High-Rise Jeans", "Denim", "M", 2499.0, "Blue", "Denim", 30, false, 0.0, "Classic", true, "Vietnam");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Leather Jacket", "Outerwear", "L", 4500.0, "Black", "Leather", 15, true, 20.0, "Winter24", false, "Turkey");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Floral Dress", "Dresses", "S", 1800.0, "Yellow", "Rayon", 40, true, 15.0, "Spring24", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Graphic Tee", "Tops", "XL", 799.0, "White", "Cotton", 100, false, 0.0, "Urban", true, "Bangladesh");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Mini Skirt", "Bottoms", "XS", 1200.0, "Red", "Polyester", 25, true, 5.0, "PartyWear", true, "China");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Cargo Pants", "Bottoms", "L", 2200.0, "Olive", "Canvas", 35, false, 0.0, "StreetStyle", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Oversized Hoodie", "Tops", "XL", 1999.0, "Grey", "Fleece", 60, true, 25.0, "Lounge", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Bikini Set", "Swimwear", "S", 1500.0, "Cyan", "Nylon", 20, false, 0.0, "Beach24", false, "Thailand");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Ankle Boots", "Footwear", "8", 3200.0, "Brown", "Suede", 10, true, 30.0, "Autumn24", true, "Spain");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Sunglasses", "Accessories", "Free", 850.0, "Gold", "Metal", 150, false, 0.0, "Retro", false, "Italy");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem(null, "Tops", "M", 500.0, "White", "Silk", 10, false, 0.0, "Luxury", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("", "Bottoms", "L", 400.0, "Black", "Wool", 5, true, 10.0, "Formal", true, "UK");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Joggers", null, "S", 900.0, "Navy", "Cotton", 45, false, 0.0, "Active", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Shorts", "", "M", 600.0, "Tan", "Linen", 55, true, 5.0, "Holiday", true, "Sri Lanka");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Blazer", "Workwear", null, 3500.0, "Beige", "Polyester", 12, false, 0.0, "Professional", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Scarf", "Accessories", "", 450.0, "Multicolor", "Wool", 80, true, 50.0, "Winter24", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Silk Scarf", "Accessories", "OneSize", 0.0, "Red", "Silk", 20, false, 0.0, "Premium", true, "France");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Sweater", "Outerwear", "L", -500.0, "Green", "Knit", 18, true, 10.0, "Cozy", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Belt", "Accessories", "M", 650.0, null, "Leather", 100, false, 0.0, "Basics", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Handbag", "Accessories", "Medium", 2800.0, "", "Vegan Leather", 8, true, 15.0, "Style", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Cap", "Accessories", "Adjustable", 550.0, "Black", null, 200, false, 0.0, "Sport", true, "China");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Beanie", "Accessories", "OneSize", 350.0, "Purple", "", 120, true, 5.0, "Winter24", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Maxi Dress", "Dresses", "XL", 2999.0, "Blue", "Chiffon", -5, false, 0.0, "Evening", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Tote Bag", "Accessories", "Large", 1200.0, "Cream", "Canvas", 40, true, 110.0, "Daily", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Tank Top", "Tops", "S", 499.0, "Peach", "Jersey", 75, false, 0.0, null, true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Camisole", "Tops", "M", 399.0, "White", "Satin", 85, true, 10.0, "", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Denim Jacket", "Outerwear", "L", 2999.0, "Blue", "Denim", 14, false, 0.0, "Essentials", true, null);
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Leggings", "Bottoms", "M", 899.0, "Black", "Spandex", 110, true, 5.0, "Yoga", true, "");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Polo Shirt", "Tops", "XL", 1100.0, "Navy", "Cotton", 30, false, 0.0, "Sporty", true, "Pakistan");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Tube Top", "Tops", "XS", 550.0, "Silver", "Sequins", 22, true, 20.0, "NightOut", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Platform Heels", "Footwear", "7", 3800.0, "Nude", "Synthetic", 12, false, 0.0, "Occasion", true, "Brazil");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Palazzo", "Bottoms", "L", 1400.0, "Maroon", "Viscose", 28, true, 15.0, "Boho", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Trench Coat", "Outerwear", "M", 5500.0, "Camel", "Gabardine", 5, false, 0.0, "London", true, "England");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Slip Dress", "Dresses", "S", 1600.0, "Emerald", "Satin", 18, true, 10.0, "DateNight", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Cardigan", "Outerwear", "L", 1800.0, "Lilac", "Acrylic", 20, false, 0.0, "CottageCore", true, "India");
        Forever24.getItemDetails();
        isValidate = Forever24.createInventoryItem("Kimono", "Tops", "Free", 1300.0, "Floral", "Silk", 15, true, 5.0, "Resort", true, "Japan");
        Forever24.getItemDetails();
    }
}