class FusionMixerRunner {
	public static void main(String[] args) {

		FusionMixer f1 = new FusionMixer();
		f1.productId = 101;
		f1.brandName = "Sample1";
		f1.mixerType = "Sample1";
		f1.color = "Sample1";
		f1.capacity = 11.0;
		f1.price = 11.0;
		f1.isElectric = false;
		f1.isAvailable = false;
		f1.manufacturingDate = "Sample1";
		f1.expiryDate = "Sample1";
		f1.bladeMaterial = "Sample1";
		f1.jarMaterial = "Sample1";
		f1.power = 11.0;
		f1.isShockProof = false;
		f1.countryOfOrigin = "Sample1";
		f1.warrantyMonths = 101;
		f1.packagingType = "Sample1";
		f1.weight = 11.0;
		f1.hasSpeedControl = false;
		f1.feature1 = "Sample1";
		f1.feature2 = "Sample1";
		f1.feature3 = "Sample1";
		f1.isPortable = false;
		f1.isEnergyEfficient = false;
		f1.rating = 101;

		System.out.println("----- FusionMixer 1 -----");
		System.out.println("productId: " + f1.productId);
		System.out.println("brandName: " + f1.brandName);
		System.out.println("mixerType: " + f1.mixerType);
		System.out.println("color: " + f1.color);
		System.out.println("capacity: " + f1.capacity);
		System.out.println("price: " + f1.price);
		System.out.println("isElectric: " + f1.isElectric);
		System.out.println("isAvailable: " + f1.isAvailable);
		System.out.println("manufacturingDate: " + f1.manufacturingDate);
		System.out.println("expiryDate: " + f1.expiryDate);
		System.out.println("bladeMaterial: " + f1.bladeMaterial);
		System.out.println("jarMaterial: " + f1.jarMaterial);
		System.out.println("power: " + f1.power);
		System.out.println("isShockProof: " + f1.isShockProof);
		System.out.println("countryOfOrigin: " + f1.countryOfOrigin);
		System.out.println("warrantyMonths: " + f1.warrantyMonths);
		System.out.println("packagingType: " + f1.packagingType);
		System.out.println("weight: " + f1.weight);
		System.out.println("hasSpeedControl: " + f1.hasSpeedControl);
		System.out.println("feature1: " + f1.feature1);
		System.out.println("feature2: " + f1.feature2);
		System.out.println("feature3: " + f1.feature3);
		System.out.println("isPortable: " + f1.isPortable);
		System.out.println("isEnergyEfficient: " + f1.isEnergyEfficient);
		System.out.println("rating: " + f1.rating);


		FusionMixer f2 = new FusionMixer();
		f2.productId = 102;
		f2.brandName = "Sample2";
		f2.mixerType = "Sample2";
		f2.color = "Sample2";
		f2.capacity = 12.0;
		f2.price = 12.0;
		f2.isElectric = true;
		f2.isAvailable = true;
		f2.manufacturingDate = "Sample2";
		f2.expiryDate = "Sample2";
		f2.bladeMaterial = "Sample2";
		f2.jarMaterial = "Sample2";
		f2.power = 12.0;
		f2.isShockProof = true;
		f2.countryOfOrigin = "Sample2";
		f2.warrantyMonths = 102;
		f2.packagingType = "Sample2";
		f2.weight = 12.0;
		f2.hasSpeedControl = true;
		f2.feature1 = "Sample2";
		f2.feature2 = "Sample2";
		f2.feature3 = "Sample2";
		f2.isPortable = true;
		f2.isEnergyEfficient = true;
		f2.rating = 102;

		System.out.println("----- FusionMixer 2 -----");
		System.out.println("productId: " + f2.productId);
		System.out.println("brandName: " + f2.brandName);
		System.out.println("mixerType: " + f2.mixerType);
		System.out.println("color: " + f2.color);
		System.out.println("capacity: " + f2.capacity);
		System.out.println("price: " + f2.price);
		System.out.println("isElectric: " + f2.isElectric);
		System.out.println("isAvailable: " + f2.isAvailable);
		System.out.println("manufacturingDate: " + f2.manufacturingDate);
		System.out.println("expiryDate: " + f2.expiryDate);
		System.out.println("bladeMaterial: " + f2.bladeMaterial);
		System.out.println("jarMaterial: " + f2.jarMaterial);
		System.out.println("power: " + f2.power);
		System.out.println("isShockProof: " + f2.isShockProof);
		System.out.println("countryOfOrigin: " + f2.countryOfOrigin);
		System.out.println("warrantyMonths: " + f2.warrantyMonths);
		System.out.println("packagingType: " + f2.packagingType);
		System.out.println("weight: " + f2.weight);
		System.out.println("hasSpeedControl: " + f2.hasSpeedControl);
		System.out.println("feature1: " + f2.feature1);
		System.out.println("feature2: " + f2.feature2);
		System.out.println("feature3: " + f2.feature3);
		System.out.println("isPortable: " + f2.isPortable);
		System.out.println("isEnergyEfficient: " + f2.isEnergyEfficient);
		System.out.println("rating: " + f2.rating);


		FusionMixer f3 = new FusionMixer();
		f3.productId = 103;
		f3.brandName = "Sample3";
		f3.mixerType = "Sample3";
		f3.color = "Sample3";
		f3.capacity = 13.0;
		f3.price = 13.0;
		f3.isElectric = false;
		f3.isAvailable = false;
		f3.manufacturingDate = "Sample3";
		f3.expiryDate = "Sample3";
		f3.bladeMaterial = "Sample3";
		f3.jarMaterial = "Sample3";
		f3.power = 13.0;
		f3.isShockProof = false;
		f3.countryOfOrigin = "Sample3";
		f3.warrantyMonths = 103;
		f3.packagingType = "Sample3";
		f3.weight = 13.0;
		f3.hasSpeedControl = false;
		f3.feature1 = "Sample3";
		f3.feature2 = "Sample3";
		f3.feature3 = "Sample3";
		f3.isPortable = false;
		f3.isEnergyEfficient = false;
		f3.rating = 103;

		System.out.println("----- FusionMixer 3 -----");
		System.out.println("productId: " + f3.productId);
		System.out.println("brandName: " + f3.brandName);
		System.out.println("mixerType: " + f3.mixerType);
		System.out.println("color: " + f3.color);
		System.out.println("capacity: " + f3.capacity);
		System.out.println("price: " + f3.price);
		System.out.println("isElectric: " + f3.isElectric);
		System.out.println("isAvailable: " + f3.isAvailable);
		System.out.println("manufacturingDate: " + f3.manufacturingDate);
		System.out.println("expiryDate: " + f3.expiryDate);
		System.out.println("bladeMaterial: " + f3.bladeMaterial);
		System.out.println("jarMaterial: " + f3.jarMaterial);
		System.out.println("power: " + f3.power);
		System.out.println("isShockProof: " + f3.isShockProof);
		System.out.println("countryOfOrigin: " + f3.countryOfOrigin);
		System.out.println("warrantyMonths: " + f3.warrantyMonths);
		System.out.println("packagingType: " + f3.packagingType);
		System.out.println("weight: " + f3.weight);
		System.out.println("hasSpeedControl: " + f3.hasSpeedControl);
		System.out.println("feature1: " + f3.feature1);
		System.out.println("feature2: " + f3.feature2);
		System.out.println("feature3: " + f3.feature3);
		System.out.println("isPortable: " + f3.isPortable);
		System.out.println("isEnergyEfficient: " + f3.isEnergyEfficient);
		System.out.println("rating: " + f3.rating);


		FusionMixer f4 = new FusionMixer();
		f4.productId = 104;
		f4.brandName = "Sample4";
		f4.mixerType = "Sample4";
		f4.color = "Sample4";
		f4.capacity = 14.0;
		f4.price = 14.0;
		f4.isElectric = true;
		f4.isAvailable = true;
		f4.manufacturingDate = "Sample4";
		f4.expiryDate = "Sample4";
		f4.bladeMaterial = "Sample4";
		f4.jarMaterial = "Sample4";
		f4.power = 14.0;
		f4.isShockProof = true;
		f4.countryOfOrigin = "Sample4";
		f4.warrantyMonths = 104;
		f4.packagingType = "Sample4";
		f4.weight = 14.0;
		f4.hasSpeedControl = true;
		f4.feature1 = "Sample4";
		f4.feature2 = "Sample4";
		f4.feature3 = "Sample4";
		f4.isPortable = true;
		f4.isEnergyEfficient = true;
		f4.rating = 104;

		System.out.println("----- FusionMixer 4 -----");
		System.out.println("productId: " + f4.productId);
		System.out.println("brandName: " + f4.brandName);
		System.out.println("mixerType: " + f4.mixerType);
		System.out.println("color: " + f4.color);
		System.out.println("capacity: " + f4.capacity);
		System.out.println("price: " + f4.price);
		System.out.println("isElectric: " + f4.isElectric);
		System.out.println("isAvailable: " + f4.isAvailable);
		System.out.println("manufacturingDate: " + f4.manufacturingDate);
		System.out.println("expiryDate: " + f4.expiryDate);
		System.out.println("bladeMaterial: " + f4.bladeMaterial);
		System.out.println("jarMaterial: " + f4.jarMaterial);
		System.out.println("power: " + f4.power);
		System.out.println("isShockProof: " + f4.isShockProof);
		System.out.println("countryOfOrigin: " + f4.countryOfOrigin);
		System.out.println("warrantyMonths: " + f4.warrantyMonths);
		System.out.println("packagingType: " + f4.packagingType);
		System.out.println("weight: " + f4.weight);
		System.out.println("hasSpeedControl: " + f4.hasSpeedControl);
		System.out.println("feature1: " + f4.feature1);
		System.out.println("feature2: " + f4.feature2);
		System.out.println("feature3: " + f4.feature3);
		System.out.println("isPortable: " + f4.isPortable);
		System.out.println("isEnergyEfficient: " + f4.isEnergyEfficient);
		System.out.println("rating: " + f4.rating);


		FusionMixer f5 = new FusionMixer();
		f5.productId = 105;
		f5.brandName = "Sample5";
		f5.mixerType = "Sample5";
		f5.color = "Sample5";
		f5.capacity = 15.0;
		f5.price = 15.0;
		f5.isElectric = false;
		f5.isAvailable = false;
		f5.manufacturingDate = "Sample5";
		f5.expiryDate = "Sample5";
		f5.bladeMaterial = "Sample5";
		f5.jarMaterial = "Sample5";
		f5.power = 15.0;
		f5.isShockProof = false;
		f5.countryOfOrigin = "Sample5";
		f5.warrantyMonths = 105;
		f5.packagingType = "Sample5";
		f5.weight = 15.0;
		f5.hasSpeedControl = false;
		f5.feature1 = "Sample5";
		f5.feature2 = "Sample5";
		f5.feature3 = "Sample5";
		f5.isPortable = false;
		f5.isEnergyEfficient = false;
		f5.rating = 105;

		System.out.println("----- FusionMixer 5 -----");
		System.out.println("productId: " + f5.productId);
		System.out.println("brandName: " + f5.brandName);
		System.out.println("mixerType: " + f5.mixerType);
		System.out.println("color: " + f5.color);
		System.out.println("capacity: " + f5.capacity);
		System.out.println("price: " + f5.price);
		System.out.println("isElectric: " + f5.isElectric);
		System.out.println("isAvailable: " + f5.isAvailable);
		System.out.println("manufacturingDate: " + f5.manufacturingDate);
		System.out.println("expiryDate: " + f5.expiryDate);
		System.out.println("bladeMaterial: " + f5.bladeMaterial);
		System.out.println("jarMaterial: " + f5.jarMaterial);
		System.out.println("power: " + f5.power);
		System.out.println("isShockProof: " + f5.isShockProof);
		System.out.println("countryOfOrigin: " + f5.countryOfOrigin);
		System.out.println("warrantyMonths: " + f5.warrantyMonths);
		System.out.println("packagingType: " + f5.packagingType);
		System.out.println("weight: " + f5.weight);
		System.out.println("hasSpeedControl: " + f5.hasSpeedControl);
		System.out.println("feature1: " + f5.feature1);
		System.out.println("feature2: " + f5.feature2);
		System.out.println("feature3: " + f5.feature3);
		System.out.println("isPortable: " + f5.isPortable);
		System.out.println("isEnergyEfficient: " + f5.isEnergyEfficient);
		System.out.println("rating: " + f5.rating);


		FusionMixer f6 = new FusionMixer();
		f6.productId = 106;
		f6.brandName = "Sample6";
		f6.mixerType = "Sample6";
		f6.color = "Sample6";
		f6.capacity = 16.0;
		f6.price = 16.0;
		f6.isElectric = true;
		f6.isAvailable = true;
		f6.manufacturingDate = "Sample6";
		f6.expiryDate = "Sample6";
		f6.bladeMaterial = "Sample6";
		f6.jarMaterial = "Sample6";
		f6.power = 16.0;
		f6.isShockProof = true;
		f6.countryOfOrigin = "Sample6";
		f6.warrantyMonths = 106;
		f6.packagingType = "Sample6";
		f6.weight = 16.0;
		f6.hasSpeedControl = true;
		f6.feature1 = "Sample6";
		f6.feature2 = "Sample6";
		f6.feature3 = "Sample6";
		f6.isPortable = true;
		f6.isEnergyEfficient = true;
		f6.rating = 106;

		System.out.println("----- FusionMixer 6 -----");
		System.out.println("productId: " + f6.productId);
		System.out.println("brandName: " + f6.brandName);
		System.out.println("mixerType: " + f6.mixerType);
		System.out.println("color: " + f6.color);
		System.out.println("capacity: " + f6.capacity);
		System.out.println("price: " + f6.price);
		System.out.println("isElectric: " + f6.isElectric);
		System.out.println("isAvailable: " + f6.isAvailable);
		System.out.println("manufacturingDate: " + f6.manufacturingDate);
		System.out.println("expiryDate: " + f6.expiryDate);
		System.out.println("bladeMaterial: " + f6.bladeMaterial);
		System.out.println("jarMaterial: " + f6.jarMaterial);
		System.out.println("power: " + f6.power);
		System.out.println("isShockProof: " + f6.isShockProof);
		System.out.println("countryOfOrigin: " + f6.countryOfOrigin);
		System.out.println("warrantyMonths: " + f6.warrantyMonths);
		System.out.println("packagingType: " + f6.packagingType);
		System.out.println("weight: " + f6.weight);
		System.out.println("hasSpeedControl: " + f6.hasSpeedControl);
		System.out.println("feature1: " + f6.feature1);
		System.out.println("feature2: " + f6.feature2);
		System.out.println("feature3: " + f6.feature3);
		System.out.println("isPortable: " + f6.isPortable);
		System.out.println("isEnergyEfficient: " + f6.isEnergyEfficient);
		System.out.println("rating: " + f6.rating);


		FusionMixer f7 = new FusionMixer();
		f7.productId = 107;
		f7.brandName = "Sample7";
		f7.mixerType = "Sample7";
		f7.color = "Sample7";
		f7.capacity = 17.0;
		f7.price = 17.0;
		f7.isElectric = false;
		f7.isAvailable = false;
		f7.manufacturingDate = "Sample7";
		f7.expiryDate = "Sample7";
		f7.bladeMaterial = "Sample7";
		f7.jarMaterial = "Sample7";
		f7.power = 17.0;
		f7.isShockProof = false;
		f7.countryOfOrigin = "Sample7";
		f7.warrantyMonths = 107;
		f7.packagingType = "Sample7";
		f7.weight = 17.0;
		f7.hasSpeedControl = false;
		f7.feature1 = "Sample7";
		f7.feature2 = "Sample7";
		f7.feature3 = "Sample7";
		f7.isPortable = false;
		f7.isEnergyEfficient = false;
		f7.rating = 107;

		System.out.println("----- FusionMixer 7 -----");
		System.out.println("productId: " + f7.productId);
		System.out.println("brandName: " + f7.brandName);
		System.out.println("mixerType: " + f7.mixerType);
		System.out.println("color: " + f7.color);
		System.out.println("capacity: " + f7.capacity);
		System.out.println("price: " + f7.price);
		System.out.println("isElectric: " + f7.isElectric);
		System.out.println("isAvailable: " + f7.isAvailable);
		System.out.println("manufacturingDate: " + f7.manufacturingDate);
		System.out.println("expiryDate: " + f7.expiryDate);
		System.out.println("bladeMaterial: " + f7.bladeMaterial);
		System.out.println("jarMaterial: " + f7.jarMaterial);
		System.out.println("power: " + f7.power);
		System.out.println("isShockProof: " + f7.isShockProof);
		System.out.println("countryOfOrigin: " + f7.countryOfOrigin);
		System.out.println("warrantyMonths: " + f7.warrantyMonths);
		System.out.println("packagingType: " + f7.packagingType);
		System.out.println("weight: " + f7.weight);
		System.out.println("hasSpeedControl: " + f7.hasSpeedControl);
		System.out.println("feature1: " + f7.feature1);
		System.out.println("feature2: " + f7.feature2);
		System.out.println("feature3: " + f7.feature3);
		System.out.println("isPortable: " + f7.isPortable);
		System.out.println("isEnergyEfficient: " + f7.isEnergyEfficient);
		System.out.println("rating: " + f7.rating);


		FusionMixer f8 = new FusionMixer();
		f8.productId = 108;
		f8.brandName = "Sample8";
		f8.mixerType = "Sample8";
		f8.color = "Sample8";
		f8.capacity = 18.0;
		f8.price = 18.0;
		f8.isElectric = true;
		f8.isAvailable = true;
		f8.manufacturingDate = "Sample8";
		f8.expiryDate = "Sample8";
		f8.bladeMaterial = "Sample8";
		f8.jarMaterial = "Sample8";
		f8.power = 18.0;
		f8.isShockProof = true;
		f8.countryOfOrigin = "Sample8";
		f8.warrantyMonths = 108;
		f8.packagingType = "Sample8";
		f8.weight = 18.0;
		f8.hasSpeedControl = true;
		f8.feature1 = "Sample8";
		f8.feature2 = "Sample8";
		f8.feature3 = "Sample8";
		f8.isPortable = true;
		f8.isEnergyEfficient = true;
		f8.rating = 108;

		System.out.println("----- FusionMixer 8 -----");
		System.out.println("productId: " + f8.productId);
		System.out.println("brandName: " + f8.brandName);
		System.out.println("mixerType: " + f8.mixerType);
		System.out.println("color: " + f8.color);
		System.out.println("capacity: " + f8.capacity);
		System.out.println("price: " + f8.price);
		System.out.println("isElectric: " + f8.isElectric);
		System.out.println("isAvailable: " + f8.isAvailable);
		System.out.println("manufacturingDate: " + f8.manufacturingDate);
		System.out.println("expiryDate: " + f8.expiryDate);
		System.out.println("bladeMaterial: " + f8.bladeMaterial);
		System.out.println("jarMaterial: " + f8.jarMaterial);
		System.out.println("power: " + f8.power);
		System.out.println("isShockProof: " + f8.isShockProof);
		System.out.println("countryOfOrigin: " + f8.countryOfOrigin);
		System.out.println("warrantyMonths: " + f8.warrantyMonths);
		System.out.println("packagingType: " + f8.packagingType);
		System.out.println("weight: " + f8.weight);
		System.out.println("hasSpeedControl: " + f8.hasSpeedControl);
		System.out.println("feature1: " + f8.feature1);
		System.out.println("feature2: " + f8.feature2);
		System.out.println("feature3: " + f8.feature3);
		System.out.println("isPortable: " + f8.isPortable);
		System.out.println("isEnergyEfficient: " + f8.isEnergyEfficient);
		System.out.println("rating: " + f8.rating);


		FusionMixer f9 = new FusionMixer();
		f9.productId = 109;
		f9.brandName = "Sample9";
		f9.mixerType = "Sample9";
		f9.color = "Sample9";
		f9.capacity = 19.0;
		f9.price = 19.0;
		f9.isElectric = false;
		f9.isAvailable = false;
		f9.manufacturingDate = "Sample9";
		f9.expiryDate = "Sample9";
		f9.bladeMaterial = "Sample9";
		f9.jarMaterial = "Sample9";
		f9.power = 19.0;
		f9.isShockProof = false;
		f9.countryOfOrigin = "Sample9";
		f9.warrantyMonths = 109;
		f9.packagingType = "Sample9";
		f9.weight = 19.0;
		f9.hasSpeedControl = false;
		f9.feature1 = "Sample9";
		f9.feature2 = "Sample9";
		f9.feature3 = "Sample9";
		f9.isPortable = false;
		f9.isEnergyEfficient = false;
		f9.rating = 109;

		System.out.println("----- FusionMixer 9 -----");
		System.out.println("productId: " + f9.productId);
		System.out.println("brandName: " + f9.brandName);
		System.out.println("mixerType: " + f9.mixerType);
		System.out.println("color: " + f9.color);
		System.out.println("capacity: " + f9.capacity);
		System.out.println("price: " + f9.price);
		System.out.println("isElectric: " + f9.isElectric);
		System.out.println("isAvailable: " + f9.isAvailable);
		System.out.println("manufacturingDate: " + f9.manufacturingDate);
		System.out.println("expiryDate: " + f9.expiryDate);
		System.out.println("bladeMaterial: " + f9.bladeMaterial);
		System.out.println("jarMaterial: " + f9.jarMaterial);
		System.out.println("power: " + f9.power);
		System.out.println("isShockProof: " + f9.isShockProof);
		System.out.println("countryOfOrigin: " + f9.countryOfOrigin);
		System.out.println("warrantyMonths: " + f9.warrantyMonths);
		System.out.println("packagingType: " + f9.packagingType);
		System.out.println("weight: " + f9.weight);
		System.out.println("hasSpeedControl: " + f9.hasSpeedControl);
		System.out.println("feature1: " + f9.feature1);
		System.out.println("feature2: " + f9.feature2);
		System.out.println("feature3: " + f9.feature3);
		System.out.println("isPortable: " + f9.isPortable);
		System.out.println("isEnergyEfficient: " + f9.isEnergyEfficient);
		System.out.println("rating: " + f9.rating);


		FusionMixer f10 = new FusionMixer();
		f10.productId = 110;
		f10.brandName = "Sample10";
		f10.mixerType = "Sample10";
		f10.color = "Sample10";
		f10.capacity = 20.0;
		f10.price = 20.0;
		f10.isElectric = true;
		f10.isAvailable = true;
		f10.manufacturingDate = "Sample10";
		f10.expiryDate = "Sample10";
		f10.bladeMaterial = "Sample10";
		f10.jarMaterial = "Sample10";
		f10.power = 20.0;
		f10.isShockProof = true;
		f10.countryOfOrigin = "Sample10";
		f10.warrantyMonths = 110;
		f10.packagingType = "Sample10";
		f10.weight = 20.0;
		f10.hasSpeedControl = true;
		f10.feature1 = "Sample10";
		f10.feature2 = "Sample10";
		f10.feature3 = "Sample10";
		f10.isPortable = true;
		f10.isEnergyEfficient = true;
		f10.rating = 110;

		System.out.println("----- FusionMixer 10 -----");
		System.out.println("productId: " + f10.productId);
		System.out.println("brandName: " + f10.brandName);
		System.out.println("mixerType: " + f10.mixerType);
		System.out.println("color: " + f10.color);
		System.out.println("capacity: " + f10.capacity);
		System.out.println("price: " + f10.price);
		System.out.println("isElectric: " + f10.isElectric);
		System.out.println("isAvailable: " + f10.isAvailable);
		System.out.println("manufacturingDate: " + f10.manufacturingDate);
		System.out.println("expiryDate: " + f10.expiryDate);
		System.out.println("bladeMaterial: " + f10.bladeMaterial);
		System.out.println("jarMaterial: " + f10.jarMaterial);
		System.out.println("power: " + f10.power);
		System.out.println("isShockProof: " + f10.isShockProof);
		System.out.println("countryOfOrigin: " + f10.countryOfOrigin);
		System.out.println("warrantyMonths: " + f10.warrantyMonths);
		System.out.println("packagingType: " + f10.packagingType);
		System.out.println("weight: " + f10.weight);
		System.out.println("hasSpeedControl: " + f10.hasSpeedControl);
		System.out.println("feature1: " + f10.feature1);
		System.out.println("feature2: " + f10.feature2);
		System.out.println("feature3: " + f10.feature3);
		System.out.println("isPortable: " + f10.isPortable);
		System.out.println("isEnergyEfficient: " + f10.isEnergyEfficient);
		System.out.println("rating: " + f10.rating);


		FusionMixer f11 = new FusionMixer();
		f11.productId = 111;
		f11.brandName = "Sample11";
		f11.mixerType = "Sample11";
		f11.color = "Sample11";
		f11.capacity = 21.0;
		f11.price = 21.0;
		f11.isElectric = false;
		f11.isAvailable = false;
		f11.manufacturingDate = "Sample11";
		f11.expiryDate = "Sample11";
		f11.bladeMaterial = "Sample11";
		f11.jarMaterial = "Sample11";
		f11.power = 21.0;
		f11.isShockProof = false;
		f11.countryOfOrigin = "Sample11";
		f11.warrantyMonths = 111;
		f11.packagingType = "Sample11";
		f11.weight = 21.0;
		f11.hasSpeedControl = false;
		f11.feature1 = "Sample11";
		f11.feature2 = "Sample11";
		f11.feature3 = "Sample11";
		f11.isPortable = false;
		f11.isEnergyEfficient = false;
		f11.rating = 111;

		System.out.println("----- FusionMixer 11 -----");
		System.out.println("productId: " + f11.productId);
		System.out.println("brandName: " + f11.brandName);
		System.out.println("mixerType: " + f11.mixerType);
		System.out.println("color: " + f11.color);
		System.out.println("capacity: " + f11.capacity);
		System.out.println("price: " + f11.price);
		System.out.println("isElectric: " + f11.isElectric);
		System.out.println("isAvailable: " + f11.isAvailable);
		System.out.println("manufacturingDate: " + f11.manufacturingDate);
		System.out.println("expiryDate: " + f11.expiryDate);
		System.out.println("bladeMaterial: " + f11.bladeMaterial);
		System.out.println("jarMaterial: " + f11.jarMaterial);
		System.out.println("power: " + f11.power);
		System.out.println("isShockProof: " + f11.isShockProof);
		System.out.println("countryOfOrigin: " + f11.countryOfOrigin);
		System.out.println("warrantyMonths: " + f11.warrantyMonths);
		System.out.println("packagingType: " + f11.packagingType);
		System.out.println("weight: " + f11.weight);
		System.out.println("hasSpeedControl: " + f11.hasSpeedControl);
		System.out.println("feature1: " + f11.feature1);
		System.out.println("feature2: " + f11.feature2);
		System.out.println("feature3: " + f11.feature3);
		System.out.println("isPortable: " + f11.isPortable);
		System.out.println("isEnergyEfficient: " + f11.isEnergyEfficient);
		System.out.println("rating: " + f11.rating);


		FusionMixer f12 = new FusionMixer();
		f12.productId = 112;
		f12.brandName = "Sample12";
		f12.mixerType = "Sample12";
		f12.color = "Sample12";
		f12.capacity = 22.0;
		f12.price = 22.0;
		f12.isElectric = true;
		f12.isAvailable = true;
		f12.manufacturingDate = "Sample12";
		f12.expiryDate = "Sample12";
		f12.bladeMaterial = "Sample12";
		f12.jarMaterial = "Sample12";
		f12.power = 22.0;
		f12.isShockProof = true;
		f12.countryOfOrigin = "Sample12";
		f12.warrantyMonths = 112;
		f12.packagingType = "Sample12";
		f12.weight = 22.0;
		f12.hasSpeedControl = true;
		f12.feature1 = "Sample12";
		f12.feature2 = "Sample12";
		f12.feature3 = "Sample12";
		f12.isPortable = true;
		f12.isEnergyEfficient = true;
		f12.rating = 112;

		System.out.println("----- FusionMixer 12 -----");
		System.out.println("productId: " + f12.productId);
		System.out.println("brandName: " + f12.brandName);
		System.out.println("mixerType: " + f12.mixerType);
		System.out.println("color: " + f12.color);
		System.out.println("capacity: " + f12.capacity);
		System.out.println("price: " + f12.price);
		System.out.println("isElectric: " + f12.isElectric);
		System.out.println("isAvailable: " + f12.isAvailable);
		System.out.println("manufacturingDate: " + f12.manufacturingDate);
		System.out.println("expiryDate: " + f12.expiryDate);
		System.out.println("bladeMaterial: " + f12.bladeMaterial);
		System.out.println("jarMaterial: " + f12.jarMaterial);
		System.out.println("power: " + f12.power);
		System.out.println("isShockProof: " + f12.isShockProof);
		System.out.println("countryOfOrigin: " + f12.countryOfOrigin);
		System.out.println("warrantyMonths: " + f12.warrantyMonths);
		System.out.println("packagingType: " + f12.packagingType);
		System.out.println("weight: " + f12.weight);
		System.out.println("hasSpeedControl: " + f12.hasSpeedControl);
		System.out.println("feature1: " + f12.feature1);
		System.out.println("feature2: " + f12.feature2);
		System.out.println("feature3: " + f12.feature3);
		System.out.println("isPortable: " + f12.isPortable);
		System.out.println("isEnergyEfficient: " + f12.isEnergyEfficient);
		System.out.println("rating: " + f12.rating);


		FusionMixer f13 = new FusionMixer();
		f13.productId = 113;
		f13.brandName = "Sample13";
		f13.mixerType = "Sample13";
		f13.color = "Sample13";
		f13.capacity = 23.0;
		f13.price = 23.0;
		f13.isElectric = false;
		f13.isAvailable = false;
		f13.manufacturingDate = "Sample13";
		f13.expiryDate = "Sample13";
		f13.bladeMaterial = "Sample13";
		f13.jarMaterial = "Sample13";
		f13.power = 23.0;
		f13.isShockProof = false;
		f13.countryOfOrigin = "Sample13";
		f13.warrantyMonths = 113;
		f13.packagingType = "Sample13";
		f13.weight = 23.0;
		f13.hasSpeedControl = false;
		f13.feature1 = "Sample13";
		f13.feature2 = "Sample13";
		f13.feature3 = "Sample13";
		f13.isPortable = false;
		f13.isEnergyEfficient = false;
		f13.rating = 113;

		System.out.println("----- FusionMixer 13 -----");
		System.out.println("productId: " + f13.productId);
		System.out.println("brandName: " + f13.brandName);
		System.out.println("mixerType: " + f13.mixerType);
		System.out.println("color: " + f13.color);
		System.out.println("capacity: " + f13.capacity);
		System.out.println("price: " + f13.price);
		System.out.println("isElectric: " + f13.isElectric);
		System.out.println("isAvailable: " + f13.isAvailable);
		System.out.println("manufacturingDate: " + f13.manufacturingDate);
		System.out.println("expiryDate: " + f13.expiryDate);
		System.out.println("bladeMaterial: " + f13.bladeMaterial);
		System.out.println("jarMaterial: " + f13.jarMaterial);
		System.out.println("power: " + f13.power);
		System.out.println("isShockProof: " + f13.isShockProof);
		System.out.println("countryOfOrigin: " + f13.countryOfOrigin);
		System.out.println("warrantyMonths: " + f13.warrantyMonths);
		System.out.println("packagingType: " + f13.packagingType);
		System.out.println("weight: " + f13.weight);
		System.out.println("hasSpeedControl: " + f13.hasSpeedControl);
		System.out.println("feature1: " + f13.feature1);
		System.out.println("feature2: " + f13.feature2);
		System.out.println("feature3: " + f13.feature3);
		System.out.println("isPortable: " + f13.isPortable);
		System.out.println("isEnergyEfficient: " + f13.isEnergyEfficient);
		System.out.println("rating: " + f13.rating);


		FusionMixer f14 = new FusionMixer();
		f14.productId = 114;
		f14.brandName = "Sample14";
		f14.mixerType = "Sample14";
		f14.color = "Sample14";
		f14.capacity = 24.0;
		f14.price = 24.0;
		f14.isElectric = true;
		f14.isAvailable = true;
		f14.manufacturingDate = "Sample14";
		f14.expiryDate = "Sample14";
		f14.bladeMaterial = "Sample14";
		f14.jarMaterial = "Sample14";
		f14.power = 24.0;
		f14.isShockProof = true;
		f14.countryOfOrigin = "Sample14";
		f14.warrantyMonths = 114;
		f14.packagingType = "Sample14";
		f14.weight = 24.0;
		f14.hasSpeedControl = true;
		f14.feature1 = "Sample14";
		f14.feature2 = "Sample14";
		f14.feature3 = "Sample14";
		f14.isPortable = true;
		f14.isEnergyEfficient = true;
		f14.rating = 114;

		System.out.println("----- FusionMixer 14 -----");
		System.out.println("productId: " + f14.productId);
		System.out.println("brandName: " + f14.brandName);
		System.out.println("mixerType: " + f14.mixerType);
		System.out.println("color: " + f14.color);
		System.out.println("capacity: " + f14.capacity);
		System.out.println("price: " + f14.price);
		System.out.println("isElectric: " + f14.isElectric);
		System.out.println("isAvailable: " + f14.isAvailable);
		System.out.println("manufacturingDate: " + f14.manufacturingDate);
		System.out.println("expiryDate: " + f14.expiryDate);
		System.out.println("bladeMaterial: " + f14.bladeMaterial);
		System.out.println("jarMaterial: " + f14.jarMaterial);
		System.out.println("power: " + f14.power);
		System.out.println("isShockProof: " + f14.isShockProof);
		System.out.println("countryOfOrigin: " + f14.countryOfOrigin);
		System.out.println("warrantyMonths: " + f14.warrantyMonths);
		System.out.println("packagingType: " + f14.packagingType);
		System.out.println("weight: " + f14.weight);
		System.out.println("hasSpeedControl: " + f14.hasSpeedControl);
		System.out.println("feature1: " + f14.feature1);
		System.out.println("feature2: " + f14.feature2);
		System.out.println("feature3: " + f14.feature3);
		System.out.println("isPortable: " + f14.isPortable);
		System.out.println("isEnergyEfficient: " + f14.isEnergyEfficient);
		System.out.println("rating: " + f14.rating);


		FusionMixer f15 = new FusionMixer();
		f15.productId = 115;
		f15.brandName = "Sample15";
		f15.mixerType = "Sample15";
		f15.color = "Sample15";
		f15.capacity = 25.0;
		f15.price = 25.0;
		f15.isElectric = false;
		f15.isAvailable = false;
		f15.manufacturingDate = "Sample15";
		f15.expiryDate = "Sample15";
		f15.bladeMaterial = "Sample15";
		f15.jarMaterial = "Sample15";
		f15.power = 25.0;
		f15.isShockProof = false;
		f15.countryOfOrigin = "Sample15";
		f15.warrantyMonths = 115;
		f15.packagingType = "Sample15";
		f15.weight = 25.0;
		f15.hasSpeedControl = false;
		f15.feature1 = "Sample15";
		f15.feature2 = "Sample15";
		f15.feature3 = "Sample15";
		f15.isPortable = false;
		f15.isEnergyEfficient = false;
		f15.rating = 115;

		System.out.println("----- FusionMixer 15 -----");
		System.out.println("productId: " + f15.productId);
		System.out.println("brandName: " + f15.brandName);
		System.out.println("mixerType: " + f15.mixerType);
		System.out.println("color: " + f15.color);
		System.out.println("capacity: " + f15.capacity);
		System.out.println("price: " + f15.price);
		System.out.println("isElectric: " + f15.isElectric);
		System.out.println("isAvailable: " + f15.isAvailable);
		System.out.println("manufacturingDate: " + f15.manufacturingDate);
		System.out.println("expiryDate: " + f15.expiryDate);
		System.out.println("bladeMaterial: " + f15.bladeMaterial);
		System.out.println("jarMaterial: " + f15.jarMaterial);
		System.out.println("power: " + f15.power);
		System.out.println("isShockProof: " + f15.isShockProof);
		System.out.println("countryOfOrigin: " + f15.countryOfOrigin);
		System.out.println("warrantyMonths: " + f15.warrantyMonths);
		System.out.println("packagingType: " + f15.packagingType);
		System.out.println("weight: " + f15.weight);
		System.out.println("hasSpeedControl: " + f15.hasSpeedControl);
		System.out.println("feature1: " + f15.feature1);
		System.out.println("feature2: " + f15.feature2);
		System.out.println("feature3: " + f15.feature3);
		System.out.println("isPortable: " + f15.isPortable);
		System.out.println("isEnergyEfficient: " + f15.isEnergyEfficient);
		System.out.println("rating: " + f15.rating);


		FusionMixer f16 = new FusionMixer();
		f16.productId = 116;
		f16.brandName = "Sample16";
		f16.mixerType = "Sample16";
		f16.color = "Sample16";
		f16.capacity = 26.0;
		f16.price = 26.0;
		f16.isElectric = true;
		f16.isAvailable = true;
		f16.manufacturingDate = "Sample16";
		f16.expiryDate = "Sample16";
		f16.bladeMaterial = "Sample16";
		f16.jarMaterial = "Sample16";
		f16.power = 26.0;
		f16.isShockProof = true;
		f16.countryOfOrigin = "Sample16";
		f16.warrantyMonths = 116;
		f16.packagingType = "Sample16";
		f16.weight = 26.0;
		f16.hasSpeedControl = true;
		f16.feature1 = "Sample16";
		f16.feature2 = "Sample16";
		f16.feature3 = "Sample16";
		f16.isPortable = true;
		f16.isEnergyEfficient = true;
		f16.rating = 116;

		System.out.println("----- FusionMixer 16 -----");
		System.out.println("productId: " + f16.productId);
		System.out.println("brandName: " + f16.brandName);
		System.out.println("mixerType: " + f16.mixerType);
		System.out.println("color: " + f16.color);
		System.out.println("capacity: " + f16.capacity);
		System.out.println("price: " + f16.price);
		System.out.println("isElectric: " + f16.isElectric);
		System.out.println("isAvailable: " + f16.isAvailable);
		System.out.println("manufacturingDate: " + f16.manufacturingDate);
		System.out.println("expiryDate: " + f16.expiryDate);
		System.out.println("bladeMaterial: " + f16.bladeMaterial);
		System.out.println("jarMaterial: " + f16.jarMaterial);
		System.out.println("power: " + f16.power);
		System.out.println("isShockProof: " + f16.isShockProof);
		System.out.println("countryOfOrigin: " + f16.countryOfOrigin);
		System.out.println("warrantyMonths: " + f16.warrantyMonths);
		System.out.println("packagingType: " + f16.packagingType);
		System.out.println("weight: " + f16.weight);
		System.out.println("hasSpeedControl: " + f16.hasSpeedControl);
		System.out.println("feature1: " + f16.feature1);
		System.out.println("feature2: " + f16.feature2);
		System.out.println("feature3: " + f16.feature3);
		System.out.println("isPortable: " + f16.isPortable);
		System.out.println("isEnergyEfficient: " + f16.isEnergyEfficient);
		System.out.println("rating: " + f16.rating);


		FusionMixer f17 = new FusionMixer();
		f17.productId = 117;
		f17.brandName = "Sample17";
		f17.mixerType = "Sample17";
		f17.color = "Sample17";
		f17.capacity = 27.0;
		f17.price = 27.0;
		f17.isElectric = false;
		f17.isAvailable = false;
		f17.manufacturingDate = "Sample17";
		f17.expiryDate = "Sample17";
		f17.bladeMaterial = "Sample17";
		f17.jarMaterial = "Sample17";
		f17.power = 27.0;
		f17.isShockProof = false;
		f17.countryOfOrigin = "Sample17";
		f17.warrantyMonths = 117;
		f17.packagingType = "Sample17";
		f17.weight = 27.0;
		f17.hasSpeedControl = false;
		f17.feature1 = "Sample17";
		f17.feature2 = "Sample17";
		f17.feature3 = "Sample17";
		f17.isPortable = false;
		f17.isEnergyEfficient = false;
		f17.rating = 117;

		System.out.println("----- FusionMixer 17 -----");
		System.out.println("productId: " + f17.productId);
		System.out.println("brandName: " + f17.brandName);
		System.out.println("mixerType: " + f17.mixerType);
		System.out.println("color: " + f17.color);
		System.out.println("capacity: " + f17.capacity);
		System.out.println("price: " + f17.price);
		System.out.println("isElectric: " + f17.isElectric);
		System.out.println("isAvailable: " + f17.isAvailable);
		System.out.println("manufacturingDate: " + f17.manufacturingDate);
		System.out.println("expiryDate: " + f17.expiryDate);
		System.out.println("bladeMaterial: " + f17.bladeMaterial);
		System.out.println("jarMaterial: " + f17.jarMaterial);
		System.out.println("power: " + f17.power);
		System.out.println("isShockProof: " + f17.isShockProof);
		System.out.println("countryOfOrigin: " + f17.countryOfOrigin);
		System.out.println("warrantyMonths: " + f17.warrantyMonths);
		System.out.println("packagingType: " + f17.packagingType);
		System.out.println("weight: " + f17.weight);
		System.out.println("hasSpeedControl: " + f17.hasSpeedControl);
		System.out.println("feature1: " + f17.feature1);
		System.out.println("feature2: " + f17.feature2);
		System.out.println("feature3: " + f17.feature3);
		System.out.println("isPortable: " + f17.isPortable);
		System.out.println("isEnergyEfficient: " + f17.isEnergyEfficient);
		System.out.println("rating: " + f17.rating);


		FusionMixer f18 = new FusionMixer();
		f18.productId = 118;
		f18.brandName = "Sample18";
		f18.mixerType = "Sample18";
		f18.color = "Sample18";
		f18.capacity = 28.0;
		f18.price = 28.0;
		f18.isElectric = true;
		f18.isAvailable = true;
		f18.manufacturingDate = "Sample18";
		f18.expiryDate = "Sample18";
		f18.bladeMaterial = "Sample18";
		f18.jarMaterial = "Sample18";
		f18.power = 28.0;
		f18.isShockProof = true;
		f18.countryOfOrigin = "Sample18";
		f18.warrantyMonths = 118;
		f18.packagingType = "Sample18";
		f18.weight = 28.0;
		f18.hasSpeedControl = true;
		f18.feature1 = "Sample18";
		f18.feature2 = "Sample18";
		f18.feature3 = "Sample18";
		f18.isPortable = true;
		f18.isEnergyEfficient = true;
		f18.rating = 118;

		System.out.println("----- FusionMixer 18 -----");
		System.out.println("productId: " + f18.productId);
		System.out.println("brandName: " + f18.brandName);
		System.out.println("mixerType: " + f18.mixerType);
		System.out.println("color: " + f18.color);
		System.out.println("capacity: " + f18.capacity);
		System.out.println("price: " + f18.price);
		System.out.println("isElectric: " + f18.isElectric);
		System.out.println("isAvailable: " + f18.isAvailable);
		System.out.println("manufacturingDate: " + f18.manufacturingDate);
		System.out.println("expiryDate: " + f18.expiryDate);
		System.out.println("bladeMaterial: " + f18.bladeMaterial);
		System.out.println("jarMaterial: " + f18.jarMaterial);
		System.out.println("power: " + f18.power);
		System.out.println("isShockProof: " + f18.isShockProof);
		System.out.println("countryOfOrigin: " + f18.countryOfOrigin);
		System.out.println("warrantyMonths: " + f18.warrantyMonths);
		System.out.println("packagingType: " + f18.packagingType);
		System.out.println("weight: " + f18.weight);
		System.out.println("hasSpeedControl: " + f18.hasSpeedControl);
		System.out.println("feature1: " + f18.feature1);
		System.out.println("feature2: " + f18.feature2);
		System.out.println("feature3: " + f18.feature3);
		System.out.println("isPortable: " + f18.isPortable);
		System.out.println("isEnergyEfficient: " + f18.isEnergyEfficient);
		System.out.println("rating: " + f18.rating);


		FusionMixer f19 = new FusionMixer();
		f19.productId = 119;
		f19.brandName = "Sample19";
		f19.mixerType = "Sample19";
		f19.color = "Sample19";
		f19.capacity = 29.0;
		f19.price = 29.0;
		f19.isElectric = false;
		f19.isAvailable = false;
		f19.manufacturingDate = "Sample19";
		f19.expiryDate = "Sample19";
		f19.bladeMaterial = "Sample19";
		f19.jarMaterial = "Sample19";
		f19.power = 29.0;
		f19.isShockProof = false;
		f19.countryOfOrigin = "Sample19";
		f19.warrantyMonths = 119;
		f19.packagingType = "Sample19";
		f19.weight = 29.0;
		f19.hasSpeedControl = false;
		f19.feature1 = "Sample19";
		f19.feature2 = "Sample19";
		f19.feature3 = "Sample19";
		f19.isPortable = false;
		f19.isEnergyEfficient = false;
		f19.rating = 119;

		System.out.println("----- FusionMixer 19 -----");
		System.out.println("productId: " + f19.productId);
		System.out.println("brandName: " + f19.brandName);
		System.out.println("mixerType: " + f19.mixerType);
		System.out.println("color: " + f19.color);
		System.out.println("capacity: " + f19.capacity);
		System.out.println("price: " + f19.price);
		System.out.println("isElectric: " + f19.isElectric);
		System.out.println("isAvailable: " + f19.isAvailable);
		System.out.println("manufacturingDate: " + f19.manufacturingDate);
		System.out.println("expiryDate: " + f19.expiryDate);
		System.out.println("bladeMaterial: " + f19.bladeMaterial);
		System.out.println("jarMaterial: " + f19.jarMaterial);
		System.out.println("power: " + f19.power);
		System.out.println("isShockProof: " + f19.isShockProof);
		System.out.println("countryOfOrigin: " + f19.countryOfOrigin);
		System.out.println("warrantyMonths: " + f19.warrantyMonths);
		System.out.println("packagingType: " + f19.packagingType);
		System.out.println("weight: " + f19.weight);
		System.out.println("hasSpeedControl: " + f19.hasSpeedControl);
		System.out.println("feature1: " + f19.feature1);
		System.out.println("feature2: " + f19.feature2);
		System.out.println("feature3: " + f19.feature3);
		System.out.println("isPortable: " + f19.isPortable);
		System.out.println("isEnergyEfficient: " + f19.isEnergyEfficient);
		System.out.println("rating: " + f19.rating);


		FusionMixer f20 = new FusionMixer();
		f20.productId = 120;
		f20.brandName = "Sample20";
		f20.mixerType = "Sample20";
		f20.color = "Sample20";
		f20.capacity = 30.0;
		f20.price = 30.0;
		f20.isElectric = true;
		f20.isAvailable = true;
		f20.manufacturingDate = "Sample20";
		f20.expiryDate = "Sample20";
		f20.bladeMaterial = "Sample20";
		f20.jarMaterial = "Sample20";
		f20.power = 30.0;
		f20.isShockProof = true;
		f20.countryOfOrigin = "Sample20";
		f20.warrantyMonths = 120;
		f20.packagingType = "Sample20";
		f20.weight = 30.0;
		f20.hasSpeedControl = true;
		f20.feature1 = "Sample20";
		f20.feature2 = "Sample20";
		f20.feature3 = "Sample20";
		f20.isPortable = true;
		f20.isEnergyEfficient = true;
		f20.rating = 120;

		System.out.println("----- FusionMixer 20 -----");
		System.out.println("productId: " + f20.productId);
		System.out.println("brandName: " + f20.brandName);
		System.out.println("mixerType: " + f20.mixerType);
		System.out.println("color: " + f20.color);
		System.out.println("capacity: " + f20.capacity);
		System.out.println("price: " + f20.price);
		System.out.println("isElectric: " + f20.isElectric);
		System.out.println("isAvailable: " + f20.isAvailable);
		System.out.println("manufacturingDate: " + f20.manufacturingDate);
		System.out.println("expiryDate: " + f20.expiryDate);
		System.out.println("bladeMaterial: " + f20.bladeMaterial);
		System.out.println("jarMaterial: " + f20.jarMaterial);
		System.out.println("power: " + f20.power);
		System.out.println("isShockProof: " + f20.isShockProof);
		System.out.println("countryOfOrigin: " + f20.countryOfOrigin);
		System.out.println("warrantyMonths: " + f20.warrantyMonths);
		System.out.println("packagingType: " + f20.packagingType);
		System.out.println("weight: " + f20.weight);
		System.out.println("hasSpeedControl: " + f20.hasSpeedControl);
		System.out.println("feature1: " + f20.feature1);
		System.out.println("feature2: " + f20.feature2);
		System.out.println("feature3: " + f20.feature3);
		System.out.println("isPortable: " + f20.isPortable);
		System.out.println("isEnergyEfficient: " + f20.isEnergyEfficient);
		System.out.println("rating: " + f20.rating);


		FusionMixer f21 = new FusionMixer();
		f21.productId = 121;
		f21.brandName = "Sample21";
		f21.mixerType = "Sample21";
		f21.color = "Sample21";
		f21.capacity = 31.0;
		f21.price = 31.0;
		f21.isElectric = false;
		f21.isAvailable = false;
		f21.manufacturingDate = "Sample21";
		f21.expiryDate = "Sample21";
		f21.bladeMaterial = "Sample21";
		f21.jarMaterial = "Sample21";
		f21.power = 31.0;
		f21.isShockProof = false;
		f21.countryOfOrigin = "Sample21";
		f21.warrantyMonths = 121;
		f21.packagingType = "Sample21";
		f21.weight = 31.0;
		f21.hasSpeedControl = false;
		f21.feature1 = "Sample21";
		f21.feature2 = "Sample21";
		f21.feature3 = "Sample21";
		f21.isPortable = false;
		f21.isEnergyEfficient = false;
		f21.rating = 121;

		System.out.println("----- FusionMixer 21 -----");
		System.out.println("productId: " + f21.productId);
		System.out.println("brandName: " + f21.brandName);
		System.out.println("mixerType: " + f21.mixerType);
		System.out.println("color: " + f21.color);
		System.out.println("capacity: " + f21.capacity);
		System.out.println("price: " + f21.price);
		System.out.println("isElectric: " + f21.isElectric);
		System.out.println("isAvailable: " + f21.isAvailable);
		System.out.println("manufacturingDate: " + f21.manufacturingDate);
		System.out.println("expiryDate: " + f21.expiryDate);
		System.out.println("bladeMaterial: " + f21.bladeMaterial);
		System.out.println("jarMaterial: " + f21.jarMaterial);
		System.out.println("power: " + f21.power);
		System.out.println("isShockProof: " + f21.isShockProof);
		System.out.println("countryOfOrigin: " + f21.countryOfOrigin);
		System.out.println("warrantyMonths: " + f21.warrantyMonths);
		System.out.println("packagingType: " + f21.packagingType);
		System.out.println("weight: " + f21.weight);
		System.out.println("hasSpeedControl: " + f21.hasSpeedControl);
		System.out.println("feature1: " + f21.feature1);
		System.out.println("feature2: " + f21.feature2);
		System.out.println("feature3: " + f21.feature3);
		System.out.println("isPortable: " + f21.isPortable);
		System.out.println("isEnergyEfficient: " + f21.isEnergyEfficient);
		System.out.println("rating: " + f21.rating);


		FusionMixer f22 = new FusionMixer();
		f22.productId = 122;
		f22.brandName = "Sample22";
		f22.mixerType = "Sample22";
		f22.color = "Sample22";
		f22.capacity = 32.0;
		f22.price = 32.0;
		f22.isElectric = true;
		f22.isAvailable = true;
		f22.manufacturingDate = "Sample22";
		f22.expiryDate = "Sample22";
		f22.bladeMaterial = "Sample22";
		f22.jarMaterial = "Sample22";
		f22.power = 32.0;
		f22.isShockProof = true;
		f22.countryOfOrigin = "Sample22";
		f22.warrantyMonths = 122;
		f22.packagingType = "Sample22";
		f22.weight = 32.0;
		f22.hasSpeedControl = true;
		f22.feature1 = "Sample22";
		f22.feature2 = "Sample22";
		f22.feature3 = "Sample22";
		f22.isPortable = true;
		f22.isEnergyEfficient = true;
		f22.rating = 122;

		System.out.println("----- FusionMixer 22 -----");
		System.out.println("productId: " + f22.productId);
		System.out.println("brandName: " + f22.brandName);
		System.out.println("mixerType: " + f22.mixerType);
		System.out.println("color: " + f22.color);
		System.out.println("capacity: " + f22.capacity);
		System.out.println("price: " + f22.price);
		System.out.println("isElectric: " + f22.isElectric);
		System.out.println("isAvailable: " + f22.isAvailable);
		System.out.println("manufacturingDate: " + f22.manufacturingDate);
		System.out.println("expiryDate: " + f22.expiryDate);
		System.out.println("bladeMaterial: " + f22.bladeMaterial);
		System.out.println("jarMaterial: " + f22.jarMaterial);
		System.out.println("power: " + f22.power);
		System.out.println("isShockProof: " + f22.isShockProof);
		System.out.println("countryOfOrigin: " + f22.countryOfOrigin);
		System.out.println("warrantyMonths: " + f22.warrantyMonths);
		System.out.println("packagingType: " + f22.packagingType);
		System.out.println("weight: " + f22.weight);
		System.out.println("hasSpeedControl: " + f22.hasSpeedControl);
		System.out.println("feature1: " + f22.feature1);
		System.out.println("feature2: " + f22.feature2);
		System.out.println("feature3: " + f22.feature3);
		System.out.println("isPortable: " + f22.isPortable);
		System.out.println("isEnergyEfficient: " + f22.isEnergyEfficient);
		System.out.println("rating: " + f22.rating);


		FusionMixer f23 = new FusionMixer();
		f23.productId = 123;
		f23.brandName = "Sample23";
		f23.mixerType = "Sample23";
		f23.color = "Sample23";
		f23.capacity = 33.0;
		f23.price = 33.0;
		f23.isElectric = false;
		f23.isAvailable = false;
		f23.manufacturingDate = "Sample23";
		f23.expiryDate = "Sample23";
		f23.bladeMaterial = "Sample23";
		f23.jarMaterial = "Sample23";
		f23.power = 33.0;
		f23.isShockProof = false;
		f23.countryOfOrigin = "Sample23";
		f23.warrantyMonths = 123;
		f23.packagingType = "Sample23";
		f23.weight = 33.0;
		f23.hasSpeedControl = false;
		f23.feature1 = "Sample23";
		f23.feature2 = "Sample23";
		f23.feature3 = "Sample23";
		f23.isPortable = false;
		f23.isEnergyEfficient = false;
		f23.rating = 123;

		System.out.println("----- FusionMixer 23 -----");
		System.out.println("productId: " + f23.productId);
		System.out.println("brandName: " + f23.brandName);
		System.out.println("mixerType: " + f23.mixerType);
		System.out.println("color: " + f23.color);
		System.out.println("capacity: " + f23.capacity);
		System.out.println("price: " + f23.price);
		System.out.println("isElectric: " + f23.isElectric);
		System.out.println("isAvailable: " + f23.isAvailable);
		System.out.println("manufacturingDate: " + f23.manufacturingDate);
		System.out.println("expiryDate: " + f23.expiryDate);
		System.out.println("bladeMaterial: " + f23.bladeMaterial);
		System.out.println("jarMaterial: " + f23.jarMaterial);
		System.out.println("power: " + f23.power);
		System.out.println("isShockProof: " + f23.isShockProof);
		System.out.println("countryOfOrigin: " + f23.countryOfOrigin);
		System.out.println("warrantyMonths: " + f23.warrantyMonths);
		System.out.println("packagingType: " + f23.packagingType);
		System.out.println("weight: " + f23.weight);
		System.out.println("hasSpeedControl: " + f23.hasSpeedControl);
		System.out.println("feature1: " + f23.feature1);
		System.out.println("feature2: " + f23.feature2);
		System.out.println("feature3: " + f23.feature3);
		System.out.println("isPortable: " + f23.isPortable);
		System.out.println("isEnergyEfficient: " + f23.isEnergyEfficient);
		System.out.println("rating: " + f23.rating);


		FusionMixer f24 = new FusionMixer();
		f24.productId = 124;
		f24.brandName = "Sample24";
		f24.mixerType = "Sample24";
		f24.color = "Sample24";
		f24.capacity = 34.0;
		f24.price = 34.0;
		f24.isElectric = true;
		f24.isAvailable = true;
		f24.manufacturingDate = "Sample24";
		f24.expiryDate = "Sample24";
		f24.bladeMaterial = "Sample24";
		f24.jarMaterial = "Sample24";
		f24.power = 34.0;
		f24.isShockProof = true;
		f24.countryOfOrigin = "Sample24";
		f24.warrantyMonths = 124;
		f24.packagingType = "Sample24";
		f24.weight = 34.0;
		f24.hasSpeedControl = true;
		f24.feature1 = "Sample24";
		f24.feature2 = "Sample24";
		f24.feature3 = "Sample24";
		f24.isPortable = true;
		f24.isEnergyEfficient = true;
		f24.rating = 124;

		System.out.println("----- FusionMixer 24 -----");
		System.out.println("productId: " + f24.productId);
		System.out.println("brandName: " + f24.brandName);
		System.out.println("mixerType: " + f24.mixerType);
		System.out.println("color: " + f24.color);
		System.out.println("capacity: " + f24.capacity);
		System.out.println("price: " + f24.price);
		System.out.println("isElectric: " + f24.isElectric);
		System.out.println("isAvailable: " + f24.isAvailable);
		System.out.println("manufacturingDate: " + f24.manufacturingDate);
		System.out.println("expiryDate: " + f24.expiryDate);
		System.out.println("bladeMaterial: " + f24.bladeMaterial);
		System.out.println("jarMaterial: " + f24.jarMaterial);
		System.out.println("power: " + f24.power);
		System.out.println("isShockProof: " + f24.isShockProof);
		System.out.println("countryOfOrigin: " + f24.countryOfOrigin);
		System.out.println("warrantyMonths: " + f24.warrantyMonths);
		System.out.println("packagingType: " + f24.packagingType);
		System.out.println("weight: " + f24.weight);
		System.out.println("hasSpeedControl: " + f24.hasSpeedControl);
		System.out.println("feature1: " + f24.feature1);
		System.out.println("feature2: " + f24.feature2);
		System.out.println("feature3: " + f24.feature3);
		System.out.println("isPortable: " + f24.isPortable);
		System.out.println("isEnergyEfficient: " + f24.isEnergyEfficient);
		System.out.println("rating: " + f24.rating);


		FusionMixer f25 = new FusionMixer();
		f25.productId = 125;
		f25.brandName = "Sample25";
		f25.mixerType = "Sample25";
		f25.color = "Sample25";
		f25.capacity = 35.0;
		f25.price = 35.0;
		f25.isElectric = false;
		f25.isAvailable = false;
		f25.manufacturingDate = "Sample25";
		f25.expiryDate = "Sample25";
		f25.bladeMaterial = "Sample25";
		f25.jarMaterial = "Sample25";
		f25.power = 35.0;
		f25.isShockProof = false;
		f25.countryOfOrigin = "Sample25";
		f25.warrantyMonths = 125;
		f25.packagingType = "Sample25";
		f25.weight = 35.0;
		f25.hasSpeedControl = false;
		f25.feature1 = "Sample25";
		f25.feature2 = "Sample25";
		f25.feature3 = "Sample25";
		f25.isPortable = false;
		f25.isEnergyEfficient = false;
		f25.rating = 125;

		System.out.println("----- FusionMixer 25 -----");
		System.out.println("productId: " + f25.productId);
		System.out.println("brandName: " + f25.brandName);
		System.out.println("mixerType: " + f25.mixerType);
		System.out.println("color: " + f25.color);
		System.out.println("capacity: " + f25.capacity);
		System.out.println("price: " + f25.price);
		System.out.println("isElectric: " + f25.isElectric);
		System.out.println("isAvailable: " + f25.isAvailable);
		System.out.println("manufacturingDate: " + f25.manufacturingDate);
		System.out.println("expiryDate: " + f25.expiryDate);
		System.out.println("bladeMaterial: " + f25.bladeMaterial);
		System.out.println("jarMaterial: " + f25.jarMaterial);
		System.out.println("power: " + f25.power);
		System.out.println("isShockProof: " + f25.isShockProof);
		System.out.println("countryOfOrigin: " + f25.countryOfOrigin);
		System.out.println("warrantyMonths: " + f25.warrantyMonths);
		System.out.println("packagingType: " + f25.packagingType);
		System.out.println("weight: " + f25.weight);
		System.out.println("hasSpeedControl: " + f25.hasSpeedControl);
		System.out.println("feature1: " + f25.feature1);
		System.out.println("feature2: " + f25.feature2);
		System.out.println("feature3: " + f25.feature3);
		System.out.println("isPortable: " + f25.isPortable);
		System.out.println("isEnergyEfficient: " + f25.isEnergyEfficient);
		System.out.println("rating: " + f25.rating);


	}
}
