class GiriasExecutor {
	public static void main(String[] args) {
		boolean isValidate;

		isValidate = Girias.createProduct("Samsung", "Refrigerator", 75000.0, 12, true, "RF28R", 580.0, "5 Star", true, "Silver");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Sony", "Television", 120000.0, 24, false, "X90L", 55.0, "4 Star", true, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("LG", "Washing Machine", 35000.0, 36, true, "THINQ7", 8.0, "5 Star", true, "Grey");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Daikin", "Air Conditioner", 45000.0, 12, true, "FTKF50", 1.5, "5 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Whirlpool", "Microwave", 15000.0, 12, false, "MAGICOOK", 25.0, "3 Star", false, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Bosch", "Dishwasher", 52000.0, 24, true, "SMS66", 14.0, "4 Star", true, "Silver");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Dell", "Laptop", 65000.0, 12, false, "INSP15", 15.6, "N/A", true, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Prestige", "Gas Stove", 8000.0, 24, true, "GT03", 3.0, "N/A", false, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Usha", "Ceiling Fan", 3500.0, 12, false, "BLOOM", 1200.0, "5 Star", false, "Brown");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Kent", "Water Purifier", 18000.0, 12, true, "GRAND", 8.0, "N/A", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Philips", "Air Fryer", 9000.0, 24, false, "HD9200", 4.1, "N/A", false, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct(null, "Heater", 4000.0, 12, true, "H102", 2000.0, "2 Star", false, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("", "Iron", 1500.0, 6, false, "NI10", 0.0, "N/A", false, "Blue");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("HP", null, 55000.0, 12, true, "VIC16", 16.1, "N/A", true, "Silver");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Acer", "", 48000.0, 12, false, "ASP5", 15.0, "N/A", true, "Grey");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Godrej", "Fridge", 0.0, 12, true, "RD190", 190.0, "3 Star", true, "Blue");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Haier", "Cooler", 12000.0, 0, false, "HLC", 50.0, "2 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Symphony", "Air Cooler", 9000.0, 12, true, null, 70.0, "3 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Bajaj", "Mixer", 5000.0, 24, false, "", 750.0, "N/A", false, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Voltas", "AC", 38000.0, 12, true, "183V", 0.0, "3 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("OnePlus", "TV", 42000.0, 12, false, "55U1", 55.0, null, true, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Mi", "Powerbank", 2000.0, 6, true, "PB3", 20000.0, "", false, "Blue");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Realme", "Tablet", 15000.0, 12, false, "PADX", 11.0, "N/A", true, null);
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Apple", "iPad", 45000.0, 12, true, "AIR5", 10.9, "N/A", true, "");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Blue Star", "Deep Freezer", 22000.0, 12, false, "CHF200", 200.0, "2 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Lloyd", "Washing Machine", 28000.0, 24, true, "LW70", 7.0, "5 Star", true, "Dark Grey");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Havells", "Geyser", 11000.0, 60, false, "MONZA", 15.0, "5 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Carrier", "Split AC", 55000.0, 12, true, "ESTER", 2.0, "4 Star", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Sunflame", "Chimney", 13000.0, 24, false, "CH70", 1100.0, "N/A", true, "Steel");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Faber", "Hob", 16000.0, 12, true, "HT65", 3.0, "N/A", false, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Lenovo", "Monitor", 12000.0, 36, false, "L24I", 24.0, "N/A", true, "Grey");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Logitech", "Mouse", 800.0, 12, true, "M220", 0.01, "N/A", false, "Red");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Boat", "Speaker", 3000.0, 12, false, "STONE", 10.0, "N/A", false, "Green");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("JBL", "Earbuds", 4500.0, 12, true, "TWS225", 0.05, "N/A", false, "Gold");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Canon", "Printer", 14000.0, 12, false, "G3010", 1.0, "N/A", true, "Black");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Epson", "Projector", 48000.0, 24, true, "EB53", 3000.0, "N/A", true, "White");
		Girias.getProductDetails();
		isValidate = Girias.createProduct("Panasonic", "Trimmer", 2500.0, 12, false, "ER207", 0.5, "N/A", false, "Black");
		Girias.getProductDetails();
	}
}