class GlacierFanRunner {
	public static void main(String[] args) {

		GlacierFan g1 = new GlacierFan();
		g1.productId = 101;
		g1.brandName = "Sample1";
		g1.fanType = "Sample1";
		g1.color = "Sample1";
		g1.power = 11.0;
		g1.price = 11.0;
		g1.isRemoteControlled = false;
		g1.isAvailable = false;
		g1.manufacturingDate = "Sample1";
		g1.expiryDate = "Sample1";
		g1.bladeMaterial = "Sample1";
		g1.bodyMaterial = "Sample1";
		g1.speedLevels = 11.0;
		g1.isEnergyEfficient = false;
		g1.countryOfOrigin = "Sample1";
		g1.warrantyMonths = 101;
		g1.packagingType = "Sample1";
		g1.weight = 11.0;
		g1.isNoiseFree = false;
		g1.feature1 = "Sample1";
		g1.feature2 = "Sample1";
		g1.feature3 = "Sample1";
		g1.hasTimer = false;
		g1.isPortable = false;
		g1.rating = 101;

		System.out.println("----- GlacierFan 1 -----");
		System.out.println("productId: " + g1.productId);
		System.out.println("brandName: " + g1.brandName);
		System.out.println("fanType: " + g1.fanType);
		System.out.println("color: " + g1.color);
		System.out.println("power: " + g1.power);
		System.out.println("price: " + g1.price);
		System.out.println("isRemoteControlled: " + g1.isRemoteControlled);
		System.out.println("isAvailable: " + g1.isAvailable);
		System.out.println("manufacturingDate: " + g1.manufacturingDate);
		System.out.println("expiryDate: " + g1.expiryDate);
		System.out.println("bladeMaterial: " + g1.bladeMaterial);
		System.out.println("bodyMaterial: " + g1.bodyMaterial);
		System.out.println("speedLevels: " + g1.speedLevels);
		System.out.println("isEnergyEfficient: " + g1.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g1.countryOfOrigin);
		System.out.println("warrantyMonths: " + g1.warrantyMonths);
		System.out.println("packagingType: " + g1.packagingType);
		System.out.println("weight: " + g1.weight);
		System.out.println("isNoiseFree: " + g1.isNoiseFree);
		System.out.println("feature1: " + g1.feature1);
		System.out.println("feature2: " + g1.feature2);
		System.out.println("feature3: " + g1.feature3);
		System.out.println("hasTimer: " + g1.hasTimer);
		System.out.println("isPortable: " + g1.isPortable);
		System.out.println("rating: " + g1.rating);


		GlacierFan g2 = new GlacierFan();
		g2.productId = 102;
		g2.brandName = "Sample2";
		g2.fanType = "Sample2";
		g2.color = "Sample2";
		g2.power = 12.0;
		g2.price = 12.0;
		g2.isRemoteControlled = true;
		g2.isAvailable = true;
		g2.manufacturingDate = "Sample2";
		g2.expiryDate = "Sample2";
		g2.bladeMaterial = "Sample2";
		g2.bodyMaterial = "Sample2";
		g2.speedLevels = 12.0;
		g2.isEnergyEfficient = true;
		g2.countryOfOrigin = "Sample2";
		g2.warrantyMonths = 102;
		g2.packagingType = "Sample2";
		g2.weight = 12.0;
		g2.isNoiseFree = true;
		g2.feature1 = "Sample2";
		g2.feature2 = "Sample2";
		g2.feature3 = "Sample2";
		g2.hasTimer = true;
		g2.isPortable = true;
		g2.rating = 102;

		System.out.println("----- GlacierFan 2 -----");
		System.out.println("productId: " + g2.productId);
		System.out.println("brandName: " + g2.brandName);
		System.out.println("fanType: " + g2.fanType);
		System.out.println("color: " + g2.color);
		System.out.println("power: " + g2.power);
		System.out.println("price: " + g2.price);
		System.out.println("isRemoteControlled: " + g2.isRemoteControlled);
		System.out.println("isAvailable: " + g2.isAvailable);
		System.out.println("manufacturingDate: " + g2.manufacturingDate);
		System.out.println("expiryDate: " + g2.expiryDate);
		System.out.println("bladeMaterial: " + g2.bladeMaterial);
		System.out.println("bodyMaterial: " + g2.bodyMaterial);
		System.out.println("speedLevels: " + g2.speedLevels);
		System.out.println("isEnergyEfficient: " + g2.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g2.countryOfOrigin);
		System.out.println("warrantyMonths: " + g2.warrantyMonths);
		System.out.println("packagingType: " + g2.packagingType);
		System.out.println("weight: " + g2.weight);
		System.out.println("isNoiseFree: " + g2.isNoiseFree);
		System.out.println("feature1: " + g2.feature1);
		System.out.println("feature2: " + g2.feature2);
		System.out.println("feature3: " + g2.feature3);
		System.out.println("hasTimer: " + g2.hasTimer);
		System.out.println("isPortable: " + g2.isPortable);
		System.out.println("rating: " + g2.rating);


		GlacierFan g3 = new GlacierFan();
		g3.productId = 103;
		g3.brandName = "Sample3";
		g3.fanType = "Sample3";
		g3.color = "Sample3";
		g3.power = 13.0;
		g3.price = 13.0;
		g3.isRemoteControlled = false;
		g3.isAvailable = false;
		g3.manufacturingDate = "Sample3";
		g3.expiryDate = "Sample3";
		g3.bladeMaterial = "Sample3";
		g3.bodyMaterial = "Sample3";
		g3.speedLevels = 13.0;
		g3.isEnergyEfficient = false;
		g3.countryOfOrigin = "Sample3";
		g3.warrantyMonths = 103;
		g3.packagingType = "Sample3";
		g3.weight = 13.0;
		g3.isNoiseFree = false;
		g3.feature1 = "Sample3";
		g3.feature2 = "Sample3";
		g3.feature3 = "Sample3";
		g3.hasTimer = false;
		g3.isPortable = false;
		g3.rating = 103;

		System.out.println("----- GlacierFan 3 -----");
		System.out.println("productId: " + g3.productId);
		System.out.println("brandName: " + g3.brandName);
		System.out.println("fanType: " + g3.fanType);
		System.out.println("color: " + g3.color);
		System.out.println("power: " + g3.power);
		System.out.println("price: " + g3.price);
		System.out.println("isRemoteControlled: " + g3.isRemoteControlled);
		System.out.println("isAvailable: " + g3.isAvailable);
		System.out.println("manufacturingDate: " + g3.manufacturingDate);
		System.out.println("expiryDate: " + g3.expiryDate);
		System.out.println("bladeMaterial: " + g3.bladeMaterial);
		System.out.println("bodyMaterial: " + g3.bodyMaterial);
		System.out.println("speedLevels: " + g3.speedLevels);
		System.out.println("isEnergyEfficient: " + g3.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g3.countryOfOrigin);
		System.out.println("warrantyMonths: " + g3.warrantyMonths);
		System.out.println("packagingType: " + g3.packagingType);
		System.out.println("weight: " + g3.weight);
		System.out.println("isNoiseFree: " + g3.isNoiseFree);
		System.out.println("feature1: " + g3.feature1);
		System.out.println("feature2: " + g3.feature2);
		System.out.println("feature3: " + g3.feature3);
		System.out.println("hasTimer: " + g3.hasTimer);
		System.out.println("isPortable: " + g3.isPortable);
		System.out.println("rating: " + g3.rating);


		GlacierFan g4 = new GlacierFan();
		g4.productId = 104;
		g4.brandName = "Sample4";
		g4.fanType = "Sample4";
		g4.color = "Sample4";
		g4.power = 14.0;
		g4.price = 14.0;
		g4.isRemoteControlled = true;
		g4.isAvailable = true;
		g4.manufacturingDate = "Sample4";
		g4.expiryDate = "Sample4";
		g4.bladeMaterial = "Sample4";
		g4.bodyMaterial = "Sample4";
		g4.speedLevels = 14.0;
		g4.isEnergyEfficient = true;
		g4.countryOfOrigin = "Sample4";
		g4.warrantyMonths = 104;
		g4.packagingType = "Sample4";
		g4.weight = 14.0;
		g4.isNoiseFree = true;
		g4.feature1 = "Sample4";
		g4.feature2 = "Sample4";
		g4.feature3 = "Sample4";
		g4.hasTimer = true;
		g4.isPortable = true;
		g4.rating = 104;

		System.out.println("----- GlacierFan 4 -----");
		System.out.println("productId: " + g4.productId);
		System.out.println("brandName: " + g4.brandName);
		System.out.println("fanType: " + g4.fanType);
		System.out.println("color: " + g4.color);
		System.out.println("power: " + g4.power);
		System.out.println("price: " + g4.price);
		System.out.println("isRemoteControlled: " + g4.isRemoteControlled);
		System.out.println("isAvailable: " + g4.isAvailable);
		System.out.println("manufacturingDate: " + g4.manufacturingDate);
		System.out.println("expiryDate: " + g4.expiryDate);
		System.out.println("bladeMaterial: " + g4.bladeMaterial);
		System.out.println("bodyMaterial: " + g4.bodyMaterial);
		System.out.println("speedLevels: " + g4.speedLevels);
		System.out.println("isEnergyEfficient: " + g4.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g4.countryOfOrigin);
		System.out.println("warrantyMonths: " + g4.warrantyMonths);
		System.out.println("packagingType: " + g4.packagingType);
		System.out.println("weight: " + g4.weight);
		System.out.println("isNoiseFree: " + g4.isNoiseFree);
		System.out.println("feature1: " + g4.feature1);
		System.out.println("feature2: " + g4.feature2);
		System.out.println("feature3: " + g4.feature3);
		System.out.println("hasTimer: " + g4.hasTimer);
		System.out.println("isPortable: " + g4.isPortable);
		System.out.println("rating: " + g4.rating);


		GlacierFan g5 = new GlacierFan();
		g5.productId = 105;
		g5.brandName = "Sample5";
		g5.fanType = "Sample5";
		g5.color = "Sample5";
		g5.power = 15.0;
		g5.price = 15.0;
		g5.isRemoteControlled = false;
		g5.isAvailable = false;
		g5.manufacturingDate = "Sample5";
		g5.expiryDate = "Sample5";
		g5.bladeMaterial = "Sample5";
		g5.bodyMaterial = "Sample5";
		g5.speedLevels = 15.0;
		g5.isEnergyEfficient = false;
		g5.countryOfOrigin = "Sample5";
		g5.warrantyMonths = 105;
		g5.packagingType = "Sample5";
		g5.weight = 15.0;
		g5.isNoiseFree = false;
		g5.feature1 = "Sample5";
		g5.feature2 = "Sample5";
		g5.feature3 = "Sample5";
		g5.hasTimer = false;
		g5.isPortable = false;
		g5.rating = 105;

		System.out.println("----- GlacierFan 5 -----");
		System.out.println("productId: " + g5.productId);
		System.out.println("brandName: " + g5.brandName);
		System.out.println("fanType: " + g5.fanType);
		System.out.println("color: " + g5.color);
		System.out.println("power: " + g5.power);
		System.out.println("price: " + g5.price);
		System.out.println("isRemoteControlled: " + g5.isRemoteControlled);
		System.out.println("isAvailable: " + g5.isAvailable);
		System.out.println("manufacturingDate: " + g5.manufacturingDate);
		System.out.println("expiryDate: " + g5.expiryDate);
		System.out.println("bladeMaterial: " + g5.bladeMaterial);
		System.out.println("bodyMaterial: " + g5.bodyMaterial);
		System.out.println("speedLevels: " + g5.speedLevels);
		System.out.println("isEnergyEfficient: " + g5.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g5.countryOfOrigin);
		System.out.println("warrantyMonths: " + g5.warrantyMonths);
		System.out.println("packagingType: " + g5.packagingType);
		System.out.println("weight: " + g5.weight);
		System.out.println("isNoiseFree: " + g5.isNoiseFree);
		System.out.println("feature1: " + g5.feature1);
		System.out.println("feature2: " + g5.feature2);
		System.out.println("feature3: " + g5.feature3);
		System.out.println("hasTimer: " + g5.hasTimer);
		System.out.println("isPortable: " + g5.isPortable);
		System.out.println("rating: " + g5.rating);


		GlacierFan g6 = new GlacierFan();
		g6.productId = 106;
		g6.brandName = "Sample6";
		g6.fanType = "Sample6";
		g6.color = "Sample6";
		g6.power = 16.0;
		g6.price = 16.0;
		g6.isRemoteControlled = true;
		g6.isAvailable = true;
		g6.manufacturingDate = "Sample6";
		g6.expiryDate = "Sample6";
		g6.bladeMaterial = "Sample6";
		g6.bodyMaterial = "Sample6";
		g6.speedLevels = 16.0;
		g6.isEnergyEfficient = true;
		g6.countryOfOrigin = "Sample6";
		g6.warrantyMonths = 106;
		g6.packagingType = "Sample6";
		g6.weight = 16.0;
		g6.isNoiseFree = true;
		g6.feature1 = "Sample6";
		g6.feature2 = "Sample6";
		g6.feature3 = "Sample6";
		g6.hasTimer = true;
		g6.isPortable = true;
		g6.rating = 106;

		System.out.println("----- GlacierFan 6 -----");
		System.out.println("productId: " + g6.productId);
		System.out.println("brandName: " + g6.brandName);
		System.out.println("fanType: " + g6.fanType);
		System.out.println("color: " + g6.color);
		System.out.println("power: " + g6.power);
		System.out.println("price: " + g6.price);
		System.out.println("isRemoteControlled: " + g6.isRemoteControlled);
		System.out.println("isAvailable: " + g6.isAvailable);
		System.out.println("manufacturingDate: " + g6.manufacturingDate);
		System.out.println("expiryDate: " + g6.expiryDate);
		System.out.println("bladeMaterial: " + g6.bladeMaterial);
		System.out.println("bodyMaterial: " + g6.bodyMaterial);
		System.out.println("speedLevels: " + g6.speedLevels);
		System.out.println("isEnergyEfficient: " + g6.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g6.countryOfOrigin);
		System.out.println("warrantyMonths: " + g6.warrantyMonths);
		System.out.println("packagingType: " + g6.packagingType);
		System.out.println("weight: " + g6.weight);
		System.out.println("isNoiseFree: " + g6.isNoiseFree);
		System.out.println("feature1: " + g6.feature1);
		System.out.println("feature2: " + g6.feature2);
		System.out.println("feature3: " + g6.feature3);
		System.out.println("hasTimer: " + g6.hasTimer);
		System.out.println("isPortable: " + g6.isPortable);
		System.out.println("rating: " + g6.rating);


		GlacierFan g7 = new GlacierFan();
		g7.productId = 107;
		g7.brandName = "Sample7";
		g7.fanType = "Sample7";
		g7.color = "Sample7";
		g7.power = 17.0;
		g7.price = 17.0;
		g7.isRemoteControlled = false;
		g7.isAvailable = false;
		g7.manufacturingDate = "Sample7";
		g7.expiryDate = "Sample7";
		g7.bladeMaterial = "Sample7";
		g7.bodyMaterial = "Sample7";
		g7.speedLevels = 17.0;
		g7.isEnergyEfficient = false;
		g7.countryOfOrigin = "Sample7";
		g7.warrantyMonths = 107;
		g7.packagingType = "Sample7";
		g7.weight = 17.0;
		g7.isNoiseFree = false;
		g7.feature1 = "Sample7";
		g7.feature2 = "Sample7";
		g7.feature3 = "Sample7";
		g7.hasTimer = false;
		g7.isPortable = false;
		g7.rating = 107;

		System.out.println("----- GlacierFan 7 -----");
		System.out.println("productId: " + g7.productId);
		System.out.println("brandName: " + g7.brandName);
		System.out.println("fanType: " + g7.fanType);
		System.out.println("color: " + g7.color);
		System.out.println("power: " + g7.power);
		System.out.println("price: " + g7.price);
		System.out.println("isRemoteControlled: " + g7.isRemoteControlled);
		System.out.println("isAvailable: " + g7.isAvailable);
		System.out.println("manufacturingDate: " + g7.manufacturingDate);
		System.out.println("expiryDate: " + g7.expiryDate);
		System.out.println("bladeMaterial: " + g7.bladeMaterial);
		System.out.println("bodyMaterial: " + g7.bodyMaterial);
		System.out.println("speedLevels: " + g7.speedLevels);
		System.out.println("isEnergyEfficient: " + g7.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g7.countryOfOrigin);
		System.out.println("warrantyMonths: " + g7.warrantyMonths);
		System.out.println("packagingType: " + g7.packagingType);
		System.out.println("weight: " + g7.weight);
		System.out.println("isNoiseFree: " + g7.isNoiseFree);
		System.out.println("feature1: " + g7.feature1);
		System.out.println("feature2: " + g7.feature2);
		System.out.println("feature3: " + g7.feature3);
		System.out.println("hasTimer: " + g7.hasTimer);
		System.out.println("isPortable: " + g7.isPortable);
		System.out.println("rating: " + g7.rating);


		GlacierFan g8 = new GlacierFan();
		g8.productId = 108;
		g8.brandName = "Sample8";
		g8.fanType = "Sample8";
		g8.color = "Sample8";
		g8.power = 18.0;
		g8.price = 18.0;
		g8.isRemoteControlled = true;
		g8.isAvailable = true;
		g8.manufacturingDate = "Sample8";
		g8.expiryDate = "Sample8";
		g8.bladeMaterial = "Sample8";
		g8.bodyMaterial = "Sample8";
		g8.speedLevels = 18.0;
		g8.isEnergyEfficient = true;
		g8.countryOfOrigin = "Sample8";
		g8.warrantyMonths = 108;
		g8.packagingType = "Sample8";
		g8.weight = 18.0;
		g8.isNoiseFree = true;
		g8.feature1 = "Sample8";
		g8.feature2 = "Sample8";
		g8.feature3 = "Sample8";
		g8.hasTimer = true;
		g8.isPortable = true;
		g8.rating = 108;

		System.out.println("----- GlacierFan 8 -----");
		System.out.println("productId: " + g8.productId);
		System.out.println("brandName: " + g8.brandName);
		System.out.println("fanType: " + g8.fanType);
		System.out.println("color: " + g8.color);
		System.out.println("power: " + g8.power);
		System.out.println("price: " + g8.price);
		System.out.println("isRemoteControlled: " + g8.isRemoteControlled);
		System.out.println("isAvailable: " + g8.isAvailable);
		System.out.println("manufacturingDate: " + g8.manufacturingDate);
		System.out.println("expiryDate: " + g8.expiryDate);
		System.out.println("bladeMaterial: " + g8.bladeMaterial);
		System.out.println("bodyMaterial: " + g8.bodyMaterial);
		System.out.println("speedLevels: " + g8.speedLevels);
		System.out.println("isEnergyEfficient: " + g8.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g8.countryOfOrigin);
		System.out.println("warrantyMonths: " + g8.warrantyMonths);
		System.out.println("packagingType: " + g8.packagingType);
		System.out.println("weight: " + g8.weight);
		System.out.println("isNoiseFree: " + g8.isNoiseFree);
		System.out.println("feature1: " + g8.feature1);
		System.out.println("feature2: " + g8.feature2);
		System.out.println("feature3: " + g8.feature3);
		System.out.println("hasTimer: " + g8.hasTimer);
		System.out.println("isPortable: " + g8.isPortable);
		System.out.println("rating: " + g8.rating);


		GlacierFan g9 = new GlacierFan();
		g9.productId = 109;
		g9.brandName = "Sample9";
		g9.fanType = "Sample9";
		g9.color = "Sample9";
		g9.power = 19.0;
		g9.price = 19.0;
		g9.isRemoteControlled = false;
		g9.isAvailable = false;
		g9.manufacturingDate = "Sample9";
		g9.expiryDate = "Sample9";
		g9.bladeMaterial = "Sample9";
		g9.bodyMaterial = "Sample9";
		g9.speedLevels = 19.0;
		g9.isEnergyEfficient = false;
		g9.countryOfOrigin = "Sample9";
		g9.warrantyMonths = 109;
		g9.packagingType = "Sample9";
		g9.weight = 19.0;
		g9.isNoiseFree = false;
		g9.feature1 = "Sample9";
		g9.feature2 = "Sample9";
		g9.feature3 = "Sample9";
		g9.hasTimer = false;
		g9.isPortable = false;
		g9.rating = 109;

		System.out.println("----- GlacierFan 9 -----");
		System.out.println("productId: " + g9.productId);
		System.out.println("brandName: " + g9.brandName);
		System.out.println("fanType: " + g9.fanType);
		System.out.println("color: " + g9.color);
		System.out.println("power: " + g9.power);
		System.out.println("price: " + g9.price);
		System.out.println("isRemoteControlled: " + g9.isRemoteControlled);
		System.out.println("isAvailable: " + g9.isAvailable);
		System.out.println("manufacturingDate: " + g9.manufacturingDate);
		System.out.println("expiryDate: " + g9.expiryDate);
		System.out.println("bladeMaterial: " + g9.bladeMaterial);
		System.out.println("bodyMaterial: " + g9.bodyMaterial);
		System.out.println("speedLevels: " + g9.speedLevels);
		System.out.println("isEnergyEfficient: " + g9.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g9.countryOfOrigin);
		System.out.println("warrantyMonths: " + g9.warrantyMonths);
		System.out.println("packagingType: " + g9.packagingType);
		System.out.println("weight: " + g9.weight);
		System.out.println("isNoiseFree: " + g9.isNoiseFree);
		System.out.println("feature1: " + g9.feature1);
		System.out.println("feature2: " + g9.feature2);
		System.out.println("feature3: " + g9.feature3);
		System.out.println("hasTimer: " + g9.hasTimer);
		System.out.println("isPortable: " + g9.isPortable);
		System.out.println("rating: " + g9.rating);


		GlacierFan g10 = new GlacierFan();
		g10.productId = 110;
		g10.brandName = "Sample10";
		g10.fanType = "Sample10";
		g10.color = "Sample10";
		g10.power = 20.0;
		g10.price = 20.0;
		g10.isRemoteControlled = true;
		g10.isAvailable = true;
		g10.manufacturingDate = "Sample10";
		g10.expiryDate = "Sample10";
		g10.bladeMaterial = "Sample10";
		g10.bodyMaterial = "Sample10";
		g10.speedLevels = 20.0;
		g10.isEnergyEfficient = true;
		g10.countryOfOrigin = "Sample10";
		g10.warrantyMonths = 110;
		g10.packagingType = "Sample10";
		g10.weight = 20.0;
		g10.isNoiseFree = true;
		g10.feature1 = "Sample10";
		g10.feature2 = "Sample10";
		g10.feature3 = "Sample10";
		g10.hasTimer = true;
		g10.isPortable = true;
		g10.rating = 110;

		System.out.println("----- GlacierFan 10 -----");
		System.out.println("productId: " + g10.productId);
		System.out.println("brandName: " + g10.brandName);
		System.out.println("fanType: " + g10.fanType);
		System.out.println("color: " + g10.color);
		System.out.println("power: " + g10.power);
		System.out.println("price: " + g10.price);
		System.out.println("isRemoteControlled: " + g10.isRemoteControlled);
		System.out.println("isAvailable: " + g10.isAvailable);
		System.out.println("manufacturingDate: " + g10.manufacturingDate);
		System.out.println("expiryDate: " + g10.expiryDate);
		System.out.println("bladeMaterial: " + g10.bladeMaterial);
		System.out.println("bodyMaterial: " + g10.bodyMaterial);
		System.out.println("speedLevels: " + g10.speedLevels);
		System.out.println("isEnergyEfficient: " + g10.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g10.countryOfOrigin);
		System.out.println("warrantyMonths: " + g10.warrantyMonths);
		System.out.println("packagingType: " + g10.packagingType);
		System.out.println("weight: " + g10.weight);
		System.out.println("isNoiseFree: " + g10.isNoiseFree);
		System.out.println("feature1: " + g10.feature1);
		System.out.println("feature2: " + g10.feature2);
		System.out.println("feature3: " + g10.feature3);
		System.out.println("hasTimer: " + g10.hasTimer);
		System.out.println("isPortable: " + g10.isPortable);
		System.out.println("rating: " + g10.rating);


		GlacierFan g11 = new GlacierFan();
		g11.productId = 111;
		g11.brandName = "Sample11";
		g11.fanType = "Sample11";
		g11.color = "Sample11";
		g11.power = 21.0;
		g11.price = 21.0;
		g11.isRemoteControlled = false;
		g11.isAvailable = false;
		g11.manufacturingDate = "Sample11";
		g11.expiryDate = "Sample11";
		g11.bladeMaterial = "Sample11";
		g11.bodyMaterial = "Sample11";
		g11.speedLevels = 21.0;
		g11.isEnergyEfficient = false;
		g11.countryOfOrigin = "Sample11";
		g11.warrantyMonths = 111;
		g11.packagingType = "Sample11";
		g11.weight = 21.0;
		g11.isNoiseFree = false;
		g11.feature1 = "Sample11";
		g11.feature2 = "Sample11";
		g11.feature3 = "Sample11";
		g11.hasTimer = false;
		g11.isPortable = false;
		g11.rating = 111;

		System.out.println("----- GlacierFan 11 -----");
		System.out.println("productId: " + g11.productId);
		System.out.println("brandName: " + g11.brandName);
		System.out.println("fanType: " + g11.fanType);
		System.out.println("color: " + g11.color);
		System.out.println("power: " + g11.power);
		System.out.println("price: " + g11.price);
		System.out.println("isRemoteControlled: " + g11.isRemoteControlled);
		System.out.println("isAvailable: " + g11.isAvailable);
		System.out.println("manufacturingDate: " + g11.manufacturingDate);
		System.out.println("expiryDate: " + g11.expiryDate);
		System.out.println("bladeMaterial: " + g11.bladeMaterial);
		System.out.println("bodyMaterial: " + g11.bodyMaterial);
		System.out.println("speedLevels: " + g11.speedLevels);
		System.out.println("isEnergyEfficient: " + g11.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g11.countryOfOrigin);
		System.out.println("warrantyMonths: " + g11.warrantyMonths);
		System.out.println("packagingType: " + g11.packagingType);
		System.out.println("weight: " + g11.weight);
		System.out.println("isNoiseFree: " + g11.isNoiseFree);
		System.out.println("feature1: " + g11.feature1);
		System.out.println("feature2: " + g11.feature2);
		System.out.println("feature3: " + g11.feature3);
		System.out.println("hasTimer: " + g11.hasTimer);
		System.out.println("isPortable: " + g11.isPortable);
		System.out.println("rating: " + g11.rating);


		GlacierFan g12 = new GlacierFan();
		g12.productId = 112;
		g12.brandName = "Sample12";
		g12.fanType = "Sample12";
		g12.color = "Sample12";
		g12.power = 22.0;
		g12.price = 22.0;
		g12.isRemoteControlled = true;
		g12.isAvailable = true;
		g12.manufacturingDate = "Sample12";
		g12.expiryDate = "Sample12";
		g12.bladeMaterial = "Sample12";
		g12.bodyMaterial = "Sample12";
		g12.speedLevels = 22.0;
		g12.isEnergyEfficient = true;
		g12.countryOfOrigin = "Sample12";
		g12.warrantyMonths = 112;
		g12.packagingType = "Sample12";
		g12.weight = 22.0;
		g12.isNoiseFree = true;
		g12.feature1 = "Sample12";
		g12.feature2 = "Sample12";
		g12.feature3 = "Sample12";
		g12.hasTimer = true;
		g12.isPortable = true;
		g12.rating = 112;

		System.out.println("----- GlacierFan 12 -----");
		System.out.println("productId: " + g12.productId);
		System.out.println("brandName: " + g12.brandName);
		System.out.println("fanType: " + g12.fanType);
		System.out.println("color: " + g12.color);
		System.out.println("power: " + g12.power);
		System.out.println("price: " + g12.price);
		System.out.println("isRemoteControlled: " + g12.isRemoteControlled);
		System.out.println("isAvailable: " + g12.isAvailable);
		System.out.println("manufacturingDate: " + g12.manufacturingDate);
		System.out.println("expiryDate: " + g12.expiryDate);
		System.out.println("bladeMaterial: " + g12.bladeMaterial);
		System.out.println("bodyMaterial: " + g12.bodyMaterial);
		System.out.println("speedLevels: " + g12.speedLevels);
		System.out.println("isEnergyEfficient: " + g12.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g12.countryOfOrigin);
		System.out.println("warrantyMonths: " + g12.warrantyMonths);
		System.out.println("packagingType: " + g12.packagingType);
		System.out.println("weight: " + g12.weight);
		System.out.println("isNoiseFree: " + g12.isNoiseFree);
		System.out.println("feature1: " + g12.feature1);
		System.out.println("feature2: " + g12.feature2);
		System.out.println("feature3: " + g12.feature3);
		System.out.println("hasTimer: " + g12.hasTimer);
		System.out.println("isPortable: " + g12.isPortable);
		System.out.println("rating: " + g12.rating);


		GlacierFan g13 = new GlacierFan();
		g13.productId = 113;
		g13.brandName = "Sample13";
		g13.fanType = "Sample13";
		g13.color = "Sample13";
		g13.power = 23.0;
		g13.price = 23.0;
		g13.isRemoteControlled = false;
		g13.isAvailable = false;
		g13.manufacturingDate = "Sample13";
		g13.expiryDate = "Sample13";
		g13.bladeMaterial = "Sample13";
		g13.bodyMaterial = "Sample13";
		g13.speedLevels = 23.0;
		g13.isEnergyEfficient = false;
		g13.countryOfOrigin = "Sample13";
		g13.warrantyMonths = 113;
		g13.packagingType = "Sample13";
		g13.weight = 23.0;
		g13.isNoiseFree = false;
		g13.feature1 = "Sample13";
		g13.feature2 = "Sample13";
		g13.feature3 = "Sample13";
		g13.hasTimer = false;
		g13.isPortable = false;
		g13.rating = 113;

		System.out.println("----- GlacierFan 13 -----");
		System.out.println("productId: " + g13.productId);
		System.out.println("brandName: " + g13.brandName);
		System.out.println("fanType: " + g13.fanType);
		System.out.println("color: " + g13.color);
		System.out.println("power: " + g13.power);
		System.out.println("price: " + g13.price);
		System.out.println("isRemoteControlled: " + g13.isRemoteControlled);
		System.out.println("isAvailable: " + g13.isAvailable);
		System.out.println("manufacturingDate: " + g13.manufacturingDate);
		System.out.println("expiryDate: " + g13.expiryDate);
		System.out.println("bladeMaterial: " + g13.bladeMaterial);
		System.out.println("bodyMaterial: " + g13.bodyMaterial);
		System.out.println("speedLevels: " + g13.speedLevels);
		System.out.println("isEnergyEfficient: " + g13.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g13.countryOfOrigin);
		System.out.println("warrantyMonths: " + g13.warrantyMonths);
		System.out.println("packagingType: " + g13.packagingType);
		System.out.println("weight: " + g13.weight);
		System.out.println("isNoiseFree: " + g13.isNoiseFree);
		System.out.println("feature1: " + g13.feature1);
		System.out.println("feature2: " + g13.feature2);
		System.out.println("feature3: " + g13.feature3);
		System.out.println("hasTimer: " + g13.hasTimer);
		System.out.println("isPortable: " + g13.isPortable);
		System.out.println("rating: " + g13.rating);


		GlacierFan g14 = new GlacierFan();
		g14.productId = 114;
		g14.brandName = "Sample14";
		g14.fanType = "Sample14";
		g14.color = "Sample14";
		g14.power = 24.0;
		g14.price = 24.0;
		g14.isRemoteControlled = true;
		g14.isAvailable = true;
		g14.manufacturingDate = "Sample14";
		g14.expiryDate = "Sample14";
		g14.bladeMaterial = "Sample14";
		g14.bodyMaterial = "Sample14";
		g14.speedLevels = 24.0;
		g14.isEnergyEfficient = true;
		g14.countryOfOrigin = "Sample14";
		g14.warrantyMonths = 114;
		g14.packagingType = "Sample14";
		g14.weight = 24.0;
		g14.isNoiseFree = true;
		g14.feature1 = "Sample14";
		g14.feature2 = "Sample14";
		g14.feature3 = "Sample14";
		g14.hasTimer = true;
		g14.isPortable = true;
		g14.rating = 114;

		System.out.println("----- GlacierFan 14 -----");
		System.out.println("productId: " + g14.productId);
		System.out.println("brandName: " + g14.brandName);
		System.out.println("fanType: " + g14.fanType);
		System.out.println("color: " + g14.color);
		System.out.println("power: " + g14.power);
		System.out.println("price: " + g14.price);
		System.out.println("isRemoteControlled: " + g14.isRemoteControlled);
		System.out.println("isAvailable: " + g14.isAvailable);
		System.out.println("manufacturingDate: " + g14.manufacturingDate);
		System.out.println("expiryDate: " + g14.expiryDate);
		System.out.println("bladeMaterial: " + g14.bladeMaterial);
		System.out.println("bodyMaterial: " + g14.bodyMaterial);
		System.out.println("speedLevels: " + g14.speedLevels);
		System.out.println("isEnergyEfficient: " + g14.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g14.countryOfOrigin);
		System.out.println("warrantyMonths: " + g14.warrantyMonths);
		System.out.println("packagingType: " + g14.packagingType);
		System.out.println("weight: " + g14.weight);
		System.out.println("isNoiseFree: " + g14.isNoiseFree);
		System.out.println("feature1: " + g14.feature1);
		System.out.println("feature2: " + g14.feature2);
		System.out.println("feature3: " + g14.feature3);
		System.out.println("hasTimer: " + g14.hasTimer);
		System.out.println("isPortable: " + g14.isPortable);
		System.out.println("rating: " + g14.rating);


		GlacierFan g15 = new GlacierFan();
		g15.productId = 115;
		g15.brandName = "Sample15";
		g15.fanType = "Sample15";
		g15.color = "Sample15";
		g15.power = 25.0;
		g15.price = 25.0;
		g15.isRemoteControlled = false;
		g15.isAvailable = false;
		g15.manufacturingDate = "Sample15";
		g15.expiryDate = "Sample15";
		g15.bladeMaterial = "Sample15";
		g15.bodyMaterial = "Sample15";
		g15.speedLevels = 25.0;
		g15.isEnergyEfficient = false;
		g15.countryOfOrigin = "Sample15";
		g15.warrantyMonths = 115;
		g15.packagingType = "Sample15";
		g15.weight = 25.0;
		g15.isNoiseFree = false;
		g15.feature1 = "Sample15";
		g15.feature2 = "Sample15";
		g15.feature3 = "Sample15";
		g15.hasTimer = false;
		g15.isPortable = false;
		g15.rating = 115;

		System.out.println("----- GlacierFan 15 -----");
		System.out.println("productId: " + g15.productId);
		System.out.println("brandName: " + g15.brandName);
		System.out.println("fanType: " + g15.fanType);
		System.out.println("color: " + g15.color);
		System.out.println("power: " + g15.power);
		System.out.println("price: " + g15.price);
		System.out.println("isRemoteControlled: " + g15.isRemoteControlled);
		System.out.println("isAvailable: " + g15.isAvailable);
		System.out.println("manufacturingDate: " + g15.manufacturingDate);
		System.out.println("expiryDate: " + g15.expiryDate);
		System.out.println("bladeMaterial: " + g15.bladeMaterial);
		System.out.println("bodyMaterial: " + g15.bodyMaterial);
		System.out.println("speedLevels: " + g15.speedLevels);
		System.out.println("isEnergyEfficient: " + g15.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g15.countryOfOrigin);
		System.out.println("warrantyMonths: " + g15.warrantyMonths);
		System.out.println("packagingType: " + g15.packagingType);
		System.out.println("weight: " + g15.weight);
		System.out.println("isNoiseFree: " + g15.isNoiseFree);
		System.out.println("feature1: " + g15.feature1);
		System.out.println("feature2: " + g15.feature2);
		System.out.println("feature3: " + g15.feature3);
		System.out.println("hasTimer: " + g15.hasTimer);
		System.out.println("isPortable: " + g15.isPortable);
		System.out.println("rating: " + g15.rating);


		GlacierFan g16 = new GlacierFan();
		g16.productId = 116;
		g16.brandName = "Sample16";
		g16.fanType = "Sample16";
		g16.color = "Sample16";
		g16.power = 26.0;
		g16.price = 26.0;
		g16.isRemoteControlled = true;
		g16.isAvailable = true;
		g16.manufacturingDate = "Sample16";
		g16.expiryDate = "Sample16";
		g16.bladeMaterial = "Sample16";
		g16.bodyMaterial = "Sample16";
		g16.speedLevels = 26.0;
		g16.isEnergyEfficient = true;
		g16.countryOfOrigin = "Sample16";
		g16.warrantyMonths = 116;
		g16.packagingType = "Sample16";
		g16.weight = 26.0;
		g16.isNoiseFree = true;
		g16.feature1 = "Sample16";
		g16.feature2 = "Sample16";
		g16.feature3 = "Sample16";
		g16.hasTimer = true;
		g16.isPortable = true;
		g16.rating = 116;

		System.out.println("----- GlacierFan 16 -----");
		System.out.println("productId: " + g16.productId);
		System.out.println("brandName: " + g16.brandName);
		System.out.println("fanType: " + g16.fanType);
		System.out.println("color: " + g16.color);
		System.out.println("power: " + g16.power);
		System.out.println("price: " + g16.price);
		System.out.println("isRemoteControlled: " + g16.isRemoteControlled);
		System.out.println("isAvailable: " + g16.isAvailable);
		System.out.println("manufacturingDate: " + g16.manufacturingDate);
		System.out.println("expiryDate: " + g16.expiryDate);
		System.out.println("bladeMaterial: " + g16.bladeMaterial);
		System.out.println("bodyMaterial: " + g16.bodyMaterial);
		System.out.println("speedLevels: " + g16.speedLevels);
		System.out.println("isEnergyEfficient: " + g16.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g16.countryOfOrigin);
		System.out.println("warrantyMonths: " + g16.warrantyMonths);
		System.out.println("packagingType: " + g16.packagingType);
		System.out.println("weight: " + g16.weight);
		System.out.println("isNoiseFree: " + g16.isNoiseFree);
		System.out.println("feature1: " + g16.feature1);
		System.out.println("feature2: " + g16.feature2);
		System.out.println("feature3: " + g16.feature3);
		System.out.println("hasTimer: " + g16.hasTimer);
		System.out.println("isPortable: " + g16.isPortable);
		System.out.println("rating: " + g16.rating);


		GlacierFan g17 = new GlacierFan();
		g17.productId = 117;
		g17.brandName = "Sample17";
		g17.fanType = "Sample17";
		g17.color = "Sample17";
		g17.power = 27.0;
		g17.price = 27.0;
		g17.isRemoteControlled = false;
		g17.isAvailable = false;
		g17.manufacturingDate = "Sample17";
		g17.expiryDate = "Sample17";
		g17.bladeMaterial = "Sample17";
		g17.bodyMaterial = "Sample17";
		g17.speedLevels = 27.0;
		g17.isEnergyEfficient = false;
		g17.countryOfOrigin = "Sample17";
		g17.warrantyMonths = 117;
		g17.packagingType = "Sample17";
		g17.weight = 27.0;
		g17.isNoiseFree = false;
		g17.feature1 = "Sample17";
		g17.feature2 = "Sample17";
		g17.feature3 = "Sample17";
		g17.hasTimer = false;
		g17.isPortable = false;
		g17.rating = 117;

		System.out.println("----- GlacierFan 17 -----");
		System.out.println("productId: " + g17.productId);
		System.out.println("brandName: " + g17.brandName);
		System.out.println("fanType: " + g17.fanType);
		System.out.println("color: " + g17.color);
		System.out.println("power: " + g17.power);
		System.out.println("price: " + g17.price);
		System.out.println("isRemoteControlled: " + g17.isRemoteControlled);
		System.out.println("isAvailable: " + g17.isAvailable);
		System.out.println("manufacturingDate: " + g17.manufacturingDate);
		System.out.println("expiryDate: " + g17.expiryDate);
		System.out.println("bladeMaterial: " + g17.bladeMaterial);
		System.out.println("bodyMaterial: " + g17.bodyMaterial);
		System.out.println("speedLevels: " + g17.speedLevels);
		System.out.println("isEnergyEfficient: " + g17.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g17.countryOfOrigin);
		System.out.println("warrantyMonths: " + g17.warrantyMonths);
		System.out.println("packagingType: " + g17.packagingType);
		System.out.println("weight: " + g17.weight);
		System.out.println("isNoiseFree: " + g17.isNoiseFree);
		System.out.println("feature1: " + g17.feature1);
		System.out.println("feature2: " + g17.feature2);
		System.out.println("feature3: " + g17.feature3);
		System.out.println("hasTimer: " + g17.hasTimer);
		System.out.println("isPortable: " + g17.isPortable);
		System.out.println("rating: " + g17.rating);


		GlacierFan g18 = new GlacierFan();
		g18.productId = 118;
		g18.brandName = "Sample18";
		g18.fanType = "Sample18";
		g18.color = "Sample18";
		g18.power = 28.0;
		g18.price = 28.0;
		g18.isRemoteControlled = true;
		g18.isAvailable = true;
		g18.manufacturingDate = "Sample18";
		g18.expiryDate = "Sample18";
		g18.bladeMaterial = "Sample18";
		g18.bodyMaterial = "Sample18";
		g18.speedLevels = 28.0;
		g18.isEnergyEfficient = true;
		g18.countryOfOrigin = "Sample18";
		g18.warrantyMonths = 118;
		g18.packagingType = "Sample18";
		g18.weight = 28.0;
		g18.isNoiseFree = true;
		g18.feature1 = "Sample18";
		g18.feature2 = "Sample18";
		g18.feature3 = "Sample18";
		g18.hasTimer = true;
		g18.isPortable = true;
		g18.rating = 118;

		System.out.println("----- GlacierFan 18 -----");
		System.out.println("productId: " + g18.productId);
		System.out.println("brandName: " + g18.brandName);
		System.out.println("fanType: " + g18.fanType);
		System.out.println("color: " + g18.color);
		System.out.println("power: " + g18.power);
		System.out.println("price: " + g18.price);
		System.out.println("isRemoteControlled: " + g18.isRemoteControlled);
		System.out.println("isAvailable: " + g18.isAvailable);
		System.out.println("manufacturingDate: " + g18.manufacturingDate);
		System.out.println("expiryDate: " + g18.expiryDate);
		System.out.println("bladeMaterial: " + g18.bladeMaterial);
		System.out.println("bodyMaterial: " + g18.bodyMaterial);
		System.out.println("speedLevels: " + g18.speedLevels);
		System.out.println("isEnergyEfficient: " + g18.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g18.countryOfOrigin);
		System.out.println("warrantyMonths: " + g18.warrantyMonths);
		System.out.println("packagingType: " + g18.packagingType);
		System.out.println("weight: " + g18.weight);
		System.out.println("isNoiseFree: " + g18.isNoiseFree);
		System.out.println("feature1: " + g18.feature1);
		System.out.println("feature2: " + g18.feature2);
		System.out.println("feature3: " + g18.feature3);
		System.out.println("hasTimer: " + g18.hasTimer);
		System.out.println("isPortable: " + g18.isPortable);
		System.out.println("rating: " + g18.rating);


		GlacierFan g19 = new GlacierFan();
		g19.productId = 119;
		g19.brandName = "Sample19";
		g19.fanType = "Sample19";
		g19.color = "Sample19";
		g19.power = 29.0;
		g19.price = 29.0;
		g19.isRemoteControlled = false;
		g19.isAvailable = false;
		g19.manufacturingDate = "Sample19";
		g19.expiryDate = "Sample19";
		g19.bladeMaterial = "Sample19";
		g19.bodyMaterial = "Sample19";
		g19.speedLevels = 29.0;
		g19.isEnergyEfficient = false;
		g19.countryOfOrigin = "Sample19";
		g19.warrantyMonths = 119;
		g19.packagingType = "Sample19";
		g19.weight = 29.0;
		g19.isNoiseFree = false;
		g19.feature1 = "Sample19";
		g19.feature2 = "Sample19";
		g19.feature3 = "Sample19";
		g19.hasTimer = false;
		g19.isPortable = false;
		g19.rating = 119;

		System.out.println("----- GlacierFan 19 -----");
		System.out.println("productId: " + g19.productId);
		System.out.println("brandName: " + g19.brandName);
		System.out.println("fanType: " + g19.fanType);
		System.out.println("color: " + g19.color);
		System.out.println("power: " + g19.power);
		System.out.println("price: " + g19.price);
		System.out.println("isRemoteControlled: " + g19.isRemoteControlled);
		System.out.println("isAvailable: " + g19.isAvailable);
		System.out.println("manufacturingDate: " + g19.manufacturingDate);
		System.out.println("expiryDate: " + g19.expiryDate);
		System.out.println("bladeMaterial: " + g19.bladeMaterial);
		System.out.println("bodyMaterial: " + g19.bodyMaterial);
		System.out.println("speedLevels: " + g19.speedLevels);
		System.out.println("isEnergyEfficient: " + g19.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g19.countryOfOrigin);
		System.out.println("warrantyMonths: " + g19.warrantyMonths);
		System.out.println("packagingType: " + g19.packagingType);
		System.out.println("weight: " + g19.weight);
		System.out.println("isNoiseFree: " + g19.isNoiseFree);
		System.out.println("feature1: " + g19.feature1);
		System.out.println("feature2: " + g19.feature2);
		System.out.println("feature3: " + g19.feature3);
		System.out.println("hasTimer: " + g19.hasTimer);
		System.out.println("isPortable: " + g19.isPortable);
		System.out.println("rating: " + g19.rating);


		GlacierFan g20 = new GlacierFan();
		g20.productId = 120;
		g20.brandName = "Sample20";
		g20.fanType = "Sample20";
		g20.color = "Sample20";
		g20.power = 30.0;
		g20.price = 30.0;
		g20.isRemoteControlled = true;
		g20.isAvailable = true;
		g20.manufacturingDate = "Sample20";
		g20.expiryDate = "Sample20";
		g20.bladeMaterial = "Sample20";
		g20.bodyMaterial = "Sample20";
		g20.speedLevels = 30.0;
		g20.isEnergyEfficient = true;
		g20.countryOfOrigin = "Sample20";
		g20.warrantyMonths = 120;
		g20.packagingType = "Sample20";
		g20.weight = 30.0;
		g20.isNoiseFree = true;
		g20.feature1 = "Sample20";
		g20.feature2 = "Sample20";
		g20.feature3 = "Sample20";
		g20.hasTimer = true;
		g20.isPortable = true;
		g20.rating = 120;

		System.out.println("----- GlacierFan 20 -----");
		System.out.println("productId: " + g20.productId);
		System.out.println("brandName: " + g20.brandName);
		System.out.println("fanType: " + g20.fanType);
		System.out.println("color: " + g20.color);
		System.out.println("power: " + g20.power);
		System.out.println("price: " + g20.price);
		System.out.println("isRemoteControlled: " + g20.isRemoteControlled);
		System.out.println("isAvailable: " + g20.isAvailable);
		System.out.println("manufacturingDate: " + g20.manufacturingDate);
		System.out.println("expiryDate: " + g20.expiryDate);
		System.out.println("bladeMaterial: " + g20.bladeMaterial);
		System.out.println("bodyMaterial: " + g20.bodyMaterial);
		System.out.println("speedLevels: " + g20.speedLevels);
		System.out.println("isEnergyEfficient: " + g20.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g20.countryOfOrigin);
		System.out.println("warrantyMonths: " + g20.warrantyMonths);
		System.out.println("packagingType: " + g20.packagingType);
		System.out.println("weight: " + g20.weight);
		System.out.println("isNoiseFree: " + g20.isNoiseFree);
		System.out.println("feature1: " + g20.feature1);
		System.out.println("feature2: " + g20.feature2);
		System.out.println("feature3: " + g20.feature3);
		System.out.println("hasTimer: " + g20.hasTimer);
		System.out.println("isPortable: " + g20.isPortable);
		System.out.println("rating: " + g20.rating);


		GlacierFan g21 = new GlacierFan();
		g21.productId = 121;
		g21.brandName = "Sample21";
		g21.fanType = "Sample21";
		g21.color = "Sample21";
		g21.power = 31.0;
		g21.price = 31.0;
		g21.isRemoteControlled = false;
		g21.isAvailable = false;
		g21.manufacturingDate = "Sample21";
		g21.expiryDate = "Sample21";
		g21.bladeMaterial = "Sample21";
		g21.bodyMaterial = "Sample21";
		g21.speedLevels = 31.0;
		g21.isEnergyEfficient = false;
		g21.countryOfOrigin = "Sample21";
		g21.warrantyMonths = 121;
		g21.packagingType = "Sample21";
		g21.weight = 31.0;
		g21.isNoiseFree = false;
		g21.feature1 = "Sample21";
		g21.feature2 = "Sample21";
		g21.feature3 = "Sample21";
		g21.hasTimer = false;
		g21.isPortable = false;
		g21.rating = 121;

		System.out.println("----- GlacierFan 21 -----");
		System.out.println("productId: " + g21.productId);
		System.out.println("brandName: " + g21.brandName);
		System.out.println("fanType: " + g21.fanType);
		System.out.println("color: " + g21.color);
		System.out.println("power: " + g21.power);
		System.out.println("price: " + g21.price);
		System.out.println("isRemoteControlled: " + g21.isRemoteControlled);
		System.out.println("isAvailable: " + g21.isAvailable);
		System.out.println("manufacturingDate: " + g21.manufacturingDate);
		System.out.println("expiryDate: " + g21.expiryDate);
		System.out.println("bladeMaterial: " + g21.bladeMaterial);
		System.out.println("bodyMaterial: " + g21.bodyMaterial);
		System.out.println("speedLevels: " + g21.speedLevels);
		System.out.println("isEnergyEfficient: " + g21.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g21.countryOfOrigin);
		System.out.println("warrantyMonths: " + g21.warrantyMonths);
		System.out.println("packagingType: " + g21.packagingType);
		System.out.println("weight: " + g21.weight);
		System.out.println("isNoiseFree: " + g21.isNoiseFree);
		System.out.println("feature1: " + g21.feature1);
		System.out.println("feature2: " + g21.feature2);
		System.out.println("feature3: " + g21.feature3);
		System.out.println("hasTimer: " + g21.hasTimer);
		System.out.println("isPortable: " + g21.isPortable);
		System.out.println("rating: " + g21.rating);


		GlacierFan g22 = new GlacierFan();
		g22.productId = 122;
		g22.brandName = "Sample22";
		g22.fanType = "Sample22";
		g22.color = "Sample22";
		g22.power = 32.0;
		g22.price = 32.0;
		g22.isRemoteControlled = true;
		g22.isAvailable = true;
		g22.manufacturingDate = "Sample22";
		g22.expiryDate = "Sample22";
		g22.bladeMaterial = "Sample22";
		g22.bodyMaterial = "Sample22";
		g22.speedLevels = 32.0;
		g22.isEnergyEfficient = true;
		g22.countryOfOrigin = "Sample22";
		g22.warrantyMonths = 122;
		g22.packagingType = "Sample22";
		g22.weight = 32.0;
		g22.isNoiseFree = true;
		g22.feature1 = "Sample22";
		g22.feature2 = "Sample22";
		g22.feature3 = "Sample22";
		g22.hasTimer = true;
		g22.isPortable = true;
		g22.rating = 122;

		System.out.println("----- GlacierFan 22 -----");
		System.out.println("productId: " + g22.productId);
		System.out.println("brandName: " + g22.brandName);
		System.out.println("fanType: " + g22.fanType);
		System.out.println("color: " + g22.color);
		System.out.println("power: " + g22.power);
		System.out.println("price: " + g22.price);
		System.out.println("isRemoteControlled: " + g22.isRemoteControlled);
		System.out.println("isAvailable: " + g22.isAvailable);
		System.out.println("manufacturingDate: " + g22.manufacturingDate);
		System.out.println("expiryDate: " + g22.expiryDate);
		System.out.println("bladeMaterial: " + g22.bladeMaterial);
		System.out.println("bodyMaterial: " + g22.bodyMaterial);
		System.out.println("speedLevels: " + g22.speedLevels);
		System.out.println("isEnergyEfficient: " + g22.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g22.countryOfOrigin);
		System.out.println("warrantyMonths: " + g22.warrantyMonths);
		System.out.println("packagingType: " + g22.packagingType);
		System.out.println("weight: " + g22.weight);
		System.out.println("isNoiseFree: " + g22.isNoiseFree);
		System.out.println("feature1: " + g22.feature1);
		System.out.println("feature2: " + g22.feature2);
		System.out.println("feature3: " + g22.feature3);
		System.out.println("hasTimer: " + g22.hasTimer);
		System.out.println("isPortable: " + g22.isPortable);
		System.out.println("rating: " + g22.rating);


		GlacierFan g23 = new GlacierFan();
		g23.productId = 123;
		g23.brandName = "Sample23";
		g23.fanType = "Sample23";
		g23.color = "Sample23";
		g23.power = 33.0;
		g23.price = 33.0;
		g23.isRemoteControlled = false;
		g23.isAvailable = false;
		g23.manufacturingDate = "Sample23";
		g23.expiryDate = "Sample23";
		g23.bladeMaterial = "Sample23";
		g23.bodyMaterial = "Sample23";
		g23.speedLevels = 33.0;
		g23.isEnergyEfficient = false;
		g23.countryOfOrigin = "Sample23";
		g23.warrantyMonths = 123;
		g23.packagingType = "Sample23";
		g23.weight = 33.0;
		g23.isNoiseFree = false;
		g23.feature1 = "Sample23";
		g23.feature2 = "Sample23";
		g23.feature3 = "Sample23";
		g23.hasTimer = false;
		g23.isPortable = false;
		g23.rating = 123;

		System.out.println("----- GlacierFan 23 -----");
		System.out.println("productId: " + g23.productId);
		System.out.println("brandName: " + g23.brandName);
		System.out.println("fanType: " + g23.fanType);
		System.out.println("color: " + g23.color);
		System.out.println("power: " + g23.power);
		System.out.println("price: " + g23.price);
		System.out.println("isRemoteControlled: " + g23.isRemoteControlled);
		System.out.println("isAvailable: " + g23.isAvailable);
		System.out.println("manufacturingDate: " + g23.manufacturingDate);
		System.out.println("expiryDate: " + g23.expiryDate);
		System.out.println("bladeMaterial: " + g23.bladeMaterial);
		System.out.println("bodyMaterial: " + g23.bodyMaterial);
		System.out.println("speedLevels: " + g23.speedLevels);
		System.out.println("isEnergyEfficient: " + g23.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g23.countryOfOrigin);
		System.out.println("warrantyMonths: " + g23.warrantyMonths);
		System.out.println("packagingType: " + g23.packagingType);
		System.out.println("weight: " + g23.weight);
		System.out.println("isNoiseFree: " + g23.isNoiseFree);
		System.out.println("feature1: " + g23.feature1);
		System.out.println("feature2: " + g23.feature2);
		System.out.println("feature3: " + g23.feature3);
		System.out.println("hasTimer: " + g23.hasTimer);
		System.out.println("isPortable: " + g23.isPortable);
		System.out.println("rating: " + g23.rating);


		GlacierFan g24 = new GlacierFan();
		g24.productId = 124;
		g24.brandName = "Sample24";
		g24.fanType = "Sample24";
		g24.color = "Sample24";
		g24.power = 34.0;
		g24.price = 34.0;
		g24.isRemoteControlled = true;
		g24.isAvailable = true;
		g24.manufacturingDate = "Sample24";
		g24.expiryDate = "Sample24";
		g24.bladeMaterial = "Sample24";
		g24.bodyMaterial = "Sample24";
		g24.speedLevels = 34.0;
		g24.isEnergyEfficient = true;
		g24.countryOfOrigin = "Sample24";
		g24.warrantyMonths = 124;
		g24.packagingType = "Sample24";
		g24.weight = 34.0;
		g24.isNoiseFree = true;
		g24.feature1 = "Sample24";
		g24.feature2 = "Sample24";
		g24.feature3 = "Sample24";
		g24.hasTimer = true;
		g24.isPortable = true;
		g24.rating = 124;

		System.out.println("----- GlacierFan 24 -----");
		System.out.println("productId: " + g24.productId);
		System.out.println("brandName: " + g24.brandName);
		System.out.println("fanType: " + g24.fanType);
		System.out.println("color: " + g24.color);
		System.out.println("power: " + g24.power);
		System.out.println("price: " + g24.price);
		System.out.println("isRemoteControlled: " + g24.isRemoteControlled);
		System.out.println("isAvailable: " + g24.isAvailable);
		System.out.println("manufacturingDate: " + g24.manufacturingDate);
		System.out.println("expiryDate: " + g24.expiryDate);
		System.out.println("bladeMaterial: " + g24.bladeMaterial);
		System.out.println("bodyMaterial: " + g24.bodyMaterial);
		System.out.println("speedLevels: " + g24.speedLevels);
		System.out.println("isEnergyEfficient: " + g24.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g24.countryOfOrigin);
		System.out.println("warrantyMonths: " + g24.warrantyMonths);
		System.out.println("packagingType: " + g24.packagingType);
		System.out.println("weight: " + g24.weight);
		System.out.println("isNoiseFree: " + g24.isNoiseFree);
		System.out.println("feature1: " + g24.feature1);
		System.out.println("feature2: " + g24.feature2);
		System.out.println("feature3: " + g24.feature3);
		System.out.println("hasTimer: " + g24.hasTimer);
		System.out.println("isPortable: " + g24.isPortable);
		System.out.println("rating: " + g24.rating);


		GlacierFan g25 = new GlacierFan();
		g25.productId = 125;
		g25.brandName = "Sample25";
		g25.fanType = "Sample25";
		g25.color = "Sample25";
		g25.power = 35.0;
		g25.price = 35.0;
		g25.isRemoteControlled = false;
		g25.isAvailable = false;
		g25.manufacturingDate = "Sample25";
		g25.expiryDate = "Sample25";
		g25.bladeMaterial = "Sample25";
		g25.bodyMaterial = "Sample25";
		g25.speedLevels = 35.0;
		g25.isEnergyEfficient = false;
		g25.countryOfOrigin = "Sample25";
		g25.warrantyMonths = 125;
		g25.packagingType = "Sample25";
		g25.weight = 35.0;
		g25.isNoiseFree = false;
		g25.feature1 = "Sample25";
		g25.feature2 = "Sample25";
		g25.feature3 = "Sample25";
		g25.hasTimer = false;
		g25.isPortable = false;
		g25.rating = 125;

		System.out.println("----- GlacierFan 25 -----");
		System.out.println("productId: " + g25.productId);
		System.out.println("brandName: " + g25.brandName);
		System.out.println("fanType: " + g25.fanType);
		System.out.println("color: " + g25.color);
		System.out.println("power: " + g25.power);
		System.out.println("price: " + g25.price);
		System.out.println("isRemoteControlled: " + g25.isRemoteControlled);
		System.out.println("isAvailable: " + g25.isAvailable);
		System.out.println("manufacturingDate: " + g25.manufacturingDate);
		System.out.println("expiryDate: " + g25.expiryDate);
		System.out.println("bladeMaterial: " + g25.bladeMaterial);
		System.out.println("bodyMaterial: " + g25.bodyMaterial);
		System.out.println("speedLevels: " + g25.speedLevels);
		System.out.println("isEnergyEfficient: " + g25.isEnergyEfficient);
		System.out.println("countryOfOrigin: " + g25.countryOfOrigin);
		System.out.println("warrantyMonths: " + g25.warrantyMonths);
		System.out.println("packagingType: " + g25.packagingType);
		System.out.println("weight: " + g25.weight);
		System.out.println("isNoiseFree: " + g25.isNoiseFree);
		System.out.println("feature1: " + g25.feature1);
		System.out.println("feature2: " + g25.feature2);
		System.out.println("feature3: " + g25.feature3);
		System.out.println("hasTimer: " + g25.hasTimer);
		System.out.println("isPortable: " + g25.isPortable);
		System.out.println("rating: " + g25.rating);


	}
}
