class LanternRunner {
	public static void main(String[] args) {

		Lantern l1 = new Lantern();
		l1.productId = 101;
		l1.brandName = "Sample1";
		l1.lightType = "Sample1";
		l1.color = "Sample1";
		l1.batteryCapacity = 11.0;
		l1.price = 11.0;
		l1.isRechargeable = false;
		l1.isAvailable = false;
		l1.manufacturingDate = "Sample1";
		l1.expiryDate = "Sample1";
		l1.usageType = "Sample1";
		l1.material = "Sample1";
		l1.brightnessLevel = 11.0;
		l1.isWaterproof = false;
		l1.countryOfOrigin = "Sample1";
		l1.warrantyMonths = 101;
		l1.packagingType = "Sample1";
		l1.weight = 11.0;
		l1.isShockResistant = false;
		l1.feature1 = "Sample1";
		l1.feature2 = "Sample1";
		l1.feature3 = "Sample1";
		l1.isPortable = false;
		l1.isEnergySaving = false;
		l1.rating = 101;

		System.out.println("----- Lantern 1 -----");
		System.out.println("productId: " + l1.productId);
		System.out.println("brandName: " + l1.brandName);
		System.out.println("lightType: " + l1.lightType);
		System.out.println("color: " + l1.color);
		System.out.println("batteryCapacity: " + l1.batteryCapacity);
		System.out.println("price: " + l1.price);
		System.out.println("isRechargeable: " + l1.isRechargeable);
		System.out.println("isAvailable: " + l1.isAvailable);
		System.out.println("manufacturingDate: " + l1.manufacturingDate);
		System.out.println("expiryDate: " + l1.expiryDate);
		System.out.println("usageType: " + l1.usageType);
		System.out.println("material: " + l1.material);
		System.out.println("brightnessLevel: " + l1.brightnessLevel);
		System.out.println("isWaterproof: " + l1.isWaterproof);
		System.out.println("countryOfOrigin: " + l1.countryOfOrigin);
		System.out.println("warrantyMonths: " + l1.warrantyMonths);
		System.out.println("packagingType: " + l1.packagingType);
		System.out.println("weight: " + l1.weight);
		System.out.println("isShockResistant: " + l1.isShockResistant);
		System.out.println("feature1: " + l1.feature1);
		System.out.println("feature2: " + l1.feature2);
		System.out.println("feature3: " + l1.feature3);
		System.out.println("isPortable: " + l1.isPortable);
		System.out.println("isEnergySaving: " + l1.isEnergySaving);
		System.out.println("rating: " + l1.rating);


		Lantern l2 = new Lantern();
		l2.productId = 102;
		l2.brandName = "Sample2";
		l2.lightType = "Sample2";
		l2.color = "Sample2";
		l2.batteryCapacity = 12.0;
		l2.price = 12.0;
		l2.isRechargeable = true;
		l2.isAvailable = true;
		l2.manufacturingDate = "Sample2";
		l2.expiryDate = "Sample2";
		l2.usageType = "Sample2";
		l2.material = "Sample2";
		l2.brightnessLevel = 12.0;
		l2.isWaterproof = true;
		l2.countryOfOrigin = "Sample2";
		l2.warrantyMonths = 102;
		l2.packagingType = "Sample2";
		l2.weight = 12.0;
		l2.isShockResistant = true;
		l2.feature1 = "Sample2";
		l2.feature2 = "Sample2";
		l2.feature3 = "Sample2";
		l2.isPortable = true;
		l2.isEnergySaving = true;
		l2.rating = 102;

		System.out.println("----- Lantern 2 -----");
		System.out.println("productId: " + l2.productId);
		System.out.println("brandName: " + l2.brandName);
		System.out.println("lightType: " + l2.lightType);
		System.out.println("color: " + l2.color);
		System.out.println("batteryCapacity: " + l2.batteryCapacity);
		System.out.println("price: " + l2.price);
		System.out.println("isRechargeable: " + l2.isRechargeable);
		System.out.println("isAvailable: " + l2.isAvailable);
		System.out.println("manufacturingDate: " + l2.manufacturingDate);
		System.out.println("expiryDate: " + l2.expiryDate);
		System.out.println("usageType: " + l2.usageType);
		System.out.println("material: " + l2.material);
		System.out.println("brightnessLevel: " + l2.brightnessLevel);
		System.out.println("isWaterproof: " + l2.isWaterproof);
		System.out.println("countryOfOrigin: " + l2.countryOfOrigin);
		System.out.println("warrantyMonths: " + l2.warrantyMonths);
		System.out.println("packagingType: " + l2.packagingType);
		System.out.println("weight: " + l2.weight);
		System.out.println("isShockResistant: " + l2.isShockResistant);
		System.out.println("feature1: " + l2.feature1);
		System.out.println("feature2: " + l2.feature2);
		System.out.println("feature3: " + l2.feature3);
		System.out.println("isPortable: " + l2.isPortable);
		System.out.println("isEnergySaving: " + l2.isEnergySaving);
		System.out.println("rating: " + l2.rating);


		Lantern l3 = new Lantern();
		l3.productId = 103;
		l3.brandName = "Sample3";
		l3.lightType = "Sample3";
		l3.color = "Sample3";
		l3.batteryCapacity = 13.0;
		l3.price = 13.0;
		l3.isRechargeable = false;
		l3.isAvailable = false;
		l3.manufacturingDate = "Sample3";
		l3.expiryDate = "Sample3";
		l3.usageType = "Sample3";
		l3.material = "Sample3";
		l3.brightnessLevel = 13.0;
		l3.isWaterproof = false;
		l3.countryOfOrigin = "Sample3";
		l3.warrantyMonths = 103;
		l3.packagingType = "Sample3";
		l3.weight = 13.0;
		l3.isShockResistant = false;
		l3.feature1 = "Sample3";
		l3.feature2 = "Sample3";
		l3.feature3 = "Sample3";
		l3.isPortable = false;
		l3.isEnergySaving = false;
		l3.rating = 103;

		System.out.println("----- Lantern 3 -----");
		System.out.println("productId: " + l3.productId);
		System.out.println("brandName: " + l3.brandName);
		System.out.println("lightType: " + l3.lightType);
		System.out.println("color: " + l3.color);
		System.out.println("batteryCapacity: " + l3.batteryCapacity);
		System.out.println("price: " + l3.price);
		System.out.println("isRechargeable: " + l3.isRechargeable);
		System.out.println("isAvailable: " + l3.isAvailable);
		System.out.println("manufacturingDate: " + l3.manufacturingDate);
		System.out.println("expiryDate: " + l3.expiryDate);
		System.out.println("usageType: " + l3.usageType);
		System.out.println("material: " + l3.material);
		System.out.println("brightnessLevel: " + l3.brightnessLevel);
		System.out.println("isWaterproof: " + l3.isWaterproof);
		System.out.println("countryOfOrigin: " + l3.countryOfOrigin);
		System.out.println("warrantyMonths: " + l3.warrantyMonths);
		System.out.println("packagingType: " + l3.packagingType);
		System.out.println("weight: " + l3.weight);
		System.out.println("isShockResistant: " + l3.isShockResistant);
		System.out.println("feature1: " + l3.feature1);
		System.out.println("feature2: " + l3.feature2);
		System.out.println("feature3: " + l3.feature3);
		System.out.println("isPortable: " + l3.isPortable);
		System.out.println("isEnergySaving: " + l3.isEnergySaving);
		System.out.println("rating: " + l3.rating);


		Lantern l4 = new Lantern();
		l4.productId = 104;
		l4.brandName = "Sample4";
		l4.lightType = "Sample4";
		l4.color = "Sample4";
		l4.batteryCapacity = 14.0;
		l4.price = 14.0;
		l4.isRechargeable = true;
		l4.isAvailable = true;
		l4.manufacturingDate = "Sample4";
		l4.expiryDate = "Sample4";
		l4.usageType = "Sample4";
		l4.material = "Sample4";
		l4.brightnessLevel = 14.0;
		l4.isWaterproof = true;
		l4.countryOfOrigin = "Sample4";
		l4.warrantyMonths = 104;
		l4.packagingType = "Sample4";
		l4.weight = 14.0;
		l4.isShockResistant = true;
		l4.feature1 = "Sample4";
		l4.feature2 = "Sample4";
		l4.feature3 = "Sample4";
		l4.isPortable = true;
		l4.isEnergySaving = true;
		l4.rating = 104;

		System.out.println("----- Lantern 4 -----");
		System.out.println("productId: " + l4.productId);
		System.out.println("brandName: " + l4.brandName);
		System.out.println("lightType: " + l4.lightType);
		System.out.println("color: " + l4.color);
		System.out.println("batteryCapacity: " + l4.batteryCapacity);
		System.out.println("price: " + l4.price);
		System.out.println("isRechargeable: " + l4.isRechargeable);
		System.out.println("isAvailable: " + l4.isAvailable);
		System.out.println("manufacturingDate: " + l4.manufacturingDate);
		System.out.println("expiryDate: " + l4.expiryDate);
		System.out.println("usageType: " + l4.usageType);
		System.out.println("material: " + l4.material);
		System.out.println("brightnessLevel: " + l4.brightnessLevel);
		System.out.println("isWaterproof: " + l4.isWaterproof);
		System.out.println("countryOfOrigin: " + l4.countryOfOrigin);
		System.out.println("warrantyMonths: " + l4.warrantyMonths);
		System.out.println("packagingType: " + l4.packagingType);
		System.out.println("weight: " + l4.weight);
		System.out.println("isShockResistant: " + l4.isShockResistant);
		System.out.println("feature1: " + l4.feature1);
		System.out.println("feature2: " + l4.feature2);
		System.out.println("feature3: " + l4.feature3);
		System.out.println("isPortable: " + l4.isPortable);
		System.out.println("isEnergySaving: " + l4.isEnergySaving);
		System.out.println("rating: " + l4.rating);


		Lantern l5 = new Lantern();
		l5.productId = 105;
		l5.brandName = "Sample5";
		l5.lightType = "Sample5";
		l5.color = "Sample5";
		l5.batteryCapacity = 15.0;
		l5.price = 15.0;
		l5.isRechargeable = false;
		l5.isAvailable = false;
		l5.manufacturingDate = "Sample5";
		l5.expiryDate = "Sample5";
		l5.usageType = "Sample5";
		l5.material = "Sample5";
		l5.brightnessLevel = 15.0;
		l5.isWaterproof = false;
		l5.countryOfOrigin = "Sample5";
		l5.warrantyMonths = 105;
		l5.packagingType = "Sample5";
		l5.weight = 15.0;
		l5.isShockResistant = false;
		l5.feature1 = "Sample5";
		l5.feature2 = "Sample5";
		l5.feature3 = "Sample5";
		l5.isPortable = false;
		l5.isEnergySaving = false;
		l5.rating = 105;

		System.out.println("----- Lantern 5 -----");
		System.out.println("productId: " + l5.productId);
		System.out.println("brandName: " + l5.brandName);
		System.out.println("lightType: " + l5.lightType);
		System.out.println("color: " + l5.color);
		System.out.println("batteryCapacity: " + l5.batteryCapacity);
		System.out.println("price: " + l5.price);
		System.out.println("isRechargeable: " + l5.isRechargeable);
		System.out.println("isAvailable: " + l5.isAvailable);
		System.out.println("manufacturingDate: " + l5.manufacturingDate);
		System.out.println("expiryDate: " + l5.expiryDate);
		System.out.println("usageType: " + l5.usageType);
		System.out.println("material: " + l5.material);
		System.out.println("brightnessLevel: " + l5.brightnessLevel);
		System.out.println("isWaterproof: " + l5.isWaterproof);
		System.out.println("countryOfOrigin: " + l5.countryOfOrigin);
		System.out.println("warrantyMonths: " + l5.warrantyMonths);
		System.out.println("packagingType: " + l5.packagingType);
		System.out.println("weight: " + l5.weight);
		System.out.println("isShockResistant: " + l5.isShockResistant);
		System.out.println("feature1: " + l5.feature1);
		System.out.println("feature2: " + l5.feature2);
		System.out.println("feature3: " + l5.feature3);
		System.out.println("isPortable: " + l5.isPortable);
		System.out.println("isEnergySaving: " + l5.isEnergySaving);
		System.out.println("rating: " + l5.rating);


		Lantern l6 = new Lantern();
		l6.productId = 106;
		l6.brandName = "Sample6";
		l6.lightType = "Sample6";
		l6.color = "Sample6";
		l6.batteryCapacity = 16.0;
		l6.price = 16.0;
		l6.isRechargeable = true;
		l6.isAvailable = true;
		l6.manufacturingDate = "Sample6";
		l6.expiryDate = "Sample6";
		l6.usageType = "Sample6";
		l6.material = "Sample6";
		l6.brightnessLevel = 16.0;
		l6.isWaterproof = true;
		l6.countryOfOrigin = "Sample6";
		l6.warrantyMonths = 106;
		l6.packagingType = "Sample6";
		l6.weight = 16.0;
		l6.isShockResistant = true;
		l6.feature1 = "Sample6";
		l6.feature2 = "Sample6";
		l6.feature3 = "Sample6";
		l6.isPortable = true;
		l6.isEnergySaving = true;
		l6.rating = 106;

		System.out.println("----- Lantern 6 -----");
		System.out.println("productId: " + l6.productId);
		System.out.println("brandName: " + l6.brandName);
		System.out.println("lightType: " + l6.lightType);
		System.out.println("color: " + l6.color);
		System.out.println("batteryCapacity: " + l6.batteryCapacity);
		System.out.println("price: " + l6.price);
		System.out.println("isRechargeable: " + l6.isRechargeable);
		System.out.println("isAvailable: " + l6.isAvailable);
		System.out.println("manufacturingDate: " + l6.manufacturingDate);
		System.out.println("expiryDate: " + l6.expiryDate);
		System.out.println("usageType: " + l6.usageType);
		System.out.println("material: " + l6.material);
		System.out.println("brightnessLevel: " + l6.brightnessLevel);
		System.out.println("isWaterproof: " + l6.isWaterproof);
		System.out.println("countryOfOrigin: " + l6.countryOfOrigin);
		System.out.println("warrantyMonths: " + l6.warrantyMonths);
		System.out.println("packagingType: " + l6.packagingType);
		System.out.println("weight: " + l6.weight);
		System.out.println("isShockResistant: " + l6.isShockResistant);
		System.out.println("feature1: " + l6.feature1);
		System.out.println("feature2: " + l6.feature2);
		System.out.println("feature3: " + l6.feature3);
		System.out.println("isPortable: " + l6.isPortable);
		System.out.println("isEnergySaving: " + l6.isEnergySaving);
		System.out.println("rating: " + l6.rating);


		Lantern l7 = new Lantern();
		l7.productId = 107;
		l7.brandName = "Sample7";
		l7.lightType = "Sample7";
		l7.color = "Sample7";
		l7.batteryCapacity = 17.0;
		l7.price = 17.0;
		l7.isRechargeable = false;
		l7.isAvailable = false;
		l7.manufacturingDate = "Sample7";
		l7.expiryDate = "Sample7";
		l7.usageType = "Sample7";
		l7.material = "Sample7";
		l7.brightnessLevel = 17.0;
		l7.isWaterproof = false;
		l7.countryOfOrigin = "Sample7";
		l7.warrantyMonths = 107;
		l7.packagingType = "Sample7";
		l7.weight = 17.0;
		l7.isShockResistant = false;
		l7.feature1 = "Sample7";
		l7.feature2 = "Sample7";
		l7.feature3 = "Sample7";
		l7.isPortable = false;
		l7.isEnergySaving = false;
		l7.rating = 107;

		System.out.println("----- Lantern 7 -----");
		System.out.println("productId: " + l7.productId);
		System.out.println("brandName: " + l7.brandName);
		System.out.println("lightType: " + l7.lightType);
		System.out.println("color: " + l7.color);
		System.out.println("batteryCapacity: " + l7.batteryCapacity);
		System.out.println("price: " + l7.price);
		System.out.println("isRechargeable: " + l7.isRechargeable);
		System.out.println("isAvailable: " + l7.isAvailable);
		System.out.println("manufacturingDate: " + l7.manufacturingDate);
		System.out.println("expiryDate: " + l7.expiryDate);
		System.out.println("usageType: " + l7.usageType);
		System.out.println("material: " + l7.material);
		System.out.println("brightnessLevel: " + l7.brightnessLevel);
		System.out.println("isWaterproof: " + l7.isWaterproof);
		System.out.println("countryOfOrigin: " + l7.countryOfOrigin);
		System.out.println("warrantyMonths: " + l7.warrantyMonths);
		System.out.println("packagingType: " + l7.packagingType);
		System.out.println("weight: " + l7.weight);
		System.out.println("isShockResistant: " + l7.isShockResistant);
		System.out.println("feature1: " + l7.feature1);
		System.out.println("feature2: " + l7.feature2);
		System.out.println("feature3: " + l7.feature3);
		System.out.println("isPortable: " + l7.isPortable);
		System.out.println("isEnergySaving: " + l7.isEnergySaving);
		System.out.println("rating: " + l7.rating);


		Lantern l8 = new Lantern();
		l8.productId = 108;
		l8.brandName = "Sample8";
		l8.lightType = "Sample8";
		l8.color = "Sample8";
		l8.batteryCapacity = 18.0;
		l8.price = 18.0;
		l8.isRechargeable = true;
		l8.isAvailable = true;
		l8.manufacturingDate = "Sample8";
		l8.expiryDate = "Sample8";
		l8.usageType = "Sample8";
		l8.material = "Sample8";
		l8.brightnessLevel = 18.0;
		l8.isWaterproof = true;
		l8.countryOfOrigin = "Sample8";
		l8.warrantyMonths = 108;
		l8.packagingType = "Sample8";
		l8.weight = 18.0;
		l8.isShockResistant = true;
		l8.feature1 = "Sample8";
		l8.feature2 = "Sample8";
		l8.feature3 = "Sample8";
		l8.isPortable = true;
		l8.isEnergySaving = true;
		l8.rating = 108;

		System.out.println("----- Lantern 8 -----");
		System.out.println("productId: " + l8.productId);
		System.out.println("brandName: " + l8.brandName);
		System.out.println("lightType: " + l8.lightType);
		System.out.println("color: " + l8.color);
		System.out.println("batteryCapacity: " + l8.batteryCapacity);
		System.out.println("price: " + l8.price);
		System.out.println("isRechargeable: " + l8.isRechargeable);
		System.out.println("isAvailable: " + l8.isAvailable);
		System.out.println("manufacturingDate: " + l8.manufacturingDate);
		System.out.println("expiryDate: " + l8.expiryDate);
		System.out.println("usageType: " + l8.usageType);
		System.out.println("material: " + l8.material);
		System.out.println("brightnessLevel: " + l8.brightnessLevel);
		System.out.println("isWaterproof: " + l8.isWaterproof);
		System.out.println("countryOfOrigin: " + l8.countryOfOrigin);
		System.out.println("warrantyMonths: " + l8.warrantyMonths);
		System.out.println("packagingType: " + l8.packagingType);
		System.out.println("weight: " + l8.weight);
		System.out.println("isShockResistant: " + l8.isShockResistant);
		System.out.println("feature1: " + l8.feature1);
		System.out.println("feature2: " + l8.feature2);
		System.out.println("feature3: " + l8.feature3);
		System.out.println("isPortable: " + l8.isPortable);
		System.out.println("isEnergySaving: " + l8.isEnergySaving);
		System.out.println("rating: " + l8.rating);


		Lantern l9 = new Lantern();
		l9.productId = 109;
		l9.brandName = "Sample9";
		l9.lightType = "Sample9";
		l9.color = "Sample9";
		l9.batteryCapacity = 19.0;
		l9.price = 19.0;
		l9.isRechargeable = false;
		l9.isAvailable = false;
		l9.manufacturingDate = "Sample9";
		l9.expiryDate = "Sample9";
		l9.usageType = "Sample9";
		l9.material = "Sample9";
		l9.brightnessLevel = 19.0;
		l9.isWaterproof = false;
		l9.countryOfOrigin = "Sample9";
		l9.warrantyMonths = 109;
		l9.packagingType = "Sample9";
		l9.weight = 19.0;
		l9.isShockResistant = false;
		l9.feature1 = "Sample9";
		l9.feature2 = "Sample9";
		l9.feature3 = "Sample9";
		l9.isPortable = false;
		l9.isEnergySaving = false;
		l9.rating = 109;

		System.out.println("----- Lantern 9 -----");
		System.out.println("productId: " + l9.productId);
		System.out.println("brandName: " + l9.brandName);
		System.out.println("lightType: " + l9.lightType);
		System.out.println("color: " + l9.color);
		System.out.println("batteryCapacity: " + l9.batteryCapacity);
		System.out.println("price: " + l9.price);
		System.out.println("isRechargeable: " + l9.isRechargeable);
		System.out.println("isAvailable: " + l9.isAvailable);
		System.out.println("manufacturingDate: " + l9.manufacturingDate);
		System.out.println("expiryDate: " + l9.expiryDate);
		System.out.println("usageType: " + l9.usageType);
		System.out.println("material: " + l9.material);
		System.out.println("brightnessLevel: " + l9.brightnessLevel);
		System.out.println("isWaterproof: " + l9.isWaterproof);
		System.out.println("countryOfOrigin: " + l9.countryOfOrigin);
		System.out.println("warrantyMonths: " + l9.warrantyMonths);
		System.out.println("packagingType: " + l9.packagingType);
		System.out.println("weight: " + l9.weight);
		System.out.println("isShockResistant: " + l9.isShockResistant);
		System.out.println("feature1: " + l9.feature1);
		System.out.println("feature2: " + l9.feature2);
		System.out.println("feature3: " + l9.feature3);
		System.out.println("isPortable: " + l9.isPortable);
		System.out.println("isEnergySaving: " + l9.isEnergySaving);
		System.out.println("rating: " + l9.rating);


		Lantern l10 = new Lantern();
		l10.productId = 110;
		l10.brandName = "Sample10";
		l10.lightType = "Sample10";
		l10.color = "Sample10";
		l10.batteryCapacity = 20.0;
		l10.price = 20.0;
		l10.isRechargeable = true;
		l10.isAvailable = true;
		l10.manufacturingDate = "Sample10";
		l10.expiryDate = "Sample10";
		l10.usageType = "Sample10";
		l10.material = "Sample10";
		l10.brightnessLevel = 20.0;
		l10.isWaterproof = true;
		l10.countryOfOrigin = "Sample10";
		l10.warrantyMonths = 110;
		l10.packagingType = "Sample10";
		l10.weight = 20.0;
		l10.isShockResistant = true;
		l10.feature1 = "Sample10";
		l10.feature2 = "Sample10";
		l10.feature3 = "Sample10";
		l10.isPortable = true;
		l10.isEnergySaving = true;
		l10.rating = 110;

		System.out.println("----- Lantern 10 -----");
		System.out.println("productId: " + l10.productId);
		System.out.println("brandName: " + l10.brandName);
		System.out.println("lightType: " + l10.lightType);
		System.out.println("color: " + l10.color);
		System.out.println("batteryCapacity: " + l10.batteryCapacity);
		System.out.println("price: " + l10.price);
		System.out.println("isRechargeable: " + l10.isRechargeable);
		System.out.println("isAvailable: " + l10.isAvailable);
		System.out.println("manufacturingDate: " + l10.manufacturingDate);
		System.out.println("expiryDate: " + l10.expiryDate);
		System.out.println("usageType: " + l10.usageType);
		System.out.println("material: " + l10.material);
		System.out.println("brightnessLevel: " + l10.brightnessLevel);
		System.out.println("isWaterproof: " + l10.isWaterproof);
		System.out.println("countryOfOrigin: " + l10.countryOfOrigin);
		System.out.println("warrantyMonths: " + l10.warrantyMonths);
		System.out.println("packagingType: " + l10.packagingType);
		System.out.println("weight: " + l10.weight);
		System.out.println("isShockResistant: " + l10.isShockResistant);
		System.out.println("feature1: " + l10.feature1);
		System.out.println("feature2: " + l10.feature2);
		System.out.println("feature3: " + l10.feature3);
		System.out.println("isPortable: " + l10.isPortable);
		System.out.println("isEnergySaving: " + l10.isEnergySaving);
		System.out.println("rating: " + l10.rating);


		Lantern l11 = new Lantern();
		l11.productId = 111;
		l11.brandName = "Sample11";
		l11.lightType = "Sample11";
		l11.color = "Sample11";
		l11.batteryCapacity = 21.0;
		l11.price = 21.0;
		l11.isRechargeable = false;
		l11.isAvailable = false;
		l11.manufacturingDate = "Sample11";
		l11.expiryDate = "Sample11";
		l11.usageType = "Sample11";
		l11.material = "Sample11";
		l11.brightnessLevel = 21.0;
		l11.isWaterproof = false;
		l11.countryOfOrigin = "Sample11";
		l11.warrantyMonths = 111;
		l11.packagingType = "Sample11";
		l11.weight = 21.0;
		l11.isShockResistant = false;
		l11.feature1 = "Sample11";
		l11.feature2 = "Sample11";
		l11.feature3 = "Sample11";
		l11.isPortable = false;
		l11.isEnergySaving = false;
		l11.rating = 111;

		System.out.println("----- Lantern 11 -----");
		System.out.println("productId: " + l11.productId);
		System.out.println("brandName: " + l11.brandName);
		System.out.println("lightType: " + l11.lightType);
		System.out.println("color: " + l11.color);
		System.out.println("batteryCapacity: " + l11.batteryCapacity);
		System.out.println("price: " + l11.price);
		System.out.println("isRechargeable: " + l11.isRechargeable);
		System.out.println("isAvailable: " + l11.isAvailable);
		System.out.println("manufacturingDate: " + l11.manufacturingDate);
		System.out.println("expiryDate: " + l11.expiryDate);
		System.out.println("usageType: " + l11.usageType);
		System.out.println("material: " + l11.material);
		System.out.println("brightnessLevel: " + l11.brightnessLevel);
		System.out.println("isWaterproof: " + l11.isWaterproof);
		System.out.println("countryOfOrigin: " + l11.countryOfOrigin);
		System.out.println("warrantyMonths: " + l11.warrantyMonths);
		System.out.println("packagingType: " + l11.packagingType);
		System.out.println("weight: " + l11.weight);
		System.out.println("isShockResistant: " + l11.isShockResistant);
		System.out.println("feature1: " + l11.feature1);
		System.out.println("feature2: " + l11.feature2);
		System.out.println("feature3: " + l11.feature3);
		System.out.println("isPortable: " + l11.isPortable);
		System.out.println("isEnergySaving: " + l11.isEnergySaving);
		System.out.println("rating: " + l11.rating);


		Lantern l12 = new Lantern();
		l12.productId = 112;
		l12.brandName = "Sample12";
		l12.lightType = "Sample12";
		l12.color = "Sample12";
		l12.batteryCapacity = 22.0;
		l12.price = 22.0;
		l12.isRechargeable = true;
		l12.isAvailable = true;
		l12.manufacturingDate = "Sample12";
		l12.expiryDate = "Sample12";
		l12.usageType = "Sample12";
		l12.material = "Sample12";
		l12.brightnessLevel = 22.0;
		l12.isWaterproof = true;
		l12.countryOfOrigin = "Sample12";
		l12.warrantyMonths = 112;
		l12.packagingType = "Sample12";
		l12.weight = 22.0;
		l12.isShockResistant = true;
		l12.feature1 = "Sample12";
		l12.feature2 = "Sample12";
		l12.feature3 = "Sample12";
		l12.isPortable = true;
		l12.isEnergySaving = true;
		l12.rating = 112;

		System.out.println("----- Lantern 12 -----");
		System.out.println("productId: " + l12.productId);
		System.out.println("brandName: " + l12.brandName);
		System.out.println("lightType: " + l12.lightType);
		System.out.println("color: " + l12.color);
		System.out.println("batteryCapacity: " + l12.batteryCapacity);
		System.out.println("price: " + l12.price);
		System.out.println("isRechargeable: " + l12.isRechargeable);
		System.out.println("isAvailable: " + l12.isAvailable);
		System.out.println("manufacturingDate: " + l12.manufacturingDate);
		System.out.println("expiryDate: " + l12.expiryDate);
		System.out.println("usageType: " + l12.usageType);
		System.out.println("material: " + l12.material);
		System.out.println("brightnessLevel: " + l12.brightnessLevel);
		System.out.println("isWaterproof: " + l12.isWaterproof);
		System.out.println("countryOfOrigin: " + l12.countryOfOrigin);
		System.out.println("warrantyMonths: " + l12.warrantyMonths);
		System.out.println("packagingType: " + l12.packagingType);
		System.out.println("weight: " + l12.weight);
		System.out.println("isShockResistant: " + l12.isShockResistant);
		System.out.println("feature1: " + l12.feature1);
		System.out.println("feature2: " + l12.feature2);
		System.out.println("feature3: " + l12.feature3);
		System.out.println("isPortable: " + l12.isPortable);
		System.out.println("isEnergySaving: " + l12.isEnergySaving);
		System.out.println("rating: " + l12.rating);


		Lantern l13 = new Lantern();
		l13.productId = 113;
		l13.brandName = "Sample13";
		l13.lightType = "Sample13";
		l13.color = "Sample13";
		l13.batteryCapacity = 23.0;
		l13.price = 23.0;
		l13.isRechargeable = false;
		l13.isAvailable = false;
		l13.manufacturingDate = "Sample13";
		l13.expiryDate = "Sample13";
		l13.usageType = "Sample13";
		l13.material = "Sample13";
		l13.brightnessLevel = 23.0;
		l13.isWaterproof = false;
		l13.countryOfOrigin = "Sample13";
		l13.warrantyMonths = 113;
		l13.packagingType = "Sample13";
		l13.weight = 23.0;
		l13.isShockResistant = false;
		l13.feature1 = "Sample13";
		l13.feature2 = "Sample13";
		l13.feature3 = "Sample13";
		l13.isPortable = false;
		l13.isEnergySaving = false;
		l13.rating = 113;

		System.out.println("----- Lantern 13 -----");
		System.out.println("productId: " + l13.productId);
		System.out.println("brandName: " + l13.brandName);
		System.out.println("lightType: " + l13.lightType);
		System.out.println("color: " + l13.color);
		System.out.println("batteryCapacity: " + l13.batteryCapacity);
		System.out.println("price: " + l13.price);
		System.out.println("isRechargeable: " + l13.isRechargeable);
		System.out.println("isAvailable: " + l13.isAvailable);
		System.out.println("manufacturingDate: " + l13.manufacturingDate);
		System.out.println("expiryDate: " + l13.expiryDate);
		System.out.println("usageType: " + l13.usageType);
		System.out.println("material: " + l13.material);
		System.out.println("brightnessLevel: " + l13.brightnessLevel);
		System.out.println("isWaterproof: " + l13.isWaterproof);
		System.out.println("countryOfOrigin: " + l13.countryOfOrigin);
		System.out.println("warrantyMonths: " + l13.warrantyMonths);
		System.out.println("packagingType: " + l13.packagingType);
		System.out.println("weight: " + l13.weight);
		System.out.println("isShockResistant: " + l13.isShockResistant);
		System.out.println("feature1: " + l13.feature1);
		System.out.println("feature2: " + l13.feature2);
		System.out.println("feature3: " + l13.feature3);
		System.out.println("isPortable: " + l13.isPortable);
		System.out.println("isEnergySaving: " + l13.isEnergySaving);
		System.out.println("rating: " + l13.rating);


		Lantern l14 = new Lantern();
		l14.productId = 114;
		l14.brandName = "Sample14";
		l14.lightType = "Sample14";
		l14.color = "Sample14";
		l14.batteryCapacity = 24.0;
		l14.price = 24.0;
		l14.isRechargeable = true;
		l14.isAvailable = true;
		l14.manufacturingDate = "Sample14";
		l14.expiryDate = "Sample14";
		l14.usageType = "Sample14";
		l14.material = "Sample14";
		l14.brightnessLevel = 24.0;
		l14.isWaterproof = true;
		l14.countryOfOrigin = "Sample14";
		l14.warrantyMonths = 114;
		l14.packagingType = "Sample14";
		l14.weight = 24.0;
		l14.isShockResistant = true;
		l14.feature1 = "Sample14";
		l14.feature2 = "Sample14";
		l14.feature3 = "Sample14";
		l14.isPortable = true;
		l14.isEnergySaving = true;
		l14.rating = 114;

		System.out.println("----- Lantern 14 -----");
		System.out.println("productId: " + l14.productId);
		System.out.println("brandName: " + l14.brandName);
		System.out.println("lightType: " + l14.lightType);
		System.out.println("color: " + l14.color);
		System.out.println("batteryCapacity: " + l14.batteryCapacity);
		System.out.println("price: " + l14.price);
		System.out.println("isRechargeable: " + l14.isRechargeable);
		System.out.println("isAvailable: " + l14.isAvailable);
		System.out.println("manufacturingDate: " + l14.manufacturingDate);
		System.out.println("expiryDate: " + l14.expiryDate);
		System.out.println("usageType: " + l14.usageType);
		System.out.println("material: " + l14.material);
		System.out.println("brightnessLevel: " + l14.brightnessLevel);
		System.out.println("isWaterproof: " + l14.isWaterproof);
		System.out.println("countryOfOrigin: " + l14.countryOfOrigin);
		System.out.println("warrantyMonths: " + l14.warrantyMonths);
		System.out.println("packagingType: " + l14.packagingType);
		System.out.println("weight: " + l14.weight);
		System.out.println("isShockResistant: " + l14.isShockResistant);
		System.out.println("feature1: " + l14.feature1);
		System.out.println("feature2: " + l14.feature2);
		System.out.println("feature3: " + l14.feature3);
		System.out.println("isPortable: " + l14.isPortable);
		System.out.println("isEnergySaving: " + l14.isEnergySaving);
		System.out.println("rating: " + l14.rating);


		Lantern l15 = new Lantern();
		l15.productId = 115;
		l15.brandName = "Sample15";
		l15.lightType = "Sample15";
		l15.color = "Sample15";
		l15.batteryCapacity = 25.0;
		l15.price = 25.0;
		l15.isRechargeable = false;
		l15.isAvailable = false;
		l15.manufacturingDate = "Sample15";
		l15.expiryDate = "Sample15";
		l15.usageType = "Sample15";
		l15.material = "Sample15";
		l15.brightnessLevel = 25.0;
		l15.isWaterproof = false;
		l15.countryOfOrigin = "Sample15";
		l15.warrantyMonths = 115;
		l15.packagingType = "Sample15";
		l15.weight = 25.0;
		l15.isShockResistant = false;
		l15.feature1 = "Sample15";
		l15.feature2 = "Sample15";
		l15.feature3 = "Sample15";
		l15.isPortable = false;
		l15.isEnergySaving = false;
		l15.rating = 115;

		System.out.println("----- Lantern 15 -----");
		System.out.println("productId: " + l15.productId);
		System.out.println("brandName: " + l15.brandName);
		System.out.println("lightType: " + l15.lightType);
		System.out.println("color: " + l15.color);
		System.out.println("batteryCapacity: " + l15.batteryCapacity);
		System.out.println("price: " + l15.price);
		System.out.println("isRechargeable: " + l15.isRechargeable);
		System.out.println("isAvailable: " + l15.isAvailable);
		System.out.println("manufacturingDate: " + l15.manufacturingDate);
		System.out.println("expiryDate: " + l15.expiryDate);
		System.out.println("usageType: " + l15.usageType);
		System.out.println("material: " + l15.material);
		System.out.println("brightnessLevel: " + l15.brightnessLevel);
		System.out.println("isWaterproof: " + l15.isWaterproof);
		System.out.println("countryOfOrigin: " + l15.countryOfOrigin);
		System.out.println("warrantyMonths: " + l15.warrantyMonths);
		System.out.println("packagingType: " + l15.packagingType);
		System.out.println("weight: " + l15.weight);
		System.out.println("isShockResistant: " + l15.isShockResistant);
		System.out.println("feature1: " + l15.feature1);
		System.out.println("feature2: " + l15.feature2);
		System.out.println("feature3: " + l15.feature3);
		System.out.println("isPortable: " + l15.isPortable);
		System.out.println("isEnergySaving: " + l15.isEnergySaving);
		System.out.println("rating: " + l15.rating);


		Lantern l16 = new Lantern();
		l16.productId = 116;
		l16.brandName = "Sample16";
		l16.lightType = "Sample16";
		l16.color = "Sample16";
		l16.batteryCapacity = 26.0;
		l16.price = 26.0;
		l16.isRechargeable = true;
		l16.isAvailable = true;
		l16.manufacturingDate = "Sample16";
		l16.expiryDate = "Sample16";
		l16.usageType = "Sample16";
		l16.material = "Sample16";
		l16.brightnessLevel = 26.0;
		l16.isWaterproof = true;
		l16.countryOfOrigin = "Sample16";
		l16.warrantyMonths = 116;
		l16.packagingType = "Sample16";
		l16.weight = 26.0;
		l16.isShockResistant = true;
		l16.feature1 = "Sample16";
		l16.feature2 = "Sample16";
		l16.feature3 = "Sample16";
		l16.isPortable = true;
		l16.isEnergySaving = true;
		l16.rating = 116;

		System.out.println("----- Lantern 16 -----");
		System.out.println("productId: " + l16.productId);
		System.out.println("brandName: " + l16.brandName);
		System.out.println("lightType: " + l16.lightType);
		System.out.println("color: " + l16.color);
		System.out.println("batteryCapacity: " + l16.batteryCapacity);
		System.out.println("price: " + l16.price);
		System.out.println("isRechargeable: " + l16.isRechargeable);
		System.out.println("isAvailable: " + l16.isAvailable);
		System.out.println("manufacturingDate: " + l16.manufacturingDate);
		System.out.println("expiryDate: " + l16.expiryDate);
		System.out.println("usageType: " + l16.usageType);
		System.out.println("material: " + l16.material);
		System.out.println("brightnessLevel: " + l16.brightnessLevel);
		System.out.println("isWaterproof: " + l16.isWaterproof);
		System.out.println("countryOfOrigin: " + l16.countryOfOrigin);
		System.out.println("warrantyMonths: " + l16.warrantyMonths);
		System.out.println("packagingType: " + l16.packagingType);
		System.out.println("weight: " + l16.weight);
		System.out.println("isShockResistant: " + l16.isShockResistant);
		System.out.println("feature1: " + l16.feature1);
		System.out.println("feature2: " + l16.feature2);
		System.out.println("feature3: " + l16.feature3);
		System.out.println("isPortable: " + l16.isPortable);
		System.out.println("isEnergySaving: " + l16.isEnergySaving);
		System.out.println("rating: " + l16.rating);


		Lantern l17 = new Lantern();
		l17.productId = 117;
		l17.brandName = "Sample17";
		l17.lightType = "Sample17";
		l17.color = "Sample17";
		l17.batteryCapacity = 27.0;
		l17.price = 27.0;
		l17.isRechargeable = false;
		l17.isAvailable = false;
		l17.manufacturingDate = "Sample17";
		l17.expiryDate = "Sample17";
		l17.usageType = "Sample17";
		l17.material = "Sample17";
		l17.brightnessLevel = 27.0;
		l17.isWaterproof = false;
		l17.countryOfOrigin = "Sample17";
		l17.warrantyMonths = 117;
		l17.packagingType = "Sample17";
		l17.weight = 27.0;
		l17.isShockResistant = false;
		l17.feature1 = "Sample17";
		l17.feature2 = "Sample17";
		l17.feature3 = "Sample17";
		l17.isPortable = false;
		l17.isEnergySaving = false;
		l17.rating = 117;

		System.out.println("----- Lantern 17 -----");
		System.out.println("productId: " + l17.productId);
		System.out.println("brandName: " + l17.brandName);
		System.out.println("lightType: " + l17.lightType);
		System.out.println("color: " + l17.color);
		System.out.println("batteryCapacity: " + l17.batteryCapacity);
		System.out.println("price: " + l17.price);
		System.out.println("isRechargeable: " + l17.isRechargeable);
		System.out.println("isAvailable: " + l17.isAvailable);
		System.out.println("manufacturingDate: " + l17.manufacturingDate);
		System.out.println("expiryDate: " + l17.expiryDate);
		System.out.println("usageType: " + l17.usageType);
		System.out.println("material: " + l17.material);
		System.out.println("brightnessLevel: " + l17.brightnessLevel);
		System.out.println("isWaterproof: " + l17.isWaterproof);
		System.out.println("countryOfOrigin: " + l17.countryOfOrigin);
		System.out.println("warrantyMonths: " + l17.warrantyMonths);
		System.out.println("packagingType: " + l17.packagingType);
		System.out.println("weight: " + l17.weight);
		System.out.println("isShockResistant: " + l17.isShockResistant);
		System.out.println("feature1: " + l17.feature1);
		System.out.println("feature2: " + l17.feature2);
		System.out.println("feature3: " + l17.feature3);
		System.out.println("isPortable: " + l17.isPortable);
		System.out.println("isEnergySaving: " + l17.isEnergySaving);
		System.out.println("rating: " + l17.rating);


		Lantern l18 = new Lantern();
		l18.productId = 118;
		l18.brandName = "Sample18";
		l18.lightType = "Sample18";
		l18.color = "Sample18";
		l18.batteryCapacity = 28.0;
		l18.price = 28.0;
		l18.isRechargeable = true;
		l18.isAvailable = true;
		l18.manufacturingDate = "Sample18";
		l18.expiryDate = "Sample18";
		l18.usageType = "Sample18";
		l18.material = "Sample18";
		l18.brightnessLevel = 28.0;
		l18.isWaterproof = true;
		l18.countryOfOrigin = "Sample18";
		l18.warrantyMonths = 118;
		l18.packagingType = "Sample18";
		l18.weight = 28.0;
		l18.isShockResistant = true;
		l18.feature1 = "Sample18";
		l18.feature2 = "Sample18";
		l18.feature3 = "Sample18";
		l18.isPortable = true;
		l18.isEnergySaving = true;
		l18.rating = 118;

		System.out.println("----- Lantern 18 -----");
		System.out.println("productId: " + l18.productId);
		System.out.println("brandName: " + l18.brandName);
		System.out.println("lightType: " + l18.lightType);
		System.out.println("color: " + l18.color);
		System.out.println("batteryCapacity: " + l18.batteryCapacity);
		System.out.println("price: " + l18.price);
		System.out.println("isRechargeable: " + l18.isRechargeable);
		System.out.println("isAvailable: " + l18.isAvailable);
		System.out.println("manufacturingDate: " + l18.manufacturingDate);
		System.out.println("expiryDate: " + l18.expiryDate);
		System.out.println("usageType: " + l18.usageType);
		System.out.println("material: " + l18.material);
		System.out.println("brightnessLevel: " + l18.brightnessLevel);
		System.out.println("isWaterproof: " + l18.isWaterproof);
		System.out.println("countryOfOrigin: " + l18.countryOfOrigin);
		System.out.println("warrantyMonths: " + l18.warrantyMonths);
		System.out.println("packagingType: " + l18.packagingType);
		System.out.println("weight: " + l18.weight);
		System.out.println("isShockResistant: " + l18.isShockResistant);
		System.out.println("feature1: " + l18.feature1);
		System.out.println("feature2: " + l18.feature2);
		System.out.println("feature3: " + l18.feature3);
		System.out.println("isPortable: " + l18.isPortable);
		System.out.println("isEnergySaving: " + l18.isEnergySaving);
		System.out.println("rating: " + l18.rating);


		Lantern l19 = new Lantern();
		l19.productId = 119;
		l19.brandName = "Sample19";
		l19.lightType = "Sample19";
		l19.color = "Sample19";
		l19.batteryCapacity = 29.0;
		l19.price = 29.0;
		l19.isRechargeable = false;
		l19.isAvailable = false;
		l19.manufacturingDate = "Sample19";
		l19.expiryDate = "Sample19";
		l19.usageType = "Sample19";
		l19.material = "Sample19";
		l19.brightnessLevel = 29.0;
		l19.isWaterproof = false;
		l19.countryOfOrigin = "Sample19";
		l19.warrantyMonths = 119;
		l19.packagingType = "Sample19";
		l19.weight = 29.0;
		l19.isShockResistant = false;
		l19.feature1 = "Sample19";
		l19.feature2 = "Sample19";
		l19.feature3 = "Sample19";
		l19.isPortable = false;
		l19.isEnergySaving = false;
		l19.rating = 119;

		System.out.println("----- Lantern 19 -----");
		System.out.println("productId: " + l19.productId);
		System.out.println("brandName: " + l19.brandName);
		System.out.println("lightType: " + l19.lightType);
		System.out.println("color: " + l19.color);
		System.out.println("batteryCapacity: " + l19.batteryCapacity);
		System.out.println("price: " + l19.price);
		System.out.println("isRechargeable: " + l19.isRechargeable);
		System.out.println("isAvailable: " + l19.isAvailable);
		System.out.println("manufacturingDate: " + l19.manufacturingDate);
		System.out.println("expiryDate: " + l19.expiryDate);
		System.out.println("usageType: " + l19.usageType);
		System.out.println("material: " + l19.material);
		System.out.println("brightnessLevel: " + l19.brightnessLevel);
		System.out.println("isWaterproof: " + l19.isWaterproof);
		System.out.println("countryOfOrigin: " + l19.countryOfOrigin);
		System.out.println("warrantyMonths: " + l19.warrantyMonths);
		System.out.println("packagingType: " + l19.packagingType);
		System.out.println("weight: " + l19.weight);
		System.out.println("isShockResistant: " + l19.isShockResistant);
		System.out.println("feature1: " + l19.feature1);
		System.out.println("feature2: " + l19.feature2);
		System.out.println("feature3: " + l19.feature3);
		System.out.println("isPortable: " + l19.isPortable);
		System.out.println("isEnergySaving: " + l19.isEnergySaving);
		System.out.println("rating: " + l19.rating);


		Lantern l20 = new Lantern();
		l20.productId = 120;
		l20.brandName = "Sample20";
		l20.lightType = "Sample20";
		l20.color = "Sample20";
		l20.batteryCapacity = 30.0;
		l20.price = 30.0;
		l20.isRechargeable = true;
		l20.isAvailable = true;
		l20.manufacturingDate = "Sample20";
		l20.expiryDate = "Sample20";
		l20.usageType = "Sample20";
		l20.material = "Sample20";
		l20.brightnessLevel = 30.0;
		l20.isWaterproof = true;
		l20.countryOfOrigin = "Sample20";
		l20.warrantyMonths = 120;
		l20.packagingType = "Sample20";
		l20.weight = 30.0;
		l20.isShockResistant = true;
		l20.feature1 = "Sample20";
		l20.feature2 = "Sample20";
		l20.feature3 = "Sample20";
		l20.isPortable = true;
		l20.isEnergySaving = true;
		l20.rating = 120;

		System.out.println("----- Lantern 20 -----");
		System.out.println("productId: " + l20.productId);
		System.out.println("brandName: " + l20.brandName);
		System.out.println("lightType: " + l20.lightType);
		System.out.println("color: " + l20.color);
		System.out.println("batteryCapacity: " + l20.batteryCapacity);
		System.out.println("price: " + l20.price);
		System.out.println("isRechargeable: " + l20.isRechargeable);
		System.out.println("isAvailable: " + l20.isAvailable);
		System.out.println("manufacturingDate: " + l20.manufacturingDate);
		System.out.println("expiryDate: " + l20.expiryDate);
		System.out.println("usageType: " + l20.usageType);
		System.out.println("material: " + l20.material);
		System.out.println("brightnessLevel: " + l20.brightnessLevel);
		System.out.println("isWaterproof: " + l20.isWaterproof);
		System.out.println("countryOfOrigin: " + l20.countryOfOrigin);
		System.out.println("warrantyMonths: " + l20.warrantyMonths);
		System.out.println("packagingType: " + l20.packagingType);
		System.out.println("weight: " + l20.weight);
		System.out.println("isShockResistant: " + l20.isShockResistant);
		System.out.println("feature1: " + l20.feature1);
		System.out.println("feature2: " + l20.feature2);
		System.out.println("feature3: " + l20.feature3);
		System.out.println("isPortable: " + l20.isPortable);
		System.out.println("isEnergySaving: " + l20.isEnergySaving);
		System.out.println("rating: " + l20.rating);


		Lantern l21 = new Lantern();
		l21.productId = 121;
		l21.brandName = "Sample21";
		l21.lightType = "Sample21";
		l21.color = "Sample21";
		l21.batteryCapacity = 31.0;
		l21.price = 31.0;
		l21.isRechargeable = false;
		l21.isAvailable = false;
		l21.manufacturingDate = "Sample21";
		l21.expiryDate = "Sample21";
		l21.usageType = "Sample21";
		l21.material = "Sample21";
		l21.brightnessLevel = 31.0;
		l21.isWaterproof = false;
		l21.countryOfOrigin = "Sample21";
		l21.warrantyMonths = 121;
		l21.packagingType = "Sample21";
		l21.weight = 31.0;
		l21.isShockResistant = false;
		l21.feature1 = "Sample21";
		l21.feature2 = "Sample21";
		l21.feature3 = "Sample21";
		l21.isPortable = false;
		l21.isEnergySaving = false;
		l21.rating = 121;

		System.out.println("----- Lantern 21 -----");
		System.out.println("productId: " + l21.productId);
		System.out.println("brandName: " + l21.brandName);
		System.out.println("lightType: " + l21.lightType);
		System.out.println("color: " + l21.color);
		System.out.println("batteryCapacity: " + l21.batteryCapacity);
		System.out.println("price: " + l21.price);
		System.out.println("isRechargeable: " + l21.isRechargeable);
		System.out.println("isAvailable: " + l21.isAvailable);
		System.out.println("manufacturingDate: " + l21.manufacturingDate);
		System.out.println("expiryDate: " + l21.expiryDate);
		System.out.println("usageType: " + l21.usageType);
		System.out.println("material: " + l21.material);
		System.out.println("brightnessLevel: " + l21.brightnessLevel);
		System.out.println("isWaterproof: " + l21.isWaterproof);
		System.out.println("countryOfOrigin: " + l21.countryOfOrigin);
		System.out.println("warrantyMonths: " + l21.warrantyMonths);
		System.out.println("packagingType: " + l21.packagingType);
		System.out.println("weight: " + l21.weight);
		System.out.println("isShockResistant: " + l21.isShockResistant);
		System.out.println("feature1: " + l21.feature1);
		System.out.println("feature2: " + l21.feature2);
		System.out.println("feature3: " + l21.feature3);
		System.out.println("isPortable: " + l21.isPortable);
		System.out.println("isEnergySaving: " + l21.isEnergySaving);
		System.out.println("rating: " + l21.rating);


		Lantern l22 = new Lantern();
		l22.productId = 122;
		l22.brandName = "Sample22";
		l22.lightType = "Sample22";
		l22.color = "Sample22";
		l22.batteryCapacity = 32.0;
		l22.price = 32.0;
		l22.isRechargeable = true;
		l22.isAvailable = true;
		l22.manufacturingDate = "Sample22";
		l22.expiryDate = "Sample22";
		l22.usageType = "Sample22";
		l22.material = "Sample22";
		l22.brightnessLevel = 32.0;
		l22.isWaterproof = true;
		l22.countryOfOrigin = "Sample22";
		l22.warrantyMonths = 122;
		l22.packagingType = "Sample22";
		l22.weight = 32.0;
		l22.isShockResistant = true;
		l22.feature1 = "Sample22";
		l22.feature2 = "Sample22";
		l22.feature3 = "Sample22";
		l22.isPortable = true;
		l22.isEnergySaving = true;
		l22.rating = 122;

		System.out.println("----- Lantern 22 -----");
		System.out.println("productId: " + l22.productId);
		System.out.println("brandName: " + l22.brandName);
		System.out.println("lightType: " + l22.lightType);
		System.out.println("color: " + l22.color);
		System.out.println("batteryCapacity: " + l22.batteryCapacity);
		System.out.println("price: " + l22.price);
		System.out.println("isRechargeable: " + l22.isRechargeable);
		System.out.println("isAvailable: " + l22.isAvailable);
		System.out.println("manufacturingDate: " + l22.manufacturingDate);
		System.out.println("expiryDate: " + l22.expiryDate);
		System.out.println("usageType: " + l22.usageType);
		System.out.println("material: " + l22.material);
		System.out.println("brightnessLevel: " + l22.brightnessLevel);
		System.out.println("isWaterproof: " + l22.isWaterproof);
		System.out.println("countryOfOrigin: " + l22.countryOfOrigin);
		System.out.println("warrantyMonths: " + l22.warrantyMonths);
		System.out.println("packagingType: " + l22.packagingType);
		System.out.println("weight: " + l22.weight);
		System.out.println("isShockResistant: " + l22.isShockResistant);
		System.out.println("feature1: " + l22.feature1);
		System.out.println("feature2: " + l22.feature2);
		System.out.println("feature3: " + l22.feature3);
		System.out.println("isPortable: " + l22.isPortable);
		System.out.println("isEnergySaving: " + l22.isEnergySaving);
		System.out.println("rating: " + l22.rating);


		Lantern l23 = new Lantern();
		l23.productId = 123;
		l23.brandName = "Sample23";
		l23.lightType = "Sample23";
		l23.color = "Sample23";
		l23.batteryCapacity = 33.0;
		l23.price = 33.0;
		l23.isRechargeable = false;
		l23.isAvailable = false;
		l23.manufacturingDate = "Sample23";
		l23.expiryDate = "Sample23";
		l23.usageType = "Sample23";
		l23.material = "Sample23";
		l23.brightnessLevel = 33.0;
		l23.isWaterproof = false;
		l23.countryOfOrigin = "Sample23";
		l23.warrantyMonths = 123;
		l23.packagingType = "Sample23";
		l23.weight = 33.0;
		l23.isShockResistant = false;
		l23.feature1 = "Sample23";
		l23.feature2 = "Sample23";
		l23.feature3 = "Sample23";
		l23.isPortable = false;
		l23.isEnergySaving = false;
		l23.rating = 123;

		System.out.println("----- Lantern 23 -----");
		System.out.println("productId: " + l23.productId);
		System.out.println("brandName: " + l23.brandName);
		System.out.println("lightType: " + l23.lightType);
		System.out.println("color: " + l23.color);
		System.out.println("batteryCapacity: " + l23.batteryCapacity);
		System.out.println("price: " + l23.price);
		System.out.println("isRechargeable: " + l23.isRechargeable);
		System.out.println("isAvailable: " + l23.isAvailable);
		System.out.println("manufacturingDate: " + l23.manufacturingDate);
		System.out.println("expiryDate: " + l23.expiryDate);
		System.out.println("usageType: " + l23.usageType);
		System.out.println("material: " + l23.material);
		System.out.println("brightnessLevel: " + l23.brightnessLevel);
		System.out.println("isWaterproof: " + l23.isWaterproof);
		System.out.println("countryOfOrigin: " + l23.countryOfOrigin);
		System.out.println("warrantyMonths: " + l23.warrantyMonths);
		System.out.println("packagingType: " + l23.packagingType);
		System.out.println("weight: " + l23.weight);
		System.out.println("isShockResistant: " + l23.isShockResistant);
		System.out.println("feature1: " + l23.feature1);
		System.out.println("feature2: " + l23.feature2);
		System.out.println("feature3: " + l23.feature3);
		System.out.println("isPortable: " + l23.isPortable);
		System.out.println("isEnergySaving: " + l23.isEnergySaving);
		System.out.println("rating: " + l23.rating);


		Lantern l24 = new Lantern();
		l24.productId = 124;
		l24.brandName = "Sample24";
		l24.lightType = "Sample24";
		l24.color = "Sample24";
		l24.batteryCapacity = 34.0;
		l24.price = 34.0;
		l24.isRechargeable = true;
		l24.isAvailable = true;
		l24.manufacturingDate = "Sample24";
		l24.expiryDate = "Sample24";
		l24.usageType = "Sample24";
		l24.material = "Sample24";
		l24.brightnessLevel = 34.0;
		l24.isWaterproof = true;
		l24.countryOfOrigin = "Sample24";
		l24.warrantyMonths = 124;
		l24.packagingType = "Sample24";
		l24.weight = 34.0;
		l24.isShockResistant = true;
		l24.feature1 = "Sample24";
		l24.feature2 = "Sample24";
		l24.feature3 = "Sample24";
		l24.isPortable = true;
		l24.isEnergySaving = true;
		l24.rating = 124;

		System.out.println("----- Lantern 24 -----");
		System.out.println("productId: " + l24.productId);
		System.out.println("brandName: " + l24.brandName);
		System.out.println("lightType: " + l24.lightType);
		System.out.println("color: " + l24.color);
		System.out.println("batteryCapacity: " + l24.batteryCapacity);
		System.out.println("price: " + l24.price);
		System.out.println("isRechargeable: " + l24.isRechargeable);
		System.out.println("isAvailable: " + l24.isAvailable);
		System.out.println("manufacturingDate: " + l24.manufacturingDate);
		System.out.println("expiryDate: " + l24.expiryDate);
		System.out.println("usageType: " + l24.usageType);
		System.out.println("material: " + l24.material);
		System.out.println("brightnessLevel: " + l24.brightnessLevel);
		System.out.println("isWaterproof: " + l24.isWaterproof);
		System.out.println("countryOfOrigin: " + l24.countryOfOrigin);
		System.out.println("warrantyMonths: " + l24.warrantyMonths);
		System.out.println("packagingType: " + l24.packagingType);
		System.out.println("weight: " + l24.weight);
		System.out.println("isShockResistant: " + l24.isShockResistant);
		System.out.println("feature1: " + l24.feature1);
		System.out.println("feature2: " + l24.feature2);
		System.out.println("feature3: " + l24.feature3);
		System.out.println("isPortable: " + l24.isPortable);
		System.out.println("isEnergySaving: " + l24.isEnergySaving);
		System.out.println("rating: " + l24.rating);


		Lantern l25 = new Lantern();
		l25.productId = 125;
		l25.brandName = "Sample25";
		l25.lightType = "Sample25";
		l25.color = "Sample25";
		l25.batteryCapacity = 35.0;
		l25.price = 35.0;
		l25.isRechargeable = false;
		l25.isAvailable = false;
		l25.manufacturingDate = "Sample25";
		l25.expiryDate = "Sample25";
		l25.usageType = "Sample25";
		l25.material = "Sample25";
		l25.brightnessLevel = 35.0;
		l25.isWaterproof = false;
		l25.countryOfOrigin = "Sample25";
		l25.warrantyMonths = 125;
		l25.packagingType = "Sample25";
		l25.weight = 35.0;
		l25.isShockResistant = false;
		l25.feature1 = "Sample25";
		l25.feature2 = "Sample25";
		l25.feature3 = "Sample25";
		l25.isPortable = false;
		l25.isEnergySaving = false;
		l25.rating = 125;

		System.out.println("----- Lantern 25 -----");
		System.out.println("productId: " + l25.productId);
		System.out.println("brandName: " + l25.brandName);
		System.out.println("lightType: " + l25.lightType);
		System.out.println("color: " + l25.color);
		System.out.println("batteryCapacity: " + l25.batteryCapacity);
		System.out.println("price: " + l25.price);
		System.out.println("isRechargeable: " + l25.isRechargeable);
		System.out.println("isAvailable: " + l25.isAvailable);
		System.out.println("manufacturingDate: " + l25.manufacturingDate);
		System.out.println("expiryDate: " + l25.expiryDate);
		System.out.println("usageType: " + l25.usageType);
		System.out.println("material: " + l25.material);
		System.out.println("brightnessLevel: " + l25.brightnessLevel);
		System.out.println("isWaterproof: " + l25.isWaterproof);
		System.out.println("countryOfOrigin: " + l25.countryOfOrigin);
		System.out.println("warrantyMonths: " + l25.warrantyMonths);
		System.out.println("packagingType: " + l25.packagingType);
		System.out.println("weight: " + l25.weight);
		System.out.println("isShockResistant: " + l25.isShockResistant);
		System.out.println("feature1: " + l25.feature1);
		System.out.println("feature2: " + l25.feature2);
		System.out.println("feature3: " + l25.feature3);
		System.out.println("isPortable: " + l25.isPortable);
		System.out.println("isEnergySaving: " + l25.isEnergySaving);
		System.out.println("rating: " + l25.rating);


	}
}
