class LGExecutor {
    public static void main(String[] args) {
        boolean isValidate;

        isValidate = LG.createProduct("OLED TV", "OLED65C3", 249999.0, 2, true, "5 Star", 4.0, true, "Metallic Silver", 15);
        LG.getProductDetails();
        isValidate = LG.createProduct("Refrigerator", "GL-B282", 35000.0, 1, true, "3 Star", 0.0, true, "Shiny Steel", 25);
        LG.getProductDetails();
        isValidate = LG.createProduct("Washing Machine", "FHM1207", 32000.0, 3, true, "5 Star", 0.0, true, "Middle Black", 20);
        LG.getProductDetails();
        isValidate = LG.createProduct("Air Conditioner", "PS-Q19BWZF", 55000.0, 1, true, "5 Star", 0.0, true, "White", 10);
        LG.getProductDetails();
        isValidate = LG.createProduct("Microwave", "MC2886", 15000.0, 1, false, "4 Star", 0.0, false, "Black", 40);
        LG.getProductDetails();
        isValidate = LG.createProduct("Monitor", "27GN800", 28000.0, 3, false, "A+", 2.0, false, "Black", 100);
        LG.getProductDetails();
        isValidate = LG.createProduct("Soundbar", "S95QR", 105000.0, 1, true, "N/A", 0.0, true, "Dark Grey", 5);
        LG.getProductDetails();
        isValidate = LG.createProduct("Projector", "HU715QW", 299000.0, 2, true, "A", 4.0, true, "White", 3);
        LG.getProductDetails();
        isValidate = LG.createProduct("Dishwasher", "DFB424", 58000.0, 2, true, "A++", 0.0, true, "Platinum Silver", 12);
        LG.getProductDetails();
        isValidate = LG.createProduct("Air Purifier", "AS10GD", 65000.0, 1, true, "5 Star", 0.0, true, "Gold", 8);
        LG.getProductDetails();
        isValidate = LG.createProduct("Dehumidifier", "UD161", 25000.0, 1, false, "3 Star", 0.0, true, "White", 14);
        LG.getProductDetails();
        isValidate = LG.createProduct(null, "OLED-X", 50000.0, 1, true, "5 Star", 4.0, true, "Black", 10);
        LG.getProductDetails();
        isValidate = LG.createProduct("", "REF-X", 20000.0, 2, false, "2 Star", 0.0, false, "Silver", 5);
        LG.getProductDetails();
        isValidate = LG.createProduct("TV", null, 45000.0, 1, true, "4 Star", 4.0, true, "Black", 10);
        LG.getProductDetails();
        isValidate = LG.createProduct("Washing Machine", "", 30000.0, 2, true, "5 Star", 0.0, true, "White", 10);
        LG.getProductDetails();
        isValidate = LG.createProduct("Fridge", "GL-X22", 0.0, 1, true, "3 Star", 0.0, true, "Steel", 5);
        LG.getProductDetails();
        isValidate = LG.createProduct("AC", "LP-W12", 40000.0, -1, true, "5 Star", 0.0, true, "White", 10);
        LG.getProductDetails();
        isValidate = LG.createProduct("Monitor", "24MP", 12000.0, 3, false, null, 1.0, false, "Black", 20);
        LG.getProductDetails();
        isValidate = LG.createProduct("Dryer", "TD-V7", 45000.0, 2, true, "", 0.0, true, "Silver", 5);
        LG.getProductDetails();
        isValidate = LG.createProduct("Laptop", "Gram 17", 110000.0, 1, false, "A", -1.0, false, "Obsidian Black", 15);
        LG.getProductDetails();
        isValidate = LG.createProduct("Phone", "Wing", 40000.0, 1, true, "N/A", 2.0, false, null, 10);
        LG.getProductDetails();
        isValidate = LG.createProduct("Vacuum", "A9", 35000.0, 2, true, "5 Star", 0.0, true, "", 20);
        LG.getProductDetails();
        isValidate = LG.createProduct("Water Purifier", "WW184", 22000.0, 1, false, "N/A", 0.0, false, "Crimson Red", -1);
        LG.getProductDetails();
        isValidate = LG.createProduct(null, null, 0.0, 0, false, null, 0.0, false, null, 0);
        LG.getProductDetails();
        isValidate = LG.createProduct("Styler", "S3WFS", 140000.0, 2, true, "A", 0.0, true, "White", 2);
        LG.getProductDetails();
        isValidate = LG.createProduct("Wine Cellar", "Signature", 450000.0, 5, true, "A++", 0.0, true, "Textured Steel", 1);
        LG.getProductDetails();
        isValidate = LG.createProduct("Ceiling Fan", "Modern", 8000.0, 2, false, "5 Star", 0.0, false, "Brown", 60);
        LG.getProductDetails();
        isValidate = LG.createProduct("Heat Pump", "Therma V", 180000.0, 3, true, "A+++", 0.0, true, "Grey", 4);
        LG.getProductDetails();
        isValidate = LG.createProduct("Kiosk", "CL-5K", 320000.0, 1, true, "N/A", 4.0, true, "White", 7);
        LG.getProductDetails();
        isValidate = LG.createProduct("Solar Panel", "NeON 2", 15000.0, 25, false, "A+++", 0.0, false, "Blue", 200);
        LG.getProductDetails();
        isValidate = LG.createProduct("TV", "NanoCell", 85000.0, 2, true, "4 Star", 4.0, true, "Dark Blue", 18);
        LG.getProductDetails();
        isValidate = LG.createProduct("Chiller", "Centrifugal", 999999.0, 5, true, "Industry Standard", 0.0, true, "Grey", 2);
        LG.getProductDetails();
        isValidate = LG.createProduct("Chest Freezer", "Freez-X", 22000.0, 1, false, "3 Star", 0.0, false, "White", 30);
        LG.getProductDetails();
        isValidate = LG.createProduct("Smart Speaker", "WK7", 9000.0, 1, true, "N/A", 0.0, true, "Titan Grey", 45);
        LG.getProductDetails();
        isValidate = LG.createProduct("Tablet", "G Pad", 18000.0, 1, false, "A", 1.5, false, "Silver", 22);
        LG.getProductDetails();
        isValidate = LG.createProduct("Medical Display", "31HN", 250000.0, 3, false, "Clinical Grade", 8.0, false, "White", 6);
        LG.getProductDetails();
        isValidate = LG.createProduct("LED Signage", "LSCB", 500000.0, 2, true, "N/A", 2.0, true, "Black", 4);
        LG.getProductDetails();
    }
}