class NovaBackpackRunner {
	public static void main(String[] args) {

		NovaBackpack n1 = new NovaBackpack();
		n1.productId = 101;
		n1.brandName = "Sample1";
		n1.material = "Sample1";
		n1.color = "Sample1";
		n1.capacity = 11.0;
		n1.price = 11.0;
		n1.isWaterproof = false;
		n1.isAvailable = false;
		n1.manufacturingDate = "Sample1";
		n1.expiryDate = "Sample1";
		n1.bagType = "Sample1";
		n1.zipperType = "Sample1";
		n1.weight = 11.0;
		n1.hasLaptopCompartment = false;
		n1.countryOfOrigin = "Sample1";
		n1.warrantyMonths = 101;
		n1.packagingType = "Sample1";
		n1.height = 11.0;
		n1.isTravelFriendly = false;
		n1.feature1 = "Sample1";
		n1.feature2 = "Sample1";
		n1.feature3 = "Sample1";
		n1.hasUSBPort = false;
		n1.isAntiTheft = false;
		n1.rating = 101;

		System.out.println("----- NovaBackpack 1 -----");
		System.out.println("productId: " + n1.productId);
		System.out.println("brandName: " + n1.brandName);
		System.out.println("material: " + n1.material);
		System.out.println("color: " + n1.color);
		System.out.println("capacity: " + n1.capacity);
		System.out.println("price: " + n1.price);
		System.out.println("isWaterproof: " + n1.isWaterproof);
		System.out.println("isAvailable: " + n1.isAvailable);
		System.out.println("manufacturingDate: " + n1.manufacturingDate);
		System.out.println("expiryDate: " + n1.expiryDate);
		System.out.println("bagType: " + n1.bagType);
		System.out.println("zipperType: " + n1.zipperType);
		System.out.println("weight: " + n1.weight);
		System.out.println("hasLaptopCompartment: " + n1.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n1.countryOfOrigin);
		System.out.println("warrantyMonths: " + n1.warrantyMonths);
		System.out.println("packagingType: " + n1.packagingType);
		System.out.println("height: " + n1.height);
		System.out.println("isTravelFriendly: " + n1.isTravelFriendly);
		System.out.println("feature1: " + n1.feature1);
		System.out.println("feature2: " + n1.feature2);
		System.out.println("feature3: " + n1.feature3);
		System.out.println("hasUSBPort: " + n1.hasUSBPort);
		System.out.println("isAntiTheft: " + n1.isAntiTheft);
		System.out.println("rating: " + n1.rating);


		NovaBackpack n2 = new NovaBackpack();
		n2.productId = 102;
		n2.brandName = "Sample2";
		n2.material = "Sample2";
		n2.color = "Sample2";
		n2.capacity = 12.0;
		n2.price = 12.0;
		n2.isWaterproof = true;
		n2.isAvailable = true;
		n2.manufacturingDate = "Sample2";
		n2.expiryDate = "Sample2";
		n2.bagType = "Sample2";
		n2.zipperType = "Sample2";
		n2.weight = 12.0;
		n2.hasLaptopCompartment = true;
		n2.countryOfOrigin = "Sample2";
		n2.warrantyMonths = 102;
		n2.packagingType = "Sample2";
		n2.height = 12.0;
		n2.isTravelFriendly = true;
		n2.feature1 = "Sample2";
		n2.feature2 = "Sample2";
		n2.feature3 = "Sample2";
		n2.hasUSBPort = true;
		n2.isAntiTheft = true;
		n2.rating = 102;

		System.out.println("----- NovaBackpack 2 -----");
		System.out.println("productId: " + n2.productId);
		System.out.println("brandName: " + n2.brandName);
		System.out.println("material: " + n2.material);
		System.out.println("color: " + n2.color);
		System.out.println("capacity: " + n2.capacity);
		System.out.println("price: " + n2.price);
		System.out.println("isWaterproof: " + n2.isWaterproof);
		System.out.println("isAvailable: " + n2.isAvailable);
		System.out.println("manufacturingDate: " + n2.manufacturingDate);
		System.out.println("expiryDate: " + n2.expiryDate);
		System.out.println("bagType: " + n2.bagType);
		System.out.println("zipperType: " + n2.zipperType);
		System.out.println("weight: " + n2.weight);
		System.out.println("hasLaptopCompartment: " + n2.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n2.countryOfOrigin);
		System.out.println("warrantyMonths: " + n2.warrantyMonths);
		System.out.println("packagingType: " + n2.packagingType);
		System.out.println("height: " + n2.height);
		System.out.println("isTravelFriendly: " + n2.isTravelFriendly);
		System.out.println("feature1: " + n2.feature1);
		System.out.println("feature2: " + n2.feature2);
		System.out.println("feature3: " + n2.feature3);
		System.out.println("hasUSBPort: " + n2.hasUSBPort);
		System.out.println("isAntiTheft: " + n2.isAntiTheft);
		System.out.println("rating: " + n2.rating);


		NovaBackpack n3 = new NovaBackpack();
		n3.productId = 103;
		n3.brandName = "Sample3";
		n3.material = "Sample3";
		n3.color = "Sample3";
		n3.capacity = 13.0;
		n3.price = 13.0;
		n3.isWaterproof = false;
		n3.isAvailable = false;
		n3.manufacturingDate = "Sample3";
		n3.expiryDate = "Sample3";
		n3.bagType = "Sample3";
		n3.zipperType = "Sample3";
		n3.weight = 13.0;
		n3.hasLaptopCompartment = false;
		n3.countryOfOrigin = "Sample3";
		n3.warrantyMonths = 103;
		n3.packagingType = "Sample3";
		n3.height = 13.0;
		n3.isTravelFriendly = false;
		n3.feature1 = "Sample3";
		n3.feature2 = "Sample3";
		n3.feature3 = "Sample3";
		n3.hasUSBPort = false;
		n3.isAntiTheft = false;
		n3.rating = 103;

		System.out.println("----- NovaBackpack 3 -----");
		System.out.println("productId: " + n3.productId);
		System.out.println("brandName: " + n3.brandName);
		System.out.println("material: " + n3.material);
		System.out.println("color: " + n3.color);
		System.out.println("capacity: " + n3.capacity);
		System.out.println("price: " + n3.price);
		System.out.println("isWaterproof: " + n3.isWaterproof);
		System.out.println("isAvailable: " + n3.isAvailable);
		System.out.println("manufacturingDate: " + n3.manufacturingDate);
		System.out.println("expiryDate: " + n3.expiryDate);
		System.out.println("bagType: " + n3.bagType);
		System.out.println("zipperType: " + n3.zipperType);
		System.out.println("weight: " + n3.weight);
		System.out.println("hasLaptopCompartment: " + n3.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n3.countryOfOrigin);
		System.out.println("warrantyMonths: " + n3.warrantyMonths);
		System.out.println("packagingType: " + n3.packagingType);
		System.out.println("height: " + n3.height);
		System.out.println("isTravelFriendly: " + n3.isTravelFriendly);
		System.out.println("feature1: " + n3.feature1);
		System.out.println("feature2: " + n3.feature2);
		System.out.println("feature3: " + n3.feature3);
		System.out.println("hasUSBPort: " + n3.hasUSBPort);
		System.out.println("isAntiTheft: " + n3.isAntiTheft);
		System.out.println("rating: " + n3.rating);


		NovaBackpack n4 = new NovaBackpack();
		n4.productId = 104;
		n4.brandName = "Sample4";
		n4.material = "Sample4";
		n4.color = "Sample4";
		n4.capacity = 14.0;
		n4.price = 14.0;
		n4.isWaterproof = true;
		n4.isAvailable = true;
		n4.manufacturingDate = "Sample4";
		n4.expiryDate = "Sample4";
		n4.bagType = "Sample4";
		n4.zipperType = "Sample4";
		n4.weight = 14.0;
		n4.hasLaptopCompartment = true;
		n4.countryOfOrigin = "Sample4";
		n4.warrantyMonths = 104;
		n4.packagingType = "Sample4";
		n4.height = 14.0;
		n4.isTravelFriendly = true;
		n4.feature1 = "Sample4";
		n4.feature2 = "Sample4";
		n4.feature3 = "Sample4";
		n4.hasUSBPort = true;
		n4.isAntiTheft = true;
		n4.rating = 104;

		System.out.println("----- NovaBackpack 4 -----");
		System.out.println("productId: " + n4.productId);
		System.out.println("brandName: " + n4.brandName);
		System.out.println("material: " + n4.material);
		System.out.println("color: " + n4.color);
		System.out.println("capacity: " + n4.capacity);
		System.out.println("price: " + n4.price);
		System.out.println("isWaterproof: " + n4.isWaterproof);
		System.out.println("isAvailable: " + n4.isAvailable);
		System.out.println("manufacturingDate: " + n4.manufacturingDate);
		System.out.println("expiryDate: " + n4.expiryDate);
		System.out.println("bagType: " + n4.bagType);
		System.out.println("zipperType: " + n4.zipperType);
		System.out.println("weight: " + n4.weight);
		System.out.println("hasLaptopCompartment: " + n4.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n4.countryOfOrigin);
		System.out.println("warrantyMonths: " + n4.warrantyMonths);
		System.out.println("packagingType: " + n4.packagingType);
		System.out.println("height: " + n4.height);
		System.out.println("isTravelFriendly: " + n4.isTravelFriendly);
		System.out.println("feature1: " + n4.feature1);
		System.out.println("feature2: " + n4.feature2);
		System.out.println("feature3: " + n4.feature3);
		System.out.println("hasUSBPort: " + n4.hasUSBPort);
		System.out.println("isAntiTheft: " + n4.isAntiTheft);
		System.out.println("rating: " + n4.rating);


		NovaBackpack n5 = new NovaBackpack();
		n5.productId = 105;
		n5.brandName = "Sample5";
		n5.material = "Sample5";
		n5.color = "Sample5";
		n5.capacity = 15.0;
		n5.price = 15.0;
		n5.isWaterproof = false;
		n5.isAvailable = false;
		n5.manufacturingDate = "Sample5";
		n5.expiryDate = "Sample5";
		n5.bagType = "Sample5";
		n5.zipperType = "Sample5";
		n5.weight = 15.0;
		n5.hasLaptopCompartment = false;
		n5.countryOfOrigin = "Sample5";
		n5.warrantyMonths = 105;
		n5.packagingType = "Sample5";
		n5.height = 15.0;
		n5.isTravelFriendly = false;
		n5.feature1 = "Sample5";
		n5.feature2 = "Sample5";
		n5.feature3 = "Sample5";
		n5.hasUSBPort = false;
		n5.isAntiTheft = false;
		n5.rating = 105;

		System.out.println("----- NovaBackpack 5 -----");
		System.out.println("productId: " + n5.productId);
		System.out.println("brandName: " + n5.brandName);
		System.out.println("material: " + n5.material);
		System.out.println("color: " + n5.color);
		System.out.println("capacity: " + n5.capacity);
		System.out.println("price: " + n5.price);
		System.out.println("isWaterproof: " + n5.isWaterproof);
		System.out.println("isAvailable: " + n5.isAvailable);
		System.out.println("manufacturingDate: " + n5.manufacturingDate);
		System.out.println("expiryDate: " + n5.expiryDate);
		System.out.println("bagType: " + n5.bagType);
		System.out.println("zipperType: " + n5.zipperType);
		System.out.println("weight: " + n5.weight);
		System.out.println("hasLaptopCompartment: " + n5.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n5.countryOfOrigin);
		System.out.println("warrantyMonths: " + n5.warrantyMonths);
		System.out.println("packagingType: " + n5.packagingType);
		System.out.println("height: " + n5.height);
		System.out.println("isTravelFriendly: " + n5.isTravelFriendly);
		System.out.println("feature1: " + n5.feature1);
		System.out.println("feature2: " + n5.feature2);
		System.out.println("feature3: " + n5.feature3);
		System.out.println("hasUSBPort: " + n5.hasUSBPort);
		System.out.println("isAntiTheft: " + n5.isAntiTheft);
		System.out.println("rating: " + n5.rating);


		NovaBackpack n6 = new NovaBackpack();
		n6.productId = 106;
		n6.brandName = "Sample6";
		n6.material = "Sample6";
		n6.color = "Sample6";
		n6.capacity = 16.0;
		n6.price = 16.0;
		n6.isWaterproof = true;
		n6.isAvailable = true;
		n6.manufacturingDate = "Sample6";
		n6.expiryDate = "Sample6";
		n6.bagType = "Sample6";
		n6.zipperType = "Sample6";
		n6.weight = 16.0;
		n6.hasLaptopCompartment = true;
		n6.countryOfOrigin = "Sample6";
		n6.warrantyMonths = 106;
		n6.packagingType = "Sample6";
		n6.height = 16.0;
		n6.isTravelFriendly = true;
		n6.feature1 = "Sample6";
		n6.feature2 = "Sample6";
		n6.feature3 = "Sample6";
		n6.hasUSBPort = true;
		n6.isAntiTheft = true;
		n6.rating = 106;

		System.out.println("----- NovaBackpack 6 -----");
		System.out.println("productId: " + n6.productId);
		System.out.println("brandName: " + n6.brandName);
		System.out.println("material: " + n6.material);
		System.out.println("color: " + n6.color);
		System.out.println("capacity: " + n6.capacity);
		System.out.println("price: " + n6.price);
		System.out.println("isWaterproof: " + n6.isWaterproof);
		System.out.println("isAvailable: " + n6.isAvailable);
		System.out.println("manufacturingDate: " + n6.manufacturingDate);
		System.out.println("expiryDate: " + n6.expiryDate);
		System.out.println("bagType: " + n6.bagType);
		System.out.println("zipperType: " + n6.zipperType);
		System.out.println("weight: " + n6.weight);
		System.out.println("hasLaptopCompartment: " + n6.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n6.countryOfOrigin);
		System.out.println("warrantyMonths: " + n6.warrantyMonths);
		System.out.println("packagingType: " + n6.packagingType);
		System.out.println("height: " + n6.height);
		System.out.println("isTravelFriendly: " + n6.isTravelFriendly);
		System.out.println("feature1: " + n6.feature1);
		System.out.println("feature2: " + n6.feature2);
		System.out.println("feature3: " + n6.feature3);
		System.out.println("hasUSBPort: " + n6.hasUSBPort);
		System.out.println("isAntiTheft: " + n6.isAntiTheft);
		System.out.println("rating: " + n6.rating);


		NovaBackpack n7 = new NovaBackpack();
		n7.productId = 107;
		n7.brandName = "Sample7";
		n7.material = "Sample7";
		n7.color = "Sample7";
		n7.capacity = 17.0;
		n7.price = 17.0;
		n7.isWaterproof = false;
		n7.isAvailable = false;
		n7.manufacturingDate = "Sample7";
		n7.expiryDate = "Sample7";
		n7.bagType = "Sample7";
		n7.zipperType = "Sample7";
		n7.weight = 17.0;
		n7.hasLaptopCompartment = false;
		n7.countryOfOrigin = "Sample7";
		n7.warrantyMonths = 107;
		n7.packagingType = "Sample7";
		n7.height = 17.0;
		n7.isTravelFriendly = false;
		n7.feature1 = "Sample7";
		n7.feature2 = "Sample7";
		n7.feature3 = "Sample7";
		n7.hasUSBPort = false;
		n7.isAntiTheft = false;
		n7.rating = 107;

		System.out.println("----- NovaBackpack 7 -----");
		System.out.println("productId: " + n7.productId);
		System.out.println("brandName: " + n7.brandName);
		System.out.println("material: " + n7.material);
		System.out.println("color: " + n7.color);
		System.out.println("capacity: " + n7.capacity);
		System.out.println("price: " + n7.price);
		System.out.println("isWaterproof: " + n7.isWaterproof);
		System.out.println("isAvailable: " + n7.isAvailable);
		System.out.println("manufacturingDate: " + n7.manufacturingDate);
		System.out.println("expiryDate: " + n7.expiryDate);
		System.out.println("bagType: " + n7.bagType);
		System.out.println("zipperType: " + n7.zipperType);
		System.out.println("weight: " + n7.weight);
		System.out.println("hasLaptopCompartment: " + n7.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n7.countryOfOrigin);
		System.out.println("warrantyMonths: " + n7.warrantyMonths);
		System.out.println("packagingType: " + n7.packagingType);
		System.out.println("height: " + n7.height);
		System.out.println("isTravelFriendly: " + n7.isTravelFriendly);
		System.out.println("feature1: " + n7.feature1);
		System.out.println("feature2: " + n7.feature2);
		System.out.println("feature3: " + n7.feature3);
		System.out.println("hasUSBPort: " + n7.hasUSBPort);
		System.out.println("isAntiTheft: " + n7.isAntiTheft);
		System.out.println("rating: " + n7.rating);


		NovaBackpack n8 = new NovaBackpack();
		n8.productId = 108;
		n8.brandName = "Sample8";
		n8.material = "Sample8";
		n8.color = "Sample8";
		n8.capacity = 18.0;
		n8.price = 18.0;
		n8.isWaterproof = true;
		n8.isAvailable = true;
		n8.manufacturingDate = "Sample8";
		n8.expiryDate = "Sample8";
		n8.bagType = "Sample8";
		n8.zipperType = "Sample8";
		n8.weight = 18.0;
		n8.hasLaptopCompartment = true;
		n8.countryOfOrigin = "Sample8";
		n8.warrantyMonths = 108;
		n8.packagingType = "Sample8";
		n8.height = 18.0;
		n8.isTravelFriendly = true;
		n8.feature1 = "Sample8";
		n8.feature2 = "Sample8";
		n8.feature3 = "Sample8";
		n8.hasUSBPort = true;
		n8.isAntiTheft = true;
		n8.rating = 108;

		System.out.println("----- NovaBackpack 8 -----");
		System.out.println("productId: " + n8.productId);
		System.out.println("brandName: " + n8.brandName);
		System.out.println("material: " + n8.material);
		System.out.println("color: " + n8.color);
		System.out.println("capacity: " + n8.capacity);
		System.out.println("price: " + n8.price);
		System.out.println("isWaterproof: " + n8.isWaterproof);
		System.out.println("isAvailable: " + n8.isAvailable);
		System.out.println("manufacturingDate: " + n8.manufacturingDate);
		System.out.println("expiryDate: " + n8.expiryDate);
		System.out.println("bagType: " + n8.bagType);
		System.out.println("zipperType: " + n8.zipperType);
		System.out.println("weight: " + n8.weight);
		System.out.println("hasLaptopCompartment: " + n8.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n8.countryOfOrigin);
		System.out.println("warrantyMonths: " + n8.warrantyMonths);
		System.out.println("packagingType: " + n8.packagingType);
		System.out.println("height: " + n8.height);
		System.out.println("isTravelFriendly: " + n8.isTravelFriendly);
		System.out.println("feature1: " + n8.feature1);
		System.out.println("feature2: " + n8.feature2);
		System.out.println("feature3: " + n8.feature3);
		System.out.println("hasUSBPort: " + n8.hasUSBPort);
		System.out.println("isAntiTheft: " + n8.isAntiTheft);
		System.out.println("rating: " + n8.rating);


		NovaBackpack n9 = new NovaBackpack();
		n9.productId = 109;
		n9.brandName = "Sample9";
		n9.material = "Sample9";
		n9.color = "Sample9";
		n9.capacity = 19.0;
		n9.price = 19.0;
		n9.isWaterproof = false;
		n9.isAvailable = false;
		n9.manufacturingDate = "Sample9";
		n9.expiryDate = "Sample9";
		n9.bagType = "Sample9";
		n9.zipperType = "Sample9";
		n9.weight = 19.0;
		n9.hasLaptopCompartment = false;
		n9.countryOfOrigin = "Sample9";
		n9.warrantyMonths = 109;
		n9.packagingType = "Sample9";
		n9.height = 19.0;
		n9.isTravelFriendly = false;
		n9.feature1 = "Sample9";
		n9.feature2 = "Sample9";
		n9.feature3 = "Sample9";
		n9.hasUSBPort = false;
		n9.isAntiTheft = false;
		n9.rating = 109;

		System.out.println("----- NovaBackpack 9 -----");
		System.out.println("productId: " + n9.productId);
		System.out.println("brandName: " + n9.brandName);
		System.out.println("material: " + n9.material);
		System.out.println("color: " + n9.color);
		System.out.println("capacity: " + n9.capacity);
		System.out.println("price: " + n9.price);
		System.out.println("isWaterproof: " + n9.isWaterproof);
		System.out.println("isAvailable: " + n9.isAvailable);
		System.out.println("manufacturingDate: " + n9.manufacturingDate);
		System.out.println("expiryDate: " + n9.expiryDate);
		System.out.println("bagType: " + n9.bagType);
		System.out.println("zipperType: " + n9.zipperType);
		System.out.println("weight: " + n9.weight);
		System.out.println("hasLaptopCompartment: " + n9.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n9.countryOfOrigin);
		System.out.println("warrantyMonths: " + n9.warrantyMonths);
		System.out.println("packagingType: " + n9.packagingType);
		System.out.println("height: " + n9.height);
		System.out.println("isTravelFriendly: " + n9.isTravelFriendly);
		System.out.println("feature1: " + n9.feature1);
		System.out.println("feature2: " + n9.feature2);
		System.out.println("feature3: " + n9.feature3);
		System.out.println("hasUSBPort: " + n9.hasUSBPort);
		System.out.println("isAntiTheft: " + n9.isAntiTheft);
		System.out.println("rating: " + n9.rating);


		NovaBackpack n10 = new NovaBackpack();
		n10.productId = 110;
		n10.brandName = "Sample10";
		n10.material = "Sample10";
		n10.color = "Sample10";
		n10.capacity = 20.0;
		n10.price = 20.0;
		n10.isWaterproof = true;
		n10.isAvailable = true;
		n10.manufacturingDate = "Sample10";
		n10.expiryDate = "Sample10";
		n10.bagType = "Sample10";
		n10.zipperType = "Sample10";
		n10.weight = 20.0;
		n10.hasLaptopCompartment = true;
		n10.countryOfOrigin = "Sample10";
		n10.warrantyMonths = 110;
		n10.packagingType = "Sample10";
		n10.height = 20.0;
		n10.isTravelFriendly = true;
		n10.feature1 = "Sample10";
		n10.feature2 = "Sample10";
		n10.feature3 = "Sample10";
		n10.hasUSBPort = true;
		n10.isAntiTheft = true;
		n10.rating = 110;

		System.out.println("----- NovaBackpack 10 -----");
		System.out.println("productId: " + n10.productId);
		System.out.println("brandName: " + n10.brandName);
		System.out.println("material: " + n10.material);
		System.out.println("color: " + n10.color);
		System.out.println("capacity: " + n10.capacity);
		System.out.println("price: " + n10.price);
		System.out.println("isWaterproof: " + n10.isWaterproof);
		System.out.println("isAvailable: " + n10.isAvailable);
		System.out.println("manufacturingDate: " + n10.manufacturingDate);
		System.out.println("expiryDate: " + n10.expiryDate);
		System.out.println("bagType: " + n10.bagType);
		System.out.println("zipperType: " + n10.zipperType);
		System.out.println("weight: " + n10.weight);
		System.out.println("hasLaptopCompartment: " + n10.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n10.countryOfOrigin);
		System.out.println("warrantyMonths: " + n10.warrantyMonths);
		System.out.println("packagingType: " + n10.packagingType);
		System.out.println("height: " + n10.height);
		System.out.println("isTravelFriendly: " + n10.isTravelFriendly);
		System.out.println("feature1: " + n10.feature1);
		System.out.println("feature2: " + n10.feature2);
		System.out.println("feature3: " + n10.feature3);
		System.out.println("hasUSBPort: " + n10.hasUSBPort);
		System.out.println("isAntiTheft: " + n10.isAntiTheft);
		System.out.println("rating: " + n10.rating);


		NovaBackpack n11 = new NovaBackpack();
		n11.productId = 111;
		n11.brandName = "Sample11";
		n11.material = "Sample11";
		n11.color = "Sample11";
		n11.capacity = 21.0;
		n11.price = 21.0;
		n11.isWaterproof = false;
		n11.isAvailable = false;
		n11.manufacturingDate = "Sample11";
		n11.expiryDate = "Sample11";
		n11.bagType = "Sample11";
		n11.zipperType = "Sample11";
		n11.weight = 21.0;
		n11.hasLaptopCompartment = false;
		n11.countryOfOrigin = "Sample11";
		n11.warrantyMonths = 111;
		n11.packagingType = "Sample11";
		n11.height = 21.0;
		n11.isTravelFriendly = false;
		n11.feature1 = "Sample11";
		n11.feature2 = "Sample11";
		n11.feature3 = "Sample11";
		n11.hasUSBPort = false;
		n11.isAntiTheft = false;
		n11.rating = 111;

		System.out.println("----- NovaBackpack 11 -----");
		System.out.println("productId: " + n11.productId);
		System.out.println("brandName: " + n11.brandName);
		System.out.println("material: " + n11.material);
		System.out.println("color: " + n11.color);
		System.out.println("capacity: " + n11.capacity);
		System.out.println("price: " + n11.price);
		System.out.println("isWaterproof: " + n11.isWaterproof);
		System.out.println("isAvailable: " + n11.isAvailable);
		System.out.println("manufacturingDate: " + n11.manufacturingDate);
		System.out.println("expiryDate: " + n11.expiryDate);
		System.out.println("bagType: " + n11.bagType);
		System.out.println("zipperType: " + n11.zipperType);
		System.out.println("weight: " + n11.weight);
		System.out.println("hasLaptopCompartment: " + n11.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n11.countryOfOrigin);
		System.out.println("warrantyMonths: " + n11.warrantyMonths);
		System.out.println("packagingType: " + n11.packagingType);
		System.out.println("height: " + n11.height);
		System.out.println("isTravelFriendly: " + n11.isTravelFriendly);
		System.out.println("feature1: " + n11.feature1);
		System.out.println("feature2: " + n11.feature2);
		System.out.println("feature3: " + n11.feature3);
		System.out.println("hasUSBPort: " + n11.hasUSBPort);
		System.out.println("isAntiTheft: " + n11.isAntiTheft);
		System.out.println("rating: " + n11.rating);


		NovaBackpack n12 = new NovaBackpack();
		n12.productId = 112;
		n12.brandName = "Sample12";
		n12.material = "Sample12";
		n12.color = "Sample12";
		n12.capacity = 22.0;
		n12.price = 22.0;
		n12.isWaterproof = true;
		n12.isAvailable = true;
		n12.manufacturingDate = "Sample12";
		n12.expiryDate = "Sample12";
		n12.bagType = "Sample12";
		n12.zipperType = "Sample12";
		n12.weight = 22.0;
		n12.hasLaptopCompartment = true;
		n12.countryOfOrigin = "Sample12";
		n12.warrantyMonths = 112;
		n12.packagingType = "Sample12";
		n12.height = 22.0;
		n12.isTravelFriendly = true;
		n12.feature1 = "Sample12";
		n12.feature2 = "Sample12";
		n12.feature3 = "Sample12";
		n12.hasUSBPort = true;
		n12.isAntiTheft = true;
		n12.rating = 112;

		System.out.println("----- NovaBackpack 12 -----");
		System.out.println("productId: " + n12.productId);
		System.out.println("brandName: " + n12.brandName);
		System.out.println("material: " + n12.material);
		System.out.println("color: " + n12.color);
		System.out.println("capacity: " + n12.capacity);
		System.out.println("price: " + n12.price);
		System.out.println("isWaterproof: " + n12.isWaterproof);
		System.out.println("isAvailable: " + n12.isAvailable);
		System.out.println("manufacturingDate: " + n12.manufacturingDate);
		System.out.println("expiryDate: " + n12.expiryDate);
		System.out.println("bagType: " + n12.bagType);
		System.out.println("zipperType: " + n12.zipperType);
		System.out.println("weight: " + n12.weight);
		System.out.println("hasLaptopCompartment: " + n12.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n12.countryOfOrigin);
		System.out.println("warrantyMonths: " + n12.warrantyMonths);
		System.out.println("packagingType: " + n12.packagingType);
		System.out.println("height: " + n12.height);
		System.out.println("isTravelFriendly: " + n12.isTravelFriendly);
		System.out.println("feature1: " + n12.feature1);
		System.out.println("feature2: " + n12.feature2);
		System.out.println("feature3: " + n12.feature3);
		System.out.println("hasUSBPort: " + n12.hasUSBPort);
		System.out.println("isAntiTheft: " + n12.isAntiTheft);
		System.out.println("rating: " + n12.rating);


		NovaBackpack n13 = new NovaBackpack();
		n13.productId = 113;
		n13.brandName = "Sample13";
		n13.material = "Sample13";
		n13.color = "Sample13";
		n13.capacity = 23.0;
		n13.price = 23.0;
		n13.isWaterproof = false;
		n13.isAvailable = false;
		n13.manufacturingDate = "Sample13";
		n13.expiryDate = "Sample13";
		n13.bagType = "Sample13";
		n13.zipperType = "Sample13";
		n13.weight = 23.0;
		n13.hasLaptopCompartment = false;
		n13.countryOfOrigin = "Sample13";
		n13.warrantyMonths = 113;
		n13.packagingType = "Sample13";
		n13.height = 23.0;
		n13.isTravelFriendly = false;
		n13.feature1 = "Sample13";
		n13.feature2 = "Sample13";
		n13.feature3 = "Sample13";
		n13.hasUSBPort = false;
		n13.isAntiTheft = false;
		n13.rating = 113;

		System.out.println("----- NovaBackpack 13 -----");
		System.out.println("productId: " + n13.productId);
		System.out.println("brandName: " + n13.brandName);
		System.out.println("material: " + n13.material);
		System.out.println("color: " + n13.color);
		System.out.println("capacity: " + n13.capacity);
		System.out.println("price: " + n13.price);
		System.out.println("isWaterproof: " + n13.isWaterproof);
		System.out.println("isAvailable: " + n13.isAvailable);
		System.out.println("manufacturingDate: " + n13.manufacturingDate);
		System.out.println("expiryDate: " + n13.expiryDate);
		System.out.println("bagType: " + n13.bagType);
		System.out.println("zipperType: " + n13.zipperType);
		System.out.println("weight: " + n13.weight);
		System.out.println("hasLaptopCompartment: " + n13.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n13.countryOfOrigin);
		System.out.println("warrantyMonths: " + n13.warrantyMonths);
		System.out.println("packagingType: " + n13.packagingType);
		System.out.println("height: " + n13.height);
		System.out.println("isTravelFriendly: " + n13.isTravelFriendly);
		System.out.println("feature1: " + n13.feature1);
		System.out.println("feature2: " + n13.feature2);
		System.out.println("feature3: " + n13.feature3);
		System.out.println("hasUSBPort: " + n13.hasUSBPort);
		System.out.println("isAntiTheft: " + n13.isAntiTheft);
		System.out.println("rating: " + n13.rating);


		NovaBackpack n14 = new NovaBackpack();
		n14.productId = 114;
		n14.brandName = "Sample14";
		n14.material = "Sample14";
		n14.color = "Sample14";
		n14.capacity = 24.0;
		n14.price = 24.0;
		n14.isWaterproof = true;
		n14.isAvailable = true;
		n14.manufacturingDate = "Sample14";
		n14.expiryDate = "Sample14";
		n14.bagType = "Sample14";
		n14.zipperType = "Sample14";
		n14.weight = 24.0;
		n14.hasLaptopCompartment = true;
		n14.countryOfOrigin = "Sample14";
		n14.warrantyMonths = 114;
		n14.packagingType = "Sample14";
		n14.height = 24.0;
		n14.isTravelFriendly = true;
		n14.feature1 = "Sample14";
		n14.feature2 = "Sample14";
		n14.feature3 = "Sample14";
		n14.hasUSBPort = true;
		n14.isAntiTheft = true;
		n14.rating = 114;

		System.out.println("----- NovaBackpack 14 -----");
		System.out.println("productId: " + n14.productId);
		System.out.println("brandName: " + n14.brandName);
		System.out.println("material: " + n14.material);
		System.out.println("color: " + n14.color);
		System.out.println("capacity: " + n14.capacity);
		System.out.println("price: " + n14.price);
		System.out.println("isWaterproof: " + n14.isWaterproof);
		System.out.println("isAvailable: " + n14.isAvailable);
		System.out.println("manufacturingDate: " + n14.manufacturingDate);
		System.out.println("expiryDate: " + n14.expiryDate);
		System.out.println("bagType: " + n14.bagType);
		System.out.println("zipperType: " + n14.zipperType);
		System.out.println("weight: " + n14.weight);
		System.out.println("hasLaptopCompartment: " + n14.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n14.countryOfOrigin);
		System.out.println("warrantyMonths: " + n14.warrantyMonths);
		System.out.println("packagingType: " + n14.packagingType);
		System.out.println("height: " + n14.height);
		System.out.println("isTravelFriendly: " + n14.isTravelFriendly);
		System.out.println("feature1: " + n14.feature1);
		System.out.println("feature2: " + n14.feature2);
		System.out.println("feature3: " + n14.feature3);
		System.out.println("hasUSBPort: " + n14.hasUSBPort);
		System.out.println("isAntiTheft: " + n14.isAntiTheft);
		System.out.println("rating: " + n14.rating);


		NovaBackpack n15 = new NovaBackpack();
		n15.productId = 115;
		n15.brandName = "Sample15";
		n15.material = "Sample15";
		n15.color = "Sample15";
		n15.capacity = 25.0;
		n15.price = 25.0;
		n15.isWaterproof = false;
		n15.isAvailable = false;
		n15.manufacturingDate = "Sample15";
		n15.expiryDate = "Sample15";
		n15.bagType = "Sample15";
		n15.zipperType = "Sample15";
		n15.weight = 25.0;
		n15.hasLaptopCompartment = false;
		n15.countryOfOrigin = "Sample15";
		n15.warrantyMonths = 115;
		n15.packagingType = "Sample15";
		n15.height = 25.0;
		n15.isTravelFriendly = false;
		n15.feature1 = "Sample15";
		n15.feature2 = "Sample15";
		n15.feature3 = "Sample15";
		n15.hasUSBPort = false;
		n15.isAntiTheft = false;
		n15.rating = 115;

		System.out.println("----- NovaBackpack 15 -----");
		System.out.println("productId: " + n15.productId);
		System.out.println("brandName: " + n15.brandName);
		System.out.println("material: " + n15.material);
		System.out.println("color: " + n15.color);
		System.out.println("capacity: " + n15.capacity);
		System.out.println("price: " + n15.price);
		System.out.println("isWaterproof: " + n15.isWaterproof);
		System.out.println("isAvailable: " + n15.isAvailable);
		System.out.println("manufacturingDate: " + n15.manufacturingDate);
		System.out.println("expiryDate: " + n15.expiryDate);
		System.out.println("bagType: " + n15.bagType);
		System.out.println("zipperType: " + n15.zipperType);
		System.out.println("weight: " + n15.weight);
		System.out.println("hasLaptopCompartment: " + n15.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n15.countryOfOrigin);
		System.out.println("warrantyMonths: " + n15.warrantyMonths);
		System.out.println("packagingType: " + n15.packagingType);
		System.out.println("height: " + n15.height);
		System.out.println("isTravelFriendly: " + n15.isTravelFriendly);
		System.out.println("feature1: " + n15.feature1);
		System.out.println("feature2: " + n15.feature2);
		System.out.println("feature3: " + n15.feature3);
		System.out.println("hasUSBPort: " + n15.hasUSBPort);
		System.out.println("isAntiTheft: " + n15.isAntiTheft);
		System.out.println("rating: " + n15.rating);


		NovaBackpack n16 = new NovaBackpack();
		n16.productId = 116;
		n16.brandName = "Sample16";
		n16.material = "Sample16";
		n16.color = "Sample16";
		n16.capacity = 26.0;
		n16.price = 26.0;
		n16.isWaterproof = true;
		n16.isAvailable = true;
		n16.manufacturingDate = "Sample16";
		n16.expiryDate = "Sample16";
		n16.bagType = "Sample16";
		n16.zipperType = "Sample16";
		n16.weight = 26.0;
		n16.hasLaptopCompartment = true;
		n16.countryOfOrigin = "Sample16";
		n16.warrantyMonths = 116;
		n16.packagingType = "Sample16";
		n16.height = 26.0;
		n16.isTravelFriendly = true;
		n16.feature1 = "Sample16";
		n16.feature2 = "Sample16";
		n16.feature3 = "Sample16";
		n16.hasUSBPort = true;
		n16.isAntiTheft = true;
		n16.rating = 116;

		System.out.println("----- NovaBackpack 16 -----");
		System.out.println("productId: " + n16.productId);
		System.out.println("brandName: " + n16.brandName);
		System.out.println("material: " + n16.material);
		System.out.println("color: " + n16.color);
		System.out.println("capacity: " + n16.capacity);
		System.out.println("price: " + n16.price);
		System.out.println("isWaterproof: " + n16.isWaterproof);
		System.out.println("isAvailable: " + n16.isAvailable);
		System.out.println("manufacturingDate: " + n16.manufacturingDate);
		System.out.println("expiryDate: " + n16.expiryDate);
		System.out.println("bagType: " + n16.bagType);
		System.out.println("zipperType: " + n16.zipperType);
		System.out.println("weight: " + n16.weight);
		System.out.println("hasLaptopCompartment: " + n16.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n16.countryOfOrigin);
		System.out.println("warrantyMonths: " + n16.warrantyMonths);
		System.out.println("packagingType: " + n16.packagingType);
		System.out.println("height: " + n16.height);
		System.out.println("isTravelFriendly: " + n16.isTravelFriendly);
		System.out.println("feature1: " + n16.feature1);
		System.out.println("feature2: " + n16.feature2);
		System.out.println("feature3: " + n16.feature3);
		System.out.println("hasUSBPort: " + n16.hasUSBPort);
		System.out.println("isAntiTheft: " + n16.isAntiTheft);
		System.out.println("rating: " + n16.rating);


		NovaBackpack n17 = new NovaBackpack();
		n17.productId = 117;
		n17.brandName = "Sample17";
		n17.material = "Sample17";
		n17.color = "Sample17";
		n17.capacity = 27.0;
		n17.price = 27.0;
		n17.isWaterproof = false;
		n17.isAvailable = false;
		n17.manufacturingDate = "Sample17";
		n17.expiryDate = "Sample17";
		n17.bagType = "Sample17";
		n17.zipperType = "Sample17";
		n17.weight = 27.0;
		n17.hasLaptopCompartment = false;
		n17.countryOfOrigin = "Sample17";
		n17.warrantyMonths = 117;
		n17.packagingType = "Sample17";
		n17.height = 27.0;
		n17.isTravelFriendly = false;
		n17.feature1 = "Sample17";
		n17.feature2 = "Sample17";
		n17.feature3 = "Sample17";
		n17.hasUSBPort = false;
		n17.isAntiTheft = false;
		n17.rating = 117;

		System.out.println("----- NovaBackpack 17 -----");
		System.out.println("productId: " + n17.productId);
		System.out.println("brandName: " + n17.brandName);
		System.out.println("material: " + n17.material);
		System.out.println("color: " + n17.color);
		System.out.println("capacity: " + n17.capacity);
		System.out.println("price: " + n17.price);
		System.out.println("isWaterproof: " + n17.isWaterproof);
		System.out.println("isAvailable: " + n17.isAvailable);
		System.out.println("manufacturingDate: " + n17.manufacturingDate);
		System.out.println("expiryDate: " + n17.expiryDate);
		System.out.println("bagType: " + n17.bagType);
		System.out.println("zipperType: " + n17.zipperType);
		System.out.println("weight: " + n17.weight);
		System.out.println("hasLaptopCompartment: " + n17.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n17.countryOfOrigin);
		System.out.println("warrantyMonths: " + n17.warrantyMonths);
		System.out.println("packagingType: " + n17.packagingType);
		System.out.println("height: " + n17.height);
		System.out.println("isTravelFriendly: " + n17.isTravelFriendly);
		System.out.println("feature1: " + n17.feature1);
		System.out.println("feature2: " + n17.feature2);
		System.out.println("feature3: " + n17.feature3);
		System.out.println("hasUSBPort: " + n17.hasUSBPort);
		System.out.println("isAntiTheft: " + n17.isAntiTheft);
		System.out.println("rating: " + n17.rating);


		NovaBackpack n18 = new NovaBackpack();
		n18.productId = 118;
		n18.brandName = "Sample18";
		n18.material = "Sample18";
		n18.color = "Sample18";
		n18.capacity = 28.0;
		n18.price = 28.0;
		n18.isWaterproof = true;
		n18.isAvailable = true;
		n18.manufacturingDate = "Sample18";
		n18.expiryDate = "Sample18";
		n18.bagType = "Sample18";
		n18.zipperType = "Sample18";
		n18.weight = 28.0;
		n18.hasLaptopCompartment = true;
		n18.countryOfOrigin = "Sample18";
		n18.warrantyMonths = 118;
		n18.packagingType = "Sample18";
		n18.height = 28.0;
		n18.isTravelFriendly = true;
		n18.feature1 = "Sample18";
		n18.feature2 = "Sample18";
		n18.feature3 = "Sample18";
		n18.hasUSBPort = true;
		n18.isAntiTheft = true;
		n18.rating = 118;

		System.out.println("----- NovaBackpack 18 -----");
		System.out.println("productId: " + n18.productId);
		System.out.println("brandName: " + n18.brandName);
		System.out.println("material: " + n18.material);
		System.out.println("color: " + n18.color);
		System.out.println("capacity: " + n18.capacity);
		System.out.println("price: " + n18.price);
		System.out.println("isWaterproof: " + n18.isWaterproof);
		System.out.println("isAvailable: " + n18.isAvailable);
		System.out.println("manufacturingDate: " + n18.manufacturingDate);
		System.out.println("expiryDate: " + n18.expiryDate);
		System.out.println("bagType: " + n18.bagType);
		System.out.println("zipperType: " + n18.zipperType);
		System.out.println("weight: " + n18.weight);
		System.out.println("hasLaptopCompartment: " + n18.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n18.countryOfOrigin);
		System.out.println("warrantyMonths: " + n18.warrantyMonths);
		System.out.println("packagingType: " + n18.packagingType);
		System.out.println("height: " + n18.height);
		System.out.println("isTravelFriendly: " + n18.isTravelFriendly);
		System.out.println("feature1: " + n18.feature1);
		System.out.println("feature2: " + n18.feature2);
		System.out.println("feature3: " + n18.feature3);
		System.out.println("hasUSBPort: " + n18.hasUSBPort);
		System.out.println("isAntiTheft: " + n18.isAntiTheft);
		System.out.println("rating: " + n18.rating);


		NovaBackpack n19 = new NovaBackpack();
		n19.productId = 119;
		n19.brandName = "Sample19";
		n19.material = "Sample19";
		n19.color = "Sample19";
		n19.capacity = 29.0;
		n19.price = 29.0;
		n19.isWaterproof = false;
		n19.isAvailable = false;
		n19.manufacturingDate = "Sample19";
		n19.expiryDate = "Sample19";
		n19.bagType = "Sample19";
		n19.zipperType = "Sample19";
		n19.weight = 29.0;
		n19.hasLaptopCompartment = false;
		n19.countryOfOrigin = "Sample19";
		n19.warrantyMonths = 119;
		n19.packagingType = "Sample19";
		n19.height = 29.0;
		n19.isTravelFriendly = false;
		n19.feature1 = "Sample19";
		n19.feature2 = "Sample19";
		n19.feature3 = "Sample19";
		n19.hasUSBPort = false;
		n19.isAntiTheft = false;
		n19.rating = 119;

		System.out.println("----- NovaBackpack 19 -----");
		System.out.println("productId: " + n19.productId);
		System.out.println("brandName: " + n19.brandName);
		System.out.println("material: " + n19.material);
		System.out.println("color: " + n19.color);
		System.out.println("capacity: " + n19.capacity);
		System.out.println("price: " + n19.price);
		System.out.println("isWaterproof: " + n19.isWaterproof);
		System.out.println("isAvailable: " + n19.isAvailable);
		System.out.println("manufacturingDate: " + n19.manufacturingDate);
		System.out.println("expiryDate: " + n19.expiryDate);
		System.out.println("bagType: " + n19.bagType);
		System.out.println("zipperType: " + n19.zipperType);
		System.out.println("weight: " + n19.weight);
		System.out.println("hasLaptopCompartment: " + n19.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n19.countryOfOrigin);
		System.out.println("warrantyMonths: " + n19.warrantyMonths);
		System.out.println("packagingType: " + n19.packagingType);
		System.out.println("height: " + n19.height);
		System.out.println("isTravelFriendly: " + n19.isTravelFriendly);
		System.out.println("feature1: " + n19.feature1);
		System.out.println("feature2: " + n19.feature2);
		System.out.println("feature3: " + n19.feature3);
		System.out.println("hasUSBPort: " + n19.hasUSBPort);
		System.out.println("isAntiTheft: " + n19.isAntiTheft);
		System.out.println("rating: " + n19.rating);


		NovaBackpack n20 = new NovaBackpack();
		n20.productId = 120;
		n20.brandName = "Sample20";
		n20.material = "Sample20";
		n20.color = "Sample20";
		n20.capacity = 30.0;
		n20.price = 30.0;
		n20.isWaterproof = true;
		n20.isAvailable = true;
		n20.manufacturingDate = "Sample20";
		n20.expiryDate = "Sample20";
		n20.bagType = "Sample20";
		n20.zipperType = "Sample20";
		n20.weight = 30.0;
		n20.hasLaptopCompartment = true;
		n20.countryOfOrigin = "Sample20";
		n20.warrantyMonths = 120;
		n20.packagingType = "Sample20";
		n20.height = 30.0;
		n20.isTravelFriendly = true;
		n20.feature1 = "Sample20";
		n20.feature2 = "Sample20";
		n20.feature3 = "Sample20";
		n20.hasUSBPort = true;
		n20.isAntiTheft = true;
		n20.rating = 120;

		System.out.println("----- NovaBackpack 20 -----");
		System.out.println("productId: " + n20.productId);
		System.out.println("brandName: " + n20.brandName);
		System.out.println("material: " + n20.material);
		System.out.println("color: " + n20.color);
		System.out.println("capacity: " + n20.capacity);
		System.out.println("price: " + n20.price);
		System.out.println("isWaterproof: " + n20.isWaterproof);
		System.out.println("isAvailable: " + n20.isAvailable);
		System.out.println("manufacturingDate: " + n20.manufacturingDate);
		System.out.println("expiryDate: " + n20.expiryDate);
		System.out.println("bagType: " + n20.bagType);
		System.out.println("zipperType: " + n20.zipperType);
		System.out.println("weight: " + n20.weight);
		System.out.println("hasLaptopCompartment: " + n20.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n20.countryOfOrigin);
		System.out.println("warrantyMonths: " + n20.warrantyMonths);
		System.out.println("packagingType: " + n20.packagingType);
		System.out.println("height: " + n20.height);
		System.out.println("isTravelFriendly: " + n20.isTravelFriendly);
		System.out.println("feature1: " + n20.feature1);
		System.out.println("feature2: " + n20.feature2);
		System.out.println("feature3: " + n20.feature3);
		System.out.println("hasUSBPort: " + n20.hasUSBPort);
		System.out.println("isAntiTheft: " + n20.isAntiTheft);
		System.out.println("rating: " + n20.rating);


		NovaBackpack n21 = new NovaBackpack();
		n21.productId = 121;
		n21.brandName = "Sample21";
		n21.material = "Sample21";
		n21.color = "Sample21";
		n21.capacity = 31.0;
		n21.price = 31.0;
		n21.isWaterproof = false;
		n21.isAvailable = false;
		n21.manufacturingDate = "Sample21";
		n21.expiryDate = "Sample21";
		n21.bagType = "Sample21";
		n21.zipperType = "Sample21";
		n21.weight = 31.0;
		n21.hasLaptopCompartment = false;
		n21.countryOfOrigin = "Sample21";
		n21.warrantyMonths = 121;
		n21.packagingType = "Sample21";
		n21.height = 31.0;
		n21.isTravelFriendly = false;
		n21.feature1 = "Sample21";
		n21.feature2 = "Sample21";
		n21.feature3 = "Sample21";
		n21.hasUSBPort = false;
		n21.isAntiTheft = false;
		n21.rating = 121;

		System.out.println("----- NovaBackpack 21 -----");
		System.out.println("productId: " + n21.productId);
		System.out.println("brandName: " + n21.brandName);
		System.out.println("material: " + n21.material);
		System.out.println("color: " + n21.color);
		System.out.println("capacity: " + n21.capacity);
		System.out.println("price: " + n21.price);
		System.out.println("isWaterproof: " + n21.isWaterproof);
		System.out.println("isAvailable: " + n21.isAvailable);
		System.out.println("manufacturingDate: " + n21.manufacturingDate);
		System.out.println("expiryDate: " + n21.expiryDate);
		System.out.println("bagType: " + n21.bagType);
		System.out.println("zipperType: " + n21.zipperType);
		System.out.println("weight: " + n21.weight);
		System.out.println("hasLaptopCompartment: " + n21.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n21.countryOfOrigin);
		System.out.println("warrantyMonths: " + n21.warrantyMonths);
		System.out.println("packagingType: " + n21.packagingType);
		System.out.println("height: " + n21.height);
		System.out.println("isTravelFriendly: " + n21.isTravelFriendly);
		System.out.println("feature1: " + n21.feature1);
		System.out.println("feature2: " + n21.feature2);
		System.out.println("feature3: " + n21.feature3);
		System.out.println("hasUSBPort: " + n21.hasUSBPort);
		System.out.println("isAntiTheft: " + n21.isAntiTheft);
		System.out.println("rating: " + n21.rating);


		NovaBackpack n22 = new NovaBackpack();
		n22.productId = 122;
		n22.brandName = "Sample22";
		n22.material = "Sample22";
		n22.color = "Sample22";
		n22.capacity = 32.0;
		n22.price = 32.0;
		n22.isWaterproof = true;
		n22.isAvailable = true;
		n22.manufacturingDate = "Sample22";
		n22.expiryDate = "Sample22";
		n22.bagType = "Sample22";
		n22.zipperType = "Sample22";
		n22.weight = 32.0;
		n22.hasLaptopCompartment = true;
		n22.countryOfOrigin = "Sample22";
		n22.warrantyMonths = 122;
		n22.packagingType = "Sample22";
		n22.height = 32.0;
		n22.isTravelFriendly = true;
		n22.feature1 = "Sample22";
		n22.feature2 = "Sample22";
		n22.feature3 = "Sample22";
		n22.hasUSBPort = true;
		n22.isAntiTheft = true;
		n22.rating = 122;

		System.out.println("----- NovaBackpack 22 -----");
		System.out.println("productId: " + n22.productId);
		System.out.println("brandName: " + n22.brandName);
		System.out.println("material: " + n22.material);
		System.out.println("color: " + n22.color);
		System.out.println("capacity: " + n22.capacity);
		System.out.println("price: " + n22.price);
		System.out.println("isWaterproof: " + n22.isWaterproof);
		System.out.println("isAvailable: " + n22.isAvailable);
		System.out.println("manufacturingDate: " + n22.manufacturingDate);
		System.out.println("expiryDate: " + n22.expiryDate);
		System.out.println("bagType: " + n22.bagType);
		System.out.println("zipperType: " + n22.zipperType);
		System.out.println("weight: " + n22.weight);
		System.out.println("hasLaptopCompartment: " + n22.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n22.countryOfOrigin);
		System.out.println("warrantyMonths: " + n22.warrantyMonths);
		System.out.println("packagingType: " + n22.packagingType);
		System.out.println("height: " + n22.height);
		System.out.println("isTravelFriendly: " + n22.isTravelFriendly);
		System.out.println("feature1: " + n22.feature1);
		System.out.println("feature2: " + n22.feature2);
		System.out.println("feature3: " + n22.feature3);
		System.out.println("hasUSBPort: " + n22.hasUSBPort);
		System.out.println("isAntiTheft: " + n22.isAntiTheft);
		System.out.println("rating: " + n22.rating);


		NovaBackpack n23 = new NovaBackpack();
		n23.productId = 123;
		n23.brandName = "Sample23";
		n23.material = "Sample23";
		n23.color = "Sample23";
		n23.capacity = 33.0;
		n23.price = 33.0;
		n23.isWaterproof = false;
		n23.isAvailable = false;
		n23.manufacturingDate = "Sample23";
		n23.expiryDate = "Sample23";
		n23.bagType = "Sample23";
		n23.zipperType = "Sample23";
		n23.weight = 33.0;
		n23.hasLaptopCompartment = false;
		n23.countryOfOrigin = "Sample23";
		n23.warrantyMonths = 123;
		n23.packagingType = "Sample23";
		n23.height = 33.0;
		n23.isTravelFriendly = false;
		n23.feature1 = "Sample23";
		n23.feature2 = "Sample23";
		n23.feature3 = "Sample23";
		n23.hasUSBPort = false;
		n23.isAntiTheft = false;
		n23.rating = 123;

		System.out.println("----- NovaBackpack 23 -----");
		System.out.println("productId: " + n23.productId);
		System.out.println("brandName: " + n23.brandName);
		System.out.println("material: " + n23.material);
		System.out.println("color: " + n23.color);
		System.out.println("capacity: " + n23.capacity);
		System.out.println("price: " + n23.price);
		System.out.println("isWaterproof: " + n23.isWaterproof);
		System.out.println("isAvailable: " + n23.isAvailable);
		System.out.println("manufacturingDate: " + n23.manufacturingDate);
		System.out.println("expiryDate: " + n23.expiryDate);
		System.out.println("bagType: " + n23.bagType);
		System.out.println("zipperType: " + n23.zipperType);
		System.out.println("weight: " + n23.weight);
		System.out.println("hasLaptopCompartment: " + n23.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n23.countryOfOrigin);
		System.out.println("warrantyMonths: " + n23.warrantyMonths);
		System.out.println("packagingType: " + n23.packagingType);
		System.out.println("height: " + n23.height);
		System.out.println("isTravelFriendly: " + n23.isTravelFriendly);
		System.out.println("feature1: " + n23.feature1);
		System.out.println("feature2: " + n23.feature2);
		System.out.println("feature3: " + n23.feature3);
		System.out.println("hasUSBPort: " + n23.hasUSBPort);
		System.out.println("isAntiTheft: " + n23.isAntiTheft);
		System.out.println("rating: " + n23.rating);


		NovaBackpack n24 = new NovaBackpack();
		n24.productId = 124;
		n24.brandName = "Sample24";
		n24.material = "Sample24";
		n24.color = "Sample24";
		n24.capacity = 34.0;
		n24.price = 34.0;
		n24.isWaterproof = true;
		n24.isAvailable = true;
		n24.manufacturingDate = "Sample24";
		n24.expiryDate = "Sample24";
		n24.bagType = "Sample24";
		n24.zipperType = "Sample24";
		n24.weight = 34.0;
		n24.hasLaptopCompartment = true;
		n24.countryOfOrigin = "Sample24";
		n24.warrantyMonths = 124;
		n24.packagingType = "Sample24";
		n24.height = 34.0;
		n24.isTravelFriendly = true;
		n24.feature1 = "Sample24";
		n24.feature2 = "Sample24";
		n24.feature3 = "Sample24";
		n24.hasUSBPort = true;
		n24.isAntiTheft = true;
		n24.rating = 124;

		System.out.println("----- NovaBackpack 24 -----");
		System.out.println("productId: " + n24.productId);
		System.out.println("brandName: " + n24.brandName);
		System.out.println("material: " + n24.material);
		System.out.println("color: " + n24.color);
		System.out.println("capacity: " + n24.capacity);
		System.out.println("price: " + n24.price);
		System.out.println("isWaterproof: " + n24.isWaterproof);
		System.out.println("isAvailable: " + n24.isAvailable);
		System.out.println("manufacturingDate: " + n24.manufacturingDate);
		System.out.println("expiryDate: " + n24.expiryDate);
		System.out.println("bagType: " + n24.bagType);
		System.out.println("zipperType: " + n24.zipperType);
		System.out.println("weight: " + n24.weight);
		System.out.println("hasLaptopCompartment: " + n24.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n24.countryOfOrigin);
		System.out.println("warrantyMonths: " + n24.warrantyMonths);
		System.out.println("packagingType: " + n24.packagingType);
		System.out.println("height: " + n24.height);
		System.out.println("isTravelFriendly: " + n24.isTravelFriendly);
		System.out.println("feature1: " + n24.feature1);
		System.out.println("feature2: " + n24.feature2);
		System.out.println("feature3: " + n24.feature3);
		System.out.println("hasUSBPort: " + n24.hasUSBPort);
		System.out.println("isAntiTheft: " + n24.isAntiTheft);
		System.out.println("rating: " + n24.rating);


		NovaBackpack n25 = new NovaBackpack();
		n25.productId = 125;
		n25.brandName = "Sample25";
		n25.material = "Sample25";
		n25.color = "Sample25";
		n25.capacity = 35.0;
		n25.price = 35.0;
		n25.isWaterproof = false;
		n25.isAvailable = false;
		n25.manufacturingDate = "Sample25";
		n25.expiryDate = "Sample25";
		n25.bagType = "Sample25";
		n25.zipperType = "Sample25";
		n25.weight = 35.0;
		n25.hasLaptopCompartment = false;
		n25.countryOfOrigin = "Sample25";
		n25.warrantyMonths = 125;
		n25.packagingType = "Sample25";
		n25.height = 35.0;
		n25.isTravelFriendly = false;
		n25.feature1 = "Sample25";
		n25.feature2 = "Sample25";
		n25.feature3 = "Sample25";
		n25.hasUSBPort = false;
		n25.isAntiTheft = false;
		n25.rating = 125;

		System.out.println("----- NovaBackpack 25 -----");
		System.out.println("productId: " + n25.productId);
		System.out.println("brandName: " + n25.brandName);
		System.out.println("material: " + n25.material);
		System.out.println("color: " + n25.color);
		System.out.println("capacity: " + n25.capacity);
		System.out.println("price: " + n25.price);
		System.out.println("isWaterproof: " + n25.isWaterproof);
		System.out.println("isAvailable: " + n25.isAvailable);
		System.out.println("manufacturingDate: " + n25.manufacturingDate);
		System.out.println("expiryDate: " + n25.expiryDate);
		System.out.println("bagType: " + n25.bagType);
		System.out.println("zipperType: " + n25.zipperType);
		System.out.println("weight: " + n25.weight);
		System.out.println("hasLaptopCompartment: " + n25.hasLaptopCompartment);
		System.out.println("countryOfOrigin: " + n25.countryOfOrigin);
		System.out.println("warrantyMonths: " + n25.warrantyMonths);
		System.out.println("packagingType: " + n25.packagingType);
		System.out.println("height: " + n25.height);
		System.out.println("isTravelFriendly: " + n25.isTravelFriendly);
		System.out.println("feature1: " + n25.feature1);
		System.out.println("feature2: " + n25.feature2);
		System.out.println("feature3: " + n25.feature3);
		System.out.println("hasUSBPort: " + n25.hasUSBPort);
		System.out.println("isAntiTheft: " + n25.isAntiTheft);
		System.out.println("rating: " + n25.rating);


	}
}
