class OrbitWatchRunner{
	public static void main(String[] args) {

		OrbitWatch o1 = new OrbitWatch();
		o1.productId = 101;
		o1.brandName = "Sample1";
		o1.strapMaterial = "Sample1";
		o1.color = "Sample1";
		o1.dialSize = 11.0;
		o1.price = 11.0;
		o1.isDigital = false;
		o1.isAvailable = false;
		o1.manufacturingDate = "Sample1";
		o1.expiryDate = "Sample1";
		o1.movementType = "Sample1";
		o1.glassType = "Sample1";
		o1.weight = 11.0;
		o1.isWaterResistant = false;
		o1.countryOfOrigin = "Sample1";
		o1.warrantyMonths = 101;
		o1.packagingType = "Sample1";
		o1.thickness = 11.0;
		o1.isShockResistant = false;
		o1.feature1 = "Sample1";
		o1.feature2 = "Sample1";
		o1.feature3 = "Sample1";
		o1.hasAlarm = false;
		o1.hasBacklight = false;
		o1.rating = 101;

		System.out.println("----- OrbitWatch 1 -----");
		System.out.println("productId: " + o1.productId);
		System.out.println("brandName: " + o1.brandName);
		System.out.println("strapMaterial: " + o1.strapMaterial);
		System.out.println("color: " + o1.color);
		System.out.println("dialSize: " + o1.dialSize);
		System.out.println("price: " + o1.price);
		System.out.println("isDigital: " + o1.isDigital);
		System.out.println("isAvailable: " + o1.isAvailable);
		System.out.println("manufacturingDate: " + o1.manufacturingDate);
		System.out.println("expiryDate: " + o1.expiryDate);
		System.out.println("movementType: " + o1.movementType);
		System.out.println("glassType: " + o1.glassType);
		System.out.println("weight: " + o1.weight);
		System.out.println("isWaterResistant: " + o1.isWaterResistant);
		System.out.println("countryOfOrigin: " + o1.countryOfOrigin);
		System.out.println("warrantyMonths: " + o1.warrantyMonths);
		System.out.println("packagingType: " + o1.packagingType);
		System.out.println("thickness: " + o1.thickness);
		System.out.println("isShockResistant: " + o1.isShockResistant);
		System.out.println("feature1: " + o1.feature1);
		System.out.println("feature2: " + o1.feature2);
		System.out.println("feature3: " + o1.feature3);
		System.out.println("hasAlarm: " + o1.hasAlarm);
		System.out.println("hasBacklight: " + o1.hasBacklight);
		System.out.println("rating: " + o1.rating);


		OrbitWatch o2 = new OrbitWatch();
		o2.productId = 102;
		o2.brandName = "Sample2";
		o2.strapMaterial = "Sample2";
		o2.color = "Sample2";
		o2.dialSize = 12.0;
		o2.price = 12.0;
		o2.isDigital = true;
		o2.isAvailable = true;
		o2.manufacturingDate = "Sample2";
		o2.expiryDate = "Sample2";
		o2.movementType = "Sample2";
		o2.glassType = "Sample2";
		o2.weight = 12.0;
		o2.isWaterResistant = true;
		o2.countryOfOrigin = "Sample2";
		o2.warrantyMonths = 102;
		o2.packagingType = "Sample2";
		o2.thickness = 12.0;
		o2.isShockResistant = true;
		o2.feature1 = "Sample2";
		o2.feature2 = "Sample2";
		o2.feature3 = "Sample2";
		o2.hasAlarm = true;
		o2.hasBacklight = true;
		o2.rating = 102;

		System.out.println("----- OrbitWatch 2 -----");
		System.out.println("productId: " + o2.productId);
		System.out.println("brandName: " + o2.brandName);
		System.out.println("strapMaterial: " + o2.strapMaterial);
		System.out.println("color: " + o2.color);
		System.out.println("dialSize: " + o2.dialSize);
		System.out.println("price: " + o2.price);
		System.out.println("isDigital: " + o2.isDigital);
		System.out.println("isAvailable: " + o2.isAvailable);
		System.out.println("manufacturingDate: " + o2.manufacturingDate);
		System.out.println("expiryDate: " + o2.expiryDate);
		System.out.println("movementType: " + o2.movementType);
		System.out.println("glassType: " + o2.glassType);
		System.out.println("weight: " + o2.weight);
		System.out.println("isWaterResistant: " + o2.isWaterResistant);
		System.out.println("countryOfOrigin: " + o2.countryOfOrigin);
		System.out.println("warrantyMonths: " + o2.warrantyMonths);
		System.out.println("packagingType: " + o2.packagingType);
		System.out.println("thickness: " + o2.thickness);
		System.out.println("isShockResistant: " + o2.isShockResistant);
		System.out.println("feature1: " + o2.feature1);
		System.out.println("feature2: " + o2.feature2);
		System.out.println("feature3: " + o2.feature3);
		System.out.println("hasAlarm: " + o2.hasAlarm);
		System.out.println("hasBacklight: " + o2.hasBacklight);
		System.out.println("rating: " + o2.rating);


		OrbitWatch o3 = new OrbitWatch();
		o3.productId = 103;
		o3.brandName = "Sample3";
		o3.strapMaterial = "Sample3";
		o3.color = "Sample3";
		o3.dialSize = 13.0;
		o3.price = 13.0;
		o3.isDigital = false;
		o3.isAvailable = false;
		o3.manufacturingDate = "Sample3";
		o3.expiryDate = "Sample3";
		o3.movementType = "Sample3";
		o3.glassType = "Sample3";
		o3.weight = 13.0;
		o3.isWaterResistant = false;
		o3.countryOfOrigin = "Sample3";
		o3.warrantyMonths = 103;
		o3.packagingType = "Sample3";
		o3.thickness = 13.0;
		o3.isShockResistant = false;
		o3.feature1 = "Sample3";
		o3.feature2 = "Sample3";
		o3.feature3 = "Sample3";
		o3.hasAlarm = false;
		o3.hasBacklight = false;
		o3.rating = 103;

		System.out.println("----- OrbitWatch 3 -----");
		System.out.println("productId: " + o3.productId);
		System.out.println("brandName: " + o3.brandName);
		System.out.println("strapMaterial: " + o3.strapMaterial);
		System.out.println("color: " + o3.color);
		System.out.println("dialSize: " + o3.dialSize);
		System.out.println("price: " + o3.price);
		System.out.println("isDigital: " + o3.isDigital);
		System.out.println("isAvailable: " + o3.isAvailable);
		System.out.println("manufacturingDate: " + o3.manufacturingDate);
		System.out.println("expiryDate: " + o3.expiryDate);
		System.out.println("movementType: " + o3.movementType);
		System.out.println("glassType: " + o3.glassType);
		System.out.println("weight: " + o3.weight);
		System.out.println("isWaterResistant: " + o3.isWaterResistant);
		System.out.println("countryOfOrigin: " + o3.countryOfOrigin);
		System.out.println("warrantyMonths: " + o3.warrantyMonths);
		System.out.println("packagingType: " + o3.packagingType);
		System.out.println("thickness: " + o3.thickness);
		System.out.println("isShockResistant: " + o3.isShockResistant);
		System.out.println("feature1: " + o3.feature1);
		System.out.println("feature2: " + o3.feature2);
		System.out.println("feature3: " + o3.feature3);
		System.out.println("hasAlarm: " + o3.hasAlarm);
		System.out.println("hasBacklight: " + o3.hasBacklight);
		System.out.println("rating: " + o3.rating);


		OrbitWatch o4 = new OrbitWatch();
		o4.productId = 104;
		o4.brandName = "Sample4";
		o4.strapMaterial = "Sample4";
		o4.color = "Sample4";
		o4.dialSize = 14.0;
		o4.price = 14.0;
		o4.isDigital = true;
		o4.isAvailable = true;
		o4.manufacturingDate = "Sample4";
		o4.expiryDate = "Sample4";
		o4.movementType = "Sample4";
		o4.glassType = "Sample4";
		o4.weight = 14.0;
		o4.isWaterResistant = true;
		o4.countryOfOrigin = "Sample4";
		o4.warrantyMonths = 104;
		o4.packagingType = "Sample4";
		o4.thickness = 14.0;
		o4.isShockResistant = true;
		o4.feature1 = "Sample4";
		o4.feature2 = "Sample4";
		o4.feature3 = "Sample4";
		o4.hasAlarm = true;
		o4.hasBacklight = true;
		o4.rating = 104;

		System.out.println("----- OrbitWatch 4 -----");
		System.out.println("productId: " + o4.productId);
		System.out.println("brandName: " + o4.brandName);
		System.out.println("strapMaterial: " + o4.strapMaterial);
		System.out.println("color: " + o4.color);
		System.out.println("dialSize: " + o4.dialSize);
		System.out.println("price: " + o4.price);
		System.out.println("isDigital: " + o4.isDigital);
		System.out.println("isAvailable: " + o4.isAvailable);
		System.out.println("manufacturingDate: " + o4.manufacturingDate);
		System.out.println("expiryDate: " + o4.expiryDate);
		System.out.println("movementType: " + o4.movementType);
		System.out.println("glassType: " + o4.glassType);
		System.out.println("weight: " + o4.weight);
		System.out.println("isWaterResistant: " + o4.isWaterResistant);
		System.out.println("countryOfOrigin: " + o4.countryOfOrigin);
		System.out.println("warrantyMonths: " + o4.warrantyMonths);
		System.out.println("packagingType: " + o4.packagingType);
		System.out.println("thickness: " + o4.thickness);
		System.out.println("isShockResistant: " + o4.isShockResistant);
		System.out.println("feature1: " + o4.feature1);
		System.out.println("feature2: " + o4.feature2);
		System.out.println("feature3: " + o4.feature3);
		System.out.println("hasAlarm: " + o4.hasAlarm);
		System.out.println("hasBacklight: " + o4.hasBacklight);
		System.out.println("rating: " + o4.rating);


		OrbitWatch o5 = new OrbitWatch();
		o5.productId = 105;
		o5.brandName = "Sample5";
		o5.strapMaterial = "Sample5";
		o5.color = "Sample5";
		o5.dialSize = 15.0;
		o5.price = 15.0;
		o5.isDigital = false;
		o5.isAvailable = false;
		o5.manufacturingDate = "Sample5";
		o5.expiryDate = "Sample5";
		o5.movementType = "Sample5";
		o5.glassType = "Sample5";
		o5.weight = 15.0;
		o5.isWaterResistant = false;
		o5.countryOfOrigin = "Sample5";
		o5.warrantyMonths = 105;
		o5.packagingType = "Sample5";
		o5.thickness = 15.0;
		o5.isShockResistant = false;
		o5.feature1 = "Sample5";
		o5.feature2 = "Sample5";
		o5.feature3 = "Sample5";
		o5.hasAlarm = false;
		o5.hasBacklight = false;
		o5.rating = 105;

		System.out.println("----- OrbitWatch 5 -----");
		System.out.println("productId: " + o5.productId);
		System.out.println("brandName: " + o5.brandName);
		System.out.println("strapMaterial: " + o5.strapMaterial);
		System.out.println("color: " + o5.color);
		System.out.println("dialSize: " + o5.dialSize);
		System.out.println("price: " + o5.price);
		System.out.println("isDigital: " + o5.isDigital);
		System.out.println("isAvailable: " + o5.isAvailable);
		System.out.println("manufacturingDate: " + o5.manufacturingDate);
		System.out.println("expiryDate: " + o5.expiryDate);
		System.out.println("movementType: " + o5.movementType);
		System.out.println("glassType: " + o5.glassType);
		System.out.println("weight: " + o5.weight);
		System.out.println("isWaterResistant: " + o5.isWaterResistant);
		System.out.println("countryOfOrigin: " + o5.countryOfOrigin);
		System.out.println("warrantyMonths: " + o5.warrantyMonths);
		System.out.println("packagingType: " + o5.packagingType);
		System.out.println("thickness: " + o5.thickness);
		System.out.println("isShockResistant: " + o5.isShockResistant);
		System.out.println("feature1: " + o5.feature1);
		System.out.println("feature2: " + o5.feature2);
		System.out.println("feature3: " + o5.feature3);
		System.out.println("hasAlarm: " + o5.hasAlarm);
		System.out.println("hasBacklight: " + o5.hasBacklight);
		System.out.println("rating: " + o5.rating);


		OrbitWatch o6 = new OrbitWatch();
		o6.productId = 106;
		o6.brandName = "Sample6";
		o6.strapMaterial = "Sample6";
		o6.color = "Sample6";
		o6.dialSize = 16.0;
		o6.price = 16.0;
		o6.isDigital = true;
		o6.isAvailable = true;
		o6.manufacturingDate = "Sample6";
		o6.expiryDate = "Sample6";
		o6.movementType = "Sample6";
		o6.glassType = "Sample6";
		o6.weight = 16.0;
		o6.isWaterResistant = true;
		o6.countryOfOrigin = "Sample6";
		o6.warrantyMonths = 106;
		o6.packagingType = "Sample6";
		o6.thickness = 16.0;
		o6.isShockResistant = true;
		o6.feature1 = "Sample6";
		o6.feature2 = "Sample6";
		o6.feature3 = "Sample6";
		o6.hasAlarm = true;
		o6.hasBacklight = true;
		o6.rating = 106;

		System.out.println("----- OrbitWatch 6 -----");
		System.out.println("productId: " + o6.productId);
		System.out.println("brandName: " + o6.brandName);
		System.out.println("strapMaterial: " + o6.strapMaterial);
		System.out.println("color: " + o6.color);
		System.out.println("dialSize: " + o6.dialSize);
		System.out.println("price: " + o6.price);
		System.out.println("isDigital: " + o6.isDigital);
		System.out.println("isAvailable: " + o6.isAvailable);
		System.out.println("manufacturingDate: " + o6.manufacturingDate);
		System.out.println("expiryDate: " + o6.expiryDate);
		System.out.println("movementType: " + o6.movementType);
		System.out.println("glassType: " + o6.glassType);
		System.out.println("weight: " + o6.weight);
		System.out.println("isWaterResistant: " + o6.isWaterResistant);
		System.out.println("countryOfOrigin: " + o6.countryOfOrigin);
		System.out.println("warrantyMonths: " + o6.warrantyMonths);
		System.out.println("packagingType: " + o6.packagingType);
		System.out.println("thickness: " + o6.thickness);
		System.out.println("isShockResistant: " + o6.isShockResistant);
		System.out.println("feature1: " + o6.feature1);
		System.out.println("feature2: " + o6.feature2);
		System.out.println("feature3: " + o6.feature3);
		System.out.println("hasAlarm: " + o6.hasAlarm);
		System.out.println("hasBacklight: " + o6.hasBacklight);
		System.out.println("rating: " + o6.rating);


		OrbitWatch o7 = new OrbitWatch();
		o7.productId = 107;
		o7.brandName = "Sample7";
		o7.strapMaterial = "Sample7";
		o7.color = "Sample7";
		o7.dialSize = 17.0;
		o7.price = 17.0;
		o7.isDigital = false;
		o7.isAvailable = false;
		o7.manufacturingDate = "Sample7";
		o7.expiryDate = "Sample7";
		o7.movementType = "Sample7";
		o7.glassType = "Sample7";
		o7.weight = 17.0;
		o7.isWaterResistant = false;
		o7.countryOfOrigin = "Sample7";
		o7.warrantyMonths = 107;
		o7.packagingType = "Sample7";
		o7.thickness = 17.0;
		o7.isShockResistant = false;
		o7.feature1 = "Sample7";
		o7.feature2 = "Sample7";
		o7.feature3 = "Sample7";
		o7.hasAlarm = false;
		o7.hasBacklight = false;
		o7.rating = 107;

		System.out.println("----- OrbitWatch 7 -----");
		System.out.println("productId: " + o7.productId);
		System.out.println("brandName: " + o7.brandName);
		System.out.println("strapMaterial: " + o7.strapMaterial);
		System.out.println("color: " + o7.color);
		System.out.println("dialSize: " + o7.dialSize);
		System.out.println("price: " + o7.price);
		System.out.println("isDigital: " + o7.isDigital);
		System.out.println("isAvailable: " + o7.isAvailable);
		System.out.println("manufacturingDate: " + o7.manufacturingDate);
		System.out.println("expiryDate: " + o7.expiryDate);
		System.out.println("movementType: " + o7.movementType);
		System.out.println("glassType: " + o7.glassType);
		System.out.println("weight: " + o7.weight);
		System.out.println("isWaterResistant: " + o7.isWaterResistant);
		System.out.println("countryOfOrigin: " + o7.countryOfOrigin);
		System.out.println("warrantyMonths: " + o7.warrantyMonths);
		System.out.println("packagingType: " + o7.packagingType);
		System.out.println("thickness: " + o7.thickness);
		System.out.println("isShockResistant: " + o7.isShockResistant);
		System.out.println("feature1: " + o7.feature1);
		System.out.println("feature2: " + o7.feature2);
		System.out.println("feature3: " + o7.feature3);
		System.out.println("hasAlarm: " + o7.hasAlarm);
		System.out.println("hasBacklight: " + o7.hasBacklight);
		System.out.println("rating: " + o7.rating);


		OrbitWatch o8 = new OrbitWatch();
		o8.productId = 108;
		o8.brandName = "Sample8";
		o8.strapMaterial = "Sample8";
		o8.color = "Sample8";
		o8.dialSize = 18.0;
		o8.price = 18.0;
		o8.isDigital = true;
		o8.isAvailable = true;
		o8.manufacturingDate = "Sample8";
		o8.expiryDate = "Sample8";
		o8.movementType = "Sample8";
		o8.glassType = "Sample8";
		o8.weight = 18.0;
		o8.isWaterResistant = true;
		o8.countryOfOrigin = "Sample8";
		o8.warrantyMonths = 108;
		o8.packagingType = "Sample8";
		o8.thickness = 18.0;
		o8.isShockResistant = true;
		o8.feature1 = "Sample8";
		o8.feature2 = "Sample8";
		o8.feature3 = "Sample8";
		o8.hasAlarm = true;
		o8.hasBacklight = true;
		o8.rating = 108;

		System.out.println("----- OrbitWatch 8 -----");
		System.out.println("productId: " + o8.productId);
		System.out.println("brandName: " + o8.brandName);
		System.out.println("strapMaterial: " + o8.strapMaterial);
		System.out.println("color: " + o8.color);
		System.out.println("dialSize: " + o8.dialSize);
		System.out.println("price: " + o8.price);
		System.out.println("isDigital: " + o8.isDigital);
		System.out.println("isAvailable: " + o8.isAvailable);
		System.out.println("manufacturingDate: " + o8.manufacturingDate);
		System.out.println("expiryDate: " + o8.expiryDate);
		System.out.println("movementType: " + o8.movementType);
		System.out.println("glassType: " + o8.glassType);
		System.out.println("weight: " + o8.weight);
		System.out.println("isWaterResistant: " + o8.isWaterResistant);
		System.out.println("countryOfOrigin: " + o8.countryOfOrigin);
		System.out.println("warrantyMonths: " + o8.warrantyMonths);
		System.out.println("packagingType: " + o8.packagingType);
		System.out.println("thickness: " + o8.thickness);
		System.out.println("isShockResistant: " + o8.isShockResistant);
		System.out.println("feature1: " + o8.feature1);
		System.out.println("feature2: " + o8.feature2);
		System.out.println("feature3: " + o8.feature3);
		System.out.println("hasAlarm: " + o8.hasAlarm);
		System.out.println("hasBacklight: " + o8.hasBacklight);
		System.out.println("rating: " + o8.rating);


		OrbitWatch o9 = new OrbitWatch();
		o9.productId = 109;
		o9.brandName = "Sample9";
		o9.strapMaterial = "Sample9";
		o9.color = "Sample9";
		o9.dialSize = 19.0;
		o9.price = 19.0;
		o9.isDigital = false;
		o9.isAvailable = false;
		o9.manufacturingDate = "Sample9";
		o9.expiryDate = "Sample9";
		o9.movementType = "Sample9";
		o9.glassType = "Sample9";
		o9.weight = 19.0;
		o9.isWaterResistant = false;
		o9.countryOfOrigin = "Sample9";
		o9.warrantyMonths = 109;
		o9.packagingType = "Sample9";
		o9.thickness = 19.0;
		o9.isShockResistant = false;
		o9.feature1 = "Sample9";
		o9.feature2 = "Sample9";
		o9.feature3 = "Sample9";
		o9.hasAlarm = false;
		o9.hasBacklight = false;
		o9.rating = 109;

		System.out.println("----- OrbitWatch 9 -----");
		System.out.println("productId: " + o9.productId);
		System.out.println("brandName: " + o9.brandName);
		System.out.println("strapMaterial: " + o9.strapMaterial);
		System.out.println("color: " + o9.color);
		System.out.println("dialSize: " + o9.dialSize);
		System.out.println("price: " + o9.price);
		System.out.println("isDigital: " + o9.isDigital);
		System.out.println("isAvailable: " + o9.isAvailable);
		System.out.println("manufacturingDate: " + o9.manufacturingDate);
		System.out.println("expiryDate: " + o9.expiryDate);
		System.out.println("movementType: " + o9.movementType);
		System.out.println("glassType: " + o9.glassType);
		System.out.println("weight: " + o9.weight);
		System.out.println("isWaterResistant: " + o9.isWaterResistant);
		System.out.println("countryOfOrigin: " + o9.countryOfOrigin);
		System.out.println("warrantyMonths: " + o9.warrantyMonths);
		System.out.println("packagingType: " + o9.packagingType);
		System.out.println("thickness: " + o9.thickness);
		System.out.println("isShockResistant: " + o9.isShockResistant);
		System.out.println("feature1: " + o9.feature1);
		System.out.println("feature2: " + o9.feature2);
		System.out.println("feature3: " + o9.feature3);
		System.out.println("hasAlarm: " + o9.hasAlarm);
		System.out.println("hasBacklight: " + o9.hasBacklight);
		System.out.println("rating: " + o9.rating);


		OrbitWatch o10 = new OrbitWatch();
		o10.productId = 110;
		o10.brandName = "Sample10";
		o10.strapMaterial = "Sample10";
		o10.color = "Sample10";
		o10.dialSize = 20.0;
		o10.price = 20.0;
		o10.isDigital = true;
		o10.isAvailable = true;
		o10.manufacturingDate = "Sample10";
		o10.expiryDate = "Sample10";
		o10.movementType = "Sample10";
		o10.glassType = "Sample10";
		o10.weight = 20.0;
		o10.isWaterResistant = true;
		o10.countryOfOrigin = "Sample10";
		o10.warrantyMonths = 110;
		o10.packagingType = "Sample10";
		o10.thickness = 20.0;
		o10.isShockResistant = true;
		o10.feature1 = "Sample10";
		o10.feature2 = "Sample10";
		o10.feature3 = "Sample10";
		o10.hasAlarm = true;
		o10.hasBacklight = true;
		o10.rating = 110;

		System.out.println("----- OrbitWatch 10 -----");
		System.out.println("productId: " + o10.productId);
		System.out.println("brandName: " + o10.brandName);
		System.out.println("strapMaterial: " + o10.strapMaterial);
		System.out.println("color: " + o10.color);
		System.out.println("dialSize: " + o10.dialSize);
		System.out.println("price: " + o10.price);
		System.out.println("isDigital: " + o10.isDigital);
		System.out.println("isAvailable: " + o10.isAvailable);
		System.out.println("manufacturingDate: " + o10.manufacturingDate);
		System.out.println("expiryDate: " + o10.expiryDate);
		System.out.println("movementType: " + o10.movementType);
		System.out.println("glassType: " + o10.glassType);
		System.out.println("weight: " + o10.weight);
		System.out.println("isWaterResistant: " + o10.isWaterResistant);
		System.out.println("countryOfOrigin: " + o10.countryOfOrigin);
		System.out.println("warrantyMonths: " + o10.warrantyMonths);
		System.out.println("packagingType: " + o10.packagingType);
		System.out.println("thickness: " + o10.thickness);
		System.out.println("isShockResistant: " + o10.isShockResistant);
		System.out.println("feature1: " + o10.feature1);
		System.out.println("feature2: " + o10.feature2);
		System.out.println("feature3: " + o10.feature3);
		System.out.println("hasAlarm: " + o10.hasAlarm);
		System.out.println("hasBacklight: " + o10.hasBacklight);
		System.out.println("rating: " + o10.rating);


		OrbitWatch o11 = new OrbitWatch();
		o11.productId = 111;
		o11.brandName = "Sample11";
		o11.strapMaterial = "Sample11";
		o11.color = "Sample11";
		o11.dialSize = 21.0;
		o11.price = 21.0;
		o11.isDigital = false;
		o11.isAvailable = false;
		o11.manufacturingDate = "Sample11";
		o11.expiryDate = "Sample11";
		o11.movementType = "Sample11";
		o11.glassType = "Sample11";
		o11.weight = 21.0;
		o11.isWaterResistant = false;
		o11.countryOfOrigin = "Sample11";
		o11.warrantyMonths = 111;
		o11.packagingType = "Sample11";
		o11.thickness = 21.0;
		o11.isShockResistant = false;
		o11.feature1 = "Sample11";
		o11.feature2 = "Sample11";
		o11.feature3 = "Sample11";
		o11.hasAlarm = false;
		o11.hasBacklight = false;
		o11.rating = 111;

		System.out.println("----- OrbitWatch 11 -----");
		System.out.println("productId: " + o11.productId);
		System.out.println("brandName: " + o11.brandName);
		System.out.println("strapMaterial: " + o11.strapMaterial);
		System.out.println("color: " + o11.color);
		System.out.println("dialSize: " + o11.dialSize);
		System.out.println("price: " + o11.price);
		System.out.println("isDigital: " + o11.isDigital);
		System.out.println("isAvailable: " + o11.isAvailable);
		System.out.println("manufacturingDate: " + o11.manufacturingDate);
		System.out.println("expiryDate: " + o11.expiryDate);
		System.out.println("movementType: " + o11.movementType);
		System.out.println("glassType: " + o11.glassType);
		System.out.println("weight: " + o11.weight);
		System.out.println("isWaterResistant: " + o11.isWaterResistant);
		System.out.println("countryOfOrigin: " + o11.countryOfOrigin);
		System.out.println("warrantyMonths: " + o11.warrantyMonths);
		System.out.println("packagingType: " + o11.packagingType);
		System.out.println("thickness: " + o11.thickness);
		System.out.println("isShockResistant: " + o11.isShockResistant);
		System.out.println("feature1: " + o11.feature1);
		System.out.println("feature2: " + o11.feature2);
		System.out.println("feature3: " + o11.feature3);
		System.out.println("hasAlarm: " + o11.hasAlarm);
		System.out.println("hasBacklight: " + o11.hasBacklight);
		System.out.println("rating: " + o11.rating);


		OrbitWatch o12 = new OrbitWatch();
		o12.productId = 112;
		o12.brandName = "Sample12";
		o12.strapMaterial = "Sample12";
		o12.color = "Sample12";
		o12.dialSize = 22.0;
		o12.price = 22.0;
		o12.isDigital = true;
		o12.isAvailable = true;
		o12.manufacturingDate = "Sample12";
		o12.expiryDate = "Sample12";
		o12.movementType = "Sample12";
		o12.glassType = "Sample12";
		o12.weight = 22.0;
		o12.isWaterResistant = true;
		o12.countryOfOrigin = "Sample12";
		o12.warrantyMonths = 112;
		o12.packagingType = "Sample12";
		o12.thickness = 22.0;
		o12.isShockResistant = true;
		o12.feature1 = "Sample12";
		o12.feature2 = "Sample12";
		o12.feature3 = "Sample12";
		o12.hasAlarm = true;
		o12.hasBacklight = true;
		o12.rating = 112;

		System.out.println("----- OrbitWatch 12 -----");
		System.out.println("productId: " + o12.productId);
		System.out.println("brandName: " + o12.brandName);
		System.out.println("strapMaterial: " + o12.strapMaterial);
		System.out.println("color: " + o12.color);
		System.out.println("dialSize: " + o12.dialSize);
		System.out.println("price: " + o12.price);
		System.out.println("isDigital: " + o12.isDigital);
		System.out.println("isAvailable: " + o12.isAvailable);
		System.out.println("manufacturingDate: " + o12.manufacturingDate);
		System.out.println("expiryDate: " + o12.expiryDate);
		System.out.println("movementType: " + o12.movementType);
		System.out.println("glassType: " + o12.glassType);
		System.out.println("weight: " + o12.weight);
		System.out.println("isWaterResistant: " + o12.isWaterResistant);
		System.out.println("countryOfOrigin: " + o12.countryOfOrigin);
		System.out.println("warrantyMonths: " + o12.warrantyMonths);
		System.out.println("packagingType: " + o12.packagingType);
		System.out.println("thickness: " + o12.thickness);
		System.out.println("isShockResistant: " + o12.isShockResistant);
		System.out.println("feature1: " + o12.feature1);
		System.out.println("feature2: " + o12.feature2);
		System.out.println("feature3: " + o12.feature3);
		System.out.println("hasAlarm: " + o12.hasAlarm);
		System.out.println("hasBacklight: " + o12.hasBacklight);
		System.out.println("rating: " + o12.rating);


		OrbitWatch o13 = new OrbitWatch();
		o13.productId = 113;
		o13.brandName = "Sample13";
		o13.strapMaterial = "Sample13";
		o13.color = "Sample13";
		o13.dialSize = 23.0;
		o13.price = 23.0;
		o13.isDigital = false;
		o13.isAvailable = false;
		o13.manufacturingDate = "Sample13";
		o13.expiryDate = "Sample13";
		o13.movementType = "Sample13";
		o13.glassType = "Sample13";
		o13.weight = 23.0;
		o13.isWaterResistant = false;
		o13.countryOfOrigin = "Sample13";
		o13.warrantyMonths = 113;
		o13.packagingType = "Sample13";
		o13.thickness = 23.0;
		o13.isShockResistant = false;
		o13.feature1 = "Sample13";
		o13.feature2 = "Sample13";
		o13.feature3 = "Sample13";
		o13.hasAlarm = false;
		o13.hasBacklight = false;
		o13.rating = 113;

		System.out.println("----- OrbitWatch 13 -----");
		System.out.println("productId: " + o13.productId);
		System.out.println("brandName: " + o13.brandName);
		System.out.println("strapMaterial: " + o13.strapMaterial);
		System.out.println("color: " + o13.color);
		System.out.println("dialSize: " + o13.dialSize);
		System.out.println("price: " + o13.price);
		System.out.println("isDigital: " + o13.isDigital);
		System.out.println("isAvailable: " + o13.isAvailable);
		System.out.println("manufacturingDate: " + o13.manufacturingDate);
		System.out.println("expiryDate: " + o13.expiryDate);
		System.out.println("movementType: " + o13.movementType);
		System.out.println("glassType: " + o13.glassType);
		System.out.println("weight: " + o13.weight);
		System.out.println("isWaterResistant: " + o13.isWaterResistant);
		System.out.println("countryOfOrigin: " + o13.countryOfOrigin);
		System.out.println("warrantyMonths: " + o13.warrantyMonths);
		System.out.println("packagingType: " + o13.packagingType);
		System.out.println("thickness: " + o13.thickness);
		System.out.println("isShockResistant: " + o13.isShockResistant);
		System.out.println("feature1: " + o13.feature1);
		System.out.println("feature2: " + o13.feature2);
		System.out.println("feature3: " + o13.feature3);
		System.out.println("hasAlarm: " + o13.hasAlarm);
		System.out.println("hasBacklight: " + o13.hasBacklight);
		System.out.println("rating: " + o13.rating);


		OrbitWatch o14 = new OrbitWatch();
		o14.productId = 114;
		o14.brandName = "Sample14";
		o14.strapMaterial = "Sample14";
		o14.color = "Sample14";
		o14.dialSize = 24.0;
		o14.price = 24.0;
		o14.isDigital = true;
		o14.isAvailable = true;
		o14.manufacturingDate = "Sample14";
		o14.expiryDate = "Sample14";
		o14.movementType = "Sample14";
		o14.glassType = "Sample14";
		o14.weight = 24.0;
		o14.isWaterResistant = true;
		o14.countryOfOrigin = "Sample14";
		o14.warrantyMonths = 114;
		o14.packagingType = "Sample14";
		o14.thickness = 24.0;
		o14.isShockResistant = true;
		o14.feature1 = "Sample14";
		o14.feature2 = "Sample14";
		o14.feature3 = "Sample14";
		o14.hasAlarm = true;
		o14.hasBacklight = true;
		o14.rating = 114;

		System.out.println("----- OrbitWatch 14 -----");
		System.out.println("productId: " + o14.productId);
		System.out.println("brandName: " + o14.brandName);
		System.out.println("strapMaterial: " + o14.strapMaterial);
		System.out.println("color: " + o14.color);
		System.out.println("dialSize: " + o14.dialSize);
		System.out.println("price: " + o14.price);
		System.out.println("isDigital: " + o14.isDigital);
		System.out.println("isAvailable: " + o14.isAvailable);
		System.out.println("manufacturingDate: " + o14.manufacturingDate);
		System.out.println("expiryDate: " + o14.expiryDate);
		System.out.println("movementType: " + o14.movementType);
		System.out.println("glassType: " + o14.glassType);
		System.out.println("weight: " + o14.weight);
		System.out.println("isWaterResistant: " + o14.isWaterResistant);
		System.out.println("countryOfOrigin: " + o14.countryOfOrigin);
		System.out.println("warrantyMonths: " + o14.warrantyMonths);
		System.out.println("packagingType: " + o14.packagingType);
		System.out.println("thickness: " + o14.thickness);
		System.out.println("isShockResistant: " + o14.isShockResistant);
		System.out.println("feature1: " + o14.feature1);
		System.out.println("feature2: " + o14.feature2);
		System.out.println("feature3: " + o14.feature3);
		System.out.println("hasAlarm: " + o14.hasAlarm);
		System.out.println("hasBacklight: " + o14.hasBacklight);
		System.out.println("rating: " + o14.rating);


		OrbitWatch o15 = new OrbitWatch();
		o15.productId = 115;
		o15.brandName = "Sample15";
		o15.strapMaterial = "Sample15";
		o15.color = "Sample15";
		o15.dialSize = 25.0;
		o15.price = 25.0;
		o15.isDigital = false;
		o15.isAvailable = false;
		o15.manufacturingDate = "Sample15";
		o15.expiryDate = "Sample15";
		o15.movementType = "Sample15";
		o15.glassType = "Sample15";
		o15.weight = 25.0;
		o15.isWaterResistant = false;
		o15.countryOfOrigin = "Sample15";
		o15.warrantyMonths = 115;
		o15.packagingType = "Sample15";
		o15.thickness = 25.0;
		o15.isShockResistant = false;
		o15.feature1 = "Sample15";
		o15.feature2 = "Sample15";
		o15.feature3 = "Sample15";
		o15.hasAlarm = false;
		o15.hasBacklight = false;
		o15.rating = 115;

		System.out.println("----- OrbitWatch 15 -----");
		System.out.println("productId: " + o15.productId);
		System.out.println("brandName: " + o15.brandName);
		System.out.println("strapMaterial: " + o15.strapMaterial);
		System.out.println("color: " + o15.color);
		System.out.println("dialSize: " + o15.dialSize);
		System.out.println("price: " + o15.price);
		System.out.println("isDigital: " + o15.isDigital);
		System.out.println("isAvailable: " + o15.isAvailable);
		System.out.println("manufacturingDate: " + o15.manufacturingDate);
		System.out.println("expiryDate: " + o15.expiryDate);
		System.out.println("movementType: " + o15.movementType);
		System.out.println("glassType: " + o15.glassType);
		System.out.println("weight: " + o15.weight);
		System.out.println("isWaterResistant: " + o15.isWaterResistant);
		System.out.println("countryOfOrigin: " + o15.countryOfOrigin);
		System.out.println("warrantyMonths: " + o15.warrantyMonths);
		System.out.println("packagingType: " + o15.packagingType);
		System.out.println("thickness: " + o15.thickness);
		System.out.println("isShockResistant: " + o15.isShockResistant);
		System.out.println("feature1: " + o15.feature1);
		System.out.println("feature2: " + o15.feature2);
		System.out.println("feature3: " + o15.feature3);
		System.out.println("hasAlarm: " + o15.hasAlarm);
		System.out.println("hasBacklight: " + o15.hasBacklight);
		System.out.println("rating: " + o15.rating);


		OrbitWatch o16 = new OrbitWatch();
		o16.productId = 116;
		o16.brandName = "Sample16";
		o16.strapMaterial = "Sample16";
		o16.color = "Sample16";
		o16.dialSize = 26.0;
		o16.price = 26.0;
		o16.isDigital = true;
		o16.isAvailable = true;
		o16.manufacturingDate = "Sample16";
		o16.expiryDate = "Sample16";
		o16.movementType = "Sample16";
		o16.glassType = "Sample16";
		o16.weight = 26.0;
		o16.isWaterResistant = true;
		o16.countryOfOrigin = "Sample16";
		o16.warrantyMonths = 116;
		o16.packagingType = "Sample16";
		o16.thickness = 26.0;
		o16.isShockResistant = true;
		o16.feature1 = "Sample16";
		o16.feature2 = "Sample16";
		o16.feature3 = "Sample16";
		o16.hasAlarm = true;
		o16.hasBacklight = true;
		o16.rating = 116;

		System.out.println("----- OrbitWatch 16 -----");
		System.out.println("productId: " + o16.productId);
		System.out.println("brandName: " + o16.brandName);
		System.out.println("strapMaterial: " + o16.strapMaterial);
		System.out.println("color: " + o16.color);
		System.out.println("dialSize: " + o16.dialSize);
		System.out.println("price: " + o16.price);
		System.out.println("isDigital: " + o16.isDigital);
		System.out.println("isAvailable: " + o16.isAvailable);
		System.out.println("manufacturingDate: " + o16.manufacturingDate);
		System.out.println("expiryDate: " + o16.expiryDate);
		System.out.println("movementType: " + o16.movementType);
		System.out.println("glassType: " + o16.glassType);
		System.out.println("weight: " + o16.weight);
		System.out.println("isWaterResistant: " + o16.isWaterResistant);
		System.out.println("countryOfOrigin: " + o16.countryOfOrigin);
		System.out.println("warrantyMonths: " + o16.warrantyMonths);
		System.out.println("packagingType: " + o16.packagingType);
		System.out.println("thickness: " + o16.thickness);
		System.out.println("isShockResistant: " + o16.isShockResistant);
		System.out.println("feature1: " + o16.feature1);
		System.out.println("feature2: " + o16.feature2);
		System.out.println("feature3: " + o16.feature3);
		System.out.println("hasAlarm: " + o16.hasAlarm);
		System.out.println("hasBacklight: " + o16.hasBacklight);
		System.out.println("rating: " + o16.rating);


		OrbitWatch o17 = new OrbitWatch();
		o17.productId = 117;
		o17.brandName = "Sample17";
		o17.strapMaterial = "Sample17";
		o17.color = "Sample17";
		o17.dialSize = 27.0;
		o17.price = 27.0;
		o17.isDigital = false;
		o17.isAvailable = false;
		o17.manufacturingDate = "Sample17";
		o17.expiryDate = "Sample17";
		o17.movementType = "Sample17";
		o17.glassType = "Sample17";
		o17.weight = 27.0;
		o17.isWaterResistant = false;
		o17.countryOfOrigin = "Sample17";
		o17.warrantyMonths = 117;
		o17.packagingType = "Sample17";
		o17.thickness = 27.0;
		o17.isShockResistant = false;
		o17.feature1 = "Sample17";
		o17.feature2 = "Sample17";
		o17.feature3 = "Sample17";
		o17.hasAlarm = false;
		o17.hasBacklight = false;
		o17.rating = 117;

		System.out.println("----- OrbitWatch 17 -----");
		System.out.println("productId: " + o17.productId);
		System.out.println("brandName: " + o17.brandName);
		System.out.println("strapMaterial: " + o17.strapMaterial);
		System.out.println("color: " + o17.color);
		System.out.println("dialSize: " + o17.dialSize);
		System.out.println("price: " + o17.price);
		System.out.println("isDigital: " + o17.isDigital);
		System.out.println("isAvailable: " + o17.isAvailable);
		System.out.println("manufacturingDate: " + o17.manufacturingDate);
		System.out.println("expiryDate: " + o17.expiryDate);
		System.out.println("movementType: " + o17.movementType);
		System.out.println("glassType: " + o17.glassType);
		System.out.println("weight: " + o17.weight);
		System.out.println("isWaterResistant: " + o17.isWaterResistant);
		System.out.println("countryOfOrigin: " + o17.countryOfOrigin);
		System.out.println("warrantyMonths: " + o17.warrantyMonths);
		System.out.println("packagingType: " + o17.packagingType);
		System.out.println("thickness: " + o17.thickness);
		System.out.println("isShockResistant: " + o17.isShockResistant);
		System.out.println("feature1: " + o17.feature1);
		System.out.println("feature2: " + o17.feature2);
		System.out.println("feature3: " + o17.feature3);
		System.out.println("hasAlarm: " + o17.hasAlarm);
		System.out.println("hasBacklight: " + o17.hasBacklight);
		System.out.println("rating: " + o17.rating);


		OrbitWatch o18 = new OrbitWatch();
		o18.productId = 118;
		o18.brandName = "Sample18";
		o18.strapMaterial = "Sample18";
		o18.color = "Sample18";
		o18.dialSize = 28.0;
		o18.price = 28.0;
		o18.isDigital = true;
		o18.isAvailable = true;
		o18.manufacturingDate = "Sample18";
		o18.expiryDate = "Sample18";
		o18.movementType = "Sample18";
		o18.glassType = "Sample18";
		o18.weight = 28.0;
		o18.isWaterResistant = true;
		o18.countryOfOrigin = "Sample18";
		o18.warrantyMonths = 118;
		o18.packagingType = "Sample18";
		o18.thickness = 28.0;
		o18.isShockResistant = true;
		o18.feature1 = "Sample18";
		o18.feature2 = "Sample18";
		o18.feature3 = "Sample18";
		o18.hasAlarm = true;
		o18.hasBacklight = true;
		o18.rating = 118;

		System.out.println("----- OrbitWatch 18 -----");
		System.out.println("productId: " + o18.productId);
		System.out.println("brandName: " + o18.brandName);
		System.out.println("strapMaterial: " + o18.strapMaterial);
		System.out.println("color: " + o18.color);
		System.out.println("dialSize: " + o18.dialSize);
		System.out.println("price: " + o18.price);
		System.out.println("isDigital: " + o18.isDigital);
		System.out.println("isAvailable: " + o18.isAvailable);
		System.out.println("manufacturingDate: " + o18.manufacturingDate);
		System.out.println("expiryDate: " + o18.expiryDate);
		System.out.println("movementType: " + o18.movementType);
		System.out.println("glassType: " + o18.glassType);
		System.out.println("weight: " + o18.weight);
		System.out.println("isWaterResistant: " + o18.isWaterResistant);
		System.out.println("countryOfOrigin: " + o18.countryOfOrigin);
		System.out.println("warrantyMonths: " + o18.warrantyMonths);
		System.out.println("packagingType: " + o18.packagingType);
		System.out.println("thickness: " + o18.thickness);
		System.out.println("isShockResistant: " + o18.isShockResistant);
		System.out.println("feature1: " + o18.feature1);
		System.out.println("feature2: " + o18.feature2);
		System.out.println("feature3: " + o18.feature3);
		System.out.println("hasAlarm: " + o18.hasAlarm);
		System.out.println("hasBacklight: " + o18.hasBacklight);
		System.out.println("rating: " + o18.rating);


		OrbitWatch o19 = new OrbitWatch();
		o19.productId = 119;
		o19.brandName = "Sample19";
		o19.strapMaterial = "Sample19";
		o19.color = "Sample19";
		o19.dialSize = 29.0;
		o19.price = 29.0;
		o19.isDigital = false;
		o19.isAvailable = false;
		o19.manufacturingDate = "Sample19";
		o19.expiryDate = "Sample19";
		o19.movementType = "Sample19";
		o19.glassType = "Sample19";
		o19.weight = 29.0;
		o19.isWaterResistant = false;
		o19.countryOfOrigin = "Sample19";
		o19.warrantyMonths = 119;
		o19.packagingType = "Sample19";
		o19.thickness = 29.0;
		o19.isShockResistant = false;
		o19.feature1 = "Sample19";
		o19.feature2 = "Sample19";
		o19.feature3 = "Sample19";
		o19.hasAlarm = false;
		o19.hasBacklight = false;
		o19.rating = 119;

		System.out.println("----- OrbitWatch 19 -----");
		System.out.println("productId: " + o19.productId);
		System.out.println("brandName: " + o19.brandName);
		System.out.println("strapMaterial: " + o19.strapMaterial);
		System.out.println("color: " + o19.color);
		System.out.println("dialSize: " + o19.dialSize);
		System.out.println("price: " + o19.price);
		System.out.println("isDigital: " + o19.isDigital);
		System.out.println("isAvailable: " + o19.isAvailable);
		System.out.println("manufacturingDate: " + o19.manufacturingDate);
		System.out.println("expiryDate: " + o19.expiryDate);
		System.out.println("movementType: " + o19.movementType);
		System.out.println("glassType: " + o19.glassType);
		System.out.println("weight: " + o19.weight);
		System.out.println("isWaterResistant: " + o19.isWaterResistant);
		System.out.println("countryOfOrigin: " + o19.countryOfOrigin);
		System.out.println("warrantyMonths: " + o19.warrantyMonths);
		System.out.println("packagingType: " + o19.packagingType);
		System.out.println("thickness: " + o19.thickness);
		System.out.println("isShockResistant: " + o19.isShockResistant);
		System.out.println("feature1: " + o19.feature1);
		System.out.println("feature2: " + o19.feature2);
		System.out.println("feature3: " + o19.feature3);
		System.out.println("hasAlarm: " + o19.hasAlarm);
		System.out.println("hasBacklight: " + o19.hasBacklight);
		System.out.println("rating: " + o19.rating);


		OrbitWatch o20 = new OrbitWatch();
		o20.productId = 120;
		o20.brandName = "Sample20";
		o20.strapMaterial = "Sample20";
		o20.color = "Sample20";
		o20.dialSize = 30.0;
		o20.price = 30.0;
		o20.isDigital = true;
		o20.isAvailable = true;
		o20.manufacturingDate = "Sample20";
		o20.expiryDate = "Sample20";
		o20.movementType = "Sample20";
		o20.glassType = "Sample20";
		o20.weight = 30.0;
		o20.isWaterResistant = true;
		o20.countryOfOrigin = "Sample20";
		o20.warrantyMonths = 120;
		o20.packagingType = "Sample20";
		o20.thickness = 30.0;
		o20.isShockResistant = true;
		o20.feature1 = "Sample20";
		o20.feature2 = "Sample20";
		o20.feature3 = "Sample20";
		o20.hasAlarm = true;
		o20.hasBacklight = true;
		o20.rating = 120;

		System.out.println("----- OrbitWatch 20 -----");
		System.out.println("productId: " + o20.productId);
		System.out.println("brandName: " + o20.brandName);
		System.out.println("strapMaterial: " + o20.strapMaterial);
		System.out.println("color: " + o20.color);
		System.out.println("dialSize: " + o20.dialSize);
		System.out.println("price: " + o20.price);
		System.out.println("isDigital: " + o20.isDigital);
		System.out.println("isAvailable: " + o20.isAvailable);
		System.out.println("manufacturingDate: " + o20.manufacturingDate);
		System.out.println("expiryDate: " + o20.expiryDate);
		System.out.println("movementType: " + o20.movementType);
		System.out.println("glassType: " + o20.glassType);
		System.out.println("weight: " + o20.weight);
		System.out.println("isWaterResistant: " + o20.isWaterResistant);
		System.out.println("countryOfOrigin: " + o20.countryOfOrigin);
		System.out.println("warrantyMonths: " + o20.warrantyMonths);
		System.out.println("packagingType: " + o20.packagingType);
		System.out.println("thickness: " + o20.thickness);
		System.out.println("isShockResistant: " + o20.isShockResistant);
		System.out.println("feature1: " + o20.feature1);
		System.out.println("feature2: " + o20.feature2);
		System.out.println("feature3: " + o20.feature3);
		System.out.println("hasAlarm: " + o20.hasAlarm);
		System.out.println("hasBacklight: " + o20.hasBacklight);
		System.out.println("rating: " + o20.rating);


		OrbitWatch o21 = new OrbitWatch();
		o21.productId = 121;
		o21.brandName = "Sample21";
		o21.strapMaterial = "Sample21";
		o21.color = "Sample21";
		o21.dialSize = 31.0;
		o21.price = 31.0;
		o21.isDigital = false;
		o21.isAvailable = false;
		o21.manufacturingDate = "Sample21";
		o21.expiryDate = "Sample21";
		o21.movementType = "Sample21";
		o21.glassType = "Sample21";
		o21.weight = 31.0;
		o21.isWaterResistant = false;
		o21.countryOfOrigin = "Sample21";
		o21.warrantyMonths = 121;
		o21.packagingType = "Sample21";
		o21.thickness = 31.0;
		o21.isShockResistant = false;
		o21.feature1 = "Sample21";
		o21.feature2 = "Sample21";
		o21.feature3 = "Sample21";
		o21.hasAlarm = false;
		o21.hasBacklight = false;
		o21.rating = 121;

		System.out.println("----- OrbitWatch 21 -----");
		System.out.println("productId: " + o21.productId);
		System.out.println("brandName: " + o21.brandName);
		System.out.println("strapMaterial: " + o21.strapMaterial);
		System.out.println("color: " + o21.color);
		System.out.println("dialSize: " + o21.dialSize);
		System.out.println("price: " + o21.price);
		System.out.println("isDigital: " + o21.isDigital);
		System.out.println("isAvailable: " + o21.isAvailable);
		System.out.println("manufacturingDate: " + o21.manufacturingDate);
		System.out.println("expiryDate: " + o21.expiryDate);
		System.out.println("movementType: " + o21.movementType);
		System.out.println("glassType: " + o21.glassType);
		System.out.println("weight: " + o21.weight);
		System.out.println("isWaterResistant: " + o21.isWaterResistant);
		System.out.println("countryOfOrigin: " + o21.countryOfOrigin);
		System.out.println("warrantyMonths: " + o21.warrantyMonths);
		System.out.println("packagingType: " + o21.packagingType);
		System.out.println("thickness: " + o21.thickness);
		System.out.println("isShockResistant: " + o21.isShockResistant);
		System.out.println("feature1: " + o21.feature1);
		System.out.println("feature2: " + o21.feature2);
		System.out.println("feature3: " + o21.feature3);
		System.out.println("hasAlarm: " + o21.hasAlarm);
		System.out.println("hasBacklight: " + o21.hasBacklight);
		System.out.println("rating: " + o21.rating);


		OrbitWatch o22 = new OrbitWatch();
		o22.productId = 122;
		o22.brandName = "Sample22";
		o22.strapMaterial = "Sample22";
		o22.color = "Sample22";
		o22.dialSize = 32.0;
		o22.price = 32.0;
		o22.isDigital = true;
		o22.isAvailable = true;
		o22.manufacturingDate = "Sample22";
		o22.expiryDate = "Sample22";
		o22.movementType = "Sample22";
		o22.glassType = "Sample22";
		o22.weight = 32.0;
		o22.isWaterResistant = true;
		o22.countryOfOrigin = "Sample22";
		o22.warrantyMonths = 122;
		o22.packagingType = "Sample22";
		o22.thickness = 32.0;
		o22.isShockResistant = true;
		o22.feature1 = "Sample22";
		o22.feature2 = "Sample22";
		o22.feature3 = "Sample22";
		o22.hasAlarm = true;
		o22.hasBacklight = true;
		o22.rating = 122;

		System.out.println("----- OrbitWatch 22 -----");
		System.out.println("productId: " + o22.productId);
		System.out.println("brandName: " + o22.brandName);
		System.out.println("strapMaterial: " + o22.strapMaterial);
		System.out.println("color: " + o22.color);
		System.out.println("dialSize: " + o22.dialSize);
		System.out.println("price: " + o22.price);
		System.out.println("isDigital: " + o22.isDigital);
		System.out.println("isAvailable: " + o22.isAvailable);
		System.out.println("manufacturingDate: " + o22.manufacturingDate);
		System.out.println("expiryDate: " + o22.expiryDate);
		System.out.println("movementType: " + o22.movementType);
		System.out.println("glassType: " + o22.glassType);
		System.out.println("weight: " + o22.weight);
		System.out.println("isWaterResistant: " + o22.isWaterResistant);
		System.out.println("countryOfOrigin: " + o22.countryOfOrigin);
		System.out.println("warrantyMonths: " + o22.warrantyMonths);
		System.out.println("packagingType: " + o22.packagingType);
		System.out.println("thickness: " + o22.thickness);
		System.out.println("isShockResistant: " + o22.isShockResistant);
		System.out.println("feature1: " + o22.feature1);
		System.out.println("feature2: " + o22.feature2);
		System.out.println("feature3: " + o22.feature3);
		System.out.println("hasAlarm: " + o22.hasAlarm);
		System.out.println("hasBacklight: " + o22.hasBacklight);
		System.out.println("rating: " + o22.rating);


		OrbitWatch o23 = new OrbitWatch();
		o23.productId = 123;
		o23.brandName = "Sample23";
		o23.strapMaterial = "Sample23";
		o23.color = "Sample23";
		o23.dialSize = 33.0;
		o23.price = 33.0;
		o23.isDigital = false;
		o23.isAvailable = false;
		o23.manufacturingDate = "Sample23";
		o23.expiryDate = "Sample23";
		o23.movementType = "Sample23";
		o23.glassType = "Sample23";
		o23.weight = 33.0;
		o23.isWaterResistant = false;
		o23.countryOfOrigin = "Sample23";
		o23.warrantyMonths = 123;
		o23.packagingType = "Sample23";
		o23.thickness = 33.0;
		o23.isShockResistant = false;
		o23.feature1 = "Sample23";
		o23.feature2 = "Sample23";
		o23.feature3 = "Sample23";
		o23.hasAlarm = false;
		o23.hasBacklight = false;
		o23.rating = 123;

		System.out.println("----- OrbitWatch 23 -----");
		System.out.println("productId: " + o23.productId);
		System.out.println("brandName: " + o23.brandName);
		System.out.println("strapMaterial: " + o23.strapMaterial);
		System.out.println("color: " + o23.color);
		System.out.println("dialSize: " + o23.dialSize);
		System.out.println("price: " + o23.price);
		System.out.println("isDigital: " + o23.isDigital);
		System.out.println("isAvailable: " + o23.isAvailable);
		System.out.println("manufacturingDate: " + o23.manufacturingDate);
		System.out.println("expiryDate: " + o23.expiryDate);
		System.out.println("movementType: " + o23.movementType);
		System.out.println("glassType: " + o23.glassType);
		System.out.println("weight: " + o23.weight);
		System.out.println("isWaterResistant: " + o23.isWaterResistant);
		System.out.println("countryOfOrigin: " + o23.countryOfOrigin);
		System.out.println("warrantyMonths: " + o23.warrantyMonths);
		System.out.println("packagingType: " + o23.packagingType);
		System.out.println("thickness: " + o23.thickness);
		System.out.println("isShockResistant: " + o23.isShockResistant);
		System.out.println("feature1: " + o23.feature1);
		System.out.println("feature2: " + o23.feature2);
		System.out.println("feature3: " + o23.feature3);
		System.out.println("hasAlarm: " + o23.hasAlarm);
		System.out.println("hasBacklight: " + o23.hasBacklight);
		System.out.println("rating: " + o23.rating);


		OrbitWatch o24 = new OrbitWatch();
		o24.productId = 124;
		o24.brandName = "Sample24";
		o24.strapMaterial = "Sample24";
		o24.color = "Sample24";
		o24.dialSize = 34.0;
		o24.price = 34.0;
		o24.isDigital = true;
		o24.isAvailable = true;
		o24.manufacturingDate = "Sample24";
		o24.expiryDate = "Sample24";
		o24.movementType = "Sample24";
		o24.glassType = "Sample24";
		o24.weight = 34.0;
		o24.isWaterResistant = true;
		o24.countryOfOrigin = "Sample24";
		o24.warrantyMonths = 124;
		o24.packagingType = "Sample24";
		o24.thickness = 34.0;
		o24.isShockResistant = true;
		o24.feature1 = "Sample24";
		o24.feature2 = "Sample24";
		o24.feature3 = "Sample24";
		o24.hasAlarm = true;
		o24.hasBacklight = true;
		o24.rating = 124;

		System.out.println("----- OrbitWatch 24 -----");
		System.out.println("productId: " + o24.productId);
		System.out.println("brandName: " + o24.brandName);
		System.out.println("strapMaterial: " + o24.strapMaterial);
		System.out.println("color: " + o24.color);
		System.out.println("dialSize: " + o24.dialSize);
		System.out.println("price: " + o24.price);
		System.out.println("isDigital: " + o24.isDigital);
		System.out.println("isAvailable: " + o24.isAvailable);
		System.out.println("manufacturingDate: " + o24.manufacturingDate);
		System.out.println("expiryDate: " + o24.expiryDate);
		System.out.println("movementType: " + o24.movementType);
		System.out.println("glassType: " + o24.glassType);
		System.out.println("weight: " + o24.weight);
		System.out.println("isWaterResistant: " + o24.isWaterResistant);
		System.out.println("countryOfOrigin: " + o24.countryOfOrigin);
		System.out.println("warrantyMonths: " + o24.warrantyMonths);
		System.out.println("packagingType: " + o24.packagingType);
		System.out.println("thickness: " + o24.thickness);
		System.out.println("isShockResistant: " + o24.isShockResistant);
		System.out.println("feature1: " + o24.feature1);
		System.out.println("feature2: " + o24.feature2);
		System.out.println("feature3: " + o24.feature3);
		System.out.println("hasAlarm: " + o24.hasAlarm);
		System.out.println("hasBacklight: " + o24.hasBacklight);
		System.out.println("rating: " + o24.rating);


		OrbitWatch o25 = new OrbitWatch();
		o25.productId = 125;
		o25.brandName = "Sample25";
		o25.strapMaterial = "Sample25";
		o25.color = "Sample25";
		o25.dialSize = 35.0;
		o25.price = 35.0;
		o25.isDigital = false;
		o25.isAvailable = false;
		o25.manufacturingDate = "Sample25";
		o25.expiryDate = "Sample25";
		o25.movementType = "Sample25";
		o25.glassType = "Sample25";
		o25.weight = 35.0;
		o25.isWaterResistant = false;
		o25.countryOfOrigin = "Sample25";
		o25.warrantyMonths = 125;
		o25.packagingType = "Sample25";
		o25.thickness = 35.0;
		o25.isShockResistant = false;
		o25.feature1 = "Sample25";
		o25.feature2 = "Sample25";
		o25.feature3 = "Sample25";
		o25.hasAlarm = false;
		o25.hasBacklight = false;
		o25.rating = 125;

		System.out.println("----- OrbitWatch 25 -----");
		System.out.println("productId: " + o25.productId);
		System.out.println("brandName: " + o25.brandName);
		System.out.println("strapMaterial: " + o25.strapMaterial);
		System.out.println("color: " + o25.color);
		System.out.println("dialSize: " + o25.dialSize);
		System.out.println("price: " + o25.price);
		System.out.println("isDigital: " + o25.isDigital);
		System.out.println("isAvailable: " + o25.isAvailable);
		System.out.println("manufacturingDate: " + o25.manufacturingDate);
		System.out.println("expiryDate: " + o25.expiryDate);
		System.out.println("movementType: " + o25.movementType);
		System.out.println("glassType: " + o25.glassType);
		System.out.println("weight: " + o25.weight);
		System.out.println("isWaterResistant: " + o25.isWaterResistant);
		System.out.println("countryOfOrigin: " + o25.countryOfOrigin);
		System.out.println("warrantyMonths: " + o25.warrantyMonths);
		System.out.println("packagingType: " + o25.packagingType);
		System.out.println("thickness: " + o25.thickness);
		System.out.println("isShockResistant: " + o25.isShockResistant);
		System.out.println("feature1: " + o25.feature1);
		System.out.println("feature2: " + o25.feature2);
		System.out.println("feature3: " + o25.feature3);
		System.out.println("hasAlarm: " + o25.hasAlarm);
		System.out.println("hasBacklight: " + o25.hasBacklight);
		System.out.println("rating: " + o25.rating);


	}
}

	