class PharmaceuticalCompanyExecutor {
    public static void main(String[] args) {
        boolean isValidate;

        isValidate = PharmaceuticalCompany.createCompany("Pfizer", "PZ12345", "New York", 1849, 500, 100.3, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Johnson & Johnson", "JJ20202", "New Brunswick", 1886, 1200, 94.9, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Roche", "RC55443", "Basel", 1896, 800, 68.7, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Merck", "MRK001", "New Jersey", 1891, 600, 59.3, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("AbbVie", "ABV998", "North Chicago", 2013, 150, 58.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Bayer", "BAY776", "Leverkusen", 1863, 1000, 50.7, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Sanofi", "SNF112", "Paris", 1973, 750, 45.2, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("AstraZeneca", "AZN445", "Cambridge", 1999, 400, 44.4, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Novartis", "NVR887", "Basel", 1996, 900, 50.5, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("GlaxoSmithKline", "GSK332", "London", 2000, 650, 36.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Eli Lilly", "LLY554", "Indianapolis", 1876, 300, 28.5, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany(null, "ERR001", "Unknown", 2020, 10, 1.0, false, false);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("", "ERR002", "Mumbai", 1990, 5, 0.5, true, false);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Bio-Tech", null, "Delhi", 2015, 20, 2.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Medi-Care", "", "Pune", 2010, 15, 1.5, false, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Sun Pharma", "SP101", null, 1983, 2000, 5.4, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Cipla", "CP202", "", 1935, 1500, 2.5, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Dr Reddys", "DR303", "Hyderabad", 1500, 1000, 3.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Lupin", "LP404", "Mumbai", 1968, -10, 2.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Zydus", "ZY505", "Ahmedabad", 1952, 800, 0.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Biocon", "BC606", "Bengaluru", 1978, 100, -5.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany(null, null, null, 0, 0, 0.0, false, false);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Novo Nordisk", "NN001", "Bagsvaerd", 1923, 200, 25.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Amgen", "AMG221", "Thousand Oaks", 1980, 120, 26.3, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Gilead", "GILD33", "Foster City", 1987, 80, 27.2, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Bristol Myers", "BMS44", "New York", 1887, 350, 46.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Takeda", "TKD99", "Tokyo", 1781, 450, 30.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Boehringer", "BI110", "Ingelheim", 1885, 250, 24.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Viatris", "VTR12", "Canonsburg", 2020, 3000, 16.2, true, false);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Teva", "TVA88", "Tel Aviv", 1901, 3500, 14.9, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Regeneron", "REGN1", "Tarrytown", 1988, 35, 12.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Biogen", "BGEN2", "Cambridge", 1978, 40, 10.1, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Alexion", "ALXN3", "Boston", 1992, 20, 6.0, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Vertex", "VRTX4", "Boston", 1989, 15, 8.9, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Incyte", "INCY5", "Wilmington", 1991, 10, 3.4, true, true);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Bausch Health", "BHC09", "Laval", 1959, 1000, 8.1, true, false);
        PharmaceuticalCompany.getCompanyDetails();
        isValidate = PharmaceuticalCompany.createCompany("Jazz Pharma", "JAZZ1", "Dublin", 2003, 25, 3.7, true, true);
        PharmaceuticalCompany.getCompanyDetails();
    }
}