class PixelTabletRunner {
	public static void main(String[] args) {

		PixelTablet p1 = new PixelTablet();
		p1.productId = 101;
		p1.brandName = "Sample1";
		p1.processor = "Sample1";
		p1.color = "Sample1";
		p1.storage = 11.0;
		p1.price = 11.0;
		p1.isWifiEnabled = false;
		p1.isAvailable = false;
		p1.manufacturingDate = "Sample1";
		p1.expiryDate = "Sample1";
		p1.screenType = "Sample1";
		p1.operatingSystem = "Sample1";
		p1.screenSize = 11.0;
		p1.hasFrontCamera = false;
		p1.countryOfOrigin = "Sample1";
		p1.warrantyMonths = 101;
		p1.packagingType = "Sample1";
		p1.weight = 11.0;
		p1.hasBluetooth = false;
		p1.feature1 = "Sample1";
		p1.feature2 = "Sample1";
		p1.feature3 = "Sample1";
		p1.hasStylusSupport = false;
		p1.isTouchScreen = false;
		p1.rating = 101;

		System.out.println("----- PixelTablet 1 -----");
		System.out.println("productId: " + p1.productId);
		System.out.println("brandName: " + p1.brandName);
		System.out.println("processor: " + p1.processor);
		System.out.println("color: " + p1.color);
		System.out.println("storage: " + p1.storage);
		System.out.println("price: " + p1.price);
		System.out.println("isWifiEnabled: " + p1.isWifiEnabled);
		System.out.println("isAvailable: " + p1.isAvailable);
		System.out.println("manufacturingDate: " + p1.manufacturingDate);
		System.out.println("expiryDate: " + p1.expiryDate);
		System.out.println("screenType: " + p1.screenType);
		System.out.println("operatingSystem: " + p1.operatingSystem);
		System.out.println("screenSize: " + p1.screenSize);
		System.out.println("hasFrontCamera: " + p1.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p1.countryOfOrigin);
		System.out.println("warrantyMonths: " + p1.warrantyMonths);
		System.out.println("packagingType: " + p1.packagingType);
		System.out.println("weight: " + p1.weight);
		System.out.println("hasBluetooth: " + p1.hasBluetooth);
		System.out.println("feature1: " + p1.feature1);
		System.out.println("feature2: " + p1.feature2);
		System.out.println("feature3: " + p1.feature3);
		System.out.println("hasStylusSupport: " + p1.hasStylusSupport);
		System.out.println("isTouchScreen: " + p1.isTouchScreen);
		System.out.println("rating: " + p1.rating);


		PixelTablet p2 = new PixelTablet();
		p2.productId = 102;
		p2.brandName = "Sample2";
		p2.processor = "Sample2";
		p2.color = "Sample2";
		p2.storage = 12.0;
		p2.price = 12.0;
		p2.isWifiEnabled = true;
		p2.isAvailable = true;
		p2.manufacturingDate = "Sample2";
		p2.expiryDate = "Sample2";
		p2.screenType = "Sample2";
		p2.operatingSystem = "Sample2";
		p2.screenSize = 12.0;
		p2.hasFrontCamera = true;
		p2.countryOfOrigin = "Sample2";
		p2.warrantyMonths = 102;
		p2.packagingType = "Sample2";
		p2.weight = 12.0;
		p2.hasBluetooth = true;
		p2.feature1 = "Sample2";
		p2.feature2 = "Sample2";
		p2.feature3 = "Sample2";
		p2.hasStylusSupport = true;
		p2.isTouchScreen = true;
		p2.rating = 102;

		System.out.println("----- PixelTablet 2 -----");
		System.out.println("productId: " + p2.productId);
		System.out.println("brandName: " + p2.brandName);
		System.out.println("processor: " + p2.processor);
		System.out.println("color: " + p2.color);
		System.out.println("storage: " + p2.storage);
		System.out.println("price: " + p2.price);
		System.out.println("isWifiEnabled: " + p2.isWifiEnabled);
		System.out.println("isAvailable: " + p2.isAvailable);
		System.out.println("manufacturingDate: " + p2.manufacturingDate);
		System.out.println("expiryDate: " + p2.expiryDate);
		System.out.println("screenType: " + p2.screenType);
		System.out.println("operatingSystem: " + p2.operatingSystem);
		System.out.println("screenSize: " + p2.screenSize);
		System.out.println("hasFrontCamera: " + p2.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p2.countryOfOrigin);
		System.out.println("warrantyMonths: " + p2.warrantyMonths);
		System.out.println("packagingType: " + p2.packagingType);
		System.out.println("weight: " + p2.weight);
		System.out.println("hasBluetooth: " + p2.hasBluetooth);
		System.out.println("feature1: " + p2.feature1);
		System.out.println("feature2: " + p2.feature2);
		System.out.println("feature3: " + p2.feature3);
		System.out.println("hasStylusSupport: " + p2.hasStylusSupport);
		System.out.println("isTouchScreen: " + p2.isTouchScreen);
		System.out.println("rating: " + p2.rating);


		PixelTablet p3 = new PixelTablet();
		p3.productId = 103;
		p3.brandName = "Sample3";
		p3.processor = "Sample3";
		p3.color = "Sample3";
		p3.storage = 13.0;
		p3.price = 13.0;
		p3.isWifiEnabled = false;
		p3.isAvailable = false;
		p3.manufacturingDate = "Sample3";
		p3.expiryDate = "Sample3";
		p3.screenType = "Sample3";
		p3.operatingSystem = "Sample3";
		p3.screenSize = 13.0;
		p3.hasFrontCamera = false;
		p3.countryOfOrigin = "Sample3";
		p3.warrantyMonths = 103;
		p3.packagingType = "Sample3";
		p3.weight = 13.0;
		p3.hasBluetooth = false;
		p3.feature1 = "Sample3";
		p3.feature2 = "Sample3";
		p3.feature3 = "Sample3";
		p3.hasStylusSupport = false;
		p3.isTouchScreen = false;
		p3.rating = 103;

		System.out.println("----- PixelTablet 3 -----");
		System.out.println("productId: " + p3.productId);
		System.out.println("brandName: " + p3.brandName);
		System.out.println("processor: " + p3.processor);
		System.out.println("color: " + p3.color);
		System.out.println("storage: " + p3.storage);
		System.out.println("price: " + p3.price);
		System.out.println("isWifiEnabled: " + p3.isWifiEnabled);
		System.out.println("isAvailable: " + p3.isAvailable);
		System.out.println("manufacturingDate: " + p3.manufacturingDate);
		System.out.println("expiryDate: " + p3.expiryDate);
		System.out.println("screenType: " + p3.screenType);
		System.out.println("operatingSystem: " + p3.operatingSystem);
		System.out.println("screenSize: " + p3.screenSize);
		System.out.println("hasFrontCamera: " + p3.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p3.countryOfOrigin);
		System.out.println("warrantyMonths: " + p3.warrantyMonths);
		System.out.println("packagingType: " + p3.packagingType);
		System.out.println("weight: " + p3.weight);
		System.out.println("hasBluetooth: " + p3.hasBluetooth);
		System.out.println("feature1: " + p3.feature1);
		System.out.println("feature2: " + p3.feature2);
		System.out.println("feature3: " + p3.feature3);
		System.out.println("hasStylusSupport: " + p3.hasStylusSupport);
		System.out.println("isTouchScreen: " + p3.isTouchScreen);
		System.out.println("rating: " + p3.rating);


		PixelTablet p4 = new PixelTablet();
		p4.productId = 104;
		p4.brandName = "Sample4";
		p4.processor = "Sample4";
		p4.color = "Sample4";
		p4.storage = 14.0;
		p4.price = 14.0;
		p4.isWifiEnabled = true;
		p4.isAvailable = true;
		p4.manufacturingDate = "Sample4";
		p4.expiryDate = "Sample4";
		p4.screenType = "Sample4";
		p4.operatingSystem = "Sample4";
		p4.screenSize = 14.0;
		p4.hasFrontCamera = true;
		p4.countryOfOrigin = "Sample4";
		p4.warrantyMonths = 104;
		p4.packagingType = "Sample4";
		p4.weight = 14.0;
		p4.hasBluetooth = true;
		p4.feature1 = "Sample4";
		p4.feature2 = "Sample4";
		p4.feature3 = "Sample4";
		p4.hasStylusSupport = true;
		p4.isTouchScreen = true;
		p4.rating = 104;

		System.out.println("----- PixelTablet 4 -----");
		System.out.println("productId: " + p4.productId);
		System.out.println("brandName: " + p4.brandName);
		System.out.println("processor: " + p4.processor);
		System.out.println("color: " + p4.color);
		System.out.println("storage: " + p4.storage);
		System.out.println("price: " + p4.price);
		System.out.println("isWifiEnabled: " + p4.isWifiEnabled);
		System.out.println("isAvailable: " + p4.isAvailable);
		System.out.println("manufacturingDate: " + p4.manufacturingDate);
		System.out.println("expiryDate: " + p4.expiryDate);
		System.out.println("screenType: " + p4.screenType);
		System.out.println("operatingSystem: " + p4.operatingSystem);
		System.out.println("screenSize: " + p4.screenSize);
		System.out.println("hasFrontCamera: " + p4.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p4.countryOfOrigin);
		System.out.println("warrantyMonths: " + p4.warrantyMonths);
		System.out.println("packagingType: " + p4.packagingType);
		System.out.println("weight: " + p4.weight);
		System.out.println("hasBluetooth: " + p4.hasBluetooth);
		System.out.println("feature1: " + p4.feature1);
		System.out.println("feature2: " + p4.feature2);
		System.out.println("feature3: " + p4.feature3);
		System.out.println("hasStylusSupport: " + p4.hasStylusSupport);
		System.out.println("isTouchScreen: " + p4.isTouchScreen);
		System.out.println("rating: " + p4.rating);


		PixelTablet p5 = new PixelTablet();
		p5.productId = 105;
		p5.brandName = "Sample5";
		p5.processor = "Sample5";
		p5.color = "Sample5";
		p5.storage = 15.0;
		p5.price = 15.0;
		p5.isWifiEnabled = false;
		p5.isAvailable = false;
		p5.manufacturingDate = "Sample5";
		p5.expiryDate = "Sample5";
		p5.screenType = "Sample5";
		p5.operatingSystem = "Sample5";
		p5.screenSize = 15.0;
		p5.hasFrontCamera = false;
		p5.countryOfOrigin = "Sample5";
		p5.warrantyMonths = 105;
		p5.packagingType = "Sample5";
		p5.weight = 15.0;
		p5.hasBluetooth = false;
		p5.feature1 = "Sample5";
		p5.feature2 = "Sample5";
		p5.feature3 = "Sample5";
		p5.hasStylusSupport = false;
		p5.isTouchScreen = false;
		p5.rating = 105;

		System.out.println("----- PixelTablet 5 -----");
		System.out.println("productId: " + p5.productId);
		System.out.println("brandName: " + p5.brandName);
		System.out.println("processor: " + p5.processor);
		System.out.println("color: " + p5.color);
		System.out.println("storage: " + p5.storage);
		System.out.println("price: " + p5.price);
		System.out.println("isWifiEnabled: " + p5.isWifiEnabled);
		System.out.println("isAvailable: " + p5.isAvailable);
		System.out.println("manufacturingDate: " + p5.manufacturingDate);
		System.out.println("expiryDate: " + p5.expiryDate);
		System.out.println("screenType: " + p5.screenType);
		System.out.println("operatingSystem: " + p5.operatingSystem);
		System.out.println("screenSize: " + p5.screenSize);
		System.out.println("hasFrontCamera: " + p5.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p5.countryOfOrigin);
		System.out.println("warrantyMonths: " + p5.warrantyMonths);
		System.out.println("packagingType: " + p5.packagingType);
		System.out.println("weight: " + p5.weight);
		System.out.println("hasBluetooth: " + p5.hasBluetooth);
		System.out.println("feature1: " + p5.feature1);
		System.out.println("feature2: " + p5.feature2);
		System.out.println("feature3: " + p5.feature3);
		System.out.println("hasStylusSupport: " + p5.hasStylusSupport);
		System.out.println("isTouchScreen: " + p5.isTouchScreen);
		System.out.println("rating: " + p5.rating);


		PixelTablet p6 = new PixelTablet();
		p6.productId = 106;
		p6.brandName = "Sample6";
		p6.processor = "Sample6";
		p6.color = "Sample6";
		p6.storage = 16.0;
		p6.price = 16.0;
		p6.isWifiEnabled = true;
		p6.isAvailable = true;
		p6.manufacturingDate = "Sample6";
		p6.expiryDate = "Sample6";
		p6.screenType = "Sample6";
		p6.operatingSystem = "Sample6";
		p6.screenSize = 16.0;
		p6.hasFrontCamera = true;
		p6.countryOfOrigin = "Sample6";
		p6.warrantyMonths = 106;
		p6.packagingType = "Sample6";
		p6.weight = 16.0;
		p6.hasBluetooth = true;
		p6.feature1 = "Sample6";
		p6.feature2 = "Sample6";
		p6.feature3 = "Sample6";
		p6.hasStylusSupport = true;
		p6.isTouchScreen = true;
		p6.rating = 106;

		System.out.println("----- PixelTablet 6 -----");
		System.out.println("productId: " + p6.productId);
		System.out.println("brandName: " + p6.brandName);
		System.out.println("processor: " + p6.processor);
		System.out.println("color: " + p6.color);
		System.out.println("storage: " + p6.storage);
		System.out.println("price: " + p6.price);
		System.out.println("isWifiEnabled: " + p6.isWifiEnabled);
		System.out.println("isAvailable: " + p6.isAvailable);
		System.out.println("manufacturingDate: " + p6.manufacturingDate);
		System.out.println("expiryDate: " + p6.expiryDate);
		System.out.println("screenType: " + p6.screenType);
		System.out.println("operatingSystem: " + p6.operatingSystem);
		System.out.println("screenSize: " + p6.screenSize);
		System.out.println("hasFrontCamera: " + p6.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p6.countryOfOrigin);
		System.out.println("warrantyMonths: " + p6.warrantyMonths);
		System.out.println("packagingType: " + p6.packagingType);
		System.out.println("weight: " + p6.weight);
		System.out.println("hasBluetooth: " + p6.hasBluetooth);
		System.out.println("feature1: " + p6.feature1);
		System.out.println("feature2: " + p6.feature2);
		System.out.println("feature3: " + p6.feature3);
		System.out.println("hasStylusSupport: " + p6.hasStylusSupport);
		System.out.println("isTouchScreen: " + p6.isTouchScreen);
		System.out.println("rating: " + p6.rating);


		PixelTablet p7 = new PixelTablet();
		p7.productId = 107;
		p7.brandName = "Sample7";
		p7.processor = "Sample7";
		p7.color = "Sample7";
		p7.storage = 17.0;
		p7.price = 17.0;
		p7.isWifiEnabled = false;
		p7.isAvailable = false;
		p7.manufacturingDate = "Sample7";
		p7.expiryDate = "Sample7";
		p7.screenType = "Sample7";
		p7.operatingSystem = "Sample7";
		p7.screenSize = 17.0;
		p7.hasFrontCamera = false;
		p7.countryOfOrigin = "Sample7";
		p7.warrantyMonths = 107;
		p7.packagingType = "Sample7";
		p7.weight = 17.0;
		p7.hasBluetooth = false;
		p7.feature1 = "Sample7";
		p7.feature2 = "Sample7";
		p7.feature3 = "Sample7";
		p7.hasStylusSupport = false;
		p7.isTouchScreen = false;
		p7.rating = 107;

		System.out.println("----- PixelTablet 7 -----");
		System.out.println("productId: " + p7.productId);
		System.out.println("brandName: " + p7.brandName);
		System.out.println("processor: " + p7.processor);
		System.out.println("color: " + p7.color);
		System.out.println("storage: " + p7.storage);
		System.out.println("price: " + p7.price);
		System.out.println("isWifiEnabled: " + p7.isWifiEnabled);
		System.out.println("isAvailable: " + p7.isAvailable);
		System.out.println("manufacturingDate: " + p7.manufacturingDate);
		System.out.println("expiryDate: " + p7.expiryDate);
		System.out.println("screenType: " + p7.screenType);
		System.out.println("operatingSystem: " + p7.operatingSystem);
		System.out.println("screenSize: " + p7.screenSize);
		System.out.println("hasFrontCamera: " + p7.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p7.countryOfOrigin);
		System.out.println("warrantyMonths: " + p7.warrantyMonths);
		System.out.println("packagingType: " + p7.packagingType);
		System.out.println("weight: " + p7.weight);
		System.out.println("hasBluetooth: " + p7.hasBluetooth);
		System.out.println("feature1: " + p7.feature1);
		System.out.println("feature2: " + p7.feature2);
		System.out.println("feature3: " + p7.feature3);
		System.out.println("hasStylusSupport: " + p7.hasStylusSupport);
		System.out.println("isTouchScreen: " + p7.isTouchScreen);
		System.out.println("rating: " + p7.rating);


		PixelTablet p8 = new PixelTablet();
		p8.productId = 108;
		p8.brandName = "Sample8";
		p8.processor = "Sample8";
		p8.color = "Sample8";
		p8.storage = 18.0;
		p8.price = 18.0;
		p8.isWifiEnabled = true;
		p8.isAvailable = true;
		p8.manufacturingDate = "Sample8";
		p8.expiryDate = "Sample8";
		p8.screenType = "Sample8";
		p8.operatingSystem = "Sample8";
		p8.screenSize = 18.0;
		p8.hasFrontCamera = true;
		p8.countryOfOrigin = "Sample8";
		p8.warrantyMonths = 108;
		p8.packagingType = "Sample8";
		p8.weight = 18.0;
		p8.hasBluetooth = true;
		p8.feature1 = "Sample8";
		p8.feature2 = "Sample8";
		p8.feature3 = "Sample8";
		p8.hasStylusSupport = true;
		p8.isTouchScreen = true;
		p8.rating = 108;

		System.out.println("----- PixelTablet 8 -----");
		System.out.println("productId: " + p8.productId);
		System.out.println("brandName: " + p8.brandName);
		System.out.println("processor: " + p8.processor);
		System.out.println("color: " + p8.color);
		System.out.println("storage: " + p8.storage);
		System.out.println("price: " + p8.price);
		System.out.println("isWifiEnabled: " + p8.isWifiEnabled);
		System.out.println("isAvailable: " + p8.isAvailable);
		System.out.println("manufacturingDate: " + p8.manufacturingDate);
		System.out.println("expiryDate: " + p8.expiryDate);
		System.out.println("screenType: " + p8.screenType);
		System.out.println("operatingSystem: " + p8.operatingSystem);
		System.out.println("screenSize: " + p8.screenSize);
		System.out.println("hasFrontCamera: " + p8.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p8.countryOfOrigin);
		System.out.println("warrantyMonths: " + p8.warrantyMonths);
		System.out.println("packagingType: " + p8.packagingType);
		System.out.println("weight: " + p8.weight);
		System.out.println("hasBluetooth: " + p8.hasBluetooth);
		System.out.println("feature1: " + p8.feature1);
		System.out.println("feature2: " + p8.feature2);
		System.out.println("feature3: " + p8.feature3);
		System.out.println("hasStylusSupport: " + p8.hasStylusSupport);
		System.out.println("isTouchScreen: " + p8.isTouchScreen);
		System.out.println("rating: " + p8.rating);


		PixelTablet p9 = new PixelTablet();
		p9.productId = 109;
		p9.brandName = "Sample9";
		p9.processor = "Sample9";
		p9.color = "Sample9";
		p9.storage = 19.0;
		p9.price = 19.0;
		p9.isWifiEnabled = false;
		p9.isAvailable = false;
		p9.manufacturingDate = "Sample9";
		p9.expiryDate = "Sample9";
		p9.screenType = "Sample9";
		p9.operatingSystem = "Sample9";
		p9.screenSize = 19.0;
		p9.hasFrontCamera = false;
		p9.countryOfOrigin = "Sample9";
		p9.warrantyMonths = 109;
		p9.packagingType = "Sample9";
		p9.weight = 19.0;
		p9.hasBluetooth = false;
		p9.feature1 = "Sample9";
		p9.feature2 = "Sample9";
		p9.feature3 = "Sample9";
		p9.hasStylusSupport = false;
		p9.isTouchScreen = false;
		p9.rating = 109;

		System.out.println("----- PixelTablet 9 -----");
		System.out.println("productId: " + p9.productId);
		System.out.println("brandName: " + p9.brandName);
		System.out.println("processor: " + p9.processor);
		System.out.println("color: " + p9.color);
		System.out.println("storage: " + p9.storage);
		System.out.println("price: " + p9.price);
		System.out.println("isWifiEnabled: " + p9.isWifiEnabled);
		System.out.println("isAvailable: " + p9.isAvailable);
		System.out.println("manufacturingDate: " + p9.manufacturingDate);
		System.out.println("expiryDate: " + p9.expiryDate);
		System.out.println("screenType: " + p9.screenType);
		System.out.println("operatingSystem: " + p9.operatingSystem);
		System.out.println("screenSize: " + p9.screenSize);
		System.out.println("hasFrontCamera: " + p9.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p9.countryOfOrigin);
		System.out.println("warrantyMonths: " + p9.warrantyMonths);
		System.out.println("packagingType: " + p9.packagingType);
		System.out.println("weight: " + p9.weight);
		System.out.println("hasBluetooth: " + p9.hasBluetooth);
		System.out.println("feature1: " + p9.feature1);
		System.out.println("feature2: " + p9.feature2);
		System.out.println("feature3: " + p9.feature3);
		System.out.println("hasStylusSupport: " + p9.hasStylusSupport);
		System.out.println("isTouchScreen: " + p9.isTouchScreen);
		System.out.println("rating: " + p9.rating);


		PixelTablet p10 = new PixelTablet();
		p10.productId = 110;
		p10.brandName = "Sample10";
		p10.processor = "Sample10";
		p10.color = "Sample10";
		p10.storage = 20.0;
		p10.price = 20.0;
		p10.isWifiEnabled = true;
		p10.isAvailable = true;
		p10.manufacturingDate = "Sample10";
		p10.expiryDate = "Sample10";
		p10.screenType = "Sample10";
		p10.operatingSystem = "Sample10";
		p10.screenSize = 20.0;
		p10.hasFrontCamera = true;
		p10.countryOfOrigin = "Sample10";
		p10.warrantyMonths = 110;
		p10.packagingType = "Sample10";
		p10.weight = 20.0;
		p10.hasBluetooth = true;
		p10.feature1 = "Sample10";
		p10.feature2 = "Sample10";
		p10.feature3 = "Sample10";
		p10.hasStylusSupport = true;
		p10.isTouchScreen = true;
		p10.rating = 110;

		System.out.println("----- PixelTablet 10 -----");
		System.out.println("productId: " + p10.productId);
		System.out.println("brandName: " + p10.brandName);
		System.out.println("processor: " + p10.processor);
		System.out.println("color: " + p10.color);
		System.out.println("storage: " + p10.storage);
		System.out.println("price: " + p10.price);
		System.out.println("isWifiEnabled: " + p10.isWifiEnabled);
		System.out.println("isAvailable: " + p10.isAvailable);
		System.out.println("manufacturingDate: " + p10.manufacturingDate);
		System.out.println("expiryDate: " + p10.expiryDate);
		System.out.println("screenType: " + p10.screenType);
		System.out.println("operatingSystem: " + p10.operatingSystem);
		System.out.println("screenSize: " + p10.screenSize);
		System.out.println("hasFrontCamera: " + p10.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p10.countryOfOrigin);
		System.out.println("warrantyMonths: " + p10.warrantyMonths);
		System.out.println("packagingType: " + p10.packagingType);
		System.out.println("weight: " + p10.weight);
		System.out.println("hasBluetooth: " + p10.hasBluetooth);
		System.out.println("feature1: " + p10.feature1);
		System.out.println("feature2: " + p10.feature2);
		System.out.println("feature3: " + p10.feature3);
		System.out.println("hasStylusSupport: " + p10.hasStylusSupport);
		System.out.println("isTouchScreen: " + p10.isTouchScreen);
		System.out.println("rating: " + p10.rating);


		PixelTablet p11 = new PixelTablet();
		p11.productId = 111;
		p11.brandName = "Sample11";
		p11.processor = "Sample11";
		p11.color = "Sample11";
		p11.storage = 21.0;
		p11.price = 21.0;
		p11.isWifiEnabled = false;
		p11.isAvailable = false;
		p11.manufacturingDate = "Sample11";
		p11.expiryDate = "Sample11";
		p11.screenType = "Sample11";
		p11.operatingSystem = "Sample11";
		p11.screenSize = 21.0;
		p11.hasFrontCamera = false;
		p11.countryOfOrigin = "Sample11";
		p11.warrantyMonths = 111;
		p11.packagingType = "Sample11";
		p11.weight = 21.0;
		p11.hasBluetooth = false;
		p11.feature1 = "Sample11";
		p11.feature2 = "Sample11";
		p11.feature3 = "Sample11";
		p11.hasStylusSupport = false;
		p11.isTouchScreen = false;
		p11.rating = 111;

		System.out.println("----- PixelTablet 11 -----");
		System.out.println("productId: " + p11.productId);
		System.out.println("brandName: " + p11.brandName);
		System.out.println("processor: " + p11.processor);
		System.out.println("color: " + p11.color);
		System.out.println("storage: " + p11.storage);
		System.out.println("price: " + p11.price);
		System.out.println("isWifiEnabled: " + p11.isWifiEnabled);
		System.out.println("isAvailable: " + p11.isAvailable);
		System.out.println("manufacturingDate: " + p11.manufacturingDate);
		System.out.println("expiryDate: " + p11.expiryDate);
		System.out.println("screenType: " + p11.screenType);
		System.out.println("operatingSystem: " + p11.operatingSystem);
		System.out.println("screenSize: " + p11.screenSize);
		System.out.println("hasFrontCamera: " + p11.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p11.countryOfOrigin);
		System.out.println("warrantyMonths: " + p11.warrantyMonths);
		System.out.println("packagingType: " + p11.packagingType);
		System.out.println("weight: " + p11.weight);
		System.out.println("hasBluetooth: " + p11.hasBluetooth);
		System.out.println("feature1: " + p11.feature1);
		System.out.println("feature2: " + p11.feature2);
		System.out.println("feature3: " + p11.feature3);
		System.out.println("hasStylusSupport: " + p11.hasStylusSupport);
		System.out.println("isTouchScreen: " + p11.isTouchScreen);
		System.out.println("rating: " + p11.rating);


		PixelTablet p12 = new PixelTablet();
		p12.productId = 112;
		p12.brandName = "Sample12";
		p12.processor = "Sample12";
		p12.color = "Sample12";
		p12.storage = 22.0;
		p12.price = 22.0;
		p12.isWifiEnabled = true;
		p12.isAvailable = true;
		p12.manufacturingDate = "Sample12";
		p12.expiryDate = "Sample12";
		p12.screenType = "Sample12";
		p12.operatingSystem = "Sample12";
		p12.screenSize = 22.0;
		p12.hasFrontCamera = true;
		p12.countryOfOrigin = "Sample12";
		p12.warrantyMonths = 112;
		p12.packagingType = "Sample12";
		p12.weight = 22.0;
		p12.hasBluetooth = true;
		p12.feature1 = "Sample12";
		p12.feature2 = "Sample12";
		p12.feature3 = "Sample12";
		p12.hasStylusSupport = true;
		p12.isTouchScreen = true;
		p12.rating = 112;

		System.out.println("----- PixelTablet 12 -----");
		System.out.println("productId: " + p12.productId);
		System.out.println("brandName: " + p12.brandName);
		System.out.println("processor: " + p12.processor);
		System.out.println("color: " + p12.color);
		System.out.println("storage: " + p12.storage);
		System.out.println("price: " + p12.price);
		System.out.println("isWifiEnabled: " + p12.isWifiEnabled);
		System.out.println("isAvailable: " + p12.isAvailable);
		System.out.println("manufacturingDate: " + p12.manufacturingDate);
		System.out.println("expiryDate: " + p12.expiryDate);
		System.out.println("screenType: " + p12.screenType);
		System.out.println("operatingSystem: " + p12.operatingSystem);
		System.out.println("screenSize: " + p12.screenSize);
		System.out.println("hasFrontCamera: " + p12.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p12.countryOfOrigin);
		System.out.println("warrantyMonths: " + p12.warrantyMonths);
		System.out.println("packagingType: " + p12.packagingType);
		System.out.println("weight: " + p12.weight);
		System.out.println("hasBluetooth: " + p12.hasBluetooth);
		System.out.println("feature1: " + p12.feature1);
		System.out.println("feature2: " + p12.feature2);
		System.out.println("feature3: " + p12.feature3);
		System.out.println("hasStylusSupport: " + p12.hasStylusSupport);
		System.out.println("isTouchScreen: " + p12.isTouchScreen);
		System.out.println("rating: " + p12.rating);


		PixelTablet p13 = new PixelTablet();
		p13.productId = 113;
		p13.brandName = "Sample13";
		p13.processor = "Sample13";
		p13.color = "Sample13";
		p13.storage = 23.0;
		p13.price = 23.0;
		p13.isWifiEnabled = false;
		p13.isAvailable = false;
		p13.manufacturingDate = "Sample13";
		p13.expiryDate = "Sample13";
		p13.screenType = "Sample13";
		p13.operatingSystem = "Sample13";
		p13.screenSize = 23.0;
		p13.hasFrontCamera = false;
		p13.countryOfOrigin = "Sample13";
		p13.warrantyMonths = 113;
		p13.packagingType = "Sample13";
		p13.weight = 23.0;
		p13.hasBluetooth = false;
		p13.feature1 = "Sample13";
		p13.feature2 = "Sample13";
		p13.feature3 = "Sample13";
		p13.hasStylusSupport = false;
		p13.isTouchScreen = false;
		p13.rating = 113;

		System.out.println("----- PixelTablet 13 -----");
		System.out.println("productId: " + p13.productId);
		System.out.println("brandName: " + p13.brandName);
		System.out.println("processor: " + p13.processor);
		System.out.println("color: " + p13.color);
		System.out.println("storage: " + p13.storage);
		System.out.println("price: " + p13.price);
		System.out.println("isWifiEnabled: " + p13.isWifiEnabled);
		System.out.println("isAvailable: " + p13.isAvailable);
		System.out.println("manufacturingDate: " + p13.manufacturingDate);
		System.out.println("expiryDate: " + p13.expiryDate);
		System.out.println("screenType: " + p13.screenType);
		System.out.println("operatingSystem: " + p13.operatingSystem);
		System.out.println("screenSize: " + p13.screenSize);
		System.out.println("hasFrontCamera: " + p13.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p13.countryOfOrigin);
		System.out.println("warrantyMonths: " + p13.warrantyMonths);
		System.out.println("packagingType: " + p13.packagingType);
		System.out.println("weight: " + p13.weight);
		System.out.println("hasBluetooth: " + p13.hasBluetooth);
		System.out.println("feature1: " + p13.feature1);
		System.out.println("feature2: " + p13.feature2);
		System.out.println("feature3: " + p13.feature3);
		System.out.println("hasStylusSupport: " + p13.hasStylusSupport);
		System.out.println("isTouchScreen: " + p13.isTouchScreen);
		System.out.println("rating: " + p13.rating);


		PixelTablet p14 = new PixelTablet();
		p14.productId = 114;
		p14.brandName = "Sample14";
		p14.processor = "Sample14";
		p14.color = "Sample14";
		p14.storage = 24.0;
		p14.price = 24.0;
		p14.isWifiEnabled = true;
		p14.isAvailable = true;
		p14.manufacturingDate = "Sample14";
		p14.expiryDate = "Sample14";
		p14.screenType = "Sample14";
		p14.operatingSystem = "Sample14";
		p14.screenSize = 24.0;
		p14.hasFrontCamera = true;
		p14.countryOfOrigin = "Sample14";
		p14.warrantyMonths = 114;
		p14.packagingType = "Sample14";
		p14.weight = 24.0;
		p14.hasBluetooth = true;
		p14.feature1 = "Sample14";
		p14.feature2 = "Sample14";
		p14.feature3 = "Sample14";
		p14.hasStylusSupport = true;
		p14.isTouchScreen = true;
		p14.rating = 114;

		System.out.println("----- PixelTablet 14 -----");
		System.out.println("productId: " + p14.productId);
		System.out.println("brandName: " + p14.brandName);
		System.out.println("processor: " + p14.processor);
		System.out.println("color: " + p14.color);
		System.out.println("storage: " + p14.storage);
		System.out.println("price: " + p14.price);
		System.out.println("isWifiEnabled: " + p14.isWifiEnabled);
		System.out.println("isAvailable: " + p14.isAvailable);
		System.out.println("manufacturingDate: " + p14.manufacturingDate);
		System.out.println("expiryDate: " + p14.expiryDate);
		System.out.println("screenType: " + p14.screenType);
		System.out.println("operatingSystem: " + p14.operatingSystem);
		System.out.println("screenSize: " + p14.screenSize);
		System.out.println("hasFrontCamera: " + p14.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p14.countryOfOrigin);
		System.out.println("warrantyMonths: " + p14.warrantyMonths);
		System.out.println("packagingType: " + p14.packagingType);
		System.out.println("weight: " + p14.weight);
		System.out.println("hasBluetooth: " + p14.hasBluetooth);
		System.out.println("feature1: " + p14.feature1);
		System.out.println("feature2: " + p14.feature2);
		System.out.println("feature3: " + p14.feature3);
		System.out.println("hasStylusSupport: " + p14.hasStylusSupport);
		System.out.println("isTouchScreen: " + p14.isTouchScreen);
		System.out.println("rating: " + p14.rating);


		PixelTablet p15 = new PixelTablet();
		p15.productId = 115;
		p15.brandName = "Sample15";
		p15.processor = "Sample15";
		p15.color = "Sample15";
		p15.storage = 25.0;
		p15.price = 25.0;
		p15.isWifiEnabled = false;
		p15.isAvailable = false;
		p15.manufacturingDate = "Sample15";
		p15.expiryDate = "Sample15";
		p15.screenType = "Sample15";
		p15.operatingSystem = "Sample15";
		p15.screenSize = 25.0;
		p15.hasFrontCamera = false;
		p15.countryOfOrigin = "Sample15";
		p15.warrantyMonths = 115;
		p15.packagingType = "Sample15";
		p15.weight = 25.0;
		p15.hasBluetooth = false;
		p15.feature1 = "Sample15";
		p15.feature2 = "Sample15";
		p15.feature3 = "Sample15";
		p15.hasStylusSupport = false;
		p15.isTouchScreen = false;
		p15.rating = 115;

		System.out.println("----- PixelTablet 15 -----");
		System.out.println("productId: " + p15.productId);
		System.out.println("brandName: " + p15.brandName);
		System.out.println("processor: " + p15.processor);
		System.out.println("color: " + p15.color);
		System.out.println("storage: " + p15.storage);
		System.out.println("price: " + p15.price);
		System.out.println("isWifiEnabled: " + p15.isWifiEnabled);
		System.out.println("isAvailable: " + p15.isAvailable);
		System.out.println("manufacturingDate: " + p15.manufacturingDate);
		System.out.println("expiryDate: " + p15.expiryDate);
		System.out.println("screenType: " + p15.screenType);
		System.out.println("operatingSystem: " + p15.operatingSystem);
		System.out.println("screenSize: " + p15.screenSize);
		System.out.println("hasFrontCamera: " + p15.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p15.countryOfOrigin);
		System.out.println("warrantyMonths: " + p15.warrantyMonths);
		System.out.println("packagingType: " + p15.packagingType);
		System.out.println("weight: " + p15.weight);
		System.out.println("hasBluetooth: " + p15.hasBluetooth);
		System.out.println("feature1: " + p15.feature1);
		System.out.println("feature2: " + p15.feature2);
		System.out.println("feature3: " + p15.feature3);
		System.out.println("hasStylusSupport: " + p15.hasStylusSupport);
		System.out.println("isTouchScreen: " + p15.isTouchScreen);
		System.out.println("rating: " + p15.rating);


		PixelTablet p16 = new PixelTablet();
		p16.productId = 116;
		p16.brandName = "Sample16";
		p16.processor = "Sample16";
		p16.color = "Sample16";
		p16.storage = 26.0;
		p16.price = 26.0;
		p16.isWifiEnabled = true;
		p16.isAvailable = true;
		p16.manufacturingDate = "Sample16";
		p16.expiryDate = "Sample16";
		p16.screenType = "Sample16";
		p16.operatingSystem = "Sample16";
		p16.screenSize = 26.0;
		p16.hasFrontCamera = true;
		p16.countryOfOrigin = "Sample16";
		p16.warrantyMonths = 116;
		p16.packagingType = "Sample16";
		p16.weight = 26.0;
		p16.hasBluetooth = true;
		p16.feature1 = "Sample16";
		p16.feature2 = "Sample16";
		p16.feature3 = "Sample16";
		p16.hasStylusSupport = true;
		p16.isTouchScreen = true;
		p16.rating = 116;

		System.out.println("----- PixelTablet 16 -----");
		System.out.println("productId: " + p16.productId);
		System.out.println("brandName: " + p16.brandName);
		System.out.println("processor: " + p16.processor);
		System.out.println("color: " + p16.color);
		System.out.println("storage: " + p16.storage);
		System.out.println("price: " + p16.price);
		System.out.println("isWifiEnabled: " + p16.isWifiEnabled);
		System.out.println("isAvailable: " + p16.isAvailable);
		System.out.println("manufacturingDate: " + p16.manufacturingDate);
		System.out.println("expiryDate: " + p16.expiryDate);
		System.out.println("screenType: " + p16.screenType);
		System.out.println("operatingSystem: " + p16.operatingSystem);
		System.out.println("screenSize: " + p16.screenSize);
		System.out.println("hasFrontCamera: " + p16.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p16.countryOfOrigin);
		System.out.println("warrantyMonths: " + p16.warrantyMonths);
		System.out.println("packagingType: " + p16.packagingType);
		System.out.println("weight: " + p16.weight);
		System.out.println("hasBluetooth: " + p16.hasBluetooth);
		System.out.println("feature1: " + p16.feature1);
		System.out.println("feature2: " + p16.feature2);
		System.out.println("feature3: " + p16.feature3);
		System.out.println("hasStylusSupport: " + p16.hasStylusSupport);
		System.out.println("isTouchScreen: " + p16.isTouchScreen);
		System.out.println("rating: " + p16.rating);


		PixelTablet p17 = new PixelTablet();
		p17.productId = 117;
		p17.brandName = "Sample17";
		p17.processor = "Sample17";
		p17.color = "Sample17";
		p17.storage = 27.0;
		p17.price = 27.0;
		p17.isWifiEnabled = false;
		p17.isAvailable = false;
		p17.manufacturingDate = "Sample17";
		p17.expiryDate = "Sample17";
		p17.screenType = "Sample17";
		p17.operatingSystem = "Sample17";
		p17.screenSize = 27.0;
		p17.hasFrontCamera = false;
		p17.countryOfOrigin = "Sample17";
		p17.warrantyMonths = 117;
		p17.packagingType = "Sample17";
		p17.weight = 27.0;
		p17.hasBluetooth = false;
		p17.feature1 = "Sample17";
		p17.feature2 = "Sample17";
		p17.feature3 = "Sample17";
		p17.hasStylusSupport = false;
		p17.isTouchScreen = false;
		p17.rating = 117;

		System.out.println("----- PixelTablet 17 -----");
		System.out.println("productId: " + p17.productId);
		System.out.println("brandName: " + p17.brandName);
		System.out.println("processor: " + p17.processor);
		System.out.println("color: " + p17.color);
		System.out.println("storage: " + p17.storage);
		System.out.println("price: " + p17.price);
		System.out.println("isWifiEnabled: " + p17.isWifiEnabled);
		System.out.println("isAvailable: " + p17.isAvailable);
		System.out.println("manufacturingDate: " + p17.manufacturingDate);
		System.out.println("expiryDate: " + p17.expiryDate);
		System.out.println("screenType: " + p17.screenType);
		System.out.println("operatingSystem: " + p17.operatingSystem);
		System.out.println("screenSize: " + p17.screenSize);
		System.out.println("hasFrontCamera: " + p17.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p17.countryOfOrigin);
		System.out.println("warrantyMonths: " + p17.warrantyMonths);
		System.out.println("packagingType: " + p17.packagingType);
		System.out.println("weight: " + p17.weight);
		System.out.println("hasBluetooth: " + p17.hasBluetooth);
		System.out.println("feature1: " + p17.feature1);
		System.out.println("feature2: " + p17.feature2);
		System.out.println("feature3: " + p17.feature3);
		System.out.println("hasStylusSupport: " + p17.hasStylusSupport);
		System.out.println("isTouchScreen: " + p17.isTouchScreen);
		System.out.println("rating: " + p17.rating);


		PixelTablet p18 = new PixelTablet();
		p18.productId = 118;
		p18.brandName = "Sample18";
		p18.processor = "Sample18";
		p18.color = "Sample18";
		p18.storage = 28.0;
		p18.price = 28.0;
		p18.isWifiEnabled = true;
		p18.isAvailable = true;
		p18.manufacturingDate = "Sample18";
		p18.expiryDate = "Sample18";
		p18.screenType = "Sample18";
		p18.operatingSystem = "Sample18";
		p18.screenSize = 28.0;
		p18.hasFrontCamera = true;
		p18.countryOfOrigin = "Sample18";
		p18.warrantyMonths = 118;
		p18.packagingType = "Sample18";
		p18.weight = 28.0;
		p18.hasBluetooth = true;
		p18.feature1 = "Sample18";
		p18.feature2 = "Sample18";
		p18.feature3 = "Sample18";
		p18.hasStylusSupport = true;
		p18.isTouchScreen = true;
		p18.rating = 118;

		System.out.println("----- PixelTablet 18 -----");
		System.out.println("productId: " + p18.productId);
		System.out.println("brandName: " + p18.brandName);
		System.out.println("processor: " + p18.processor);
		System.out.println("color: " + p18.color);
		System.out.println("storage: " + p18.storage);
		System.out.println("price: " + p18.price);
		System.out.println("isWifiEnabled: " + p18.isWifiEnabled);
		System.out.println("isAvailable: " + p18.isAvailable);
		System.out.println("manufacturingDate: " + p18.manufacturingDate);
		System.out.println("expiryDate: " + p18.expiryDate);
		System.out.println("screenType: " + p18.screenType);
		System.out.println("operatingSystem: " + p18.operatingSystem);
		System.out.println("screenSize: " + p18.screenSize);
		System.out.println("hasFrontCamera: " + p18.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p18.countryOfOrigin);
		System.out.println("warrantyMonths: " + p18.warrantyMonths);
		System.out.println("packagingType: " + p18.packagingType);
		System.out.println("weight: " + p18.weight);
		System.out.println("hasBluetooth: " + p18.hasBluetooth);
		System.out.println("feature1: " + p18.feature1);
		System.out.println("feature2: " + p18.feature2);
		System.out.println("feature3: " + p18.feature3);
		System.out.println("hasStylusSupport: " + p18.hasStylusSupport);
		System.out.println("isTouchScreen: " + p18.isTouchScreen);
		System.out.println("rating: " + p18.rating);


		PixelTablet p19 = new PixelTablet();
		p19.productId = 119;
		p19.brandName = "Sample19";
		p19.processor = "Sample19";
		p19.color = "Sample19";
		p19.storage = 29.0;
		p19.price = 29.0;
		p19.isWifiEnabled = false;
		p19.isAvailable = false;
		p19.manufacturingDate = "Sample19";
		p19.expiryDate = "Sample19";
		p19.screenType = "Sample19";
		p19.operatingSystem = "Sample19";
		p19.screenSize = 29.0;
		p19.hasFrontCamera = false;
		p19.countryOfOrigin = "Sample19";
		p19.warrantyMonths = 119;
		p19.packagingType = "Sample19";
		p19.weight = 29.0;
		p19.hasBluetooth = false;
		p19.feature1 = "Sample19";
		p19.feature2 = "Sample19";
		p19.feature3 = "Sample19";
		p19.hasStylusSupport = false;
		p19.isTouchScreen = false;
		p19.rating = 119;

		System.out.println("----- PixelTablet 19 -----");
		System.out.println("productId: " + p19.productId);
		System.out.println("brandName: " + p19.brandName);
		System.out.println("processor: " + p19.processor);
		System.out.println("color: " + p19.color);
		System.out.println("storage: " + p19.storage);
		System.out.println("price: " + p19.price);
		System.out.println("isWifiEnabled: " + p19.isWifiEnabled);
		System.out.println("isAvailable: " + p19.isAvailable);
		System.out.println("manufacturingDate: " + p19.manufacturingDate);
		System.out.println("expiryDate: " + p19.expiryDate);
		System.out.println("screenType: " + p19.screenType);
		System.out.println("operatingSystem: " + p19.operatingSystem);
		System.out.println("screenSize: " + p19.screenSize);
		System.out.println("hasFrontCamera: " + p19.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p19.countryOfOrigin);
		System.out.println("warrantyMonths: " + p19.warrantyMonths);
		System.out.println("packagingType: " + p19.packagingType);
		System.out.println("weight: " + p19.weight);
		System.out.println("hasBluetooth: " + p19.hasBluetooth);
		System.out.println("feature1: " + p19.feature1);
		System.out.println("feature2: " + p19.feature2);
		System.out.println("feature3: " + p19.feature3);
		System.out.println("hasStylusSupport: " + p19.hasStylusSupport);
		System.out.println("isTouchScreen: " + p19.isTouchScreen);
		System.out.println("rating: " + p19.rating);


		PixelTablet p20 = new PixelTablet();
		p20.productId = 120;
		p20.brandName = "Sample20";
		p20.processor = "Sample20";
		p20.color = "Sample20";
		p20.storage = 30.0;
		p20.price = 30.0;
		p20.isWifiEnabled = true;
		p20.isAvailable = true;
		p20.manufacturingDate = "Sample20";
		p20.expiryDate = "Sample20";
		p20.screenType = "Sample20";
		p20.operatingSystem = "Sample20";
		p20.screenSize = 30.0;
		p20.hasFrontCamera = true;
		p20.countryOfOrigin = "Sample20";
		p20.warrantyMonths = 120;
		p20.packagingType = "Sample20";
		p20.weight = 30.0;
		p20.hasBluetooth = true;
		p20.feature1 = "Sample20";
		p20.feature2 = "Sample20";
		p20.feature3 = "Sample20";
		p20.hasStylusSupport = true;
		p20.isTouchScreen = true;
		p20.rating = 120;

		System.out.println("----- PixelTablet 20 -----");
		System.out.println("productId: " + p20.productId);
		System.out.println("brandName: " + p20.brandName);
		System.out.println("processor: " + p20.processor);
		System.out.println("color: " + p20.color);
		System.out.println("storage: " + p20.storage);
		System.out.println("price: " + p20.price);
		System.out.println("isWifiEnabled: " + p20.isWifiEnabled);
		System.out.println("isAvailable: " + p20.isAvailable);
		System.out.println("manufacturingDate: " + p20.manufacturingDate);
		System.out.println("expiryDate: " + p20.expiryDate);
		System.out.println("screenType: " + p20.screenType);
		System.out.println("operatingSystem: " + p20.operatingSystem);
		System.out.println("screenSize: " + p20.screenSize);
		System.out.println("hasFrontCamera: " + p20.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p20.countryOfOrigin);
		System.out.println("warrantyMonths: " + p20.warrantyMonths);
		System.out.println("packagingType: " + p20.packagingType);
		System.out.println("weight: " + p20.weight);
		System.out.println("hasBluetooth: " + p20.hasBluetooth);
		System.out.println("feature1: " + p20.feature1);
		System.out.println("feature2: " + p20.feature2);
		System.out.println("feature3: " + p20.feature3);
		System.out.println("hasStylusSupport: " + p20.hasStylusSupport);
		System.out.println("isTouchScreen: " + p20.isTouchScreen);
		System.out.println("rating: " + p20.rating);


		PixelTablet p21 = new PixelTablet();
		p21.productId = 121;
		p21.brandName = "Sample21";
		p21.processor = "Sample21";
		p21.color = "Sample21";
		p21.storage = 31.0;
		p21.price = 31.0;
		p21.isWifiEnabled = false;
		p21.isAvailable = false;
		p21.manufacturingDate = "Sample21";
		p21.expiryDate = "Sample21";
		p21.screenType = "Sample21";
		p21.operatingSystem = "Sample21";
		p21.screenSize = 31.0;
		p21.hasFrontCamera = false;
		p21.countryOfOrigin = "Sample21";
		p21.warrantyMonths = 121;
		p21.packagingType = "Sample21";
		p21.weight = 31.0;
		p21.hasBluetooth = false;
		p21.feature1 = "Sample21";
		p21.feature2 = "Sample21";
		p21.feature3 = "Sample21";
		p21.hasStylusSupport = false;
		p21.isTouchScreen = false;
		p21.rating = 121;

		System.out.println("----- PixelTablet 21 -----");
		System.out.println("productId: " + p21.productId);
		System.out.println("brandName: " + p21.brandName);
		System.out.println("processor: " + p21.processor);
		System.out.println("color: " + p21.color);
		System.out.println("storage: " + p21.storage);
		System.out.println("price: " + p21.price);
		System.out.println("isWifiEnabled: " + p21.isWifiEnabled);
		System.out.println("isAvailable: " + p21.isAvailable);
		System.out.println("manufacturingDate: " + p21.manufacturingDate);
		System.out.println("expiryDate: " + p21.expiryDate);
		System.out.println("screenType: " + p21.screenType);
		System.out.println("operatingSystem: " + p21.operatingSystem);
		System.out.println("screenSize: " + p21.screenSize);
		System.out.println("hasFrontCamera: " + p21.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p21.countryOfOrigin);
		System.out.println("warrantyMonths: " + p21.warrantyMonths);
		System.out.println("packagingType: " + p21.packagingType);
		System.out.println("weight: " + p21.weight);
		System.out.println("hasBluetooth: " + p21.hasBluetooth);
		System.out.println("feature1: " + p21.feature1);
		System.out.println("feature2: " + p21.feature2);
		System.out.println("feature3: " + p21.feature3);
		System.out.println("hasStylusSupport: " + p21.hasStylusSupport);
		System.out.println("isTouchScreen: " + p21.isTouchScreen);
		System.out.println("rating: " + p21.rating);


		PixelTablet p22 = new PixelTablet();
		p22.productId = 122;
		p22.brandName = "Sample22";
		p22.processor = "Sample22";
		p22.color = "Sample22";
		p22.storage = 32.0;
		p22.price = 32.0;
		p22.isWifiEnabled = true;
		p22.isAvailable = true;
		p22.manufacturingDate = "Sample22";
		p22.expiryDate = "Sample22";
		p22.screenType = "Sample22";
		p22.operatingSystem = "Sample22";
		p22.screenSize = 32.0;
		p22.hasFrontCamera = true;
		p22.countryOfOrigin = "Sample22";
		p22.warrantyMonths = 122;
		p22.packagingType = "Sample22";
		p22.weight = 32.0;
		p22.hasBluetooth = true;
		p22.feature1 = "Sample22";
		p22.feature2 = "Sample22";
		p22.feature3 = "Sample22";
		p22.hasStylusSupport = true;
		p22.isTouchScreen = true;
		p22.rating = 122;

		System.out.println("----- PixelTablet 22 -----");
		System.out.println("productId: " + p22.productId);
		System.out.println("brandName: " + p22.brandName);
		System.out.println("processor: " + p22.processor);
		System.out.println("color: " + p22.color);
		System.out.println("storage: " + p22.storage);
		System.out.println("price: " + p22.price);
		System.out.println("isWifiEnabled: " + p22.isWifiEnabled);
		System.out.println("isAvailable: " + p22.isAvailable);
		System.out.println("manufacturingDate: " + p22.manufacturingDate);
		System.out.println("expiryDate: " + p22.expiryDate);
		System.out.println("screenType: " + p22.screenType);
		System.out.println("operatingSystem: " + p22.operatingSystem);
		System.out.println("screenSize: " + p22.screenSize);
		System.out.println("hasFrontCamera: " + p22.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p22.countryOfOrigin);
		System.out.println("warrantyMonths: " + p22.warrantyMonths);
		System.out.println("packagingType: " + p22.packagingType);
		System.out.println("weight: " + p22.weight);
		System.out.println("hasBluetooth: " + p22.hasBluetooth);
		System.out.println("feature1: " + p22.feature1);
		System.out.println("feature2: " + p22.feature2);
		System.out.println("feature3: " + p22.feature3);
		System.out.println("hasStylusSupport: " + p22.hasStylusSupport);
		System.out.println("isTouchScreen: " + p22.isTouchScreen);
		System.out.println("rating: " + p22.rating);


		PixelTablet p23 = new PixelTablet();
		p23.productId = 123;
		p23.brandName = "Sample23";
		p23.processor = "Sample23";
		p23.color = "Sample23";
		p23.storage = 33.0;
		p23.price = 33.0;
		p23.isWifiEnabled = false;
		p23.isAvailable = false;
		p23.manufacturingDate = "Sample23";
		p23.expiryDate = "Sample23";
		p23.screenType = "Sample23";
		p23.operatingSystem = "Sample23";
		p23.screenSize = 33.0;
		p23.hasFrontCamera = false;
		p23.countryOfOrigin = "Sample23";
		p23.warrantyMonths = 123;
		p23.packagingType = "Sample23";
		p23.weight = 33.0;
		p23.hasBluetooth = false;
		p23.feature1 = "Sample23";
		p23.feature2 = "Sample23";
		p23.feature3 = "Sample23";
		p23.hasStylusSupport = false;
		p23.isTouchScreen = false;
		p23.rating = 123;

		System.out.println("----- PixelTablet 23 -----");
		System.out.println("productId: " + p23.productId);
		System.out.println("brandName: " + p23.brandName);
		System.out.println("processor: " + p23.processor);
		System.out.println("color: " + p23.color);
		System.out.println("storage: " + p23.storage);
		System.out.println("price: " + p23.price);
		System.out.println("isWifiEnabled: " + p23.isWifiEnabled);
		System.out.println("isAvailable: " + p23.isAvailable);
		System.out.println("manufacturingDate: " + p23.manufacturingDate);
		System.out.println("expiryDate: " + p23.expiryDate);
		System.out.println("screenType: " + p23.screenType);
		System.out.println("operatingSystem: " + p23.operatingSystem);
		System.out.println("screenSize: " + p23.screenSize);
		System.out.println("hasFrontCamera: " + p23.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p23.countryOfOrigin);
		System.out.println("warrantyMonths: " + p23.warrantyMonths);
		System.out.println("packagingType: " + p23.packagingType);
		System.out.println("weight: " + p23.weight);
		System.out.println("hasBluetooth: " + p23.hasBluetooth);
		System.out.println("feature1: " + p23.feature1);
		System.out.println("feature2: " + p23.feature2);
		System.out.println("feature3: " + p23.feature3);
		System.out.println("hasStylusSupport: " + p23.hasStylusSupport);
		System.out.println("isTouchScreen: " + p23.isTouchScreen);
		System.out.println("rating: " + p23.rating);


		PixelTablet p24 = new PixelTablet();
		p24.productId = 124;
		p24.brandName = "Sample24";
		p24.processor = "Sample24";
		p24.color = "Sample24";
		p24.storage = 34.0;
		p24.price = 34.0;
		p24.isWifiEnabled = true;
		p24.isAvailable = true;
		p24.manufacturingDate = "Sample24";
		p24.expiryDate = "Sample24";
		p24.screenType = "Sample24";
		p24.operatingSystem = "Sample24";
		p24.screenSize = 34.0;
		p24.hasFrontCamera = true;
		p24.countryOfOrigin = "Sample24";
		p24.warrantyMonths = 124;
		p24.packagingType = "Sample24";
		p24.weight = 34.0;
		p24.hasBluetooth = true;
		p24.feature1 = "Sample24";
		p24.feature2 = "Sample24";
		p24.feature3 = "Sample24";
		p24.hasStylusSupport = true;
		p24.isTouchScreen = true;
		p24.rating = 124;

		System.out.println("----- PixelTablet 24 -----");
		System.out.println("productId: " + p24.productId);
		System.out.println("brandName: " + p24.brandName);
		System.out.println("processor: " + p24.processor);
		System.out.println("color: " + p24.color);
		System.out.println("storage: " + p24.storage);
		System.out.println("price: " + p24.price);
		System.out.println("isWifiEnabled: " + p24.isWifiEnabled);
		System.out.println("isAvailable: " + p24.isAvailable);
		System.out.println("manufacturingDate: " + p24.manufacturingDate);
		System.out.println("expiryDate: " + p24.expiryDate);
		System.out.println("screenType: " + p24.screenType);
		System.out.println("operatingSystem: " + p24.operatingSystem);
		System.out.println("screenSize: " + p24.screenSize);
		System.out.println("hasFrontCamera: " + p24.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p24.countryOfOrigin);
		System.out.println("warrantyMonths: " + p24.warrantyMonths);
		System.out.println("packagingType: " + p24.packagingType);
		System.out.println("weight: " + p24.weight);
		System.out.println("hasBluetooth: " + p24.hasBluetooth);
		System.out.println("feature1: " + p24.feature1);
		System.out.println("feature2: " + p24.feature2);
		System.out.println("feature3: " + p24.feature3);
		System.out.println("hasStylusSupport: " + p24.hasStylusSupport);
		System.out.println("isTouchScreen: " + p24.isTouchScreen);
		System.out.println("rating: " + p24.rating);


		PixelTablet p25 = new PixelTablet();
		p25.productId = 125;
		p25.brandName = "Sample25";
		p25.processor = "Sample25";
		p25.color = "Sample25";
		p25.storage = 35.0;
		p25.price = 35.0;
		p25.isWifiEnabled = false;
		p25.isAvailable = false;
		p25.manufacturingDate = "Sample25";
		p25.expiryDate = "Sample25";
		p25.screenType = "Sample25";
		p25.operatingSystem = "Sample25";
		p25.screenSize = 35.0;
		p25.hasFrontCamera = false;
		p25.countryOfOrigin = "Sample25";
		p25.warrantyMonths = 125;
		p25.packagingType = "Sample25";
		p25.weight = 35.0;
		p25.hasBluetooth = false;
		p25.feature1 = "Sample25";
		p25.feature2 = "Sample25";
		p25.feature3 = "Sample25";
		p25.hasStylusSupport = false;
		p25.isTouchScreen = false;
		p25.rating = 125;

		System.out.println("----- PixelTablet 25 -----");
		System.out.println("productId: " + p25.productId);
		System.out.println("brandName: " + p25.brandName);
		System.out.println("processor: " + p25.processor);
		System.out.println("color: " + p25.color);
		System.out.println("storage: " + p25.storage);
		System.out.println("price: " + p25.price);
		System.out.println("isWifiEnabled: " + p25.isWifiEnabled);
		System.out.println("isAvailable: " + p25.isAvailable);
		System.out.println("manufacturingDate: " + p25.manufacturingDate);
		System.out.println("expiryDate: " + p25.expiryDate);
		System.out.println("screenType: " + p25.screenType);
		System.out.println("operatingSystem: " + p25.operatingSystem);
		System.out.println("screenSize: " + p25.screenSize);
		System.out.println("hasFrontCamera: " + p25.hasFrontCamera);
		System.out.println("countryOfOrigin: " + p25.countryOfOrigin);
		System.out.println("warrantyMonths: " + p25.warrantyMonths);
		System.out.println("packagingType: " + p25.packagingType);
		System.out.println("weight: " + p25.weight);
		System.out.println("hasBluetooth: " + p25.hasBluetooth);
		System.out.println("feature1: " + p25.feature1);
		System.out.println("feature2: " + p25.feature2);
		System.out.println("feature3: " + p25.feature3);
		System.out.println("hasStylusSupport: " + p25.hasStylusSupport);
		System.out.println("isTouchScreen: " + p25.isTouchScreen);
		System.out.println("rating: " + p25.rating);


	}
}
