class QuantumMouseRunner {
	public static void main(String[] args) {

		QuantumMouse q1 = new QuantumMouse();
		q1.productId = 101;
		q1.brandName = "Sample1";
		q1.connectivityType = "Sample1";
		q1.color = "Sample1";
		q1.dpi = 11.0;
		q1.price = 11.0;
		q1.isWireless = false;
		q1.isAvailable = false;
		q1.manufacturingDate = "Sample1";
		q1.expiryDate = "Sample1";
		q1.sensorType = "Sample1";
		q1.material = "Sample1";
		q1.weight = 11.0;
		q1.isErgonomic = false;
		q1.countryOfOrigin = "Sample1";
		q1.warrantyMonths = 101;
		q1.packagingType = "Sample1";
		q1.cableLength = 11.0;
		q1.hasRGB = false;
		q1.feature1 = "Sample1";
		q1.feature2 = "Sample1";
		q1.feature3 = "Sample1";
		q1.hasBluetooth = false;
		q1.isRechargeable = false;
		q1.rating = 101;

		System.out.println("----- QuantumMouse 1 -----");
		System.out.println("productId: " + q1.productId);
		System.out.println("brandName: " + q1.brandName);
		System.out.println("connectivityType: " + q1.connectivityType);
		System.out.println("color: " + q1.color);
		System.out.println("dpi: " + q1.dpi);
		System.out.println("price: " + q1.price);
		System.out.println("isWireless: " + q1.isWireless);
		System.out.println("isAvailable: " + q1.isAvailable);
		System.out.println("manufacturingDate: " + q1.manufacturingDate);
		System.out.println("expiryDate: " + q1.expiryDate);
		System.out.println("sensorType: " + q1.sensorType);
		System.out.println("material: " + q1.material);
		System.out.println("weight: " + q1.weight);
		System.out.println("isErgonomic: " + q1.isErgonomic);
		System.out.println("countryOfOrigin: " + q1.countryOfOrigin);
		System.out.println("warrantyMonths: " + q1.warrantyMonths);
		System.out.println("packagingType: " + q1.packagingType);
		System.out.println("cableLength: " + q1.cableLength);
		System.out.println("hasRGB: " + q1.hasRGB);
		System.out.println("feature1: " + q1.feature1);
		System.out.println("feature2: " + q1.feature2);
		System.out.println("feature3: " + q1.feature3);
		System.out.println("hasBluetooth: " + q1.hasBluetooth);
		System.out.println("isRechargeable: " + q1.isRechargeable);
		System.out.println("rating: " + q1.rating);


		QuantumMouse q2 = new QuantumMouse();
		q2.productId = 102;
		q2.brandName = "Sample2";
		q2.connectivityType = "Sample2";
		q2.color = "Sample2";
		q2.dpi = 12.0;
		q2.price = 12.0;
		q2.isWireless = true;
		q2.isAvailable = true;
		q2.manufacturingDate = "Sample2";
		q2.expiryDate = "Sample2";
		q2.sensorType = "Sample2";
		q2.material = "Sample2";
		q2.weight = 12.0;
		q2.isErgonomic = true;
		q2.countryOfOrigin = "Sample2";
		q2.warrantyMonths = 102;
		q2.packagingType = "Sample2";
		q2.cableLength = 12.0;
		q2.hasRGB = true;
		q2.feature1 = "Sample2";
		q2.feature2 = "Sample2";
		q2.feature3 = "Sample2";
		q2.hasBluetooth = true;
		q2.isRechargeable = true;
		q2.rating = 102;

		System.out.println("----- QuantumMouse 2 -----");
		System.out.println("productId: " + q2.productId);
		System.out.println("brandName: " + q2.brandName);
		System.out.println("connectivityType: " + q2.connectivityType);
		System.out.println("color: " + q2.color);
		System.out.println("dpi: " + q2.dpi);
		System.out.println("price: " + q2.price);
		System.out.println("isWireless: " + q2.isWireless);
		System.out.println("isAvailable: " + q2.isAvailable);
		System.out.println("manufacturingDate: " + q2.manufacturingDate);
		System.out.println("expiryDate: " + q2.expiryDate);
		System.out.println("sensorType: " + q2.sensorType);
		System.out.println("material: " + q2.material);
		System.out.println("weight: " + q2.weight);
		System.out.println("isErgonomic: " + q2.isErgonomic);
		System.out.println("countryOfOrigin: " + q2.countryOfOrigin);
		System.out.println("warrantyMonths: " + q2.warrantyMonths);
		System.out.println("packagingType: " + q2.packagingType);
		System.out.println("cableLength: " + q2.cableLength);
		System.out.println("hasRGB: " + q2.hasRGB);
		System.out.println("feature1: " + q2.feature1);
		System.out.println("feature2: " + q2.feature2);
		System.out.println("feature3: " + q2.feature3);
		System.out.println("hasBluetooth: " + q2.hasBluetooth);
		System.out.println("isRechargeable: " + q2.isRechargeable);
		System.out.println("rating: " + q2.rating);


		QuantumMouse q3 = new QuantumMouse();
		q3.productId = 103;
		q3.brandName = "Sample3";
		q3.connectivityType = "Sample3";
		q3.color = "Sample3";
		q3.dpi = 13.0;
		q3.price = 13.0;
		q3.isWireless = false;
		q3.isAvailable = false;
		q3.manufacturingDate = "Sample3";
		q3.expiryDate = "Sample3";
		q3.sensorType = "Sample3";
		q3.material = "Sample3";
		q3.weight = 13.0;
		q3.isErgonomic = false;
		q3.countryOfOrigin = "Sample3";
		q3.warrantyMonths = 103;
		q3.packagingType = "Sample3";
		q3.cableLength = 13.0;
		q3.hasRGB = false;
		q3.feature1 = "Sample3";
		q3.feature2 = "Sample3";
		q3.feature3 = "Sample3";
		q3.hasBluetooth = false;
		q3.isRechargeable = false;
		q3.rating = 103;

		System.out.println("----- QuantumMouse 3 -----");
		System.out.println("productId: " + q3.productId);
		System.out.println("brandName: " + q3.brandName);
		System.out.println("connectivityType: " + q3.connectivityType);
		System.out.println("color: " + q3.color);
		System.out.println("dpi: " + q3.dpi);
		System.out.println("price: " + q3.price);
		System.out.println("isWireless: " + q3.isWireless);
		System.out.println("isAvailable: " + q3.isAvailable);
		System.out.println("manufacturingDate: " + q3.manufacturingDate);
		System.out.println("expiryDate: " + q3.expiryDate);
		System.out.println("sensorType: " + q3.sensorType);
		System.out.println("material: " + q3.material);
		System.out.println("weight: " + q3.weight);
		System.out.println("isErgonomic: " + q3.isErgonomic);
		System.out.println("countryOfOrigin: " + q3.countryOfOrigin);
		System.out.println("warrantyMonths: " + q3.warrantyMonths);
		System.out.println("packagingType: " + q3.packagingType);
		System.out.println("cableLength: " + q3.cableLength);
		System.out.println("hasRGB: " + q3.hasRGB);
		System.out.println("feature1: " + q3.feature1);
		System.out.println("feature2: " + q3.feature2);
		System.out.println("feature3: " + q3.feature3);
		System.out.println("hasBluetooth: " + q3.hasBluetooth);
		System.out.println("isRechargeable: " + q3.isRechargeable);
		System.out.println("rating: " + q3.rating);


		QuantumMouse q4 = new QuantumMouse();
		q4.productId = 104;
		q4.brandName = "Sample4";
		q4.connectivityType = "Sample4";
		q4.color = "Sample4";
		q4.dpi = 14.0;
		q4.price = 14.0;
		q4.isWireless = true;
		q4.isAvailable = true;
		q4.manufacturingDate = "Sample4";
		q4.expiryDate = "Sample4";
		q4.sensorType = "Sample4";
		q4.material = "Sample4";
		q4.weight = 14.0;
		q4.isErgonomic = true;
		q4.countryOfOrigin = "Sample4";
		q4.warrantyMonths = 104;
		q4.packagingType = "Sample4";
		q4.cableLength = 14.0;
		q4.hasRGB = true;
		q4.feature1 = "Sample4";
		q4.feature2 = "Sample4";
		q4.feature3 = "Sample4";
		q4.hasBluetooth = true;
		q4.isRechargeable = true;
		q4.rating = 104;

		System.out.println("----- QuantumMouse 4 -----");
		System.out.println("productId: " + q4.productId);
		System.out.println("brandName: " + q4.brandName);
		System.out.println("connectivityType: " + q4.connectivityType);
		System.out.println("color: " + q4.color);
		System.out.println("dpi: " + q4.dpi);
		System.out.println("price: " + q4.price);
		System.out.println("isWireless: " + q4.isWireless);
		System.out.println("isAvailable: " + q4.isAvailable);
		System.out.println("manufacturingDate: " + q4.manufacturingDate);
		System.out.println("expiryDate: " + q4.expiryDate);
		System.out.println("sensorType: " + q4.sensorType);
		System.out.println("material: " + q4.material);
		System.out.println("weight: " + q4.weight);
		System.out.println("isErgonomic: " + q4.isErgonomic);
		System.out.println("countryOfOrigin: " + q4.countryOfOrigin);
		System.out.println("warrantyMonths: " + q4.warrantyMonths);
		System.out.println("packagingType: " + q4.packagingType);
		System.out.println("cableLength: " + q4.cableLength);
		System.out.println("hasRGB: " + q4.hasRGB);
		System.out.println("feature1: " + q4.feature1);
		System.out.println("feature2: " + q4.feature2);
		System.out.println("feature3: " + q4.feature3);
		System.out.println("hasBluetooth: " + q4.hasBluetooth);
		System.out.println("isRechargeable: " + q4.isRechargeable);
		System.out.println("rating: " + q4.rating);


		QuantumMouse q5 = new QuantumMouse();
		q5.productId = 105;
		q5.brandName = "Sample5";
		q5.connectivityType = "Sample5";
		q5.color = "Sample5";
		q5.dpi = 15.0;
		q5.price = 15.0;
		q5.isWireless = false;
		q5.isAvailable = false;
		q5.manufacturingDate = "Sample5";
		q5.expiryDate = "Sample5";
		q5.sensorType = "Sample5";
		q5.material = "Sample5";
		q5.weight = 15.0;
		q5.isErgonomic = false;
		q5.countryOfOrigin = "Sample5";
		q5.warrantyMonths = 105;
		q5.packagingType = "Sample5";
		q5.cableLength = 15.0;
		q5.hasRGB = false;
		q5.feature1 = "Sample5";
		q5.feature2 = "Sample5";
		q5.feature3 = "Sample5";
		q5.hasBluetooth = false;
		q5.isRechargeable = false;
		q5.rating = 105;

		System.out.println("----- QuantumMouse 5 -----");
		System.out.println("productId: " + q5.productId);
		System.out.println("brandName: " + q5.brandName);
		System.out.println("connectivityType: " + q5.connectivityType);
		System.out.println("color: " + q5.color);
		System.out.println("dpi: " + q5.dpi);
		System.out.println("price: " + q5.price);
		System.out.println("isWireless: " + q5.isWireless);
		System.out.println("isAvailable: " + q5.isAvailable);
		System.out.println("manufacturingDate: " + q5.manufacturingDate);
		System.out.println("expiryDate: " + q5.expiryDate);
		System.out.println("sensorType: " + q5.sensorType);
		System.out.println("material: " + q5.material);
		System.out.println("weight: " + q5.weight);
		System.out.println("isErgonomic: " + q5.isErgonomic);
		System.out.println("countryOfOrigin: " + q5.countryOfOrigin);
		System.out.println("warrantyMonths: " + q5.warrantyMonths);
		System.out.println("packagingType: " + q5.packagingType);
		System.out.println("cableLength: " + q5.cableLength);
		System.out.println("hasRGB: " + q5.hasRGB);
		System.out.println("feature1: " + q5.feature1);
		System.out.println("feature2: " + q5.feature2);
		System.out.println("feature3: " + q5.feature3);
		System.out.println("hasBluetooth: " + q5.hasBluetooth);
		System.out.println("isRechargeable: " + q5.isRechargeable);
		System.out.println("rating: " + q5.rating);


		QuantumMouse q6 = new QuantumMouse();
		q6.productId = 106;
		q6.brandName = "Sample6";
		q6.connectivityType = "Sample6";
		q6.color = "Sample6";
		q6.dpi = 16.0;
		q6.price = 16.0;
		q6.isWireless = true;
		q6.isAvailable = true;
		q6.manufacturingDate = "Sample6";
		q6.expiryDate = "Sample6";
		q6.sensorType = "Sample6";
		q6.material = "Sample6";
		q6.weight = 16.0;
		q6.isErgonomic = true;
		q6.countryOfOrigin = "Sample6";
		q6.warrantyMonths = 106;
		q6.packagingType = "Sample6";
		q6.cableLength = 16.0;
		q6.hasRGB = true;
		q6.feature1 = "Sample6";
		q6.feature2 = "Sample6";
		q6.feature3 = "Sample6";
		q6.hasBluetooth = true;
		q6.isRechargeable = true;
		q6.rating = 106;

		System.out.println("----- QuantumMouse 6 -----");
		System.out.println("productId: " + q6.productId);
		System.out.println("brandName: " + q6.brandName);
		System.out.println("connectivityType: " + q6.connectivityType);
		System.out.println("color: " + q6.color);
		System.out.println("dpi: " + q6.dpi);
		System.out.println("price: " + q6.price);
		System.out.println("isWireless: " + q6.isWireless);
		System.out.println("isAvailable: " + q6.isAvailable);
		System.out.println("manufacturingDate: " + q6.manufacturingDate);
		System.out.println("expiryDate: " + q6.expiryDate);
		System.out.println("sensorType: " + q6.sensorType);
		System.out.println("material: " + q6.material);
		System.out.println("weight: " + q6.weight);
		System.out.println("isErgonomic: " + q6.isErgonomic);
		System.out.println("countryOfOrigin: " + q6.countryOfOrigin);
		System.out.println("warrantyMonths: " + q6.warrantyMonths);
		System.out.println("packagingType: " + q6.packagingType);
		System.out.println("cableLength: " + q6.cableLength);
		System.out.println("hasRGB: " + q6.hasRGB);
		System.out.println("feature1: " + q6.feature1);
		System.out.println("feature2: " + q6.feature2);
		System.out.println("feature3: " + q6.feature3);
		System.out.println("hasBluetooth: " + q6.hasBluetooth);
		System.out.println("isRechargeable: " + q6.isRechargeable);
		System.out.println("rating: " + q6.rating);


		QuantumMouse q7 = new QuantumMouse();
		q7.productId = 107;
		q7.brandName = "Sample7";
		q7.connectivityType = "Sample7";
		q7.color = "Sample7";
		q7.dpi = 17.0;
		q7.price = 17.0;
		q7.isWireless = false;
		q7.isAvailable = false;
		q7.manufacturingDate = "Sample7";
		q7.expiryDate = "Sample7";
		q7.sensorType = "Sample7";
		q7.material = "Sample7";
		q7.weight = 17.0;
		q7.isErgonomic = false;
		q7.countryOfOrigin = "Sample7";
		q7.warrantyMonths = 107;
		q7.packagingType = "Sample7";
		q7.cableLength = 17.0;
		q7.hasRGB = false;
		q7.feature1 = "Sample7";
		q7.feature2 = "Sample7";
		q7.feature3 = "Sample7";
		q7.hasBluetooth = false;
		q7.isRechargeable = false;
		q7.rating = 107;

		System.out.println("----- QuantumMouse 7 -----");
		System.out.println("productId: " + q7.productId);
		System.out.println("brandName: " + q7.brandName);
		System.out.println("connectivityType: " + q7.connectivityType);
		System.out.println("color: " + q7.color);
		System.out.println("dpi: " + q7.dpi);
		System.out.println("price: " + q7.price);
		System.out.println("isWireless: " + q7.isWireless);
		System.out.println("isAvailable: " + q7.isAvailable);
		System.out.println("manufacturingDate: " + q7.manufacturingDate);
		System.out.println("expiryDate: " + q7.expiryDate);
		System.out.println("sensorType: " + q7.sensorType);
		System.out.println("material: " + q7.material);
		System.out.println("weight: " + q7.weight);
		System.out.println("isErgonomic: " + q7.isErgonomic);
		System.out.println("countryOfOrigin: " + q7.countryOfOrigin);
		System.out.println("warrantyMonths: " + q7.warrantyMonths);
		System.out.println("packagingType: " + q7.packagingType);
		System.out.println("cableLength: " + q7.cableLength);
		System.out.println("hasRGB: " + q7.hasRGB);
		System.out.println("feature1: " + q7.feature1);
		System.out.println("feature2: " + q7.feature2);
		System.out.println("feature3: " + q7.feature3);
		System.out.println("hasBluetooth: " + q7.hasBluetooth);
		System.out.println("isRechargeable: " + q7.isRechargeable);
		System.out.println("rating: " + q7.rating);


		QuantumMouse q8 = new QuantumMouse();
		q8.productId = 108;
		q8.brandName = "Sample8";
		q8.connectivityType = "Sample8";
		q8.color = "Sample8";
		q8.dpi = 18.0;
		q8.price = 18.0;
		q8.isWireless = true;
		q8.isAvailable = true;
		q8.manufacturingDate = "Sample8";
		q8.expiryDate = "Sample8";
		q8.sensorType = "Sample8";
		q8.material = "Sample8";
		q8.weight = 18.0;
		q8.isErgonomic = true;
		q8.countryOfOrigin = "Sample8";
		q8.warrantyMonths = 108;
		q8.packagingType = "Sample8";
		q8.cableLength = 18.0;
		q8.hasRGB = true;
		q8.feature1 = "Sample8";
		q8.feature2 = "Sample8";
		q8.feature3 = "Sample8";
		q8.hasBluetooth = true;
		q8.isRechargeable = true;
		q8.rating = 108;

		System.out.println("----- QuantumMouse 8 -----");
		System.out.println("productId: " + q8.productId);
		System.out.println("brandName: " + q8.brandName);
		System.out.println("connectivityType: " + q8.connectivityType);
		System.out.println("color: " + q8.color);
		System.out.println("dpi: " + q8.dpi);
		System.out.println("price: " + q8.price);
		System.out.println("isWireless: " + q8.isWireless);
		System.out.println("isAvailable: " + q8.isAvailable);
		System.out.println("manufacturingDate: " + q8.manufacturingDate);
		System.out.println("expiryDate: " + q8.expiryDate);
		System.out.println("sensorType: " + q8.sensorType);
		System.out.println("material: " + q8.material);
		System.out.println("weight: " + q8.weight);
		System.out.println("isErgonomic: " + q8.isErgonomic);
		System.out.println("countryOfOrigin: " + q8.countryOfOrigin);
		System.out.println("warrantyMonths: " + q8.warrantyMonths);
		System.out.println("packagingType: " + q8.packagingType);
		System.out.println("cableLength: " + q8.cableLength);
		System.out.println("hasRGB: " + q8.hasRGB);
		System.out.println("feature1: " + q8.feature1);
		System.out.println("feature2: " + q8.feature2);
		System.out.println("feature3: " + q8.feature3);
		System.out.println("hasBluetooth: " + q8.hasBluetooth);
		System.out.println("isRechargeable: " + q8.isRechargeable);
		System.out.println("rating: " + q8.rating);


		QuantumMouse q9 = new QuantumMouse();
		q9.productId = 109;
		q9.brandName = "Sample9";
		q9.connectivityType = "Sample9";
		q9.color = "Sample9";
		q9.dpi = 19.0;
		q9.price = 19.0;
		q9.isWireless = false;
		q9.isAvailable = false;
		q9.manufacturingDate = "Sample9";
		q9.expiryDate = "Sample9";
		q9.sensorType = "Sample9";
		q9.material = "Sample9";
		q9.weight = 19.0;
		q9.isErgonomic = false;
		q9.countryOfOrigin = "Sample9";
		q9.warrantyMonths = 109;
		q9.packagingType = "Sample9";
		q9.cableLength = 19.0;
		q9.hasRGB = false;
		q9.feature1 = "Sample9";
		q9.feature2 = "Sample9";
		q9.feature3 = "Sample9";
		q9.hasBluetooth = false;
		q9.isRechargeable = false;
		q9.rating = 109;

		System.out.println("----- QuantumMouse 9 -----");
		System.out.println("productId: " + q9.productId);
		System.out.println("brandName: " + q9.brandName);
		System.out.println("connectivityType: " + q9.connectivityType);
		System.out.println("color: " + q9.color);
		System.out.println("dpi: " + q9.dpi);
		System.out.println("price: " + q9.price);
		System.out.println("isWireless: " + q9.isWireless);
		System.out.println("isAvailable: " + q9.isAvailable);
		System.out.println("manufacturingDate: " + q9.manufacturingDate);
		System.out.println("expiryDate: " + q9.expiryDate);
		System.out.println("sensorType: " + q9.sensorType);
		System.out.println("material: " + q9.material);
		System.out.println("weight: " + q9.weight);
		System.out.println("isErgonomic: " + q9.isErgonomic);
		System.out.println("countryOfOrigin: " + q9.countryOfOrigin);
		System.out.println("warrantyMonths: " + q9.warrantyMonths);
		System.out.println("packagingType: " + q9.packagingType);
		System.out.println("cableLength: " + q9.cableLength);
		System.out.println("hasRGB: " + q9.hasRGB);
		System.out.println("feature1: " + q9.feature1);
		System.out.println("feature2: " + q9.feature2);
		System.out.println("feature3: " + q9.feature3);
		System.out.println("hasBluetooth: " + q9.hasBluetooth);
		System.out.println("isRechargeable: " + q9.isRechargeable);
		System.out.println("rating: " + q9.rating);


		QuantumMouse q10 = new QuantumMouse();
		q10.productId = 110;
		q10.brandName = "Sample10";
		q10.connectivityType = "Sample10";
		q10.color = "Sample10";
		q10.dpi = 20.0;
		q10.price = 20.0;
		q10.isWireless = true;
		q10.isAvailable = true;
		q10.manufacturingDate = "Sample10";
		q10.expiryDate = "Sample10";
		q10.sensorType = "Sample10";
		q10.material = "Sample10";
		q10.weight = 20.0;
		q10.isErgonomic = true;
		q10.countryOfOrigin = "Sample10";
		q10.warrantyMonths = 110;
		q10.packagingType = "Sample10";
		q10.cableLength = 20.0;
		q10.hasRGB = true;
		q10.feature1 = "Sample10";
		q10.feature2 = "Sample10";
		q10.feature3 = "Sample10";
		q10.hasBluetooth = true;
		q10.isRechargeable = true;
		q10.rating = 110;

		System.out.println("----- QuantumMouse 10 -----");
		System.out.println("productId: " + q10.productId);
		System.out.println("brandName: " + q10.brandName);
		System.out.println("connectivityType: " + q10.connectivityType);
		System.out.println("color: " + q10.color);
		System.out.println("dpi: " + q10.dpi);
		System.out.println("price: " + q10.price);
		System.out.println("isWireless: " + q10.isWireless);
		System.out.println("isAvailable: " + q10.isAvailable);
		System.out.println("manufacturingDate: " + q10.manufacturingDate);
		System.out.println("expiryDate: " + q10.expiryDate);
		System.out.println("sensorType: " + q10.sensorType);
		System.out.println("material: " + q10.material);
		System.out.println("weight: " + q10.weight);
		System.out.println("isErgonomic: " + q10.isErgonomic);
		System.out.println("countryOfOrigin: " + q10.countryOfOrigin);
		System.out.println("warrantyMonths: " + q10.warrantyMonths);
		System.out.println("packagingType: " + q10.packagingType);
		System.out.println("cableLength: " + q10.cableLength);
		System.out.println("hasRGB: " + q10.hasRGB);
		System.out.println("feature1: " + q10.feature1);
		System.out.println("feature2: " + q10.feature2);
		System.out.println("feature3: " + q10.feature3);
		System.out.println("hasBluetooth: " + q10.hasBluetooth);
		System.out.println("isRechargeable: " + q10.isRechargeable);
		System.out.println("rating: " + q10.rating);


		QuantumMouse q11 = new QuantumMouse();
		q11.productId = 111;
		q11.brandName = "Sample11";
		q11.connectivityType = "Sample11";
		q11.color = "Sample11";
		q11.dpi = 21.0;
		q11.price = 21.0;
		q11.isWireless = false;
		q11.isAvailable = false;
		q11.manufacturingDate = "Sample11";
		q11.expiryDate = "Sample11";
		q11.sensorType = "Sample11";
		q11.material = "Sample11";
		q11.weight = 21.0;
		q11.isErgonomic = false;
		q11.countryOfOrigin = "Sample11";
		q11.warrantyMonths = 111;
		q11.packagingType = "Sample11";
		q11.cableLength = 21.0;
		q11.hasRGB = false;
		q11.feature1 = "Sample11";
		q11.feature2 = "Sample11";
		q11.feature3 = "Sample11";
		q11.hasBluetooth = false;
		q11.isRechargeable = false;
		q11.rating = 111;

		System.out.println("----- QuantumMouse 11 -----");
		System.out.println("productId: " + q11.productId);
		System.out.println("brandName: " + q11.brandName);
		System.out.println("connectivityType: " + q11.connectivityType);
		System.out.println("color: " + q11.color);
		System.out.println("dpi: " + q11.dpi);
		System.out.println("price: " + q11.price);
		System.out.println("isWireless: " + q11.isWireless);
		System.out.println("isAvailable: " + q11.isAvailable);
		System.out.println("manufacturingDate: " + q11.manufacturingDate);
		System.out.println("expiryDate: " + q11.expiryDate);
		System.out.println("sensorType: " + q11.sensorType);
		System.out.println("material: " + q11.material);
		System.out.println("weight: " + q11.weight);
		System.out.println("isErgonomic: " + q11.isErgonomic);
		System.out.println("countryOfOrigin: " + q11.countryOfOrigin);
		System.out.println("warrantyMonths: " + q11.warrantyMonths);
		System.out.println("packagingType: " + q11.packagingType);
		System.out.println("cableLength: " + q11.cableLength);
		System.out.println("hasRGB: " + q11.hasRGB);
		System.out.println("feature1: " + q11.feature1);
		System.out.println("feature2: " + q11.feature2);
		System.out.println("feature3: " + q11.feature3);
		System.out.println("hasBluetooth: " + q11.hasBluetooth);
		System.out.println("isRechargeable: " + q11.isRechargeable);
		System.out.println("rating: " + q11.rating);


		QuantumMouse q12 = new QuantumMouse();
		q12.productId = 112;
		q12.brandName = "Sample12";
		q12.connectivityType = "Sample12";
		q12.color = "Sample12";
		q12.dpi = 22.0;
		q12.price = 22.0;
		q12.isWireless = true;
		q12.isAvailable = true;
		q12.manufacturingDate = "Sample12";
		q12.expiryDate = "Sample12";
		q12.sensorType = "Sample12";
		q12.material = "Sample12";
		q12.weight = 22.0;
		q12.isErgonomic = true;
		q12.countryOfOrigin = "Sample12";
		q12.warrantyMonths = 112;
		q12.packagingType = "Sample12";
		q12.cableLength = 22.0;
		q12.hasRGB = true;
		q12.feature1 = "Sample12";
		q12.feature2 = "Sample12";
		q12.feature3 = "Sample12";
		q12.hasBluetooth = true;
		q12.isRechargeable = true;
		q12.rating = 112;

		System.out.println("----- QuantumMouse 12 -----");
		System.out.println("productId: " + q12.productId);
		System.out.println("brandName: " + q12.brandName);
		System.out.println("connectivityType: " + q12.connectivityType);
		System.out.println("color: " + q12.color);
		System.out.println("dpi: " + q12.dpi);
		System.out.println("price: " + q12.price);
		System.out.println("isWireless: " + q12.isWireless);
		System.out.println("isAvailable: " + q12.isAvailable);
		System.out.println("manufacturingDate: " + q12.manufacturingDate);
		System.out.println("expiryDate: " + q12.expiryDate);
		System.out.println("sensorType: " + q12.sensorType);
		System.out.println("material: " + q12.material);
		System.out.println("weight: " + q12.weight);
		System.out.println("isErgonomic: " + q12.isErgonomic);
		System.out.println("countryOfOrigin: " + q12.countryOfOrigin);
		System.out.println("warrantyMonths: " + q12.warrantyMonths);
		System.out.println("packagingType: " + q12.packagingType);
		System.out.println("cableLength: " + q12.cableLength);
		System.out.println("hasRGB: " + q12.hasRGB);
		System.out.println("feature1: " + q12.feature1);
		System.out.println("feature2: " + q12.feature2);
		System.out.println("feature3: " + q12.feature3);
		System.out.println("hasBluetooth: " + q12.hasBluetooth);
		System.out.println("isRechargeable: " + q12.isRechargeable);
		System.out.println("rating: " + q12.rating);


		QuantumMouse q13 = new QuantumMouse();
		q13.productId = 113;
		q13.brandName = "Sample13";
		q13.connectivityType = "Sample13";
		q13.color = "Sample13";
		q13.dpi = 23.0;
		q13.price = 23.0;
		q13.isWireless = false;
		q13.isAvailable = false;
		q13.manufacturingDate = "Sample13";
		q13.expiryDate = "Sample13";
		q13.sensorType = "Sample13";
		q13.material = "Sample13";
		q13.weight = 23.0;
		q13.isErgonomic = false;
		q13.countryOfOrigin = "Sample13";
		q13.warrantyMonths = 113;
		q13.packagingType = "Sample13";
		q13.cableLength = 23.0;
		q13.hasRGB = false;
		q13.feature1 = "Sample13";
		q13.feature2 = "Sample13";
		q13.feature3 = "Sample13";
		q13.hasBluetooth = false;
		q13.isRechargeable = false;
		q13.rating = 113;

		System.out.println("----- QuantumMouse 13 -----");
		System.out.println("productId: " + q13.productId);
		System.out.println("brandName: " + q13.brandName);
		System.out.println("connectivityType: " + q13.connectivityType);
		System.out.println("color: " + q13.color);
		System.out.println("dpi: " + q13.dpi);
		System.out.println("price: " + q13.price);
		System.out.println("isWireless: " + q13.isWireless);
		System.out.println("isAvailable: " + q13.isAvailable);
		System.out.println("manufacturingDate: " + q13.manufacturingDate);
		System.out.println("expiryDate: " + q13.expiryDate);
		System.out.println("sensorType: " + q13.sensorType);
		System.out.println("material: " + q13.material);
		System.out.println("weight: " + q13.weight);
		System.out.println("isErgonomic: " + q13.isErgonomic);
		System.out.println("countryOfOrigin: " + q13.countryOfOrigin);
		System.out.println("warrantyMonths: " + q13.warrantyMonths);
		System.out.println("packagingType: " + q13.packagingType);
		System.out.println("cableLength: " + q13.cableLength);
		System.out.println("hasRGB: " + q13.hasRGB);
		System.out.println("feature1: " + q13.feature1);
		System.out.println("feature2: " + q13.feature2);
		System.out.println("feature3: " + q13.feature3);
		System.out.println("hasBluetooth: " + q13.hasBluetooth);
		System.out.println("isRechargeable: " + q13.isRechargeable);
		System.out.println("rating: " + q13.rating);


		QuantumMouse q14 = new QuantumMouse();
		q14.productId = 114;
		q14.brandName = "Sample14";
		q14.connectivityType = "Sample14";
		q14.color = "Sample14";
		q14.dpi = 24.0;
		q14.price = 24.0;
		q14.isWireless = true;
		q14.isAvailable = true;
		q14.manufacturingDate = "Sample14";
		q14.expiryDate = "Sample14";
		q14.sensorType = "Sample14";
		q14.material = "Sample14";
		q14.weight = 24.0;
		q14.isErgonomic = true;
		q14.countryOfOrigin = "Sample14";
		q14.warrantyMonths = 114;
		q14.packagingType = "Sample14";
		q14.cableLength = 24.0;
		q14.hasRGB = true;
		q14.feature1 = "Sample14";
		q14.feature2 = "Sample14";
		q14.feature3 = "Sample14";
		q14.hasBluetooth = true;
		q14.isRechargeable = true;
		q14.rating = 114;

		System.out.println("----- QuantumMouse 14 -----");
		System.out.println("productId: " + q14.productId);
		System.out.println("brandName: " + q14.brandName);
		System.out.println("connectivityType: " + q14.connectivityType);
		System.out.println("color: " + q14.color);
		System.out.println("dpi: " + q14.dpi);
		System.out.println("price: " + q14.price);
		System.out.println("isWireless: " + q14.isWireless);
		System.out.println("isAvailable: " + q14.isAvailable);
		System.out.println("manufacturingDate: " + q14.manufacturingDate);
		System.out.println("expiryDate: " + q14.expiryDate);
		System.out.println("sensorType: " + q14.sensorType);
		System.out.println("material: " + q14.material);
		System.out.println("weight: " + q14.weight);
		System.out.println("isErgonomic: " + q14.isErgonomic);
		System.out.println("countryOfOrigin: " + q14.countryOfOrigin);
		System.out.println("warrantyMonths: " + q14.warrantyMonths);
		System.out.println("packagingType: " + q14.packagingType);
		System.out.println("cableLength: " + q14.cableLength);
		System.out.println("hasRGB: " + q14.hasRGB);
		System.out.println("feature1: " + q14.feature1);
		System.out.println("feature2: " + q14.feature2);
		System.out.println("feature3: " + q14.feature3);
		System.out.println("hasBluetooth: " + q14.hasBluetooth);
		System.out.println("isRechargeable: " + q14.isRechargeable);
		System.out.println("rating: " + q14.rating);


		QuantumMouse q15 = new QuantumMouse();
		q15.productId = 115;
		q15.brandName = "Sample15";
		q15.connectivityType = "Sample15";
		q15.color = "Sample15";
		q15.dpi = 25.0;
		q15.price = 25.0;
		q15.isWireless = false;
		q15.isAvailable = false;
		q15.manufacturingDate = "Sample15";
		q15.expiryDate = "Sample15";
		q15.sensorType = "Sample15";
		q15.material = "Sample15";
		q15.weight = 25.0;
		q15.isErgonomic = false;
		q15.countryOfOrigin = "Sample15";
		q15.warrantyMonths = 115;
		q15.packagingType = "Sample15";
		q15.cableLength = 25.0;
		q15.hasRGB = false;
		q15.feature1 = "Sample15";
		q15.feature2 = "Sample15";
		q15.feature3 = "Sample15";
		q15.hasBluetooth = false;
		q15.isRechargeable = false;
		q15.rating = 115;

		System.out.println("----- QuantumMouse 15 -----");
		System.out.println("productId: " + q15.productId);
		System.out.println("brandName: " + q15.brandName);
		System.out.println("connectivityType: " + q15.connectivityType);
		System.out.println("color: " + q15.color);
		System.out.println("dpi: " + q15.dpi);
		System.out.println("price: " + q15.price);
		System.out.println("isWireless: " + q15.isWireless);
		System.out.println("isAvailable: " + q15.isAvailable);
		System.out.println("manufacturingDate: " + q15.manufacturingDate);
		System.out.println("expiryDate: " + q15.expiryDate);
		System.out.println("sensorType: " + q15.sensorType);
		System.out.println("material: " + q15.material);
		System.out.println("weight: " + q15.weight);
		System.out.println("isErgonomic: " + q15.isErgonomic);
		System.out.println("countryOfOrigin: " + q15.countryOfOrigin);
		System.out.println("warrantyMonths: " + q15.warrantyMonths);
		System.out.println("packagingType: " + q15.packagingType);
		System.out.println("cableLength: " + q15.cableLength);
		System.out.println("hasRGB: " + q15.hasRGB);
		System.out.println("feature1: " + q15.feature1);
		System.out.println("feature2: " + q15.feature2);
		System.out.println("feature3: " + q15.feature3);
		System.out.println("hasBluetooth: " + q15.hasBluetooth);
		System.out.println("isRechargeable: " + q15.isRechargeable);
		System.out.println("rating: " + q15.rating);


		QuantumMouse q16 = new QuantumMouse();
		q16.productId = 116;
		q16.brandName = "Sample16";
		q16.connectivityType = "Sample16";
		q16.color = "Sample16";
		q16.dpi = 26.0;
		q16.price = 26.0;
		q16.isWireless = true;
		q16.isAvailable = true;
		q16.manufacturingDate = "Sample16";
		q16.expiryDate = "Sample16";
		q16.sensorType = "Sample16";
		q16.material = "Sample16";
		q16.weight = 26.0;
		q16.isErgonomic = true;
		q16.countryOfOrigin = "Sample16";
		q16.warrantyMonths = 116;
		q16.packagingType = "Sample16";
		q16.cableLength = 26.0;
		q16.hasRGB = true;
		q16.feature1 = "Sample16";
		q16.feature2 = "Sample16";
		q16.feature3 = "Sample16";
		q16.hasBluetooth = true;
		q16.isRechargeable = true;
		q16.rating = 116;

		System.out.println("----- QuantumMouse 16 -----");
		System.out.println("productId: " + q16.productId);
		System.out.println("brandName: " + q16.brandName);
		System.out.println("connectivityType: " + q16.connectivityType);
		System.out.println("color: " + q16.color);
		System.out.println("dpi: " + q16.dpi);
		System.out.println("price: " + q16.price);
		System.out.println("isWireless: " + q16.isWireless);
		System.out.println("isAvailable: " + q16.isAvailable);
		System.out.println("manufacturingDate: " + q16.manufacturingDate);
		System.out.println("expiryDate: " + q16.expiryDate);
		System.out.println("sensorType: " + q16.sensorType);
		System.out.println("material: " + q16.material);
		System.out.println("weight: " + q16.weight);
		System.out.println("isErgonomic: " + q16.isErgonomic);
		System.out.println("countryOfOrigin: " + q16.countryOfOrigin);
		System.out.println("warrantyMonths: " + q16.warrantyMonths);
		System.out.println("packagingType: " + q16.packagingType);
		System.out.println("cableLength: " + q16.cableLength);
		System.out.println("hasRGB: " + q16.hasRGB);
		System.out.println("feature1: " + q16.feature1);
		System.out.println("feature2: " + q16.feature2);
		System.out.println("feature3: " + q16.feature3);
		System.out.println("hasBluetooth: " + q16.hasBluetooth);
		System.out.println("isRechargeable: " + q16.isRechargeable);
		System.out.println("rating: " + q16.rating);


		QuantumMouse q17 = new QuantumMouse();
		q17.productId = 117;
		q17.brandName = "Sample17";
		q17.connectivityType = "Sample17";
		q17.color = "Sample17";
		q17.dpi = 27.0;
		q17.price = 27.0;
		q17.isWireless = false;
		q17.isAvailable = false;
		q17.manufacturingDate = "Sample17";
		q17.expiryDate = "Sample17";
		q17.sensorType = "Sample17";
		q17.material = "Sample17";
		q17.weight = 27.0;
		q17.isErgonomic = false;
		q17.countryOfOrigin = "Sample17";
		q17.warrantyMonths = 117;
		q17.packagingType = "Sample17";
		q17.cableLength = 27.0;
		q17.hasRGB = false;
		q17.feature1 = "Sample17";
		q17.feature2 = "Sample17";
		q17.feature3 = "Sample17";
		q17.hasBluetooth = false;
		q17.isRechargeable = false;
		q17.rating = 117;

		System.out.println("----- QuantumMouse 17 -----");
		System.out.println("productId: " + q17.productId);
		System.out.println("brandName: " + q17.brandName);
		System.out.println("connectivityType: " + q17.connectivityType);
		System.out.println("color: " + q17.color);
		System.out.println("dpi: " + q17.dpi);
		System.out.println("price: " + q17.price);
		System.out.println("isWireless: " + q17.isWireless);
		System.out.println("isAvailable: " + q17.isAvailable);
		System.out.println("manufacturingDate: " + q17.manufacturingDate);
		System.out.println("expiryDate: " + q17.expiryDate);
		System.out.println("sensorType: " + q17.sensorType);
		System.out.println("material: " + q17.material);
		System.out.println("weight: " + q17.weight);
		System.out.println("isErgonomic: " + q17.isErgonomic);
		System.out.println("countryOfOrigin: " + q17.countryOfOrigin);
		System.out.println("warrantyMonths: " + q17.warrantyMonths);
		System.out.println("packagingType: " + q17.packagingType);
		System.out.println("cableLength: " + q17.cableLength);
		System.out.println("hasRGB: " + q17.hasRGB);
		System.out.println("feature1: " + q17.feature1);
		System.out.println("feature2: " + q17.feature2);
		System.out.println("feature3: " + q17.feature3);
		System.out.println("hasBluetooth: " + q17.hasBluetooth);
		System.out.println("isRechargeable: " + q17.isRechargeable);
		System.out.println("rating: " + q17.rating);


		QuantumMouse q18 = new QuantumMouse();
		q18.productId = 118;
		q18.brandName = "Sample18";
		q18.connectivityType = "Sample18";
		q18.color = "Sample18";
		q18.dpi = 28.0;
		q18.price = 28.0;
		q18.isWireless = true;
		q18.isAvailable = true;
		q18.manufacturingDate = "Sample18";
		q18.expiryDate = "Sample18";
		q18.sensorType = "Sample18";
		q18.material = "Sample18";
		q18.weight = 28.0;
		q18.isErgonomic = true;
		q18.countryOfOrigin = "Sample18";
		q18.warrantyMonths = 118;
		q18.packagingType = "Sample18";
		q18.cableLength = 28.0;
		q18.hasRGB = true;
		q18.feature1 = "Sample18";
		q18.feature2 = "Sample18";
		q18.feature3 = "Sample18";
		q18.hasBluetooth = true;
		q18.isRechargeable = true;
		q18.rating = 118;

		System.out.println("----- QuantumMouse 18 -----");
		System.out.println("productId: " + q18.productId);
		System.out.println("brandName: " + q18.brandName);
		System.out.println("connectivityType: " + q18.connectivityType);
		System.out.println("color: " + q18.color);
		System.out.println("dpi: " + q18.dpi);
		System.out.println("price: " + q18.price);
		System.out.println("isWireless: " + q18.isWireless);
		System.out.println("isAvailable: " + q18.isAvailable);
		System.out.println("manufacturingDate: " + q18.manufacturingDate);
		System.out.println("expiryDate: " + q18.expiryDate);
		System.out.println("sensorType: " + q18.sensorType);
		System.out.println("material: " + q18.material);
		System.out.println("weight: " + q18.weight);
		System.out.println("isErgonomic: " + q18.isErgonomic);
		System.out.println("countryOfOrigin: " + q18.countryOfOrigin);
		System.out.println("warrantyMonths: " + q18.warrantyMonths);
		System.out.println("packagingType: " + q18.packagingType);
		System.out.println("cableLength: " + q18.cableLength);
		System.out.println("hasRGB: " + q18.hasRGB);
		System.out.println("feature1: " + q18.feature1);
		System.out.println("feature2: " + q18.feature2);
		System.out.println("feature3: " + q18.feature3);
		System.out.println("hasBluetooth: " + q18.hasBluetooth);
		System.out.println("isRechargeable: " + q18.isRechargeable);
		System.out.println("rating: " + q18.rating);


		QuantumMouse q19 = new QuantumMouse();
		q19.productId = 119;
		q19.brandName = "Sample19";
		q19.connectivityType = "Sample19";
		q19.color = "Sample19";
		q19.dpi = 29.0;
		q19.price = 29.0;
		q19.isWireless = false;
		q19.isAvailable = false;
		q19.manufacturingDate = "Sample19";
		q19.expiryDate = "Sample19";
		q19.sensorType = "Sample19";
		q19.material = "Sample19";
		q19.weight = 29.0;
		q19.isErgonomic = false;
		q19.countryOfOrigin = "Sample19";
		q19.warrantyMonths = 119;
		q19.packagingType = "Sample19";
		q19.cableLength = 29.0;
		q19.hasRGB = false;
		q19.feature1 = "Sample19";
		q19.feature2 = "Sample19";
		q19.feature3 = "Sample19";
		q19.hasBluetooth = false;
		q19.isRechargeable = false;
		q19.rating = 119;

		System.out.println("----- QuantumMouse 19 -----");
		System.out.println("productId: " + q19.productId);
		System.out.println("brandName: " + q19.brandName);
		System.out.println("connectivityType: " + q19.connectivityType);
		System.out.println("color: " + q19.color);
		System.out.println("dpi: " + q19.dpi);
		System.out.println("price: " + q19.price);
		System.out.println("isWireless: " + q19.isWireless);
		System.out.println("isAvailable: " + q19.isAvailable);
		System.out.println("manufacturingDate: " + q19.manufacturingDate);
		System.out.println("expiryDate: " + q19.expiryDate);
		System.out.println("sensorType: " + q19.sensorType);
		System.out.println("material: " + q19.material);
		System.out.println("weight: " + q19.weight);
		System.out.println("isErgonomic: " + q19.isErgonomic);
		System.out.println("countryOfOrigin: " + q19.countryOfOrigin);
		System.out.println("warrantyMonths: " + q19.warrantyMonths);
		System.out.println("packagingType: " + q19.packagingType);
		System.out.println("cableLength: " + q19.cableLength);
		System.out.println("hasRGB: " + q19.hasRGB);
		System.out.println("feature1: " + q19.feature1);
		System.out.println("feature2: " + q19.feature2);
		System.out.println("feature3: " + q19.feature3);
		System.out.println("hasBluetooth: " + q19.hasBluetooth);
		System.out.println("isRechargeable: " + q19.isRechargeable);
		System.out.println("rating: " + q19.rating);


		QuantumMouse q20 = new QuantumMouse();
		q20.productId = 120;
		q20.brandName = "Sample20";
		q20.connectivityType = "Sample20";
		q20.color = "Sample20";
		q20.dpi = 30.0;
		q20.price = 30.0;
		q20.isWireless = true;
		q20.isAvailable = true;
		q20.manufacturingDate = "Sample20";
		q20.expiryDate = "Sample20";
		q20.sensorType = "Sample20";
		q20.material = "Sample20";
		q20.weight = 30.0;
		q20.isErgonomic = true;
		q20.countryOfOrigin = "Sample20";
		q20.warrantyMonths = 120;
		q20.packagingType = "Sample20";
		q20.cableLength = 30.0;
		q20.hasRGB = true;
		q20.feature1 = "Sample20";
		q20.feature2 = "Sample20";
		q20.feature3 = "Sample20";
		q20.hasBluetooth = true;
		q20.isRechargeable = true;
		q20.rating = 120;

		System.out.println("----- QuantumMouse 20 -----");
		System.out.println("productId: " + q20.productId);
		System.out.println("brandName: " + q20.brandName);
		System.out.println("connectivityType: " + q20.connectivityType);
		System.out.println("color: " + q20.color);
		System.out.println("dpi: " + q20.dpi);
		System.out.println("price: " + q20.price);
		System.out.println("isWireless: " + q20.isWireless);
		System.out.println("isAvailable: " + q20.isAvailable);
		System.out.println("manufacturingDate: " + q20.manufacturingDate);
		System.out.println("expiryDate: " + q20.expiryDate);
		System.out.println("sensorType: " + q20.sensorType);
		System.out.println("material: " + q20.material);
		System.out.println("weight: " + q20.weight);
		System.out.println("isErgonomic: " + q20.isErgonomic);
		System.out.println("countryOfOrigin: " + q20.countryOfOrigin);
		System.out.println("warrantyMonths: " + q20.warrantyMonths);
		System.out.println("packagingType: " + q20.packagingType);
		System.out.println("cableLength: " + q20.cableLength);
		System.out.println("hasRGB: " + q20.hasRGB);
		System.out.println("feature1: " + q20.feature1);
		System.out.println("feature2: " + q20.feature2);
		System.out.println("feature3: " + q20.feature3);
		System.out.println("hasBluetooth: " + q20.hasBluetooth);
		System.out.println("isRechargeable: " + q20.isRechargeable);
		System.out.println("rating: " + q20.rating);


		QuantumMouse q21 = new QuantumMouse();
		q21.productId = 121;
		q21.brandName = "Sample21";
		q21.connectivityType = "Sample21";
		q21.color = "Sample21";
		q21.dpi = 31.0;
		q21.price = 31.0;
		q21.isWireless = false;
		q21.isAvailable = false;
		q21.manufacturingDate = "Sample21";
		q21.expiryDate = "Sample21";
		q21.sensorType = "Sample21";
		q21.material = "Sample21";
		q21.weight = 31.0;
		q21.isErgonomic = false;
		q21.countryOfOrigin = "Sample21";
		q21.warrantyMonths = 121;
		q21.packagingType = "Sample21";
		q21.cableLength = 31.0;
		q21.hasRGB = false;
		q21.feature1 = "Sample21";
		q21.feature2 = "Sample21";
		q21.feature3 = "Sample21";
		q21.hasBluetooth = false;
		q21.isRechargeable = false;
		q21.rating = 121;

		System.out.println("----- QuantumMouse 21 -----");
		System.out.println("productId: " + q21.productId);
		System.out.println("brandName: " + q21.brandName);
		System.out.println("connectivityType: " + q21.connectivityType);
		System.out.println("color: " + q21.color);
		System.out.println("dpi: " + q21.dpi);
		System.out.println("price: " + q21.price);
		System.out.println("isWireless: " + q21.isWireless);
		System.out.println("isAvailable: " + q21.isAvailable);
		System.out.println("manufacturingDate: " + q21.manufacturingDate);
		System.out.println("expiryDate: " + q21.expiryDate);
		System.out.println("sensorType: " + q21.sensorType);
		System.out.println("material: " + q21.material);
		System.out.println("weight: " + q21.weight);
		System.out.println("isErgonomic: " + q21.isErgonomic);
		System.out.println("countryOfOrigin: " + q21.countryOfOrigin);
		System.out.println("warrantyMonths: " + q21.warrantyMonths);
		System.out.println("packagingType: " + q21.packagingType);
		System.out.println("cableLength: " + q21.cableLength);
		System.out.println("hasRGB: " + q21.hasRGB);
		System.out.println("feature1: " + q21.feature1);
		System.out.println("feature2: " + q21.feature2);
		System.out.println("feature3: " + q21.feature3);
		System.out.println("hasBluetooth: " + q21.hasBluetooth);
		System.out.println("isRechargeable: " + q21.isRechargeable);
		System.out.println("rating: " + q21.rating);


		QuantumMouse q22 = new QuantumMouse();
		q22.productId = 122;
		q22.brandName = "Sample22";
		q22.connectivityType = "Sample22";
		q22.color = "Sample22";
		q22.dpi = 32.0;
		q22.price = 32.0;
		q22.isWireless = true;
		q22.isAvailable = true;
		q22.manufacturingDate = "Sample22";
		q22.expiryDate = "Sample22";
		q22.sensorType = "Sample22";
		q22.material = "Sample22";
		q22.weight = 32.0;
		q22.isErgonomic = true;
		q22.countryOfOrigin = "Sample22";
		q22.warrantyMonths = 122;
		q22.packagingType = "Sample22";
		q22.cableLength = 32.0;
		q22.hasRGB = true;
		q22.feature1 = "Sample22";
		q22.feature2 = "Sample22";
		q22.feature3 = "Sample22";
		q22.hasBluetooth = true;
		q22.isRechargeable = true;
		q22.rating = 122;

		System.out.println("----- QuantumMouse 22 -----");
		System.out.println("productId: " + q22.productId);
		System.out.println("brandName: " + q22.brandName);
		System.out.println("connectivityType: " + q22.connectivityType);
		System.out.println("color: " + q22.color);
		System.out.println("dpi: " + q22.dpi);
		System.out.println("price: " + q22.price);
		System.out.println("isWireless: " + q22.isWireless);
		System.out.println("isAvailable: " + q22.isAvailable);
		System.out.println("manufacturingDate: " + q22.manufacturingDate);
		System.out.println("expiryDate: " + q22.expiryDate);
		System.out.println("sensorType: " + q22.sensorType);
		System.out.println("material: " + q22.material);
		System.out.println("weight: " + q22.weight);
		System.out.println("isErgonomic: " + q22.isErgonomic);
		System.out.println("countryOfOrigin: " + q22.countryOfOrigin);
		System.out.println("warrantyMonths: " + q22.warrantyMonths);
		System.out.println("packagingType: " + q22.packagingType);
		System.out.println("cableLength: " + q22.cableLength);
		System.out.println("hasRGB: " + q22.hasRGB);
		System.out.println("feature1: " + q22.feature1);
		System.out.println("feature2: " + q22.feature2);
		System.out.println("feature3: " + q22.feature3);
		System.out.println("hasBluetooth: " + q22.hasBluetooth);
		System.out.println("isRechargeable: " + q22.isRechargeable);
		System.out.println("rating: " + q22.rating);


		QuantumMouse q23 = new QuantumMouse();
		q23.productId = 123;
		q23.brandName = "Sample23";
		q23.connectivityType = "Sample23";
		q23.color = "Sample23";
		q23.dpi = 33.0;
		q23.price = 33.0;
		q23.isWireless = false;
		q23.isAvailable = false;
		q23.manufacturingDate = "Sample23";
		q23.expiryDate = "Sample23";
		q23.sensorType = "Sample23";
		q23.material = "Sample23";
		q23.weight = 33.0;
		q23.isErgonomic = false;
		q23.countryOfOrigin = "Sample23";
		q23.warrantyMonths = 123;
		q23.packagingType = "Sample23";
		q23.cableLength = 33.0;
		q23.hasRGB = false;
		q23.feature1 = "Sample23";
		q23.feature2 = "Sample23";
		q23.feature3 = "Sample23";
		q23.hasBluetooth = false;
		q23.isRechargeable = false;
		q23.rating = 123;

		System.out.println("----- QuantumMouse 23 -----");
		System.out.println("productId: " + q23.productId);
		System.out.println("brandName: " + q23.brandName);
		System.out.println("connectivityType: " + q23.connectivityType);
		System.out.println("color: " + q23.color);
		System.out.println("dpi: " + q23.dpi);
		System.out.println("price: " + q23.price);
		System.out.println("isWireless: " + q23.isWireless);
		System.out.println("isAvailable: " + q23.isAvailable);
		System.out.println("manufacturingDate: " + q23.manufacturingDate);
		System.out.println("expiryDate: " + q23.expiryDate);
		System.out.println("sensorType: " + q23.sensorType);
		System.out.println("material: " + q23.material);
		System.out.println("weight: " + q23.weight);
		System.out.println("isErgonomic: " + q23.isErgonomic);
		System.out.println("countryOfOrigin: " + q23.countryOfOrigin);
		System.out.println("warrantyMonths: " + q23.warrantyMonths);
		System.out.println("packagingType: " + q23.packagingType);
		System.out.println("cableLength: " + q23.cableLength);
		System.out.println("hasRGB: " + q23.hasRGB);
		System.out.println("feature1: " + q23.feature1);
		System.out.println("feature2: " + q23.feature2);
		System.out.println("feature3: " + q23.feature3);
		System.out.println("hasBluetooth: " + q23.hasBluetooth);
		System.out.println("isRechargeable: " + q23.isRechargeable);
		System.out.println("rating: " + q23.rating);


		QuantumMouse q24 = new QuantumMouse();
		q24.productId = 124;
		q24.brandName = "Sample24";
		q24.connectivityType = "Sample24";
		q24.color = "Sample24";
		q24.dpi = 34.0;
		q24.price = 34.0;
		q24.isWireless = true;
		q24.isAvailable = true;
		q24.manufacturingDate = "Sample24";
		q24.expiryDate = "Sample24";
		q24.sensorType = "Sample24";
		q24.material = "Sample24";
		q24.weight = 34.0;
		q24.isErgonomic = true;
		q24.countryOfOrigin = "Sample24";
		q24.warrantyMonths = 124;
		q24.packagingType = "Sample24";
		q24.cableLength = 34.0;
		q24.hasRGB = true;
		q24.feature1 = "Sample24";
		q24.feature2 = "Sample24";
		q24.feature3 = "Sample24";
		q24.hasBluetooth = true;
		q24.isRechargeable = true;
		q24.rating = 124;

		System.out.println("----- QuantumMouse 24 -----");
		System.out.println("productId: " + q24.productId);
		System.out.println("brandName: " + q24.brandName);
		System.out.println("connectivityType: " + q24.connectivityType);
		System.out.println("color: " + q24.color);
		System.out.println("dpi: " + q24.dpi);
		System.out.println("price: " + q24.price);
		System.out.println("isWireless: " + q24.isWireless);
		System.out.println("isAvailable: " + q24.isAvailable);
		System.out.println("manufacturingDate: " + q24.manufacturingDate);
		System.out.println("expiryDate: " + q24.expiryDate);
		System.out.println("sensorType: " + q24.sensorType);
		System.out.println("material: " + q24.material);
		System.out.println("weight: " + q24.weight);
		System.out.println("isErgonomic: " + q24.isErgonomic);
		System.out.println("countryOfOrigin: " + q24.countryOfOrigin);
		System.out.println("warrantyMonths: " + q24.warrantyMonths);
		System.out.println("packagingType: " + q24.packagingType);
		System.out.println("cableLength: " + q24.cableLength);
		System.out.println("hasRGB: " + q24.hasRGB);
		System.out.println("feature1: " + q24.feature1);
		System.out.println("feature2: " + q24.feature2);
		System.out.println("feature3: " + q24.feature3);
		System.out.println("hasBluetooth: " + q24.hasBluetooth);
		System.out.println("isRechargeable: " + q24.isRechargeable);
		System.out.println("rating: " + q24.rating);


		QuantumMouse q25 = new QuantumMouse();
		q25.productId = 125;
		q25.brandName = "Sample25";
		q25.connectivityType = "Sample25";
		q25.color = "Sample25";
		q25.dpi = 35.0;
		q25.price = 35.0;
		q25.isWireless = false;
		q25.isAvailable = false;
		q25.manufacturingDate = "Sample25";
		q25.expiryDate = "Sample25";
		q25.sensorType = "Sample25";
		q25.material = "Sample25";
		q25.weight = 35.0;
		q25.isErgonomic = false;
		q25.countryOfOrigin = "Sample25";
		q25.warrantyMonths = 125;
		q25.packagingType = "Sample25";
		q25.cableLength = 35.0;
		q25.hasRGB = false;
		q25.feature1 = "Sample25";
		q25.feature2 = "Sample25";
		q25.feature3 = "Sample25";
		q25.hasBluetooth = false;
		q25.isRechargeable = false;
		q25.rating = 125;

		System.out.println("----- QuantumMouse 25 -----");
		System.out.println("productId: " + q25.productId);
		System.out.println("brandName: " + q25.brandName);
		System.out.println("connectivityType: " + q25.connectivityType);
		System.out.println("color: " + q25.color);
		System.out.println("dpi: " + q25.dpi);
		System.out.println("price: " + q25.price);
		System.out.println("isWireless: " + q25.isWireless);
		System.out.println("isAvailable: " + q25.isAvailable);
		System.out.println("manufacturingDate: " + q25.manufacturingDate);
		System.out.println("expiryDate: " + q25.expiryDate);
		System.out.println("sensorType: " + q25.sensorType);
		System.out.println("material: " + q25.material);
		System.out.println("weight: " + q25.weight);
		System.out.println("isErgonomic: " + q25.isErgonomic);
		System.out.println("countryOfOrigin: " + q25.countryOfOrigin);
		System.out.println("warrantyMonths: " + q25.warrantyMonths);
		System.out.println("packagingType: " + q25.packagingType);
		System.out.println("cableLength: " + q25.cableLength);
		System.out.println("hasRGB: " + q25.hasRGB);
		System.out.println("feature1: " + q25.feature1);
		System.out.println("feature2: " + q25.feature2);
		System.out.println("feature3: " + q25.feature3);
		System.out.println("hasBluetooth: " + q25.hasBluetooth);
		System.out.println("isRechargeable: " + q25.isRechargeable);
		System.out.println("rating: " + q25.rating);


	}
}
