class SolarTorchRunner {
	public static void main(String[] args) {

		SolarTorch s1 = new SolarTorch();
		s1.productId = 101;
		s1.brandName = "Sample1";
		s1.lightType = "Sample1";
		s1.color = "Sample1";
		s1.batteryCapacity = 11.0;
		s1.price = 11.0;
		s1.isSolarPowered = false;
		s1.isAvailable = false;
		s1.manufacturingDate = "Sample1";
		s1.expiryDate = "Sample1";
		s1.usageType = "Sample1";
		s1.material = "Sample1";
		s1.brightnessLevel = 11.0;
		s1.isWaterproof = false;
		s1.countryOfOrigin = "Sample1";
		s1.warrantyMonths = 101;
		s1.packagingType = "Sample1";
		s1.weight = 11.0;
		s1.isShockResistant = false;
		s1.feature1 = "Sample1";
		s1.feature2 = "Sample1";
		s1.feature3 = "Sample1";
		s1.isPortable = false;
		s1.isEnergySaving = false;
		s1.rating = 101;

		System.out.println("----- SolarTorch 1 -----");
		System.out.println("productId: " + s1.productId);
		System.out.println("brandName: " + s1.brandName);
		System.out.println("lightType: " + s1.lightType);
		System.out.println("color: " + s1.color);
		System.out.println("batteryCapacity: " + s1.batteryCapacity);
		System.out.println("price: " + s1.price);
		System.out.println("isSolarPowered: " + s1.isSolarPowered);
		System.out.println("isAvailable: " + s1.isAvailable);
		System.out.println("manufacturingDate: " + s1.manufacturingDate);
		System.out.println("expiryDate: " + s1.expiryDate);
		System.out.println("usageType: " + s1.usageType);
		System.out.println("material: " + s1.material);
		System.out.println("brightnessLevel: " + s1.brightnessLevel);
		System.out.println("isWaterproof: " + s1.isWaterproof);
		System.out.println("countryOfOrigin: " + s1.countryOfOrigin);
		System.out.println("warrantyMonths: " + s1.warrantyMonths);
		System.out.println("packagingType: " + s1.packagingType);
		System.out.println("weight: " + s1.weight);
		System.out.println("isShockResistant: " + s1.isShockResistant);
		System.out.println("feature1: " + s1.feature1);
		System.out.println("feature2: " + s1.feature2);
		System.out.println("feature3: " + s1.feature3);
		System.out.println("isPortable: " + s1.isPortable);
		System.out.println("isEnergySaving: " + s1.isEnergySaving);
		System.out.println("rating: " + s1.rating);


		SolarTorch s2 = new SolarTorch();
		s2.productId = 102;
		s2.brandName = "Sample2";
		s2.lightType = "Sample2";
		s2.color = "Sample2";
		s2.batteryCapacity = 12.0;
		s2.price = 12.0;
		s2.isSolarPowered = true;
		s2.isAvailable = true;
		s2.manufacturingDate = "Sample2";
		s2.expiryDate = "Sample2";
		s2.usageType = "Sample2";
		s2.material = "Sample2";
		s2.brightnessLevel = 12.0;
		s2.isWaterproof = true;
		s2.countryOfOrigin = "Sample2";
		s2.warrantyMonths = 102;
		s2.packagingType = "Sample2";
		s2.weight = 12.0;
		s2.isShockResistant = true;
		s2.feature1 = "Sample2";
		s2.feature2 = "Sample2";
		s2.feature3 = "Sample2";
		s2.isPortable = true;
		s2.isEnergySaving = true;
		s2.rating = 102;

		System.out.println("----- SolarTorch 2 -----");
		System.out.println("productId: " + s2.productId);
		System.out.println("brandName: " + s2.brandName);
		System.out.println("lightType: " + s2.lightType);
		System.out.println("color: " + s2.color);
		System.out.println("batteryCapacity: " + s2.batteryCapacity);
		System.out.println("price: " + s2.price);
		System.out.println("isSolarPowered: " + s2.isSolarPowered);
		System.out.println("isAvailable: " + s2.isAvailable);
		System.out.println("manufacturingDate: " + s2.manufacturingDate);
		System.out.println("expiryDate: " + s2.expiryDate);
		System.out.println("usageType: " + s2.usageType);
		System.out.println("material: " + s2.material);
		System.out.println("brightnessLevel: " + s2.brightnessLevel);
		System.out.println("isWaterproof: " + s2.isWaterproof);
		System.out.println("countryOfOrigin: " + s2.countryOfOrigin);
		System.out.println("warrantyMonths: " + s2.warrantyMonths);
		System.out.println("packagingType: " + s2.packagingType);
		System.out.println("weight: " + s2.weight);
		System.out.println("isShockResistant: " + s2.isShockResistant);
		System.out.println("feature1: " + s2.feature1);
		System.out.println("feature2: " + s2.feature2);
		System.out.println("feature3: " + s2.feature3);
		System.out.println("isPortable: " + s2.isPortable);
		System.out.println("isEnergySaving: " + s2.isEnergySaving);
		System.out.println("rating: " + s2.rating);


		SolarTorch s3 = new SolarTorch();
		s3.productId = 103;
		s3.brandName = "Sample3";
		s3.lightType = "Sample3";
		s3.color = "Sample3";
		s3.batteryCapacity = 13.0;
		s3.price = 13.0;
		s3.isSolarPowered = false;
		s3.isAvailable = false;
		s3.manufacturingDate = "Sample3";
		s3.expiryDate = "Sample3";
		s3.usageType = "Sample3";
		s3.material = "Sample3";
		s3.brightnessLevel = 13.0;
		s3.isWaterproof = false;
		s3.countryOfOrigin = "Sample3";
		s3.warrantyMonths = 103;
		s3.packagingType = "Sample3";
		s3.weight = 13.0;
		s3.isShockResistant = false;
		s3.feature1 = "Sample3";
		s3.feature2 = "Sample3";
		s3.feature3 = "Sample3";
		s3.isPortable = false;
		s3.isEnergySaving = false;
		s3.rating = 103;

		System.out.println("----- SolarTorch 3 -----");
		System.out.println("productId: " + s3.productId);
		System.out.println("brandName: " + s3.brandName);
		System.out.println("lightType: " + s3.lightType);
		System.out.println("color: " + s3.color);
		System.out.println("batteryCapacity: " + s3.batteryCapacity);
		System.out.println("price: " + s3.price);
		System.out.println("isSolarPowered: " + s3.isSolarPowered);
		System.out.println("isAvailable: " + s3.isAvailable);
		System.out.println("manufacturingDate: " + s3.manufacturingDate);
		System.out.println("expiryDate: " + s3.expiryDate);
		System.out.println("usageType: " + s3.usageType);
		System.out.println("material: " + s3.material);
		System.out.println("brightnessLevel: " + s3.brightnessLevel);
		System.out.println("isWaterproof: " + s3.isWaterproof);
		System.out.println("countryOfOrigin: " + s3.countryOfOrigin);
		System.out.println("warrantyMonths: " + s3.warrantyMonths);
		System.out.println("packagingType: " + s3.packagingType);
		System.out.println("weight: " + s3.weight);
		System.out.println("isShockResistant: " + s3.isShockResistant);
		System.out.println("feature1: " + s3.feature1);
		System.out.println("feature2: " + s3.feature2);
		System.out.println("feature3: " + s3.feature3);
		System.out.println("isPortable: " + s3.isPortable);
		System.out.println("isEnergySaving: " + s3.isEnergySaving);
		System.out.println("rating: " + s3.rating);


		SolarTorch s4 = new SolarTorch();
		s4.productId = 104;
		s4.brandName = "Sample4";
		s4.lightType = "Sample4";
		s4.color = "Sample4";
		s4.batteryCapacity = 14.0;
		s4.price = 14.0;
		s4.isSolarPowered = true;
		s4.isAvailable = true;
		s4.manufacturingDate = "Sample4";
		s4.expiryDate = "Sample4";
		s4.usageType = "Sample4";
		s4.material = "Sample4";
		s4.brightnessLevel = 14.0;
		s4.isWaterproof = true;
		s4.countryOfOrigin = "Sample4";
		s4.warrantyMonths = 104;
		s4.packagingType = "Sample4";
		s4.weight = 14.0;
		s4.isShockResistant = true;
		s4.feature1 = "Sample4";
		s4.feature2 = "Sample4";
		s4.feature3 = "Sample4";
		s4.isPortable = true;
		s4.isEnergySaving = true;
		s4.rating = 104;

		System.out.println("----- SolarTorch 4 -----");
		System.out.println("productId: " + s4.productId);
		System.out.println("brandName: " + s4.brandName);
		System.out.println("lightType: " + s4.lightType);
		System.out.println("color: " + s4.color);
		System.out.println("batteryCapacity: " + s4.batteryCapacity);
		System.out.println("price: " + s4.price);
		System.out.println("isSolarPowered: " + s4.isSolarPowered);
		System.out.println("isAvailable: " + s4.isAvailable);
		System.out.println("manufacturingDate: " + s4.manufacturingDate);
		System.out.println("expiryDate: " + s4.expiryDate);
		System.out.println("usageType: " + s4.usageType);
		System.out.println("material: " + s4.material);
		System.out.println("brightnessLevel: " + s4.brightnessLevel);
		System.out.println("isWaterproof: " + s4.isWaterproof);
		System.out.println("countryOfOrigin: " + s4.countryOfOrigin);
		System.out.println("warrantyMonths: " + s4.warrantyMonths);
		System.out.println("packagingType: " + s4.packagingType);
		System.out.println("weight: " + s4.weight);
		System.out.println("isShockResistant: " + s4.isShockResistant);
		System.out.println("feature1: " + s4.feature1);
		System.out.println("feature2: " + s4.feature2);
		System.out.println("feature3: " + s4.feature3);
		System.out.println("isPortable: " + s4.isPortable);
		System.out.println("isEnergySaving: " + s4.isEnergySaving);
		System.out.println("rating: " + s4.rating);


		SolarTorch s5 = new SolarTorch();
		s5.productId = 105;
		s5.brandName = "Sample5";
		s5.lightType = "Sample5";
		s5.color = "Sample5";
		s5.batteryCapacity = 15.0;
		s5.price = 15.0;
		s5.isSolarPowered = false;
		s5.isAvailable = false;
		s5.manufacturingDate = "Sample5";
		s5.expiryDate = "Sample5";
		s5.usageType = "Sample5";
		s5.material = "Sample5";
		s5.brightnessLevel = 15.0;
		s5.isWaterproof = false;
		s5.countryOfOrigin = "Sample5";
		s5.warrantyMonths = 105;
		s5.packagingType = "Sample5";
		s5.weight = 15.0;
		s5.isShockResistant = false;
		s5.feature1 = "Sample5";
		s5.feature2 = "Sample5";
		s5.feature3 = "Sample5";
		s5.isPortable = false;
		s5.isEnergySaving = false;
		s5.rating = 105;

		System.out.println("----- SolarTorch 5 -----");
		System.out.println("productId: " + s5.productId);
		System.out.println("brandName: " + s5.brandName);
		System.out.println("lightType: " + s5.lightType);
		System.out.println("color: " + s5.color);
		System.out.println("batteryCapacity: " + s5.batteryCapacity);
		System.out.println("price: " + s5.price);
		System.out.println("isSolarPowered: " + s5.isSolarPowered);
		System.out.println("isAvailable: " + s5.isAvailable);
		System.out.println("manufacturingDate: " + s5.manufacturingDate);
		System.out.println("expiryDate: " + s5.expiryDate);
		System.out.println("usageType: " + s5.usageType);
		System.out.println("material: " + s5.material);
		System.out.println("brightnessLevel: " + s5.brightnessLevel);
		System.out.println("isWaterproof: " + s5.isWaterproof);
		System.out.println("countryOfOrigin: " + s5.countryOfOrigin);
		System.out.println("warrantyMonths: " + s5.warrantyMonths);
		System.out.println("packagingType: " + s5.packagingType);
		System.out.println("weight: " + s5.weight);
		System.out.println("isShockResistant: " + s5.isShockResistant);
		System.out.println("feature1: " + s5.feature1);
		System.out.println("feature2: " + s5.feature2);
		System.out.println("feature3: " + s5.feature3);
		System.out.println("isPortable: " + s5.isPortable);
		System.out.println("isEnergySaving: " + s5.isEnergySaving);
		System.out.println("rating: " + s5.rating);


		SolarTorch s6 = new SolarTorch();
		s6.productId = 106;
		s6.brandName = "Sample6";
		s6.lightType = "Sample6";
		s6.color = "Sample6";
		s6.batteryCapacity = 16.0;
		s6.price = 16.0;
		s6.isSolarPowered = true;
		s6.isAvailable = true;
		s6.manufacturingDate = "Sample6";
		s6.expiryDate = "Sample6";
		s6.usageType = "Sample6";
		s6.material = "Sample6";
		s6.brightnessLevel = 16.0;
		s6.isWaterproof = true;
		s6.countryOfOrigin = "Sample6";
		s6.warrantyMonths = 106;
		s6.packagingType = "Sample6";
		s6.weight = 16.0;
		s6.isShockResistant = true;
		s6.feature1 = "Sample6";
		s6.feature2 = "Sample6";
		s6.feature3 = "Sample6";
		s6.isPortable = true;
		s6.isEnergySaving = true;
		s6.rating = 106;

		System.out.println("----- SolarTorch 6 -----");
		System.out.println("productId: " + s6.productId);
		System.out.println("brandName: " + s6.brandName);
		System.out.println("lightType: " + s6.lightType);
		System.out.println("color: " + s6.color);
		System.out.println("batteryCapacity: " + s6.batteryCapacity);
		System.out.println("price: " + s6.price);
		System.out.println("isSolarPowered: " + s6.isSolarPowered);
		System.out.println("isAvailable: " + s6.isAvailable);
		System.out.println("manufacturingDate: " + s6.manufacturingDate);
		System.out.println("expiryDate: " + s6.expiryDate);
		System.out.println("usageType: " + s6.usageType);
		System.out.println("material: " + s6.material);
		System.out.println("brightnessLevel: " + s6.brightnessLevel);
		System.out.println("isWaterproof: " + s6.isWaterproof);
		System.out.println("countryOfOrigin: " + s6.countryOfOrigin);
		System.out.println("warrantyMonths: " + s6.warrantyMonths);
		System.out.println("packagingType: " + s6.packagingType);
		System.out.println("weight: " + s6.weight);
		System.out.println("isShockResistant: " + s6.isShockResistant);
		System.out.println("feature1: " + s6.feature1);
		System.out.println("feature2: " + s6.feature2);
		System.out.println("feature3: " + s6.feature3);
		System.out.println("isPortable: " + s6.isPortable);
		System.out.println("isEnergySaving: " + s6.isEnergySaving);
		System.out.println("rating: " + s6.rating);


		SolarTorch s7 = new SolarTorch();
		s7.productId = 107;
		s7.brandName = "Sample7";
		s7.lightType = "Sample7";
		s7.color = "Sample7";
		s7.batteryCapacity = 17.0;
		s7.price = 17.0;
		s7.isSolarPowered = false;
		s7.isAvailable = false;
		s7.manufacturingDate = "Sample7";
		s7.expiryDate = "Sample7";
		s7.usageType = "Sample7";
		s7.material = "Sample7";
		s7.brightnessLevel = 17.0;
		s7.isWaterproof = false;
		s7.countryOfOrigin = "Sample7";
		s7.warrantyMonths = 107;
		s7.packagingType = "Sample7";
		s7.weight = 17.0;
		s7.isShockResistant = false;
		s7.feature1 = "Sample7";
		s7.feature2 = "Sample7";
		s7.feature3 = "Sample7";
		s7.isPortable = false;
		s7.isEnergySaving = false;
		s7.rating = 107;

		System.out.println("----- SolarTorch 7 -----");
		System.out.println("productId: " + s7.productId);
		System.out.println("brandName: " + s7.brandName);
		System.out.println("lightType: " + s7.lightType);
		System.out.println("color: " + s7.color);
		System.out.println("batteryCapacity: " + s7.batteryCapacity);
		System.out.println("price: " + s7.price);
		System.out.println("isSolarPowered: " + s7.isSolarPowered);
		System.out.println("isAvailable: " + s7.isAvailable);
		System.out.println("manufacturingDate: " + s7.manufacturingDate);
		System.out.println("expiryDate: " + s7.expiryDate);
		System.out.println("usageType: " + s7.usageType);
		System.out.println("material: " + s7.material);
		System.out.println("brightnessLevel: " + s7.brightnessLevel);
		System.out.println("isWaterproof: " + s7.isWaterproof);
		System.out.println("countryOfOrigin: " + s7.countryOfOrigin);
		System.out.println("warrantyMonths: " + s7.warrantyMonths);
		System.out.println("packagingType: " + s7.packagingType);
		System.out.println("weight: " + s7.weight);
		System.out.println("isShockResistant: " + s7.isShockResistant);
		System.out.println("feature1: " + s7.feature1);
		System.out.println("feature2: " + s7.feature2);
		System.out.println("feature3: " + s7.feature3);
		System.out.println("isPortable: " + s7.isPortable);
		System.out.println("isEnergySaving: " + s7.isEnergySaving);
		System.out.println("rating: " + s7.rating);


		SolarTorch s8 = new SolarTorch();
		s8.productId = 108;
		s8.brandName = "Sample8";
		s8.lightType = "Sample8";
		s8.color = "Sample8";
		s8.batteryCapacity = 18.0;
		s8.price = 18.0;
		s8.isSolarPowered = true;
		s8.isAvailable = true;
		s8.manufacturingDate = "Sample8";
		s8.expiryDate = "Sample8";
		s8.usageType = "Sample8";
		s8.material = "Sample8";
		s8.brightnessLevel = 18.0;
		s8.isWaterproof = true;
		s8.countryOfOrigin = "Sample8";
		s8.warrantyMonths = 108;
		s8.packagingType = "Sample8";
		s8.weight = 18.0;
		s8.isShockResistant = true;
		s8.feature1 = "Sample8";
		s8.feature2 = "Sample8";
		s8.feature3 = "Sample8";
		s8.isPortable = true;
		s8.isEnergySaving = true;
		s8.rating = 108;

		System.out.println("----- SolarTorch 8 -----");
		System.out.println("productId: " + s8.productId);
		System.out.println("brandName: " + s8.brandName);
		System.out.println("lightType: " + s8.lightType);
		System.out.println("color: " + s8.color);
		System.out.println("batteryCapacity: " + s8.batteryCapacity);
		System.out.println("price: " + s8.price);
		System.out.println("isSolarPowered: " + s8.isSolarPowered);
		System.out.println("isAvailable: " + s8.isAvailable);
		System.out.println("manufacturingDate: " + s8.manufacturingDate);
		System.out.println("expiryDate: " + s8.expiryDate);
		System.out.println("usageType: " + s8.usageType);
		System.out.println("material: " + s8.material);
		System.out.println("brightnessLevel: " + s8.brightnessLevel);
		System.out.println("isWaterproof: " + s8.isWaterproof);
		System.out.println("countryOfOrigin: " + s8.countryOfOrigin);
		System.out.println("warrantyMonths: " + s8.warrantyMonths);
		System.out.println("packagingType: " + s8.packagingType);
		System.out.println("weight: " + s8.weight);
		System.out.println("isShockResistant: " + s8.isShockResistant);
		System.out.println("feature1: " + s8.feature1);
		System.out.println("feature2: " + s8.feature2);
		System.out.println("feature3: " + s8.feature3);
		System.out.println("isPortable: " + s8.isPortable);
		System.out.println("isEnergySaving: " + s8.isEnergySaving);
		System.out.println("rating: " + s8.rating);


		SolarTorch s9 = new SolarTorch();
		s9.productId = 109;
		s9.brandName = "Sample9";
		s9.lightType = "Sample9";
		s9.color = "Sample9";
		s9.batteryCapacity = 19.0;
		s9.price = 19.0;
		s9.isSolarPowered = false;
		s9.isAvailable = false;
		s9.manufacturingDate = "Sample9";
		s9.expiryDate = "Sample9";
		s9.usageType = "Sample9";
		s9.material = "Sample9";
		s9.brightnessLevel = 19.0;
		s9.isWaterproof = false;
		s9.countryOfOrigin = "Sample9";
		s9.warrantyMonths = 109;
		s9.packagingType = "Sample9";
		s9.weight = 19.0;
		s9.isShockResistant = false;
		s9.feature1 = "Sample9";
		s9.feature2 = "Sample9";
		s9.feature3 = "Sample9";
		s9.isPortable = false;
		s9.isEnergySaving = false;
		s9.rating = 109;

		System.out.println("----- SolarTorch 9 -----");
		System.out.println("productId: " + s9.productId);
		System.out.println("brandName: " + s9.brandName);
		System.out.println("lightType: " + s9.lightType);
		System.out.println("color: " + s9.color);
		System.out.println("batteryCapacity: " + s9.batteryCapacity);
		System.out.println("price: " + s9.price);
		System.out.println("isSolarPowered: " + s9.isSolarPowered);
		System.out.println("isAvailable: " + s9.isAvailable);
		System.out.println("manufacturingDate: " + s9.manufacturingDate);
		System.out.println("expiryDate: " + s9.expiryDate);
		System.out.println("usageType: " + s9.usageType);
		System.out.println("material: " + s9.material);
		System.out.println("brightnessLevel: " + s9.brightnessLevel);
		System.out.println("isWaterproof: " + s9.isWaterproof);
		System.out.println("countryOfOrigin: " + s9.countryOfOrigin);
		System.out.println("warrantyMonths: " + s9.warrantyMonths);
		System.out.println("packagingType: " + s9.packagingType);
		System.out.println("weight: " + s9.weight);
		System.out.println("isShockResistant: " + s9.isShockResistant);
		System.out.println("feature1: " + s9.feature1);
		System.out.println("feature2: " + s9.feature2);
		System.out.println("feature3: " + s9.feature3);
		System.out.println("isPortable: " + s9.isPortable);
		System.out.println("isEnergySaving: " + s9.isEnergySaving);
		System.out.println("rating: " + s9.rating);


		SolarTorch s10 = new SolarTorch();
		s10.productId = 110;
		s10.brandName = "Sample10";
		s10.lightType = "Sample10";
		s10.color = "Sample10";
		s10.batteryCapacity = 20.0;
		s10.price = 20.0;
		s10.isSolarPowered = true;
		s10.isAvailable = true;
		s10.manufacturingDate = "Sample10";
		s10.expiryDate = "Sample10";
		s10.usageType = "Sample10";
		s10.material = "Sample10";
		s10.brightnessLevel = 20.0;
		s10.isWaterproof = true;
		s10.countryOfOrigin = "Sample10";
		s10.warrantyMonths = 110;
		s10.packagingType = "Sample10";
		s10.weight = 20.0;
		s10.isShockResistant = true;
		s10.feature1 = "Sample10";
		s10.feature2 = "Sample10";
		s10.feature3 = "Sample10";
		s10.isPortable = true;
		s10.isEnergySaving = true;
		s10.rating = 110;

		System.out.println("----- SolarTorch 10 -----");
		System.out.println("productId: " + s10.productId);
		System.out.println("brandName: " + s10.brandName);
		System.out.println("lightType: " + s10.lightType);
		System.out.println("color: " + s10.color);
		System.out.println("batteryCapacity: " + s10.batteryCapacity);
		System.out.println("price: " + s10.price);
		System.out.println("isSolarPowered: " + s10.isSolarPowered);
		System.out.println("isAvailable: " + s10.isAvailable);
		System.out.println("manufacturingDate: " + s10.manufacturingDate);
		System.out.println("expiryDate: " + s10.expiryDate);
		System.out.println("usageType: " + s10.usageType);
		System.out.println("material: " + s10.material);
		System.out.println("brightnessLevel: " + s10.brightnessLevel);
		System.out.println("isWaterproof: " + s10.isWaterproof);
		System.out.println("countryOfOrigin: " + s10.countryOfOrigin);
		System.out.println("warrantyMonths: " + s10.warrantyMonths);
		System.out.println("packagingType: " + s10.packagingType);
		System.out.println("weight: " + s10.weight);
		System.out.println("isShockResistant: " + s10.isShockResistant);
		System.out.println("feature1: " + s10.feature1);
		System.out.println("feature2: " + s10.feature2);
		System.out.println("feature3: " + s10.feature3);
		System.out.println("isPortable: " + s10.isPortable);
		System.out.println("isEnergySaving: " + s10.isEnergySaving);
		System.out.println("rating: " + s10.rating);


		SolarTorch s11 = new SolarTorch();
		s11.productId = 111;
		s11.brandName = "Sample11";
		s11.lightType = "Sample11";
		s11.color = "Sample11";
		s11.batteryCapacity = 21.0;
		s11.price = 21.0;
		s11.isSolarPowered = false;
		s11.isAvailable = false;
		s11.manufacturingDate = "Sample11";
		s11.expiryDate = "Sample11";
		s11.usageType = "Sample11";
		s11.material = "Sample11";
		s11.brightnessLevel = 21.0;
		s11.isWaterproof = false;
		s11.countryOfOrigin = "Sample11";
		s11.warrantyMonths = 111;
		s11.packagingType = "Sample11";
		s11.weight = 21.0;
		s11.isShockResistant = false;
		s11.feature1 = "Sample11";
		s11.feature2 = "Sample11";
		s11.feature3 = "Sample11";
		s11.isPortable = false;
		s11.isEnergySaving = false;
		s11.rating = 111;

		System.out.println("----- SolarTorch 11 -----");
		System.out.println("productId: " + s11.productId);
		System.out.println("brandName: " + s11.brandName);
		System.out.println("lightType: " + s11.lightType);
		System.out.println("color: " + s11.color);
		System.out.println("batteryCapacity: " + s11.batteryCapacity);
		System.out.println("price: " + s11.price);
		System.out.println("isSolarPowered: " + s11.isSolarPowered);
		System.out.println("isAvailable: " + s11.isAvailable);
		System.out.println("manufacturingDate: " + s11.manufacturingDate);
		System.out.println("expiryDate: " + s11.expiryDate);
		System.out.println("usageType: " + s11.usageType);
		System.out.println("material: " + s11.material);
		System.out.println("brightnessLevel: " + s11.brightnessLevel);
		System.out.println("isWaterproof: " + s11.isWaterproof);
		System.out.println("countryOfOrigin: " + s11.countryOfOrigin);
		System.out.println("warrantyMonths: " + s11.warrantyMonths);
		System.out.println("packagingType: " + s11.packagingType);
		System.out.println("weight: " + s11.weight);
		System.out.println("isShockResistant: " + s11.isShockResistant);
		System.out.println("feature1: " + s11.feature1);
		System.out.println("feature2: " + s11.feature2);
		System.out.println("feature3: " + s11.feature3);
		System.out.println("isPortable: " + s11.isPortable);
		System.out.println("isEnergySaving: " + s11.isEnergySaving);
		System.out.println("rating: " + s11.rating);


		SolarTorch s12 = new SolarTorch();
		s12.productId = 112;
		s12.brandName = "Sample12";
		s12.lightType = "Sample12";
		s12.color = "Sample12";
		s12.batteryCapacity = 22.0;
		s12.price = 22.0;
		s12.isSolarPowered = true;
		s12.isAvailable = true;
		s12.manufacturingDate = "Sample12";
		s12.expiryDate = "Sample12";
		s12.usageType = "Sample12";
		s12.material = "Sample12";
		s12.brightnessLevel = 22.0;
		s12.isWaterproof = true;
		s12.countryOfOrigin = "Sample12";
		s12.warrantyMonths = 112;
		s12.packagingType = "Sample12";
		s12.weight = 22.0;
		s12.isShockResistant = true;
		s12.feature1 = "Sample12";
		s12.feature2 = "Sample12";
		s12.feature3 = "Sample12";
		s12.isPortable = true;
		s12.isEnergySaving = true;
		s12.rating = 112;

		System.out.println("----- SolarTorch 12 -----");
		System.out.println("productId: " + s12.productId);
		System.out.println("brandName: " + s12.brandName);
		System.out.println("lightType: " + s12.lightType);
		System.out.println("color: " + s12.color);
		System.out.println("batteryCapacity: " + s12.batteryCapacity);
		System.out.println("price: " + s12.price);
		System.out.println("isSolarPowered: " + s12.isSolarPowered);
		System.out.println("isAvailable: " + s12.isAvailable);
		System.out.println("manufacturingDate: " + s12.manufacturingDate);
		System.out.println("expiryDate: " + s12.expiryDate);
		System.out.println("usageType: " + s12.usageType);
		System.out.println("material: " + s12.material);
		System.out.println("brightnessLevel: " + s12.brightnessLevel);
		System.out.println("isWaterproof: " + s12.isWaterproof);
		System.out.println("countryOfOrigin: " + s12.countryOfOrigin);
		System.out.println("warrantyMonths: " + s12.warrantyMonths);
		System.out.println("packagingType: " + s12.packagingType);
		System.out.println("weight: " + s12.weight);
		System.out.println("isShockResistant: " + s12.isShockResistant);
		System.out.println("feature1: " + s12.feature1);
		System.out.println("feature2: " + s12.feature2);
		System.out.println("feature3: " + s12.feature3);
		System.out.println("isPortable: " + s12.isPortable);
		System.out.println("isEnergySaving: " + s12.isEnergySaving);
		System.out.println("rating: " + s12.rating);


		SolarTorch s13 = new SolarTorch();
		s13.productId = 113;
		s13.brandName = "Sample13";
		s13.lightType = "Sample13";
		s13.color = "Sample13";
		s13.batteryCapacity = 23.0;
		s13.price = 23.0;
		s13.isSolarPowered = false;
		s13.isAvailable = false;
		s13.manufacturingDate = "Sample13";
		s13.expiryDate = "Sample13";
		s13.usageType = "Sample13";
		s13.material = "Sample13";
		s13.brightnessLevel = 23.0;
		s13.isWaterproof = false;
		s13.countryOfOrigin = "Sample13";
		s13.warrantyMonths = 113;
		s13.packagingType = "Sample13";
		s13.weight = 23.0;
		s13.isShockResistant = false;
		s13.feature1 = "Sample13";
		s13.feature2 = "Sample13";
		s13.feature3 = "Sample13";
		s13.isPortable = false;
		s13.isEnergySaving = false;
		s13.rating = 113;

		System.out.println("----- SolarTorch 13 -----");
		System.out.println("productId: " + s13.productId);
		System.out.println("brandName: " + s13.brandName);
		System.out.println("lightType: " + s13.lightType);
		System.out.println("color: " + s13.color);
		System.out.println("batteryCapacity: " + s13.batteryCapacity);
		System.out.println("price: " + s13.price);
		System.out.println("isSolarPowered: " + s13.isSolarPowered);
		System.out.println("isAvailable: " + s13.isAvailable);
		System.out.println("manufacturingDate: " + s13.manufacturingDate);
		System.out.println("expiryDate: " + s13.expiryDate);
		System.out.println("usageType: " + s13.usageType);
		System.out.println("material: " + s13.material);
		System.out.println("brightnessLevel: " + s13.brightnessLevel);
		System.out.println("isWaterproof: " + s13.isWaterproof);
		System.out.println("countryOfOrigin: " + s13.countryOfOrigin);
		System.out.println("warrantyMonths: " + s13.warrantyMonths);
		System.out.println("packagingType: " + s13.packagingType);
		System.out.println("weight: " + s13.weight);
		System.out.println("isShockResistant: " + s13.isShockResistant);
		System.out.println("feature1: " + s13.feature1);
		System.out.println("feature2: " + s13.feature2);
		System.out.println("feature3: " + s13.feature3);
		System.out.println("isPortable: " + s13.isPortable);
		System.out.println("isEnergySaving: " + s13.isEnergySaving);
		System.out.println("rating: " + s13.rating);


		SolarTorch s14 = new SolarTorch();
		s14.productId = 114;
		s14.brandName = "Sample14";
		s14.lightType = "Sample14";
		s14.color = "Sample14";
		s14.batteryCapacity = 24.0;
		s14.price = 24.0;
		s14.isSolarPowered = true;
		s14.isAvailable = true;
		s14.manufacturingDate = "Sample14";
		s14.expiryDate = "Sample14";
		s14.usageType = "Sample14";
		s14.material = "Sample14";
		s14.brightnessLevel = 24.0;
		s14.isWaterproof = true;
		s14.countryOfOrigin = "Sample14";
		s14.warrantyMonths = 114;
		s14.packagingType = "Sample14";
		s14.weight = 24.0;
		s14.isShockResistant = true;
		s14.feature1 = "Sample14";
		s14.feature2 = "Sample14";
		s14.feature3 = "Sample14";
		s14.isPortable = true;
		s14.isEnergySaving = true;
		s14.rating = 114;

		System.out.println("----- SolarTorch 14 -----");
		System.out.println("productId: " + s14.productId);
		System.out.println("brandName: " + s14.brandName);
		System.out.println("lightType: " + s14.lightType);
		System.out.println("color: " + s14.color);
		System.out.println("batteryCapacity: " + s14.batteryCapacity);
		System.out.println("price: " + s14.price);
		System.out.println("isSolarPowered: " + s14.isSolarPowered);
		System.out.println("isAvailable: " + s14.isAvailable);
		System.out.println("manufacturingDate: " + s14.manufacturingDate);
		System.out.println("expiryDate: " + s14.expiryDate);
		System.out.println("usageType: " + s14.usageType);
		System.out.println("material: " + s14.material);
		System.out.println("brightnessLevel: " + s14.brightnessLevel);
		System.out.println("isWaterproof: " + s14.isWaterproof);
		System.out.println("countryOfOrigin: " + s14.countryOfOrigin);
		System.out.println("warrantyMonths: " + s14.warrantyMonths);
		System.out.println("packagingType: " + s14.packagingType);
		System.out.println("weight: " + s14.weight);
		System.out.println("isShockResistant: " + s14.isShockResistant);
		System.out.println("feature1: " + s14.feature1);
		System.out.println("feature2: " + s14.feature2);
		System.out.println("feature3: " + s14.feature3);
		System.out.println("isPortable: " + s14.isPortable);
		System.out.println("isEnergySaving: " + s14.isEnergySaving);
		System.out.println("rating: " + s14.rating);


		SolarTorch s15 = new SolarTorch();
		s15.productId = 115;
		s15.brandName = "Sample15";
		s15.lightType = "Sample15";
		s15.color = "Sample15";
		s15.batteryCapacity = 25.0;
		s15.price = 25.0;
		s15.isSolarPowered = false;
		s15.isAvailable = false;
		s15.manufacturingDate = "Sample15";
		s15.expiryDate = "Sample15";
		s15.usageType = "Sample15";
		s15.material = "Sample15";
		s15.brightnessLevel = 25.0;
		s15.isWaterproof = false;
		s15.countryOfOrigin = "Sample15";
		s15.warrantyMonths = 115;
		s15.packagingType = "Sample15";
		s15.weight = 25.0;
		s15.isShockResistant = false;
		s15.feature1 = "Sample15";
		s15.feature2 = "Sample15";
		s15.feature3 = "Sample15";
		s15.isPortable = false;
		s15.isEnergySaving = false;
		s15.rating = 115;

		System.out.println("----- SolarTorch 15 -----");
		System.out.println("productId: " + s15.productId);
		System.out.println("brandName: " + s15.brandName);
		System.out.println("lightType: " + s15.lightType);
		System.out.println("color: " + s15.color);
		System.out.println("batteryCapacity: " + s15.batteryCapacity);
		System.out.println("price: " + s15.price);
		System.out.println("isSolarPowered: " + s15.isSolarPowered);
		System.out.println("isAvailable: " + s15.isAvailable);
		System.out.println("manufacturingDate: " + s15.manufacturingDate);
		System.out.println("expiryDate: " + s15.expiryDate);
		System.out.println("usageType: " + s15.usageType);
		System.out.println("material: " + s15.material);
		System.out.println("brightnessLevel: " + s15.brightnessLevel);
		System.out.println("isWaterproof: " + s15.isWaterproof);
		System.out.println("countryOfOrigin: " + s15.countryOfOrigin);
		System.out.println("warrantyMonths: " + s15.warrantyMonths);
		System.out.println("packagingType: " + s15.packagingType);
		System.out.println("weight: " + s15.weight);
		System.out.println("isShockResistant: " + s15.isShockResistant);
		System.out.println("feature1: " + s15.feature1);
		System.out.println("feature2: " + s15.feature2);
		System.out.println("feature3: " + s15.feature3);
		System.out.println("isPortable: " + s15.isPortable);
		System.out.println("isEnergySaving: " + s15.isEnergySaving);
		System.out.println("rating: " + s15.rating);


		SolarTorch s16 = new SolarTorch();
		s16.productId = 116;
		s16.brandName = "Sample16";
		s16.lightType = "Sample16";
		s16.color = "Sample16";
		s16.batteryCapacity = 26.0;
		s16.price = 26.0;
		s16.isSolarPowered = true;
		s16.isAvailable = true;
		s16.manufacturingDate = "Sample16";
		s16.expiryDate = "Sample16";
		s16.usageType = "Sample16";
		s16.material = "Sample16";
		s16.brightnessLevel = 26.0;
		s16.isWaterproof = true;
		s16.countryOfOrigin = "Sample16";
		s16.warrantyMonths = 116;
		s16.packagingType = "Sample16";
		s16.weight = 26.0;
		s16.isShockResistant = true;
		s16.feature1 = "Sample16";
		s16.feature2 = "Sample16";
		s16.feature3 = "Sample16";
		s16.isPortable = true;
		s16.isEnergySaving = true;
		s16.rating = 116;

		System.out.println("----- SolarTorch 16 -----");
		System.out.println("productId: " + s16.productId);
		System.out.println("brandName: " + s16.brandName);
		System.out.println("lightType: " + s16.lightType);
		System.out.println("color: " + s16.color);
		System.out.println("batteryCapacity: " + s16.batteryCapacity);
		System.out.println("price: " + s16.price);
		System.out.println("isSolarPowered: " + s16.isSolarPowered);
		System.out.println("isAvailable: " + s16.isAvailable);
		System.out.println("manufacturingDate: " + s16.manufacturingDate);
		System.out.println("expiryDate: " + s16.expiryDate);
		System.out.println("usageType: " + s16.usageType);
		System.out.println("material: " + s16.material);
		System.out.println("brightnessLevel: " + s16.brightnessLevel);
		System.out.println("isWaterproof: " + s16.isWaterproof);
		System.out.println("countryOfOrigin: " + s16.countryOfOrigin);
		System.out.println("warrantyMonths: " + s16.warrantyMonths);
		System.out.println("packagingType: " + s16.packagingType);
		System.out.println("weight: " + s16.weight);
		System.out.println("isShockResistant: " + s16.isShockResistant);
		System.out.println("feature1: " + s16.feature1);
		System.out.println("feature2: " + s16.feature2);
		System.out.println("feature3: " + s16.feature3);
		System.out.println("isPortable: " + s16.isPortable);
		System.out.println("isEnergySaving: " + s16.isEnergySaving);
		System.out.println("rating: " + s16.rating);


		SolarTorch s17 = new SolarTorch();
		s17.productId = 117;
		s17.brandName = "Sample17";
		s17.lightType = "Sample17";
		s17.color = "Sample17";
		s17.batteryCapacity = 27.0;
		s17.price = 27.0;
		s17.isSolarPowered = false;
		s17.isAvailable = false;
		s17.manufacturingDate = "Sample17";
		s17.expiryDate = "Sample17";
		s17.usageType = "Sample17";
		s17.material = "Sample17";
		s17.brightnessLevel = 27.0;
		s17.isWaterproof = false;
		s17.countryOfOrigin = "Sample17";
		s17.warrantyMonths = 117;
		s17.packagingType = "Sample17";
		s17.weight = 27.0;
		s17.isShockResistant = false;
		s17.feature1 = "Sample17";
		s17.feature2 = "Sample17";
		s17.feature3 = "Sample17";
		s17.isPortable = false;
		s17.isEnergySaving = false;
		s17.rating = 117;

		System.out.println("----- SolarTorch 17 -----");
		System.out.println("productId: " + s17.productId);
		System.out.println("brandName: " + s17.brandName);
		System.out.println("lightType: " + s17.lightType);
		System.out.println("color: " + s17.color);
		System.out.println("batteryCapacity: " + s17.batteryCapacity);
		System.out.println("price: " + s17.price);
		System.out.println("isSolarPowered: " + s17.isSolarPowered);
		System.out.println("isAvailable: " + s17.isAvailable);
		System.out.println("manufacturingDate: " + s17.manufacturingDate);
		System.out.println("expiryDate: " + s17.expiryDate);
		System.out.println("usageType: " + s17.usageType);
		System.out.println("material: " + s17.material);
		System.out.println("brightnessLevel: " + s17.brightnessLevel);
		System.out.println("isWaterproof: " + s17.isWaterproof);
		System.out.println("countryOfOrigin: " + s17.countryOfOrigin);
		System.out.println("warrantyMonths: " + s17.warrantyMonths);
		System.out.println("packagingType: " + s17.packagingType);
		System.out.println("weight: " + s17.weight);
		System.out.println("isShockResistant: " + s17.isShockResistant);
		System.out.println("feature1: " + s17.feature1);
		System.out.println("feature2: " + s17.feature2);
		System.out.println("feature3: " + s17.feature3);
		System.out.println("isPortable: " + s17.isPortable);
		System.out.println("isEnergySaving: " + s17.isEnergySaving);
		System.out.println("rating: " + s17.rating);


		SolarTorch s18 = new SolarTorch();
		s18.productId = 118;
		s18.brandName = "Sample18";
		s18.lightType = "Sample18";
		s18.color = "Sample18";
		s18.batteryCapacity = 28.0;
		s18.price = 28.0;
		s18.isSolarPowered = true;
		s18.isAvailable = true;
		s18.manufacturingDate = "Sample18";
		s18.expiryDate = "Sample18";
		s18.usageType = "Sample18";
		s18.material = "Sample18";
		s18.brightnessLevel = 28.0;
		s18.isWaterproof = true;
		s18.countryOfOrigin = "Sample18";
		s18.warrantyMonths = 118;
		s18.packagingType = "Sample18";
		s18.weight = 28.0;
		s18.isShockResistant = true;
		s18.feature1 = "Sample18";
		s18.feature2 = "Sample18";
		s18.feature3 = "Sample18";
		s18.isPortable = true;
		s18.isEnergySaving = true;
		s18.rating = 118;

		System.out.println("----- SolarTorch 18 -----");
		System.out.println("productId: " + s18.productId);
		System.out.println("brandName: " + s18.brandName);
		System.out.println("lightType: " + s18.lightType);
		System.out.println("color: " + s18.color);
		System.out.println("batteryCapacity: " + s18.batteryCapacity);
		System.out.println("price: " + s18.price);
		System.out.println("isSolarPowered: " + s18.isSolarPowered);
		System.out.println("isAvailable: " + s18.isAvailable);
		System.out.println("manufacturingDate: " + s18.manufacturingDate);
		System.out.println("expiryDate: " + s18.expiryDate);
		System.out.println("usageType: " + s18.usageType);
		System.out.println("material: " + s18.material);
		System.out.println("brightnessLevel: " + s18.brightnessLevel);
		System.out.println("isWaterproof: " + s18.isWaterproof);
		System.out.println("countryOfOrigin: " + s18.countryOfOrigin);
		System.out.println("warrantyMonths: " + s18.warrantyMonths);
		System.out.println("packagingType: " + s18.packagingType);
		System.out.println("weight: " + s18.weight);
		System.out.println("isShockResistant: " + s18.isShockResistant);
		System.out.println("feature1: " + s18.feature1);
		System.out.println("feature2: " + s18.feature2);
		System.out.println("feature3: " + s18.feature3);
		System.out.println("isPortable: " + s18.isPortable);
		System.out.println("isEnergySaving: " + s18.isEnergySaving);
		System.out.println("rating: " + s18.rating);


		SolarTorch s19 = new SolarTorch();
		s19.productId = 119;
		s19.brandName = "Sample19";
		s19.lightType = "Sample19";
		s19.color = "Sample19";
		s19.batteryCapacity = 29.0;
		s19.price = 29.0;
		s19.isSolarPowered = false;
		s19.isAvailable = false;
		s19.manufacturingDate = "Sample19";
		s19.expiryDate = "Sample19";
		s19.usageType = "Sample19";
		s19.material = "Sample19";
		s19.brightnessLevel = 29.0;
		s19.isWaterproof = false;
		s19.countryOfOrigin = "Sample19";
		s19.warrantyMonths = 119;
		s19.packagingType = "Sample19";
		s19.weight = 29.0;
		s19.isShockResistant = false;
		s19.feature1 = "Sample19";
		s19.feature2 = "Sample19";
		s19.feature3 = "Sample19";
		s19.isPortable = false;
		s19.isEnergySaving = false;
		s19.rating = 119;

		System.out.println("----- SolarTorch 19 -----");
		System.out.println("productId: " + s19.productId);
		System.out.println("brandName: " + s19.brandName);
		System.out.println("lightType: " + s19.lightType);
		System.out.println("color: " + s19.color);
		System.out.println("batteryCapacity: " + s19.batteryCapacity);
		System.out.println("price: " + s19.price);
		System.out.println("isSolarPowered: " + s19.isSolarPowered);
		System.out.println("isAvailable: " + s19.isAvailable);
		System.out.println("manufacturingDate: " + s19.manufacturingDate);
		System.out.println("expiryDate: " + s19.expiryDate);
		System.out.println("usageType: " + s19.usageType);
		System.out.println("material: " + s19.material);
		System.out.println("brightnessLevel: " + s19.brightnessLevel);
		System.out.println("isWaterproof: " + s19.isWaterproof);
		System.out.println("countryOfOrigin: " + s19.countryOfOrigin);
		System.out.println("warrantyMonths: " + s19.warrantyMonths);
		System.out.println("packagingType: " + s19.packagingType);
		System.out.println("weight: " + s19.weight);
		System.out.println("isShockResistant: " + s19.isShockResistant);
		System.out.println("feature1: " + s19.feature1);
		System.out.println("feature2: " + s19.feature2);
		System.out.println("feature3: " + s19.feature3);
		System.out.println("isPortable: " + s19.isPortable);
		System.out.println("isEnergySaving: " + s19.isEnergySaving);
		System.out.println("rating: " + s19.rating);


		SolarTorch s20 = new SolarTorch();
		s20.productId = 120;
		s20.brandName = "Sample20";
		s20.lightType = "Sample20";
		s20.color = "Sample20";
		s20.batteryCapacity = 30.0;
		s20.price = 30.0;
		s20.isSolarPowered = true;
		s20.isAvailable = true;
		s20.manufacturingDate = "Sample20";
		s20.expiryDate = "Sample20";
		s20.usageType = "Sample20";
		s20.material = "Sample20";
		s20.brightnessLevel = 30.0;
		s20.isWaterproof = true;
		s20.countryOfOrigin = "Sample20";
		s20.warrantyMonths = 120;
		s20.packagingType = "Sample20";
		s20.weight = 30.0;
		s20.isShockResistant = true;
		s20.feature1 = "Sample20";
		s20.feature2 = "Sample20";
		s20.feature3 = "Sample20";
		s20.isPortable = true;
		s20.isEnergySaving = true;
		s20.rating = 120;

		System.out.println("----- SolarTorch 20 -----");
		System.out.println("productId: " + s20.productId);
		System.out.println("brandName: " + s20.brandName);
		System.out.println("lightType: " + s20.lightType);
		System.out.println("color: " + s20.color);
		System.out.println("batteryCapacity: " + s20.batteryCapacity);
		System.out.println("price: " + s20.price);
		System.out.println("isSolarPowered: " + s20.isSolarPowered);
		System.out.println("isAvailable: " + s20.isAvailable);
		System.out.println("manufacturingDate: " + s20.manufacturingDate);
		System.out.println("expiryDate: " + s20.expiryDate);
		System.out.println("usageType: " + s20.usageType);
		System.out.println("material: " + s20.material);
		System.out.println("brightnessLevel: " + s20.brightnessLevel);
		System.out.println("isWaterproof: " + s20.isWaterproof);
		System.out.println("countryOfOrigin: " + s20.countryOfOrigin);
		System.out.println("warrantyMonths: " + s20.warrantyMonths);
		System.out.println("packagingType: " + s20.packagingType);
		System.out.println("weight: " + s20.weight);
		System.out.println("isShockResistant: " + s20.isShockResistant);
		System.out.println("feature1: " + s20.feature1);
		System.out.println("feature2: " + s20.feature2);
		System.out.println("feature3: " + s20.feature3);
		System.out.println("isPortable: " + s20.isPortable);
		System.out.println("isEnergySaving: " + s20.isEnergySaving);
		System.out.println("rating: " + s20.rating);


		SolarTorch s21 = new SolarTorch();
		s21.productId = 121;
		s21.brandName = "Sample21";
		s21.lightType = "Sample21";
		s21.color = "Sample21";
		s21.batteryCapacity = 31.0;
		s21.price = 31.0;
		s21.isSolarPowered = false;
		s21.isAvailable = false;
		s21.manufacturingDate = "Sample21";
		s21.expiryDate = "Sample21";
		s21.usageType = "Sample21";
		s21.material = "Sample21";
		s21.brightnessLevel = 31.0;
		s21.isWaterproof = false;
		s21.countryOfOrigin = "Sample21";
		s21.warrantyMonths = 121;
		s21.packagingType = "Sample21";
		s21.weight = 31.0;
		s21.isShockResistant = false;
		s21.feature1 = "Sample21";
		s21.feature2 = "Sample21";
		s21.feature3 = "Sample21";
		s21.isPortable = false;
		s21.isEnergySaving = false;
		s21.rating = 121;

		System.out.println("----- SolarTorch 21 -----");
		System.out.println("productId: " + s21.productId);
		System.out.println("brandName: " + s21.brandName);
		System.out.println("lightType: " + s21.lightType);
		System.out.println("color: " + s21.color);
		System.out.println("batteryCapacity: " + s21.batteryCapacity);
		System.out.println("price: " + s21.price);
		System.out.println("isSolarPowered: " + s21.isSolarPowered);
		System.out.println("isAvailable: " + s21.isAvailable);
		System.out.println("manufacturingDate: " + s21.manufacturingDate);
		System.out.println("expiryDate: " + s21.expiryDate);
		System.out.println("usageType: " + s21.usageType);
		System.out.println("material: " + s21.material);
		System.out.println("brightnessLevel: " + s21.brightnessLevel);
		System.out.println("isWaterproof: " + s21.isWaterproof);
		System.out.println("countryOfOrigin: " + s21.countryOfOrigin);
		System.out.println("warrantyMonths: " + s21.warrantyMonths);
		System.out.println("packagingType: " + s21.packagingType);
		System.out.println("weight: " + s21.weight);
		System.out.println("isShockResistant: " + s21.isShockResistant);
		System.out.println("feature1: " + s21.feature1);
		System.out.println("feature2: " + s21.feature2);
		System.out.println("feature3: " + s21.feature3);
		System.out.println("isPortable: " + s21.isPortable);
		System.out.println("isEnergySaving: " + s21.isEnergySaving);
		System.out.println("rating: " + s21.rating);


		SolarTorch s22 = new SolarTorch();
		s22.productId = 122;
		s22.brandName = "Sample22";
		s22.lightType = "Sample22";
		s22.color = "Sample22";
		s22.batteryCapacity = 32.0;
		s22.price = 32.0;
		s22.isSolarPowered = true;
		s22.isAvailable = true;
		s22.manufacturingDate = "Sample22";
		s22.expiryDate = "Sample22";
		s22.usageType = "Sample22";
		s22.material = "Sample22";
		s22.brightnessLevel = 32.0;
		s22.isWaterproof = true;
		s22.countryOfOrigin = "Sample22";
		s22.warrantyMonths = 122;
		s22.packagingType = "Sample22";
		s22.weight = 32.0;
		s22.isShockResistant = true;
		s22.feature1 = "Sample22";
		s22.feature2 = "Sample22";
		s22.feature3 = "Sample22";
		s22.isPortable = true;
		s22.isEnergySaving = true;
		s22.rating = 122;

		System.out.println("----- SolarTorch 22 -----");
		System.out.println("productId: " + s22.productId);
		System.out.println("brandName: " + s22.brandName);
		System.out.println("lightType: " + s22.lightType);
		System.out.println("color: " + s22.color);
		System.out.println("batteryCapacity: " + s22.batteryCapacity);
		System.out.println("price: " + s22.price);
		System.out.println("isSolarPowered: " + s22.isSolarPowered);
		System.out.println("isAvailable: " + s22.isAvailable);
		System.out.println("manufacturingDate: " + s22.manufacturingDate);
		System.out.println("expiryDate: " + s22.expiryDate);
		System.out.println("usageType: " + s22.usageType);
		System.out.println("material: " + s22.material);
		System.out.println("brightnessLevel: " + s22.brightnessLevel);
		System.out.println("isWaterproof: " + s22.isWaterproof);
		System.out.println("countryOfOrigin: " + s22.countryOfOrigin);
		System.out.println("warrantyMonths: " + s22.warrantyMonths);
		System.out.println("packagingType: " + s22.packagingType);
		System.out.println("weight: " + s22.weight);
		System.out.println("isShockResistant: " + s22.isShockResistant);
		System.out.println("feature1: " + s22.feature1);
		System.out.println("feature2: " + s22.feature2);
		System.out.println("feature3: " + s22.feature3);
		System.out.println("isPortable: " + s22.isPortable);
		System.out.println("isEnergySaving: " + s22.isEnergySaving);
		System.out.println("rating: " + s22.rating);


		SolarTorch s23 = new SolarTorch();
		s23.productId = 123;
		s23.brandName = "Sample23";
		s23.lightType = "Sample23";
		s23.color = "Sample23";
		s23.batteryCapacity = 33.0;
		s23.price = 33.0;
		s23.isSolarPowered = false;
		s23.isAvailable = false;
		s23.manufacturingDate = "Sample23";
		s23.expiryDate = "Sample23";
		s23.usageType = "Sample23";
		s23.material = "Sample23";
		s23.brightnessLevel = 33.0;
		s23.isWaterproof = false;
		s23.countryOfOrigin = "Sample23";
		s23.warrantyMonths = 123;
		s23.packagingType = "Sample23";
		s23.weight = 33.0;
		s23.isShockResistant = false;
		s23.feature1 = "Sample23";
		s23.feature2 = "Sample23";
		s23.feature3 = "Sample23";
		s23.isPortable = false;
		s23.isEnergySaving = false;
		s23.rating = 123;

		System.out.println("----- SolarTorch 23 -----");
		System.out.println("productId: " + s23.productId);
		System.out.println("brandName: " + s23.brandName);
		System.out.println("lightType: " + s23.lightType);
		System.out.println("color: " + s23.color);
		System.out.println("batteryCapacity: " + s23.batteryCapacity);
		System.out.println("price: " + s23.price);
		System.out.println("isSolarPowered: " + s23.isSolarPowered);
		System.out.println("isAvailable: " + s23.isAvailable);
		System.out.println("manufacturingDate: " + s23.manufacturingDate);
		System.out.println("expiryDate: " + s23.expiryDate);
		System.out.println("usageType: " + s23.usageType);
		System.out.println("material: " + s23.material);
		System.out.println("brightnessLevel: " + s23.brightnessLevel);
		System.out.println("isWaterproof: " + s23.isWaterproof);
		System.out.println("countryOfOrigin: " + s23.countryOfOrigin);
		System.out.println("warrantyMonths: " + s23.warrantyMonths);
		System.out.println("packagingType: " + s23.packagingType);
		System.out.println("weight: " + s23.weight);
		System.out.println("isShockResistant: " + s23.isShockResistant);
		System.out.println("feature1: " + s23.feature1);
		System.out.println("feature2: " + s23.feature2);
		System.out.println("feature3: " + s23.feature3);
		System.out.println("isPortable: " + s23.isPortable);
		System.out.println("isEnergySaving: " + s23.isEnergySaving);
		System.out.println("rating: " + s23.rating);


		SolarTorch s24 = new SolarTorch();
		s24.productId = 124;
		s24.brandName = "Sample24";
		s24.lightType = "Sample24";
		s24.color = "Sample24";
		s24.batteryCapacity = 34.0;
		s24.price = 34.0;
		s24.isSolarPowered = true;
		s24.isAvailable = true;
		s24.manufacturingDate = "Sample24";
		s24.expiryDate = "Sample24";
		s24.usageType = "Sample24";
		s24.material = "Sample24";
		s24.brightnessLevel = 34.0;
		s24.isWaterproof = true;
		s24.countryOfOrigin = "Sample24";
		s24.warrantyMonths = 124;
		s24.packagingType = "Sample24";
		s24.weight = 34.0;
		s24.isShockResistant = true;
		s24.feature1 = "Sample24";
		s24.feature2 = "Sample24";
		s24.feature3 = "Sample24";
		s24.isPortable = true;
		s24.isEnergySaving = true;
		s24.rating = 124;

		System.out.println("----- SolarTorch 24 -----");
		System.out.println("productId: " + s24.productId);
		System.out.println("brandName: " + s24.brandName);
		System.out.println("lightType: " + s24.lightType);
		System.out.println("color: " + s24.color);
		System.out.println("batteryCapacity: " + s24.batteryCapacity);
		System.out.println("price: " + s24.price);
		System.out.println("isSolarPowered: " + s24.isSolarPowered);
		System.out.println("isAvailable: " + s24.isAvailable);
		System.out.println("manufacturingDate: " + s24.manufacturingDate);
		System.out.println("expiryDate: " + s24.expiryDate);
		System.out.println("usageType: " + s24.usageType);
		System.out.println("material: " + s24.material);
		System.out.println("brightnessLevel: " + s24.brightnessLevel);
		System.out.println("isWaterproof: " + s24.isWaterproof);
		System.out.println("countryOfOrigin: " + s24.countryOfOrigin);
		System.out.println("warrantyMonths: " + s24.warrantyMonths);
		System.out.println("packagingType: " + s24.packagingType);
		System.out.println("weight: " + s24.weight);
		System.out.println("isShockResistant: " + s24.isShockResistant);
		System.out.println("feature1: " + s24.feature1);
		System.out.println("feature2: " + s24.feature2);
		System.out.println("feature3: " + s24.feature3);
		System.out.println("isPortable: " + s24.isPortable);
		System.out.println("isEnergySaving: " + s24.isEnergySaving);
		System.out.println("rating: " + s24.rating);


		SolarTorch s25 = new SolarTorch();
		s25.productId = 125;
		s25.brandName = "Sample25";
		s25.lightType = "Sample25";
		s25.color = "Sample25";
		s25.batteryCapacity = 35.0;
		s25.price = 35.0;
		s25.isSolarPowered = false;
		s25.isAvailable = false;
		s25.manufacturingDate = "Sample25";
		s25.expiryDate = "Sample25";
		s25.usageType = "Sample25";
		s25.material = "Sample25";
		s25.brightnessLevel = 35.0;
		s25.isWaterproof = false;
		s25.countryOfOrigin = "Sample25";
		s25.warrantyMonths = 125;
		s25.packagingType = "Sample25";
		s25.weight = 35.0;
		s25.isShockResistant = false;
		s25.feature1 = "Sample25";
		s25.feature2 = "Sample25";
		s25.feature3 = "Sample25";
		s25.isPortable = false;
		s25.isEnergySaving = false;
		s25.rating = 125;

		System.out.println("----- SolarTorch 25 -----");
		System.out.println("productId: " + s25.productId);
		System.out.println("brandName: " + s25.brandName);
		System.out.println("lightType: " + s25.lightType);
		System.out.println("color: " + s25.color);
		System.out.println("batteryCapacity: " + s25.batteryCapacity);
		System.out.println("price: " + s25.price);
		System.out.println("isSolarPowered: " + s25.isSolarPowered);
		System.out.println("isAvailable: " + s25.isAvailable);
		System.out.println("manufacturingDate: " + s25.manufacturingDate);
		System.out.println("expiryDate: " + s25.expiryDate);
		System.out.println("usageType: " + s25.usageType);
		System.out.println("material: " + s25.material);
		System.out.println("brightnessLevel: " + s25.brightnessLevel);
		System.out.println("isWaterproof: " + s25.isWaterproof);
		System.out.println("countryOfOrigin: " + s25.countryOfOrigin);
		System.out.println("warrantyMonths: " + s25.warrantyMonths);
		System.out.println("packagingType: " + s25.packagingType);
		System.out.println("weight: " + s25.weight);
		System.out.println("isShockResistant: " + s25.isShockResistant);
		System.out.println("feature1: " + s25.feature1);
		System.out.println("feature2: " + s25.feature2);
		System.out.println("feature3: " + s25.feature3);
		System.out.println("isPortable: " + s25.isPortable);
		System.out.println("isEnergySaving: " + s25.isEnergySaving);
		System.out.println("rating: " + s25.rating);


	}
}
