class SwiggyExecutor{
	public static void main(String[] food){
		String foodName = "White Sauce Pasta";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "White Sauce Pasta";
		int quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Red Sauce Pasta";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Red Sauce Pasta";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Lasagna";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Lasagna";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Mac and Cheese";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Mac and Cheese";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Caesar Salad";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Caesar Salad";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Greek Salad";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Greek Salad";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Tandoori Chicken";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Tandoori Chicken";
		quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Butter Chicken";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Butter Chicken";
		quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Kadai Paneer";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Kadai Paneer";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Kadai Chicken";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Kadai Chicken";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Veg Kofta";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Veg Kofta";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Matar Paneer";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Matar Paneer";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Rajma Masala";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Rajma Masala";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Kadhi Pakora";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Kadhi Pakora";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Upma";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Upma";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Pongal";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Pongal";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Appam";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Appam";
		quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Puttu";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Puttu";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Kerala Parotta";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Kerala Parotta";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Chilli Paneer";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Chilli Paneer";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Chilli Chicken";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Chilli Chicken";
		quantity =6;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Fried Momos";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Fried Momos";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Steamed Momos";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Steamed Momos";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Thukpa";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Thukpa";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Falooda";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Falooda";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Kulfi";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Kulfi";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Rabri";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Rabri";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Basundi";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Basundi";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Shahi Tukda";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Shahi Tukda";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Moong Dal Halwa";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Moong Dal Halwa";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Carrot Halwa";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Carrot Halwa";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Badam Milk";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Badam Milk";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Lassi";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Lassi";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Buttermilk";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Buttermilk";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Masala Tea";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Masala Tea";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Filter Coffee";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Filter Coffee";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Cold Coffee";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Cold Coffee";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Cappuccino";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Cappuccino";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Espresso";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Espresso";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Blueberry Cheesecake";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Blueberry Cheesecake";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Strawberry Shake";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Strawberry Shake";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Pineapple Juice";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Pineapple Juice";
		quantity =8;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Watermelon Juice";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Watermelon Juice";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Orange Juice";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Orange Juice";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Veg Thali";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Veg Thali";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Non Veg Thali";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Non Veg Thali";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Dal Makhani";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Dal Makhani";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Bhindi Masala";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Bhindi Masala";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Baingan Bharta";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Baingan Bharta";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Stuffed Capsicum";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Stuffed Capsicum";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Corn Cheese Balls";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Corn Cheese Balls";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Nachos with Salsa";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Nachos with Salsa";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Mexican Burrito";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Mexican Burrito";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Tacos";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Tacos";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Sushi Roll";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Sushi Roll";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
		foodName = "Ramen Bowl";
		System.out.println("The price of " + foodName + " is "+ Swiggy.search(foodName));
		foodName = "Ramen Bowl";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Swiggy.search(foodName,quantity));
	}
}