class TitanKettleRunner {
	public static void main(String[] args) {

		TitanKettle t1 = new TitanKettle();
		t1.productId = 101;
		t1.brandName = "Sample1";
		t1.material = "Sample1";
		t1.color = "Sample1";
		t1.capacity = 11.0;
		t1.price = 11.0;
		t1.isElectric = false;
		t1.isAvailable = false;
		t1.manufacturingDate = "Sample1";
		t1.expiryDate = "Sample1";
		t1.heatingType = "Sample1";
		t1.handleMaterial = "Sample1";
		t1.power = 11.0;
		t1.isAutoShutOff = false;
		t1.countryOfOrigin = "Sample1";
		t1.warrantyMonths = 101;
		t1.packagingType = "Sample1";
		t1.weight = 11.0;
		t1.isCordless = false;
		t1.feature1 = "Sample1";
		t1.feature2 = "Sample1";
		t1.feature3 = "Sample1";
		t1.hasIndicator = false;
		t1.isEnergyEfficient = false;
		t1.rating = 101;

		System.out.println("----- TitanKettle 1 -----");
		System.out.println("productId: " + t1.productId);
		System.out.println("brandName: " + t1.brandName);
		System.out.println("material: " + t1.material);
		System.out.println("color: " + t1.color);
		System.out.println("capacity: " + t1.capacity);
		System.out.println("price: " + t1.price);
		System.out.println("isElectric: " + t1.isElectric);
		System.out.println("isAvailable: " + t1.isAvailable);
		System.out.println("manufacturingDate: " + t1.manufacturingDate);
		System.out.println("expiryDate: " + t1.expiryDate);
		System.out.println("heatingType: " + t1.heatingType);
		System.out.println("handleMaterial: " + t1.handleMaterial);
		System.out.println("power: " + t1.power);
		System.out.println("isAutoShutOff: " + t1.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t1.countryOfOrigin);
		System.out.println("warrantyMonths: " + t1.warrantyMonths);
		System.out.println("packagingType: " + t1.packagingType);
		System.out.println("weight: " + t1.weight);
		System.out.println("isCordless: " + t1.isCordless);
		System.out.println("feature1: " + t1.feature1);
		System.out.println("feature2: " + t1.feature2);
		System.out.println("feature3: " + t1.feature3);
		System.out.println("hasIndicator: " + t1.hasIndicator);
		System.out.println("isEnergyEfficient: " + t1.isEnergyEfficient);
		System.out.println("rating: " + t1.rating);


		TitanKettle t2 = new TitanKettle();
		t2.productId = 102;
		t2.brandName = "Sample2";
		t2.material = "Sample2";
		t2.color = "Sample2";
		t2.capacity = 12.0;
		t2.price = 12.0;
		t2.isElectric = true;
		t2.isAvailable = true;
		t2.manufacturingDate = "Sample2";
		t2.expiryDate = "Sample2";
		t2.heatingType = "Sample2";
		t2.handleMaterial = "Sample2";
		t2.power = 12.0;
		t2.isAutoShutOff = true;
		t2.countryOfOrigin = "Sample2";
		t2.warrantyMonths = 102;
		t2.packagingType = "Sample2";
		t2.weight = 12.0;
		t2.isCordless = true;
		t2.feature1 = "Sample2";
		t2.feature2 = "Sample2";
		t2.feature3 = "Sample2";
		t2.hasIndicator = true;
		t2.isEnergyEfficient = true;
		t2.rating = 102;

		System.out.println("----- TitanKettle 2 -----");
		System.out.println("productId: " + t2.productId);
		System.out.println("brandName: " + t2.brandName);
		System.out.println("material: " + t2.material);
		System.out.println("color: " + t2.color);
		System.out.println("capacity: " + t2.capacity);
		System.out.println("price: " + t2.price);
		System.out.println("isElectric: " + t2.isElectric);
		System.out.println("isAvailable: " + t2.isAvailable);
		System.out.println("manufacturingDate: " + t2.manufacturingDate);
		System.out.println("expiryDate: " + t2.expiryDate);
		System.out.println("heatingType: " + t2.heatingType);
		System.out.println("handleMaterial: " + t2.handleMaterial);
		System.out.println("power: " + t2.power);
		System.out.println("isAutoShutOff: " + t2.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t2.countryOfOrigin);
		System.out.println("warrantyMonths: " + t2.warrantyMonths);
		System.out.println("packagingType: " + t2.packagingType);
		System.out.println("weight: " + t2.weight);
		System.out.println("isCordless: " + t2.isCordless);
		System.out.println("feature1: " + t2.feature1);
		System.out.println("feature2: " + t2.feature2);
		System.out.println("feature3: " + t2.feature3);
		System.out.println("hasIndicator: " + t2.hasIndicator);
		System.out.println("isEnergyEfficient: " + t2.isEnergyEfficient);
		System.out.println("rating: " + t2.rating);


		TitanKettle t3 = new TitanKettle();
		t3.productId = 103;
		t3.brandName = "Sample3";
		t3.material = "Sample3";
		t3.color = "Sample3";
		t3.capacity = 13.0;
		t3.price = 13.0;
		t3.isElectric = false;
		t3.isAvailable = false;
		t3.manufacturingDate = "Sample3";
		t3.expiryDate = "Sample3";
		t3.heatingType = "Sample3";
		t3.handleMaterial = "Sample3";
		t3.power = 13.0;
		t3.isAutoShutOff = false;
		t3.countryOfOrigin = "Sample3";
		t3.warrantyMonths = 103;
		t3.packagingType = "Sample3";
		t3.weight = 13.0;
		t3.isCordless = false;
		t3.feature1 = "Sample3";
		t3.feature2 = "Sample3";
		t3.feature3 = "Sample3";
		t3.hasIndicator = false;
		t3.isEnergyEfficient = false;
		t3.rating = 103;

		System.out.println("----- TitanKettle 3 -----");
		System.out.println("productId: " + t3.productId);
		System.out.println("brandName: " + t3.brandName);
		System.out.println("material: " + t3.material);
		System.out.println("color: " + t3.color);
		System.out.println("capacity: " + t3.capacity);
		System.out.println("price: " + t3.price);
		System.out.println("isElectric: " + t3.isElectric);
		System.out.println("isAvailable: " + t3.isAvailable);
		System.out.println("manufacturingDate: " + t3.manufacturingDate);
		System.out.println("expiryDate: " + t3.expiryDate);
		System.out.println("heatingType: " + t3.heatingType);
		System.out.println("handleMaterial: " + t3.handleMaterial);
		System.out.println("power: " + t3.power);
		System.out.println("isAutoShutOff: " + t3.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t3.countryOfOrigin);
		System.out.println("warrantyMonths: " + t3.warrantyMonths);
		System.out.println("packagingType: " + t3.packagingType);
		System.out.println("weight: " + t3.weight);
		System.out.println("isCordless: " + t3.isCordless);
		System.out.println("feature1: " + t3.feature1);
		System.out.println("feature2: " + t3.feature2);
		System.out.println("feature3: " + t3.feature3);
		System.out.println("hasIndicator: " + t3.hasIndicator);
		System.out.println("isEnergyEfficient: " + t3.isEnergyEfficient);
		System.out.println("rating: " + t3.rating);


		TitanKettle t4 = new TitanKettle();
		t4.productId = 104;
		t4.brandName = "Sample4";
		t4.material = "Sample4";
		t4.color = "Sample4";
		t4.capacity = 14.0;
		t4.price = 14.0;
		t4.isElectric = true;
		t4.isAvailable = true;
		t4.manufacturingDate = "Sample4";
		t4.expiryDate = "Sample4";
		t4.heatingType = "Sample4";
		t4.handleMaterial = "Sample4";
		t4.power = 14.0;
		t4.isAutoShutOff = true;
		t4.countryOfOrigin = "Sample4";
		t4.warrantyMonths = 104;
		t4.packagingType = "Sample4";
		t4.weight = 14.0;
		t4.isCordless = true;
		t4.feature1 = "Sample4";
		t4.feature2 = "Sample4";
		t4.feature3 = "Sample4";
		t4.hasIndicator = true;
		t4.isEnergyEfficient = true;
		t4.rating = 104;

		System.out.println("----- TitanKettle 4 -----");
		System.out.println("productId: " + t4.productId);
		System.out.println("brandName: " + t4.brandName);
		System.out.println("material: " + t4.material);
		System.out.println("color: " + t4.color);
		System.out.println("capacity: " + t4.capacity);
		System.out.println("price: " + t4.price);
		System.out.println("isElectric: " + t4.isElectric);
		System.out.println("isAvailable: " + t4.isAvailable);
		System.out.println("manufacturingDate: " + t4.manufacturingDate);
		System.out.println("expiryDate: " + t4.expiryDate);
		System.out.println("heatingType: " + t4.heatingType);
		System.out.println("handleMaterial: " + t4.handleMaterial);
		System.out.println("power: " + t4.power);
		System.out.println("isAutoShutOff: " + t4.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t4.countryOfOrigin);
		System.out.println("warrantyMonths: " + t4.warrantyMonths);
		System.out.println("packagingType: " + t4.packagingType);
		System.out.println("weight: " + t4.weight);
		System.out.println("isCordless: " + t4.isCordless);
		System.out.println("feature1: " + t4.feature1);
		System.out.println("feature2: " + t4.feature2);
		System.out.println("feature3: " + t4.feature3);
		System.out.println("hasIndicator: " + t4.hasIndicator);
		System.out.println("isEnergyEfficient: " + t4.isEnergyEfficient);
		System.out.println("rating: " + t4.rating);


		TitanKettle t5 = new TitanKettle();
		t5.productId = 105;
		t5.brandName = "Sample5";
		t5.material = "Sample5";
		t5.color = "Sample5";
		t5.capacity = 15.0;
		t5.price = 15.0;
		t5.isElectric = false;
		t5.isAvailable = false;
		t5.manufacturingDate = "Sample5";
		t5.expiryDate = "Sample5";
		t5.heatingType = "Sample5";
		t5.handleMaterial = "Sample5";
		t5.power = 15.0;
		t5.isAutoShutOff = false;
		t5.countryOfOrigin = "Sample5";
		t5.warrantyMonths = 105;
		t5.packagingType = "Sample5";
		t5.weight = 15.0;
		t5.isCordless = false;
		t5.feature1 = "Sample5";
		t5.feature2 = "Sample5";
		t5.feature3 = "Sample5";
		t5.hasIndicator = false;
		t5.isEnergyEfficient = false;
		t5.rating = 105;

		System.out.println("----- TitanKettle 5 -----");
		System.out.println("productId: " + t5.productId);
		System.out.println("brandName: " + t5.brandName);
		System.out.println("material: " + t5.material);
		System.out.println("color: " + t5.color);
		System.out.println("capacity: " + t5.capacity);
		System.out.println("price: " + t5.price);
		System.out.println("isElectric: " + t5.isElectric);
		System.out.println("isAvailable: " + t5.isAvailable);
		System.out.println("manufacturingDate: " + t5.manufacturingDate);
		System.out.println("expiryDate: " + t5.expiryDate);
		System.out.println("heatingType: " + t5.heatingType);
		System.out.println("handleMaterial: " + t5.handleMaterial);
		System.out.println("power: " + t5.power);
		System.out.println("isAutoShutOff: " + t5.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t5.countryOfOrigin);
		System.out.println("warrantyMonths: " + t5.warrantyMonths);
		System.out.println("packagingType: " + t5.packagingType);
		System.out.println("weight: " + t5.weight);
		System.out.println("isCordless: " + t5.isCordless);
		System.out.println("feature1: " + t5.feature1);
		System.out.println("feature2: " + t5.feature2);
		System.out.println("feature3: " + t5.feature3);
		System.out.println("hasIndicator: " + t5.hasIndicator);
		System.out.println("isEnergyEfficient: " + t5.isEnergyEfficient);
		System.out.println("rating: " + t5.rating);


		TitanKettle t6 = new TitanKettle();
		t6.productId = 106;
		t6.brandName = "Sample6";
		t6.material = "Sample6";
		t6.color = "Sample6";
		t6.capacity = 16.0;
		t6.price = 16.0;
		t6.isElectric = true;
		t6.isAvailable = true;
		t6.manufacturingDate = "Sample6";
		t6.expiryDate = "Sample6";
		t6.heatingType = "Sample6";
		t6.handleMaterial = "Sample6";
		t6.power = 16.0;
		t6.isAutoShutOff = true;
		t6.countryOfOrigin = "Sample6";
		t6.warrantyMonths = 106;
		t6.packagingType = "Sample6";
		t6.weight = 16.0;
		t6.isCordless = true;
		t6.feature1 = "Sample6";
		t6.feature2 = "Sample6";
		t6.feature3 = "Sample6";
		t6.hasIndicator = true;
		t6.isEnergyEfficient = true;
		t6.rating = 106;

		System.out.println("----- TitanKettle 6 -----");
		System.out.println("productId: " + t6.productId);
		System.out.println("brandName: " + t6.brandName);
		System.out.println("material: " + t6.material);
		System.out.println("color: " + t6.color);
		System.out.println("capacity: " + t6.capacity);
		System.out.println("price: " + t6.price);
		System.out.println("isElectric: " + t6.isElectric);
		System.out.println("isAvailable: " + t6.isAvailable);
		System.out.println("manufacturingDate: " + t6.manufacturingDate);
		System.out.println("expiryDate: " + t6.expiryDate);
		System.out.println("heatingType: " + t6.heatingType);
		System.out.println("handleMaterial: " + t6.handleMaterial);
		System.out.println("power: " + t6.power);
		System.out.println("isAutoShutOff: " + t6.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t6.countryOfOrigin);
		System.out.println("warrantyMonths: " + t6.warrantyMonths);
		System.out.println("packagingType: " + t6.packagingType);
		System.out.println("weight: " + t6.weight);
		System.out.println("isCordless: " + t6.isCordless);
		System.out.println("feature1: " + t6.feature1);
		System.out.println("feature2: " + t6.feature2);
		System.out.println("feature3: " + t6.feature3);
		System.out.println("hasIndicator: " + t6.hasIndicator);
		System.out.println("isEnergyEfficient: " + t6.isEnergyEfficient);
		System.out.println("rating: " + t6.rating);


		TitanKettle t7 = new TitanKettle();
		t7.productId = 107;
		t7.brandName = "Sample7";
		t7.material = "Sample7";
		t7.color = "Sample7";
		t7.capacity = 17.0;
		t7.price = 17.0;
		t7.isElectric = false;
		t7.isAvailable = false;
		t7.manufacturingDate = "Sample7";
		t7.expiryDate = "Sample7";
		t7.heatingType = "Sample7";
		t7.handleMaterial = "Sample7";
		t7.power = 17.0;
		t7.isAutoShutOff = false;
		t7.countryOfOrigin = "Sample7";
		t7.warrantyMonths = 107;
		t7.packagingType = "Sample7";
		t7.weight = 17.0;
		t7.isCordless = false;
		t7.feature1 = "Sample7";
		t7.feature2 = "Sample7";
		t7.feature3 = "Sample7";
		t7.hasIndicator = false;
		t7.isEnergyEfficient = false;
		t7.rating = 107;

		System.out.println("----- TitanKettle 7 -----");
		System.out.println("productId: " + t7.productId);
		System.out.println("brandName: " + t7.brandName);
		System.out.println("material: " + t7.material);
		System.out.println("color: " + t7.color);
		System.out.println("capacity: " + t7.capacity);
		System.out.println("price: " + t7.price);
		System.out.println("isElectric: " + t7.isElectric);
		System.out.println("isAvailable: " + t7.isAvailable);
		System.out.println("manufacturingDate: " + t7.manufacturingDate);
		System.out.println("expiryDate: " + t7.expiryDate);
		System.out.println("heatingType: " + t7.heatingType);
		System.out.println("handleMaterial: " + t7.handleMaterial);
		System.out.println("power: " + t7.power);
		System.out.println("isAutoShutOff: " + t7.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t7.countryOfOrigin);
		System.out.println("warrantyMonths: " + t7.warrantyMonths);
		System.out.println("packagingType: " + t7.packagingType);
		System.out.println("weight: " + t7.weight);
		System.out.println("isCordless: " + t7.isCordless);
		System.out.println("feature1: " + t7.feature1);
		System.out.println("feature2: " + t7.feature2);
		System.out.println("feature3: " + t7.feature3);
		System.out.println("hasIndicator: " + t7.hasIndicator);
		System.out.println("isEnergyEfficient: " + t7.isEnergyEfficient);
		System.out.println("rating: " + t7.rating);


		TitanKettle t8 = new TitanKettle();
		t8.productId = 108;
		t8.brandName = "Sample8";
		t8.material = "Sample8";
		t8.color = "Sample8";
		t8.capacity = 18.0;
		t8.price = 18.0;
		t8.isElectric = true;
		t8.isAvailable = true;
		t8.manufacturingDate = "Sample8";
		t8.expiryDate = "Sample8";
		t8.heatingType = "Sample8";
		t8.handleMaterial = "Sample8";
		t8.power = 18.0;
		t8.isAutoShutOff = true;
		t8.countryOfOrigin = "Sample8";
		t8.warrantyMonths = 108;
		t8.packagingType = "Sample8";
		t8.weight = 18.0;
		t8.isCordless = true;
		t8.feature1 = "Sample8";
		t8.feature2 = "Sample8";
		t8.feature3 = "Sample8";
		t8.hasIndicator = true;
		t8.isEnergyEfficient = true;
		t8.rating = 108;

		System.out.println("----- TitanKettle 8 -----");
		System.out.println("productId: " + t8.productId);
		System.out.println("brandName: " + t8.brandName);
		System.out.println("material: " + t8.material);
		System.out.println("color: " + t8.color);
		System.out.println("capacity: " + t8.capacity);
		System.out.println("price: " + t8.price);
		System.out.println("isElectric: " + t8.isElectric);
		System.out.println("isAvailable: " + t8.isAvailable);
		System.out.println("manufacturingDate: " + t8.manufacturingDate);
		System.out.println("expiryDate: " + t8.expiryDate);
		System.out.println("heatingType: " + t8.heatingType);
		System.out.println("handleMaterial: " + t8.handleMaterial);
		System.out.println("power: " + t8.power);
		System.out.println("isAutoShutOff: " + t8.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t8.countryOfOrigin);
		System.out.println("warrantyMonths: " + t8.warrantyMonths);
		System.out.println("packagingType: " + t8.packagingType);
		System.out.println("weight: " + t8.weight);
		System.out.println("isCordless: " + t8.isCordless);
		System.out.println("feature1: " + t8.feature1);
		System.out.println("feature2: " + t8.feature2);
		System.out.println("feature3: " + t8.feature3);
		System.out.println("hasIndicator: " + t8.hasIndicator);
		System.out.println("isEnergyEfficient: " + t8.isEnergyEfficient);
		System.out.println("rating: " + t8.rating);


		TitanKettle t9 = new TitanKettle();
		t9.productId = 109;
		t9.brandName = "Sample9";
		t9.material = "Sample9";
		t9.color = "Sample9";
		t9.capacity = 19.0;
		t9.price = 19.0;
		t9.isElectric = false;
		t9.isAvailable = false;
		t9.manufacturingDate = "Sample9";
		t9.expiryDate = "Sample9";
		t9.heatingType = "Sample9";
		t9.handleMaterial = "Sample9";
		t9.power = 19.0;
		t9.isAutoShutOff = false;
		t9.countryOfOrigin = "Sample9";
		t9.warrantyMonths = 109;
		t9.packagingType = "Sample9";
		t9.weight = 19.0;
		t9.isCordless = false;
		t9.feature1 = "Sample9";
		t9.feature2 = "Sample9";
		t9.feature3 = "Sample9";
		t9.hasIndicator = false;
		t9.isEnergyEfficient = false;
		t9.rating = 109;

		System.out.println("----- TitanKettle 9 -----");
		System.out.println("productId: " + t9.productId);
		System.out.println("brandName: " + t9.brandName);
		System.out.println("material: " + t9.material);
		System.out.println("color: " + t9.color);
		System.out.println("capacity: " + t9.capacity);
		System.out.println("price: " + t9.price);
		System.out.println("isElectric: " + t9.isElectric);
		System.out.println("isAvailable: " + t9.isAvailable);
		System.out.println("manufacturingDate: " + t9.manufacturingDate);
		System.out.println("expiryDate: " + t9.expiryDate);
		System.out.println("heatingType: " + t9.heatingType);
		System.out.println("handleMaterial: " + t9.handleMaterial);
		System.out.println("power: " + t9.power);
		System.out.println("isAutoShutOff: " + t9.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t9.countryOfOrigin);
		System.out.println("warrantyMonths: " + t9.warrantyMonths);
		System.out.println("packagingType: " + t9.packagingType);
		System.out.println("weight: " + t9.weight);
		System.out.println("isCordless: " + t9.isCordless);
		System.out.println("feature1: " + t9.feature1);
		System.out.println("feature2: " + t9.feature2);
		System.out.println("feature3: " + t9.feature3);
		System.out.println("hasIndicator: " + t9.hasIndicator);
		System.out.println("isEnergyEfficient: " + t9.isEnergyEfficient);
		System.out.println("rating: " + t9.rating);


		TitanKettle t10 = new TitanKettle();
		t10.productId = 110;
		t10.brandName = "Sample10";
		t10.material = "Sample10";
		t10.color = "Sample10";
		t10.capacity = 20.0;
		t10.price = 20.0;
		t10.isElectric = true;
		t10.isAvailable = true;
		t10.manufacturingDate = "Sample10";
		t10.expiryDate = "Sample10";
		t10.heatingType = "Sample10";
		t10.handleMaterial = "Sample10";
		t10.power = 20.0;
		t10.isAutoShutOff = true;
		t10.countryOfOrigin = "Sample10";
		t10.warrantyMonths = 110;
		t10.packagingType = "Sample10";
		t10.weight = 20.0;
		t10.isCordless = true;
		t10.feature1 = "Sample10";
		t10.feature2 = "Sample10";
		t10.feature3 = "Sample10";
		t10.hasIndicator = true;
		t10.isEnergyEfficient = true;
		t10.rating = 110;

		System.out.println("----- TitanKettle 10 -----");
		System.out.println("productId: " + t10.productId);
		System.out.println("brandName: " + t10.brandName);
		System.out.println("material: " + t10.material);
		System.out.println("color: " + t10.color);
		System.out.println("capacity: " + t10.capacity);
		System.out.println("price: " + t10.price);
		System.out.println("isElectric: " + t10.isElectric);
		System.out.println("isAvailable: " + t10.isAvailable);
		System.out.println("manufacturingDate: " + t10.manufacturingDate);
		System.out.println("expiryDate: " + t10.expiryDate);
		System.out.println("heatingType: " + t10.heatingType);
		System.out.println("handleMaterial: " + t10.handleMaterial);
		System.out.println("power: " + t10.power);
		System.out.println("isAutoShutOff: " + t10.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t10.countryOfOrigin);
		System.out.println("warrantyMonths: " + t10.warrantyMonths);
		System.out.println("packagingType: " + t10.packagingType);
		System.out.println("weight: " + t10.weight);
		System.out.println("isCordless: " + t10.isCordless);
		System.out.println("feature1: " + t10.feature1);
		System.out.println("feature2: " + t10.feature2);
		System.out.println("feature3: " + t10.feature3);
		System.out.println("hasIndicator: " + t10.hasIndicator);
		System.out.println("isEnergyEfficient: " + t10.isEnergyEfficient);
		System.out.println("rating: " + t10.rating);


		TitanKettle t11 = new TitanKettle();
		t11.productId = 111;
		t11.brandName = "Sample11";
		t11.material = "Sample11";
		t11.color = "Sample11";
		t11.capacity = 21.0;
		t11.price = 21.0;
		t11.isElectric = false;
		t11.isAvailable = false;
		t11.manufacturingDate = "Sample11";
		t11.expiryDate = "Sample11";
		t11.heatingType = "Sample11";
		t11.handleMaterial = "Sample11";
		t11.power = 21.0;
		t11.isAutoShutOff = false;
		t11.countryOfOrigin = "Sample11";
		t11.warrantyMonths = 111;
		t11.packagingType = "Sample11";
		t11.weight = 21.0;
		t11.isCordless = false;
		t11.feature1 = "Sample11";
		t11.feature2 = "Sample11";
		t11.feature3 = "Sample11";
		t11.hasIndicator = false;
		t11.isEnergyEfficient = false;
		t11.rating = 111;

		System.out.println("----- TitanKettle 11 -----");
		System.out.println("productId: " + t11.productId);
		System.out.println("brandName: " + t11.brandName);
		System.out.println("material: " + t11.material);
		System.out.println("color: " + t11.color);
		System.out.println("capacity: " + t11.capacity);
		System.out.println("price: " + t11.price);
		System.out.println("isElectric: " + t11.isElectric);
		System.out.println("isAvailable: " + t11.isAvailable);
		System.out.println("manufacturingDate: " + t11.manufacturingDate);
		System.out.println("expiryDate: " + t11.expiryDate);
		System.out.println("heatingType: " + t11.heatingType);
		System.out.println("handleMaterial: " + t11.handleMaterial);
		System.out.println("power: " + t11.power);
		System.out.println("isAutoShutOff: " + t11.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t11.countryOfOrigin);
		System.out.println("warrantyMonths: " + t11.warrantyMonths);
		System.out.println("packagingType: " + t11.packagingType);
		System.out.println("weight: " + t11.weight);
		System.out.println("isCordless: " + t11.isCordless);
		System.out.println("feature1: " + t11.feature1);
		System.out.println("feature2: " + t11.feature2);
		System.out.println("feature3: " + t11.feature3);
		System.out.println("hasIndicator: " + t11.hasIndicator);
		System.out.println("isEnergyEfficient: " + t11.isEnergyEfficient);
		System.out.println("rating: " + t11.rating);


		TitanKettle t12 = new TitanKettle();
		t12.productId = 112;
		t12.brandName = "Sample12";
		t12.material = "Sample12";
		t12.color = "Sample12";
		t12.capacity = 22.0;
		t12.price = 22.0;
		t12.isElectric = true;
		t12.isAvailable = true;
		t12.manufacturingDate = "Sample12";
		t12.expiryDate = "Sample12";
		t12.heatingType = "Sample12";
		t12.handleMaterial = "Sample12";
		t12.power = 22.0;
		t12.isAutoShutOff = true;
		t12.countryOfOrigin = "Sample12";
		t12.warrantyMonths = 112;
		t12.packagingType = "Sample12";
		t12.weight = 22.0;
		t12.isCordless = true;
		t12.feature1 = "Sample12";
		t12.feature2 = "Sample12";
		t12.feature3 = "Sample12";
		t12.hasIndicator = true;
		t12.isEnergyEfficient = true;
		t12.rating = 112;

		System.out.println("----- TitanKettle 12 -----");
		System.out.println("productId: " + t12.productId);
		System.out.println("brandName: " + t12.brandName);
		System.out.println("material: " + t12.material);
		System.out.println("color: " + t12.color);
		System.out.println("capacity: " + t12.capacity);
		System.out.println("price: " + t12.price);
		System.out.println("isElectric: " + t12.isElectric);
		System.out.println("isAvailable: " + t12.isAvailable);
		System.out.println("manufacturingDate: " + t12.manufacturingDate);
		System.out.println("expiryDate: " + t12.expiryDate);
		System.out.println("heatingType: " + t12.heatingType);
		System.out.println("handleMaterial: " + t12.handleMaterial);
		System.out.println("power: " + t12.power);
		System.out.println("isAutoShutOff: " + t12.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t12.countryOfOrigin);
		System.out.println("warrantyMonths: " + t12.warrantyMonths);
		System.out.println("packagingType: " + t12.packagingType);
		System.out.println("weight: " + t12.weight);
		System.out.println("isCordless: " + t12.isCordless);
		System.out.println("feature1: " + t12.feature1);
		System.out.println("feature2: " + t12.feature2);
		System.out.println("feature3: " + t12.feature3);
		System.out.println("hasIndicator: " + t12.hasIndicator);
		System.out.println("isEnergyEfficient: " + t12.isEnergyEfficient);
		System.out.println("rating: " + t12.rating);


		TitanKettle t13 = new TitanKettle();
		t13.productId = 113;
		t13.brandName = "Sample13";
		t13.material = "Sample13";
		t13.color = "Sample13";
		t13.capacity = 23.0;
		t13.price = 23.0;
		t13.isElectric = false;
		t13.isAvailable = false;
		t13.manufacturingDate = "Sample13";
		t13.expiryDate = "Sample13";
		t13.heatingType = "Sample13";
		t13.handleMaterial = "Sample13";
		t13.power = 23.0;
		t13.isAutoShutOff = false;
		t13.countryOfOrigin = "Sample13";
		t13.warrantyMonths = 113;
		t13.packagingType = "Sample13";
		t13.weight = 23.0;
		t13.isCordless = false;
		t13.feature1 = "Sample13";
		t13.feature2 = "Sample13";
		t13.feature3 = "Sample13";
		t13.hasIndicator = false;
		t13.isEnergyEfficient = false;
		t13.rating = 113;

		System.out.println("----- TitanKettle 13 -----");
		System.out.println("productId: " + t13.productId);
		System.out.println("brandName: " + t13.brandName);
		System.out.println("material: " + t13.material);
		System.out.println("color: " + t13.color);
		System.out.println("capacity: " + t13.capacity);
		System.out.println("price: " + t13.price);
		System.out.println("isElectric: " + t13.isElectric);
		System.out.println("isAvailable: " + t13.isAvailable);
		System.out.println("manufacturingDate: " + t13.manufacturingDate);
		System.out.println("expiryDate: " + t13.expiryDate);
		System.out.println("heatingType: " + t13.heatingType);
		System.out.println("handleMaterial: " + t13.handleMaterial);
		System.out.println("power: " + t13.power);
		System.out.println("isAutoShutOff: " + t13.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t13.countryOfOrigin);
		System.out.println("warrantyMonths: " + t13.warrantyMonths);
		System.out.println("packagingType: " + t13.packagingType);
		System.out.println("weight: " + t13.weight);
		System.out.println("isCordless: " + t13.isCordless);
		System.out.println("feature1: " + t13.feature1);
		System.out.println("feature2: " + t13.feature2);
		System.out.println("feature3: " + t13.feature3);
		System.out.println("hasIndicator: " + t13.hasIndicator);
		System.out.println("isEnergyEfficient: " + t13.isEnergyEfficient);
		System.out.println("rating: " + t13.rating);


		TitanKettle t14 = new TitanKettle();
		t14.productId = 114;
		t14.brandName = "Sample14";
		t14.material = "Sample14";
		t14.color = "Sample14";
		t14.capacity = 24.0;
		t14.price = 24.0;
		t14.isElectric = true;
		t14.isAvailable = true;
		t14.manufacturingDate = "Sample14";
		t14.expiryDate = "Sample14";
		t14.heatingType = "Sample14";
		t14.handleMaterial = "Sample14";
		t14.power = 24.0;
		t14.isAutoShutOff = true;
		t14.countryOfOrigin = "Sample14";
		t14.warrantyMonths = 114;
		t14.packagingType = "Sample14";
		t14.weight = 24.0;
		t14.isCordless = true;
		t14.feature1 = "Sample14";
		t14.feature2 = "Sample14";
		t14.feature3 = "Sample14";
		t14.hasIndicator = true;
		t14.isEnergyEfficient = true;
		t14.rating = 114;

		System.out.println("----- TitanKettle 14 -----");
		System.out.println("productId: " + t14.productId);
		System.out.println("brandName: " + t14.brandName);
		System.out.println("material: " + t14.material);
		System.out.println("color: " + t14.color);
		System.out.println("capacity: " + t14.capacity);
		System.out.println("price: " + t14.price);
		System.out.println("isElectric: " + t14.isElectric);
		System.out.println("isAvailable: " + t14.isAvailable);
		System.out.println("manufacturingDate: " + t14.manufacturingDate);
		System.out.println("expiryDate: " + t14.expiryDate);
		System.out.println("heatingType: " + t14.heatingType);
		System.out.println("handleMaterial: " + t14.handleMaterial);
		System.out.println("power: " + t14.power);
		System.out.println("isAutoShutOff: " + t14.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t14.countryOfOrigin);
		System.out.println("warrantyMonths: " + t14.warrantyMonths);
		System.out.println("packagingType: " + t14.packagingType);
		System.out.println("weight: " + t14.weight);
		System.out.println("isCordless: " + t14.isCordless);
		System.out.println("feature1: " + t14.feature1);
		System.out.println("feature2: " + t14.feature2);
		System.out.println("feature3: " + t14.feature3);
		System.out.println("hasIndicator: " + t14.hasIndicator);
		System.out.println("isEnergyEfficient: " + t14.isEnergyEfficient);
		System.out.println("rating: " + t14.rating);


		TitanKettle t15 = new TitanKettle();
		t15.productId = 115;
		t15.brandName = "Sample15";
		t15.material = "Sample15";
		t15.color = "Sample15";
		t15.capacity = 25.0;
		t15.price = 25.0;
		t15.isElectric = false;
		t15.isAvailable = false;
		t15.manufacturingDate = "Sample15";
		t15.expiryDate = "Sample15";
		t15.heatingType = "Sample15";
		t15.handleMaterial = "Sample15";
		t15.power = 25.0;
		t15.isAutoShutOff = false;
		t15.countryOfOrigin = "Sample15";
		t15.warrantyMonths = 115;
		t15.packagingType = "Sample15";
		t15.weight = 25.0;
		t15.isCordless = false;
		t15.feature1 = "Sample15";
		t15.feature2 = "Sample15";
		t15.feature3 = "Sample15";
		t15.hasIndicator = false;
		t15.isEnergyEfficient = false;
		t15.rating = 115;

		System.out.println("----- TitanKettle 15 -----");
		System.out.println("productId: " + t15.productId);
		System.out.println("brandName: " + t15.brandName);
		System.out.println("material: " + t15.material);
		System.out.println("color: " + t15.color);
		System.out.println("capacity: " + t15.capacity);
		System.out.println("price: " + t15.price);
		System.out.println("isElectric: " + t15.isElectric);
		System.out.println("isAvailable: " + t15.isAvailable);
		System.out.println("manufacturingDate: " + t15.manufacturingDate);
		System.out.println("expiryDate: " + t15.expiryDate);
		System.out.println("heatingType: " + t15.heatingType);
		System.out.println("handleMaterial: " + t15.handleMaterial);
		System.out.println("power: " + t15.power);
		System.out.println("isAutoShutOff: " + t15.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t15.countryOfOrigin);
		System.out.println("warrantyMonths: " + t15.warrantyMonths);
		System.out.println("packagingType: " + t15.packagingType);
		System.out.println("weight: " + t15.weight);
		System.out.println("isCordless: " + t15.isCordless);
		System.out.println("feature1: " + t15.feature1);
		System.out.println("feature2: " + t15.feature2);
		System.out.println("feature3: " + t15.feature3);
		System.out.println("hasIndicator: " + t15.hasIndicator);
		System.out.println("isEnergyEfficient: " + t15.isEnergyEfficient);
		System.out.println("rating: " + t15.rating);


		TitanKettle t16 = new TitanKettle();
		t16.productId = 116;
		t16.brandName = "Sample16";
		t16.material = "Sample16";
		t16.color = "Sample16";
		t16.capacity = 26.0;
		t16.price = 26.0;
		t16.isElectric = true;
		t16.isAvailable = true;
		t16.manufacturingDate = "Sample16";
		t16.expiryDate = "Sample16";
		t16.heatingType = "Sample16";
		t16.handleMaterial = "Sample16";
		t16.power = 26.0;
		t16.isAutoShutOff = true;
		t16.countryOfOrigin = "Sample16";
		t16.warrantyMonths = 116;
		t16.packagingType = "Sample16";
		t16.weight = 26.0;
		t16.isCordless = true;
		t16.feature1 = "Sample16";
		t16.feature2 = "Sample16";
		t16.feature3 = "Sample16";
		t16.hasIndicator = true;
		t16.isEnergyEfficient = true;
		t16.rating = 116;

		System.out.println("----- TitanKettle 16 -----");
		System.out.println("productId: " + t16.productId);
		System.out.println("brandName: " + t16.brandName);
		System.out.println("material: " + t16.material);
		System.out.println("color: " + t16.color);
		System.out.println("capacity: " + t16.capacity);
		System.out.println("price: " + t16.price);
		System.out.println("isElectric: " + t16.isElectric);
		System.out.println("isAvailable: " + t16.isAvailable);
		System.out.println("manufacturingDate: " + t16.manufacturingDate);
		System.out.println("expiryDate: " + t16.expiryDate);
		System.out.println("heatingType: " + t16.heatingType);
		System.out.println("handleMaterial: " + t16.handleMaterial);
		System.out.println("power: " + t16.power);
		System.out.println("isAutoShutOff: " + t16.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t16.countryOfOrigin);
		System.out.println("warrantyMonths: " + t16.warrantyMonths);
		System.out.println("packagingType: " + t16.packagingType);
		System.out.println("weight: " + t16.weight);
		System.out.println("isCordless: " + t16.isCordless);
		System.out.println("feature1: " + t16.feature1);
		System.out.println("feature2: " + t16.feature2);
		System.out.println("feature3: " + t16.feature3);
		System.out.println("hasIndicator: " + t16.hasIndicator);
		System.out.println("isEnergyEfficient: " + t16.isEnergyEfficient);
		System.out.println("rating: " + t16.rating);


		TitanKettle t17 = new TitanKettle();
		t17.productId = 117;
		t17.brandName = "Sample17";
		t17.material = "Sample17";
		t17.color = "Sample17";
		t17.capacity = 27.0;
		t17.price = 27.0;
		t17.isElectric = false;
		t17.isAvailable = false;
		t17.manufacturingDate = "Sample17";
		t17.expiryDate = "Sample17";
		t17.heatingType = "Sample17";
		t17.handleMaterial = "Sample17";
		t17.power = 27.0;
		t17.isAutoShutOff = false;
		t17.countryOfOrigin = "Sample17";
		t17.warrantyMonths = 117;
		t17.packagingType = "Sample17";
		t17.weight = 27.0;
		t17.isCordless = false;
		t17.feature1 = "Sample17";
		t17.feature2 = "Sample17";
		t17.feature3 = "Sample17";
		t17.hasIndicator = false;
		t17.isEnergyEfficient = false;
		t17.rating = 117;

		System.out.println("----- TitanKettle 17 -----");
		System.out.println("productId: " + t17.productId);
		System.out.println("brandName: " + t17.brandName);
		System.out.println("material: " + t17.material);
		System.out.println("color: " + t17.color);
		System.out.println("capacity: " + t17.capacity);
		System.out.println("price: " + t17.price);
		System.out.println("isElectric: " + t17.isElectric);
		System.out.println("isAvailable: " + t17.isAvailable);
		System.out.println("manufacturingDate: " + t17.manufacturingDate);
		System.out.println("expiryDate: " + t17.expiryDate);
		System.out.println("heatingType: " + t17.heatingType);
		System.out.println("handleMaterial: " + t17.handleMaterial);
		System.out.println("power: " + t17.power);
		System.out.println("isAutoShutOff: " + t17.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t17.countryOfOrigin);
		System.out.println("warrantyMonths: " + t17.warrantyMonths);
		System.out.println("packagingType: " + t17.packagingType);
		System.out.println("weight: " + t17.weight);
		System.out.println("isCordless: " + t17.isCordless);
		System.out.println("feature1: " + t17.feature1);
		System.out.println("feature2: " + t17.feature2);
		System.out.println("feature3: " + t17.feature3);
		System.out.println("hasIndicator: " + t17.hasIndicator);
		System.out.println("isEnergyEfficient: " + t17.isEnergyEfficient);
		System.out.println("rating: " + t17.rating);


		TitanKettle t18 = new TitanKettle();
		t18.productId = 118;
		t18.brandName = "Sample18";
		t18.material = "Sample18";
		t18.color = "Sample18";
		t18.capacity = 28.0;
		t18.price = 28.0;
		t18.isElectric = true;
		t18.isAvailable = true;
		t18.manufacturingDate = "Sample18";
		t18.expiryDate = "Sample18";
		t18.heatingType = "Sample18";
		t18.handleMaterial = "Sample18";
		t18.power = 28.0;
		t18.isAutoShutOff = true;
		t18.countryOfOrigin = "Sample18";
		t18.warrantyMonths = 118;
		t18.packagingType = "Sample18";
		t18.weight = 28.0;
		t18.isCordless = true;
		t18.feature1 = "Sample18";
		t18.feature2 = "Sample18";
		t18.feature3 = "Sample18";
		t18.hasIndicator = true;
		t18.isEnergyEfficient = true;
		t18.rating = 118;

		System.out.println("----- TitanKettle 18 -----");
		System.out.println("productId: " + t18.productId);
		System.out.println("brandName: " + t18.brandName);
		System.out.println("material: " + t18.material);
		System.out.println("color: " + t18.color);
		System.out.println("capacity: " + t18.capacity);
		System.out.println("price: " + t18.price);
		System.out.println("isElectric: " + t18.isElectric);
		System.out.println("isAvailable: " + t18.isAvailable);
		System.out.println("manufacturingDate: " + t18.manufacturingDate);
		System.out.println("expiryDate: " + t18.expiryDate);
		System.out.println("heatingType: " + t18.heatingType);
		System.out.println("handleMaterial: " + t18.handleMaterial);
		System.out.println("power: " + t18.power);
		System.out.println("isAutoShutOff: " + t18.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t18.countryOfOrigin);
		System.out.println("warrantyMonths: " + t18.warrantyMonths);
		System.out.println("packagingType: " + t18.packagingType);
		System.out.println("weight: " + t18.weight);
		System.out.println("isCordless: " + t18.isCordless);
		System.out.println("feature1: " + t18.feature1);
		System.out.println("feature2: " + t18.feature2);
		System.out.println("feature3: " + t18.feature3);
		System.out.println("hasIndicator: " + t18.hasIndicator);
		System.out.println("isEnergyEfficient: " + t18.isEnergyEfficient);
		System.out.println("rating: " + t18.rating);


		TitanKettle t19 = new TitanKettle();
		t19.productId = 119;
		t19.brandName = "Sample19";
		t19.material = "Sample19";
		t19.color = "Sample19";
		t19.capacity = 29.0;
		t19.price = 29.0;
		t19.isElectric = false;
		t19.isAvailable = false;
		t19.manufacturingDate = "Sample19";
		t19.expiryDate = "Sample19";
		t19.heatingType = "Sample19";
		t19.handleMaterial = "Sample19";
		t19.power = 29.0;
		t19.isAutoShutOff = false;
		t19.countryOfOrigin = "Sample19";
		t19.warrantyMonths = 119;
		t19.packagingType = "Sample19";
		t19.weight = 29.0;
		t19.isCordless = false;
		t19.feature1 = "Sample19";
		t19.feature2 = "Sample19";
		t19.feature3 = "Sample19";
		t19.hasIndicator = false;
		t19.isEnergyEfficient = false;
		t19.rating = 119;

		System.out.println("----- TitanKettle 19 -----");
		System.out.println("productId: " + t19.productId);
		System.out.println("brandName: " + t19.brandName);
		System.out.println("material: " + t19.material);
		System.out.println("color: " + t19.color);
		System.out.println("capacity: " + t19.capacity);
		System.out.println("price: " + t19.price);
		System.out.println("isElectric: " + t19.isElectric);
		System.out.println("isAvailable: " + t19.isAvailable);
		System.out.println("manufacturingDate: " + t19.manufacturingDate);
		System.out.println("expiryDate: " + t19.expiryDate);
		System.out.println("heatingType: " + t19.heatingType);
		System.out.println("handleMaterial: " + t19.handleMaterial);
		System.out.println("power: " + t19.power);
		System.out.println("isAutoShutOff: " + t19.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t19.countryOfOrigin);
		System.out.println("warrantyMonths: " + t19.warrantyMonths);
		System.out.println("packagingType: " + t19.packagingType);
		System.out.println("weight: " + t19.weight);
		System.out.println("isCordless: " + t19.isCordless);
		System.out.println("feature1: " + t19.feature1);
		System.out.println("feature2: " + t19.feature2);
		System.out.println("feature3: " + t19.feature3);
		System.out.println("hasIndicator: " + t19.hasIndicator);
		System.out.println("isEnergyEfficient: " + t19.isEnergyEfficient);
		System.out.println("rating: " + t19.rating);


		TitanKettle t20 = new TitanKettle();
		t20.productId = 120;
		t20.brandName = "Sample20";
		t20.material = "Sample20";
		t20.color = "Sample20";
		t20.capacity = 30.0;
		t20.price = 30.0;
		t20.isElectric = true;
		t20.isAvailable = true;
		t20.manufacturingDate = "Sample20";
		t20.expiryDate = "Sample20";
		t20.heatingType = "Sample20";
		t20.handleMaterial = "Sample20";
		t20.power = 30.0;
		t20.isAutoShutOff = true;
		t20.countryOfOrigin = "Sample20";
		t20.warrantyMonths = 120;
		t20.packagingType = "Sample20";
		t20.weight = 30.0;
		t20.isCordless = true;
		t20.feature1 = "Sample20";
		t20.feature2 = "Sample20";
		t20.feature3 = "Sample20";
		t20.hasIndicator = true;
		t20.isEnergyEfficient = true;
		t20.rating = 120;

		System.out.println("----- TitanKettle 20 -----");
		System.out.println("productId: " + t20.productId);
		System.out.println("brandName: " + t20.brandName);
		System.out.println("material: " + t20.material);
		System.out.println("color: " + t20.color);
		System.out.println("capacity: " + t20.capacity);
		System.out.println("price: " + t20.price);
		System.out.println("isElectric: " + t20.isElectric);
		System.out.println("isAvailable: " + t20.isAvailable);
		System.out.println("manufacturingDate: " + t20.manufacturingDate);
		System.out.println("expiryDate: " + t20.expiryDate);
		System.out.println("heatingType: " + t20.heatingType);
		System.out.println("handleMaterial: " + t20.handleMaterial);
		System.out.println("power: " + t20.power);
		System.out.println("isAutoShutOff: " + t20.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t20.countryOfOrigin);
		System.out.println("warrantyMonths: " + t20.warrantyMonths);
		System.out.println("packagingType: " + t20.packagingType);
		System.out.println("weight: " + t20.weight);
		System.out.println("isCordless: " + t20.isCordless);
		System.out.println("feature1: " + t20.feature1);
		System.out.println("feature2: " + t20.feature2);
		System.out.println("feature3: " + t20.feature3);
		System.out.println("hasIndicator: " + t20.hasIndicator);
		System.out.println("isEnergyEfficient: " + t20.isEnergyEfficient);
		System.out.println("rating: " + t20.rating);


		TitanKettle t21 = new TitanKettle();
		t21.productId = 121;
		t21.brandName = "Sample21";
		t21.material = "Sample21";
		t21.color = "Sample21";
		t21.capacity = 31.0;
		t21.price = 31.0;
		t21.isElectric = false;
		t21.isAvailable = false;
		t21.manufacturingDate = "Sample21";
		t21.expiryDate = "Sample21";
		t21.heatingType = "Sample21";
		t21.handleMaterial = "Sample21";
		t21.power = 31.0;
		t21.isAutoShutOff = false;
		t21.countryOfOrigin = "Sample21";
		t21.warrantyMonths = 121;
		t21.packagingType = "Sample21";
		t21.weight = 31.0;
		t21.isCordless = false;
		t21.feature1 = "Sample21";
		t21.feature2 = "Sample21";
		t21.feature3 = "Sample21";
		t21.hasIndicator = false;
		t21.isEnergyEfficient = false;
		t21.rating = 121;

		System.out.println("----- TitanKettle 21 -----");
		System.out.println("productId: " + t21.productId);
		System.out.println("brandName: " + t21.brandName);
		System.out.println("material: " + t21.material);
		System.out.println("color: " + t21.color);
		System.out.println("capacity: " + t21.capacity);
		System.out.println("price: " + t21.price);
		System.out.println("isElectric: " + t21.isElectric);
		System.out.println("isAvailable: " + t21.isAvailable);
		System.out.println("manufacturingDate: " + t21.manufacturingDate);
		System.out.println("expiryDate: " + t21.expiryDate);
		System.out.println("heatingType: " + t21.heatingType);
		System.out.println("handleMaterial: " + t21.handleMaterial);
		System.out.println("power: " + t21.power);
		System.out.println("isAutoShutOff: " + t21.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t21.countryOfOrigin);
		System.out.println("warrantyMonths: " + t21.warrantyMonths);
		System.out.println("packagingType: " + t21.packagingType);
		System.out.println("weight: " + t21.weight);
		System.out.println("isCordless: " + t21.isCordless);
		System.out.println("feature1: " + t21.feature1);
		System.out.println("feature2: " + t21.feature2);
		System.out.println("feature3: " + t21.feature3);
		System.out.println("hasIndicator: " + t21.hasIndicator);
		System.out.println("isEnergyEfficient: " + t21.isEnergyEfficient);
		System.out.println("rating: " + t21.rating);


		TitanKettle t22 = new TitanKettle();
		t22.productId = 122;
		t22.brandName = "Sample22";
		t22.material = "Sample22";
		t22.color = "Sample22";
		t22.capacity = 32.0;
		t22.price = 32.0;
		t22.isElectric = true;
		t22.isAvailable = true;
		t22.manufacturingDate = "Sample22";
		t22.expiryDate = "Sample22";
		t22.heatingType = "Sample22";
		t22.handleMaterial = "Sample22";
		t22.power = 32.0;
		t22.isAutoShutOff = true;
		t22.countryOfOrigin = "Sample22";
		t22.warrantyMonths = 122;
		t22.packagingType = "Sample22";
		t22.weight = 32.0;
		t22.isCordless = true;
		t22.feature1 = "Sample22";
		t22.feature2 = "Sample22";
		t22.feature3 = "Sample22";
		t22.hasIndicator = true;
		t22.isEnergyEfficient = true;
		t22.rating = 122;

		System.out.println("----- TitanKettle 22 -----");
		System.out.println("productId: " + t22.productId);
		System.out.println("brandName: " + t22.brandName);
		System.out.println("material: " + t22.material);
		System.out.println("color: " + t22.color);
		System.out.println("capacity: " + t22.capacity);
		System.out.println("price: " + t22.price);
		System.out.println("isElectric: " + t22.isElectric);
		System.out.println("isAvailable: " + t22.isAvailable);
		System.out.println("manufacturingDate: " + t22.manufacturingDate);
		System.out.println("expiryDate: " + t22.expiryDate);
		System.out.println("heatingType: " + t22.heatingType);
		System.out.println("handleMaterial: " + t22.handleMaterial);
		System.out.println("power: " + t22.power);
		System.out.println("isAutoShutOff: " + t22.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t22.countryOfOrigin);
		System.out.println("warrantyMonths: " + t22.warrantyMonths);
		System.out.println("packagingType: " + t22.packagingType);
		System.out.println("weight: " + t22.weight);
		System.out.println("isCordless: " + t22.isCordless);
		System.out.println("feature1: " + t22.feature1);
		System.out.println("feature2: " + t22.feature2);
		System.out.println("feature3: " + t22.feature3);
		System.out.println("hasIndicator: " + t22.hasIndicator);
		System.out.println("isEnergyEfficient: " + t22.isEnergyEfficient);
		System.out.println("rating: " + t22.rating);


		TitanKettle t23 = new TitanKettle();
		t23.productId = 123;
		t23.brandName = "Sample23";
		t23.material = "Sample23";
		t23.color = "Sample23";
		t23.capacity = 33.0;
		t23.price = 33.0;
		t23.isElectric = false;
		t23.isAvailable = false;
		t23.manufacturingDate = "Sample23";
		t23.expiryDate = "Sample23";
		t23.heatingType = "Sample23";
		t23.handleMaterial = "Sample23";
		t23.power = 33.0;
		t23.isAutoShutOff = false;
		t23.countryOfOrigin = "Sample23";
		t23.warrantyMonths = 123;
		t23.packagingType = "Sample23";
		t23.weight = 33.0;
		t23.isCordless = false;
		t23.feature1 = "Sample23";
		t23.feature2 = "Sample23";
		t23.feature3 = "Sample23";
		t23.hasIndicator = false;
		t23.isEnergyEfficient = false;
		t23.rating = 123;

		System.out.println("----- TitanKettle 23 -----");
		System.out.println("productId: " + t23.productId);
		System.out.println("brandName: " + t23.brandName);
		System.out.println("material: " + t23.material);
		System.out.println("color: " + t23.color);
		System.out.println("capacity: " + t23.capacity);
		System.out.println("price: " + t23.price);
		System.out.println("isElectric: " + t23.isElectric);
		System.out.println("isAvailable: " + t23.isAvailable);
		System.out.println("manufacturingDate: " + t23.manufacturingDate);
		System.out.println("expiryDate: " + t23.expiryDate);
		System.out.println("heatingType: " + t23.heatingType);
		System.out.println("handleMaterial: " + t23.handleMaterial);
		System.out.println("power: " + t23.power);
		System.out.println("isAutoShutOff: " + t23.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t23.countryOfOrigin);
		System.out.println("warrantyMonths: " + t23.warrantyMonths);
		System.out.println("packagingType: " + t23.packagingType);
		System.out.println("weight: " + t23.weight);
		System.out.println("isCordless: " + t23.isCordless);
		System.out.println("feature1: " + t23.feature1);
		System.out.println("feature2: " + t23.feature2);
		System.out.println("feature3: " + t23.feature3);
		System.out.println("hasIndicator: " + t23.hasIndicator);
		System.out.println("isEnergyEfficient: " + t23.isEnergyEfficient);
		System.out.println("rating: " + t23.rating);


		TitanKettle t24 = new TitanKettle();
		t24.productId = 124;
		t24.brandName = "Sample24";
		t24.material = "Sample24";
		t24.color = "Sample24";
		t24.capacity = 34.0;
		t24.price = 34.0;
		t24.isElectric = true;
		t24.isAvailable = true;
		t24.manufacturingDate = "Sample24";
		t24.expiryDate = "Sample24";
		t24.heatingType = "Sample24";
		t24.handleMaterial = "Sample24";
		t24.power = 34.0;
		t24.isAutoShutOff = true;
		t24.countryOfOrigin = "Sample24";
		t24.warrantyMonths = 124;
		t24.packagingType = "Sample24";
		t24.weight = 34.0;
		t24.isCordless = true;
		t24.feature1 = "Sample24";
		t24.feature2 = "Sample24";
		t24.feature3 = "Sample24";
		t24.hasIndicator = true;
		t24.isEnergyEfficient = true;
		t24.rating = 124;

		System.out.println("----- TitanKettle 24 -----");
		System.out.println("productId: " + t24.productId);
		System.out.println("brandName: " + t24.brandName);
		System.out.println("material: " + t24.material);
		System.out.println("color: " + t24.color);
		System.out.println("capacity: " + t24.capacity);
		System.out.println("price: " + t24.price);
		System.out.println("isElectric: " + t24.isElectric);
		System.out.println("isAvailable: " + t24.isAvailable);
		System.out.println("manufacturingDate: " + t24.manufacturingDate);
		System.out.println("expiryDate: " + t24.expiryDate);
		System.out.println("heatingType: " + t24.heatingType);
		System.out.println("handleMaterial: " + t24.handleMaterial);
		System.out.println("power: " + t24.power);
		System.out.println("isAutoShutOff: " + t24.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t24.countryOfOrigin);
		System.out.println("warrantyMonths: " + t24.warrantyMonths);
		System.out.println("packagingType: " + t24.packagingType);
		System.out.println("weight: " + t24.weight);
		System.out.println("isCordless: " + t24.isCordless);
		System.out.println("feature1: " + t24.feature1);
		System.out.println("feature2: " + t24.feature2);
		System.out.println("feature3: " + t24.feature3);
		System.out.println("hasIndicator: " + t24.hasIndicator);
		System.out.println("isEnergyEfficient: " + t24.isEnergyEfficient);
		System.out.println("rating: " + t24.rating);


		TitanKettle t25 = new TitanKettle();
		t25.productId = 125;
		t25.brandName = "Sample25";
		t25.material = "Sample25";
		t25.color = "Sample25";
		t25.capacity = 35.0;
		t25.price = 35.0;
		t25.isElectric = false;
		t25.isAvailable = false;
		t25.manufacturingDate = "Sample25";
		t25.expiryDate = "Sample25";
		t25.heatingType = "Sample25";
		t25.handleMaterial = "Sample25";
		t25.power = 35.0;
		t25.isAutoShutOff = false;
		t25.countryOfOrigin = "Sample25";
		t25.warrantyMonths = 125;
		t25.packagingType = "Sample25";
		t25.weight = 35.0;
		t25.isCordless = false;
		t25.feature1 = "Sample25";
		t25.feature2 = "Sample25";
		t25.feature3 = "Sample25";
		t25.hasIndicator = false;
		t25.isEnergyEfficient = false;
		t25.rating = 125;

		System.out.println("----- TitanKettle 25 -----");
		System.out.println("productId: " + t25.productId);
		System.out.println("brandName: " + t25.brandName);
		System.out.println("material: " + t25.material);
		System.out.println("color: " + t25.color);
		System.out.println("capacity: " + t25.capacity);
		System.out.println("price: " + t25.price);
		System.out.println("isElectric: " + t25.isElectric);
		System.out.println("isAvailable: " + t25.isAvailable);
		System.out.println("manufacturingDate: " + t25.manufacturingDate);
		System.out.println("expiryDate: " + t25.expiryDate);
		System.out.println("heatingType: " + t25.heatingType);
		System.out.println("handleMaterial: " + t25.handleMaterial);
		System.out.println("power: " + t25.power);
		System.out.println("isAutoShutOff: " + t25.isAutoShutOff);
		System.out.println("countryOfOrigin: " + t25.countryOfOrigin);
		System.out.println("warrantyMonths: " + t25.warrantyMonths);
		System.out.println("packagingType: " + t25.packagingType);
		System.out.println("weight: " + t25.weight);
		System.out.println("isCordless: " + t25.isCordless);
		System.out.println("feature1: " + t25.feature1);
		System.out.println("feature2: " + t25.feature2);
		System.out.println("feature3: " + t25.feature3);
		System.out.println("hasIndicator: " + t25.hasIndicator);
		System.out.println("isEnergyEfficient: " + t25.isEnergyEfficient);
		System.out.println("rating: " + t25.rating);


	}
}

	