class VelvetCandleRunner {
	public static void main(String[] args) {

		VelvetCandle v1 = new VelvetCandle();
		v1.productId = 101;
		v1.brandName = "Sample1";
		v1.waxType = "Sample1";
		v1.fragrance = "Sample1";
		v1.burnTime = 11.0;
		v1.price = 11.0;
		v1.isScented = false;
		v1.isAvailable = false;
		v1.manufacturingDate = "Sample1";
		v1.expiryDate = "Sample1";
		v1.color = "Sample1";
		v1.containerType = "Sample1";
		v1.height = 11.0;
		v1.isOrganic = false;
		v1.countryOfOrigin = "Sample1";
		v1.shelfLifeMonths = 101;
		v1.packagingType = "Sample1";
		v1.weight = 11.0;
		v1.isSmokeless = false;
		v1.ingredient1 = "Sample1";
		v1.ingredient2 = "Sample1";
		v1.ingredient3 = "Sample1";
		v1.isDecorative = false;
		v1.isHandmade = false;
		v1.rating = 101;

		System.out.println("----- VelvetCandle 1 -----");
		System.out.println("productId: " + v1.productId);
		System.out.println("brandName: " + v1.brandName);
		System.out.println("waxType: " + v1.waxType);
		System.out.println("fragrance: " + v1.fragrance);
		System.out.println("burnTime: " + v1.burnTime);
		System.out.println("price: " + v1.price);
		System.out.println("isScented: " + v1.isScented);
		System.out.println("isAvailable: " + v1.isAvailable);
		System.out.println("manufacturingDate: " + v1.manufacturingDate);
		System.out.println("expiryDate: " + v1.expiryDate);
		System.out.println("color: " + v1.color);
		System.out.println("containerType: " + v1.containerType);
		System.out.println("height: " + v1.height);
		System.out.println("isOrganic: " + v1.isOrganic);
		System.out.println("countryOfOrigin: " + v1.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v1.shelfLifeMonths);
		System.out.println("packagingType: " + v1.packagingType);
		System.out.println("weight: " + v1.weight);
		System.out.println("isSmokeless: " + v1.isSmokeless);
		System.out.println("ingredient1: " + v1.ingredient1);
		System.out.println("ingredient2: " + v1.ingredient2);
		System.out.println("ingredient3: " + v1.ingredient3);
		System.out.println("isDecorative: " + v1.isDecorative);
		System.out.println("isHandmade: " + v1.isHandmade);
		System.out.println("rating: " + v1.rating);


		VelvetCandle v2 = new VelvetCandle();
		v2.productId = 102;
		v2.brandName = "Sample2";
		v2.waxType = "Sample2";
		v2.fragrance = "Sample2";
		v2.burnTime = 12.0;
		v2.price = 12.0;
		v2.isScented = true;
		v2.isAvailable = true;
		v2.manufacturingDate = "Sample2";
		v2.expiryDate = "Sample2";
		v2.color = "Sample2";
		v2.containerType = "Sample2";
		v2.height = 12.0;
		v2.isOrganic = true;
		v2.countryOfOrigin = "Sample2";
		v2.shelfLifeMonths = 102;
		v2.packagingType = "Sample2";
		v2.weight = 12.0;
		v2.isSmokeless = true;
		v2.ingredient1 = "Sample2";
		v2.ingredient2 = "Sample2";
		v2.ingredient3 = "Sample2";
		v2.isDecorative = true;
		v2.isHandmade = true;
		v2.rating = 102;

		System.out.println("----- VelvetCandle 2 -----");
		System.out.println("productId: " + v2.productId);
		System.out.println("brandName: " + v2.brandName);
		System.out.println("waxType: " + v2.waxType);
		System.out.println("fragrance: " + v2.fragrance);
		System.out.println("burnTime: " + v2.burnTime);
		System.out.println("price: " + v2.price);
		System.out.println("isScented: " + v2.isScented);
		System.out.println("isAvailable: " + v2.isAvailable);
		System.out.println("manufacturingDate: " + v2.manufacturingDate);
		System.out.println("expiryDate: " + v2.expiryDate);
		System.out.println("color: " + v2.color);
		System.out.println("containerType: " + v2.containerType);
		System.out.println("height: " + v2.height);
		System.out.println("isOrganic: " + v2.isOrganic);
		System.out.println("countryOfOrigin: " + v2.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v2.shelfLifeMonths);
		System.out.println("packagingType: " + v2.packagingType);
		System.out.println("weight: " + v2.weight);
		System.out.println("isSmokeless: " + v2.isSmokeless);
		System.out.println("ingredient1: " + v2.ingredient1);
		System.out.println("ingredient2: " + v2.ingredient2);
		System.out.println("ingredient3: " + v2.ingredient3);
		System.out.println("isDecorative: " + v2.isDecorative);
		System.out.println("isHandmade: " + v2.isHandmade);
		System.out.println("rating: " + v2.rating);


		VelvetCandle v3 = new VelvetCandle();
		v3.productId = 103;
		v3.brandName = "Sample3";
		v3.waxType = "Sample3";
		v3.fragrance = "Sample3";
		v3.burnTime = 13.0;
		v3.price = 13.0;
		v3.isScented = false;
		v3.isAvailable = false;
		v3.manufacturingDate = "Sample3";
		v3.expiryDate = "Sample3";
		v3.color = "Sample3";
		v3.containerType = "Sample3";
		v3.height = 13.0;
		v3.isOrganic = false;
		v3.countryOfOrigin = "Sample3";
		v3.shelfLifeMonths = 103;
		v3.packagingType = "Sample3";
		v3.weight = 13.0;
		v3.isSmokeless = false;
		v3.ingredient1 = "Sample3";
		v3.ingredient2 = "Sample3";
		v3.ingredient3 = "Sample3";
		v3.isDecorative = false;
		v3.isHandmade = false;
		v3.rating = 103;

		System.out.println("----- VelvetCandle 3 -----");
		System.out.println("productId: " + v3.productId);
		System.out.println("brandName: " + v3.brandName);
		System.out.println("waxType: " + v3.waxType);
		System.out.println("fragrance: " + v3.fragrance);
		System.out.println("burnTime: " + v3.burnTime);
		System.out.println("price: " + v3.price);
		System.out.println("isScented: " + v3.isScented);
		System.out.println("isAvailable: " + v3.isAvailable);
		System.out.println("manufacturingDate: " + v3.manufacturingDate);
		System.out.println("expiryDate: " + v3.expiryDate);
		System.out.println("color: " + v3.color);
		System.out.println("containerType: " + v3.containerType);
		System.out.println("height: " + v3.height);
		System.out.println("isOrganic: " + v3.isOrganic);
		System.out.println("countryOfOrigin: " + v3.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v3.shelfLifeMonths);
		System.out.println("packagingType: " + v3.packagingType);
		System.out.println("weight: " + v3.weight);
		System.out.println("isSmokeless: " + v3.isSmokeless);
		System.out.println("ingredient1: " + v3.ingredient1);
		System.out.println("ingredient2: " + v3.ingredient2);
		System.out.println("ingredient3: " + v3.ingredient3);
		System.out.println("isDecorative: " + v3.isDecorative);
		System.out.println("isHandmade: " + v3.isHandmade);
		System.out.println("rating: " + v3.rating);


		VelvetCandle v4 = new VelvetCandle();
		v4.productId = 104;
		v4.brandName = "Sample4";
		v4.waxType = "Sample4";
		v4.fragrance = "Sample4";
		v4.burnTime = 14.0;
		v4.price = 14.0;
		v4.isScented = true;
		v4.isAvailable = true;
		v4.manufacturingDate = "Sample4";
		v4.expiryDate = "Sample4";
		v4.color = "Sample4";
		v4.containerType = "Sample4";
		v4.height = 14.0;
		v4.isOrganic = true;
		v4.countryOfOrigin = "Sample4";
		v4.shelfLifeMonths = 104;
		v4.packagingType = "Sample4";
		v4.weight = 14.0;
		v4.isSmokeless = true;
		v4.ingredient1 = "Sample4";
		v4.ingredient2 = "Sample4";
		v4.ingredient3 = "Sample4";
		v4.isDecorative = true;
		v4.isHandmade = true;
		v4.rating = 104;

		System.out.println("----- VelvetCandle 4 -----");
		System.out.println("productId: " + v4.productId);
		System.out.println("brandName: " + v4.brandName);
		System.out.println("waxType: " + v4.waxType);
		System.out.println("fragrance: " + v4.fragrance);
		System.out.println("burnTime: " + v4.burnTime);
		System.out.println("price: " + v4.price);
		System.out.println("isScented: " + v4.isScented);
		System.out.println("isAvailable: " + v4.isAvailable);
		System.out.println("manufacturingDate: " + v4.manufacturingDate);
		System.out.println("expiryDate: " + v4.expiryDate);
		System.out.println("color: " + v4.color);
		System.out.println("containerType: " + v4.containerType);
		System.out.println("height: " + v4.height);
		System.out.println("isOrganic: " + v4.isOrganic);
		System.out.println("countryOfOrigin: " + v4.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v4.shelfLifeMonths);
		System.out.println("packagingType: " + v4.packagingType);
		System.out.println("weight: " + v4.weight);
		System.out.println("isSmokeless: " + v4.isSmokeless);
		System.out.println("ingredient1: " + v4.ingredient1);
		System.out.println("ingredient2: " + v4.ingredient2);
		System.out.println("ingredient3: " + v4.ingredient3);
		System.out.println("isDecorative: " + v4.isDecorative);
		System.out.println("isHandmade: " + v4.isHandmade);
		System.out.println("rating: " + v4.rating);


		VelvetCandle v5 = new VelvetCandle();
		v5.productId = 105;
		v5.brandName = "Sample5";
		v5.waxType = "Sample5";
		v5.fragrance = "Sample5";
		v5.burnTime = 15.0;
		v5.price = 15.0;
		v5.isScented = false;
		v5.isAvailable = false;
		v5.manufacturingDate = "Sample5";
		v5.expiryDate = "Sample5";
		v5.color = "Sample5";
		v5.containerType = "Sample5";
		v5.height = 15.0;
		v5.isOrganic = false;
		v5.countryOfOrigin = "Sample5";
		v5.shelfLifeMonths = 105;
		v5.packagingType = "Sample5";
		v5.weight = 15.0;
		v5.isSmokeless = false;
		v5.ingredient1 = "Sample5";
		v5.ingredient2 = "Sample5";
		v5.ingredient3 = "Sample5";
		v5.isDecorative = false;
		v5.isHandmade = false;
		v5.rating = 105;

		System.out.println("----- VelvetCandle 5 -----");
		System.out.println("productId: " + v5.productId);
		System.out.println("brandName: " + v5.brandName);
		System.out.println("waxType: " + v5.waxType);
		System.out.println("fragrance: " + v5.fragrance);
		System.out.println("burnTime: " + v5.burnTime);
		System.out.println("price: " + v5.price);
		System.out.println("isScented: " + v5.isScented);
		System.out.println("isAvailable: " + v5.isAvailable);
		System.out.println("manufacturingDate: " + v5.manufacturingDate);
		System.out.println("expiryDate: " + v5.expiryDate);
		System.out.println("color: " + v5.color);
		System.out.println("containerType: " + v5.containerType);
		System.out.println("height: " + v5.height);
		System.out.println("isOrganic: " + v5.isOrganic);
		System.out.println("countryOfOrigin: " + v5.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v5.shelfLifeMonths);
		System.out.println("packagingType: " + v5.packagingType);
		System.out.println("weight: " + v5.weight);
		System.out.println("isSmokeless: " + v5.isSmokeless);
		System.out.println("ingredient1: " + v5.ingredient1);
		System.out.println("ingredient2: " + v5.ingredient2);
		System.out.println("ingredient3: " + v5.ingredient3);
		System.out.println("isDecorative: " + v5.isDecorative);
		System.out.println("isHandmade: " + v5.isHandmade);
		System.out.println("rating: " + v5.rating);


		VelvetCandle v6 = new VelvetCandle();
		v6.productId = 106;
		v6.brandName = "Sample6";
		v6.waxType = "Sample6";
		v6.fragrance = "Sample6";
		v6.burnTime = 16.0;
		v6.price = 16.0;
		v6.isScented = true;
		v6.isAvailable = true;
		v6.manufacturingDate = "Sample6";
		v6.expiryDate = "Sample6";
		v6.color = "Sample6";
		v6.containerType = "Sample6";
		v6.height = 16.0;
		v6.isOrganic = true;
		v6.countryOfOrigin = "Sample6";
		v6.shelfLifeMonths = 106;
		v6.packagingType = "Sample6";
		v6.weight = 16.0;
		v6.isSmokeless = true;
		v6.ingredient1 = "Sample6";
		v6.ingredient2 = "Sample6";
		v6.ingredient3 = "Sample6";
		v6.isDecorative = true;
		v6.isHandmade = true;
		v6.rating = 106;

		System.out.println("----- VelvetCandle 6 -----");
		System.out.println("productId: " + v6.productId);
		System.out.println("brandName: " + v6.brandName);
		System.out.println("waxType: " + v6.waxType);
		System.out.println("fragrance: " + v6.fragrance);
		System.out.println("burnTime: " + v6.burnTime);
		System.out.println("price: " + v6.price);
		System.out.println("isScented: " + v6.isScented);
		System.out.println("isAvailable: " + v6.isAvailable);
		System.out.println("manufacturingDate: " + v6.manufacturingDate);
		System.out.println("expiryDate: " + v6.expiryDate);
		System.out.println("color: " + v6.color);
		System.out.println("containerType: " + v6.containerType);
		System.out.println("height: " + v6.height);
		System.out.println("isOrganic: " + v6.isOrganic);
		System.out.println("countryOfOrigin: " + v6.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v6.shelfLifeMonths);
		System.out.println("packagingType: " + v6.packagingType);
		System.out.println("weight: " + v6.weight);
		System.out.println("isSmokeless: " + v6.isSmokeless);
		System.out.println("ingredient1: " + v6.ingredient1);
		System.out.println("ingredient2: " + v6.ingredient2);
		System.out.println("ingredient3: " + v6.ingredient3);
		System.out.println("isDecorative: " + v6.isDecorative);
		System.out.println("isHandmade: " + v6.isHandmade);
		System.out.println("rating: " + v6.rating);


		VelvetCandle v7 = new VelvetCandle();
		v7.productId = 107;
		v7.brandName = "Sample7";
		v7.waxType = "Sample7";
		v7.fragrance = "Sample7";
		v7.burnTime = 17.0;
		v7.price = 17.0;
		v7.isScented = false;
		v7.isAvailable = false;
		v7.manufacturingDate = "Sample7";
		v7.expiryDate = "Sample7";
		v7.color = "Sample7";
		v7.containerType = "Sample7";
		v7.height = 17.0;
		v7.isOrganic = false;
		v7.countryOfOrigin = "Sample7";
		v7.shelfLifeMonths = 107;
		v7.packagingType = "Sample7";
		v7.weight = 17.0;
		v7.isSmokeless = false;
		v7.ingredient1 = "Sample7";
		v7.ingredient2 = "Sample7";
		v7.ingredient3 = "Sample7";
		v7.isDecorative = false;
		v7.isHandmade = false;
		v7.rating = 107;

		System.out.println("----- VelvetCandle 7 -----");
		System.out.println("productId: " + v7.productId);
		System.out.println("brandName: " + v7.brandName);
		System.out.println("waxType: " + v7.waxType);
		System.out.println("fragrance: " + v7.fragrance);
		System.out.println("burnTime: " + v7.burnTime);
		System.out.println("price: " + v7.price);
		System.out.println("isScented: " + v7.isScented);
		System.out.println("isAvailable: " + v7.isAvailable);
		System.out.println("manufacturingDate: " + v7.manufacturingDate);
		System.out.println("expiryDate: " + v7.expiryDate);
		System.out.println("color: " + v7.color);
		System.out.println("containerType: " + v7.containerType);
		System.out.println("height: " + v7.height);
		System.out.println("isOrganic: " + v7.isOrganic);
		System.out.println("countryOfOrigin: " + v7.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v7.shelfLifeMonths);
		System.out.println("packagingType: " + v7.packagingType);
		System.out.println("weight: " + v7.weight);
		System.out.println("isSmokeless: " + v7.isSmokeless);
		System.out.println("ingredient1: " + v7.ingredient1);
		System.out.println("ingredient2: " + v7.ingredient2);
		System.out.println("ingredient3: " + v7.ingredient3);
		System.out.println("isDecorative: " + v7.isDecorative);
		System.out.println("isHandmade: " + v7.isHandmade);
		System.out.println("rating: " + v7.rating);


		VelvetCandle v8 = new VelvetCandle();
		v8.productId = 108;
		v8.brandName = "Sample8";
		v8.waxType = "Sample8";
		v8.fragrance = "Sample8";
		v8.burnTime = 18.0;
		v8.price = 18.0;
		v8.isScented = true;
		v8.isAvailable = true;
		v8.manufacturingDate = "Sample8";
		v8.expiryDate = "Sample8";
		v8.color = "Sample8";
		v8.containerType = "Sample8";
		v8.height = 18.0;
		v8.isOrganic = true;
		v8.countryOfOrigin = "Sample8";
		v8.shelfLifeMonths = 108;
		v8.packagingType = "Sample8";
		v8.weight = 18.0;
		v8.isSmokeless = true;
		v8.ingredient1 = "Sample8";
		v8.ingredient2 = "Sample8";
		v8.ingredient3 = "Sample8";
		v8.isDecorative = true;
		v8.isHandmade = true;
		v8.rating = 108;

		System.out.println("----- VelvetCandle 8 -----");
		System.out.println("productId: " + v8.productId);
		System.out.println("brandName: " + v8.brandName);
		System.out.println("waxType: " + v8.waxType);
		System.out.println("fragrance: " + v8.fragrance);
		System.out.println("burnTime: " + v8.burnTime);
		System.out.println("price: " + v8.price);
		System.out.println("isScented: " + v8.isScented);
		System.out.println("isAvailable: " + v8.isAvailable);
		System.out.println("manufacturingDate: " + v8.manufacturingDate);
		System.out.println("expiryDate: " + v8.expiryDate);
		System.out.println("color: " + v8.color);
		System.out.println("containerType: " + v8.containerType);
		System.out.println("height: " + v8.height);
		System.out.println("isOrganic: " + v8.isOrganic);
		System.out.println("countryOfOrigin: " + v8.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v8.shelfLifeMonths);
		System.out.println("packagingType: " + v8.packagingType);
		System.out.println("weight: " + v8.weight);
		System.out.println("isSmokeless: " + v8.isSmokeless);
		System.out.println("ingredient1: " + v8.ingredient1);
		System.out.println("ingredient2: " + v8.ingredient2);
		System.out.println("ingredient3: " + v8.ingredient3);
		System.out.println("isDecorative: " + v8.isDecorative);
		System.out.println("isHandmade: " + v8.isHandmade);
		System.out.println("rating: " + v8.rating);


		VelvetCandle v9 = new VelvetCandle();
		v9.productId = 109;
		v9.brandName = "Sample9";
		v9.waxType = "Sample9";
		v9.fragrance = "Sample9";
		v9.burnTime = 19.0;
		v9.price = 19.0;
		v9.isScented = false;
		v9.isAvailable = false;
		v9.manufacturingDate = "Sample9";
		v9.expiryDate = "Sample9";
		v9.color = "Sample9";
		v9.containerType = "Sample9";
		v9.height = 19.0;
		v9.isOrganic = false;
		v9.countryOfOrigin = "Sample9";
		v9.shelfLifeMonths = 109;
		v9.packagingType = "Sample9";
		v9.weight = 19.0;
		v9.isSmokeless = false;
		v9.ingredient1 = "Sample9";
		v9.ingredient2 = "Sample9";
		v9.ingredient3 = "Sample9";
		v9.isDecorative = false;
		v9.isHandmade = false;
		v9.rating = 109;

		System.out.println("----- VelvetCandle 9 -----");
		System.out.println("productId: " + v9.productId);
		System.out.println("brandName: " + v9.brandName);
		System.out.println("waxType: " + v9.waxType);
		System.out.println("fragrance: " + v9.fragrance);
		System.out.println("burnTime: " + v9.burnTime);
		System.out.println("price: " + v9.price);
		System.out.println("isScented: " + v9.isScented);
		System.out.println("isAvailable: " + v9.isAvailable);
		System.out.println("manufacturingDate: " + v9.manufacturingDate);
		System.out.println("expiryDate: " + v9.expiryDate);
		System.out.println("color: " + v9.color);
		System.out.println("containerType: " + v9.containerType);
		System.out.println("height: " + v9.height);
		System.out.println("isOrganic: " + v9.isOrganic);
		System.out.println("countryOfOrigin: " + v9.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v9.shelfLifeMonths);
		System.out.println("packagingType: " + v9.packagingType);
		System.out.println("weight: " + v9.weight);
		System.out.println("isSmokeless: " + v9.isSmokeless);
		System.out.println("ingredient1: " + v9.ingredient1);
		System.out.println("ingredient2: " + v9.ingredient2);
		System.out.println("ingredient3: " + v9.ingredient3);
		System.out.println("isDecorative: " + v9.isDecorative);
		System.out.println("isHandmade: " + v9.isHandmade);
		System.out.println("rating: " + v9.rating);


		VelvetCandle v10 = new VelvetCandle();
		v10.productId = 110;
		v10.brandName = "Sample10";
		v10.waxType = "Sample10";
		v10.fragrance = "Sample10";
		v10.burnTime = 20.0;
		v10.price = 20.0;
		v10.isScented = true;
		v10.isAvailable = true;
		v10.manufacturingDate = "Sample10";
		v10.expiryDate = "Sample10";
		v10.color = "Sample10";
		v10.containerType = "Sample10";
		v10.height = 20.0;
		v10.isOrganic = true;
		v10.countryOfOrigin = "Sample10";
		v10.shelfLifeMonths = 110;
		v10.packagingType = "Sample10";
		v10.weight = 20.0;
		v10.isSmokeless = true;
		v10.ingredient1 = "Sample10";
		v10.ingredient2 = "Sample10";
		v10.ingredient3 = "Sample10";
		v10.isDecorative = true;
		v10.isHandmade = true;
		v10.rating = 110;

		System.out.println("----- VelvetCandle 10 -----");
		System.out.println("productId: " + v10.productId);
		System.out.println("brandName: " + v10.brandName);
		System.out.println("waxType: " + v10.waxType);
		System.out.println("fragrance: " + v10.fragrance);
		System.out.println("burnTime: " + v10.burnTime);
		System.out.println("price: " + v10.price);
		System.out.println("isScented: " + v10.isScented);
		System.out.println("isAvailable: " + v10.isAvailable);
		System.out.println("manufacturingDate: " + v10.manufacturingDate);
		System.out.println("expiryDate: " + v10.expiryDate);
		System.out.println("color: " + v10.color);
		System.out.println("containerType: " + v10.containerType);
		System.out.println("height: " + v10.height);
		System.out.println("isOrganic: " + v10.isOrganic);
		System.out.println("countryOfOrigin: " + v10.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v10.shelfLifeMonths);
		System.out.println("packagingType: " + v10.packagingType);
		System.out.println("weight: " + v10.weight);
		System.out.println("isSmokeless: " + v10.isSmokeless);
		System.out.println("ingredient1: " + v10.ingredient1);
		System.out.println("ingredient2: " + v10.ingredient2);
		System.out.println("ingredient3: " + v10.ingredient3);
		System.out.println("isDecorative: " + v10.isDecorative);
		System.out.println("isHandmade: " + v10.isHandmade);
		System.out.println("rating: " + v10.rating);


		VelvetCandle v11 = new VelvetCandle();
		v11.productId = 111;
		v11.brandName = "Sample11";
		v11.waxType = "Sample11";
		v11.fragrance = "Sample11";
		v11.burnTime = 21.0;
		v11.price = 21.0;
		v11.isScented = false;
		v11.isAvailable = false;
		v11.manufacturingDate = "Sample11";
		v11.expiryDate = "Sample11";
		v11.color = "Sample11";
		v11.containerType = "Sample11";
		v11.height = 21.0;
		v11.isOrganic = false;
		v11.countryOfOrigin = "Sample11";
		v11.shelfLifeMonths = 111;
		v11.packagingType = "Sample11";
		v11.weight = 21.0;
		v11.isSmokeless = false;
		v11.ingredient1 = "Sample11";
		v11.ingredient2 = "Sample11";
		v11.ingredient3 = "Sample11";
		v11.isDecorative = false;
		v11.isHandmade = false;
		v11.rating = 111;

		System.out.println("----- VelvetCandle 11 -----");
		System.out.println("productId: " + v11.productId);
		System.out.println("brandName: " + v11.brandName);
		System.out.println("waxType: " + v11.waxType);
		System.out.println("fragrance: " + v11.fragrance);
		System.out.println("burnTime: " + v11.burnTime);
		System.out.println("price: " + v11.price);
		System.out.println("isScented: " + v11.isScented);
		System.out.println("isAvailable: " + v11.isAvailable);
		System.out.println("manufacturingDate: " + v11.manufacturingDate);
		System.out.println("expiryDate: " + v11.expiryDate);
		System.out.println("color: " + v11.color);
		System.out.println("containerType: " + v11.containerType);
		System.out.println("height: " + v11.height);
		System.out.println("isOrganic: " + v11.isOrganic);
		System.out.println("countryOfOrigin: " + v11.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v11.shelfLifeMonths);
		System.out.println("packagingType: " + v11.packagingType);
		System.out.println("weight: " + v11.weight);
		System.out.println("isSmokeless: " + v11.isSmokeless);
		System.out.println("ingredient1: " + v11.ingredient1);
		System.out.println("ingredient2: " + v11.ingredient2);
		System.out.println("ingredient3: " + v11.ingredient3);
		System.out.println("isDecorative: " + v11.isDecorative);
		System.out.println("isHandmade: " + v11.isHandmade);
		System.out.println("rating: " + v11.rating);


		VelvetCandle v12 = new VelvetCandle();
		v12.productId = 112;
		v12.brandName = "Sample12";
		v12.waxType = "Sample12";
		v12.fragrance = "Sample12";
		v12.burnTime = 22.0;
		v12.price = 22.0;
		v12.isScented = true;
		v12.isAvailable = true;
		v12.manufacturingDate = "Sample12";
		v12.expiryDate = "Sample12";
		v12.color = "Sample12";
		v12.containerType = "Sample12";
		v12.height = 22.0;
		v12.isOrganic = true;
		v12.countryOfOrigin = "Sample12";
		v12.shelfLifeMonths = 112;
		v12.packagingType = "Sample12";
		v12.weight = 22.0;
		v12.isSmokeless = true;
		v12.ingredient1 = "Sample12";
		v12.ingredient2 = "Sample12";
		v12.ingredient3 = "Sample12";
		v12.isDecorative = true;
		v12.isHandmade = true;
		v12.rating = 112;

		System.out.println("----- VelvetCandle 12 -----");
		System.out.println("productId: " + v12.productId);
		System.out.println("brandName: " + v12.brandName);
		System.out.println("waxType: " + v12.waxType);
		System.out.println("fragrance: " + v12.fragrance);
		System.out.println("burnTime: " + v12.burnTime);
		System.out.println("price: " + v12.price);
		System.out.println("isScented: " + v12.isScented);
		System.out.println("isAvailable: " + v12.isAvailable);
		System.out.println("manufacturingDate: " + v12.manufacturingDate);
		System.out.println("expiryDate: " + v12.expiryDate);
		System.out.println("color: " + v12.color);
		System.out.println("containerType: " + v12.containerType);
		System.out.println("height: " + v12.height);
		System.out.println("isOrganic: " + v12.isOrganic);
		System.out.println("countryOfOrigin: " + v12.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v12.shelfLifeMonths);
		System.out.println("packagingType: " + v12.packagingType);
		System.out.println("weight: " + v12.weight);
		System.out.println("isSmokeless: " + v12.isSmokeless);
		System.out.println("ingredient1: " + v12.ingredient1);
		System.out.println("ingredient2: " + v12.ingredient2);
		System.out.println("ingredient3: " + v12.ingredient3);
		System.out.println("isDecorative: " + v12.isDecorative);
		System.out.println("isHandmade: " + v12.isHandmade);
		System.out.println("rating: " + v12.rating);


		VelvetCandle v13 = new VelvetCandle();
		v13.productId = 113;
		v13.brandName = "Sample13";
		v13.waxType = "Sample13";
		v13.fragrance = "Sample13";
		v13.burnTime = 23.0;
		v13.price = 23.0;
		v13.isScented = false;
		v13.isAvailable = false;
		v13.manufacturingDate = "Sample13";
		v13.expiryDate = "Sample13";
		v13.color = "Sample13";
		v13.containerType = "Sample13";
		v13.height = 23.0;
		v13.isOrganic = false;
		v13.countryOfOrigin = "Sample13";
		v13.shelfLifeMonths = 113;
		v13.packagingType = "Sample13";
		v13.weight = 23.0;
		v13.isSmokeless = false;
		v13.ingredient1 = "Sample13";
		v13.ingredient2 = "Sample13";
		v13.ingredient3 = "Sample13";
		v13.isDecorative = false;
		v13.isHandmade = false;
		v13.rating = 113;

		System.out.println("----- VelvetCandle 13 -----");
		System.out.println("productId: " + v13.productId);
		System.out.println("brandName: " + v13.brandName);
		System.out.println("waxType: " + v13.waxType);
		System.out.println("fragrance: " + v13.fragrance);
		System.out.println("burnTime: " + v13.burnTime);
		System.out.println("price: " + v13.price);
		System.out.println("isScented: " + v13.isScented);
		System.out.println("isAvailable: " + v13.isAvailable);
		System.out.println("manufacturingDate: " + v13.manufacturingDate);
		System.out.println("expiryDate: " + v13.expiryDate);
		System.out.println("color: " + v13.color);
		System.out.println("containerType: " + v13.containerType);
		System.out.println("height: " + v13.height);
		System.out.println("isOrganic: " + v13.isOrganic);
		System.out.println("countryOfOrigin: " + v13.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v13.shelfLifeMonths);
		System.out.println("packagingType: " + v13.packagingType);
		System.out.println("weight: " + v13.weight);
		System.out.println("isSmokeless: " + v13.isSmokeless);
		System.out.println("ingredient1: " + v13.ingredient1);
		System.out.println("ingredient2: " + v13.ingredient2);
		System.out.println("ingredient3: " + v13.ingredient3);
		System.out.println("isDecorative: " + v13.isDecorative);
		System.out.println("isHandmade: " + v13.isHandmade);
		System.out.println("rating: " + v13.rating);


		VelvetCandle v14 = new VelvetCandle();
		v14.productId = 114;
		v14.brandName = "Sample14";
		v14.waxType = "Sample14";
		v14.fragrance = "Sample14";
		v14.burnTime = 24.0;
		v14.price = 24.0;
		v14.isScented = true;
		v14.isAvailable = true;
		v14.manufacturingDate = "Sample14";
		v14.expiryDate = "Sample14";
		v14.color = "Sample14";
		v14.containerType = "Sample14";
		v14.height = 24.0;
		v14.isOrganic = true;
		v14.countryOfOrigin = "Sample14";
		v14.shelfLifeMonths = 114;
		v14.packagingType = "Sample14";
		v14.weight = 24.0;
		v14.isSmokeless = true;
		v14.ingredient1 = "Sample14";
		v14.ingredient2 = "Sample14";
		v14.ingredient3 = "Sample14";
		v14.isDecorative = true;
		v14.isHandmade = true;
		v14.rating = 114;

		System.out.println("----- VelvetCandle 14 -----");
		System.out.println("productId: " + v14.productId);
		System.out.println("brandName: " + v14.brandName);
		System.out.println("waxType: " + v14.waxType);
		System.out.println("fragrance: " + v14.fragrance);
		System.out.println("burnTime: " + v14.burnTime);
		System.out.println("price: " + v14.price);
		System.out.println("isScented: " + v14.isScented);
		System.out.println("isAvailable: " + v14.isAvailable);
		System.out.println("manufacturingDate: " + v14.manufacturingDate);
		System.out.println("expiryDate: " + v14.expiryDate);
		System.out.println("color: " + v14.color);
		System.out.println("containerType: " + v14.containerType);
		System.out.println("height: " + v14.height);
		System.out.println("isOrganic: " + v14.isOrganic);
		System.out.println("countryOfOrigin: " + v14.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v14.shelfLifeMonths);
		System.out.println("packagingType: " + v14.packagingType);
		System.out.println("weight: " + v14.weight);
		System.out.println("isSmokeless: " + v14.isSmokeless);
		System.out.println("ingredient1: " + v14.ingredient1);
		System.out.println("ingredient2: " + v14.ingredient2);
		System.out.println("ingredient3: " + v14.ingredient3);
		System.out.println("isDecorative: " + v14.isDecorative);
		System.out.println("isHandmade: " + v14.isHandmade);
		System.out.println("rating: " + v14.rating);


		VelvetCandle v15 = new VelvetCandle();
		v15.productId = 115;
		v15.brandName = "Sample15";
		v15.waxType = "Sample15";
		v15.fragrance = "Sample15";
		v15.burnTime = 25.0;
		v15.price = 25.0;
		v15.isScented = false;
		v15.isAvailable = false;
		v15.manufacturingDate = "Sample15";
		v15.expiryDate = "Sample15";
		v15.color = "Sample15";
		v15.containerType = "Sample15";
		v15.height = 25.0;
		v15.isOrganic = false;
		v15.countryOfOrigin = "Sample15";
		v15.shelfLifeMonths = 115;
		v15.packagingType = "Sample15";
		v15.weight = 25.0;
		v15.isSmokeless = false;
		v15.ingredient1 = "Sample15";
		v15.ingredient2 = "Sample15";
		v15.ingredient3 = "Sample15";
		v15.isDecorative = false;
		v15.isHandmade = false;
		v15.rating = 115;

		System.out.println("----- VelvetCandle 15 -----");
		System.out.println("productId: " + v15.productId);
		System.out.println("brandName: " + v15.brandName);
		System.out.println("waxType: " + v15.waxType);
		System.out.println("fragrance: " + v15.fragrance);
		System.out.println("burnTime: " + v15.burnTime);
		System.out.println("price: " + v15.price);
		System.out.println("isScented: " + v15.isScented);
		System.out.println("isAvailable: " + v15.isAvailable);
		System.out.println("manufacturingDate: " + v15.manufacturingDate);
		System.out.println("expiryDate: " + v15.expiryDate);
		System.out.println("color: " + v15.color);
		System.out.println("containerType: " + v15.containerType);
		System.out.println("height: " + v15.height);
		System.out.println("isOrganic: " + v15.isOrganic);
		System.out.println("countryOfOrigin: " + v15.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v15.shelfLifeMonths);
		System.out.println("packagingType: " + v15.packagingType);
		System.out.println("weight: " + v15.weight);
		System.out.println("isSmokeless: " + v15.isSmokeless);
		System.out.println("ingredient1: " + v15.ingredient1);
		System.out.println("ingredient2: " + v15.ingredient2);
		System.out.println("ingredient3: " + v15.ingredient3);
		System.out.println("isDecorative: " + v15.isDecorative);
		System.out.println("isHandmade: " + v15.isHandmade);
		System.out.println("rating: " + v15.rating);


		VelvetCandle v16 = new VelvetCandle();
		v16.productId = 116;
		v16.brandName = "Sample16";
		v16.waxType = "Sample16";
		v16.fragrance = "Sample16";
		v16.burnTime = 26.0;
		v16.price = 26.0;
		v16.isScented = true;
		v16.isAvailable = true;
		v16.manufacturingDate = "Sample16";
		v16.expiryDate = "Sample16";
		v16.color = "Sample16";
		v16.containerType = "Sample16";
		v16.height = 26.0;
		v16.isOrganic = true;
		v16.countryOfOrigin = "Sample16";
		v16.shelfLifeMonths = 116;
		v16.packagingType = "Sample16";
		v16.weight = 26.0;
		v16.isSmokeless = true;
		v16.ingredient1 = "Sample16";
		v16.ingredient2 = "Sample16";
		v16.ingredient3 = "Sample16";
		v16.isDecorative = true;
		v16.isHandmade = true;
		v16.rating = 116;

		System.out.println("----- VelvetCandle 16 -----");
		System.out.println("productId: " + v16.productId);
		System.out.println("brandName: " + v16.brandName);
		System.out.println("waxType: " + v16.waxType);
		System.out.println("fragrance: " + v16.fragrance);
		System.out.println("burnTime: " + v16.burnTime);
		System.out.println("price: " + v16.price);
		System.out.println("isScented: " + v16.isScented);
		System.out.println("isAvailable: " + v16.isAvailable);
		System.out.println("manufacturingDate: " + v16.manufacturingDate);
		System.out.println("expiryDate: " + v16.expiryDate);
		System.out.println("color: " + v16.color);
		System.out.println("containerType: " + v16.containerType);
		System.out.println("height: " + v16.height);
		System.out.println("isOrganic: " + v16.isOrganic);
		System.out.println("countryOfOrigin: " + v16.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v16.shelfLifeMonths);
		System.out.println("packagingType: " + v16.packagingType);
		System.out.println("weight: " + v16.weight);
		System.out.println("isSmokeless: " + v16.isSmokeless);
		System.out.println("ingredient1: " + v16.ingredient1);
		System.out.println("ingredient2: " + v16.ingredient2);
		System.out.println("ingredient3: " + v16.ingredient3);
		System.out.println("isDecorative: " + v16.isDecorative);
		System.out.println("isHandmade: " + v16.isHandmade);
		System.out.println("rating: " + v16.rating);


		VelvetCandle v17 = new VelvetCandle();
		v17.productId = 117;
		v17.brandName = "Sample17";
		v17.waxType = "Sample17";
		v17.fragrance = "Sample17";
		v17.burnTime = 27.0;
		v17.price = 27.0;
		v17.isScented = false;
		v17.isAvailable = false;
		v17.manufacturingDate = "Sample17";
		v17.expiryDate = "Sample17";
		v17.color = "Sample17";
		v17.containerType = "Sample17";
		v17.height = 27.0;
		v17.isOrganic = false;
		v17.countryOfOrigin = "Sample17";
		v17.shelfLifeMonths = 117;
		v17.packagingType = "Sample17";
		v17.weight = 27.0;
		v17.isSmokeless = false;
		v17.ingredient1 = "Sample17";
		v17.ingredient2 = "Sample17";
		v17.ingredient3 = "Sample17";
		v17.isDecorative = false;
		v17.isHandmade = false;
		v17.rating = 117;

		System.out.println("----- VelvetCandle 17 -----");
		System.out.println("productId: " + v17.productId);
		System.out.println("brandName: " + v17.brandName);
		System.out.println("waxType: " + v17.waxType);
		System.out.println("fragrance: " + v17.fragrance);
		System.out.println("burnTime: " + v17.burnTime);
		System.out.println("price: " + v17.price);
		System.out.println("isScented: " + v17.isScented);
		System.out.println("isAvailable: " + v17.isAvailable);
		System.out.println("manufacturingDate: " + v17.manufacturingDate);
		System.out.println("expiryDate: " + v17.expiryDate);
		System.out.println("color: " + v17.color);
		System.out.println("containerType: " + v17.containerType);
		System.out.println("height: " + v17.height);
		System.out.println("isOrganic: " + v17.isOrganic);
		System.out.println("countryOfOrigin: " + v17.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v17.shelfLifeMonths);
		System.out.println("packagingType: " + v17.packagingType);
		System.out.println("weight: " + v17.weight);
		System.out.println("isSmokeless: " + v17.isSmokeless);
		System.out.println("ingredient1: " + v17.ingredient1);
		System.out.println("ingredient2: " + v17.ingredient2);
		System.out.println("ingredient3: " + v17.ingredient3);
		System.out.println("isDecorative: " + v17.isDecorative);
		System.out.println("isHandmade: " + v17.isHandmade);
		System.out.println("rating: " + v17.rating);


		VelvetCandle v18 = new VelvetCandle();
		v18.productId = 118;
		v18.brandName = "Sample18";
		v18.waxType = "Sample18";
		v18.fragrance = "Sample18";
		v18.burnTime = 28.0;
		v18.price = 28.0;
		v18.isScented = true;
		v18.isAvailable = true;
		v18.manufacturingDate = "Sample18";
		v18.expiryDate = "Sample18";
		v18.color = "Sample18";
		v18.containerType = "Sample18";
		v18.height = 28.0;
		v18.isOrganic = true;
		v18.countryOfOrigin = "Sample18";
		v18.shelfLifeMonths = 118;
		v18.packagingType = "Sample18";
		v18.weight = 28.0;
		v18.isSmokeless = true;
		v18.ingredient1 = "Sample18";
		v18.ingredient2 = "Sample18";
		v18.ingredient3 = "Sample18";
		v18.isDecorative = true;
		v18.isHandmade = true;
		v18.rating = 118;

		System.out.println("----- VelvetCandle 18 -----");
		System.out.println("productId: " + v18.productId);
		System.out.println("brandName: " + v18.brandName);
		System.out.println("waxType: " + v18.waxType);
		System.out.println("fragrance: " + v18.fragrance);
		System.out.println("burnTime: " + v18.burnTime);
		System.out.println("price: " + v18.price);
		System.out.println("isScented: " + v18.isScented);
		System.out.println("isAvailable: " + v18.isAvailable);
		System.out.println("manufacturingDate: " + v18.manufacturingDate);
		System.out.println("expiryDate: " + v18.expiryDate);
		System.out.println("color: " + v18.color);
		System.out.println("containerType: " + v18.containerType);
		System.out.println("height: " + v18.height);
		System.out.println("isOrganic: " + v18.isOrganic);
		System.out.println("countryOfOrigin: " + v18.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v18.shelfLifeMonths);
		System.out.println("packagingType: " + v18.packagingType);
		System.out.println("weight: " + v18.weight);
		System.out.println("isSmokeless: " + v18.isSmokeless);
		System.out.println("ingredient1: " + v18.ingredient1);
		System.out.println("ingredient2: " + v18.ingredient2);
		System.out.println("ingredient3: " + v18.ingredient3);
		System.out.println("isDecorative: " + v18.isDecorative);
		System.out.println("isHandmade: " + v18.isHandmade);
		System.out.println("rating: " + v18.rating);


		VelvetCandle v19 = new VelvetCandle();
		v19.productId = 119;
		v19.brandName = "Sample19";
		v19.waxType = "Sample19";
		v19.fragrance = "Sample19";
		v19.burnTime = 29.0;
		v19.price = 29.0;
		v19.isScented = false;
		v19.isAvailable = false;
		v19.manufacturingDate = "Sample19";
		v19.expiryDate = "Sample19";
		v19.color = "Sample19";
		v19.containerType = "Sample19";
		v19.height = 29.0;
		v19.isOrganic = false;
		v19.countryOfOrigin = "Sample19";
		v19.shelfLifeMonths = 119;
		v19.packagingType = "Sample19";
		v19.weight = 29.0;
		v19.isSmokeless = false;
		v19.ingredient1 = "Sample19";
		v19.ingredient2 = "Sample19";
		v19.ingredient3 = "Sample19";
		v19.isDecorative = false;
		v19.isHandmade = false;
		v19.rating = 119;

		System.out.println("----- VelvetCandle 19 -----");
		System.out.println("productId: " + v19.productId);
		System.out.println("brandName: " + v19.brandName);
		System.out.println("waxType: " + v19.waxType);
		System.out.println("fragrance: " + v19.fragrance);
		System.out.println("burnTime: " + v19.burnTime);
		System.out.println("price: " + v19.price);
		System.out.println("isScented: " + v19.isScented);
		System.out.println("isAvailable: " + v19.isAvailable);
		System.out.println("manufacturingDate: " + v19.manufacturingDate);
		System.out.println("expiryDate: " + v19.expiryDate);
		System.out.println("color: " + v19.color);
		System.out.println("containerType: " + v19.containerType);
		System.out.println("height: " + v19.height);
		System.out.println("isOrganic: " + v19.isOrganic);
		System.out.println("countryOfOrigin: " + v19.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v19.shelfLifeMonths);
		System.out.println("packagingType: " + v19.packagingType);
		System.out.println("weight: " + v19.weight);
		System.out.println("isSmokeless: " + v19.isSmokeless);
		System.out.println("ingredient1: " + v19.ingredient1);
		System.out.println("ingredient2: " + v19.ingredient2);
		System.out.println("ingredient3: " + v19.ingredient3);
		System.out.println("isDecorative: " + v19.isDecorative);
		System.out.println("isHandmade: " + v19.isHandmade);
		System.out.println("rating: " + v19.rating);


		VelvetCandle v20 = new VelvetCandle();
		v20.productId = 120;
		v20.brandName = "Sample20";
		v20.waxType = "Sample20";
		v20.fragrance = "Sample20";
		v20.burnTime = 30.0;
		v20.price = 30.0;
		v20.isScented = true;
		v20.isAvailable = true;
		v20.manufacturingDate = "Sample20";
		v20.expiryDate = "Sample20";
		v20.color = "Sample20";
		v20.containerType = "Sample20";
		v20.height = 30.0;
		v20.isOrganic = true;
		v20.countryOfOrigin = "Sample20";
		v20.shelfLifeMonths = 120;
		v20.packagingType = "Sample20";
		v20.weight = 30.0;
		v20.isSmokeless = true;
		v20.ingredient1 = "Sample20";
		v20.ingredient2 = "Sample20";
		v20.ingredient3 = "Sample20";
		v20.isDecorative = true;
		v20.isHandmade = true;
		v20.rating = 120;

		System.out.println("----- VelvetCandle 20 -----");
		System.out.println("productId: " + v20.productId);
		System.out.println("brandName: " + v20.brandName);
		System.out.println("waxType: " + v20.waxType);
		System.out.println("fragrance: " + v20.fragrance);
		System.out.println("burnTime: " + v20.burnTime);
		System.out.println("price: " + v20.price);
		System.out.println("isScented: " + v20.isScented);
		System.out.println("isAvailable: " + v20.isAvailable);
		System.out.println("manufacturingDate: " + v20.manufacturingDate);
		System.out.println("expiryDate: " + v20.expiryDate);
		System.out.println("color: " + v20.color);
		System.out.println("containerType: " + v20.containerType);
		System.out.println("height: " + v20.height);
		System.out.println("isOrganic: " + v20.isOrganic);
		System.out.println("countryOfOrigin: " + v20.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v20.shelfLifeMonths);
		System.out.println("packagingType: " + v20.packagingType);
		System.out.println("weight: " + v20.weight);
		System.out.println("isSmokeless: " + v20.isSmokeless);
		System.out.println("ingredient1: " + v20.ingredient1);
		System.out.println("ingredient2: " + v20.ingredient2);
		System.out.println("ingredient3: " + v20.ingredient3);
		System.out.println("isDecorative: " + v20.isDecorative);
		System.out.println("isHandmade: " + v20.isHandmade);
		System.out.println("rating: " + v20.rating);


		VelvetCandle v21 = new VelvetCandle();
		v21.productId = 121;
		v21.brandName = "Sample21";
		v21.waxType = "Sample21";
		v21.fragrance = "Sample21";
		v21.burnTime = 31.0;
		v21.price = 31.0;
		v21.isScented = false;
		v21.isAvailable = false;
		v21.manufacturingDate = "Sample21";
		v21.expiryDate = "Sample21";
		v21.color = "Sample21";
		v21.containerType = "Sample21";
		v21.height = 31.0;
		v21.isOrganic = false;
		v21.countryOfOrigin = "Sample21";
		v21.shelfLifeMonths = 121;
		v21.packagingType = "Sample21";
		v21.weight = 31.0;
		v21.isSmokeless = false;
		v21.ingredient1 = "Sample21";
		v21.ingredient2 = "Sample21";
		v21.ingredient3 = "Sample21";
		v21.isDecorative = false;
		v21.isHandmade = false;
		v21.rating = 121;

		System.out.println("----- VelvetCandle 21 -----");
		System.out.println("productId: " + v21.productId);
		System.out.println("brandName: " + v21.brandName);
		System.out.println("waxType: " + v21.waxType);
		System.out.println("fragrance: " + v21.fragrance);
		System.out.println("burnTime: " + v21.burnTime);
		System.out.println("price: " + v21.price);
		System.out.println("isScented: " + v21.isScented);
		System.out.println("isAvailable: " + v21.isAvailable);
		System.out.println("manufacturingDate: " + v21.manufacturingDate);
		System.out.println("expiryDate: " + v21.expiryDate);
		System.out.println("color: " + v21.color);
		System.out.println("containerType: " + v21.containerType);
		System.out.println("height: " + v21.height);
		System.out.println("isOrganic: " + v21.isOrganic);
		System.out.println("countryOfOrigin: " + v21.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v21.shelfLifeMonths);
		System.out.println("packagingType: " + v21.packagingType);
		System.out.println("weight: " + v21.weight);
		System.out.println("isSmokeless: " + v21.isSmokeless);
		System.out.println("ingredient1: " + v21.ingredient1);
		System.out.println("ingredient2: " + v21.ingredient2);
		System.out.println("ingredient3: " + v21.ingredient3);
		System.out.println("isDecorative: " + v21.isDecorative);
		System.out.println("isHandmade: " + v21.isHandmade);
		System.out.println("rating: " + v21.rating);


		VelvetCandle v22 = new VelvetCandle();
		v22.productId = 122;
		v22.brandName = "Sample22";
		v22.waxType = "Sample22";
		v22.fragrance = "Sample22";
		v22.burnTime = 32.0;
		v22.price = 32.0;
		v22.isScented = true;
		v22.isAvailable = true;
		v22.manufacturingDate = "Sample22";
		v22.expiryDate = "Sample22";
		v22.color = "Sample22";
		v22.containerType = "Sample22";
		v22.height = 32.0;
		v22.isOrganic = true;
		v22.countryOfOrigin = "Sample22";
		v22.shelfLifeMonths = 122;
		v22.packagingType = "Sample22";
		v22.weight = 32.0;
		v22.isSmokeless = true;
		v22.ingredient1 = "Sample22";
		v22.ingredient2 = "Sample22";
		v22.ingredient3 = "Sample22";
		v22.isDecorative = true;
		v22.isHandmade = true;
		v22.rating = 122;

		System.out.println("----- VelvetCandle 22 -----");
		System.out.println("productId: " + v22.productId);
		System.out.println("brandName: " + v22.brandName);
		System.out.println("waxType: " + v22.waxType);
		System.out.println("fragrance: " + v22.fragrance);
		System.out.println("burnTime: " + v22.burnTime);
		System.out.println("price: " + v22.price);
		System.out.println("isScented: " + v22.isScented);
		System.out.println("isAvailable: " + v22.isAvailable);
		System.out.println("manufacturingDate: " + v22.manufacturingDate);
		System.out.println("expiryDate: " + v22.expiryDate);
		System.out.println("color: " + v22.color);
		System.out.println("containerType: " + v22.containerType);
		System.out.println("height: " + v22.height);
		System.out.println("isOrganic: " + v22.isOrganic);
		System.out.println("countryOfOrigin: " + v22.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v22.shelfLifeMonths);
		System.out.println("packagingType: " + v22.packagingType);
		System.out.println("weight: " + v22.weight);
		System.out.println("isSmokeless: " + v22.isSmokeless);
		System.out.println("ingredient1: " + v22.ingredient1);
		System.out.println("ingredient2: " + v22.ingredient2);
		System.out.println("ingredient3: " + v22.ingredient3);
		System.out.println("isDecorative: " + v22.isDecorative);
		System.out.println("isHandmade: " + v22.isHandmade);
		System.out.println("rating: " + v22.rating);


		VelvetCandle v23 = new VelvetCandle();
		v23.productId = 123;
		v23.brandName = "Sample23";
		v23.waxType = "Sample23";
		v23.fragrance = "Sample23";
		v23.burnTime = 33.0;
		v23.price = 33.0;
		v23.isScented = false;
		v23.isAvailable = false;
		v23.manufacturingDate = "Sample23";
		v23.expiryDate = "Sample23";
		v23.color = "Sample23";
		v23.containerType = "Sample23";
		v23.height = 33.0;
		v23.isOrganic = false;
		v23.countryOfOrigin = "Sample23";
		v23.shelfLifeMonths = 123;
		v23.packagingType = "Sample23";
		v23.weight = 33.0;
		v23.isSmokeless = false;
		v23.ingredient1 = "Sample23";
		v23.ingredient2 = "Sample23";
		v23.ingredient3 = "Sample23";
		v23.isDecorative = false;
		v23.isHandmade = false;
		v23.rating = 123;

		System.out.println("----- VelvetCandle 23 -----");
		System.out.println("productId: " + v23.productId);
		System.out.println("brandName: " + v23.brandName);
		System.out.println("waxType: " + v23.waxType);
		System.out.println("fragrance: " + v23.fragrance);
		System.out.println("burnTime: " + v23.burnTime);
		System.out.println("price: " + v23.price);
		System.out.println("isScented: " + v23.isScented);
		System.out.println("isAvailable: " + v23.isAvailable);
		System.out.println("manufacturingDate: " + v23.manufacturingDate);
		System.out.println("expiryDate: " + v23.expiryDate);
		System.out.println("color: " + v23.color);
		System.out.println("containerType: " + v23.containerType);
		System.out.println("height: " + v23.height);
		System.out.println("isOrganic: " + v23.isOrganic);
		System.out.println("countryOfOrigin: " + v23.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v23.shelfLifeMonths);
		System.out.println("packagingType: " + v23.packagingType);
		System.out.println("weight: " + v23.weight);
		System.out.println("isSmokeless: " + v23.isSmokeless);
		System.out.println("ingredient1: " + v23.ingredient1);
		System.out.println("ingredient2: " + v23.ingredient2);
		System.out.println("ingredient3: " + v23.ingredient3);
		System.out.println("isDecorative: " + v23.isDecorative);
		System.out.println("isHandmade: " + v23.isHandmade);
		System.out.println("rating: " + v23.rating);


		VelvetCandle v24 = new VelvetCandle();
		v24.productId = 124;
		v24.brandName = "Sample24";
		v24.waxType = "Sample24";
		v24.fragrance = "Sample24";
		v24.burnTime = 34.0;
		v24.price = 34.0;
		v24.isScented = true;
		v24.isAvailable = true;
		v24.manufacturingDate = "Sample24";
		v24.expiryDate = "Sample24";
		v24.color = "Sample24";
		v24.containerType = "Sample24";
		v24.height = 34.0;
		v24.isOrganic = true;
		v24.countryOfOrigin = "Sample24";
		v24.shelfLifeMonths = 124;
		v24.packagingType = "Sample24";
		v24.weight = 34.0;
		v24.isSmokeless = true;
		v24.ingredient1 = "Sample24";
		v24.ingredient2 = "Sample24";
		v24.ingredient3 = "Sample24";
		v24.isDecorative = true;
		v24.isHandmade = true;
		v24.rating = 124;

		System.out.println("----- VelvetCandle 24 -----");
		System.out.println("productId: " + v24.productId);
		System.out.println("brandName: " + v24.brandName);
		System.out.println("waxType: " + v24.waxType);
		System.out.println("fragrance: " + v24.fragrance);
		System.out.println("burnTime: " + v24.burnTime);
		System.out.println("price: " + v24.price);
		System.out.println("isScented: " + v24.isScented);
		System.out.println("isAvailable: " + v24.isAvailable);
		System.out.println("manufacturingDate: " + v24.manufacturingDate);
		System.out.println("expiryDate: " + v24.expiryDate);
		System.out.println("color: " + v24.color);
		System.out.println("containerType: " + v24.containerType);
		System.out.println("height: " + v24.height);
		System.out.println("isOrganic: " + v24.isOrganic);
		System.out.println("countryOfOrigin: " + v24.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v24.shelfLifeMonths);
		System.out.println("packagingType: " + v24.packagingType);
		System.out.println("weight: " + v24.weight);
		System.out.println("isSmokeless: " + v24.isSmokeless);
		System.out.println("ingredient1: " + v24.ingredient1);
		System.out.println("ingredient2: " + v24.ingredient2);
		System.out.println("ingredient3: " + v24.ingredient3);
		System.out.println("isDecorative: " + v24.isDecorative);
		System.out.println("isHandmade: " + v24.isHandmade);
		System.out.println("rating: " + v24.rating);


		VelvetCandle v25 = new VelvetCandle();
		v25.productId = 125;
		v25.brandName = "Sample25";
		v25.waxType = "Sample25";
		v25.fragrance = "Sample25";
		v25.burnTime = 35.0;
		v25.price = 35.0;
		v25.isScented = false;
		v25.isAvailable = false;
		v25.manufacturingDate = "Sample25";
		v25.expiryDate = "Sample25";
		v25.color = "Sample25";
		v25.containerType = "Sample25";
		v25.height = 35.0;
		v25.isOrganic = false;
		v25.countryOfOrigin = "Sample25";
		v25.shelfLifeMonths = 125;
		v25.packagingType = "Sample25";
		v25.weight = 35.0;
		v25.isSmokeless = false;
		v25.ingredient1 = "Sample25";
		v25.ingredient2 = "Sample25";
		v25.ingredient3 = "Sample25";
		v25.isDecorative = false;
		v25.isHandmade = false;
		v25.rating = 125;

		System.out.println("----- VelvetCandle 25 -----");
		System.out.println("productId: " + v25.productId);
		System.out.println("brandName: " + v25.brandName);
		System.out.println("waxType: " + v25.waxType);
		System.out.println("fragrance: " + v25.fragrance);
		System.out.println("burnTime: " + v25.burnTime);
		System.out.println("price: " + v25.price);
		System.out.println("isScented: " + v25.isScented);
		System.out.println("isAvailable: " + v25.isAvailable);
		System.out.println("manufacturingDate: " + v25.manufacturingDate);
		System.out.println("expiryDate: " + v25.expiryDate);
		System.out.println("color: " + v25.color);
		System.out.println("containerType: " + v25.containerType);
		System.out.println("height: " + v25.height);
		System.out.println("isOrganic: " + v25.isOrganic);
		System.out.println("countryOfOrigin: " + v25.countryOfOrigin);
		System.out.println("shelfLifeMonths: " + v25.shelfLifeMonths);
		System.out.println("packagingType: " + v25.packagingType);
		System.out.println("weight: " + v25.weight);
		System.out.println("isSmokeless: " + v25.isSmokeless);
		System.out.println("ingredient1: " + v25.ingredient1);
		System.out.println("ingredient2: " + v25.ingredient2);
		System.out.println("ingredient3: " + v25.ingredient3);
		System.out.println("isDecorative: " + v25.isDecorative);
		System.out.println("isHandmade: " + v25.isHandmade);
		System.out.println("rating: " + v25.rating);


	}
}

	