class ZenNotebookRunner {
	public static void main(String[] args) {

		ZenNotebook z1 = new ZenNotebook();
		z1.productId = 101;
		z1.brandName = "Sample1";
		z1.paperType = "Sample1";
		z1.color = "Sample1";
		z1.pageCount = 11.0;
		z1.price = 11.0;
		z1.isHardCover = false;
		z1.isAvailable = false;
		z1.manufacturingDate = "Sample1";
		z1.expiryDate = "Sample1";
		z1.bindingType = "Sample1";
		z1.size = "Sample1";
		z1.weight = 11.0;
		z1.isEcoFriendly = false;
		z1.countryOfOrigin = "Sample1";
		z1.warrantyMonths = 101;
		z1.packagingType = "Sample1";
		z1.thickness = 11.0;
		z1.isRecyclable = false;
		z1.feature1 = "Sample1";
		z1.feature2 = "Sample1";
		z1.feature3 = "Sample1";
		z1.hasBookmark = false;
		z1.hasElasticBand = false;
		z1.rating = 101;

		System.out.println("----- ZenNotebook 1 -----");
		System.out.println("productId: " + z1.productId);
		System.out.println("brandName: " + z1.brandName);
		System.out.println("paperType: " + z1.paperType);
		System.out.println("color: " + z1.color);
		System.out.println("pageCount: " + z1.pageCount);
		System.out.println("price: " + z1.price);
		System.out.println("isHardCover: " + z1.isHardCover);
		System.out.println("isAvailable: " + z1.isAvailable);
		System.out.println("manufacturingDate: " + z1.manufacturingDate);
		System.out.println("expiryDate: " + z1.expiryDate);
		System.out.println("bindingType: " + z1.bindingType);
		System.out.println("size: " + z1.size);
		System.out.println("weight: " + z1.weight);
		System.out.println("isEcoFriendly: " + z1.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z1.countryOfOrigin);
		System.out.println("warrantyMonths: " + z1.warrantyMonths);
		System.out.println("packagingType: " + z1.packagingType);
		System.out.println("thickness: " + z1.thickness);
		System.out.println("isRecyclable: " + z1.isRecyclable);
		System.out.println("feature1: " + z1.feature1);
		System.out.println("feature2: " + z1.feature2);
		System.out.println("feature3: " + z1.feature3);
		System.out.println("hasBookmark: " + z1.hasBookmark);
		System.out.println("hasElasticBand: " + z1.hasElasticBand);
		System.out.println("rating: " + z1.rating);


		ZenNotebook z2 = new ZenNotebook();
		z2.productId = 102;
		z2.brandName = "Sample2";
		z2.paperType = "Sample2";
		z2.color = "Sample2";
		z2.pageCount = 12.0;
		z2.price = 12.0;
		z2.isHardCover = true;
		z2.isAvailable = true;
		z2.manufacturingDate = "Sample2";
		z2.expiryDate = "Sample2";
		z2.bindingType = "Sample2";
		z2.size = "Sample2";
		z2.weight = 12.0;
		z2.isEcoFriendly = true;
		z2.countryOfOrigin = "Sample2";
		z2.warrantyMonths = 102;
		z2.packagingType = "Sample2";
		z2.thickness = 12.0;
		z2.isRecyclable = true;
		z2.feature1 = "Sample2";
		z2.feature2 = "Sample2";
		z2.feature3 = "Sample2";
		z2.hasBookmark = true;
		z2.hasElasticBand = true;
		z2.rating = 102;

		System.out.println("----- ZenNotebook 2 -----");
		System.out.println("productId: " + z2.productId);
		System.out.println("brandName: " + z2.brandName);
		System.out.println("paperType: " + z2.paperType);
		System.out.println("color: " + z2.color);
		System.out.println("pageCount: " + z2.pageCount);
		System.out.println("price: " + z2.price);
		System.out.println("isHardCover: " + z2.isHardCover);
		System.out.println("isAvailable: " + z2.isAvailable);
		System.out.println("manufacturingDate: " + z2.manufacturingDate);
		System.out.println("expiryDate: " + z2.expiryDate);
		System.out.println("bindingType: " + z2.bindingType);
		System.out.println("size: " + z2.size);
		System.out.println("weight: " + z2.weight);
		System.out.println("isEcoFriendly: " + z2.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z2.countryOfOrigin);
		System.out.println("warrantyMonths: " + z2.warrantyMonths);
		System.out.println("packagingType: " + z2.packagingType);
		System.out.println("thickness: " + z2.thickness);
		System.out.println("isRecyclable: " + z2.isRecyclable);
		System.out.println("feature1: " + z2.feature1);
		System.out.println("feature2: " + z2.feature2);
		System.out.println("feature3: " + z2.feature3);
		System.out.println("hasBookmark: " + z2.hasBookmark);
		System.out.println("hasElasticBand: " + z2.hasElasticBand);
		System.out.println("rating: " + z2.rating);


		ZenNotebook z3 = new ZenNotebook();
		z3.productId = 103;
		z3.brandName = "Sample3";
		z3.paperType = "Sample3";
		z3.color = "Sample3";
		z3.pageCount = 13.0;
		z3.price = 13.0;
		z3.isHardCover = false;
		z3.isAvailable = false;
		z3.manufacturingDate = "Sample3";
		z3.expiryDate = "Sample3";
		z3.bindingType = "Sample3";
		z3.size = "Sample3";
		z3.weight = 13.0;
		z3.isEcoFriendly = false;
		z3.countryOfOrigin = "Sample3";
		z3.warrantyMonths = 103;
		z3.packagingType = "Sample3";
		z3.thickness = 13.0;
		z3.isRecyclable = false;
		z3.feature1 = "Sample3";
		z3.feature2 = "Sample3";
		z3.feature3 = "Sample3";
		z3.hasBookmark = false;
		z3.hasElasticBand = false;
		z3.rating = 103;

		System.out.println("----- ZenNotebook 3 -----");
		System.out.println("productId: " + z3.productId);
		System.out.println("brandName: " + z3.brandName);
		System.out.println("paperType: " + z3.paperType);
		System.out.println("color: " + z3.color);
		System.out.println("pageCount: " + z3.pageCount);
		System.out.println("price: " + z3.price);
		System.out.println("isHardCover: " + z3.isHardCover);
		System.out.println("isAvailable: " + z3.isAvailable);
		System.out.println("manufacturingDate: " + z3.manufacturingDate);
		System.out.println("expiryDate: " + z3.expiryDate);
		System.out.println("bindingType: " + z3.bindingType);
		System.out.println("size: " + z3.size);
		System.out.println("weight: " + z3.weight);
		System.out.println("isEcoFriendly: " + z3.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z3.countryOfOrigin);
		System.out.println("warrantyMonths: " + z3.warrantyMonths);
		System.out.println("packagingType: " + z3.packagingType);
		System.out.println("thickness: " + z3.thickness);
		System.out.println("isRecyclable: " + z3.isRecyclable);
		System.out.println("feature1: " + z3.feature1);
		System.out.println("feature2: " + z3.feature2);
		System.out.println("feature3: " + z3.feature3);
		System.out.println("hasBookmark: " + z3.hasBookmark);
		System.out.println("hasElasticBand: " + z3.hasElasticBand);
		System.out.println("rating: " + z3.rating);


		ZenNotebook z4 = new ZenNotebook();
		z4.productId = 104;
		z4.brandName = "Sample4";
		z4.paperType = "Sample4";
		z4.color = "Sample4";
		z4.pageCount = 14.0;
		z4.price = 14.0;
		z4.isHardCover = true;
		z4.isAvailable = true;
		z4.manufacturingDate = "Sample4";
		z4.expiryDate = "Sample4";
		z4.bindingType = "Sample4";
		z4.size = "Sample4";
		z4.weight = 14.0;
		z4.isEcoFriendly = true;
		z4.countryOfOrigin = "Sample4";
		z4.warrantyMonths = 104;
		z4.packagingType = "Sample4";
		z4.thickness = 14.0;
		z4.isRecyclable = true;
		z4.feature1 = "Sample4";
		z4.feature2 = "Sample4";
		z4.feature3 = "Sample4";
		z4.hasBookmark = true;
		z4.hasElasticBand = true;
		z4.rating = 104;

		System.out.println("----- ZenNotebook 4 -----");
		System.out.println("productId: " + z4.productId);
		System.out.println("brandName: " + z4.brandName);
		System.out.println("paperType: " + z4.paperType);
		System.out.println("color: " + z4.color);
		System.out.println("pageCount: " + z4.pageCount);
		System.out.println("price: " + z4.price);
		System.out.println("isHardCover: " + z4.isHardCover);
		System.out.println("isAvailable: " + z4.isAvailable);
		System.out.println("manufacturingDate: " + z4.manufacturingDate);
		System.out.println("expiryDate: " + z4.expiryDate);
		System.out.println("bindingType: " + z4.bindingType);
		System.out.println("size: " + z4.size);
		System.out.println("weight: " + z4.weight);
		System.out.println("isEcoFriendly: " + z4.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z4.countryOfOrigin);
		System.out.println("warrantyMonths: " + z4.warrantyMonths);
		System.out.println("packagingType: " + z4.packagingType);
		System.out.println("thickness: " + z4.thickness);
		System.out.println("isRecyclable: " + z4.isRecyclable);
		System.out.println("feature1: " + z4.feature1);
		System.out.println("feature2: " + z4.feature2);
		System.out.println("feature3: " + z4.feature3);
		System.out.println("hasBookmark: " + z4.hasBookmark);
		System.out.println("hasElasticBand: " + z4.hasElasticBand);
		System.out.println("rating: " + z4.rating);


		ZenNotebook z5 = new ZenNotebook();
		z5.productId = 105;
		z5.brandName = "Sample5";
		z5.paperType = "Sample5";
		z5.color = "Sample5";
		z5.pageCount = 15.0;
		z5.price = 15.0;
		z5.isHardCover = false;
		z5.isAvailable = false;
		z5.manufacturingDate = "Sample5";
		z5.expiryDate = "Sample5";
		z5.bindingType = "Sample5";
		z5.size = "Sample5";
		z5.weight = 15.0;
		z5.isEcoFriendly = false;
		z5.countryOfOrigin = "Sample5";
		z5.warrantyMonths = 105;
		z5.packagingType = "Sample5";
		z5.thickness = 15.0;
		z5.isRecyclable = false;
		z5.feature1 = "Sample5";
		z5.feature2 = "Sample5";
		z5.feature3 = "Sample5";
		z5.hasBookmark = false;
		z5.hasElasticBand = false;
		z5.rating = 105;

		System.out.println("----- ZenNotebook 5 -----");
		System.out.println("productId: " + z5.productId);
		System.out.println("brandName: " + z5.brandName);
		System.out.println("paperType: " + z5.paperType);
		System.out.println("color: " + z5.color);
		System.out.println("pageCount: " + z5.pageCount);
		System.out.println("price: " + z5.price);
		System.out.println("isHardCover: " + z5.isHardCover);
		System.out.println("isAvailable: " + z5.isAvailable);
		System.out.println("manufacturingDate: " + z5.manufacturingDate);
		System.out.println("expiryDate: " + z5.expiryDate);
		System.out.println("bindingType: " + z5.bindingType);
		System.out.println("size: " + z5.size);
		System.out.println("weight: " + z5.weight);
		System.out.println("isEcoFriendly: " + z5.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z5.countryOfOrigin);
		System.out.println("warrantyMonths: " + z5.warrantyMonths);
		System.out.println("packagingType: " + z5.packagingType);
		System.out.println("thickness: " + z5.thickness);
		System.out.println("isRecyclable: " + z5.isRecyclable);
		System.out.println("feature1: " + z5.feature1);
		System.out.println("feature2: " + z5.feature2);
		System.out.println("feature3: " + z5.feature3);
		System.out.println("hasBookmark: " + z5.hasBookmark);
		System.out.println("hasElasticBand: " + z5.hasElasticBand);
		System.out.println("rating: " + z5.rating);


		ZenNotebook z6 = new ZenNotebook();
		z6.productId = 106;
		z6.brandName = "Sample6";
		z6.paperType = "Sample6";
		z6.color = "Sample6";
		z6.pageCount = 16.0;
		z6.price = 16.0;
		z6.isHardCover = true;
		z6.isAvailable = true;
		z6.manufacturingDate = "Sample6";
		z6.expiryDate = "Sample6";
		z6.bindingType = "Sample6";
		z6.size = "Sample6";
		z6.weight = 16.0;
		z6.isEcoFriendly = true;
		z6.countryOfOrigin = "Sample6";
		z6.warrantyMonths = 106;
		z6.packagingType = "Sample6";
		z6.thickness = 16.0;
		z6.isRecyclable = true;
		z6.feature1 = "Sample6";
		z6.feature2 = "Sample6";
		z6.feature3 = "Sample6";
		z6.hasBookmark = true;
		z6.hasElasticBand = true;
		z6.rating = 106;

		System.out.println("----- ZenNotebook 6 -----");
		System.out.println("productId: " + z6.productId);
		System.out.println("brandName: " + z6.brandName);
		System.out.println("paperType: " + z6.paperType);
		System.out.println("color: " + z6.color);
		System.out.println("pageCount: " + z6.pageCount);
		System.out.println("price: " + z6.price);
		System.out.println("isHardCover: " + z6.isHardCover);
		System.out.println("isAvailable: " + z6.isAvailable);
		System.out.println("manufacturingDate: " + z6.manufacturingDate);
		System.out.println("expiryDate: " + z6.expiryDate);
		System.out.println("bindingType: " + z6.bindingType);
		System.out.println("size: " + z6.size);
		System.out.println("weight: " + z6.weight);
		System.out.println("isEcoFriendly: " + z6.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z6.countryOfOrigin);
		System.out.println("warrantyMonths: " + z6.warrantyMonths);
		System.out.println("packagingType: " + z6.packagingType);
		System.out.println("thickness: " + z6.thickness);
		System.out.println("isRecyclable: " + z6.isRecyclable);
		System.out.println("feature1: " + z6.feature1);
		System.out.println("feature2: " + z6.feature2);
		System.out.println("feature3: " + z6.feature3);
		System.out.println("hasBookmark: " + z6.hasBookmark);
		System.out.println("hasElasticBand: " + z6.hasElasticBand);
		System.out.println("rating: " + z6.rating);


		ZenNotebook z7 = new ZenNotebook();
		z7.productId = 107;
		z7.brandName = "Sample7";
		z7.paperType = "Sample7";
		z7.color = "Sample7";
		z7.pageCount = 17.0;
		z7.price = 17.0;
		z7.isHardCover = false;
		z7.isAvailable = false;
		z7.manufacturingDate = "Sample7";
		z7.expiryDate = "Sample7";
		z7.bindingType = "Sample7";
		z7.size = "Sample7";
		z7.weight = 17.0;
		z7.isEcoFriendly = false;
		z7.countryOfOrigin = "Sample7";
		z7.warrantyMonths = 107;
		z7.packagingType = "Sample7";
		z7.thickness = 17.0;
		z7.isRecyclable = false;
		z7.feature1 = "Sample7";
		z7.feature2 = "Sample7";
		z7.feature3 = "Sample7";
		z7.hasBookmark = false;
		z7.hasElasticBand = false;
		z7.rating = 107;

		System.out.println("----- ZenNotebook 7 -----");
		System.out.println("productId: " + z7.productId);
		System.out.println("brandName: " + z7.brandName);
		System.out.println("paperType: " + z7.paperType);
		System.out.println("color: " + z7.color);
		System.out.println("pageCount: " + z7.pageCount);
		System.out.println("price: " + z7.price);
		System.out.println("isHardCover: " + z7.isHardCover);
		System.out.println("isAvailable: " + z7.isAvailable);
		System.out.println("manufacturingDate: " + z7.manufacturingDate);
		System.out.println("expiryDate: " + z7.expiryDate);
		System.out.println("bindingType: " + z7.bindingType);
		System.out.println("size: " + z7.size);
		System.out.println("weight: " + z7.weight);
		System.out.println("isEcoFriendly: " + z7.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z7.countryOfOrigin);
		System.out.println("warrantyMonths: " + z7.warrantyMonths);
		System.out.println("packagingType: " + z7.packagingType);
		System.out.println("thickness: " + z7.thickness);
		System.out.println("isRecyclable: " + z7.isRecyclable);
		System.out.println("feature1: " + z7.feature1);
		System.out.println("feature2: " + z7.feature2);
		System.out.println("feature3: " + z7.feature3);
		System.out.println("hasBookmark: " + z7.hasBookmark);
		System.out.println("hasElasticBand: " + z7.hasElasticBand);
		System.out.println("rating: " + z7.rating);


		ZenNotebook z8 = new ZenNotebook();
		z8.productId = 108;
		z8.brandName = "Sample8";
		z8.paperType = "Sample8";
		z8.color = "Sample8";
		z8.pageCount = 18.0;
		z8.price = 18.0;
		z8.isHardCover = true;
		z8.isAvailable = true;
		z8.manufacturingDate = "Sample8";
		z8.expiryDate = "Sample8";
		z8.bindingType = "Sample8";
		z8.size = "Sample8";
		z8.weight = 18.0;
		z8.isEcoFriendly = true;
		z8.countryOfOrigin = "Sample8";
		z8.warrantyMonths = 108;
		z8.packagingType = "Sample8";
		z8.thickness = 18.0;
		z8.isRecyclable = true;
		z8.feature1 = "Sample8";
		z8.feature2 = "Sample8";
		z8.feature3 = "Sample8";
		z8.hasBookmark = true;
		z8.hasElasticBand = true;
		z8.rating = 108;

		System.out.println("----- ZenNotebook 8 -----");
		System.out.println("productId: " + z8.productId);
		System.out.println("brandName: " + z8.brandName);
		System.out.println("paperType: " + z8.paperType);
		System.out.println("color: " + z8.color);
		System.out.println("pageCount: " + z8.pageCount);
		System.out.println("price: " + z8.price);
		System.out.println("isHardCover: " + z8.isHardCover);
		System.out.println("isAvailable: " + z8.isAvailable);
		System.out.println("manufacturingDate: " + z8.manufacturingDate);
		System.out.println("expiryDate: " + z8.expiryDate);
		System.out.println("bindingType: " + z8.bindingType);
		System.out.println("size: " + z8.size);
		System.out.println("weight: " + z8.weight);
		System.out.println("isEcoFriendly: " + z8.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z8.countryOfOrigin);
		System.out.println("warrantyMonths: " + z8.warrantyMonths);
		System.out.println("packagingType: " + z8.packagingType);
		System.out.println("thickness: " + z8.thickness);
		System.out.println("isRecyclable: " + z8.isRecyclable);
		System.out.println("feature1: " + z8.feature1);
		System.out.println("feature2: " + z8.feature2);
		System.out.println("feature3: " + z8.feature3);
		System.out.println("hasBookmark: " + z8.hasBookmark);
		System.out.println("hasElasticBand: " + z8.hasElasticBand);
		System.out.println("rating: " + z8.rating);


		ZenNotebook z9 = new ZenNotebook();
		z9.productId = 109;
		z9.brandName = "Sample9";
		z9.paperType = "Sample9";
		z9.color = "Sample9";
		z9.pageCount = 19.0;
		z9.price = 19.0;
		z9.isHardCover = false;
		z9.isAvailable = false;
		z9.manufacturingDate = "Sample9";
		z9.expiryDate = "Sample9";
		z9.bindingType = "Sample9";
		z9.size = "Sample9";
		z9.weight = 19.0;
		z9.isEcoFriendly = false;
		z9.countryOfOrigin = "Sample9";
		z9.warrantyMonths = 109;
		z9.packagingType = "Sample9";
		z9.thickness = 19.0;
		z9.isRecyclable = false;
		z9.feature1 = "Sample9";
		z9.feature2 = "Sample9";
		z9.feature3 = "Sample9";
		z9.hasBookmark = false;
		z9.hasElasticBand = false;
		z9.rating = 109;

		System.out.println("----- ZenNotebook 9 -----");
		System.out.println("productId: " + z9.productId);
		System.out.println("brandName: " + z9.brandName);
		System.out.println("paperType: " + z9.paperType);
		System.out.println("color: " + z9.color);
		System.out.println("pageCount: " + z9.pageCount);
		System.out.println("price: " + z9.price);
		System.out.println("isHardCover: " + z9.isHardCover);
		System.out.println("isAvailable: " + z9.isAvailable);
		System.out.println("manufacturingDate: " + z9.manufacturingDate);
		System.out.println("expiryDate: " + z9.expiryDate);
		System.out.println("bindingType: " + z9.bindingType);
		System.out.println("size: " + z9.size);
		System.out.println("weight: " + z9.weight);
		System.out.println("isEcoFriendly: " + z9.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z9.countryOfOrigin);
		System.out.println("warrantyMonths: " + z9.warrantyMonths);
		System.out.println("packagingType: " + z9.packagingType);
		System.out.println("thickness: " + z9.thickness);
		System.out.println("isRecyclable: " + z9.isRecyclable);
		System.out.println("feature1: " + z9.feature1);
		System.out.println("feature2: " + z9.feature2);
		System.out.println("feature3: " + z9.feature3);
		System.out.println("hasBookmark: " + z9.hasBookmark);
		System.out.println("hasElasticBand: " + z9.hasElasticBand);
		System.out.println("rating: " + z9.rating);


		ZenNotebook z10 = new ZenNotebook();
		z10.productId = 110;
		z10.brandName = "Sample10";
		z10.paperType = "Sample10";
		z10.color = "Sample10";
		z10.pageCount = 20.0;
		z10.price = 20.0;
		z10.isHardCover = true;
		z10.isAvailable = true;
		z10.manufacturingDate = "Sample10";
		z10.expiryDate = "Sample10";
		z10.bindingType = "Sample10";
		z10.size = "Sample10";
		z10.weight = 20.0;
		z10.isEcoFriendly = true;
		z10.countryOfOrigin = "Sample10";
		z10.warrantyMonths = 110;
		z10.packagingType = "Sample10";
		z10.thickness = 20.0;
		z10.isRecyclable = true;
		z10.feature1 = "Sample10";
		z10.feature2 = "Sample10";
		z10.feature3 = "Sample10";
		z10.hasBookmark = true;
		z10.hasElasticBand = true;
		z10.rating = 110;

		System.out.println("----- ZenNotebook 10 -----");
		System.out.println("productId: " + z10.productId);
		System.out.println("brandName: " + z10.brandName);
		System.out.println("paperType: " + z10.paperType);
		System.out.println("color: " + z10.color);
		System.out.println("pageCount: " + z10.pageCount);
		System.out.println("price: " + z10.price);
		System.out.println("isHardCover: " + z10.isHardCover);
		System.out.println("isAvailable: " + z10.isAvailable);
		System.out.println("manufacturingDate: " + z10.manufacturingDate);
		System.out.println("expiryDate: " + z10.expiryDate);
		System.out.println("bindingType: " + z10.bindingType);
		System.out.println("size: " + z10.size);
		System.out.println("weight: " + z10.weight);
		System.out.println("isEcoFriendly: " + z10.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z10.countryOfOrigin);
		System.out.println("warrantyMonths: " + z10.warrantyMonths);
		System.out.println("packagingType: " + z10.packagingType);
		System.out.println("thickness: " + z10.thickness);
		System.out.println("isRecyclable: " + z10.isRecyclable);
		System.out.println("feature1: " + z10.feature1);
		System.out.println("feature2: " + z10.feature2);
		System.out.println("feature3: " + z10.feature3);
		System.out.println("hasBookmark: " + z10.hasBookmark);
		System.out.println("hasElasticBand: " + z10.hasElasticBand);
		System.out.println("rating: " + z10.rating);


		ZenNotebook z11 = new ZenNotebook();
		z11.productId = 111;
		z11.brandName = "Sample11";
		z11.paperType = "Sample11";
		z11.color = "Sample11";
		z11.pageCount = 21.0;
		z11.price = 21.0;
		z11.isHardCover = false;
		z11.isAvailable = false;
		z11.manufacturingDate = "Sample11";
		z11.expiryDate = "Sample11";
		z11.bindingType = "Sample11";
		z11.size = "Sample11";
		z11.weight = 21.0;
		z11.isEcoFriendly = false;
		z11.countryOfOrigin = "Sample11";
		z11.warrantyMonths = 111;
		z11.packagingType = "Sample11";
		z11.thickness = 21.0;
		z11.isRecyclable = false;
		z11.feature1 = "Sample11";
		z11.feature2 = "Sample11";
		z11.feature3 = "Sample11";
		z11.hasBookmark = false;
		z11.hasElasticBand = false;
		z11.rating = 111;

		System.out.println("----- ZenNotebook 11 -----");
		System.out.println("productId: " + z11.productId);
		System.out.println("brandName: " + z11.brandName);
		System.out.println("paperType: " + z11.paperType);
		System.out.println("color: " + z11.color);
		System.out.println("pageCount: " + z11.pageCount);
		System.out.println("price: " + z11.price);
		System.out.println("isHardCover: " + z11.isHardCover);
		System.out.println("isAvailable: " + z11.isAvailable);
		System.out.println("manufacturingDate: " + z11.manufacturingDate);
		System.out.println("expiryDate: " + z11.expiryDate);
		System.out.println("bindingType: " + z11.bindingType);
		System.out.println("size: " + z11.size);
		System.out.println("weight: " + z11.weight);
		System.out.println("isEcoFriendly: " + z11.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z11.countryOfOrigin);
		System.out.println("warrantyMonths: " + z11.warrantyMonths);
		System.out.println("packagingType: " + z11.packagingType);
		System.out.println("thickness: " + z11.thickness);
		System.out.println("isRecyclable: " + z11.isRecyclable);
		System.out.println("feature1: " + z11.feature1);
		System.out.println("feature2: " + z11.feature2);
		System.out.println("feature3: " + z11.feature3);
		System.out.println("hasBookmark: " + z11.hasBookmark);
		System.out.println("hasElasticBand: " + z11.hasElasticBand);
		System.out.println("rating: " + z11.rating);


		ZenNotebook z12 = new ZenNotebook();
		z12.productId = 112;
		z12.brandName = "Sample12";
		z12.paperType = "Sample12";
		z12.color = "Sample12";
		z12.pageCount = 22.0;
		z12.price = 22.0;
		z12.isHardCover = true;
		z12.isAvailable = true;
		z12.manufacturingDate = "Sample12";
		z12.expiryDate = "Sample12";
		z12.bindingType = "Sample12";
		z12.size = "Sample12";
		z12.weight = 22.0;
		z12.isEcoFriendly = true;
		z12.countryOfOrigin = "Sample12";
		z12.warrantyMonths = 112;
		z12.packagingType = "Sample12";
		z12.thickness = 22.0;
		z12.isRecyclable = true;
		z12.feature1 = "Sample12";
		z12.feature2 = "Sample12";
		z12.feature3 = "Sample12";
		z12.hasBookmark = true;
		z12.hasElasticBand = true;
		z12.rating = 112;

		System.out.println("----- ZenNotebook 12 -----");
		System.out.println("productId: " + z12.productId);
		System.out.println("brandName: " + z12.brandName);
		System.out.println("paperType: " + z12.paperType);
		System.out.println("color: " + z12.color);
		System.out.println("pageCount: " + z12.pageCount);
		System.out.println("price: " + z12.price);
		System.out.println("isHardCover: " + z12.isHardCover);
		System.out.println("isAvailable: " + z12.isAvailable);
		System.out.println("manufacturingDate: " + z12.manufacturingDate);
		System.out.println("expiryDate: " + z12.expiryDate);
		System.out.println("bindingType: " + z12.bindingType);
		System.out.println("size: " + z12.size);
		System.out.println("weight: " + z12.weight);
		System.out.println("isEcoFriendly: " + z12.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z12.countryOfOrigin);
		System.out.println("warrantyMonths: " + z12.warrantyMonths);
		System.out.println("packagingType: " + z12.packagingType);
		System.out.println("thickness: " + z12.thickness);
		System.out.println("isRecyclable: " + z12.isRecyclable);
		System.out.println("feature1: " + z12.feature1);
		System.out.println("feature2: " + z12.feature2);
		System.out.println("feature3: " + z12.feature3);
		System.out.println("hasBookmark: " + z12.hasBookmark);
		System.out.println("hasElasticBand: " + z12.hasElasticBand);
		System.out.println("rating: " + z12.rating);


		ZenNotebook z13 = new ZenNotebook();
		z13.productId = 113;
		z13.brandName = "Sample13";
		z13.paperType = "Sample13";
		z13.color = "Sample13";
		z13.pageCount = 23.0;
		z13.price = 23.0;
		z13.isHardCover = false;
		z13.isAvailable = false;
		z13.manufacturingDate = "Sample13";
		z13.expiryDate = "Sample13";
		z13.bindingType = "Sample13";
		z13.size = "Sample13";
		z13.weight = 23.0;
		z13.isEcoFriendly = false;
		z13.countryOfOrigin = "Sample13";
		z13.warrantyMonths = 113;
		z13.packagingType = "Sample13";
		z13.thickness = 23.0;
		z13.isRecyclable = false;
		z13.feature1 = "Sample13";
		z13.feature2 = "Sample13";
		z13.feature3 = "Sample13";
		z13.hasBookmark = false;
		z13.hasElasticBand = false;
		z13.rating = 113;

		System.out.println("----- ZenNotebook 13 -----");
		System.out.println("productId: " + z13.productId);
		System.out.println("brandName: " + z13.brandName);
		System.out.println("paperType: " + z13.paperType);
		System.out.println("color: " + z13.color);
		System.out.println("pageCount: " + z13.pageCount);
		System.out.println("price: " + z13.price);
		System.out.println("isHardCover: " + z13.isHardCover);
		System.out.println("isAvailable: " + z13.isAvailable);
		System.out.println("manufacturingDate: " + z13.manufacturingDate);
		System.out.println("expiryDate: " + z13.expiryDate);
		System.out.println("bindingType: " + z13.bindingType);
		System.out.println("size: " + z13.size);
		System.out.println("weight: " + z13.weight);
		System.out.println("isEcoFriendly: " + z13.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z13.countryOfOrigin);
		System.out.println("warrantyMonths: " + z13.warrantyMonths);
		System.out.println("packagingType: " + z13.packagingType);
		System.out.println("thickness: " + z13.thickness);
		System.out.println("isRecyclable: " + z13.isRecyclable);
		System.out.println("feature1: " + z13.feature1);
		System.out.println("feature2: " + z13.feature2);
		System.out.println("feature3: " + z13.feature3);
		System.out.println("hasBookmark: " + z13.hasBookmark);
		System.out.println("hasElasticBand: " + z13.hasElasticBand);
		System.out.println("rating: " + z13.rating);


		ZenNotebook z14 = new ZenNotebook();
		z14.productId = 114;
		z14.brandName = "Sample14";
		z14.paperType = "Sample14";
		z14.color = "Sample14";
		z14.pageCount = 24.0;
		z14.price = 24.0;
		z14.isHardCover = true;
		z14.isAvailable = true;
		z14.manufacturingDate = "Sample14";
		z14.expiryDate = "Sample14";
		z14.bindingType = "Sample14";
		z14.size = "Sample14";
		z14.weight = 24.0;
		z14.isEcoFriendly = true;
		z14.countryOfOrigin = "Sample14";
		z14.warrantyMonths = 114;
		z14.packagingType = "Sample14";
		z14.thickness = 24.0;
		z14.isRecyclable = true;
		z14.feature1 = "Sample14";
		z14.feature2 = "Sample14";
		z14.feature3 = "Sample14";
		z14.hasBookmark = true;
		z14.hasElasticBand = true;
		z14.rating = 114;

		System.out.println("----- ZenNotebook 14 -----");
		System.out.println("productId: " + z14.productId);
		System.out.println("brandName: " + z14.brandName);
		System.out.println("paperType: " + z14.paperType);
		System.out.println("color: " + z14.color);
		System.out.println("pageCount: " + z14.pageCount);
		System.out.println("price: " + z14.price);
		System.out.println("isHardCover: " + z14.isHardCover);
		System.out.println("isAvailable: " + z14.isAvailable);
		System.out.println("manufacturingDate: " + z14.manufacturingDate);
		System.out.println("expiryDate: " + z14.expiryDate);
		System.out.println("bindingType: " + z14.bindingType);
		System.out.println("size: " + z14.size);
		System.out.println("weight: " + z14.weight);
		System.out.println("isEcoFriendly: " + z14.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z14.countryOfOrigin);
		System.out.println("warrantyMonths: " + z14.warrantyMonths);
		System.out.println("packagingType: " + z14.packagingType);
		System.out.println("thickness: " + z14.thickness);
		System.out.println("isRecyclable: " + z14.isRecyclable);
		System.out.println("feature1: " + z14.feature1);
		System.out.println("feature2: " + z14.feature2);
		System.out.println("feature3: " + z14.feature3);
		System.out.println("hasBookmark: " + z14.hasBookmark);
		System.out.println("hasElasticBand: " + z14.hasElasticBand);
		System.out.println("rating: " + z14.rating);


		ZenNotebook z15 = new ZenNotebook();
		z15.productId = 115;
		z15.brandName = "Sample15";
		z15.paperType = "Sample15";
		z15.color = "Sample15";
		z15.pageCount = 25.0;
		z15.price = 25.0;
		z15.isHardCover = false;
		z15.isAvailable = false;
		z15.manufacturingDate = "Sample15";
		z15.expiryDate = "Sample15";
		z15.bindingType = "Sample15";
		z15.size = "Sample15";
		z15.weight = 25.0;
		z15.isEcoFriendly = false;
		z15.countryOfOrigin = "Sample15";
		z15.warrantyMonths = 115;
		z15.packagingType = "Sample15";
		z15.thickness = 25.0;
		z15.isRecyclable = false;
		z15.feature1 = "Sample15";
		z15.feature2 = "Sample15";
		z15.feature3 = "Sample15";
		z15.hasBookmark = false;
		z15.hasElasticBand = false;
		z15.rating = 115;

		System.out.println("----- ZenNotebook 15 -----");
		System.out.println("productId: " + z15.productId);
		System.out.println("brandName: " + z15.brandName);
		System.out.println("paperType: " + z15.paperType);
		System.out.println("color: " + z15.color);
		System.out.println("pageCount: " + z15.pageCount);
		System.out.println("price: " + z15.price);
		System.out.println("isHardCover: " + z15.isHardCover);
		System.out.println("isAvailable: " + z15.isAvailable);
		System.out.println("manufacturingDate: " + z15.manufacturingDate);
		System.out.println("expiryDate: " + z15.expiryDate);
		System.out.println("bindingType: " + z15.bindingType);
		System.out.println("size: " + z15.size);
		System.out.println("weight: " + z15.weight);
		System.out.println("isEcoFriendly: " + z15.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z15.countryOfOrigin);
		System.out.println("warrantyMonths: " + z15.warrantyMonths);
		System.out.println("packagingType: " + z15.packagingType);
		System.out.println("thickness: " + z15.thickness);
		System.out.println("isRecyclable: " + z15.isRecyclable);
		System.out.println("feature1: " + z15.feature1);
		System.out.println("feature2: " + z15.feature2);
		System.out.println("feature3: " + z15.feature3);
		System.out.println("hasBookmark: " + z15.hasBookmark);
		System.out.println("hasElasticBand: " + z15.hasElasticBand);
		System.out.println("rating: " + z15.rating);


		ZenNotebook z16 = new ZenNotebook();
		z16.productId = 116;
		z16.brandName = "Sample16";
		z16.paperType = "Sample16";
		z16.color = "Sample16";
		z16.pageCount = 26.0;
		z16.price = 26.0;
		z16.isHardCover = true;
		z16.isAvailable = true;
		z16.manufacturingDate = "Sample16";
		z16.expiryDate = "Sample16";
		z16.bindingType = "Sample16";
		z16.size = "Sample16";
		z16.weight = 26.0;
		z16.isEcoFriendly = true;
		z16.countryOfOrigin = "Sample16";
		z16.warrantyMonths = 116;
		z16.packagingType = "Sample16";
		z16.thickness = 26.0;
		z16.isRecyclable = true;
		z16.feature1 = "Sample16";
		z16.feature2 = "Sample16";
		z16.feature3 = "Sample16";
		z16.hasBookmark = true;
		z16.hasElasticBand = true;
		z16.rating = 116;

		System.out.println("----- ZenNotebook 16 -----");
		System.out.println("productId: " + z16.productId);
		System.out.println("brandName: " + z16.brandName);
		System.out.println("paperType: " + z16.paperType);
		System.out.println("color: " + z16.color);
		System.out.println("pageCount: " + z16.pageCount);
		System.out.println("price: " + z16.price);
		System.out.println("isHardCover: " + z16.isHardCover);
		System.out.println("isAvailable: " + z16.isAvailable);
		System.out.println("manufacturingDate: " + z16.manufacturingDate);
		System.out.println("expiryDate: " + z16.expiryDate);
		System.out.println("bindingType: " + z16.bindingType);
		System.out.println("size: " + z16.size);
		System.out.println("weight: " + z16.weight);
		System.out.println("isEcoFriendly: " + z16.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z16.countryOfOrigin);
		System.out.println("warrantyMonths: " + z16.warrantyMonths);
		System.out.println("packagingType: " + z16.packagingType);
		System.out.println("thickness: " + z16.thickness);
		System.out.println("isRecyclable: " + z16.isRecyclable);
		System.out.println("feature1: " + z16.feature1);
		System.out.println("feature2: " + z16.feature2);
		System.out.println("feature3: " + z16.feature3);
		System.out.println("hasBookmark: " + z16.hasBookmark);
		System.out.println("hasElasticBand: " + z16.hasElasticBand);
		System.out.println("rating: " + z16.rating);


		ZenNotebook z17 = new ZenNotebook();
		z17.productId = 117;
		z17.brandName = "Sample17";
		z17.paperType = "Sample17";
		z17.color = "Sample17";
		z17.pageCount = 27.0;
		z17.price = 27.0;
		z17.isHardCover = false;
		z17.isAvailable = false;
		z17.manufacturingDate = "Sample17";
		z17.expiryDate = "Sample17";
		z17.bindingType = "Sample17";
		z17.size = "Sample17";
		z17.weight = 27.0;
		z17.isEcoFriendly = false;
		z17.countryOfOrigin = "Sample17";
		z17.warrantyMonths = 117;
		z17.packagingType = "Sample17";
		z17.thickness = 27.0;
		z17.isRecyclable = false;
		z17.feature1 = "Sample17";
		z17.feature2 = "Sample17";
		z17.feature3 = "Sample17";
		z17.hasBookmark = false;
		z17.hasElasticBand = false;
		z17.rating = 117;

		System.out.println("----- ZenNotebook 17 -----");
		System.out.println("productId: " + z17.productId);
		System.out.println("brandName: " + z17.brandName);
		System.out.println("paperType: " + z17.paperType);
		System.out.println("color: " + z17.color);
		System.out.println("pageCount: " + z17.pageCount);
		System.out.println("price: " + z17.price);
		System.out.println("isHardCover: " + z17.isHardCover);
		System.out.println("isAvailable: " + z17.isAvailable);
		System.out.println("manufacturingDate: " + z17.manufacturingDate);
		System.out.println("expiryDate: " + z17.expiryDate);
		System.out.println("bindingType: " + z17.bindingType);
		System.out.println("size: " + z17.size);
		System.out.println("weight: " + z17.weight);
		System.out.println("isEcoFriendly: " + z17.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z17.countryOfOrigin);
		System.out.println("warrantyMonths: " + z17.warrantyMonths);
		System.out.println("packagingType: " + z17.packagingType);
		System.out.println("thickness: " + z17.thickness);
		System.out.println("isRecyclable: " + z17.isRecyclable);
		System.out.println("feature1: " + z17.feature1);
		System.out.println("feature2: " + z17.feature2);
		System.out.println("feature3: " + z17.feature3);
		System.out.println("hasBookmark: " + z17.hasBookmark);
		System.out.println("hasElasticBand: " + z17.hasElasticBand);
		System.out.println("rating: " + z17.rating);


		ZenNotebook z18 = new ZenNotebook();
		z18.productId = 118;
		z18.brandName = "Sample18";
		z18.paperType = "Sample18";
		z18.color = "Sample18";
		z18.pageCount = 28.0;
		z18.price = 28.0;
		z18.isHardCover = true;
		z18.isAvailable = true;
		z18.manufacturingDate = "Sample18";
		z18.expiryDate = "Sample18";
		z18.bindingType = "Sample18";
		z18.size = "Sample18";
		z18.weight = 28.0;
		z18.isEcoFriendly = true;
		z18.countryOfOrigin = "Sample18";
		z18.warrantyMonths = 118;
		z18.packagingType = "Sample18";
		z18.thickness = 28.0;
		z18.isRecyclable = true;
		z18.feature1 = "Sample18";
		z18.feature2 = "Sample18";
		z18.feature3 = "Sample18";
		z18.hasBookmark = true;
		z18.hasElasticBand = true;
		z18.rating = 118;

		System.out.println("----- ZenNotebook 18 -----");
		System.out.println("productId: " + z18.productId);
		System.out.println("brandName: " + z18.brandName);
		System.out.println("paperType: " + z18.paperType);
		System.out.println("color: " + z18.color);
		System.out.println("pageCount: " + z18.pageCount);
		System.out.println("price: " + z18.price);
		System.out.println("isHardCover: " + z18.isHardCover);
		System.out.println("isAvailable: " + z18.isAvailable);
		System.out.println("manufacturingDate: " + z18.manufacturingDate);
		System.out.println("expiryDate: " + z18.expiryDate);
		System.out.println("bindingType: " + z18.bindingType);
		System.out.println("size: " + z18.size);
		System.out.println("weight: " + z18.weight);
		System.out.println("isEcoFriendly: " + z18.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z18.countryOfOrigin);
		System.out.println("warrantyMonths: " + z18.warrantyMonths);
		System.out.println("packagingType: " + z18.packagingType);
		System.out.println("thickness: " + z18.thickness);
		System.out.println("isRecyclable: " + z18.isRecyclable);
		System.out.println("feature1: " + z18.feature1);
		System.out.println("feature2: " + z18.feature2);
		System.out.println("feature3: " + z18.feature3);
		System.out.println("hasBookmark: " + z18.hasBookmark);
		System.out.println("hasElasticBand: " + z18.hasElasticBand);
		System.out.println("rating: " + z18.rating);


		ZenNotebook z19 = new ZenNotebook();
		z19.productId = 119;
		z19.brandName = "Sample19";
		z19.paperType = "Sample19";
		z19.color = "Sample19";
		z19.pageCount = 29.0;
		z19.price = 29.0;
		z19.isHardCover = false;
		z19.isAvailable = false;
		z19.manufacturingDate = "Sample19";
		z19.expiryDate = "Sample19";
		z19.bindingType = "Sample19";
		z19.size = "Sample19";
		z19.weight = 29.0;
		z19.isEcoFriendly = false;
		z19.countryOfOrigin = "Sample19";
		z19.warrantyMonths = 119;
		z19.packagingType = "Sample19";
		z19.thickness = 29.0;
		z19.isRecyclable = false;
		z19.feature1 = "Sample19";
		z19.feature2 = "Sample19";
		z19.feature3 = "Sample19";
		z19.hasBookmark = false;
		z19.hasElasticBand = false;
		z19.rating = 119;

		System.out.println("----- ZenNotebook 19 -----");
		System.out.println("productId: " + z19.productId);
		System.out.println("brandName: " + z19.brandName);
		System.out.println("paperType: " + z19.paperType);
		System.out.println("color: " + z19.color);
		System.out.println("pageCount: " + z19.pageCount);
		System.out.println("price: " + z19.price);
		System.out.println("isHardCover: " + z19.isHardCover);
		System.out.println("isAvailable: " + z19.isAvailable);
		System.out.println("manufacturingDate: " + z19.manufacturingDate);
		System.out.println("expiryDate: " + z19.expiryDate);
		System.out.println("bindingType: " + z19.bindingType);
		System.out.println("size: " + z19.size);
		System.out.println("weight: " + z19.weight);
		System.out.println("isEcoFriendly: " + z19.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z19.countryOfOrigin);
		System.out.println("warrantyMonths: " + z19.warrantyMonths);
		System.out.println("packagingType: " + z19.packagingType);
		System.out.println("thickness: " + z19.thickness);
		System.out.println("isRecyclable: " + z19.isRecyclable);
		System.out.println("feature1: " + z19.feature1);
		System.out.println("feature2: " + z19.feature2);
		System.out.println("feature3: " + z19.feature3);
		System.out.println("hasBookmark: " + z19.hasBookmark);
		System.out.println("hasElasticBand: " + z19.hasElasticBand);
		System.out.println("rating: " + z19.rating);


		ZenNotebook z20 = new ZenNotebook();
		z20.productId = 120;
		z20.brandName = "Sample20";
		z20.paperType = "Sample20";
		z20.color = "Sample20";
		z20.pageCount = 30.0;
		z20.price = 30.0;
		z20.isHardCover = true;
		z20.isAvailable = true;
		z20.manufacturingDate = "Sample20";
		z20.expiryDate = "Sample20";
		z20.bindingType = "Sample20";
		z20.size = "Sample20";
		z20.weight = 30.0;
		z20.isEcoFriendly = true;
		z20.countryOfOrigin = "Sample20";
		z20.warrantyMonths = 120;
		z20.packagingType = "Sample20";
		z20.thickness = 30.0;
		z20.isRecyclable = true;
		z20.feature1 = "Sample20";
		z20.feature2 = "Sample20";
		z20.feature3 = "Sample20";
		z20.hasBookmark = true;
		z20.hasElasticBand = true;
		z20.rating = 120;

		System.out.println("----- ZenNotebook 20 -----");
		System.out.println("productId: " + z20.productId);
		System.out.println("brandName: " + z20.brandName);
		System.out.println("paperType: " + z20.paperType);
		System.out.println("color: " + z20.color);
		System.out.println("pageCount: " + z20.pageCount);
		System.out.println("price: " + z20.price);
		System.out.println("isHardCover: " + z20.isHardCover);
		System.out.println("isAvailable: " + z20.isAvailable);
		System.out.println("manufacturingDate: " + z20.manufacturingDate);
		System.out.println("expiryDate: " + z20.expiryDate);
		System.out.println("bindingType: " + z20.bindingType);
		System.out.println("size: " + z20.size);
		System.out.println("weight: " + z20.weight);
		System.out.println("isEcoFriendly: " + z20.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z20.countryOfOrigin);
		System.out.println("warrantyMonths: " + z20.warrantyMonths);
		System.out.println("packagingType: " + z20.packagingType);
		System.out.println("thickness: " + z20.thickness);
		System.out.println("isRecyclable: " + z20.isRecyclable);
		System.out.println("feature1: " + z20.feature1);
		System.out.println("feature2: " + z20.feature2);
		System.out.println("feature3: " + z20.feature3);
		System.out.println("hasBookmark: " + z20.hasBookmark);
		System.out.println("hasElasticBand: " + z20.hasElasticBand);
		System.out.println("rating: " + z20.rating);


		ZenNotebook z21 = new ZenNotebook();
		z21.productId = 121;
		z21.brandName = "Sample21";
		z21.paperType = "Sample21";
		z21.color = "Sample21";
		z21.pageCount = 31.0;
		z21.price = 31.0;
		z21.isHardCover = false;
		z21.isAvailable = false;
		z21.manufacturingDate = "Sample21";
		z21.expiryDate = "Sample21";
		z21.bindingType = "Sample21";
		z21.size = "Sample21";
		z21.weight = 31.0;
		z21.isEcoFriendly = false;
		z21.countryOfOrigin = "Sample21";
		z21.warrantyMonths = 121;
		z21.packagingType = "Sample21";
		z21.thickness = 31.0;
		z21.isRecyclable = false;
		z21.feature1 = "Sample21";
		z21.feature2 = "Sample21";
		z21.feature3 = "Sample21";
		z21.hasBookmark = false;
		z21.hasElasticBand = false;
		z21.rating = 121;

		System.out.println("----- ZenNotebook 21 -----");
		System.out.println("productId: " + z21.productId);
		System.out.println("brandName: " + z21.brandName);
		System.out.println("paperType: " + z21.paperType);
		System.out.println("color: " + z21.color);
		System.out.println("pageCount: " + z21.pageCount);
		System.out.println("price: " + z21.price);
		System.out.println("isHardCover: " + z21.isHardCover);
		System.out.println("isAvailable: " + z21.isAvailable);
		System.out.println("manufacturingDate: " + z21.manufacturingDate);
		System.out.println("expiryDate: " + z21.expiryDate);
		System.out.println("bindingType: " + z21.bindingType);
		System.out.println("size: " + z21.size);
		System.out.println("weight: " + z21.weight);
		System.out.println("isEcoFriendly: " + z21.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z21.countryOfOrigin);
		System.out.println("warrantyMonths: " + z21.warrantyMonths);
		System.out.println("packagingType: " + z21.packagingType);
		System.out.println("thickness: " + z21.thickness);
		System.out.println("isRecyclable: " + z21.isRecyclable);
		System.out.println("feature1: " + z21.feature1);
		System.out.println("feature2: " + z21.feature2);
		System.out.println("feature3: " + z21.feature3);
		System.out.println("hasBookmark: " + z21.hasBookmark);
		System.out.println("hasElasticBand: " + z21.hasElasticBand);
		System.out.println("rating: " + z21.rating);


		ZenNotebook z22 = new ZenNotebook();
		z22.productId = 122;
		z22.brandName = "Sample22";
		z22.paperType = "Sample22";
		z22.color = "Sample22";
		z22.pageCount = 32.0;
		z22.price = 32.0;
		z22.isHardCover = true;
		z22.isAvailable = true;
		z22.manufacturingDate = "Sample22";
		z22.expiryDate = "Sample22";
		z22.bindingType = "Sample22";
		z22.size = "Sample22";
		z22.weight = 32.0;
		z22.isEcoFriendly = true;
		z22.countryOfOrigin = "Sample22";
		z22.warrantyMonths = 122;
		z22.packagingType = "Sample22";
		z22.thickness = 32.0;
		z22.isRecyclable = true;
		z22.feature1 = "Sample22";
		z22.feature2 = "Sample22";
		z22.feature3 = "Sample22";
		z22.hasBookmark = true;
		z22.hasElasticBand = true;
		z22.rating = 122;

		System.out.println("----- ZenNotebook 22 -----");
		System.out.println("productId: " + z22.productId);
		System.out.println("brandName: " + z22.brandName);
		System.out.println("paperType: " + z22.paperType);
		System.out.println("color: " + z22.color);
		System.out.println("pageCount: " + z22.pageCount);
		System.out.println("price: " + z22.price);
		System.out.println("isHardCover: " + z22.isHardCover);
		System.out.println("isAvailable: " + z22.isAvailable);
		System.out.println("manufacturingDate: " + z22.manufacturingDate);
		System.out.println("expiryDate: " + z22.expiryDate);
		System.out.println("bindingType: " + z22.bindingType);
		System.out.println("size: " + z22.size);
		System.out.println("weight: " + z22.weight);
		System.out.println("isEcoFriendly: " + z22.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z22.countryOfOrigin);
		System.out.println("warrantyMonths: " + z22.warrantyMonths);
		System.out.println("packagingType: " + z22.packagingType);
		System.out.println("thickness: " + z22.thickness);
		System.out.println("isRecyclable: " + z22.isRecyclable);
		System.out.println("feature1: " + z22.feature1);
		System.out.println("feature2: " + z22.feature2);
		System.out.println("feature3: " + z22.feature3);
		System.out.println("hasBookmark: " + z22.hasBookmark);
		System.out.println("hasElasticBand: " + z22.hasElasticBand);
		System.out.println("rating: " + z22.rating);


		ZenNotebook z23 = new ZenNotebook();
		z23.productId = 123;
		z23.brandName = "Sample23";
		z23.paperType = "Sample23";
		z23.color = "Sample23";
		z23.pageCount = 33.0;
		z23.price = 33.0;
		z23.isHardCover = false;
		z23.isAvailable = false;
		z23.manufacturingDate = "Sample23";
		z23.expiryDate = "Sample23";
		z23.bindingType = "Sample23";
		z23.size = "Sample23";
		z23.weight = 33.0;
		z23.isEcoFriendly = false;
		z23.countryOfOrigin = "Sample23";
		z23.warrantyMonths = 123;
		z23.packagingType = "Sample23";
		z23.thickness = 33.0;
		z23.isRecyclable = false;
		z23.feature1 = "Sample23";
		z23.feature2 = "Sample23";
		z23.feature3 = "Sample23";
		z23.hasBookmark = false;
		z23.hasElasticBand = false;
		z23.rating = 123;

		System.out.println("----- ZenNotebook 23 -----");
		System.out.println("productId: " + z23.productId);
		System.out.println("brandName: " + z23.brandName);
		System.out.println("paperType: " + z23.paperType);
		System.out.println("color: " + z23.color);
		System.out.println("pageCount: " + z23.pageCount);
		System.out.println("price: " + z23.price);
		System.out.println("isHardCover: " + z23.isHardCover);
		System.out.println("isAvailable: " + z23.isAvailable);
		System.out.println("manufacturingDate: " + z23.manufacturingDate);
		System.out.println("expiryDate: " + z23.expiryDate);
		System.out.println("bindingType: " + z23.bindingType);
		System.out.println("size: " + z23.size);
		System.out.println("weight: " + z23.weight);
		System.out.println("isEcoFriendly: " + z23.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z23.countryOfOrigin);
		System.out.println("warrantyMonths: " + z23.warrantyMonths);
		System.out.println("packagingType: " + z23.packagingType);
		System.out.println("thickness: " + z23.thickness);
		System.out.println("isRecyclable: " + z23.isRecyclable);
		System.out.println("feature1: " + z23.feature1);
		System.out.println("feature2: " + z23.feature2);
		System.out.println("feature3: " + z23.feature3);
		System.out.println("hasBookmark: " + z23.hasBookmark);
		System.out.println("hasElasticBand: " + z23.hasElasticBand);
		System.out.println("rating: " + z23.rating);


		ZenNotebook z24 = new ZenNotebook();
		z24.productId = 124;
		z24.brandName = "Sample24";
		z24.paperType = "Sample24";
		z24.color = "Sample24";
		z24.pageCount = 34.0;
		z24.price = 34.0;
		z24.isHardCover = true;
		z24.isAvailable = true;
		z24.manufacturingDate = "Sample24";
		z24.expiryDate = "Sample24";
		z24.bindingType = "Sample24";
		z24.size = "Sample24";
		z24.weight = 34.0;
		z24.isEcoFriendly = true;
		z24.countryOfOrigin = "Sample24";
		z24.warrantyMonths = 124;
		z24.packagingType = "Sample24";
		z24.thickness = 34.0;
		z24.isRecyclable = true;
		z24.feature1 = "Sample24";
		z24.feature2 = "Sample24";
		z24.feature3 = "Sample24";
		z24.hasBookmark = true;
		z24.hasElasticBand = true;
		z24.rating = 124;

		System.out.println("----- ZenNotebook 24 -----");
		System.out.println("productId: " + z24.productId);
		System.out.println("brandName: " + z24.brandName);
		System.out.println("paperType: " + z24.paperType);
		System.out.println("color: " + z24.color);
		System.out.println("pageCount: " + z24.pageCount);
		System.out.println("price: " + z24.price);
		System.out.println("isHardCover: " + z24.isHardCover);
		System.out.println("isAvailable: " + z24.isAvailable);
		System.out.println("manufacturingDate: " + z24.manufacturingDate);
		System.out.println("expiryDate: " + z24.expiryDate);
		System.out.println("bindingType: " + z24.bindingType);
		System.out.println("size: " + z24.size);
		System.out.println("weight: " + z24.weight);
		System.out.println("isEcoFriendly: " + z24.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z24.countryOfOrigin);
		System.out.println("warrantyMonths: " + z24.warrantyMonths);
		System.out.println("packagingType: " + z24.packagingType);
		System.out.println("thickness: " + z24.thickness);
		System.out.println("isRecyclable: " + z24.isRecyclable);
		System.out.println("feature1: " + z24.feature1);
		System.out.println("feature2: " + z24.feature2);
		System.out.println("feature3: " + z24.feature3);
		System.out.println("hasBookmark: " + z24.hasBookmark);
		System.out.println("hasElasticBand: " + z24.hasElasticBand);
		System.out.println("rating: " + z24.rating);


		ZenNotebook z25 = new ZenNotebook();
		z25.productId = 125;
		z25.brandName = "Sample25";
		z25.paperType = "Sample25";
		z25.color = "Sample25";
		z25.pageCount = 35.0;
		z25.price = 35.0;
		z25.isHardCover = false;
		z25.isAvailable = false;
		z25.manufacturingDate = "Sample25";
		z25.expiryDate = "Sample25";
		z25.bindingType = "Sample25";
		z25.size = "Sample25";
		z25.weight = 35.0;
		z25.isEcoFriendly = false;
		z25.countryOfOrigin = "Sample25";
		z25.warrantyMonths = 125;
		z25.packagingType = "Sample25";
		z25.thickness = 35.0;
		z25.isRecyclable = false;
		z25.feature1 = "Sample25";
		z25.feature2 = "Sample25";
		z25.feature3 = "Sample25";
		z25.hasBookmark = false;
		z25.hasElasticBand = false;
		z25.rating = 125;

		System.out.println("----- ZenNotebook 25 -----");
		System.out.println("productId: " + z25.productId);
		System.out.println("brandName: " + z25.brandName);
		System.out.println("paperType: " + z25.paperType);
		System.out.println("color: " + z25.color);
		System.out.println("pageCount: " + z25.pageCount);
		System.out.println("price: " + z25.price);
		System.out.println("isHardCover: " + z25.isHardCover);
		System.out.println("isAvailable: " + z25.isAvailable);
		System.out.println("manufacturingDate: " + z25.manufacturingDate);
		System.out.println("expiryDate: " + z25.expiryDate);
		System.out.println("bindingType: " + z25.bindingType);
		System.out.println("size: " + z25.size);
		System.out.println("weight: " + z25.weight);
		System.out.println("isEcoFriendly: " + z25.isEcoFriendly);
		System.out.println("countryOfOrigin: " + z25.countryOfOrigin);
		System.out.println("warrantyMonths: " + z25.warrantyMonths);
		System.out.println("packagingType: " + z25.packagingType);
		System.out.println("thickness: " + z25.thickness);
		System.out.println("isRecyclable: " + z25.isRecyclable);
		System.out.println("feature1: " + z25.feature1);
		System.out.println("feature2: " + z25.feature2);
		System.out.println("feature3: " + z25.feature3);
		System.out.println("hasBookmark: " + z25.hasBookmark);
		System.out.println("hasElasticBand: " + z25.hasElasticBand);
		System.out.println("rating: " + z25.rating);


	}
}

	