class ZomatoExecutor{
	public static void main(String[] food){
		String foodName = "Masala Dosa";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Masala Dosa";
		int quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Paneer Butter Masala";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Paneer Butter Masala";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Veg Biryan";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Veg Biryan";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Chicken Biryani";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Chicken Biryani";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Mutton Rogan Josh";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Mutton Rogan Josh";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Gobi Manchurian";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Gobi Manchurian";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Idli Sambar";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Idli Sambar";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Butter Naan";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Butter Naan";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Palak Paneer";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Palak Paneer";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Veg Fried Rice";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Veg Fried Rice";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Chicken Tikka";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Chicken Tikka";
		quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Chole Bhature";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Chole Bhature";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Pani Puri";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Pani Puri";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Samosa Chaat";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Samosa Chaat";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Margherita Pizza";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Margherita Pizza";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Veg Burger";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Veg Burger";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "French Fries";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "French Fries";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Tomato Soup";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Tomato Soup";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Ice Cream Sundae";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Ice Cream Sundae";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Chocolate Brownie";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Chocolate Brownie";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Mango Milkshake";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Mango Milkshake";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Rava Dosa";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Rava Dosa";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Mysore Pak";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Mysore Pak";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Kaju Katli";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Kaju Katli";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Rasmalai";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Rasmalai";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Gulab Jamun";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Gulab Jamun";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Jalebi";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Jalebi";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Dal Tadka";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Dal Tadka";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Jeera Rice";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Jeera Rice";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Veg Pulao";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Veg Pulao";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Hyderabadi Biryani";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Hyderabadi Biryani";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Tandoori Roti";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Tandoori Roti";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Malai Kofta";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Malai Kofta";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Aloo Paratha";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Aloo Paratha";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Pav Bhaji";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Pav Bhaji";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Vada Pav";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Vada Pav";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Dahi Puri";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Dahi Puri";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Sev Puri";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Sev Puri";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Hakka Noodles";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Hakka Noodles";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Schezwan Rice";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Schezwan Rice";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Chicken 65";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Chicken 65";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Fish Fry";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Fish Fry";
		quantity =1;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Prawn Curry";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Prawn Curry";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Egg Curry";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Egg Curry";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Lemon Rice";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Lemon Rice";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Curd Rice";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Curd Rice";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Tamarind Rice";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Tamarind Rice";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Veg Manchow Soup";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Veg Manchow Soup";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Sweet Corn Soup";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Sweet Corn Soup";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Hot and Sour Soup";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Hot and Sour Soup";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Paneer Tikka";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Paneer Tikka";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Chicken Lollipop";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Chicken Lollipop";
		quantity =6;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Veg Spring Roll";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Veg Spring Roll";
		quantity =3;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Cheese Sandwich";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Cheese Sandwich";
		quantity =4;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Club Sandwich";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Club Sandwich";
		quantity =2;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
		foodName = "Garlic Bread";
		System.out.println("The price of " + foodName + " is "+ Zomato.search(foodName));
		foodName = "Garlic Bread";
		quantity =5;
		System.out.println("The price of " + foodName + " for "+ quantity+" is "+ Zomato.search(foodName,quantity));
	}
}